### ISSUE TITLE
Nested array in group

### ISSUE THREAD

**Issue by MahmoudAwwad94** [ng-select/ng-select#1000]
First of all i want to thank you guys for this library and i just wondering if this behavior is achievable through ng-select
### Expected behaviour
if i have a array and nested array lets say project and sub projects and i want to group the sub projects based on the projects that belong to it and i should be able to choose a project or project and sub project and show it in the label can we achieve this behavior in ng-select 

the JSON data for the ng-select will look like that 
```json
[{
  "ID": 1,
  "PROJECT_NAME": "My test project",
  "PROJECT_NAME2": "my project 2",
  "STATUS_DATE": "THURSDAY",
  "CHILD_PROJECTS": [{
      "ID": 2,
      "NAME": "My child Project",
      "NAME_2": "My child Project",
      "STATUS": 2,
      "STATUS_DESC": "child",
      "PRJ_COLOR": null,
      "CREATED_BY": "test1",
      "CREATION_DATE": null,
      "MODIFIED_BY": "test1",
      "MODIFICATION_DATE": null
    },
    {
      "ID": 3,
      "NAME": "child Project2",
      "NAME_2": "child Project2",
      "STATUS": 2,
      "STATUS_DESC": "child2",
      "PRJ_COLOR": null,
      "CREATED_BY": "test2",
      "CREATION_DATE": null,
      "MODIFIED_BY": "test2",
      "MODIFICATION_DATE": null
    }
  ]

}]
```

**Comment by anjmao** [comment]
Hi @MahmoudAwwad94, currently it is not supported and there is feature request for that https://github.com/ng-select/ng-select/issues/186

You could flatten you data and pass groupBy for ng-select. Example https://ng-select.github.io/ng-select#/grouping.
