### ISSUE TITLE
Reactive forms selection come without items data

### ISSUE THREAD

**Issue by kamlesh0606** [ng-select/ng-select#1001]
Hi,

I using Reactive forms. Some items data update but selection is not remove.

Following Way To Update items data ?
- Master base items 
- Depended Drop-down menu. Like country to state to city.
- Dynamical items data update.

Please Help for above problem.

i need to remove selection if items data not exist . If again items data comes then again select old value.

Thanks

**Comment by anjmao** [comment]
Hi @kamlesh0606, it realy hard to help you without example showing your problem, could you please create a stackblitz demo showing this bug?

**Comment by varnastadeus** [comment]
closing as inactive
