### ISSUE TITLE
How to detect the actions that add or remove items? for ng-select version 0.25

### ISSUE THREAD

**Issue by jeseel** [ng-select/ng-select#1003]
Hi guys,

I am my project is using an angular (4.4.3) old version that the reason that I need for that select version.
How I handle before add or remove an item? I would like to do some validation after adding an item.

**Comment by varnastadeus** [comment]
I am not sure which events are present in that version, but you should use (add) or (change) events. Also use new version for latest features and bug fixes since we don't support old ones.
