### ISSUE TITLE
FormArray Ng-Select

### ISSUE THREAD

**Issue by elvispdosreis** [ng-select/ng-select#1010]
I have a form bound by a formArray using the ng-select typeahead, however the ng-select triggers several asyn one for each element of the formArray has to inhibit to make only one request

**Comment by varnastadeus** [comment]
you can check example in this issue https://github.com/ng-select/ng-select/issues/993, there shouldn't be multiple requests

**Comment by elvispdosreis** [comment]
I create a test example, I need an array object to be connected directly as formcontrol

https://stackblitz.com/edit/angular-gxgrxs

however if you observe the log console it triggers several request

**Comment by varnastadeus** [comment]
It is because you are using single subject with multiple subscriptions. You can use rxjs `share` operator to share source among multiple subscribers

```ts
this.list$ =

      concat(of(this.category), this.listInput$.pipe(
        debounceTime(800),
        distinctUntilChanged(),
        switchMap((term) => {
          console.log('request');
          return this.getCategory(term);
        })
      )).pipe(share())
```

**Comment by elvispdosreis** [comment]
Thank you worked out prefectly, sorry for the problem, it was only a rxjs configuration

**Comment by suhailvs** [comment]
solved my problem. you can import share from rxjs/operators

    import { share } from 'rxjs/operators';
