### ISSUE TITLE
Long Text

### ISSUE THREAD

**Issue by elvispdosreis** [ng-select/ng-select#1011]
I some case my ng-select I need to display long text, some solution to display this text in an elegant way

[sample](https://stackblitz.com/edit/ng-select-reactive-form-long-text)

ng-select version: 2.13.3
reproducible in demo page: yes

**Comment by varnastadeus** [comment]
- use title or tooltip
- wrap text and have bigger options to fit text

**Comment by paugp** [comment]
Override css to word break into labels.
`.ng-dropdown-panel .ng-dropdown-panel-items .ng-option {
 white-space: break-spaces;
}`
