### ISSUE TITLE
Autofill possible?

### ISSUE THREAD

**Issue by zaspen** [ng-select/ng-select#1012]
I assume the answer is no, but I thought I'd ask the experts. Is there anyway for this control to work with browser autofill?

My specific use case is having ng-select show a list of states as part of an address form. Chrome prompts me to autofill the address and the state is the only field not filled.

Thanks for any advice, ideas, or feedback.

**Comment by anjmao** [comment]
Hi @zaspen, does it work if you change ng-select to native html select?
