### ISSUE TITLE
ng-select should not show dropdown list on click 

### ISSUE THREAD

**Issue by neerajknextgen** [ng-select/ng-select#1013]
**Is your feature request related to a problem? Please describe.**
I want to it to behave like autocomplete multiselect textbox. It should not show list on click. List should come only on search.

**Describe the solution you'd like**
Some property binding which have option to enable and disable the list opening on click

**Describe alternatives you've considered**

**Additional context**

**Comment by varnastadeus** [comment]
if there are items preloaded then it shows them, if not it shows `type to search` message. If you want to see the message every time you open dropdown, then clear your [items] array on close.
