### ISSUE TITLE
Add examples about how to test ng-select

### ISSUE THREAD

**Issue by FrancescoBorzi** [ng-select/ng-select#1014]
**Is your feature request related to a problem? Please describe.**
I'm trying to test some very simple use-cases of ng-select but I'm failing, for example this is what I'm trying to accomplish: https://stackoverflow.com/questions/54037484/how-to-test-ng-select-inside-a-reactive-form

**Describe the solution you'd like**
Add some examples in the documentation about how to test ng-select using [Angular Component DOM Testing](https://angular.io/guide/testing#component-dom-testing)

**Comment by varnastadeus** [comment]
there is 200+ tests in the repo, just look there and pick which one fits best

**Comment by FrancescoBorzi** [comment]
@varnastadeus can you please point some meaningful ones ? mostly using `ng-select` as a whole component, not the ones which test the internals

**Comment by varnastadeus** [comment]
all tests uses ng-select as component, simulating selection, opening and etc

**Comment by FrancescoBorzi** [comment]
do I have to look at this list? https://github.com/ng-select/ng-select/tree/master/src/ng-select

**Comment by varnastadeus** [comment]
*.spec.ts files
