### ISSUE TITLE
Best way to extend ng-select?

### ISSUE THREAD

**Issue by gaspardip** [ng-select/ng-select#1015]
Hi, I found myself in the need to extend the functionality of ng-select to include some business logic and I don't want to repeat the business code every time. 

So I was wondering what is the best way to extend ng-select? I went with the "wrap in another component" route, but this forced me to support a lot of `Input()` and `Outputs()` myself, which is not ideal. 

I tried to extend the NgSelectComponent class itself, but for some reason angular or ts couldn't find the module `console.service` (when forwarding the constructor params to `super()`)

**Comment by anjmao** [comment]
Hi @gaspardip, actually wrapping it inside another component would be the best and easiest idea.

**Comment by gaspardip** [comment]
Oh I thought I did something wrong or there was a better way. Nevermind then, thank you.
