### ISSUE TITLE
Is it possible for treeview concepts?

### ISSUE THREAD

**Issue by raghulrajnkl** [ng-select/ng-select#1016]
Please fill below information if issuing a bug report. 
### Expected behaviour
Thanks for your efforts its very useful things
I expected, dropdown treeview options, (ngx-treeview) 

### Actual behaviour
Actual current grouping support only one groups, i expect infintive group one under one

### More Info
ng-select version: 2.13

browser: All

reproducible in demo page: [YES/NO] YES

**Comment by anjmao** [comment]
Hi @raghulrajnkl, there is no support for such complex treeview. It would be overkill for a select component :)
