### ISSUE TITLE
ng-select does not update search results correctly.

### ISSUE THREAD

**Issue by phristov** [ng-select/ng-select#1019]
Go to [link](https://stackblitz.com/edit/ng-select-bpqvh8?file=app/app.component.ts).

Type `Las` , and you will see `Last, Test`.
Add `a` to the end: `Lasa`, and you will see an empty array.

Go to dependencies, and click update all to latest.
Type `Las` , and you will see `Last, Test`.
Add `a` to the end: `Lasa`, and you will see again `Last, Test`. It should be an empty array.

The provided example is taken from the tutorial **Custom server-side search** 
ver 2.1.0 works correctly 
ver 2.14.0 does not work correctly

**Comment by chimmi** [comment]
I`m having the same issue. I just wanted to add that if you use select like this:

`<ng-select [items]="data.data" [(ngModel)]="client.test" #test="ngModel" id="test" name="test" bindLabel="lastName" bindValue="personId"></ng-select>`

in the provided example, it works.
