### ISSUE TITLE
Multi select change event

### ISSUE THREAD

**Issue by Goonersid** [ng-select/ng-select#102]
Hi, I have a query... I have a custom auto complete implementation on multi select. I'm noticing the following behaviour for change event.. When we just type in something random and click outside the select box, it correctly clears out the text in the input , but also fires the change event. Is it  necessary to fire the change event in this case as no tag was added or dropped.

**Comment by Goonersid** [comment]
Might be related to #91

**Comment by Goonersid** [comment]
@anjmao any update on this??

**Comment by anjmao** [comment]
@Goonersid That is a good catch! It should not fire change event on this case. I hope I will fix it this week :)
