### ISSUE TITLE
How can this be used inside for loop? 

### ISSUE THREAD

**Issue by ratiuandreea** [ng-select/ng-select#1024]
I have to loop through an array and create input for each element in array. The problem is that whenever I search for something in one input, all the other inputs load data. Hundreds of request are fired.
I tried to use this on (search) event but there is no way to concat the data. 
And I cannot see a viable way to use loading while searching only in one input. 
Is this doable?

**Comment by varnastadeus** [comment]
check this issue https://github.com/ng-select/ng-select/issues/1010

**Comment by ratiuandreea** [comment]
Is there an example with loading for each input?

**Comment by varnastadeus** [comment]
this should be handled same as any other control, each of your item should contain state of each own
