### ISSUE TITLE
Allow grouping to be collapsible/expandable

### ISSUE THREAD

**Issue by tosehee75** [ng-select/ng-select#1025]
Maybe this feature already exists, but is it possible to have grouping be expandable and collapsable?

I have a large list (close to 1000), and by grouping, they are roughly 100 each. So, I have 10 groups that contains 100 elements each.

I'd like to start off with them being a collapsed. Then, when I select them, it expands to show the elements.

**Comment by nealyip** [comment]
I just came across this issue.  In my case, the list will grow by the growth of the business.

**Comment by shijoshaji** [comment]
i feel this feature will benefits with large number of data

**Comment by LunaSquee** [comment]
My project would also greatly benefit from this feature. Please reopen

**Comment by pantekx3** [comment]
Any update on this? It is a really must-have feature

**Comment by tballast** [comment]
Would also love to have this!

**Comment by HemantL9** [comment]
Has this been resolved or not?
