### ISSUE TITLE
please remove inline styles in ng-select.component.ts

### ISSUE THREAD

**Issue by steve3d** [ng-select/ng-select#1028]
well, this might be a feature but also a problem.

currently you load the inline styles in `ng-select.component.ts`, which works of course, but it also make it not possible if  I want to override some style in `ng-select.component.scss`, because angular works this way, the inline styles are always loaded in the last section of `head` element.

so any global styles is loaded before the styles in `ng-select.component.scss`, then it's not possible to override anything in it.

So I'm asking is it possible to remove this inline styles and move all styles into theme scss?

**Comment by steve3d** [comment]
@varnastadeus, can not believe this is your solution, **increase css specificity** basically means I need to use more specific css select path, which last part, under `ng-select` element can not be changed, then the only part can change is it's parents elements.

then I currently have about 20-30 use case, so I need to write each instance a more  **specific** select path to make a common style change. so what if I have more like 100 use case?

so by my understanding, you are suggesting that I can only override a style for each/every instance of ng-select to override a common style?

**Comment by steve3d** [comment]
well, there is another way, which is add a class to `ng-select`, but in order to change a common style, I still have to add a class to every `ng-select` element.

still this is not a best solution.

**Comment by varnastadeus** [comment]
ng-select.component styles include general things like `position`, `display` and other common things which makes it easier applying custom theme without worrying about layout itself. What are you trying to override since usually you shouldn't do changes there?

**Comment by steve3d** [comment]
sorry, finally, I found this is my problem.
