### ISSUE TITLE
Custom html ID for ng-option

### ISSUE THREAD

**Issue by aphairpq2** [ng-select/ng-select#1031]
**Is your feature request related to a problem? Please describe.**
To make automated end-to-end tests easier, we would like to be able to target an ng-option by id or similar html attribute. Currently, this id appears to be auto-generated and random, ex:
```
<div class="ng-option ng-star-inserted" role="option" aria-selected="false" id="afe5112c5617">
   someValue
</div>
```

**Describe the solution you'd like**
An input property or other mechanism to specify what the ng-option id should be.

**Describe alternatives you've considered**
We have tried a custom ng-option template, which sort-of works but results in an additional container (one for the generated div and one for whatever we put in the custom template). Ideally, we don't want to have to specify a custom template just for an id. Example:
```
<div class="ng-option ng-option-marked ng-star-inserted" role="option" aria-selected="false" id="ab3eb8bf401c">
   <div id="whatIWantTheIDToBe" class="ng-star-inserted">
      someValue
   </div>
</div>
```

**Comment by varnastadeus** [comment]
why not just using indexes? Those ids are used for accessibility

**Comment by aphairpq2** [comment]
@varnastadeus The items in the dropdown box are dynamic, so I'm not sure we could use indexes reliably. Selecting by text will work - but the selectors are quite long, we were trying to make things simpler by using an id. 

Do you have an example of one of your selectors used in your tests? Maybe we are going about it the incorrect way.

Thanks!

**Comment by varnastadeus** [comment]
it is fairly simple if you are using protractor

```ts
selectOption(label: string) {
        element(by.css('[data-test-id="my-ng-select"]')).click(); //opens dropdown
        element(by.cssContainingText('span.ng-option-label', label)).click(); // selects option by provided text
    }
```

**Comment by aphairpq2** [comment]
We are currently using Selenium, but I'm sure it will be very similar. I'll speak with our QA tester and let them know about your suggestion. Thank you again!
