### ISSUE TITLE
Select duplicates.

### ISSUE THREAD

**Issue by Serg-Mois** [ng-select/ng-select#1032]
The ability to select the same item twice, when multiple mode is enabled. 
For now if hideSelected options is false -  alredy selected items shown in bold style, and on click - item is unselected.

**Comment by Serg-Mois** [comment]
Looks like:

 compareWith(optionValue: any, modelValue: any): boolean {
     return false;  
}
should resolve that. I'm correct?

**Comment by varnastadeus** [comment]
yes, if value can't be resolved automatically based on bindLabel/bindValue then you should provide your custom compare function
