### ISSUE TITLE
Class attribute not being applied correctly

### ISSUE THREAD

**Issue by seanbotha123** [ng-select/ng-select#1035]
**Describe the bug**
_class_ attribute gets applied to `ng-select` tag as well as `ng-dropdown-panel`. This makes it very diffucult to apply bootstrap styling as I need to apply only `form-control` class to the select component, and not the child components.

**Reproducbile example**
Please see images below:
![screenshot from 2019-01-31 08-20-30](https://user-images.githubusercontent.com/5496698/52034705-a138f300-2531-11e9-8565-5732c1689a82.png)
![screenshot from 2019-01-31 08-17-07](https://user-images.githubusercontent.com/5496698/52034708-a302b680-2531-11e9-85a7-c3a774f295bc.png)

**Expected behavior**
The class should only be applied to the `ng-select` tag, as this is where it is being set.

**Desktop (please complete the following information):**
- Operating system and version: Ubuntu 18.04.1 LTS
- Browser and version: Chrome 70.0.3538.77

Thanks!

**Comment by certainlyakey** [comment]
I believe the resolution of this issue introduces another serious issue as described in #1208. Basically we're unable to change styles on `.ng-dropdown-panel` when `appendTo="body"` is used since custom classes are not transferred anymore to the panel. Please consider reverting it.
