### ISSUE TITLE
Difference between let-item="item" and let-item$="item$" ?

### ISSUE THREAD

**Issue by jziggas** [ng-select/ng-select#1038]
I can't seem to find an explanation anywhere in the demo documentation, but both of these are used in the demo for a multiselect checkbox. I'm having trouble getting a selected value to show up as checked and wondering if I am incorrectly using these two variables. Thanks.

**Comment by varnastadeus** [comment]
`item` represents your value which you provide in `[items]` array and `$item` is internal which has additional properties like _selected, marked_ etc

**Comment by aldo-jimenez** [comment]
I'm using Angular 5, and using item$ gives me error when using ng-option tmp

``        <ng-template ng-option-tmp let-item="item" let-item$="item$" let-index="index">
            <input id="item-{{index}}" name="item-{{index}}" type="checkbox" [ngModel]="item.selected"/> &nbsp; &nbsp;{{item.name}}
          </ng-template>
