### ISSUE TITLE
editing selected element

### ISSUE THREAD

**Issue by lukas728912** [ng-select/ng-select#1039]
Hello,

is there any way that the user can edit the selected element of the ng-select? like a normal textfield?

thank you

**Comment by varnastadeus** [comment]
since you can put your custom template for selected items, then yes it is possible

**Comment by varnastadeus** [comment]
you are right, some of events propagation is stopped which doesn't allow you to select input

**Comment by varnastadeus** [comment]
closing in favor of #1169

**Comment by dembrovszky** [comment]
[editableSearchTerm]="true"
            [multiple]="false"
