### ISSUE TITLE
Add feature: Disable single option within ng-select

### ISSUE THREAD

**Issue by gongAll** [ng-select/ng-select#1046]
I have an ng-select element where I would like to be able to disable the selection of a given option, whenever I want.

```
<ng-select [items]="comboboxElements"
           [bindValue]="comboboxElements['value']"
           dropdownPosition="bottom"
           virtualScroll="true"
           [ngModel]="active"
           (ngModelChange)="activeChange.emit($event)"
           (change)="onChange($event)">

    <ng-template ng-label-tmp
                 let-item="item">
        {{item.labelKey | translate}}
    </ng-template>

    <ng-template ng-option-tmp
                 let-item="item">
        {{ item.labelKey | translate }}
    </ng-template>
</ng-select>
```

I believe this feature would make sense to be available inside the ng-option-tmp, as so:
```
    <ng-template ng-option-tmp
                 [disabled]="item.disabled"
                 let-item="item">
        {{ item.labelKey | translate }}
    </ng-template>
```

**Comment by gongAll** [comment]
Sorry for the late update.

For whoever may concern, all I had to do on the .ts file was:

``
this.comboboxElements[0].disabled = true;
``

I believe this property should be documented, as I believe it is not very clear it exists.

**Comment by vladyour** [comment]
Hi @gongAll,
Are you sure if it works?
When I code `<ng-template ng-option-tmp [disabled]="itemIsDisabled(item)" ...`, I see error in console:
`Uncaught Error: Template parse errors:
Can't bind to 'disabled' since it isn't a known property of 'ng-template'.`

**Comment by gongAll** [comment]
Instead, add a 'disabled: boolean' attribute to the object you're using to fill the table, as such: 
**html**
```
<ng-select [items]="someRandomItems">
</ng-select>
```

**ts**
```
...
public someRandomItems: SomeRandomModel[] = [];
...
export class SomeRandomModel {
  ... your attributes ...
  public disabled = false;
}
```

**Comment by vladyour** [comment]
Wow! It works! Thank you!

**Comment by FarizF** [comment]
Is this also possible with the 2.20.0 version of ng-select? I'm trying to assign the attribute to the ng-option element/component, but can't get the option to be disabled. I've also tried adding the attribute to the model, without success.

**Comment by loverzpark** [comment]
[disable] is not working for directive **ng-option-tmp**

**Comment by gongAll** [comment]
@loverzpark maybe read the entire conversation? It's not a bindable attribute, it's an attribute inside each element of the list.
