### ISSUE TITLE
Multi select checkbox custom style , on click of label not checked.

### ISSUE THREAD

**Issue by Amarnath92** [ng-select/ng-select#1048]
Hi,

When i am trying to add some custom styles to change the checkbox,(let's say i using bootstrap,psudo elements to styling) multi select checkbox, on click of the label or checkbox value is not binding to the provided object in [(ngModel)] , with the ng-select component, i wrapped the checkbox and label with a div, on click of that particular div its getting selected and binding to the object as well.

Could someone provide your input on the same?

Please find the below code:

<ng-select class="custom" [items]="users.data" [multiple]="true" [closeOnSelect]="false" 
         placeholder="Search User"
           autofocus [(ngModel)]="user">
	<ng-template ng-label-tmp let-item="clear"></ng-template>
	<ng-template ng-option-tmp let-item="item" let-index="index" let-item$="item$">
		<div class="custom-control custom-checkbox">
			<input id="item-{{item$.value}}" type="checkbox" [ngModel]="item$.selected" 
                         class="custom-control-input" [checked]="item$.selected"/>
			<label class="form-check-label ml-2 custom-control-label"
                  for="item-{{item$.value}}">{{item}}</label>
		</div>
	</ng-template>
</ng-select>

Added to this ticket please give some suggestion to make ng-label-tmp empty, means when i am selecting the options the label should not get appended with any values. it should always shows the placeholder or some fixed label text.

**Comment by ashu07** [comment]
> Even I am facing a problem when using bootstrap checkbox classes to style the checkbox of multi-select. 
> The click on checkbox and label doesn't select/unselect the element but when clicking on the div do the work.

How to handle this situation to select/unselect on click on checkbox/ label?


@varnastadeus Any suggestion?

**Comment by varnastadeus** [comment]
create reproducible example

**Comment by ashu07** [comment]
> When you click on item options div element, it works fine but on clicking checkbox/label, it is not binded with the selected values. and here item$ is also not working. check the working demo.

[https://stackblitz.com/edit/ng-select-5ueycm](url)

**Comment by ashu07** [comment]
@varnastadeus Can you create a working example as it doesn't work for me with the same use case.

**Comment by varnastadeus** [comment]
https://stackblitz.com/edit/ng-select-tr6kpy?file=app/app.component.ts. Here it is, note that I updated dependencies to use latest ng-select version

**Comment by ashu07** [comment]
Thanks! This works fine.

**Comment by nestok** [comment]
@varnastadeus Seems like select on label and input still doesn't work when label has 'for' property for input id

**Comment by ezequiel88** [comment]
Não sei se ainda persiste o problema mas modificando a linha abaixo fica funcionando bem.

<ng-template ng-multi-label-tmp>**{{selectedUser}}**</ng-template>

**Comment by Saqib92** [comment]
> I am not sure why are you trying to bind label with checkbox inside dropdown or using label in the first place but below solution works
> 
> ```
> <ng-template ng-option-tmp let-item="item" let-index="index" let-item$="item$">
>     <div class="custom-control custom-checkbox">
>         <input type="checkbox" [ngModel]="item$.selected" class="custom-control-input"/>
>         <label class="form-check-label ml-2 custom-control-label">{{item}}</label>
>     </div>
> </ng-template>
> ```

How can I change `Color` on selected item? currently it is in black. i want to highlight text if selected.
