### ISSUE TITLE
ng-select binding content doesn't reflect to multiple dropdown

### ISSUE THREAD

**Issue by chetanladdha** [ng-select/ng-select#1049]
I have multiple ng-select dropdowns using same [items] array.
If someone selected something in the first dropdown, I want to disable selected item in other dropdowns.

**Issue:**
Even setting new items array with new content with disabled=true, its not able to understand it.

https://stackblitz.com/edit/ng-select-uym4ip is where I have reproduced an issue.

**Comment by varnastadeus** [comment]
check the issues, there was similar question before

**Comment by chetanladdha** [comment]
I have gone through the open and close issues, couldn't find similar situation problem.
I found below issues related but I couldn't find any solution out of them.

https://github.com/ng-select/ng-select/issues/866
https://github.com/ng-select/ng-select/issues/736
https://github.com/ng-select/ng-select/issues/313

Is it a bug? Or I am doing anything wrong? Any workaround? 
I need to add multiple dropdowns as and when required with same items array.

**Comment by varnastadeus** [comment]
you need to mutate your are
https://github.com/ng-select/ng-select#change-detection

**Comment by chetanladdha** [comment]
Thanks, Yes, an item doesn't mutate if you assign that value.

Assigning it to null and coping it works.
