### ISSUE TITLE
multiselect dropdown location does not move when selected items causes a new row to be added

### ISSUE THREAD

**Issue by Alexolo** [ng-select/ng-select#1050]
When adding more items then fit on one row, a second row is added. When this happens the dropdown box does not move with the bottom of the selected items input field.

```
<ng-select class="form-control"
[multiple]="true" 
[searchable]="false"
[hideSelected]="true" 
[closeOnSelect]="false" 
[(ngModel)]="p"
[items]="f" 
appendTo="body"
bindLabel="name">
</ng-select>

```

![image](https://user-images.githubusercontent.com/5850852/52424658-b944df80-2afa-11e9-8ff7-5b13a7ccb5c8.png)

**Comment by varnastadeus** [comment]
dup of #984
