### ISSUE TITLE
dropdown is slow in IE11

### ISSUE THREAD

**Issue by aniltomar10** [ng-select/ng-select#1051]
I am using this dropdown in angular 6 web application. everything is fine in google chrome but in IE11 dropdown open, search, value selection actions shows delay of 2-4 seconds. 
for example if I click on dropdown to see values, nothing happen for like 2-4 seconds and then it opens.
I have only 2000 records in dropdown and there is no other control with more than 100 records in my web page.

**Comment by varnastadeus** [comment]
rendering 2000 elements in DOM is a lot, and you should avoid it by any means. You should use [virtualScroll] for that
