### ISSUE TITLE
text.replace is not a function error when use [ngOptionHighlight]="search"

### ISSUE THREAD

**Issue by Denis-Evseev** [ng-select/ng-select#1052]
I am using ng-select with dynamic items (load items from API). Items, which I receive is just an array of objects that have only 3 properties: Id, Name, Group. BindValue and BindLabel set to Name property.
Name contains values in Russian language

This is the code, which I use to ng-select dropdown list:
```
<ng-select [items]="fastSearchResult"
        [multiple]="true" [(ngModel)]="fastSearchObj.search" (search)='fastSearchChanged($event)'
        groupBy="group" bindLabel="Name" bindValue="Name"
        class="form-control keyword"
        placeholder="Быстрый поиск вуза, спец-ти ">
    <ng-template ng-optgroup-tmp let-item="item">
          <div>{{ item.group }}</div>
     </ng-template>
      <ng-template ng-option-tmp let-item="item">
           <div [ngOptionHighlight]="search" class="fs-13 ml-1 lh-20">{{ item.Name }}</div>
       </ng-template>
</ng-select>
```

Be aware that I use Subjects to trigger a moment when a user stopped typing and send a request to API
Each time when ng-select receives a result it shows an error:

> text.replace is not a function
>     at stripSpecialChars (ng-select.js:1056)

Inside of this function: 
```
function stripSpecialChars(text) {
    /** @type {?} */
    var match = function (a) {
        return diacritics[a] || a;
    };
    return text.replace(/[^\u0000-\u007E]/g, match);
}
```

Could you please advise what i need to do to resolve the issue? 
Can the Russian language be a problem? It used to work in AngularJS

Many thanks

**Comment by varnastadeus** [comment]
can you create simple reproducible example?

**Comment by ComsatArchitects** [comment]
Also getting this function error, but triggered when hitting any key on the keyboard while a dropdown with option groups is open and searching is disabled:

```
There was a Type error:
 TypeError: text.replace is not a function
    at stripSpecialChars (ng-select.js:1056)
    at ng-select.js:1306
    at Array.find (<anonymous>)
    at ItemsList.push../node_modules/@ng-select/ng-select/fesm5/ng-select.js.ItemsList.findByLabel (ng-select.js:1304)
    at SafeSubscriber._next (ng-select.js:3352)
    at SafeSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub (Subscriber.js:194)
    at SafeSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next (Subscriber.js:132)
    at Subscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next (Subscriber.js:76)
    at Subscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (Subscriber.js:53)
    at MapSubscriber.push../node_modules/rxjs/_esm5/internal/operators/map.js.MapSubscriber._next (map.js:41)
```

**Comment by ComsatArchitects** [comment]
Any updates on this?

**Comment by ComsatArchitects** [comment]
To reproduce - have a ng-select that is not searchable, but type a letter anyway when it's open.

I typed "d" and the first time through it called function stripSpecialChars('d') on line 1064 of ng-select.js

The function ran again but for some reason it called stripSpecialChars(false) and it threw the error, not knowing how to deal with "false" as an input.

**Comment by Khokhlachov** [comment]
@Denis-Evseev  your "group" in `groupBy="group"` is numbers and error in https://www.screencast.com/t/Jk3tJCk2  need map your "group" value to string
