### ISSUE TITLE
Unresponsive select when using Array.filter()

### ISSUE THREAD

**Issue by chrispickford** [ng-select/ng-select#1053]
**Description**
When binding an `ng-select` component to to result of an `Array.filter()` call the select options become unresponsive.

**Reproducible example**
[StackBlitz Example](https://stackblitz.com/edit/ng-select-array-filter-issue) reproduces described behaviour. Attempting to choose an option from the select list causes the app to freeze.

**Expected behaviour**
The select behaves as normal, with the chosen option becoming selected.

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 72

**Comment by varnastadeus** [comment]
this is related to #777 and there is not much we can do now, just don't mutate your array in getter
