### ISSUE TITLE
Validation on submit

### ISSUE THREAD

**Issue by florianislitzer** [ng-select/ng-select#1055]
Hi,
When ng-select is not touched and I submit the form no invalid-class is added.
Is there a way to listen to the parent submit and add a custom error class?

**Comment by varnastadeus** [comment]
if there is no required attribute there is nothing to validate thats why you get no invalid-class is added. Just add the attribute

**Comment by florianislitzer** [comment]
@varnastadeus I added the required attribute and the invalid is added when I touch the select component, when it´s not touched and i submit the form nothing happens - should that work?

**Comment by varnastadeus** [comment]
There is example in demo with required example. https://angular.io/guide/form-validation I think this should answer all your questions

**Comment by babupca** [comment]
@florianislitzer,
I'm also getting the same problem in angular 6. Could you please share the fix for me. thank you. 
On Submit it is not hilighted in red, but when i touch it is highlighted in red.

**Comment by florianislitzer** [comment]
@babupca We decided to highlight it as long as it is invalid, no matter if it´s touched or submitted, found no other way.

**Comment by babupca** [comment]
@florianislitzer , 

oh in that case when the form loaded, that time itself it will be highlighted in red, which is not good. :(

Ok i'm searching for some other solution, if any thing i will also update you . 

thank you

**Comment by florianislitzer** [comment]
@babupca yes it´s not good but we thought users would understand that better than no highlighting.
Would be great if you inform me about any updates!

**Comment by azollai** [comment]
It is really annoying to me, too.
E.g. I put ng-select it into a modal. I make some changes, so it triggers validation. I close, reset the form, and reopen the modal. And the invalid class appears. 
It really DOES NOT help users to understand the working of the select. Please make it customizable (by the form's touched attribute)
Thank you.

**Comment by azollai** [comment]
@babupca and everyone in the future who reads it:
Workaround:
 -  you define the default border-color and box-shadow
`  ng-select .ng-select-container {
    border-color: #ccc;
    box-shadow: none;
  }

  ng-select.ng-invalid .ng-select-container {
    border-color: #f4516c;
    box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 0 3px #fde6e8;
  }`
 -  then in your code you can add/remove the ng-invalid class: 
`this.ngSelect.element.classList.add('ng-invalid');`
`this.ngSelect-element.classList.remove('ng-invalid');`

also you have to get the templatereference by ViewChild
`@ViewChild(NgSelectComponent) ngSelect: NgSelectComponent;`

**Comment by ayaz76** [comment]
<div class="form-group mb-3 tg-inputwithicon"
                      [ngClass]="{ 'has-error': fstep1.submitted && sub_category_id.invalid }">
                      <label class="control-label">{{'CardPost.subCategory' | translate}}<span
                          class="asterisc">*</span></label>
                      <div class="tg-select form-control">
                        

                        <ng-select [items]="subCategories" [multiple]="true" [closeOnSelect]="true" bindLabel="name"
                          bindValue="id" required placeholder="{{'CardPost.selectSubCategory' | translate}}"
                          [(ngModel)]="model.selectedsubCategoriesIds" id="sub_category_id" name="sub_category_id"
                          #sub_category_id="ngModel">
                          <ng-template ng-multi-label-tmp let-items="items" let-clear="clear">
                            <div class="ng-value" *ngFor="let item of (items ? items.slice(0,2): [])">
                              <span class="ng-value-label"> {{item.name}}</span>
                              <span class="ng-value-icon right" (click)="clear(item)" aria-hidden="true">×</span>
                            </div>
                            <div class="ng-value" *ngIf="items.length > 2">
                              <span class="ng-value-label">{{items.length - 2}} more...</span>
                            </div>
                          </ng-template>
                        </ng-select>
                        <div *ngIf="fstep1.submitted && sub_category_id.invalid" class="help-block">
                          <div *ngIf="sub_category_id.errors.required">{{'CardPost.subcategoryMandatory' | translate}}
                          </div>
                        </div>
                      </div>


This is working example using Template driven form validation.

**Comment by sjt7911** [comment]
This is my approach:

First I set up boolean parameter in ts class file:

requiredRecipients: boolean;

 ngOnInit() {
    this.buildForm();
    this.requiredRecipients = false;
 }

private buildForm() {
    this.form = this.formBuilder.group({
      recipients: ['', [Validators.required]]
    });
}

submit() {
    if (this.onConfirm && this.form.valid) {
        // do request
    } else {
         requiredRecipients: false;
    }
}
--------------------------------------------------------------------------------------------------------------------
In ng-select component in html file add class ng-touched if submit form has false:

<ng-select class="disable-arrow disable-dropdown"
                       [class.ng-touched]="requiredRecipients"
                       formControlName="recipients">
</ng-select>

**Comment by poddarkhushbu07** [comment]
For template driven forms in angular, when first time form gets loaded, ng-select input with required attribute will be in default state (valid). But when save action is triggered it should apply invalid class to ng-select. Is there any way to achieve this?

**Comment by majedur-rahaman** [comment]
There is no build-in `required` attribute in `ng-select`. I always validate it through form validation.
In angular2 or above you can use `ng-select` with `ngNativeValidate `directive for template driven form.

```
<form #registerUser="ngForm" ngNativeValidate (ngSubmit)="onSubmit()">  

   <ng-select
    class="col-md-8 required"
    [items]="options" 
    bindLabel="label" 
    bindValue="value"
    [multiple]="true" 
    name="skills"
    placeholder="Select Skills" 
    [(ngModel)]="registerUserData.skills"                                       
    required>
</ng-select>
<div *ngIf="!registerUserData.skills" class="invalid-feedback">
    Skills are required
</div>

<button type='submit' [disabled]="!registerUser.valid" [isFormValid]="!registerUser.valid">Submit</button>

</form>
```
I am also using custom style to red mark field when `untouched `or `touched `and `invalid`. You can put it in global `scss `or `css `file to work as same all `component`.

> SCSS:

```
ng-select.required.ng-invalid.ng-touched {
    .ng-select-container{
        border-color: #dc3545;
        box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 0 3px #fde6e8;
    }
}
ng-select.required.ng-invalid.ng-untouched {
    .ng-select-container{
        border-color: #dc3545;
        box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 0 3px #fde6e8;
    }
}
```

> CSS:

```
ng-select.required.ng-invalid.ng-touched .ng-select-container{
 
    border-color: #dc3545;
    box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 0 3px #fde6e8;
}
ng-select.required.ng-invalid.ng-untouched .ng-select-container {

    border-color: #dc3545;
    box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 0 3px #fde6e8;
}
```

**Comment by evertonrivas** [comment]
Please try this solution...


```
<ng-select
                                [items]="itPaymentData"
                                bindLabel="name"
                                bindValue="id"
                                placeholder="Select a payment condition"
                                (change)="setPayment()"                                
                                required
                                formControlName="slPayment"
                                [ngClass]="{'ng-invalid': submitted && f['slPayment'].errors,'ng-touched': submitted && f['slPayment'].errors }">
                            </ng-select>
```


Declare one function called f on your ts file. Like this:

```
get f(): { [key: string]: AbstractControl } {
    return this.frmCheckout.controls;
  }
```

Declare your formCheckout as FormGroup.

**Comment by stealthAngel** [comment]
It took me some time but I solved it this way:


The result is the following:

```

<div class="row mb-3">
              <div class="col-md-12">
                <label for="companyId" class="form-label">Coimpany</label>
                <ng-select placeholder="select a company" appNgSelectWorkaroundValidator
                  formControlName="companyId" [items]="companies" bindValue="id" bindLabel="name"
                  required>
                </ng-select>
              </div>
            </div>
```
where you see that we added a `appNgSelectWorkaroundValidator` directive to the ng select.
This is what we want. 

we create a directive first.
```
import { Directive, HostBinding, Optional, Self } from '@angular/core';
import { NgControl } from '@angular/forms';

@Directive({
  selector: '[appNgSelectWorkaroundValidator]',
  standalone: true,
})
export class NgSelectWorkaroundValidator {
  constructor(@Optional() @Self() public ngControl: NgControl) {}

  @HostBinding('class.is-invalid') get isInvalid(): boolean {
    // The control is invalid and has been touched.
    return this.ngControl
      ? this.ngControl.invalid &&
          (this.ngControl.dirty || this.ngControl.touched)
      : false;
  }
}
```

we set a css globally somewhere:

```
.is-invalid {
  border: 1px solid red;
  border-radius: 4px; /* Optional, for rounded corners */
}
```

and don't forget to import the directive in your component:

```
@Component({
  selector: 'app-some-component',
  standalone: true,
  imports: [ NgSelectWorkaroundValidator],
```
