### ISSUE TITLE
Dropdown overflow hidden with bootstrap 4.2+ and accordion

### ISSUE THREAD

**Issue by achimha** [ng-select/ng-select#1057]
When placing an ng-select inside a Bootstrap accordion so that the dropdown extends beyond the size of the accordion card, the overflow is hidden starting with bootstrap 4.2. This is due to a change in their CSS which sets `overflow: hidden` for the `.card` div.

https://github.com/twbs/bootstrap/commit/fccdda544816202d1c02df673e528bb5a22f0484

<img width="117" alt="screenshot 2019-02-12 at 09 43 22" src="https://user-images.githubusercontent.com/6816140/52622661-afc8c800-2eaa-11e9-809a-6cc7bdd9666e.png">

Is this something that should be worked around in ng-select or a bootstrap bug?

**Comment by varnastadeus** [comment]
this is not a actual bug, this is how browser works and this is addressed in ng-select using `appendTo="body"`
