### ISSUE TITLE
Minimum number of characters

### ISSUE THREAD

**Issue by alissonssz** [ng-select/ng-select#1058]
Hi guys!

How can I start filter after typed 3 characters? 

PS: I want do it in front-end, no server-side search.

**More Info**

ng-select version: ^2.13.3

browser: Version 71.0.3578.98 64 bits

reproducible in demo page: [NO]

**Comment by yeddaalous** [comment]
Hi Guys,

We need this feature too.

But unfortunately we are still working with Angular 5, Could you please add a patch for ng-select 1.x ?

**Comment by anjmao** [comment]
Hi @alissonssz, could you describe why would you want to filter on client side only after some characters? It would not be user friendly.

**Comment by alissonssz** [comment]
Hi @anjmao, I need to do it to keep the same behavior through the whole application. Even when backend search is not necessary. It's a user requirement.

Do you think I can achieve that using the [typeahead] option?

**Comment by anjmao** [comment]
Yes, you have achieve it by both [searchFn] or [typeahead].

```html
<ng-select [searchFn]="customSearchFn"></ng-select>
```

```ts
customSearchFn(term: string, item: YouModel) {
        if (term.lenght < MIN_CHARACTERS_LEN) {
               return false;
        }
        // do search and return true;
}
```
