### ISSUE TITLE
hideSelected not working as expected

### ISSUE THREAD

**Issue by shyamal890** [ng-select/ng-select#1059]
**Describe the bug**
`hideSelected` is no longer working properly. I can confirm that it worked in 2.1.0 and now it doesn't with `2.15.3` or `2.15.2`.

**Reproducbile example**
[Example](https://stackblitz.com/edit/ng-select-hide-selected)

**Additional context**
Refer to https://github.com/ng-select/ng-select/issues/970 someone posted the same issue there. I created a new one as the old one was created in 2018 and is now closed

**Comment by shyamal890** [comment]
Any updates on this?

**Comment by shyamal890** [comment]
@varnastadeus would appreciate if you could have a look.

**Comment by vladilins** [comment]
It still doesn't work

**Comment by BrendanBerkley** [comment]
I'm currently looking at the multiselect docs, and it's definitely not hiding selected items there. So this is broken for single selections and multiselections. Not sure if that merits a new issue or a reopen of this one.
