### ISSUE TITLE
Dropdown position right/left

### ISSUE THREAD

**Issue by mikila85** [ng-select/ng-select#1060]
Hi we have alot of places where the select is inside a form and the dropdown it self coveres the fields below or the Submit button, it would be awesome to have the option for dropdownPosition:
Auto/Top/Bottom/Left/Right

![image](https://user-images.githubusercontent.com/3965957/52712338-f5fe5400-2f9c-11e9-811c-3c97445cef5d.png)

**Comment by mikila85** [comment]
BTW, tried implementing this as an override but the 
_updateAppendedDropdownPosition
function is a private one :(

**Comment by Zverit** [comment]
It will be done in new release? Can it autoposition to another side if overflow?

**Comment by mikila85** [comment]
@varnastadeus  is this something considered to a certain release?

**Comment by erez86** [comment]
+1

**Comment by mikila85** [comment]
?

**Comment by ronbnsim** [comment]
+1

**Comment by saiyaff** [comment]
Eagerly waiting for this +1

**Comment by 1sharma2** [comment]
+1

**Comment by anthony-bt** [comment]
+1

Anyone have some news about this very very usefull feature ?
