### ISSUE TITLE
Placeholder not show on first load

### ISSUE THREAD

**Issue by CanerDemir** [ng-select/ng-select#1063]
**Describe the bug**
I use ng-select with template-driven form like:
`<ng-select class="env-custom-select" [items]="documentTypeList" bindLabel="description" ngModel name="documentType" placeholder="Doküman Tipi Seçiniz" [searchable]="false" clearAllText="Temizle">
						</ng-select>`
everything is alright but when i first come to page the select show remove icon now placeholder. When i click remove icon then the placeholder appear. I think it select an empty value or something else.

**Expected behavior**
When first come to page it should show placeholder if any value does not selected.

**Screenshots**
1. When go to the page
![select](https://user-images.githubusercontent.com/9214645/52782612-89e52400-3060-11e9-9cbf-32583196068c.PNG)
2. Then click remove icon
![select2](https://user-images.githubusercontent.com/9214645/52782650-a5e8c580-3060-11e9-83e8-e367deff3b58.PNG)

**Desktop (please complete the following information):**
 - OS: windows10
 - BrowserChrome

**Comment by varnastadeus** [comment]
<img width="620" alt="screenshot 2019-02-14 at 13 10 04" src="https://user-images.githubusercontent.com/17824796/52783215-e98c0100-3059-11e9-887f-ef60182787cb.png">
this `x` means you have value selected and when value is selected, placeholder is not shown

**Comment by CanerDemir** [comment]
Ok. But i don't select any value in init. Can it be about template driven form type?

**Comment by luis-abeno** [comment]
I'm facing the same problem.

**Comment by CanerDemir** [comment]
I got it. When using template-driven-form like `ngModel name="documentType"` that, the field default value is ""(empty string). And ng-select suppose that field is has a value and don't show placeholder. I convert my code to reactive form and set initial value to `null` , the issue solved.

**Comment by luis-abeno** [comment]
Thanks @CanerDemir, it worked :)

**Comment by riajha1** [comment]
Hello team, i am facing issue in placeholder. it is not displaying.
i am using reactive form

**Comment by riajha1** [comment]
> I got it. When using template-driven-form like `ngModel name="documentType"` that, the field default value is ""(empty string). And ng-select suppose that field is has a value and don't show placeholder. I convert my code to reactive form and set initial value to `null` , the issue solved.

Hello team, i am facing issue in placeholder. it is not displaying.
i am using reactive form

**Comment by XIZT07** [comment]
If you are using template-driven-form, then you can just use `patchValue` to set the initial values of the required fields to null.
This way the initial empty string problem is resolved. 
Using reactive forms is still a better approach.
Note: You can use `patchValue` in template-driven-form by accessing form via `@ViewChild` and setting value after a timeout.

**Comment by johnatanbrayan** [comment]
I had a similar problem, and when I started the page, the ng-select input
showed an x ​​in the right corner. Like that:

[image with similar problem example][1]

  [1]: https://i.stack.imgur.com/Wrzsa.png


This occurred to me because the variable with formControlName or [(ngModel)] was
initializing with a value. Like that:

*With ngModel:

    nameExample = '';

*With formControlName:

    editForm = this.fb.group({
       nameExample: [''],
    });

The correct way was like that:

*With ngModel:

    nameExample?: string;

*With reactive Form:

    editForm = this.fb.group({
       nameExample: [null],
    });

An example in html would look something like this:

*With ngModel:

    <ng-select class="custom" id="field_exemplo" name="nameExample" 
        appearance="outline" [trackByFn]="trackById" [items]="listNameExamples!" 
        [(ngModel)]="nameExample" bindValue="id" bindLabel="name" 
        [placeholder]="'APP_TITLE | translate">
    </ng-select>

*With reactive Form:

    <ng-select class="custom" id="field_exemplo" name="nameExample" 
        appearance="outline" [trackByFn]="trackById" [items]="listNameExamples!" 
        formControlName="nameExample" bindValue="id" bindLabel="name" 
        [placeholder]="'APP_TITLE | translate">
    </ng-select>

**Comment by nikhat5311** [comment]
Thanks a tons

**Comment by gethari** [comment]
> <img alt="screenshot 2019-02-14 at 13 10 04" width="620" src="https://user-images.githubusercontent.com/17824796/52783215-e98c0100-3059-11e9-887f-ef60182787cb.png">
> 
> this `x` means you have value selected and when value is selected, placeholder is not shown

Thank you, setting `undefined` for a reactiveForm value instead of `""` worked
