### ISSUE TITLE
groupBy="subprojects" + [selectableGroup]="true" + multiple false root group does not shown

### ISSUE THREAD

**Issue by HNAmine** [ng-select/ng-select#1066]
**groupBy="subprojects" + [selectableGroup]="true" + multiple false root group does not shown**
when i use groupBy sub object and selectableGroup true and multiple false the sub item show in select input but root group dosent shown 
thank you 

                  <ng-select [items]="projects"
                  bindLabel="title"
                  bindValue="id"
                  groupBy="subprojects"
                  [multiple]="true"
                  [(ngModel)]="selectedProjects" [selectableGroup]="true">
                  
                  <ng-template ng-optgroup-tmp let-item="item">
                      {{item.title}}
                  </ng-template>
                  <ng-template ng-option-tmp let-item="item">
                      {{item.title}}
                  </ng-template>
              </ng-select>

**Comment by varnastadeus** [comment]
Your issue gives zero information, create reproducible example

**Comment by MansoorJafari9** [comment]
Hello
I want select group name with above example
but not showing in ng select
https://stackblitz.com/run?file=src%2Fgroup-children-example.component.html

![image](https://user-images.githubusercontent.com/52848663/62728469-26491b80-ba31-11e9-85e3-297b773a8ab6.png)

select Project A

and  Project B
