### ISSUE TITLE
Debouncing Typeahead

### ISSUE THREAD

**Issue by mikemicmike** [ng-select/ng-select#1067]
Hey I've looked through the solutions but i don't see how i can fix this. 

Here is my issue: i'm using typeahead feature because i do custom filtering/sorting of the results. It works great i debounce everything so I'm not killing performance. My problem is that this is the kind of software where most people know the information they are putting in the select box. So they are typing quickly and hitting enter. 

My debounce is killing it because half the time, the user types something hits enter expecting what he typed to be correct. I debounce at 200ms so sometimes the typeahead hasn't debounced yet and i get the wrong selection. 

Is there anything anyone can think of to help me solve this? 

Thanks!

**Comment by varnastadeus** [comment]
try disabling control before loading 🤔
