### ISSUE TITLE
Is it possible to use let-items in the ng-option-tmp template. I need each option to be aware of how many options are selected for multi-select.

### ISSUE THREAD

**Issue by nikkonduru88** [ng-select/ng-select#1069]
### Expected behaviour
Basically I want both let-items="items" and let-item="item" in the option template. I want item for the actual label and I want items to see if there are any selections or not for spacing purposes. Is this possible? 

### Actual behaviour
I get an error (ERROR TypeError: Cannot read property 'length' of undefined) if I set let-items="items" in the template (ng-option-tmp) and using this *ngIf="items.length > 0" in inside the template.

**Comment by varnastadeus** [comment]
your model keeps your selected items, so get the count from there
