### ISSUE TITLE
No option to disable Typehead

### ISSUE THREAD

**Issue by arun-maddheshia** [ng-select/ng-select#107]
### Expected behaviour
Their is no option to turn off search input.

### Actual behaviour
I want to use it as single select without search I can't

### More Info
ng-select version: 0.4.1

**Comment by varnastadeus** [comment]
Hi, thanks for request. This is indeed a valid situation, we will try to implement it so users could get desired behaviour with ease.

**Comment by arun-maddheshia** [comment]
Thanks waiting for this update so I can implement in my live project other property and interface are so cool.

**Comment by anjmao** [comment]
@varnastadeus Any progress on this? This is a very simple feature to add, maybe I can take it ?

**Comment by varnastadeus** [comment]
added support of searchable in 0.6.0
```html
[searchable]="false"
```

**Comment by arun-maddheshia** [comment]
thanx buddy you make my day easy.
