### ISSUE TITLE
Is there a way to make the first option in the dropdown to clear the model?

### ISSUE THREAD

**Issue by nikkonduru88** [ng-select/ng-select#1070]
**Describe the solution you'd like**
I want to have a way to dedicate one of the select item to clear the model. Similar to 'x' the icon when clearable is set to true. For example, first item in the dropdown could have this label: '- - -' and when clicked on this, pervious selection is cleared.

**Describe alternatives you've considered**
I tried to use one of template to set clear function based on the value of the item.

**Comment by varnastadeus** [comment]
when your model changes and value is equal `---` then clear your model, that's it

**Comment by nikkonduru88** [comment]
Thanks @varnastadeus This works when something is already selected. If nothing is selected and I click on the '- - -', it does not clear. My model clears, but I see '- - -' selected.
