### ISSUE TITLE
Adding multiple tags with a Comma delimited list

### ISSUE THREAD

**Issue by Troyd-Destin** [ng-select/ng-select#1071]
**Is your feature request related to a problem? Please describe.**
Pasting a comma delimited list of values into the field doesn't select anything. It tries to search for the full string. 

**Describe the solution you'd like**
When in multi-select mode, an option to toggle where the select box look for commas and attempt to select a list of values as a response. Similar to pasting a comma delimited list of emails into an email when writing to multiple people / mailing list. 

If I paste the string "1,2,3,4,5" into the select box, it will select the objects with the id values 1 2 3 4 and 5.

**Comment by varnastadeus** [comment]
why not implement it yourself? 
```html
<ng-select (paste)="onPaste($event)">
    <ng-option>It works!</ng-option>
</ng-select>
```
