### ISSUE TITLE
Clear focus on select

### ISSUE THREAD

**Issue by salazarr-js** [ng-select/ng-select#1072]
**Describe the bug**
On mobile, the keyboard still open after close the select, even if the close event is emited.
I have to clear the focused state or blur it clicking/taping in another place or with javascript

```javascript
document.activeElement.blur();
```

**Reproducbile example**
[stackblitz example](https://ng-select.stackblitz.io/)

**To Reproduce** 
1. Open the [stackblitz example](https://ng-select.stackblitz.io/) in an mobile browser
2. Open any select (the keyboard will open)
3. Select any option (the select will close automatically)
6. The keyboard still open

**Expected behavior**
The keyboard should hide automatically after select a option or close the select

**Screenshots**
![](https://i.imgur.com/GPAXrVS.jpg)

**Smartphone (please complete the following information):**
 - Device: Moto E (4)
 - OS: Android 7.1.1
 - Browser: Chrome
 - Version: 72

**Additional context**
I use Ionic to compile to mobile devices, but still fail in chrome browser.

**Comment by varnastadeus** [comment]
this works by design, if you select the option control is still focused and since it is searchable keyboard is open too. If you want it to work as simple dropdown use `[searchable]="false"`

**Comment by jpike88** [comment]
@varnastadeus I disagree, from a mobile user's perspective it seems clunky. We're just talking about single select here of course... I understand why you'd want to let the user defocus manually on a multi select.

The user does the following:
1. Focus field, type, look around
2. Hit select
3. Keyboard's still open...

^ that to me is not desirable. if they tapped an option, that means they locked it an option. The field should no longer be focused as the operation by the user is complete, why would they want to continue using the field?
