### ISSUE TITLE
Disabling LastPass on input field via data-lpignore attribute

### ISSUE THREAD

**Issue by experimint** [ng-select/ng-select#1073]
**Is your feature request related to a problem? Please describe.**
I have been experiencing some performance-issues due to the way the LastPass browser-plugin scans over input fields.
Every time a ng-select element is selected, it tries to fill in the input field.

**Describe the solution you'd like**
A way to add the `data-lpignore="true"` attribute to the generated `<input>`
This should tell LastPass to keep its paws off of the field.

**Describe alternatives you've considered**
I've added the `autocomplete="off"` to the `<form>` and changed my LastPass settings, alas to no avail

**Comment by krunal-ctrl** [comment]
probably too late but for future reference 

adding this to ng-select disable laspass 
`[inputAttrs]="{ 'data-lpignore': 'true' }"`

**Comment by Darshan-upadhyay1110** [comment]
> probably too late but for future reference
> 
> adding this to ng-select disable laspass `[inputAttrs]="{ 'data-lpignore': 'true' }"`

By my friend parth raiyani

**Comment by lawaldare** [comment]
@krunal-ctrl `inputAttrs` is not a valid attribute

**Comment by krunal-ctrl** [comment]
Please refer to documentation it is
