### ISSUE TITLE
Sort Group Ordering

### ISSUE THREAD

**Issue by Ryu13** [ng-select/ng-select#1074]
It'd be nice to have the groups themselves support ordering. For example, a list of issues with varying severity.

[{ id: 1, text: 'high1', severity: 'HIGH' },
{ id: 2, text: 'low1', severity: 'LOW' },
{ id: 3, text: 'med1', severity: 'MED' },
{ id: 4, text: 'high2', severity: 'HIGH' }]

<ng-select [groupKeySort]="sorter" bindLabel="text" bindValue="id" ... >...</ng-select>
assume my "sorter" function sorts from LOW to HIGH

would then display

LOW
   low1
MED
   med1
HIGH
   high1
   high2

I'm working on updating an old angularjs project and coming from ui-select which supported group-filter: https://github.com/angular-ui/ui-select/wiki/ui-select-choices

I saw another issue in here (https://github.com/ng-select/ng-select/issues/847) about grouping for the addTag, the same should occur here; when a tag is added that would fall into a new group, the group sorting would need to occur again.

**Comment by varnastadeus** [comment]
sort your items before passing them to ng-select and you will have desired order

**Comment by ahmadalibaloch** [comment]
Sorting items doesn't sort the groups

**Comment by Draluy** [comment]
I tried it and the order of the items is kept, so sorting the items properly does diplay them grouped as intended. 
I think updating the documentation or allowing for a sorting function would be welcome anyway.
