### ISSUE TITLE
passing list of Object as items but ngModel is not binded for default value when passed.

### ISSUE THREAD

**Issue by ashu07** [ng-select/ng-select#1075]
I am Facing an issue when passing a list of objects as items and list of selectedItems with ngModel.
When I try to give a default selected value. It is not getting bound and the checkbox is not checked 

Any suggestions?

**Comment by varnastadeus** [comment]
use `compareWith`

**Comment by ashu07** [comment]
**

can you give an example?

**
I am facing issue to pre-populate the selected values.

**Comment by varnastadeus** [comment]
I think you should give an example of what you trying to achieve

**Comment by ashu07** [comment]
Reproducible example: [Stackblitz](https://stackblitz.com/edit/ng-select-qrc8mn?file=app/app.component.ts)

Find that the given selected object is not prepopulated in the text box inside ng-select options.

How to bind the complete object?

**Comment by varnastadeus** [comment]
It is because you are using ng-multi-label-tmp which is empty
