### ISSUE TITLE
Need asterisk sign besides the placeholder when required attribute is mentioned

### ISSUE THREAD

**Issue by jdm007** [ng-select/ng-select#1078]
Please fill below information if issuing a bug report. 
### Expected behaviour
**Need of Asterisk Sign Besides the Placeholder of ng-select-DropDown using Material theme** 

### Actual behaviour
**Asterisk sign is not appended even if required is mentioned in the code** 

**<ng-select>**
**placeholder= "hello"**
**</ng-select>**

Cannot add HTML entity in placeholder.

**Comment by anjmao** [comment]
Hi @jdm007,

You can add asterisk by `placeholder= "* hello"`, but ideally you should not put asterisk on placeholder but on some label instead.

**Comment by jdm007** [comment]
Hi @anjmao 
But in Material Theme your placeholder becomes the label ( Floating Label ) for ng-select
so i want the asterisk mark on the label and placeholder

**Comment by wautersj** [comment]
I have the same issue. There should be a way to set the asterisks depending whether or not the field is configured as required. Or at least a way to add it manually.

Right now something like; adding it to the label, is a quickfix, but not very flexible. There is no way oh theming it (color, size). If the placeholder accepts html, this could be achieved. But today this is not the case.

![Schermafbeelding 2020-04-02 om 15 15 26](https://user-images.githubusercontent.com/4070167/78253723-1b2d8900-74f5-11ea-9915-d25a5e4194b0.png)

This would be a very nice improvement!

**Comment by wautersj** [comment]
@dahiwalejayesh In reference to what you commented:

another quickfix of doing this, adding if with a pseudo element:

```
.required {
  .ng-select {
    .ng-placeholder {
      &:after {
        content: ' *';
        color: $secondary;
      }
    }
  }
}
```

```
<div class="form-group required">
  <ng-select [items]="languageOptions" [placeholder]="'Preferred language'" formControlName="language"></ng-select>
</div>
```

![Schermafbeelding 2020-04-02 om 15 22 41](https://user-images.githubusercontent.com/4070167/78254498-4e244c80-74f6-11ea-8c2e-37e12a131df1.png)
