### ISSUE TITLE
In Single Select: Remove selected item from dropdowns when selecting the same item again like in multi select.

### ISSUE THREAD

**Issue by rowansiwakoti** [ng-select/ng-select#1079]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by varnastadeus** [comment]
can you add any reasoning behind this or it is because you need this?

**Comment by rowansiwakoti** [comment]
> can you add any reasoning behind this or it is because you need this?

No any reason! I just need this :)
