### ISSUE TITLE
Feature request: Show full value of select option if it have overflow

### ISSUE THREAD

**Issue by swymmwys** [ng-select/ng-select#1082]
**Describe the solution you'd like**
It would be nice if ng-select in case of there is an overflow ('some val...') in option element will show a some kind of popover(tooltip) with whole value.

![2019-03-01_1231](https://user-images.githubusercontent.com/17503250/53629305-4670e500-3c1e-11e9-93f3-8b257c894f56.png)
![2019-03-01_1234](https://user-images.githubusercontent.com/17503250/53629361-6902fe00-3c1e-11e9-83ab-3df1a6cfe158.png)

**Comment by varnastadeus** [comment]
check https://github.com/ng-select/ng-select/issues/939

**Comment by swymmwys** [comment]
@varnastadeus it's not what exactly what I'm trying to accomplish. My suggestion was to implement in ng-select such functionality that will show an external option over dropdown which display complete value of option.
I know, that I can write my own custom template for ng-select option and implement such behavior by myself. But it's would just be nice to have this feature in component it self.

**Comment by varnastadeus** [comment]
It is not easy to say when option overflows, so I would suggest adding `title` or tooltip of your choice while hovering on option

**Comment by swymmwys** [comment]
@varnastadeus sure, I know that it's not easy to implement this.
You can close the issue then if you definitely do not make it in a near future.
Maybe, you can just add an optional 'title' attribute to the element of the 'option' and then browser shows a default tooltip.

**Comment by thesumitshrestha** [comment]
@swymmwys adding ng-select { .ng-dropdown-panel { width: auto !important; } } in CSS, it works but I would like to suggest adding a tooltip while hovering making a substring than adding css. 

<ng-template ng-option-tmp let-item="item">
        <div [ngbTooltip]="item.length > 15 ? item : ''" container="body">
          {{item.length > 15 ? (item| slice:0:15) + '..' : item}}
        </div>
</ng-template>
