### ISSUE TITLE
Showing a loading indicator when using the async pipe

### ISSUE THREAD

**Issue by rangitha** [ng-select/ng-select#1083]
Is there a way to display a loading indicator when we're using the async pipe on an Observable? It looks to me like you can't use the async pipe pattern and show a loading indicator at the same time using the `loading`/`loadingText` property bindings

```
<ng-select [items]="people$ | async"
    bindLabel="name"
    autofocus
    bindValue="id"
    [loading]=?
    loadingText=?
    [(ngModel)]="selectedPersonId">
</ng-select>
```
If not, does such a feature or change make sense if implemented?

**Comment by varnastadeus** [comment]
you probably need to tap into your observable and set loading true/false before and after completion.

**Comment by rangitha** [comment]
Thanks for the heads-up! Solved it like this:

Template:
```
<ng-select [items]="people$ | async"
    bindLabel="name"
    autofocus
    bindValue="id"
    [loading]=loadingPeople
    loadingText='Loading...'
    [(ngModel)]="selectedPersonId">
</ng-select>
```

Component class:
```
ngOnInit() {
    this.loadingPeople = true;

    this.people$ = this.dataService.getPeople()
      .pipe(tap(() => this.loadingPeople = false));
}
```

**Comment by mtvspec** [comment]
Or you can use RxJS Subject to manage state, with observables for success, failure and loading state
`
<ng-select [items]="people$ | async"
    bindLabel="name"
    autofocus
    bindValue="id"
    [loading]="loadingPeople$ | async"
    loadingText='Loading...'
    [(ngModel)]="selectedPersonId">
</ng-select>

// in PeopleService

#peopleLoadingState$ = this.peopleList();
peopleLoading$ = #peopleLoadingState$.asObservable();

#fetchPeopleActionSubject = new ReplaySubject(1);
peopleList$ = this.fetchPeopleActionSubject.asObservable().pipe(
  tap(_ => this.peopleLoadingStateSubject.next(true)),
  switchMap(_ => this.peopleDataService.fetchPeople()),
  tap(_ => this.peopleLoadingStateSubject.next(false)),
  shareReplay(1),
);

getPeople(): void {
  fetchPeopleActionSubject.next();
}

// in People component

public people$ = this.peopleService.peopleList$;
public loadingPeople$ = this.peopleService.peopleLoading$;

ngOnInit() {
    
  this.peopleService.getPeople();
    
}

`

**Comment by IbrahimAyed1** [comment]
You can use the same observable & pipe but use ' ! '
`<ng-select [items]="people$ | async"
    bindLabel="name"
    autofocus
    bindValue="id"
    [loading]="!(people$ | async)"
    loadingText="Loading..."
    [(ngModel)]="selectedPersonId">
</ng-select>
`
