### ISSUE TITLE
The dropdown is transparent and the selected value is not correctly assigned to the field.

### ISSUE THREAD

**Issue by LeonardoVini** [ng-select/ng-select#1084]
**Describe the bug**
The dropdown is transparent and the selected value is not correctly assigned to the field.

**Reproducbile example**
The down arrow does not appear and when I click it the dropdown is transparent.
And when I select one of the values, the selected value appears in addition to the placeholder.

HTML:
```
         <div class="form-group col-md-4">
             <label for="AccountOwner" placement="right" ngbTooltip="Nome do gerente de contas">Account Owner</label>
            <ng-select 
                class="form-control isRequired" 
                [items]="managerNames"
                [selectOnTab]="true"
                bindLabel="ManagerName" 
                dropdownPosition="auto"
                bindValue="ManagerName" 
                labelForId="AccountOwner" 
                placeholder="Select Account Owner"
                [virtualScroll]="true"
                formControlName="AccountOwner">
                <ng-template ng-option-tmp let-item="item" let-search="searchTerm">
                    <div><span [ngOptionHighlight]="search">{{ item.ManagerName }}</span></div>
                </ng-template>
            </ng-select>
        </div>
```

Component.ts:
```
getAccountManagerNames() {
        this.managerNameService.getAccountManagerNames()
            .subscribe(
                managerName => {
                    this.managerNames = [...managerName]
                    console.log(this.managerNames)
                },
                (err) => console.log(err)
            )
    }
```

**Expected behavior**
I want the field to work properly, as shown in the given examples.

**Screenshots**
![image](https://user-images.githubusercontent.com/37921663/53659439-55659080-3c3a-11e9-8402-d48fa6c4202c.png)

![image](https://user-images.githubusercontent.com/37921663/53659628-cefd7e80-3c3a-11e9-9156-8bd6739f40b9.png)

**Desktop (please complete the following information):**
 - Browser: Chrome (70+)
 - Version: 2.12.0

**Additional context**

**Comment by czielin** [comment]
@LeonardoVini Did you find a resolution to this? We are seeing similar behavior after performing an Angular upgrade.

**Comment by Mehadmushtaq** [comment]
any solution??

**Comment by Nachiten** [comment]
@LeonardoVini how could you fix this problem? Please tell us

**Comment by babluroy** [comment]
Here is the solution :

```
.ng-dropdown-panel {
       white-space: normal;
       height: fit-content;
}
```
![Screenshot 2024-05-28 131819](https://github.com/ng-select/ng-select/assets/57542922/df439ab8-58ae-479c-a64c-e2eacd2c594f)
