### ISSUE TITLE
Set ng-select's properties with directive

### ISSUE THREAD

**Issue by sametsafak** [ng-select/ng-select#1085]
I think I am missing something very basic, please forgive me for that but I really can't find the problem.

I just want to set ng-select's parameters (including items) with a directive. It's working on some static properties like clearAllText, but I can't use my directive to change items. 

Here is my sample https://stackblitz.com/edit/ng-select-tests-share

**Comment by varnastadeus** [comment]
https://github.com/ng-select/ng-select#change-detection check this

**Comment by sametsafak** [comment]
Hi @varnastadeus I already checked the documentation. The difference is, I am trying to update items from a directive, not in the component's itself. Please check the [stackblitz](https://stackblitz.com/edit/ng-select-tests-share) link I shared (especially directive file) 

I'm already trying to add items like this:
`hostSelectComponent.items = [
        ...hostSelectComponent.items, 
        {id: '1', text: 'New item'}
      ];`

**Comment by sametsafak** [comment]
Anyone who wants to achieve this problem, here is the solution. Documentation is not.

[https://stackoverflow.com/questions/54961212/how-can-i-change-ng-selects-items-with-directive](https://stackoverflow.com/questions/54961212/how-can-i-change-ng-selects-items-with-directive)
