### ISSUE TITLE
 No Asterisk sign beside the placeholder when required attribute is mentioned

### ISSUE THREAD

**Issue by jdm007** [ng-select/ng-select#1086]
**Describe the bug**

**Reproducbile example**
[Example](https://stackblitz.com) which reproduces described behaviour

**To Reproduce** 
Steps to reproduce the behavior (if example is not provided):

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by varnastadeus** [comment]
asterisk is something that should be added manually, it is not default behaviour that required attribute adds asterisk
