### ISSUE TITLE
Group select is not working

### ISSUE THREAD

**Issue by PiyushCode** [ng-select/ng-select#1089]
**Describe the bug**
while providing group to data grouping select is not working.

**Reproducbile example**
[Example](https://stackblitz.com) which reproduces described behaviour

**To Reproduce** 
Create a fresh project of angular 5-
1-Install version 1.6.3 of ng-select from npm
2-copy the multiselect checkbox example in your project.
3-You'll observe that multiselect check box is not working when check any group option it is not checking every children

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by varnastadeus** [comment]
use latest version, we are not backporting fixes and features to old versions
