### ISSUE TITLE
feature request change Ux

### ISSUE THREAD

**Issue by GoNode5** [ng-select/ng-select#109]
Would it be possible to change the default interface with selected items are non selectable. I'am very happy with current ng-select but I still get a lot of user complaints. I think the chosen.js user interface by greying out selected items is much more clear.  I never saw a need in  showing a select box with disabled items. Just don't show them...

![image](https://user-images.githubusercontent.com/2210672/32135796-05ed2a2e-bc05-11e7-880e-0866e42ac095.png)

**Comment by anjmao** [comment]
@GoNode5 I agree with you, what do you think about not showing selected items in dropdown items list at all?

**Comment by anjmao** [comment]
@varnastadeus We talked about this a lot, probably the best idea would to not show selected items in the dropdown list. What do you think?

**Comment by GoNode5** [comment]
The best thing would be if its optional but think its also a good idea. Thank you for considering :-). To be honest I have for year using chosen so I'am a little biased.  
I understand that it's easier to remove, so for now not showing selected items is fine. Also from a user point of view it's at least very clear.

**Comment by varnastadeus** [comment]
@GoNode5 you can achieve desired look just by overriding css 
![image](https://user-images.githubusercontent.com/17824796/32138441-660de426-bc3b-11e7-85f3-669d19684417.png)

**Comment by varnastadeus** [comment]
@anjmao regarding not showing selected items at all, I don't see any good reason why we should change default implementation.

**Comment by GoNode5** [comment]
@varnastadeus No problem. I will try the css, thanks. Didn't know about pointer-events. Learning everyday... In the end there always be different opinions about user interfaces. An endless debat indeed.  I can always rewrite, fork or pr :-). I think this select, already promoting it to others. It has a good base. Still very happy
