### ISSUE TITLE
Dropdown always opens on custom template label click

### ISSUE THREAD

**Issue by Schwankenson** [ng-select/ng-select#1092]
I need to execute an action if a user clicks on my custom label in a ng-select multiselect in Angular 6. I tried the following:

Template:

    <ng-select [multiple]="true"] (...)>

      <ng-template ng-label-tmp let-item="item" let-clear="clear">
          <span class="ng-value-label" (click)="onLabelClick(item, $event)">{{item.name}}</span>
          <span class="ng-value-icon right" (click)="clear(item)" aria-hidden="true">×</span>
      </ng-template>

  	</ng-select>

Component function:

    onLabelClick(item, $event) {

      $event.stopPropagation();
      $event.preventDefault();

      // Do my stuff
      (...)
    }

The function is triggered, but it always opens the ng-select dropdown and sets the focus in the ng-select combobox. I want the dropdown to stay closed, when a user clicks one of the labels. And the focus should not be in the combobox, because on a mobile device this would open the keyboard. 

Is there a way to not open the dropdown?

I also created a Stackoverflow thread here. I will put the answer there is I get one here:
https://stackoverflow.com/questions/54960202/ng-select-do-not-open-dropdown-on-custom-template-label-click

**Comment by varnastadeus** [comment]
you should use mousedown, eg.:

```html
<ng-template ng-label-tmp let-item="item" >
      <span (mousedown)="$event.stopPropagation()">{{ item }}</span> 
</ng-template>
```

**Comment by Schwankenson** [comment]
Works perfectly, thank you

**Comment by exitlol** [comment]
What about single selection? it doesn't seem to work with those for some reason, any hints & solutions?

**Comment by grubersimon** [comment]
Please reopen this issue, problem from @dstj still exists.
Couldn't find any solution to make it work for single selection workflow.

**Comment by grubersimon** [comment]
Made `(mousedown)` & `(click)` events work on **single selection ng-select** by setting **z-index** (e.g. 50) to object where I want to trigger custom behaviour. Of course you could also handle both `$event.stopPropagation()` & `customMethod(item.id)` via (mousedown), just an example.

```
<ng-template ng-label-tmp let-item="item">
  <span>
    <span
      (click)="customMethod(item.id)"
      (mousedown)="$event.stopPropagation()"
      style="z-index: 50;"
    >PUT CONTENT HERE</span>
    <span>{{item.name}}</span>
  </span>
</ng-template>
```
