### ISSUE TITLE
Dropdown list data obtained asynchronously，the initial model value page does not display when bindLabel  is a variable

### ISSUE THREAD

**Issue by vistwang** [ng-select/ng-select#1093]
**Describe the bug**

**Reproducbile example**
[Example](https://stackblitz.com) which reproduces described behaviour

**To Reproduce** 
Steps to reproduce the behavior (if example is not provided):

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by varnastadeus** [comment]
duplicate
