### ISSUE TITLE
Wrong focused item from inactive mouse position

### ISSUE THREAD

**Issue by sircon** [ng-select/ng-select#1096]
**Description**
When adding a new item from ng-select using search, the inactive mouse focus on its position, instead of the first item on the list.

**Example**
1. [Go to the ng-select examples page](https://ng-select.github.io/ng-select#/data-sources)
2. Select the first dropdown and put your mouse over `Franklin James`
3. Write `a`
4. Press enter

**Expected**
If I'm fast editing and I write something to filter the list, I expect the first item to be selected and not a random one where I left my mouse before start filtering.

**Screenshots**
![Mar-11-2019 12-06-09](https://user-images.githubusercontent.com/1938296/54119668-31ead480-43f6-11e9-99ae-fe7803a17cff.gif)

**Desktop:**
 - MacOS 10.14.1
 - Chrome
 - Version 72.0.3626.121

**Possible solution**
On keyboard inputs, always try to focus the first item of the list (if it exists)

**Comment by varnastadeus** [comment]
looks like this is fixed in the latest version
