### ISSUE TITLE
Copy the selected text from ng-select autocomplete

### ISSUE THREAD

**Issue by hzidan** [ng-select/ng-select#1100]
I am working on an ERP system I want to use ng-select. If you are working on Jira they have a very good example of autocomplete. I want to copy the text of the selected item after select it but in ng-select you always replace the input control with a div and span containing the selected text. Is there an option to keep the input in ng-select or allow copying of text?. 

![jira autocomplete](https://user-images.githubusercontent.com/43990076/54260588-00971380-4572-11e9-9ce4-b0789e978af7.png)

**Comment by natalicontguard** [comment]
I am having the same issue. 
I can't copy the text appears in the component input field.

**Comment by smile2014** [comment]
I am having the same issue.
I can't copy the text appears in the component input field.

**Comment by smile2014** [comment]
@varnastadeus 
I am having the same issue.
I can't copy the text appears in the component input field.

**Comment by smile2014** [comment]
I am having the same issue.
I can't copy the text appears in the component input field.

https://js.devexpress.com/Demos/WidgetsGallery/Demo/SelectBox/SearchAndEditing/Angular/Light/

**Comment by varnastadeus** [comment]
I guess `editableSearchTerm` should solve this

**Comment by hemanthkumarnr6361** [comment]
> I guess `editableSearchTerm` should solve this

No

**Comment by smile2014** [comment]
disabled  should solve this

**Comment by elnino3800** [comment]
There is css:
.ng-select.ng-select-disabled .ng-select-container .ng-value-container .ng-placeholder, .ng-select.ng-select-disabled .ng-select-container .ng-value-container .ng-value {
    -webkit-user-select: none;
    user-select: none;
    cursor: default;
}

If you set user-select: inherit !important;, it should works
