### ISSUE TITLE
Drag to select/toggle

### ISSUE THREAD

**Issue by almania69** [ng-select/ng-select#1102]
I'm having to create a custom component to implement drag-to-select functionality and it's a bit difficult and messy having to subscribe to option events to make this work. The ng-select has a direct connection to events fired on the list options so it would be easier and much more clean to add native support.

If I can implement drag-to-select functionality. Would you consider adding it to this project?

**Comment by varnastadeus** [comment]
I am not fully sure what you mean by drag to select, but this doesn't sound like a proper behaviour for me
