### ISSUE TITLE
Typeahead does not emit when search is cleared

### ISSUE THREAD

**Issue by vesauimonen** [ng-select/ng-select#1107]
**Describe the bug**
When searching & selecting an item, the search is cleared, but typeahead does not emit anything. 

**Reproducible example**
https://stackblitz.com/edit/ng-select-typeahead-when-search-cleared

**To Reproduce** 
1. Go to the [StackBlitz example](https://stackblitz.com/edit/ng-select-typeahead-when-search-cleared)
2. Click on the select field
3. Type "ja" to the search
4. Click on one of the 2 options

**Expected behaviour**
The option is selected and the search is cleared. Typeahead emits `null` when the search is cleared. Clicking the select again will show results with empty search.

**Actual behaviour**
The option is selected and the search is cleared, but typeahead does not emit anything. The latest emission is the "ja" search. Clicking the select again will show results for the "ja" search.

**Additional context**
To my understanding, when the search is cleared and set to `null`, typeahead should also emit the `null` in:

https://github.com/ng-select/ng-select/blob/a4315cd1013eadfc0af535502c5e97cadd537e7e/src/ng-select/ng-select.component.ts#L705-L712

**Additional reproduction**
1. Click the select
2. Type "ja" to the search
3. Click outside of the select
4. Click the select

Typeahead's latest emission is "ja", while the search is empty. Select shows results for "ja" search.

**Comment by BrandonWilliamsCS** [comment]
I'm battling this as well. As a workaround, I'm listening to close events and treating that as if it were a typeahead emission of `null`.
