### ISSUE TITLE
Browser autocompletion shown on Internet Explorer 11

### ISSUE THREAD

**Issue by p91paul** [ng-select/ng-select#1108]
**Describe the bug**
Pressing the arrow down key on IE 11 while on an ng-select opens the browser's own completion dropdown. See below screenshot.

**To Reproduce** 
Steps to reproduce the behavior (if example is not provided):
1. Make sure to have previously filled some forms in your instance of IE11
2. Click on an ng-select instance
3. Push the arrow-down button

**Expected behavior**
No autocomplete options should be shown by the browser, as autocomplete is already handled by ng-select itself

**Screenshots**
![immagine](https://user-images.githubusercontent.com/2157006/54600815-e52e7b80-4a3d-11e9-92a8-9e08a04fe153.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Internet Explorer
 - Version: 11

**Additional context**
According to this stackoverflow answer (https://stackoverflow.com/questions/32785958/disable-input-text-suggestions-in-edge) it should be enough to add the `autocomplete=off` attribute to the `<input>` tag. The question is about edge, but comments suggest this solution works in IE.

**Comment by p91paul** [comment]
As a workaround, setting labelForId="something" on ng-select sets autocomplete=off because of line 27 in https://github.com/ng-select/ng-select/blob/master/src/ng-select/ng-select.component.html.

However, what's the point of setting autocomplete to anything different than "off" in this component?

**Comment by varnastadeus** [comment]
read this issue https://stackblitz.com/edit/ng-select-gm1hwt?file=app/app.component.ts

**Comment by p91paul** [comment]
I've been saying for a while Chrome was going to be the next IE6, and here we are...well I don't think you can do much unless you want to start testing the browser name to handle different behaviors.
