### ISSUE TITLE
Dropdown-panel hiding somewhere inside

### ISSUE THREAD

**Issue by khadervali** [ng-select/ng-select#1111]
**Describe the bug**
I am trying to bind a keyboard shortcut for opening dropdown with ng-template, 

  ```
<a id="select_{{rowItem.id}}" style="cursor:pointer;" (dblclick)="onDial(rowItem)"
    (click)="openSelect(select,rowItem.id)" class="icon-small">
  </a>
  <ng-select #select style="opacity:0; width:220px; position: absolute;" [items]="rowItem?.info" bindLabel="val"
    [clearable]="false" appendTo="body" [(ngModel)]="selectedVal" (change)="onChange($event, rowItem)"
    (open)="onOpen($event)" (close)="onClose($event)">
    <ng-template ng-option-tmp let-item="item">
      <div class="row">
        <div class="col col-md-4">{{item.type}}</div>
        <div class="col col-md-6" style="padding:0;">{{item.name}}</div>
        <div class="col col-md-2">
          <i class="icon-small"></i>
        </div>
      </div>
    </ng-template>
  </ng-select>
```

from somewhere else if binded keyboard shortcut pressed let say `Ctrl+ D`, triggering select open event like
```
var selecEle = document.getElementById('select_'+row.id);
setTimeout(()=>{
   if(selectEle){
       selectEle.click();
  }
});
```
dropdown is opening but hiding top left somewhere and width coming as 0
please find screenshot
**Expected behavior**
If i click on anchor link with mouse click, it's opening currectly, I want same behavior even if we triger openselect method

**Screenshots**
[screenshot](http://bit.ly/2FpWmeY)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome

**Additional context**

**Comment by varnastadeus** [comment]
create reproducible example
