### ISSUE TITLE
Is there a way to set number of rendered options in the dropdown list?

### ISSUE THREAD

**Issue by SerenaIce** [ng-select/ng-select#1113]
Expected: I can set the number to control how many options to be displayed in the dropdown list panel no matter if there is a scrolling.
For example, the display number in the snapshot below is 6, how can I set it to 10 or any other customized number?

<img width="562" alt="Snapshot-rendered number" src="https://user-images.githubusercontent.com/43363062/54976217-a1ef8200-4fd4-11e9-9632-1259f1fb9184.PNG">

**Comment by jcubic** [comment]
Image is broken, you probably clicked comment before it get uploaded and changed to uploaded file.

**Comment by SerenaIce** [comment]
> Image is broken, you probably clicked comment before it get uploaded and changed to uploaded file.

Thanks for your reminder. I've updated it.

**Comment by jcubic** [comment]
You can do this in CSS, open developer tools (google have the best one IMHO) and search in DOM tree this selector `.ng-dropdown-panel .ng-dropdown-panel-items` then set `max-height` (you can use arrows to change it by one pixel) until the number of rows equal to 10, then you need this in your component:
```css
::ng-deep ng-select .ng-dropdown-panel .ng-dropdown-panel-items {
   max-height: 1000px; /* put your value from dev tools here */
}
```

`::ng-deep` will disable css encapsulation for this one selector (not `[_content]` attribute in result css).

**Comment by varnastadeus** [comment]
The answer above is correct, just increase height of dropdown
