### ISSUE TITLE
[Question] cannot install using npm install --save @ng-select/ng-select

### ISSUE THREAD

**Issue by redcastle9** [ng-select/ng-select#1114]
Please fill below information if issuing a bug report. 
### Expected behaviour
When running npm install --save @ng-select/ng-select in my project I expect the package to get installed.

### Actual behaviour
PS D:\Source\NPAInternal\sprint3\opat-cvg-client> npm install --save @ng-select/ng-select
Unrecognized token in source text.
At line:1 char:20
+ npm install --save  <<<< @ng-select/ng-select
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnrecognizedToken
![image](https://user-images.githubusercontent.com/15613295/54827251-29589080-4c77-11e9-99b5-774b7165d124.png)

### More Info
ng-select version: whatever is available right now

I am using npm version 6.4.1, node v10.15.1 and angular version 7.1.4

Is this problem with angular 7?  I am unable to rollback to an earlier version of angular.

**Comment by jcubic** [comment]
Try to type this by hand and not copy/paste maybe there are some hidden unicode characters (or space like character) in your command. I've tested both Ubuntu (Windows WSL) and PowerShell and it works fine.

**Comment by varnastadeus** [comment]
I agree, there shouldn't be any problems installing it.

**Comment by PerttiPalokangas** [comment]
You could try enclosing the text containing at-sign within apostrophes ('), like so:
'@ng-select/ng-select'.
I had similar problem with another npm install command also containing an @-character, and it helped in that case.

**Comment by endresol** [comment]
can it be related to a 32 bit version? I got this same problem on an old laptop running windows 7

**Comment by toner728** [comment]
I had the same issue and after I added a ' before and after the statement it worked no problem.. e.g.  this is the shell command for creating a microsoft sharepoint webpart.   yo 'microsoft/sharepoint'

**Comment by PabsModeG** [comment]
Unrecognized token in source text.
At line:1 char:13
+ npm install  

> <<<< @material-ui/core

    + CategoryInfo          : ParserError: (:) [], P 
   arentContainsErrorRecordException
    + FullyQualifiedErrorId : UnrecognizedToken

when I try to install Material UI

**Comment by al-freezy** [comment]
Try using external Terminal (CMD) ,It worked like a charm.

**Comment by chetanchandel31** [comment]
> when I try to install Material UI

Was just facing same issue, added ' like others suggested and it worked.

Had to do `npm install '@material-ui/core'` instead of `npm install @material-ui/core`.

**Comment by faicalyahia** [comment]
npm install '@material-ui/core' this resolved the problem. thank you chetanchandel31

**Comment by VeNom748** [comment]
> > when I try to install Material UI
> 
> Was just facing same issue, added ' like others suggested and it worked.
> 
> Had to do `npm install '@material-ui/core'` instead of `npm install @material-ui/core`.

Thanks chetanchandel31  it's Working

**Comment by faicalyahia** [comment]
thank you very much.
it's ok

Le dim. 13 juin 2021 à 10:44, Akash Rajiwale ***@***.***> a
écrit :

**Comment by aniketsingh30** [comment]
Thanks enclosing within single code is working.
**npm install -g '@aws-amplify/cli'**
