### ISSUE TITLE
Placeholder not displaying for empty string

### ISSUE THREAD

**Issue by AT41** [ng-select/ng-select#1115]
**Is your feature request related to a problem? Please describe.**
When a formControl is passed into ng-select with a value of `''`, placeholder is not getting displayed. 

**Describe the solution you'd like**
I think that placeholder should be displayed when `''` is the current value, or placeholder should be passed a function that lets the user decide when placeholder should be displayed or not.

**Describe alternatives you've considered**
Constructing a formControl with a default of `null` solves this, but it would make sense for `''` to be treated the same way.

Thanks!

**Comment by varnastadeus** [comment]
empty string is treated as valid value, thats why placeholder doesn't get displayed

**Comment by bibinbabygit** [comment]
Is there any way to show placeholder, if the ngModel is an empty string ('') ??

**Comment by albertzubkowicz** [comment]
> empty string is treated as valid value, thats why placeholder doesn't get displayed

This is definitely wrong behaviour, especially now with Angular 14 Typed Forms. Having Form Control of string type expects you to init that control with empty string. Is there any workaround for this?

**Comment by albertzubkowicz** [comment]
> 
@varnastadeus are you gonna fix this or plan on keeping ng-select incompatible with angular?

**Comment by Iuriy-Budnikov** [comment]
angular = 💩
