### ISSUE TITLE
Escape key swallowing

### ISSUE THREAD

**Issue by ilplotkin** [ng-select/ng-select#1118]
We use ng-select in popups which can be closed using Escape key. But ng-select always performs preventDefault/stopPropagation in Escape key handler and so popup never got this event.
It's proposed to perform preventDefault/stopPropagation not always but only in case when ng-select is opened. Then first Escape will clear/close ng-select and second Escape will close popup.
What is your opinion?

**Comment by domoneill1** [comment]
you can get around by using keyup listener for escape

**Comment by varnastadeus** [comment]
fixed in latest version
