### ISSUE TITLE
When a array having same labels are not displayed as selected

### ISSUE THREAD

**Issue by Varshamathukumalli** [ng-select/ng-select#1119]
Hi There,

In the below sample, i have duplicated the names of two cities, but not the id's.
({id: 1, name: 'Vilnius'},
        {id: 2, name: 'Vilnius'}) 
Then the selected list is showing only one of them, but not both.

Kindly provide a fix for this problem.

stackblitz url:
https://stackblitz.com/edit/ng-select-qzrzxr?file=app/app.component.ts

**Comment by varnastadeus** [comment]
use compareWith
```ts
compareFn(a, b) {
      return a.id === b.id
}
```

**Comment by Varshamathukumalli** [comment]
@varnastadeus ,

can you please update in the sample and share. Because the issue is the list provided in ngModel is not showing all the values. Where to use the compare function you have provided?

**Comment by varnastadeus** [comment]
```html
<ng-select [compareWith]="compareFn" ></ng-select>
```
```ts
compareFn(option, selected) {
    return optiond.id === selected.id
}
```

**Comment by Varshamathukumalli** [comment]
Thanks for the soultion.

**Comment by alvaro-octal** [comment]
Any ideas about how could be implemented just once?, It works well but now I have to implement compareFn at every single component
