### ISSUE TITLE
Item selection does not work

### ISSUE THREAD

**Issue by brianharwell** [ng-select/ng-select#1120]
Please fill below information if issuing a bug report. 
### Expected behaviour
I should be able to select **any** item in the list programmatically by value

### Actual behaviour
I am trying to select an item in the list when the page is loaded. I am using grouping and I can select a child but not the parent.

https://stackblitz.com/edit/angular-prztjb

#### With Grouping
I can select a child but I cannot select a parent.

Click Set Parent: Error in console
Click Set Child 1: Works
Click Set Orphan 1: Error in console

#### Without Grouping
I can select any top level item.

Click Set Parent: Works
Click Set Child 1: Removed because there are no children displayed
Click Set Orphan 1: Works

### More Info
ng-select version: 2.16.2

browser: 
Chrome Version 73.0.3683.86 (Official Build) (64-bit)
Microsoft Edge 41.16299.1004.0
Firefox 66.0.1 (64-bit)

reproducible in demo page: 
Not sure what you mean by "demo page". I have a StackBlitz that demonstrates the issue.

**Comment by varnastadeus** [comment]
you need to use `SelectableGroup` to make parent selectable

**Comment by brianharwell** [comment]
@varnastadeus I did.

I can select the parent item manually but I cannot select the item programmatically.

Please review the StackBlitz link.

**Comment by varnastadeus** [comment]
Firstly don't use getter as your items, it lags obviously in your example. 
Secondly you shouldn't use internal apis for that purpose, set `ngModel` with your desired value should be object

**Comment by brianharwell** [comment]
I initially had a reactive form control and was trying to set the value. The behavior was the same, I could set the value to a child but not the parent.

**Comment by brianharwell** [comment]
I updated the StackBlitz. I am using a FormControl and I am setting the value. Works great if I am setting the value to a child but it does not work if I set the value to a parent or to an item that does not have any children. No errors this time.

Please reopen this issue.

**Comment by brianharwell** [comment]
Ok thanks. The documentation should make that abundantly clear. I can submit a PR if you'd like.

**Comment by varnastadeus** [comment]
compareWith is in documentation, but maybe we need more information what it is used for
