### ISSUE TITLE
REGRESSION: Page jumping when scroll showing from a dialog

### ISSUE THREAD

**Issue by jpike88** [ng-select/ng-select#1122]
Opening ng-select on a recent version causes the whole page to jump momentarily for me.

http://streaka.testing.videos.s3.amazonaws.com/screencast_2019-03-28_13-37-01.mp4

@cjdreiss @anjmao this PR is almost definitely the culprit.

https://github.com/ng-select/ng-select/commit/d38f8970f5eddf4e0279357edbc49e788b2443c3

The bug only occurs when I upgraded from 2.15.3 to 2.16.2. It doesn't happen when downgrading back to 2.15.3

**Comment by cjdreiss** [comment]
What OS / browser?  It doesn't do it for me in my apps or in the demo page (https://ng-select.github.io/ng-select#/virtual-scroll) in chrome on windows.

It looks like your component is in some sort of virtual scrolling overlay.  Is there a UI framework your using?

**Comment by jpike88** [comment]
Angular material dialog

**Comment by cjdreiss** [comment]
Are you using the "appendTo" option?

**Comment by cjdreiss** [comment]
I quickly checked and it seems to behave that way because the call to `_updateAppenededDropdownPosition()` is now in that set timeout.  I made that call outside the set timeout (but also kept it in there even though it seemed ok with out it, I think maybe I was getting lucky with the setting of current postion happening before `_updateAppendedDropdownPosition()` checks the value.

```
function () {
        var _this = this;
        this._window.setTimeout(function () {
            _this._currentPosition = _this._calculateCurrentPosition(_this._dropdown);
            if (_this._currentPosition === 'top') {
                _this._renderer.addClass(_this._dropdown, TOP_CSS_CLASS);
                _this._renderer.removeClass(_this._dropdown, BOTTOM_CSS_CLASS);
                _this._renderer.addClass(_this._select, TOP_CSS_CLASS);
                _this._renderer.removeClass(_this._select, BOTTOM_CSS_CLASS);
            }
            else {
                _this._renderer.addClass(_this._dropdown, BOTTOM_CSS_CLASS);
                _this._renderer.removeClass(_this._dropdown, TOP_CSS_CLASS);
                _this._renderer.addClass(_this._select, BOTTOM_CSS_CLASS);
                _this._renderer.removeClass(_this._select, TOP_CSS_CLASS);
            }
            if (_this.appendTo) {
                _this._updateAppendedDropdownPosition();
            }
            _this._dropdown.style.opacity = '1';
        }, 0);

        // DUPILCATED THIS CALL HERE, SO IT RUNS OUTSIDE THE TIMEOUT LIKE BEFORE
        if (_this.appendTo) {
            _this._updateAppendedDropdownPosition();
        }
    };
```
@anjmao thoughts on this?  Seems weird to have the call both in the set timeout and outside the set timeout, but I haven't really dove into the code much.

**Comment by jpike88** [comment]
Yes I'm appending to document body

**Comment by cjdreiss** [comment]
I put in a PR for this, #1127 

I noticed the issue happened to me on a screen that had no scrollbar as well. 

The code block for updating the drop down position needed to be both inside the timeout and outside the timeout to work correctly.  Without having it in both places, the top/bottom position was not correct.
