### ISSUE TITLE
Typeahead Dropdown does not highlight/select first selectable element

### ISSUE THREAD

**Issue by AT41** [ng-select/ng-select#1123]
When implementing typeahead with \<ng-option\>, the dropdown items do not get marked when only using keyboard to navigate.

See https://stackblitz.com/edit/ng-select-zqv9cm?file=app/app.component.ts. 
Clicking on first ng-select component and typing will not automatically highlight the first option in the dropdown, and I am not able to select the option by pressing enter. Refreshing the page and clicking on the second ng-select component and typing will highlight the first option though. 

Repro:
1. Select first ng-select component.
2. Type 'Vil' and press enter. Pressing enter will not select any of the options.
3.  Refresh the page.
4. Select second ng-select component.
5. Type 'Vil' and press enter. Pressing enter will select the first component.

I would expect that the first ng-select act like the second ng-select.

**Desktop**
 - OS: MacOS Mojave v10.14.3
 - Browser: Chrome 73.0.3683.86

**Comment by jothipandiyanjp** [comment]
I am also facing the same issue.
Is there any possible way to solve this in the current version or we need to wait till it merging into master??

**Comment by AT41** [comment]
@jothipandiyanjp My fix was just to access the ng-select.component.ts class, and subscribe to ngOptions.changes. See this: 
![image](https://user-images.githubusercontent.com/18402976/55413053-cf34b680-5525-11e9-8e39-3e8c6b8c30bd.png)

Basically, inside the subscribe() method, I set `_markedIndex` to the index I want to highlight.

**Comment by hisham** [comment]
Hi @varnastadeus - we might be able to do a PR with the fix for this. Is this something you're open to looking at and merging into the repo?

**Comment by hisham** [comment]
It's still a bug.
