### ISSUE TITLE
Placeholder always visible

### ISSUE THREAD

**Issue by JakaRua** [ng-select/ng-select#1124]
**Describe the bug**
When using a translation, placeholder is not cleared. 
I also noticed that placeholder does not work if it has more than 1 word.

**To Reproduce** 
Add to select ` placeholder='{{translateString + "select.order" | translate}}'`

`      <ng-select
        [items]="selectRemoveOptions"
        placeholder='{{translateString + "select.order" | translate}}'
        labelForId="removeOption"
        bindValue="id"
        [bindLabel]="'name'"
        class="custom-select"
        (change)="setFiltersModel($event, 'TradeType')"
        [searchable]="false"
        [dropdownPosition]="'bottom'"
        #sortOrderSelect
        bindLabel="removeOption"
      ></ng-select>`

**Screenshots**
http://prntscr.com/n4lhbb
http://prntscr.com/n4lhkd

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version: 73.0.3683.8

**Comment by varnastadeus** [comment]
create reproducible example

**Comment by Dranac** [comment]
hi, you can take a look on the link below to have a live example : 

https://stackblitz.com/edit/angular-11icia
