### ISSUE TITLE
filtered and selected option not highlighted in ng-select options

### ISSUE THREAD

**Issue by JayasimhaJay1994** [ng-select/ng-select#1125]
when we filter and select an option, and when we reopen the options again, for the first time then the selected option is not highlighted in the options list. this is happening only for the first time but from second time onwards its highlighting. what would be the issue please suggest me

**Comment by hisham** [comment]
This might be related to https://github.com/ng-select/ng-select/issues/1123

**Comment by JayasimhaJay1994** [comment]
> This might be related to #1123

ohh yes !!

**Comment by ExFlo** [comment]
Hi
Maybe the highlight directive is messing with the template system. Go to https://ng-select.github.io/ng-select#/templates example  Custom common, type "Pa' it is not working.
BR

**Comment by varnastadeus** [comment]
I think this is fixed in the latest version
