### ISSUE TITLE
Do you plan to support Ant Design？If yes, need a pr?

### ISSUE THREAD

**Issue by yy7054wyq5** [ng-select/ng-select#1128]
[Ant Design](https://ant.design/)

**Comment by varnastadeus** [comment]
what do you mean by supporting ant design?

**Comment by yy7054wyq5** [comment]
Add like ant scss.because ant layout is different.

**Comment by varnastadeus** [comment]
yes, themes are welcome

**Comment by yy7054wyq5** [comment]
ok.i will.
