### ISSUE TITLE
null Group By values always first

### ISSUE THREAD

**Issue by abney317** [ng-select/ng-select#1132]
**Describe the bug**
If you do a group by on a certain key, all objects in the list that have a null value for that key show first. I would like for them to show last.

For example I might want a list like this:

```
data = [
	{ name: 'Bob', group: 'Favorites' },
	{ name: 'John', group: 'Favorites' },
	{ name: 'Alice', group: null },
	{ name: 'Janice', group: null },
	{ name: 'Jim', group: null },
	{ name: 'Mary', group: null },
]
```

> Favorites
> -Bob
> -John
> Alice
> Janice
> Jim
> Mary

But if I sort my data where the people with a null group are last, then ng-select still puts them at the top.

I can select the "Favorites" group to add both Bob and John, or select any of the other people who don't have a group. I'd rather not have to make an "everyone else" group to make them show below as I wouldn't want that to be a selectable option.

**Comment by varnastadeus** [comment]
this was intended since usually you have items without group first, and then groups later on

**Comment by abney317** [comment]
I guess you can call this a feature request then

**Comment by fzs1994** [comment]
@abney317 can you please share your CSS hack? I'm still facing this same issue

**Comment by abney317** [comment]
> @abney317 can you please share your CSS hack? I'm still facing this same issue

This is stuff from 4 years ago but here it is. Looks like there's some bootstrap 4 classes in here also that could easily be swapped to your own classes.

```
<ng-select class="groupfirst" [items]="users" bindLabel="name" groupBy="group" [selectableGroup]="true" [selectableGroupAsModel]="false" [(ngModel)]="selectedUsers" multiple="true" placeholder="Users">
  <ng-template ng-optgroup-tmp let-item="item">
    <div [ngClass]="item.group != '' ? 'font-weight-bold mx-2 mt-2 mb-1' : 'font-weight-bold'">{{ item.group }}</div>
  </ng-template>
  <ng-template ng-option-tmp let-item="item">
    <div [class.unindent]="item.group == ''">
      <span class="font-weight-bold small">{{ item.name }}</span>
    </div>
  </ng-template>
</ng-select>
```

Couldn't use nulls for sorting, so used blank string instead.

```
data= data.sort((a,b) => {
  if(a.group == '' && b.group == '') {
    return 0;
  }

  if(a.group == '') {
    return 1;
  }

  return -1;
});
 ```
 
 CSS:
```
.ng-select.groupfirst > .ng-dropdown-panel .ng-dropdown-panel-items .ng-optgroup {
  padding: 0px !important;
}

.ng-select.groupfirst > .ng-dropdown-panel .ng-dropdown-panel-items .ng-option {
  padding-top: 2px !important;
  padding-bottom: 3px !important;

  div > span.small {
    margin-top: -4px;
  }
}

.ng-option div.unindent {
  margin-left: -12px !important;
}
```
