### ISSUE TITLE
example with flag icon?

### ISSUE THREAD

**Issue by calidion** [ng-select/ng-select#1133]
Is there any example on how to integrate with flag-icon?

**Comment by varnastadeus** [comment]
what if flag icon 🤔 ?

**Comment by calidion** [comment]
flag icon:
http://flag-icon-css.lip.is/
flag icon with bootstrap selector example which can select  languages:
https://vigcoin.org

**Comment by varnastadeus** [comment]
just check demo site, there are plenty of examples
