### ISSUE TITLE
Make use of NgForOf's 'trackBy' attribute for options and selected values

### ISSUE THREAD

**Issue by homj** [ng-select/ng-select#1134]
**Is your feature request related to a problem? Please describe.**
The `trackBy` attribute allows to specify a function that returns a unique identifier for an element in `NgForOf`. This helps avoiding unnecessary & expensive comparisons when the dataset changes (e.g. when receiving new data from an http call).

**Describe the solution you'd like**
By default, the `trackBy` function could/should use the path defined by `bindValue` to identify elements. I'd love to specify my own function though, in cases where i don't use `bindValue`.

**Describe alternatives you've considered**
The only alternative to make use of `trackBy` is to specify the options in the template itself (without using the `items` attribute).

**Additional context**
The reasoning behind `trackBy` is described in the official documentation for `NgForOf`: [https://angular.io/api/common/NgForOf#change-propagation](https://angular.io/api/common/NgForOf#change-propagation)

**Comment by kelvinlouis** [comment]
> The only alternative to make use of trackBy is to specify the options in the template itself (without using the items attribute).

Only if you use `ng-option` you will be able to use `trackBy`. This works perfectly fine:
```
<ng-option *ngFor="let country of (countries$ | async); trackBy: countryTrackByFn" [value]="country.countryCode">
  {{country.name}}
</ng-option>
```

However, if you have the use case of custom templates, you won't be able to mix `ng-option` and templates together. Only plain text can be rendered within `ng-option`. Thus, it would be nice if there is a way to use custom templates and `trackBy` at the same time.
