### ISSUE TITLE
Doesn't mark the first item when the selected item is cleared by backspace

### ISSUE THREAD

**Issue by saiyaff** [ng-select/ng-select#1136]
**Describe the bug**
The scenario is when the `[clearOnBackspace]="true" [markFirst]="true"` attributes are enabled.
So when I clear the value using backspace, it behaves as expected. Which is, it clears the input field and mark the first attribute in the dropdown.
Now, I select a value from the dropdown below and focus out from the input field. Then I click on the input field and clear the selected item using backspace, it doesn't mark the first one

**Reproducible example**
Stackbiltz [Example](https://stackblitz.com/edit/ng-select-clear-on-backspace?file=app/app.component.ts) which reproduces described behavior

**To Reproduce** 
Steps to reproduce the behavior (if the example is not provided):
1. Go to the given example
2. Click on the select dropdown
3. Scroll down and select a value
4. Focus out from the select input field
5. Again focus on the select input field
6. clear the selected item using backspace
7. Can observe the issue the first item is not marked but the previously selected item

**Expected behavior**
On the 7th step, mark the first item in the dropdown

**Desktop (please complete the following information):**
 - Browser - chrome, firefox, edge
 - Version -  73.0.3683.86 (Official Build) (64-bit), 66.0.2 (64-bit), 44.17763.1.0 respectively

**Smartphone (please complete the following information):**
 - Didn't test

**Additional context**
The expected behavior happens when the selected item is cleared using the clear/close icon though

**Comment by Rishanthakumar** [comment]
I too got this issue. Any solution?

**Comment by varnastadeus** [comment]
I am not sure what the issue is. When dropdown is opened, it doesn't navigate to the first item even though you clear your selection using backspace

**Comment by saiyaff** [comment]
> I am not sure what the issue is. When dropdown is opened, it doesn't navigate to the first item even though you clear your selection using the backspace

Yeas. "When dropdown is opened, it doesn't navigate to the first item even though you clear your selection using backspace"
This is exactly the issue. It means it doesn't mark/highlight the first item.

If you refer the **To Reproduce** section [here](https://github.com/ng-select/ng-select/issues/1136#issue-430521893), it is the behavior.

Therefore, when the `[clearOnBackspace]="true" [markFirst]="true"` shouldn't that mark the first item of the dropdown list?

**Comment by varnastadeus** [comment]
the intention of `[markFirst]` was to continue from last selection/first item when opening the dropdown. While dropdown is opened marked item stays in the same position. This is by design and otherwise, the user will get unexpected scrolls which will result in bad UX.

**Comment by saiyaff** [comment]
> the intention of `[markFirst]` was to continue from last selection/first item when opening the dropdown. While dropdown is opened marked item stays in the same position. This is by design and otherwise, the user will get unexpected scrolls which will result in bad UX.

Okay. That makes sense.
But, it would be great if there's a public method in the library that can be accessed to mark the first item then. Reason being there are some use cases that we need to mark the first item clearing using backspace. Also, If not a method what you'd recommend?

**Comment by varnastadeus** [comment]
This should work:

```ts
const [first] = select.itemsList.filteredItems;
select.itemsList.markItem(first);
// to scroll
select.dropdownPanel.scrollTo(first);
```
