### ISSUE TITLE
Can't enter Chinese characters on IE

### ISSUE THREAD

**Issue by piwko28** [ng-select/ng-select#1138]
**Describe the bug**
When the user is trying to enter chinese characters, there immediately appears blank spaces instead of chars. The issue occurs only on IE 11.

**To Reproduce** 
1. Install chinese keyword - I used Chinese (Traditional, Taiwan) - New Phonetic.
2. Change keyword to Chinese and alphabet to Chinese
3. Try to put a character by keyboard
4. See blank spaces instead of Chinese characters

**Expected behavior**
Helper to combine syllabes into word should appear and there is a possibility to put a Chinese character after using space.

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Internet Explorer
 - Version: 11

**Additional context**
Compare behavior with Chrome browser, where it works fine.
It works when you copy and paste Chinese characters.
It looks like something is blocking OS-embedded tooltip.

**Comment by varnastadeus** [comment]
maybe this is because https://blogs.msdn.microsoft.com/ie/2014/03/31/building-better-input-experience-for-east-asian-users-with-the-ime-api-in-ie11/
