### ISSUE TITLE
Is it possible to have a callback for the term. 

### ISSUE THREAD

**Issue by batosi175** [ng-select/ng-select#1143]
**Is your feature request related to a problem? Please describe.**
Currently i'm pulling from a list of items that are all 3 character codes and i don't want my user's to start typing past 3 characters

**Describe the solution you'd like**
I'd like to be able to limit what user's can type in (things like number of characters or allowed characters). The ideal solution would be a callback that lets me have full control over it but,
at a simpler level i'd be nice enough to have maxLength like native input boxes have. 

**What i've tried**
I've tried using the (search) output to set the ngModel, but that does not change the input in the text box itself.

**Comment by varnastadeus** [comment]
you can pass any attribute to input using [inputAttrs]
