### ISSUE TITLE
Multiple and repeatable

### ISSUE THREAD

**Issue by oscarcalvo** [ng-select/ng-select#1148]
**Is your feature request related to a problem? Please describe.**
Its a question: Is there a way or workaround to select the same item several times?
Use case: A list of gifts, where the user has to select two gifts but as well can select the same gift two times (for example a theatre ticket)

**Describe alternatives you've considered**
I have played with compareWith and other options but with no results yet.

**Additional context**
I know maybe a select is not the best control to this feature but I want to use due to space limitations.

Thanks.

**Comment by varnastadeus** [comment]
what you need is to remove connection between option and selected model
```ts
compareFn() {
    return false;
}

onAdd(newItem) {
    this.selected = [...this.selected, newItem]
}
```

```html
<ng-select
    [ngModel]="selected"
    [compareWith]="compareFn"
    (add)="onAdd($event)">
  </ng-select>
```

**Comment by oscarcalvo** [comment]
Thanks, @varnastadeus I have created this example but not working yet. Do I need to use ngOption or something like that? https://stackblitz.com/edit/ng-select-bh8efy?file=app/app.component.ts

**Comment by varnastadeus** [comment]
you are missing two things: `[ngModel]="selectedCityIds"` and `selectedCityIds = []`

**Comment by oscarcalvo** [comment]
you are right, it works perfectly now. Thanks a lot
