### ISSUE TITLE
Ability to add any text

### ISSUE THREAD

**Issue by Velocity540** [ng-select/ng-select#1154]
Might be a simple question, lack of knowledge.

Is there any way (setting) that will allow ng-select to have a dropdown AND free text.
Lets say my drop down contains colors, [Red,Blue,White].

Id like to select the colors but also type in "Blue" as well. Might be simple, but I cannot find the setting to allow me to do this. If I type something not in the list it comes back as not found and blanks out my selection

**Comment by varnastadeus** [comment]
https://ng-select.github.io/ng-select#/tags check demo page

**Comment by david-bulte** [comment]
@varnastadeus 

Using [addTag] somewhat works, but als adds the "free text" in the list of options, which is not what is needed.

My use case:

User fills in the text field, and some suggestions appear in the drop down. Now he is free to either enter his "free text", or to pick one of the options. The next time he uses the select, the earlier chosen "free text" should not appear as an option.

Hope this makes sense. Thanks for the great library!
