### ISSUE TITLE
Ability to disable dropdown open with ArrowDown

### ISSUE THREAD

**Issue by bajzik** [ng-select/ng-select#1155]
**Is your feature request related to a problem? Please describe.**
In table, i need to move under another cell when ArrowDown in clicked. As now, i have it resolved by focusing elements. But in ng-select, when i press ArrowDown when ng-select is focused, dropdown is opened.

**Describe the solution you'd like**
Add possibility to disable dropdown opening on ArrowDown keydown event. Select will be opened Enter key pressed.

**Comment by saiyaff** [comment]
I am facing the same issue and looking for a solution.

**Comment by varnastadeus** [comment]
allowing to invoke user-defined function before actual handlers should do the work  https://github.com/ng-select/ng-select/blob/master/src/ng-select/ng-select.component.ts#L267
