### ISSUE TITLE
Feat: Allow to edit selected item text 

### ISSUE THREAD

**Issue by nfdevil** [ng-select/ng-select#1156]
**Is your feature request related to a problem? Please describe.**
This feature would save the time of having to select the item yourself and pressing Enter to select it.

**Describe the solution you'd like**
A property to switch this feature on or off. When it is on:
When you start to type, select the first item in the list by default. Highlight the part that the user did not type so that he can still continue to type or change it. When the control loses focus and the user clicks on it again, the whole value is selected, so that the user can type over it.  (See screenshot and link at bottom for more info)

**Describe alternatives you've considered**
/

**Additional context**
This feature exists in a paid control of the Telerik collection.
Docs: https://docs.telerik.com/devtools/aspnet-ajax/controls/combobox/functionality/autocomplete
Example (the autocomplete): https://demos.telerik.com/aspnet-ajax/combobox/examples/functionality/autocompleteclientside/defaultcs.aspx
This example does not filter the list when typing, I'd say it would be better that it still filters the list also. We use an application in our company that has a control that does both: 
![autocomplete1](https://user-images.githubusercontent.com/7434048/57139505-b84be300-6db5-11e9-8e1c-41e5a42faae9.png)
![autocomplete2](https://user-images.githubusercontent.com/7434048/57139506-b84be300-6db5-11e9-8712-30fdb6886ada.png)

**Comment by monis001** [comment]
What is the status regarding this issue ??

**Comment by monis001** [comment]
Thanks for mentioning issue references, currently I am using `2.15.3`  Is it in pipeline for next release ?
Thanks

**Comment by saiyaff** [comment]
I am eagerly waiting for this feature as I have got these kinda same requirements at many occurrences while working with ng-select or any other select libraries.
So do atm...

**Comment by varnastadeus** [comment]
This should probably apply only for single select

**Comment by ludydoo** [comment]
For those who are looking for a temp. solution, here is a simple directive to allow for editing ng-select when re-selecting.

You have to add this style as well in your styles.css.

```
.ng-select.ng-select-focused.ng-select-custom-editable .ng-value-label {
  color: transparent;
}
```

```
import { Subscription } from 'rxjs';
import { NgSelectComponent } from '@ng-select/ng-select';
import { Directive, OnInit, OnDestroy, Renderer2 } from '@angular/core';

@Directive({
  selector: '[ngEditableSelect]'
})
export class NgEditableSelectDirective implements OnInit, OnDestroy {
  constructor(private ngSelect: NgSelectComponent, private render: Renderer2) {}

  private subscriptions: Subscription[] = [];

  private static comboBoxSelector = "input[role='combobox']";
  private static className = 'ng-select-custom-editable';

  ngOnInit() {
    this.render.addClass(
      this.ngSelect.element,
      NgEditableSelectDirective.className
    );
    this.subscriptions.push(
      this.ngSelect.blurEvent.subscribe(evt => this.onBlur(evt))
    );
    this.subscriptions.push(
      this.ngSelect.changeEvent.subscribe(evt => this.onChange(evt))
    );
    this.subscriptions.push(
      this.ngSelect.focusEvent.subscribe(evt => this.onFocus(evt))
    );
  }
  ngOnDestroy() {
    this.render.removeClass(
      this.ngSelect.element,
      NgEditableSelectDirective.className
    );
    this.subscriptions.forEach(sub => sub.unsubscribe());
  }

  getComboBox(): HTMLInputElement {
    return this.ngSelect.element.querySelector(
      NgEditableSelectDirective.comboBoxSelector
    );
  }

  onFocus($event) {
    const comboBox = this.getComboBox();
    if (comboBox && this.ngSelect.selectedItems.length) {
      comboBox.value = this.ngSelect.selectedItems[0].label;
    }
  }

  onChange($event) {
    const comboBox = this.getComboBox();
    if (comboBox && this.ngSelect.selectedItems.length) {
      setTimeout(() => {
        comboBox.value = this.ngSelect.selectedItems[0].label;
      }, 0);
    }
  }

  onBlur($event) {
    const comboBox = this.getComboBox();
    if (comboBox) {
      comboBox.value = '';
    }
  }
}

```

then to use the directive

```
<ng-select ngEditableSelect></ng-select>
```

**Comment by hanatharesh2712** [comment]
> in this code, class name should be NgEditableSelectDirective.

**Comment by varnastadeus** [comment]
this is already done with `[editableSearchTerm]`
