### ISSUE TITLE
Providing an apply button to accept the selection

### ISSUE THREAD

**Issue by AnakinPt** [ng-select/ng-select#1157]
I'm using the ng-select to select multiple values of an attribute. To confirm the selection the user must click outside the selection to close it and it's not clear to my users.

I would like to have the ability to add an "apply" button at the bottom of the selection.

This is similar to this request https://github.com/davidstutz/bootstrap-multiselect/issues/535.

**Comment by varnastadeus** [comment]
there is custom footer template where you could add this button
