### ISSUE TITLE
is it possible to use both themes together?

### ISSUE THREAD

**Issue by cls-yzhang** [ng-select/ng-select#1158]
**Is your feature request related to a problem? Please describe.**
We are in the process to convert to material design.  I'm wondering if it is possible to load both themes and use one ng-select with default theme, the other with material theme?

**Describe the solution you'd like**
Use both ng-select with different themes.

**Comment by cls-yzhang** [comment]
Basically, I'm looking for somehow to show 2 ng-select together, one default theme and one material theme.  Just like demo, but what I didn't get is how the theme use() and unuse() work. Around https://github.com/ng-select/ng-select/blob/1c2e792f927bcd729525a31f537a66cac5780d33/demo/app/layout/header.component.ts#L69-L84

What's the differences between `require` and @import
https://github.com/ng-select/ng-select/blob/1c2e792f927bcd729525a31f537a66cac5780d33/demo/app/layout/header.component.ts#L2-L4

**Comment by varnastadeus** [comment]
Demo page uses dynamic loading of themes which adds css into page based on selection. 

What could potentially work is to add wrapper component eg.: `NgSelectMaterial` and include material theme, this will encapsulate all styles for this component only. Also you could try to prefix material theme with your custom selector not sure if scss preprocessors allow to do it though.

**Comment by cls-yzhang** [comment]
Thanks.  I prefixed the material theme.

**Comment by vel007** [comment]
Hi @cls-yzhang ,
I know you have closed this issue. I'm sharing a different solution here because, It may useful for others.
Here is the **solution** in that you can use both the themes of ng-select.

**1. In your style.css, import ng-select themes as below**
```
.material {
  @import "~@ng-select/ng-select/themes/material.theme";
}
.default {
  @import "~@ng-select/ng-select/themes/default.theme";
}
```

**2. hence you can use different themes by calling respective class in the parent tag of ng-select as below**
```
<div class="default">
    <ng-select [items]="choices" [(ngModel)]="model" name="{{name}}" bindLabel="value"></ng-select>
</div>
<div class="material">
    <ng-select [items]="choices" [(ngModel)]="model" name="{{name}}" bindLabel="value"></ng-select>
</div>
```
Have a nice day.
