### ISSUE TITLE
Angular material checkbox and ng-select

### ISSUE THREAD

**Issue by tlebreton** [ng-select/ng-select#1160]
Hi everyone

First thank for this awesome library that save me a lot of time.
I was using the material theme and i was wondering if we can mix ng select with material component specialy the checkbox (mat-checkbox).

So i give a try and the result was pretty good (despite css but it's not a problem).
The main problem is that time to time the selection are not good.

If we select a group sometimes the group is not checked but the children are etc (dont know how to explain but it's perfectly reproductible in the stackblitz below)

https://stackblitz.com/edit/ng-select-23qe1m

If you got any question dont hesitate

Cheers

**Comment by Ashiv3r** [comment]
Hi there!

Found a workaround for this problem, which is: when you click on Angular Material checkbox it fires own click event which is changing item$.selected value inside ng-select, but also there is ng-select event fired (add or change) at the same time. In short you are selecting item twice by mat-checkbox and by ng-select. That can cause described problem.

Workaround:
I've added click event to mat-checkbox and assigned it false. My ng-select code looks like this:

`<ng-select [items]=" [multiple]="true" groupBy="type" bindLabel="name" bindValue="id" placeholder="Wybierz aplikacje" [selectableGroup]="true" [selectableGroupAsModel]="false" [closeOnSelect]="false" [(ngModel)]="selectedApplications">
  <ng-template ng-optgroup-tmp let-item="item" let-item$="item$" let-index="index">
    <mat-checkbox id="item-{{index}}" color="primary" [ngModel]="item$.selected" (click)="false">{{ item.type | uppercase }}</mat-checkbox>
  </ng-template>
  <ng-template ng-option-tmp let-item="item" let-item$="item$" let-index="index">
    <mat-checkbox id="item-{{index}}" color="primary" [ngModel]="item$.selected" (click)="false">{{ item.name }}</mat-checkbox>
  </ng-template>
</ng-select>`

Maybe it's not the most beautiful one, but it fixes problem you encountered. It looks like click event is not fired from mat-checkbox anymore and selection is made only by ng-select.

Cheers!

**Comment by varnastadeus** [comment]
option isn't selected because material checkbox is stopping click event propagation
https://github.com/angular/components/blob/master/src/material/checkbox/checkbox.ts#L374

maybe add simple checkbox and style it as material
