### ISSUE TITLE
Initial selected value can't be displayed correctly when items data is async and bindValue is an object

### ISSUE THREAD

**Issue by GitKou** [ng-select/ng-select#1165]
**Describe the bug**
The bindValue is an object, when items is sync, the selected data can be showed. But when items is async, the selected data is blank.
![image](https://user-images.githubusercontent.com/7437397/57425114-a43c3180-724c-11e9-9313-772c53dad3ce.png)

**Reproducbile example**

https://stackblitz.com/edit/angular-qdr7hy

**Screenshots**
![image](https://user-images.githubusercontent.com/7437397/57425130-b1f1b700-724c-11e9-9457-65784baf0458.png)
.

**Comment by varnastadeus** [comment]
`bindValue` is not intended to be used with objects because your input model will differ with output model, but with `compareWith` it is possible. 
Your model should be defined like this:
```ts
users = [ {user: { uid: '1' }}, {user: { uid: '2' }}];
```

**Comment by GitKou** [comment]
> `bindValue` is not intended to be used with objects because your input model will differ with output model, but with `compareWith` it is possible.
> Your model should be defined like this:
> 
> ```js
> users = [ {user: { uid: '1' }}, {user: { uid: '2' }}];
> ```

Thanks for your quick reply!
I tried what you said.
So the type of ```ngModel``` 's input and output can be different ?
After select an option, ```users```  turns into [  { uid: '1' } ,  { uid: '2' }]
