### ISSUE TITLE
Auto update items

### ISSUE THREAD

**Issue by xyrintech** [ng-select/ng-select#1166]
**Describe the bug**
The items array has changed but ng-select is not updating the items. Lets say when we add a new item to items and then it should show up in dropdown but its not showing up.

**Desktop (please complete the following information):**
 - OS: MAC
 - Browser Every Browser
 - Version 2.16.2

**Comment by varnastadeus** [comment]
read this https://github.com/ng-select/ng-select#change-detection

**Comment by JChoto** [comment]
Hi, You must reload the information for the ng Select: Make a new call to the information load function.
