### ISSUE TITLE
Add option to prevent focusing ng-options on hover. (to focus with arrow keys only or mouse click)

### ISSUE THREAD

**Issue by boltex** [ng-select/ng-select#1167]
**Related problem**
When the dropdown opens, even with setting [markFirst]="false", if the mouse rests in the open space where the dropdown appears, it focuses on the ng-option under it. So with tagging enabled, it will prevent the tagging to have effect, and instead select the option beneath the mouse cursor when pressing enter.

**solution I'd like**
An option to prevent the focussing of ng-options with a mouse hover. 

Thanks for answering and sorry if I missed an already available solution for my problem.

**Comment by mikemicmike** [comment]
Here is the result we would like to achieve 
[https://imgur.com/a/EdWbJIJ](https://imgur.com/a/EdWbJIJ) 

Notice how when we use the arrows it selects it but when you hover with the mouse it just has a hover effect. 

Thanks in advance!

**Comment by adardesign** [comment]
@varnastadeus, Any update on this issue?
Is there any recommendation on how to at least overwrite this issue?

**Comment by aks1994** [comment]
Appreciate the functionality of this component, it is near perfect! If only this feature could be added / a temp fix could be provided, it would help prevent some accidental selections

**Comment by timjklein36** [comment]
Hey all. I was able to pull together a [minimally working attempt](https://github.com/timjklein36/ng-select/tree/tk/no-hover-focus-1167) at this feature.

I will try to add the remainder of the theme style changes, unit tests, and some more documentation over the weekend and then submit an official PR.
