### ISSUE TITLE
Allow custom keyboard actions

### ISSUE THREAD

**Issue by GoNode5** [ng-select/ng-select#117]
The Yes/No example is ok but to much keys to select a yes or no, by keyboard. After key Y or N you need to confirm with enter. For people trained to use the keyboard (not filling forms with mouse ;-) ) its not handy. A key Y or N should by enough, maybe not even an dropdown shown...  I would rather choose for checkbox or switch... then 1 key is enough...

**Comment by anjmao** [comment]
This can be an improvement for custom keyboard actions so you can subscribe to them and do actions using public api.
