### ISSUE TITLE
[Feature] Set the pre-selected values in the items array

### ISSUE THREAD

**Issue by gregoryalary** [ng-select/ng-select#1172]
**Is your feature request related to a problem? Please describe.**
The API i'm consumming returns a list containing the select options (the label, the value & a boolean indicating if the option must be pre-selected or not).
Something like :
```
options = [
  {
    label: 'label1',
    value: 1,
    selected: true
   },
  {
    label: 'label2',
    value: 2,
    selected: false
   },
  {
    label: 'label3',
    value: 3,
    selected: true
   },
]
```
But currently I haven't found an elegant solution to pre-select theses options. 

**Describe the solution you'd like**
The possibility to pass a boolean (called selected or not) saying if the option must be pre-selected would be nice.
`<ng-select [items]="(options)" [multiple]="true"></ng-select>`

**Comment by varnastadeus** [comment]
what you need to do is set those items as your NgModel and they will be preselected

**Comment by gregoryalary** [comment]
Thank you, for your answer. :)
I know that, I just thought that it would be way more elegant to be able to pass a flag in the item list, what do you think?

**Comment by varnastadeus** [comment]
I don't see much value in that, it will be more work on component side when on your side it is basically one line of code

**Comment by gregoryalary** [comment]
Hmmm, ok I get it. Thanks for you work 👍

**Comment by umangchadha** [comment]
i am using formControlName instead of ngModel how can i preselect values in multiselect and single select?

**Comment by contactipraju** [comment]
+1 for umangchadha's comment above..

Angular is giving (the following) WARNING when we try to use ngModel inside a Reactive Form (formControlName).

_**It looks like you're using ngModel on the same form field as formControlName.
    Support for using the ngModel input property and ngModelChange event with
    reactive form directives has been deprecated in Angular v6 and will be removed
    in a future version of Angular.

    For more information on this, see our API docs here:
    https://angular.io/api/forms/FormControlName#use-with-ngmodel**_
