### ISSUE TITLE
Virtual scrolling jumps to an unexpected position

### ISSUE THREAD

**Issue by akuaku2017** [ng-select/ng-select#1173]
**Describe the bug**
Sometimes virtual scrolling doesn't work correctly - scroll position jumps to random locations.

**Reproducible example**
[Example is here](https://stackblitz.com/edit/ng-select-bhsc7z) : it has 3 ng-selects.

First one jumps when scrolling.
The second and third one works correctly. 

**Expected behavior**
I expect that if the virtual scroll is selected, regardless of element height, scrolling will work without unexpected jumping.

**Screenshots**
If applicable, add screenshots to help explain your problem:
![scrolling-jumps](https://user-images.githubusercontent.com/25659052/57912808-6dea5c00-78b5-11e9-8d77-4941f001063f.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterpricse 2016 LTSB (version 1607)
 - Browser:
-- Firefox Developer Edition 67.0b17 (64-bit)
-- Chrome 74.0.3729.131 (64 bit)

**Comment by varnastadeus** [comment]
I think the issue is with dynamic heights of elements which is not supported at this time

**Comment by Troyd-Destin** [comment]
The only way i've been able to fix this, is by setting static row heights. Or preventing any dyanmic elements from changing the row height.

Eg making every row the same height of 50px.

**Comment by varnastadeus** [comment]
yes, thats correct. There is issue #291 for that to be investigated since complexity of it is very high
