### ISSUE TITLE
autocomplete search with dynamic parameters 

### ISSUE THREAD

**Issue by d3x47** [ng-select/ng-select#1178]
**Load autocomplete list dynamically based on the parameters**

Hi, I would like to know if there's an option to load the **autocomplete list data** dynamically rather than loading on NgOnInit.  The data will be fetched from server based on the parameter (one of the parameter represents the sourc/url to fetch data), so i have to pass parameters to the typeahead function. 

Is it possible with ng-select?

StackBlitz to work on:
https://stackblitz.com/edit/ng-select-example-fkhvv5?file=app%2Fapp.component.ts

**Comment by d3x47** [comment]
I need something like [this ](https://stackoverflow.com/questions/56115727/ngbtypeahead-pass-parameters/56116625?noredirect=1#comment98884527_56116625)to be written for ng-select..

**Comment by varnastadeus** [comment]
yes it is possible, just check demo page

**Comment by d3x47** [comment]
I have managed to do this through focus event. 

`<ng-select  [formControlName]="question.id"
                            [items]="multiValueTypeaheadItems$ | async" 
                            bindLabel="name" 
                            [addTag]="true" 
                            [multiple]="true"
                            [hideSelected]="true" 
                            [loading]="searching" 
                            [typeahead]="multiValueTypeaheadInput$"
                            (focus)="onSearch(question.optionsUri, question.minSearchChars)"
                            (change)="getUpdate(questionForms[i], question)"
                            (clear)="onClear()">
                </ng-select>`

I think it should work fine.
