### ISSUE TITLE
with `searchFn` (key entry) enabled, the focused field, or click on field should allow right/left arrow keys

### ISSUE THREAD

**Issue by btmurrell** [ng-select/ng-select#1179]
**Describe the bug**
With custom `searchFn` defined, user is able to type values into the select input field. However, if a user wishes to modify an existing value, clicking on the field re-reveals the dropdown items, but the right/left arrow keys are ignored. I see that the `input` field is controlled by the component, but intuitively, one would expect to be able to right-arrow to an existing value to edit its contents.  The up/down arrow are available to navigate the drop down.  The right/left arrows **should** be enabled to activate the underlying `input` field and allow edits. I cannot take advantage of existing value -- I must start typing which resets the current value.  After typing, right/left arrow keys work as expected to edit existing new entry.

**Reproducbile example**
[Example](https://stackblitz.com/edit/ng-select-right-arrow) which reproduces described behaviour

**To Reproduce** 
1. Go to https://stackblitz.com/edit/ng-select-right-arrow to run the demo
2. with keyboard, enter 12:10 AM, then &lt;enter&gt; key to accept
3. Observe, we have field focus and a flashing cursor.
4. Instinctively, I *should* be able to use the right arrow to edit the field to change the "12:10 AM" to "12:15 AM" (change the '0' to a '5').

**Expected behavior**
Expect that the right arrow would be enabled to allow me to edit field inline.

**Screenshots**
stackblitz demo shows problem.

**Desktop (please complete the following information):**
 - OS: an
 - Browser: chrome, probably others.
 - Version: 2.20.0

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by varnastadeus** [comment]
duplicate #1156
