### ISSUE TITLE
Listen to `touchstart` events for outside click

### ISSUE THREAD

**Issue by kavibhavsar** [ng-select/ng-select#1180]
whenever i touch outside of dropdown. it does not dismiss dropdown. I am using angular 5.

**Comment by varnastadeus** [comment]
there should be fixes in latests version, update to latest version

**Comment by kavibhavsar** [comment]
I am using angular 5. latest version does not support angular 5

**Comment by varnastadeus** [comment]
it is supported from angular 6, we are not supporting older versions

**Comment by kavibhavsar** [comment]
thank you so much for reply,

Do you have any solution for angular 5 ?

**Comment by varnastadeus** [comment]
you can backport fix to 1.x branch and create PR for that
