### ISSUE TITLE
Typeahead and ngOptionHighlight does not work together

### ISSUE THREAD

**Issue by AT41** [ng-select/ng-select#1181]
**Describe the bug**
When using both Typeahead and ngOptionHighlight, the dropdown menu does not display the correct items.

**Reproducible example**
https://stackblitz.com/edit/angular-4efznn

**To Reproduce** 
1. Type in 'asdf'
2. Hit backspace 4 times
3. Type in 'hello'

**Expected behavior**
When typing 'hello' you should see the item 'hello' rather than the item 'asdf'

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome (not tested on other browsers)

**Additional context**
This worked as expected in version 2.19.0 and below, but does not work in version 2.20.0

**Comment by MCGods** [comment]
ngOptionHighlight does not seem to work without using typeahead either. If you look at the third (Custom label option and optgroup) example https://ng-select.github.io/ng-select#/templates and alternate type 'vi' and change to 'si' it shows the wrong option. Changing it afterwards to 'au' suggests that the number of options is always correct (and their order) but the item being displayed is not.
