### ISSUE TITLE
Selection of group with [selecteableGroup]="true" and filtered items does not only select visible items

### ISSUE THREAD

**Issue by jeanchung1337** [ng-select/ng-select#1182]
I have the following simplified situation when using the ng-select component with enabled selectablegroup, groupBy, multiple enabled, selectableGroupAsModel disabled:

[              ] (Search)
[] group1
    [] item_1
    [] item_11

My intention is to filter items by '_11' which results in

[_11] (Search)
[] group1
    [] item_11

as expected and to select all remaining items in group1 which looks like this.

[_11]
[x] group1
    [x] item_11

What now happens is, that in my selected items list all of the items grouped by group1 are selected, that means 'item_1' and 'item_11' which is not what I expect.

I do expect only the remaining items, in this example 'item_11', to be in the selection.

Can you fix this issue or help me accomplish the behaviour explained above?

PS: 
https://ng-select.github.io/ng-select#/multiselect-checkbox last example.

**Comment by varnastadeus** [comment]
if you select whole group and `[selectableGroupAsModel]=true` then all group items are selected, that is by design
