### ISSUE TITLE
Wrong initialization when using with bindValue and selectableGroup

### ISSUE THREAD

**Issue by armved** [ng-select/ng-select#1183]
**Describe the bug**
Select creates new option instead of taking existing one when using with bindValue, selectableGroup, multiple and passing initial value through new FormControl([value])

**Reproducbile example**
[Example](https://stackblitz.com/edit/angular-wm2xwk) which reproduces described behaviour

**Expected behavior**
USA and it's children should be selected and label of group should be correct.

**Additional context**
This can be related to #1161. Examples are same except that in this example FormControl has initialValue ['US']

**Comment by armved** [comment]
I will try to fix this myself

**Comment by holgerb** [comment]
I am having the same issue. Looks like, that this is related to reactive forms. When using the same approach with ngModel seems to work.
