### ISSUE TITLE
clear current search term when using multiple

### ISSUE THREAD

**Issue by sangecz** [ng-select/ng-select#1185]
**Is your feature request related to a problem? Please describe.**
when using multiple=true be able to manually clear current search term

**Describe the solution you'd like**
expose method _clearSearch publicly (this works for me, but it's hacky)

**Comment by varnastadeus** [comment]
why do you need that? You could use `select.filterValue  = null`

**Comment by sangecz** [comment]
thanks @varnastadeus it works. I need that because I'm building more complicated label input (expression), when first you select key, then operator, then value(s)and need to handle model change manually and also clearing the search when item selected
