### ISSUE TITLE
Material theme single select without value arrow position too high issue in IE 11

### ISSUE THREAD

**Issue by cls-yzhang** [ng-select/ng-select#1186]
**Describe the bug**
In material theme, the arrow shows up much higher in single select without value in IE 11.

**Reproducbile example**
Below is the single select without value
![IE11 single select without value](https://user-images.githubusercontent.com/42817903/58346402-cd51ea00-7e28-11e9-8c36-c2acdcfd130c.png)

**To Reproduce** 
Steps to reproduce the behavior open IE 11 browser:
1. Go to https://ng-select.github.io/ng-select
2. Choose "Material theme" in top left corner.
3. Hit "Clear All" in first dropdown.
4. See issue in first image above

**Expected behavior**
Keep same height for the arrow after clear the value

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser IE 11
 - Version 11.0.9600.19356IS

**Screenshots**
Example of material theme single select with value in the same browser, the arrow is at the same line as selected value
![IE11 single select with value](https://user-images.githubusercontent.com/42817903/58346681-a7791500-7e29-11e9-94a9-722744434b68.png)

Example of material theme multi select without value in the same browser, the arrow is at the same line as placeholder
![IE11 multiselect without value](https://user-images.githubusercontent.com/42817903/58346763-e4450c00-7e29-11e9-886d-7b6825f82621.png)

Example of material theme single select without value in chrome works just fine.
![chrome](https://user-images.githubusercontent.com/42817903/58346881-4c93ed80-7e2a-11e9-9e24-0075e75f050d.png)

**Comment by daniel-seitz** [comment]
Just wanted to open this as well.

The problem lies in the position: absolute within .ng-select-single.ng-select .ng-select-container .ng-value-container **.ng-input**

Not sure why this is specified. Doesn't seem to have any effect in the three themes.

**Comment by daniel-seitz** [comment]
This should not be closed since it hasnt been solved.

**Comment by daniel-seitz** [comment]
I found the solution, it behaves bad because of a flexbox bug in ie11 and min-height. See number 3 of https://github.com/philipwalton/flexbugs

Is there a reason to use min-height? I think height would also work.
