### ISSUE TITLE
Add option to limit a number of lines in ng-select input

### ISSUE THREAD

**Issue by sangecz** [ng-select/ng-select#1187]
**Is your feature request related to a problem? Please describe.**
We have more complicated labels consisting key, op. and value(s) of unpredictable length. We'd like to have consistent label-input dimensions across app and show more on demand. Basically show more/less option.

**Describe the solution you'd like**
Add option to limit num. lines of ng-select input. Add method to show all lines.

**Describe alternatives you've considered**
"X more..." solution won't work as labels are of unpredictable length.

**Comment by YakovL** [comment]
In our project it is required to just limit the number of shown suggestions (top 10). For now, I'm going to try to implement this by dynamically updating the list of suggestions but it would be definitely nice to have this out of box
