### ISSUE TITLE
Dropdown not positioned correctly

### ISSUE THREAD

**Issue by jpike88** [ng-select/ng-select#1190]
![Screen Shot 2019-05-27 at 5 45 56 pm](https://user-images.githubusercontent.com/9585787/58415106-a0f7d100-80a7-11e9-8e32-cec2caa51801.png)

**Describe the bug**
Dropdown is incorrectly calculating where to display in a mat-dialog-content tag

**Comment by jpike88** [comment]
Workaround: add this styling to the component:

```
::ng-deep .ng-dropdown-panel {
		margin-left: 8px;
}
```

The offset appears to be off by 8px, any idea why

**Comment by jpike88** [comment]
I FOUND THE PROBLEM.

If appendToBody is enabled, I think it's a good idea to check if there are margin values present in body, and fire a warning in the console. Angular material's fullscreen mode on sidenavs doesn't affect body margin, so this is a tricky one to have to figure out.

**Comment by varnastadeus** [comment]
Docs - Append dropdown to body or any other element using css selector. For correct positioning body should have position:relative

**Comment by jpike88** [comment]
This is still an issue. Problem is, if I append to the item, the dropdown gets hidden by the dialog container. Any ng-select in a mat-dialog has this problem.

And margin-left: 8px; doesn't actually work, it makes the dropdown go up a little and sit on top of the ng-select-container.
