### ISSUE TITLE
Strange behavior when component detect a change

### ISSUE THREAD

**Issue by OlegEndovitskiiy** [ng-select/ng-select#1191]
I make a request if 3 or more characters are entered in the search string. I do it this way:
```
onSearch(search) {
        if(search && search.term && search.term.length > 2) {
            let psr: PersonSearchRequest = new PersonSearchRequest();
            psr.query = search.term;
            this.personService.search(psr).subscribe(data => {
                for(let result of data.results) {
                    this.searchAutocompleteSuggest = [...this.searchAutocompleteSuggest, new SearchAutocompleteSuggest(
                        result.source['firstName'] + ' ' + result.source['lastName'] + ' - ' + result.source['accountLogin'],
                        'xxx',
                        result.source)];
                }
                console.log(this.searchAutocompleteSuggest);
            });
        }
    }
```

Here is my html code of ng-select:
```
<ng-select   [items]="searchAutocompleteSuggest"
             [markFirst]="true"
             [clearOnBackspace]="false"
             [(ngModel)]="query"
             (search)="onSearch($event)"
             (close)="onClose()"
             bindValue="label"
             bindLabel="label"
             placeholder="{{'person.searchAndAdd' | translate}}"
             dropdownPosition="bottom"
             appendTo="body"
             name="addPersonToGroup">
</ng-select>
```

My issue is that console.log displays the correct result. But the drop-down list is not at all the results that I expect. The list is different. But then when I erase the search term (or click clear button), the result becomes correct, and if close the drop-down panel and open it again, the result becomes correct, just as in console.log. You can see an example on the images. Most likely, it also filters the data that the service returned

![image](https://user-images.githubusercontent.com/16243830/58428870-9855c980-80ac-11e9-8b56-d111eacf2990.png)

![image](https://user-images.githubusercontent.com/16243830/58429057-46617380-80ad-11e9-9d27-f34060a73e91.png)

**Comment by varnastadeus** [comment]
create reproducible example

**Comment by OlegEndovitskiiy** [comment]
I created a test simplified [example](https://stackblitz.com/edit/angular-plwvbe), but it seems that this problem is not reproduced.

**Comment by OlegEndovitskiiy** [comment]
Strange, but it manages to filter the data that I received from the `this.personService.search` service. If the search term is erased, then the data becomes correct. This is visible on the images above.

**Comment by OlegEndovitskiiy** [comment]
solved with Typeahead
