### ISSUE TITLE
Set an option selected with it's selected index 0,1, 2 and so on with patchValue reactive forms

### ISSUE THREAD

**Issue by edocbuhtig** [ng-select/ng-select#1192]
**Is your feature request related to a problem? Please describe.**
Like in angular material drop-down I can set option selected just by passing index can we set ng-select populated with [items] sending index with angular 7 reactive forms patchValue

Can we do like *ngFor="let data of bigdata; let index;" to track index, send back the index to API and reverse.

**Describe the solution you'd like**
Can we have patchValue(index) instead of actual option value

**Describe alternatives you've considered**
Cannot find any for reactive forms in your docs

**Comment by varnastadeus** [comment]
use `compareWith` and you can set item as selected based on any predicate

**Comment by edocbuhtig** [comment]
Please can you share how to use [compare With] in reactive forms? I want to set an Option of index 9 as selected item in [items]

**Comment by varnastadeus** [comment]
```html
<ng-select [compareWith]="compareFn"></ng-select>
```

```ts
compareFn(a: any, index: number) {
    return this.items.indexOf(a) === index;
}
```
