### ISSUE TITLE
Connection between ng-select and ng-dropdown-panel

### ISSUE THREAD

**Issue by Kepro** [ng-select/ng-select#1193]
**Is your feature request related to a problem? Please describe.**
I want to help TQA guys to find a connection between ng-select and ng-dropdown-panel if I'm using appendTo="body" but I'm not able to pass custom id or data-* attribute to ng-dropdown-panel

**Describe the solution you'd like**
A possible way for that?

**Comment by varnastadeus** [comment]
you can add class to your ng-select and it will be passed on to panel also

**Comment by Kepro** [comment]
@varnastadeus, not the best solution, to have fake classes, it is possible to add some custom attribute to ng-dropdown-panel?

**Comment by varnastadeus** [comment]
there could be only one dropdown panel in DOM at once so that should be enough
