### ISSUE TITLE
Please update your library so it will support Angular 8

### ISSUE THREAD

**Issue by ovesyan19** [ng-select/ng-select#1195]
Package "@ng-select/ng-select" has an incompatible peer dependency to "@angular/common" (requires ">=6.0.0 <8.0.0", would install "8.0.0")

**Comment by jpike88** [comment]
@varnastadeus bump

**Comment by jpike88** [comment]
I should add that I've been using the angular 8 beta from the beginning, this lib works fine on it

**Comment by jpike88** [comment]
@ovesyan19 why did you close it...

**Comment by ovesyan19** [comment]
@jpike88 reason is that errors appear only if I do ng update --all. but if I update ng-select first and then angular to 8 version then it's working nice

**Comment by jpike88** [comment]
What versions are you seeing in your package.lock? it's probably held you back a version to resolve the dependency warning.
