### ISSUE TITLE
Update to angular 8

### ISSUE THREAD

**Issue by jpike88** [ng-select/ng-select#1196]
I'm getting peer dependency warnings

**Comment by alvaro-octal** [comment]
**Issue description**

running `npm install` throws the following warning:

```
npm WARN @ng-select/ng-select@2.20.0 requires a peer of @angular/common@>=6.0.0 <8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ng-select/ng-select@2.20.0 requires a peer of @angular/core@>=6.0.0 <8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ng-select/ng-select@2.20.0 requires a peer of @angular/forms@>=6.0.0 <8.0.0 but none is installed. You must install peer dependencies yourself.
```
**Steps to reproduce and a minimal demo of the problem**

`npm install` with Angular 8

**Current behavior**

`npm install` shows a couple of warning due to peer dependencies.

**Expected/desired behavior**

No warnings should be shown

**Comment by edocbuhtig** [comment]
Same here when we update to Angular v8 we get warn: angular common 6 < 8 .... This project need version update to v8, and that should resolve. But the select works with no issues.

**Comment by FrancescoBorzi** [comment]
Confirmed

**Comment by nfantone** [comment]
> But the select works with no issues.

Kinda.

Cloning the repo and using latest `core.d.ts` definitions in `@angular/core` `8.0.0`, I'm getting this on `ng-dropdown-panel.component.ts`.


The actual error is:

```sh
Argument of type '{ read: typeof ElementRef; }' is not assignable to parameter of type '{ read?: any; static: boolean; }'.
  Property 'static' is missing in type '{ read: typeof ElementRef; }' but required in type '{ read?: any; static: boolean; }'.ts(2345)
```

Setting `{ static: false|true }` solves the issue - but now using the component raises:

```sh
ERROR TypeError: Cannot read property 'nativeElement' of undefined
```

This comes from `_handleScroll()`.

**Comment by jpike88** [comment]
make static false, it's the default behaviour I believe

**Comment by edocbuhtig** [comment]
@nfantone That's Angular v8 changes you must now use @ViewChild("xyz",{status:true}) xyz: ElememtRef<HTMLElement>

**Comment by nfantone** [comment]
@edocbuhtig @jpike88 I tried both values. It compiles ok, but whenever you open a dropdown, you get ```ERROR TypeError: Cannot read property 'nativeElement' of undefined``` as mentioned [in my previous comment](https://github.com/ng-select/ng-select/issues/1196#issuecomment-497843626).

Maybe I'm doing something wrong?

**Comment by smile2014** [comment]
ERROR TypeError: templateRef.createEmbeddedView is not a function
    at ViewContainerRef_.push../node_modules/@angular/core/fesm5/core.js.ViewContainerRef_.createEmbeddedView (core.js:18838)
    at ViewContainerRef_.push../node_modules/@angular/core/fesm5/core.js.ViewContainerRef_.createEmbeddedView (core.js:18838)
    at NgTemplateOutlet.push../node_modules/@angular/common/fesm5/common.js.NgTemplateOutlet.ngOnChanges (common.js:4773)
    at checkAndUpdateDirectiveInline (core.js:19323)
    at checkAndUpdateNodeInline (core.js:27585)
    at checkAndUpdateNode (core.js:27547)
    at debugCheckAndUpdateNode (core.js:28181)
    at debugCheckDirectivesFn (core.js:28141)
    at Object.View_NgSelectComponent_2.currVal_0 [as updateDirectives] (NgSelectComponent.html:15)

**Comment by jpike88** [comment]
Can someone please add a PR with a test that fails, replicating the issue? I don't see any issues with my setup.

**Comment by markleusink** [comment]
Just to confirm: Upgraded to Angular 8 last week. Using ng-select in various configurations. No issues found so far.

**Comment by jpike88** [comment]
This is frustrating, it seems some of us have zero problems, but some who are reporting it are failing to elaborate, or not firing up a stackblitz which would take a few minutes at most. Which puts this in limbo...

@nfantone can you isolate this in a stackblitz please

**Comment by edocbuhtig** [comment]
@jpike88 There are no errors with ng-select when upgrading from angular 7 to angular 8, the only thing popups up are the peer dependency warnings, that's cos the ng-select project needs to upgrade it's dev dependencies to angular 8 from current v6.

When you upgrade from v7 to v8 Angular CLI automatically scans and update all you @Viewchild to accommodate {static:true} for elementRef

Absolutely no issues it works like a charm in Angular v8

**Comment by spitfjre** [comment]
Typahead does not work anymore with ng8. It correctly adjusts the size of the result, but the values stay the same (and are not adjusted to search term).

**Comment by nfantone** [comment]
@jpike88 So the component seems to work ok. It's just that the version on the repository doesn't compile against the new definitions + you get errors on runtime _after_ fixing the missing `static` attributes.

If you use `ng-select` as-is, from the registry, it just works.

**Comment by jpike88** [comment]
@varnastadeus looks like angular 8 works fine, I think it's good to proceed

**Comment by edocbuhtig** [comment]
With update to version 2.20.2 these warnings still persists.

```
npm WARN @ng-select/ng-select@2.20.2 requires a peer of @angular/common@>=6.0.0 <8.0.0 but none is installed. you must install peer dependencies yourself.
```
