### ISSUE TITLE
Invalid scrollbar position with initial value

### ISSUE THREAD

**Issue by ShevchenkoAlbert** [ng-select/ng-select#1198]
If we have an initial value (f.e. Ukrainian (Ukraine)), then when you first open the menu, the scrollbar position is displayed incorrectly. When reopened, displayed correctly.

**Reproducbile example**
[StackBlitz example](https://stackblitz.com/edit/angular-xe6i89)
**To Reproduce** 
Steps to reproduce the behavior (if example is not provided):
1. Go to '[StackBlitz example](https://stackblitz.com/edit/angular-xe6i89)'
2. Click on 'ng-select'
3. See error incorrect position scrollbar.
4. Closed ng-select.
5. Opened again and see correctly position scrollbar

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [74.0.3729.169 (Official Build)]

![Initial](https://user-images.githubusercontent.com/29691959/58611108-b727ac00-82b6-11e9-9bdd-0e13f0cece6a.jpg)
![Firs_open](https://user-images.githubusercontent.com/29691959/58611110-b727ac00-82b6-11e9-9057-170e3f1d5196.jpg)
![Second_open](https://user-images.githubusercontent.com/29691959/58611109-b727ac00-82b6-11e9-8d49-8e03a060367c.jpg)

**Comment by varnastadeus** [comment]
dup of one of mentioned in https://github.com/ng-select/ng-select/pull/1188
