### ISSUE TITLE
Get value of selected item

### ISSUE THREAD

**Issue by mdmoura** [ng-select/ng-select#1202]
I have the following component:

```
export class CreateProjectComponent implements OnInit {

  form: FormGroup;
  countries$: Observable<CountryModel[]>;

  constructor(private countryService: CountryService) { }

  ngOnInit() {
    this.countries$ = this.countryService.getAll();
  }

  onCountryChange() {
  }

}
```

And the following `ng-select` on the component's html:

    <ng-select 
        [items]="countries$ | async"
        [multiple]="false"
        bindLabel="name"
        bindValue="code"
        formControlName="countryCode">
      </ng-select>

I need to call the function `onCountryChange` when a new country is selected.

And I need to get the value of the selected country.

Can this be done?

**Comment by varnastadeus** [comment]
have you read the documentation before creating this issue?

**Comment by mdmoura** [comment]
@varnastadeus Sure, I was looking for events and found the (add) output but it seems it is only for [multiple]="true". Then I searched in issues to find an example but I wasn't able to find one ...

Maybe because I was searching using the wrong term.

**Comment by varnastadeus** [comment]
Near output events:
(change) | Fired on model change. Outputs whole model.

Also, you are using reactive forms, you can get all the changes from the form you have...

**Comment by mdmoura** [comment]
@varnastadeus Thank you for the help. I though (change) was for associated changes on [items]. 

Yes, I was just checking the Reactive Forms changes ...

**Comment by varnastadeus** [comment]
if you wanted the whole object, then don't use bindValue
