### ISSUE TITLE
ng-select not able to edit text after Item selection - reopen issue

### ISSUE THREAD

**Issue by sanmscse** [ng-select/ng-select#1203]
Hi,
I am using Angular 5 with "@ng-select/ng-select": "^1.5.2"

I had an issue with ng-select text focus and edit text after selected item.

For ex i searched "Test12" first, then i've to choose "test31" in this case i can't clear last two characters.
For change search term i've to clear whole text and retype again for new search.

Please provide some guidance on how to achieve this using ng-select
@varnastadeus , @coveralls

and i'm reopen the issue #1088 since its closed

**Comment by varnastadeus** [comment]
there is already an issue for that, no need to duplicate them
