### ISSUE TITLE
Add tag not allowing to add the item on blur

### ISSUE THREAD

**Issue by deepender87** [ng-select/ng-select#1204]
Add tag is not allowing to add the item in the list on blur. I have to either click or press the enter to add the tag.?
Please let me know if there is a way to add the item in the list without click on the element or pressing the enter key.

**Comment by varnastadeus** [comment]
it is unusual that blur would invoke some sort of action, maybe `[selectOnTab]="true"` is enough

**Comment by deepender87** [comment]
> it is unusual that blur would invoke some sort of action, maybe `[selectOnTab]="true"` is enough?

It will only select the tag on tab. I want something which allow the user to simply write the item and that to be added in the list. 
Here we are forcing the user to click or press enter to add the item in the list. As a UX user won't know the action to take to add the new item.

**Comment by varnastadeus** [comment]
On any other control, a blur event won't trigger any action. eg.: checkbox won't be checked when you focus out of it

But if you really want that behaviour this should work:

```html
<ng-selectselect #select (blur)="select.toggle()">...</ng-select>
```

**Comment by andreiradoi** [comment]
I have to agree with @deepender87 that it makes more sense for the user to have the value saved on blur event.

The solution @varnastadeus proposed did not work for me, but here is something that did the trick:

`
<ng-select #select formControlName="email" ... (keydown)="saveValue()">
`

`
    @ViewChild('select', null) select: ElementRef;
...
saveValue() {
        this.form.get('email').setValue(this.select.searchTerm);
}
`

**Comment by yinyann** [comment]
I had a similar issue.
In my opinion the component should provide a way to transform a user input into a tag on blur event (same behaviour as when he presses tab or enter).

I was not abble to use @andreiradoi trick because I'm not in an angular form context.

My version here is working in my case and I believe it would work most of the time because it relies on the ng-select selectTag().

`<ng-select
	[addTag]="addContactFn"
	[selectOnTab]="true"
    [multiple]="true"
	[isOpen]="false"
	bindLabel="addresseMail"
	(blur)="onBlur($event)">
</ng-select>`


```
private addContactFn(mail: string): Contact {
		if (!mail || mail.length === 0 || ValidatorHelper.IfIsInvalidEmailFormat(mail)){
			return null;
		} else {
			return {
				libelle: '',
				addresseMail: mail
			};
		}
    }

    private onBlur($event: Event): void {
		if (this.input.searchTerm && this.input.searchTerm.length > 0) {
			const contact: Contact = this.addContactFn(this.input.searchTerm);

			if (contact === null) {
				this.input.searchTerm = '';
			} else {
				this.input.selectTag();
			}
		}
    }
```

**Comment by Tonio-lavanda** [comment]
I had the same issue and this is how I solved it (I removed all the code not directly linked to this problem in the code below):

HTML:

```
      <ng-select
        (search)="onTagSearch($event)"
        (blur)="onBlur()"
        [(ngModel)]="selectedItems"
      ></ng-select>
```


TS:

```
public selectedItems: string[] = [];
private lastTagSearched: string = '';

  onTagSearch(inputEvent: TagSearchEvent) {
    this.lastTagSearched = inputEvent.term;
  }

  onBlur() {
    if (this.lastTagSearched) {
        this.selectedItems.push(this.lastTagSearched)
    }
  }

```

**Comment by benzdouglas** [comment]
Small modification to @Tonio-lavanda solution: If you type a partial name and hit return to select it, the last tag searched would still be not null when blur is triggered, so need to clear it out on a change event. (either switch lastTagSearched to public or have change trigger a function)

HTML:
` <ng-select
        (search)="onTagSearch($event)"
        (blur)="onBlur()"
        (change)="lastTagSearched = ''"
        [(ngModel)]="selectedItems"
      ></ng-select>
`

**Comment by Hypnos3** [comment]
For me is working:
```html:
<ng-select #select (blur)="select.selectTag()">...</ng-select>
```
