### ISSUE TITLE
not allowing add items on ngInit

### ISSUE THREAD

**Issue by ehsan69h** [ng-select/ng-select#1206]
**Describe the bug**

**Reproducbile example**
[Example](https://stackblitz.com) which reproduces described behaviour

**To Reproduce** 
Steps to reproduce the behavior (if example is not provided):

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by varnastadeus** [comment]
A clear and concise description of what the bug is..
