### ISSUE TITLE
not allowing add items on ngInit

### ISSUE THREAD

**Issue by ehsan69h** [ng-select/ng-select#1207]
i cant to add items from server to drop down

<ng-select
[items]="tags"
[addTag]="addTag"
[hideSelected]="true"
multiple="true"
bindLabel="name"
[(ngModel)]="newTags"
>
ngOnInit() {
this.tags = [];
this.tourismServiceTagSVC
.Get(this.tourismServiceID, TagType.TourismService)
.subscribe(
(response: any[]) => {
response.forEach((c, i) => {
this.tags.push({ id: i, name: c.text });
});
},
error => {
console.log(error);
}
);
}

**Comment by varnastadeus** [comment]
now read docs, https://github.com/ng-select/ng-select#change-detection
