### ISSUE TITLE
Group Self Reference

### ISSUE THREAD

**Issue by elvispdosreis** [ng-select/ng-select#1209]
#Please fill below information if issuing a bug report. 
### Expected behaviour
I would like help solving a problem described in the stackblitz link

**Expected result**

        Móveis
           Guarda-roupas de Solteiro
               5 Portas
               3 Portas

        Por Ambiente
           Quarto

**or**

        Móveis > Guarda-roupas de Solteiro > 5 Portas
        Móveis > Guarda-roupas de Solteiro > 3 Portas
        Por Ambiente >  Quarto

### Actual behaviour
Describe how it actually works or even better create example using [StackBlitz](https://stackblitz.com/edit/ng-select-1mybvg) issue template

### More Info
ng-select version: 2.16.0

browser: Chrome

reproducible in demo page: Yes

**Comment by varnastadeus** [comment]
dup of #1176
