### ISSUE TITLE
dropdown panel behaviour differs between on click to scroll vs mouse wheel scroll

### ISSUE THREAD

**Issue by carpeVideo** [ng-select/ng-select#1210]
**Description**
The drop down panel listens for a click outside the ng select and if this occurs it closes the drop down panel so multiple panels are not open.  This leads to the behavior where if you click the windows scrollbar or other outside scrollbar to scroll the drop down is closed (which I think is the correct behavior).  But if you scroll an outside element with the mousewheel the dropdown panel stays open

**Example**
[Example]https://ng-select.github.io/ng-select#/data-sources

**To Reproduce** 
Open any select panel, click on the window scroll bar to scroll  and the dropdown panel will close , do it again and use the scroll wheel only to scroll and the dropdown panel remains open

**Expected behavior**
The dropdown panel should probably be closed on any outside scroll just as it is closed on any outside click (or this should be an option).  If its not closed certain conditions may cause a dangling drop down panel.

**Additional context**
This can be fixed by adding one line the ng-dropdown-panel.component.ts ngOnInit().  I only did rudimentary testing.

ngOnInit() {
        this._select = this._dropdown.parentElement;
        this._handleScroll();
        if (this._document) {
            merge(
                fromEvent(this._document, 'touchstart', { capture: true }),
                fromEvent(this._document, 'mousedown', { capture: true }),
                fromEvent(this._document, 'scroll', { capture: true }) // ***** added line
            )
                .pipe(takeUntil(this._destroy$))
                .subscribe(($event) => this._handleOutsideClick($event));
        }
    }

**Comment by varnastadeus** [comment]
click and scroll are different actions, I don't think it should close on scroll

**Comment by carpeVideo** [comment]
The panel already does close on some scrolls - if you scroll by clicking on the scroll bar either as a drag or a page down the panel will close,  if you scroll using the scroll wheel it does not.  So the behavior is not consistent, scroll one way the panel closes, scroll another it does not.  To make it consistent the code either needs to close on both cases (add 1 line of code) or stay open on both cases (check if outside click is on scroll bar and keep open.)     Or make it configurable, allowing one or the other.  

I checked a few other applications/widgets and the behaviors differ:
**bootstrap** - behaves as ng-select does - click anywhere (including scrollbar) closes drop down, mouse wheel scroll and the drop down stays open (so they have inconsistent behavior)
**excel** - clicks anywhere, or any type of scroll (click or mousewheel) closes dropdown
**material** - click outside anywhere but a scroll bar and the dropdown closes, click on an outside scroll bar the dropdown stays open, use mousewheel to scroll and the dropdown stays open.

My particular use case has the ng-select within a custom virtual scroll and when the virtual scroll occurs if an ng-select is open the drop down panel appears to float on an incorrect element.   So for that case to work well with ng-select a configurable option to close on any outside scroll would be the best fix (as opposed to hooking into ng-select and moving the drop down somehow or listening to all scrolls and manually closing the ng-select panel). 

I'd happily do the mod to the ng-select code base to make it configurable to allow close on scroll so it mimics excel behavior, it seems like a fairly straight forward enhancement.

**Comment by varnastadeus** [comment]
dropdown is closed because you click outside of control, it doesn't matter if your scroll afterwards or not. Also, I think your issue is related to https://github.com/ng-select/ng-select/issues/1130
