### ISSUE TITLE
Event not emitting to parent component in case of using ng-select in child component with async mode

### ISSUE THREAD

**Issue by mariumhashmi12** [ng-select/ng-select#1213]
Event not emitting to parent component in case of using ng-select in child component with async mode.
In the example for async mode here 
https://github.com/ng-select/ng-select/blob/master/demo/app/examples/search.component.ts, 
value is being set by ngModel and bindValue is not being used. And it is working well, but if i try and change select value it is not being emitted to parent component.
And if I use bindValue, then it emits the changed value to parent component but in that case setting the ngModel does not set the dropdown value.

Let me know if any more clarification is needed, thanks in advance.

**Comment by varnastadeus** [comment]
without a working example, I can't help you out. Use https://stackblitz.com/ for that
