### ISSUE TITLE
How to set name attribute to ng-select option ?

### ISSUE THREAD

**Issue by anilkokate2009** [ng-select/ng-select#1214]
Hi ,

First thank you for such nice component.It helps a lot

Can you please help on this , how i can set name attribute to ng-select ? 

Can i access using this select document.getElementBYName  ?

**Comment by varnastadeus** [comment]
ng-options are removed from DOM when dropdown is closed, if you only want to add on control itself then just add the name
```html
<ng-select name="my-select"></ng-select>
```

**Comment by anilkokate2009** [comment]
Thank you for your prompt reply. 
It works for static name.
but for dynamic name its not working. getting template parse error. I am using dynamic forms/json forms. I have tried for below options.but not work for me .
<ng-select [name]="{{field.name}}"></ng-select>
<ng-select name="{{field.name}}"></ng-select>

Please help to look into this .

**Comment by p-spacek** [comment]
Hello, I would like to ask you for support name attribute.
<ng-select [name]="controlName">... will rendered as html <input ... name="awesome-ng-input">
it's usefull for autofill extensions, testing...
Thanks
