### ISSUE TITLE
Select All groups option

### ISSUE THREAD

**Issue by Dinesh-AR** [ng-select/ng-select#1217]
I am using ng-select control with multi select checkbox and grouping enabled. I want to have select all option which should select all the groups and items under each group. 

Right now I am using header template for select all option. On click of select all, i have function which is assigning all values to [(ngModel)] variable. But in UI it is only selecting first group and its items.

Could you please tell me how can I achieve this.

Thanks for Good work..

**Comment by varnastadeus** [comment]
create reproducible example

**Comment by Dinesh-AR** [comment]
In StackBlitz, it is working fine. May be some issue in my code.  
https://stackblitz.com/edit/ng-select-u2zeme
