### ISSUE TITLE
Problems after upgrade to Angular 8

### ISSUE THREAD

**Issue by kettunen** [ng-select/ng-select#1218]
It seems there's some problem in search functionality after upgrading to Angular 8. My code worked with Angular 7 but with 8 search doesn't show correct values.

See https://stackblitz.com/edit/angular-r1ugkp

Steps:
1. Click 'Valitse tuote'
2. Type 'acti'

It should show you two products "Aloe Activator" and "Forever Active Probiotic"
but it shows you first one "AA uusis pruire" and third one "Alpha-E Factor"

Is there a bug in my code or in ng-select's?

**Comment by baveryt** [comment]
I'm having the same issue. I found downgrading to ng-select 2.19.0 resolves the problem, so it would appear to be an issue in the latest version of ng-select
