### ISSUE TITLE
Search 'onkeyup' event delay

### ISSUE THREAD

**Issue by vTodorov** [ng-select/ng-select#1219]
How can I delay the search input 'onkeyup' event so that it doesn't fire on every single key press?

**Comment by varnastadeus** [comment]
https://github.com/ng-select/ng-select/blob/master/demo/app/examples/search.component.ts#L113 add debounceTime to your input subject

**Comment by denispostilnyak** [comment]
@varnastadeus hi, do you know why this file was removed?

**Comment by denispostilnyak** [comment]
@vTodorov could you please share your example with debounce?
