### ISSUE TITLE
Unable to bind model in Loop Statemnt

### ISSUE THREAD

**Issue by arun-maddheshia** [ng-select/ng-select#122]
In a loop statement get error if I assign ngModel value dynamic like Cannot read property '0' of undefined and if it is static all looped data value changes from any select change.
```
<ng-select
              formControlName="milestoneCompleteType"
                [items]="milestoneCompleteData"
                bindLabel="name"
                bindValue="id"
                [clearable]="false"
                [(ngModel)]="milestoneCompleteType"
                (change)="onChangeMilestone(i)"
                [searchable]="false">
</ng-select>
```
### Expected behaviour
![3](https://user-images.githubusercontent.com/5073214/32591807-f3753a8a-c546-11e7-987b-502a870218f8.png)

### Actual behaviour
![1](https://user-images.githubusercontent.com/5073214/32591809-f858e40c-c546-11e7-863f-bd66ce0fd405.png)

**Comment by varnastadeus** [comment]
Hi @arun-maddheshia, can you provide more information what exactly you are doing? You are looping through some sort of list and adding `ng-selects`?

**Comment by arun-maddheshia** [comment]
Hi @varnastadeus please delete this my code is wrong now its working sorry for raising an issue without proper debug.
