### ISSUE TITLE
bindValue initializes multiple changes, Default values cannot be displayed

### ISSUE THREAD

**Issue by vistwang** [ng-select/ng-select#1223]
For example
html:
<ng-select
    bindValue="{{modelConfig.bindValue}}"
    bindLabel="{{modelConfig.bindLabel}}"
    placeholder="ng-select 请选择"
    [(ngModel)]="modelConfig.innerValue"
    [items]="modelConfig.items">
    </ng-select>

ts：
modelConfig: any = {
        bindValue: 'id',
        bindLabel: 'name',
        innerValue: 4,
        items: [
            {name: '小米', id: 1},
            {name: '华为', id: 2},
            {name: '三星', id: 3},
        ]
 };

ngOnInit() {
        setTimeout(() => {
            this.modelConfig.bindValue = 'ids',
            this.modelConfig.bindLabel = 'names',
            this.modelConfig.items = [
                {names: '魅族', ids: 4},
                {names: '中兴', ids: 5},
                {names: '苹果', ids: 6},
            ];
        }, 0);
   }

At this point, the default values are not shown, and I need to adjust bindValue in my code.

how can i do?, I need help.

**Comment by varnastadeus** [comment]
`bindValue` and `bindLabel` are static and after initialization cannot change
