### ISSUE TITLE
"label1 &amp label 2 " is coming with label ? how to display only & ? 

### ISSUE THREAD

**Issue by anilkokate2009** [ng-select/ng-select#1227]
"label1 &amp label 2 " is coming with label ? how to display only & ? 

Please help me on this

**Comment by arun-maddheshia** [comment]
@anilkokate2009 `label1 &amp label 2` you are missing a `;` it should be `label1 &amp; label 2`

**Comment by anilkokate2009** [comment]
Thank you for u r reply.

comma is there, the service returns label "label1 & label2", but in dropdown is displaye like "label1 &amp; label2"

**Comment by arun-maddheshia** [comment]
@anilkokate2009 it's not clear what you are trying to achieve can you please provide a [Example](https://stackblitz.com) which reproduces described behaviour.

**Comment by varnastadeus** [comment]
dup and workaround inside #506
