### ISSUE TITLE
It returns null on clicking cross (X)

### ISSUE THREAD

**Issue by sukheja-varun** [ng-select/ng-select#1228]
I have an array of string and by default the value of my field is empty string ''.

But when I click on ng-select dropdown and select some value and then click on cross it sets `null` as the field value.

```
<ng-select [dropdownPosition]="'top'" [searchable]="false" [items]="operationStatusList$ | async"
    formControlName="operationStatus">
</ng-select>
```

**Comment by varnastadeus** [comment]
So what's the problem? We treat empty string as valid value

**Comment by varnastadeus** [comment]
closing as inactive
