### ISSUE TITLE
Replacing the items 'live' is broken since 2.20.0 (ok in 2.19)

### ISSUE THREAD

**Issue by boltex** [ng-select/ng-select#1229]
**Describe the bug**
When implementing a custom search, by replacing the items, ('live' as the user types) the resulting items in the dropdown are corrupted. (wrong indexes and/or wrong values) We had to revert to 2.19.0.

here is a snippet of html to show a context of what we're doing (intercepting search input and replacing items with our viewitems): 

```html
<ng-select [items]="viewItems"
      [typeahead]="searchInput$"
              ... 
```
So basicaly we replace the items with our own search result. (based on our own criterias) In the screenshot you can see our results as of ng-select version 2.19.0: 
![image](https://user-images.githubusercontent.com/847716/59712176-b198f400-91da-11e9-8dda-bede03d71c9f.png)

I re-tried by compiling the same exact code with ng-select version 2.17, 2.18, 2.19 and it completely broke at 2.20.0. (the results displayed are inconsistent with what was put in items) 
![image](https://user-images.githubusercontent.com/847716/59712192-b9f12f00-91da-11e9-82fa-e1b360858b60.png)

(This is my first preliminary report for this bug - i was in a rush so no plunker/stackblitz for now but i'll make one if needed later, sorry!)

**Comment by spitfjre** [comment]
I have the same problem, event with 2.17, 2.18, 2.19 in combination angular 8.

**Comment by varnastadeus** [comment]
Can you create reproducible example?

**Comment by stephanecot** [comment]
Same probleme here with angular 8 et ngselect 2.20.
An ajax called is done with each type, but the list content is not refresh, only filtered.

**Comment by MCGods** [comment]
Looks like #1181
