### ISSUE TITLE
[Question] About Multiselect

### ISSUE THREAD

**Issue by sameeri** [ng-select/ng-select#1230]
Is there a setting to turn **off** the custom behavior of adding chips on multi-select?

I tried to add empty templates like this:

```
      <ng-template ng-label-tmp let-item="item">
      </ng-template>
```
But it adds a `ng-value` div for each of the items. The divs are empty but styles come into play.

Is there an alternate better approach to solving such a use-case?

**Comment by varnastadeus** [comment]
Just override css
