### ISSUE TITLE
Don't Allow Value To Be Selected Again in Ng-Select in Angular

### ISSUE THREAD

**Issue by jtan80813** [ng-select/ng-select#1231]
I'm trying to use the ng-select package in my Angular application and i need some help if i wanted to select something from the dropdown and i don't want it to be selected again if it is already selected. How will i able to do this? Thanks. Pls check this stackblitz link to see the complete code [CLICK THIS LINK](https://stackblitz.com/edit/ng-select-prevent-value-selected-again?file=app%2Fapp.component.html)

**Comment by jtan80813** [comment]
@varnastadeus

**Comment by varnastadeus** [comment]
I think there was a similar question before, but you need to exclude selected items from an array of options every time you select something

**Comment by jtan80813** [comment]
@varnastadeus. There is a question about this but it was not answered. Could you please forked the stackblitz link i have given above? Thanks a lot.

**Comment by varnastadeus** [comment]
you just need to remove the selected item from your `ingridients` on selection, and add it back on removal. There is no other way since one ng-select doesn't share selected state between others

**Comment by jtan80813** [comment]
@varmastadeus. Can you edit my stackblitz? https://stackblitz.com/edit/ng-select-prevent-value-selected-again?file=app%2Fapp.component.html
