### ISSUE TITLE
Add Tag: Option to add new tag despite existing tag

### ISSUE THREAD

**Issue by AT41** [ng-select/ng-select#1232]
**Is your feature request related to a problem? Please describe.**
Sometimes there are cases where I would like to add a new user to an existing database by name. If there's already a user that has the same name I should still have the option to add a new tag.

**Describe the solution you'd like**
Instead of the changes made here https://github.com/ng-select/ng-select/commit/d5e97af72201a3fbedb1fa78d6c69be61776c872, it would be nice if there could be an `@Input` that allows for the 'Add Tag' option appearing even if itemsList contains a match.

**Comment by hisham** [comment]
+1. The use case is creating new people and looking up people by name. People can have same names. So if I lookup "John Smith", I should still have an option to add "John Smith" even if there is an existing person in the list named "John Smith".

**Comment by hisham** [comment]
It's still a bug / feature request.

**Comment by yuvgeek** [comment]
@hisham If two people have the same name, how do you differentiate the user if you going to remove one of them?

**Comment by hisham** [comment]
We use date of birth and other ids to help people distinguish between two people using the same name. 

Screenshot: 

<img width="121" alt="CSI 2019-10-20 09-44-54" src="https://user-images.githubusercontent.com/81853/67162116-6163a700-f31e-11e9-81b4-aa7be0e6d24f.png">

**Comment by yuvgeek** [comment]
@hisham - I have raised PR for this feature request. #1394

**Comment by varnastadeus** [comment]
Ok, let's start from the beginning. Default search filters items by label and if your item label matches, it just returns existing item. If you want to add item with the same label, just override `searchFn`.

```ts
searchFn(term: string, item: {name: string}) {
    return item.name.includes(term) && item.name !== term;
}
```

<img width="598" alt="Screenshot 2019-10-25 at 20 40 46" src="https://user-images.githubusercontent.com/17824796/67592183-c3ca0680-f767-11e9-814e-3b0cb2e6281b.png">
