### ISSUE TITLE
How do I select an item from the list programatically for a multiselect?

### ISSUE THREAD

**Issue by jziggas** [ng-select/ng-select#1235]
I have tried several variations of using ngSelectComponent.itemsList.select(), ngSelectComponent.select(), and cloning the array of selected items but nothing seems to work 100% correct. Calling `ngSelectComponent.select(item)` yields `[undefined]` during the change event.

What am I missing? Thanks for the great library!

**Comment by jziggas** [comment]
I think I figured it out. When calling `ngSelectComponent.select()` I was passing in one of the items but the methods takes an NgOption. So passing in something like this got it working:
```
itemClicked(item) {
  ngSelectComponent.select({
    value: item,
    label: item.title,
    selected: false,
    marked: false,
  })
}
```

**Comment by varnastadeus** [comment]
you can just set your ngModel
