### ISSUE TITLE
Select dropdown panel auto width not working

### ISSUE THREAD

**Issue by sri-ir** [ng-select/ng-select#1236]
ng-select dropdown panel not respecting width auto, so that i am unable to see my complete dropdown panel option labels and it is showing ellipses.

look at the below stackblitz example 
https://stackblitz.com/edit/ng-select-9oqmzo

**Dropdown-1 (without css):** In first example complete option labels are not visible in dropdown panel.
**Dropdown-2 (with css):** Still not visible completely after customized with css also, and in extreme right cases getting browser scroll when i am open dropdown panel.

Please help how to show dropdown panel complete labels without getting browser scroll

**Comment by varnastadeus** [comment]
there is no way to show full labels without browser scroll since there is no space on the right

**Comment by sri-ir** [comment]
but my left side browser space is empty, so i am expected to open dropdown panel right to left.

**Comment by varnastadeus** [comment]
I think you need this #1060
