### ISSUE TITLE
typeahead doesn't work since 2.20.1

### ISSUE THREAD

**Issue by aviaur** [ng-select/ng-select#1237]
**Describe the bug**
When I use the ng-select with typeahead (search values to a server)
Before 2.20.1 it did work

But since 2.20.1 I have this error in my console :

**Screenshots**
![image](https://user-images.githubusercontent.com/37070195/60185436-39f64500-982a-11e9-8e97-ab07ae8c56f1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome

Thx

**Comment by varnastadeus** [comment]
create reproducible example

**Comment by elementalPRESS** [comment]
same here after the latest update. The error messages appear as soon as you click into the input field.

**Comment by HDinger** [comment]
Happens for me too. Here is a minimum stackblitz with the error: https://stackblitz.com/edit/angular-d2yewe

**Comment by custompro12** [comment]
> Happens for me too. Here is a minimum stackblitz with the error: https://stackblitz.com/edit/angular-d2yewe

Your component has the local variable `users$`, but your template is trying to bind to `users$$` which doesn't exist.

Also, you never assign the result of calling `getUser()` in your ngOnInit to the `users$` variable...

Here is your example fixed and working fine: https://stackblitz.com/edit/angular-nbrx8x
