### ISSUE TITLE
Add multiple tags

### ISSUE THREAD

**Issue by Hesesses** [ng-select/ng-select#124]
### Expected behaviour
I should be able to add multiple tags

### Actual behaviour
Only first tag is added

### More Info
ng-select version: 0.6.2
browser: latest chrome
reproducible in demo page: [NO]

I'm using reactive forms with formControlName
![image](https://user-images.githubusercontent.com/2721970/32704143-2064ff02-c809-11e7-9bdc-67e98caca44e.png)

**Comment by anjmao** [comment]
@Hesesses I'm unable to reproduce this in reactive forms. Can you provide more info how are inserting second tag and you ng-select html code?  Thanks :)

**Comment by Hesesses** [comment]
https://www.useloom.com/share/63715cf9e199447885816eb01fa8b857

this is my html
```
<ng-select [items]="judges"
                     [addTag]="true"
                     multiple="true"
                     addTagText="Add a new judge"
                     notFoundText="User does not exist"
                     typeToSearchText="Search for Judges"
                     bindLabel="displayname"
                     [placeholder]="placeholder"
                     [typeahead]="judgeTypeahead"
                     formControlName="judges">
                    <ng-template ng-label-tmp let-item="item" let-index="index">
                      <span *ngIf="item.country" class="flag-icon flag-icon-{{item.country.code}}"></span>{{item.displayname}}
                    </ng-template>
                    <ng-template ng-option-tmp let-item="item" let-index="index">
                      <span *ngIf="item.country" class="flag-icon flag-icon-{{item.country.code}}"></span>{{item.displayname}}
                    </ng-template>
          </ng-select>
```

**Comment by anjmao** [comment]
@Hesesses Thanks, I was able to reproduce it :)
