### ISSUE TITLE
Virtual scroll causes errors when items are empty

### ISSUE THREAD

**Issue by custompro12** [ng-select/ng-select#1240]
**Describe the bug**
When `[items]` is an empty array, null, or undefined, then settings `[virtualScroll]="true"` will cause errors on the console and the dropdown not to display.

**Reproducible example**
[Example](https://stackblitz.com/edit/angular-nshzqi?file=src%2Fapp%2Fapp.component.html)

1. Expand dropdown
2. Observe errors on the console
3. Change `[virtualScroll]=` to `"false"`
4. Expand dropdown
5. Observe `No items found` correctly displays and no errors on the console

**Expected behavior**
When `[items]` is an empty array, null, or undefined, then settings `[virtualScroll]="true"` should properly show `No items found` in the dropdown (as it did in 2.19.x).

Version: 2.20.0

**Comment by varnastadeus** [comment]
duplicate

**Comment by custompro12** [comment]
> duplicate #1237

The issue you referenced is closed.  I don't see any other open issues relating to virtual scroll.

**Comment by custompro12** [comment]
> > duplicate #1237
> 
> The issue you referenced is closed. I don't see any other open issues relating to virtual scroll.

Nevermind, I see the new release with the fix.  Thanks!
