### ISSUE TITLE
[style.background-color] does not work

### ISSUE THREAD

**Issue by andrejm7** [ng-select/ng-select#1243]
<ng-select [(ngModel)]="situacaoSelecionado" (change)="trocaSituacao(situacaoSelecionado)" [style.background-color]="qtdeRegistros > 0 ? '#bbffb9' : write">

[style.background-color]="qtdeRegistros > 0 ? '#bbffb9' : write" ---  does not work

how can i use it in ng-select?
need to paint background-color

**Comment by andrejm7** [comment]
![image](https://user-images.githubusercontent.com/13546247/60554751-3de50400-9d0f-11e9-8440-b8428d2018f7.png)

**Comment by andrejm7** [comment]
![image](https://user-images.githubusercontent.com/13546247/60554783-708efc80-9d0f-11e9-802c-b38819456707.png)

ng-select without background-color

**Comment by varnastadeus** [comment]
you need to add background-color on `.ng-select-container` not ng-select itself. Add class on ng-select and then add style rules that would paint `.ng-select-container`
