### ISSUE TITLE
match first characters

### ISSUE THREAD

**Issue by shalludogra** [ng-select/ng-select#1245]
This package finds a match using 'LIKE %word%'. Possible to change it to 'LIKE %word' Example: If I type the letter 'I' when searching states, currently it returns following:
H**I**
**I**D
**I**L
**I**N
**I**A
M**I**
R**I**

I'd like it to return:
**I**D
**I**L
**I**N
**I**A

**Comment by varnastadeus** [comment]
use custom `[searchFn]` for that

**Comment by shalludogra** [comment]
Thanks, @varnastadeus for your help. Is there any inbuilt property for this?

**Comment by varnastadeus** [comment]
Yes, there is, and I actually wrote the name of that property. There is even example how to use it in https://ng-select.github.io/ng-select#/filter

**Comment by shalludogra** [comment]
Thanks, @varnastadeus
