### ISSUE TITLE
Problem with z-index after updating to Angular 8.

### ISSUE THREAD

**Issue by ikretinin** [ng-select/ng-select#1246]
After updating dropdown of the ng-select with appendTo="body" located behind the modal window. 
How can I fix it?

![image](https://user-images.githubusercontent.com/39625376/60645443-5b19ef80-9e41-11e9-8625-ec7c39fa2b3a.png)

**Comment by varnastadeus** [comment]
I don't think it is related to update since z-index didn't change. Looks like your modal has bigger z-index. Increase z-index of `.ng-dropdown-panel` or decrease z-index of your modal

**Comment by ingrocha** [comment]
I solved by changing the append instead of going to the body of the page i use de body of the modal!!

**Comment by harvanchik** [comment]
> I solved by changing the append instead of going to the body of the page i use de body of the modal!!

How did you do this?
