### ISSUE TITLE
Selection lost when filtering

### ISSUE THREAD

**Issue by davidescr** [ng-select/ng-select#1247]
**Describe the bug**
Filtering items will lose the selection, if the selected item index is no longer visible. After selection is lost, pressing arrow down will result in the following error in console:

TypeError: Cannot read property 'disabled' of undefined
    at ItemsList._stepToItem (ng-select.js:1509)
    at ItemsList.markNextItem (ng-select.js:1341)
    at NgSelectComponent._handleArrowDown (ng-select.js:3126)
    at NgSelectComponent.handleKeyDown (ng-select.js:2495)
    ...

The line is the following (in items-list.ts):
" if (this.markedItem.disabled) {"
because markedItem is undefined

**Reproducbile example**
[https://angular-qchw8u.stackblitz.io](https://angular-qchw8u.stackblitz.io)

**To Reproduce** 
Steps written in the example

**Expected behavior**
If the selected item index is out of the new range, select the first visible element

**Desktop (please complete the following information):**
 - OS: Linux Xubuntu 18.04.2 LTS
 - Browser Chrome
 - Version 75.0.3770.100

**Comment by varnastadeus** [comment]
thanks for well-defined description and reproduce steps, gonna fix it today 👍
