### ISSUE TITLE
How to Create Cascading between components

### ISSUE THREAD

**Issue by diegosliver** [ng-select/ng-select#1251]
**Is your feature request related to a problem? Please describe.**
Hello guys!

I believe that my case is a technical doubt.

I need to use ng-select by cascading another ng-select.

For example, I have an ng-select that uses a list of countries
` 
var countries = [{
  id: 1,
  name: 'Brazil'
},
{
 id: 2,
name: 'USA'
}];
`
and another ng-select using a list of states, which should only display the states related to the selected country in the previous ng-select

`
var states = [{
   id: 1,
   countryId: 1,
   name: 'Sao Paulo'
},
{
  id: 2,
  coutryId: 2,
  name: 'New York'
}];
`
He likes to know the best way to make this cascade.

**Comment by varnastadeus** [comment]
just filter `states` array after each selection of countries 🤔
