### ISSUE TITLE
ng-option-tmp doesn't work in v3.0

### ISSUE THREAD

**Issue by elementalPRESS** [ng-select/ng-select#1255]
After update to version 3.0 the templates for `ng-option-tmp` are not shown anymore.

 - Browser chrome
 - Version 75
 - Angular 8.1

**Comment by varnastadeus** [comment]
1. go to the demo page 
2. fork example and create reproducible case

**Comment by elementalPRESS** [comment]
ok, I could get it to work...

**Code before v3.0:**
`<ng-template ng-option-tmp let-item="item" let-index="index" let-search="searchTerm" *ngIf="viewType == view.TYPE1>
	...
</ng-template>
`

**Code for v3.0:**
`<ng-template ng-option-tmp let-item="item" let-index="index" let-search="searchTerm">
	<ng-container *ngIf="viewType == view.TYPE1>
		...
	</ng-container>
</ng-template>`

**Comment by varnastadeus** [comment]
this happens because angular now resolves @ViewChild differently and custom templates in ng-select should be static

**Comment by dzonatan** [comment]
@varnastadeus is there a specific technical reason why static templates are used now? I can't find a need for that (also `static: false` is a default). 
This adds some limitation to the way you can use `ng-select`. 
Previously you could have a wrapper component for `ng-select` that includes your corporate design defaults with the ability to override everything that `ng-select` provides.
Now, since static templates are used, this becomes super tricky to achieve.

**Comment by varnastadeus** [comment]
Most of the time you define your template and during the lifetime of ng-select, it doesn't change. If, let say your option needs to have different look you should define `ng-option-tmp` once and do the conditions inside of the template. 

Maybe some of the templates could be made dynamic but I didn't get any use cases for that. @dzonatan can you elaborate more on your use case?

**Comment by amazkovoi** [comment]
@varnastadeus firstly, thank you for building such a solid and versatile component! We love using ng-select, and I think it’s the most complete and flexible select/auto-complete component out there.

We have recently upgraded to ng-select 3.0.6 (and Angular 8) and also hit this issue.

Our use case: we have built a “wrapper control” around ng-select. The wrapper control allows us to re-use some logic and look and feel across all usages of ng-select within our application.

The wrapper control accepts templates, and passes them to ng-select. For example, if the place where the wrapper control is used declares the ng-multi-label-tmp template, it will be passed to the ng-select. This allows the users of the wrapper control to decide which custom templates to use (if any).

To make this work, we had to use conditional logic around the templates that are passed to ng-select. This worked very well in older versions of ng-select.

I am guessing that our use case is very similar to @dzonatan 's 

The usage of “static: true” in ng-select when injecting custom templates, stops this functionality from working. As far as I can tell there is no way for us to have the same (awesome) flexibility that we had before. i.e. we cannot have a reusable wrapper control in place, as it cannot conditionally pass templates to ng-select.

It seems the main benefit of having “static: true” for templates is to have access to templates inside ngOnInit(), which ng-select does not need. The default now is (and will be in Angular 9) “static: false”, which allows for greater flexibility, which existed in previous versions.

To test, I have forked ng-select and set static to false, which appears to work very well. 

Would it be possible to change static to false in ng-select?

I believe it will allow for greater flexibility, and also will make it more backwards compatible, as a few people seem to run into similar issue's when upgrading: https://github.com/ng-select/ng-select/issues/1344 https://github.com/ng-select/ng-select/issues/1306

Again, thanks a lot for your awesome work!

**Comment by lucagouty** [comment]
@varnastadeus any thoughts on @amazkovoi suggestion ? 

As far as I can see using `static: false` doesn't create any issue and allow greater flexibility, also it's default angular behavior.

For now the only way we found was to copy default templates from ng-select and use them along with our custom templates 😞

**Comment by varnastadeus** [comment]
I agree, in case of wrapper control there is not much you can with static templates so this should be definitely changed :+1

**Comment by amazkovoi** [comment]
@varnastadeus, thanks for the reply!

Would it be possible to make a release of ng-select with this change?
