### ISSUE TITLE
Incorrect bundle import

### ISSUE THREAD

**Issue by Surecom** [ng-select/ng-select#1256]
**Describe the bug**
Just install 3.0.0 version of @ng-select/ng-select package and open ng-select-ng-select.js file under fesm2015/fesm5/bundles folders:
ɵɵdefineInjectable - incorrect name of import

**Expected behavior**
defineInjectable - is correct import instead of ɵɵdefineInjectable

**Screenshots**
![image](https://user-images.githubusercontent.com/7001010/60827132-2ea30200-a1b8-11e9-8c88-9d349d22b331.png)
![image](https://user-images.githubusercontent.com/7001010/60827423-d1f41700-a1b8-11e9-998f-8325c9c4bf17.png)
![image](https://user-images.githubusercontent.com/7001010/60827372-bf79dd80-a1b8-11e9-8fd2-152d71028316.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.5
 - Browser Chrome
 - Version 75.0.3770.100

**Comment by varnastadeus** [comment]
imports are correct, it seems that the library built with angular v8 is not backward compatible with previous angular versions so you shouldn't use `ng-select@3.x.x` with angular pre-8.

Solutions: 
- update to angular 8
- don't use `ng-select@3.x.x` with older versions

**Comment by bxh566** [comment]
@varnastadeus  Some fixes are not included in the older versions under 3.0.0, e.g. issue 620.
Is it possible to release 2.x.x include these fixes, to continue supporting angular v6/v7?

**Comment by ohabash** [comment]
so how do i use ng-select with angular 7... I cant find a version that works

**Comment by ohabash** [comment]
So people in NG7 cannot use ng-select?
