### ISSUE TITLE
 ng-label-tmp not working

### ISSUE THREAD

**Issue by RanjeetEppa18** [ng-select/ng-select#1258]
<ng-select
      [items]="presets$ | async"
      [multiple]="true"
      [closeOnSelect]="false"
      [hideSelected]="true"
      bindLabel="title"
      bindValue="_id"
      [hideSelected]="true"
      (add)="select($event)"
      [(ngModel)]="presetSelect"
      (change)="changed(presetSelect)">

        <ng-template ng-label-tmp let-item="item" let-clear="clear">
            <span class="ng-value-icon left" (click)="clear(item)" aria-hidden="true">×</span>
            <span class="ng-value-label text-white" [style.background-color]="item.kolor">{{item.title}}</span>
        </ng-template>

<ng-select>

This code not generating the output as it should be.
This is just binding default options UI , Do you know why ?
But working fine if I use ng-option-tmp .

**Comment by varnastadeus** [comment]
create stackblitz example

**Comment by RanjeetEppa18** [comment]
It will take time , 
Can you please tell me what's wrong by looking the code ? , OR I am good with code.

**Comment by varnastadeus** [comment]
1. go to https://ng-select.github.io/ng-select
2. find appropriate example
3. press stackblitz button
4. boom you have stackblitz ready

**Comment by RanjeetEppa18** [comment]
I will close it for a while

**Comment by Chaitanya-32** [comment]
What is the resolution for this issue ?

**Comment by RanjeetEppa18** [comment]
@Chaitanya-32 I found that It is working fine, I misunderstood the concept.
Here is working example https://ng-select.github.io/ng-select#/templates

**Comment by hemanthkumarnr6361** [comment]
> @Chaitanya-32 I found that It is working fine, I misunderstood the concept. Here is working example https://ng-select.github.io/ng-select#/templates

Works only when [editableSearchTerm]="false"
For "true" scenario it is having issues.
