### ISSUE TITLE
Dropdown missplaced since 2.20.1 with appendTo

### ISSUE THREAD

**Issue by stephanecot** [ng-select/ng-select#1259]
Since 2.20.1, the dropdown is missplaced when i used: appendTo="body".

![Capture](https://user-images.githubusercontent.com/49247624/60894421-e68ce980-a262-11e9-9b5d-05d0122460a1.PNG)
==> I use something like that:
`
<ng-select [items]="articleFamillyList"
                               bindLabel="label"
                               bindValue="code"
                               appendTo="body"
                               formControlName="familly"
                               [searchFn]="refObjectSearchFn"
                               placeholder="--- Select a familly ---">
                      <ng-template ng-label-tmp let-item="item">
                        {{ item.code }} - {{ item.label }}
                      </ng-template>
                      <ng-template ng-option-tmp let-item="item" let-index="index" let-search="searchTerm">
                        <span [ngOptionHighlight]="search">{{ item.code }} - {{ item.label }}</span>
                      </ng-template>
                    </ng-select>
`

Exemples:
Version: 2.20.1 (the dropdown not perfectly align, but less than in my app)
https://stackblitz.com/edit/angular-6bsddn

Version: 2.19.0 (the dropwn down is perfectly align)
https://stackblitz.com/edit/angular-8umxey

**Comment by varnastadeus** [comment]
you should use 
```css
body {
  position: relative;
}
```

**Comment by stephanecot** [comment]
It's change nothing.

**Comment by varnastadeus** [comment]
it does in your stackblitz examples

**Comment by stephanecot** [comment]
now in stackblitz, my "bug" is inverted.
It work in 2.20.1 and not working well in 2.19.0.
I have the exact oposite in my app...

**Comment by varnastadeus** [comment]
<img width="1183" alt="Screenshot 2019-07-09 at 17 35 04" src="https://user-images.githubusercontent.com/17824796/60896973-eba46580-a26f-11e9-8cb2-6180dce63def.png">

It works in both examples for me

**Comment by stephanecot** [comment]
Ok sorry, my mistake.
I remove appendTo="body" to the first exemple to test something, and I forget that auto save...
So with this, it's working, but not in my app...

**Comment by andreash92** [comment]
@stephanecot did you find any solution? I am also using `appentTo="body"` and `body {position:relative}` in my styles but it doesn't work. 
In my case it seems that the position is correct when the page has scroll bar

**Comment by stephanecot** [comment]
Nop, I don't find any solution. I must have a "bad" css somewhere in my (big) page that cause this issue.
You must be right with the scrollbar. 
I have another project where I used the 3.x version, It's work only in mobile  mode, but I have a scrollbar.

**Comment by oliverguenther** [comment]
We also experience this in our project despite the `appendTo` container having `position: relative` set. It happens with `body` as well as with smaller containers where this definitely worked before. We're on `2.20.3` still so I'm trying upgrading next

**Comment by oliverguenther** [comment]
This is connected to the `body` or append to wrapper being `100%` in height. When the dropdown is inserted, it's initial height is 2px and causes the window to grow, in our case resulting in a scrollbar to be visible for a short period of time.

That shifts the entire content to the left, causing this offset.

Here's an example that causes the dropdown to be moved to the left by the width of the scrollbar (which in stackblitz is narrow): 

https://stackblitz.com/edit/angular-fzmu56?file=src/app/app.component.html

**Comment by oliverguenther** [comment]
This is still an issue for us. I tracked it down to the `.ng-dropdown-panel` class having a border of 1px which gets inserted _before_ the position is set, resulting in it sticking at the bottom and extending the container size.

If we could get an additional class on the dropdown such as `opened` or `positioned`, then it would be possible to set that border only when the position has been performed.

**Comment by MonstraG** [comment]
Updated to 3.7.2, still happening with  `appentTo="body"` and `body {position:relative}`.

**Comment by andreash92** [comment]
> Updated to 3.7.2, still happening with `appentTo="body"` and `body {position:relative}`.

Check this out to learn why is still happening  https://github.com/ng-select/ng-select/issues/1404#issuecomment-548008332

**Comment by MonstraG** [comment]
> Check this out to learn why is still happening [#1404 (comment)](https://github.com/ng-select/ng-select/issues/1404#issuecomment-548008332)

Thanks!

**Comment by musman92** [comment]
problem still exist any other solution

**Comment by koliaZ** [comment]
i have ng-select in material ui popup and has misalign issue
![image](https://user-images.githubusercontent.com/11311299/93351946-f9298800-f842-11ea-81d1-7f06aae3f0f4.png)
and I was able to solve it by removing this style property (or set it to 'auto') and there is no need to set position:relative
![image](https://user-images.githubusercontent.com/11311299/93352970-13179a80-f844-11ea-8835-89bee25010fa.png)

ng-select "3.7.3"

**Comment by juona** [comment]
I wouldn't be able to update to ng-select@3+ anyway, so a work-around is the only option. Here's something to try. In global styles add:

```
.ng-dropdown-panel {
    top: 0;
    left: 0;
}

.ng-select .ng-dropdown-panel {
    top: auto;
    left: auto;
}
```

This will ensure that the panel spawns in the top-right corner. Its height is limited to 240px whereas the width is set to 100%, so it should never overflow the screen, thus saving you from the scrollbars.
