### ISSUE TITLE
Incorrect name of method defineInjectable in bundle in 3.0.0 version of ng-select

### ISSUE THREAD

**Issue by Surecom** [ng-select/ng-select#1260]
Parent issue - https://github.com/ng-select/ng-select/issues/1256

Don't tell me about Angular 8, because you have in repository incorrect bundles, how you get it - i don't know, thats why i ask you to fix it. **Otherwise I would create PR with fixes.**

Somehow in package you have incorrect imports and usage methods from angular/core
https://angular.io/api/core/defineInjectable - is correct one. 

Don't ignore - please fix.

**Comment by varnastadeus** [comment]
As you can see from your link it is deprecated. Also, those bundles are auto-generated using `ng-packagr`.

 I already provided an explanation and solution in the previous issue https://github.com/ng-select/ng-select/issues/1256#issuecomment-509637172

**Comment by Surecom** [comment]
It is not a solution, you just waved away from the fix the issue

**Comment by varnastadeus** [comment]
what fix do you want? No one told you that version 3.x.x will be backwards compatible with previous angular versions

**Comment by Surecom** [comment]
WHY are you talking about that I have ?? you have in your repository incorrect import like ɵɵdefineInjectable word - what is that ? when **defineInjectable** is correct one, i have no idea how you get it, but it is

**Comment by varnastadeus** [comment]
you clearly don't understand what I am talking about. Have a good day

**Comment by Surecom** [comment]
Angular 8 doest have ɵɵdefineInjectable service... you ignore your users - have a nice day... 
good approach - this issue i will not fix, this issue is not our problem, you looks like junior

**Comment by varnastadeus** [comment]
it doesn't have indeed -https://github.com/angular/angular/blob/58be2ff88400d7dc876d357f8cc3eb01b0912aae/packages/core/src/di/interface/defs.ts#L141

**Comment by Surecom** [comment]
and this i must put from you out, i got everything i need. unfortunately you have to learn how to have a conversation with people in bug reports. nothing personal, just a business
