### ISSUE TITLE
Dropdown does not close (CD related issue)

### ISSUE THREAD

**Issue by dbdkoptro** [ng-select/ng-select#1261]
First of all thank you so much for the awesome work!

I am facing problems in some of my app pages (sorry but I could not reproduce in stackblitz.com):

_The dropdown panel does not close when clicking out_ 

This happens when I update from version 2.20.0 -> **2.20.1** (newer versions do not work either).

I can see you made some rework on DropdownPanel in 2.20.1, adding this:

```
this._zone.runOutsideAngular(() => {
      merge(
            fromEvent(this._document, 'touchstart', { capture: true }),
            fromEvent(this._document, 'mousedown', { capture: true })
      ).pipe(takeUntil(this._destroy$))
      .subscribe($event => this._checkToClose($event));
});
```

When I debug I see the `close()` method is being called (`isOpen` set to `false`) but ChangeDetection is not run :(

However if I emit the `outsideClick` inside Angular zone, ChangeDetection is run normally and the `markForCheck()` call in `close()` method is now useful, solving my issue:

```
this._zone.run(function() {
    this.outsideClick.emit();
});
```

I can fix it locally triggering `detectChanges()` when close is emitted, but I would appreciate a lot if anyone can give me some ideas about why this could be happening.

Also, would changing the `markForCheck()` call in `close()` method by a `detectChanges()` as in `open()` make sense?

Thank you again!

**Comment by varnastadeus** [comment]
without reproducible example there is not much we can do
