### ISSUE TITLE
If value type of bindValue is Number , the option don't choose with the same value in String type

### ISSUE THREAD

**Issue by pichlou** [ng-select/ng-select#1263]
Hi 
I am using ng-select with version 2.20.5
If I use property "id":2 in bindValue, I can't choose an option with passing id equal to "2"

**Comment by varnastadeus** [comment]
I don't quite understand the problem, create reproducible example

**Comment by pichlou** [comment]
```
<ng-select formControlName="CurrencyId" [items]="currencies"
           bindValue="id" bindLabel="abbreviation" placeholder="currency">
     <ng-template ng-label-tmp ng-option-tmp let-item="item" let-index="index"
            let-search="searchTerm">
           <span [ngOptionHighlight]="search">
                {{item.abbreviation}} - {{item.title}}
           </span>
     </ng-template>
</ng-select>
```

This is my code; I used the following array for items :
`currencies = [{"id": 2 , .....} , {"id":3 , ....} , ....]`
If I set CurrencyId in formGroup to "2" (String) value; the option can't select.
`this.myForm.get('CurrencyId').patchValue("2");`
I passed the CurrencyId with 2 (Number) value and it worked correctly!
`this.myForm.get('CurrencyId').patchValue(2);`

**Comment by varnastadeus** [comment]
so value types must match while using default comparer, you can provide your own `[compareWith]` function
