### ISSUE TITLE
Adapt Documentation/ReadMe to ng-option-highlight package

### ISSUE THREAD

**Issue by clemensul** [ng-select/ng-select#1264]
# Description

`ngOptionHighlight` is decribed as an Directive in the [ReadMe](https://github.com/ng-select/ng-select#other). There is no information that it is only available in a separate package.
Since it is a breaking change with v3 (as described in the changelog) the documentation should be in sync.

# Additional context

V3 Issue: #1250

**Comment by EddieBenji** [comment]
How does the ngOptionHighlight should be used now?
should I import the ngOptionHighlight directive separately in my module?

**Comment by EddieBenji** [comment]
I noticed it is needed to add the **"@ng-select/ng-option-highlight": "0.0.1",** in the package json, and you still need to import it in your module:
**import { NgOptionHighlightModule } from '@ng-select/ng-option-highlight';**
```
imports: [
NgOptionHighlightModule
]
```


However, when trying to use something similar to what you show in https://github.com/ng-select/ng-select/blob/master/src/demo/app/examples/forms-custom-template-example/forms-custom-template-example.component.html (line 17)
while typing in the view, the list doesn't get updated accordingly to what the user typed. 
This may be a bug, or maybe the documentation (example) should be updated, please. I will really appreciate it your input.

**Comment by EddieBenji** [comment]
Any update on the ng-option-highlight library @varnastadeus ?
thanks
