### ISSUE TITLE
Typeahead - submit selection while still loading items

### ISSUE THREAD

**Issue by PiotrTecza** [ng-select/ng-select#1267]
**Describe the bug**
Starting from v2.4.0 it's not possible to submit search term (by pressing enter) when loading = true. It works fine for v2.3.6

**Reproducbile example**
[Example](https://codesandbox.io/s/ngselect-od4kd) working example with v2.3.6. Once updated to v2.4.0 or above it's not working.

```
<ng-select
        [multiple]="true"
        [addTag]="true"
        [items]="suggestedItems | async"
        (change)="onSelectionChange($event)"
        [typeahead]="suggestionSubject"
        [loading] = "true" -- constantly true for demo purpose
    >
    </ng-select>
```

**To Reproduce** 
1. Insert search term
2. Press enter (while items still being loaded) 

**Expected behavior**
Search term should be selected and change callback should be triggered.

**Screenshots**
Working solution (v2.3.6)
![image](https://user-images.githubusercontent.com/11783299/61047962-8e77f380-a3d8-11e9-81ec-3561b8229c3b.png)

![image](https://user-images.githubusercontent.com/11783299/61047700-fbd75480-a3d7-11e9-9346-c42511d47522.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome]
 - Version [e.g. 75]

**Comment by varnastadeus** [comment]
there was probably bug before that's why you were able to add tag while loading

**Comment by PiotrTecza** [comment]
That's what I thought as well, but it would be nice to have this possibility anyway

The way we use ngSelect is:
1. user inserts a search term and receives suggestions (this may take a couple of seconds)
2a. user selects a suggestion, which triggers a search query to DB
2b. user submits search term without waiting for suggestions, which triggers a search query to DB

Is it possible to achieve in another way?
