### ISSUE TITLE
Default Item Selected not working

### ISSUE THREAD

**Issue by arun-maddheshia** [ng-select/ng-select#127]
Please fill below information if issuing a bug report. 
### Expected behaviour
Describe how you think it should work
By default I set Yes to selected as Native select works
But nothing selected in Ng-Select
![2](https://user-images.githubusercontent.com/5073214/32881213-876699b6-cad6-11e7-9764-524943b2688d.png)

```
<ng-select formControlName="agree">
    <ng-option selected value="1">Yes</ng-option>
    <ng-option value="2">No</ng-option>
</ng-select>
```

### Actual behaviour
![1](https://user-images.githubusercontent.com/5073214/32881231-8eee214a-cad6-11e7-8180-493fe6ae57eb.png)

**Comment by varnastadeus** [comment]
```selected``` is not supported, you need to set formControlName="agree" as your selected model
