### ISSUE TITLE
Unable to programmatically open select from the DOM

### ISSUE THREAD

**Issue by jpike88** [ng-select/ng-select#1270]
I need a way to open the select box from the Dom:

e.g.

```document.querySelector('ng-select').click()```

```
var event = new MouseEvent('click', {
    'bubbles': true
  });
document.querySelector('ng-select').dispatchEvent(event);

```

```
document.querySelector('ng-select').dispatchEvent(new KeyboardEvent('keypress',{which:'a'}));

```
Currently, it doesn't seem to work for any of the above examples.

This is critical for CI testing, and also when calling a component that isn't easily accessible view ViewChild.

**Comment by varnastadeus** [comment]
we use `element(by.css('span.ng-arrow-wrapper')).click();` in our e2e tests using protractor which works perfectly fine

**Comment by amfische** [comment]
Is it possible to programmatically set the value of `ng-select` from the DOM? Are there any publicly exposed methods for interacting with an Angular app?

**Comment by vanerleo** [comment]
ng-select angular reactive form protrator
```
function ngSelectNth(name, offset) {
		element(
			by.css('[formcontrolname="' + name + '"] span.ng-arrow-wrapper')
		).click();

		element(
			by.css(
				'[formcontrolname="' +
					name +
					'"] .ng-option:nth-child(' +
					offset +
					')'
			)
		).click();
	}
```

**Comment by dongmei-cao** [comment]
> 
> Also if you look at [code](https://github.com/ng-select/ng-select/blob/master/src/ng-select/lib/ng-select.component.html#L1), you can see that you need to dispatch `mousedown` event on `.ng-select-container` instead.

This works perfectly for me.
