### ISSUE TITLE
manipulate search results dropdown (sort / display limit)

### ISSUE THREAD

**Issue by ronbiter** [ng-select/ng-select#1271]
i will be more precies - is there a way to manipulate the search results in the dropdown - sort by name/other user defined sort, limit display of results in dropdown

for example if i want to have max 7 results in dropdown, and as the user keeps typing the search results will focus the results

thanks

**Comment by varnastadeus** [comment]
you can use typeahead [example](https://ng-select.github.io/ng-select#/search) and manipulate data as to display as you wish
