### ISSUE TITLE
groupBy doesn't show the first group

### ISSUE THREAD

**Issue by custompro12** [ng-select/ng-select#1273]
**Describe the bug**
When using the `groupBy` attribute the first group is not shown in the initial dropdown view.  The user has to scroll up to see the first group name.

**Reproducible example**
[Example](https://stackblitz.com/edit/angular-kv5nkd)

**To Reproduce** 
Steps to reproduce the behavior (if example is not provided):
1. Open above example
2. Expand dropdown
3. **Observe that first group named 'MyGroup' is not shown initially**
4. Scroll up in the dropdown
5. Now first group is visible

**Expected behavior**
First group should show up in the dropdown initially.

**Versions**
Bug is reproducible in any version between 2.20.1 and 3.0.3

Version 2.20.0 works as expected.
Tested with Angular 7 and 8.

**Comment by varnastadeus** [comment]
your example doesn't works

**Comment by custompro12** [comment]
> your example doesn't works

Should work now.  It was a Stackblitz [issue](https://github.com/stackblitz/core/issues/930)
