### ISSUE TITLE
Add appendTo to NgSelectConfig

### ISSUE THREAD

**Issue by mgohin** [ng-select/ng-select#1276]
**Is your feature request related to a problem? Please describe.**
All my ng-select must be appended to body, and I have to set it to every ng-select.

**Describe the solution you'd like**
I would like to be able to set it into my `NgSelectConfig` I can set globally.

**Comment by rafaelss95** [comment]
@varnastadeus This can be closed now.

**Comment by mgohin** [comment]
Thanks for the PR ;)
