### ISSUE TITLE
Possibility to access the content of the search field

### ISSUE THREAD

**Issue by Anthony-Jhoiro** [ng-select/ng-select#1277]
**Is your feature request related to a problem? Please describe.**
Whe you type something to find some element and you press enter, it can only select the first one.

**Describe the solution you'd like**
I would like to have the possibility to select all the options corresponding to the search field value when I press enter.

**Describe alternatives you've considered**
As an alternative, I'd like to access the value in the search field.

Have a nice day, Thank you !

**Comment by varnastadeus** [comment]
It is already possible to access search term, use `search` event or `select.searchTerm`
