### ISSUE TITLE
Change detection not working

### ISSUE THREAD

**Issue by Hesesses** [ng-select/ng-select#1278]
Yes, i have read the change detection section on docs :)

```
users: User[];

-

<ng-select formControlName="user_id" id="user_id"
[items]="users"
bindLabel="lastname"
bindValue="id"
(search)="searchUsers($event)"
>

-

searchUsers(event) {
    this.userService.getAll({params: {"searchUser": event.term}}).subscribe((res:any) => {
      // I have tried all of these
      this.users = [...res.data];
      this.users = [...res.data, ...res.data];
      this.users = [...res.data, {id:1, lastname:"lastname"}];
    });
  }
```
The component shows "No items found" all the time, but when clicked away and back to component, then the list of users is shown.

Any ideas?

Using v3.0.3

**Comment by varnastadeus** [comment]
create reproducible example

**Comment by Hesesses** [comment]
@varnastadeus https://stackblitz.com/edit/angular-wlqp2k

**Comment by Hesesses** [comment]
Any ideas?

**Comment by varnastadeus** [comment]
@Hesesses I don't think there are any CD issues in your example, when you are using (search) event your items are populated, but since your `bindLabel` is `lastName` _first_ is not found among items
