### ISSUE TITLE
Preselection not present in list

### ISSUE THREAD

**Issue by mgohin** [ng-select/ng-select#1283]
**Describe the bug**
Pre selected item is shown, but not selected in the dropdown list.
I had this problem because ids where different from the preselected element and list I got from webserver.

Maybe it's a desired behavior to show selection that have been available at some moment, but I'd like not to.

**Reproductible example**
https://stackblitz.com/edit/angular-6cwhed

**Additional context**
 - angular 8
 - ng-select 3.0.3

**Comment by varnastadeus** [comment]
your `compareById` compares ids and there is none that matches `02` that's why it is not selected

**Comment by mgohin** [comment]
> I had this problem because ids where different from the preselected element and list I got from webserver.

I'm aware of the problem on my side BUT why is the preselected item shown in the input ? I did not found any option to prevent from preselecting items not in items list

**Comment by varnastadeus** [comment]
this is by design, you can clear your model when you get a response from the backend
