### ISSUE TITLE
If ng-select is rendered in small block/space, and it has long values there is no way to see whole value

### ISSUE THREAD

**Issue by metodribic** [ng-select/ng-select#1284]
**Describe the bug**
If ng-select is rendered in small/narrow space and items are rather long, ng-select by default truncate the strings and therefore user can not see the whole value, which in some cases could be crucial because values could be different only by the ending.

**Reproducible example**
[Example](https://stackblitz.com/edit/angular-zc5eg7) which reproduces described behaviour

**To Reproduce** 
Steps to reproduce the behavior (if example is not provided):
1. Open ng-select
2. **ERROR**: All values looks the same but all of them has different ending

**Expected behavior**
There should be mechanism to show full value. A simple HTML title attribute would be sufficient

**Screenshots**
![Screenshot 2019-07-26 at 07 20 47](https://user-images.githubusercontent.com/6840850/61927673-f3555100-af75-11e9-8212-a1d238f8d22d.png)

**Desktop (please complete the following information):**
 - All browser

**Smartphone (please complete the following information):**
 - All Devices

**Additional context**
If needed I can implement proposed or any other solution

**Comment by varnastadeus** [comment]
should work
```html
<ng-template ng-option-tmp let-item="item">
    <span  [title]="item.name">{{item.name}}</span>
</ng-template>
```

**Comment by metodribic** [comment]
Oh I see! I somehow overlooked _Templates_ section in documentation. Thank you!
