### ISSUE TITLE
Width of ng-select is autosized to selected value if it is longer.

### ISSUE THREAD

**Issue by wmalaschonok** [ng-select/ng-select#1285]
**Describe the bug**
If a selected value in drop down is longer then a select box, then the box width extends to the lenght of the selected value.
CSS configuration of parent element width (if any exists) is ignored.

**Reproducbile example**
https://ng-select.stackblitz.io/
Select a long string (e.g. "Vilnus Vilnus Vilnis ..." in 'One' or "Kaunas Kaunas Kaunas ..." in 'Two')

**To Reproduce** 
To reproduce this behavior was created a table with two columns with an ng-select in each one of them. 
https://stackblitz.com/edit/ng-select?file=app%2Fapp.component.ts 

> 
<table>

        <th>0ne</th>
        <th>Two</th>
        <tr>
          <td>
            <ng-select [items]="cities"
                      bindLabel="name"
                      placeholder="Select city"
                      [(ngModel)]="selectedCity">
            </ng-select>
          </td>
          <td>
            <ng-select [items]="cities2"
                   bindLabel="name"
                   bindValue="id"
                   [multiple]="true"
                   placeholder="Select cities"
                   [(ngModel)]="selectedCityIds">
            </ng-select>
          </td>
        </tr>
   </table>

**Expected behavior**
The drop down box is not changing its width by selecting a long text value.
If there are more ng-select elements in the same row and their behavior is defined (e.g. {min-width: 15%} or {width: 10%}), then they are not changing their width over or under these values. 

**Screenshots**

![1](https://user-images.githubusercontent.com/16102431/61939257-265a0d80-af93-11e9-9dc4-7eb1f61c5527.png)

_**Selected one long value**_
![2](https://user-images.githubusercontent.com/16102431/61939267-2b1ec180-af93-11e9-9252-b6e93d2475cb.png)

_**Selected two long values**_
![3](https://user-images.githubusercontent.com/16102431/61939271-2e19b200-af93-11e9-92ef-081e39cebabc.png)

_**Both selected values are shorter then the drop down box width**_
![4](https://user-images.githubusercontent.com/16102431/61939276-307c0c00-af93-11e9-92d1-3ee3ca639420.png)

_**Second drop down box is narrowed down, so its values are all invisible before you select one**_
![5](https://user-images.githubusercontent.com/16102431/61939950-b8aee100-af94-11e9-8cca-a9f510a77c24.PNG)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: chrome 75.0.3770.142

**Comment by varnastadeus** [comment]
I am not sure what behaviour you are expecting, by default `ng-select` grows to available space and if you want to fixed-width you should define it in your style sheets

**Comment by cyberbobjr** [comment]
With this override, you can fix your problem (SCSS)

```
  .ng-value-container {
    .ng-value {
      white-space: normal !important;
    }
  }
```
