### ISSUE TITLE
Issue with ng-select check-box button.

### ISSUE THREAD

**Issue by vijaysahu12** [ng-select/ng-select#1286]
If (maxselectedItem == 2 )
then 
expectation: It should not allowed to select more then 2 values/tags either clicking on checkbox or items
BUT Reality: 

It's true that we are not able to select more then 2 while clicking on top of item but able to click on more then 2 check-boxes .

From UI perspective it does not look good. 

Please suggest how to disable other check-box if we have already selected 2 items.

**Comment by varnastadeus** [comment]
since checkboxes are part of your code, you should disable them yourself

**Comment by vijaysahu12** [comment]
But checkbox are binding on drop-down from your side..

**Comment by varnastadeus** [comment]
everything that is in custom template is your side
