### ISSUE TITLE
Expand model

### ISSUE THREAD

**Issue by ilvenos** [ng-select/ng-select#1287]
Hi,
I need add extra field in properties depends of model.

My code:
```
                        <ng-select *ngIf="langDict" [items]="langDict"
                                  bindLabel="Name"
                                  name="lang"
                                  [multiple]="true"
                                  [(ngModel)]="test">
                      </ng-select>
                      <span *ngFor="let item of test; let i = index">
                        <input name="test_{{i}}" [(ngModel)]="item['Description']">
                      </span>
```

When I add new record, everything works good, but when I want edit data loaded from API (assigne data from API to object test) I lost value Description. 
Is it possible to do it with this module?

**Comment by varnastadeus** [comment]
This module just displays the data, you need to insure your added property remains after data was loaded in your application code
