### ISSUE TITLE
Cannot show image inside ng-option

### ISSUE THREAD

**Issue by tungns1** [ng-select/ng-select#1290]
### Expected behaviour
Hi, base on [this stackblitz](https://stackblitz.com/run?file=src/search-default-example.component.html) demo. It's able to have image inside ng-option

### Actual behaviour
But it's show html code now

![Capture1](https://user-images.githubusercontent.com/40974920/62150161-76382c00-b327-11e9-97c8-eb44fd0f8d59.PNG)

There is a special way to achieve that?
Thx.

More Info
ng-select version: 2.20.5

Angular 6

browser: Chrome/firefox/ie

**Comment by varnastadeus** [comment]
use latest version

**Comment by tungns1** [comment]
> use latest version

So i have to update Angular 8 and ng-select 3 to show image?

**Comment by varnastadeus** [comment]
check fix commit https://github.com/ng-select/ng-select/commit/7ccea9d, there is an example how images were handled before fix
