### ISSUE TITLE
close event does not triggered when clicking out-side window

### ISSUE THREAD

**Issue by vijaysahu12** [ng-select/ng-select#1291]
**My Code Sample**
 <ng-select
                    #select
                    placeholder	='Select Weekly/off'
                    [items]="emp.WeeklyOff"
                    [multiple]="true"                    
                    bindLabel="name"
                    bindValue="id"
                    maxSelectedItems= 2
                    [selectableGroup]="false"
                    [closeOnSelect]="false"
                    notFoundText='no result found!'
                    [(ngModel)]="emp.WeeklyOffSelected"
                    (click)='onWeeklyOffDropDownOpen(emp)'
                    (change)='onWeeklyOffDropDownChange(emp)'
                    [isOpen]='emp.WeeklyOffIsOpen'              
                    >
                    <ng-template ng-option-tmp let-item="item" let-item$="item$" let-index="index">
                        <input class="ra-checkbox" [disabled]="!item$.selected && emp.WeeklyOffSelected.length == 2" id="item-{{index}}" type="checkbox" [ngModel]="item$.selected"/> <span> {{item.name}} </span>
                    </ng-template>

**Once used the [isOpen] property**
**(close)** event does not trigger. 

Is there any way to close the drop-down if clicking on window screen. 

**Or please suggest me what is the best possible solution for this**

**Comment by varnastadeus** [comment]
this is by design, if you set [isOpen] true then it will never close, check the docs

**Comment by vijaysahu12** [comment]
Yes I agree with this point but is there any other way to set the isOpen property to false ?

**Comment by varnastadeus** [comment]
if you want to control it programmatically you should use ng-select `close/open` methods
