### ISSUE TITLE
How to disabled the ng-select default css theme

### ISSUE THREAD

**Issue by vijaysahu12** [ng-select/ng-select#1292]
**Seems like ng-select rendered on page even without referring the default theme css file**

![ngselectcss](https://user-images.githubusercontent.com/5511469/62151485-0c675480-b31e-11e9-92f6-93cb1a420cb4.PNG)

**How to stop rendering the css files**

**Comment by varnastadeus** [comment]
those are core css which styles that allows ng-select to work properly, you can't remove them and they are included in component itself
