### ISSUE TITLE
Placeholder value not showing up -  Angular 7 (used ngx-bootstrap and ng2smart table)

### ISSUE THREAD

**Issue by radsin99** [ng-select/ng-select#1293]
The placeholder is not showing up on the dropdown bar
`  <div class="form-group">
                  <label>Select Dropdown</label>
                  <div class="input-group input-group-sm">
                    <select class="form-control" name="id" [(ngModel)]="id" #oldValue = "ngModel">
                        <option [value]="null" disabled="true" [selected]="true">Placeholder text..</option>
                      <option *ngFor="let entity of entityList" [value]="entity.id">{{entity.entity}}</option>
                    </select>
                    <span class="input-group-btn">
                      <button type="button" id="getlist" disabled (click)="getEntityList(id)" class="ml-10 btn btn-info btn-sm">Loading...</button>
                    </span>
                  </div>
                </div>`

**Comment by varnastadeus** [comment]
create reproducible example
