### ISSUE TITLE
Add data binding for current search term

### ISSUE THREAD

**Issue by cciccole** [ng-select/ng-select#1299]
**Is your feature request related to a problem? Please describe.**
It would make life easier to build custom behavior related to searching if the component supported data binding for the current search term.

**Describe the solution you'd like**
A new API field `[searchTerm]` or similar that reflects the current state of the search field.

**Describe alternatives you've considered**
Right now I have to keep track of current search term with callbacks. Currently to do this requires coordination across multiple callbacks of `(search)`, `(clear)`, and `(close)` because all of these modify the current search term. Providing the data binding is much simpler.

**Comment by varnastadeus** [comment]
searchTerm is already available via `select. searchTerm`

**Comment by cciccole** [comment]
Maybe I'm missing something but could you elaborate on how to properly access this?

Perhaps give a modified version of a stackblitz from the first item on this page [(link)](https://ng-select.github.io/ng-select#/bindings) but where the text underneath the selector indicates the current search term instead of the current selection.

**Comment by varnastadeus** [comment]
this is how you can access it easily in HTML. In typescript, you would need to use `@ViewChild`

```html
search term: {{select.searchTerm}}

<ng-select 
           #select
           [items]="defaultBindingsList"
           [(ngModel)]="selectedCity">
</ng-select>
```

**Comment by cciccole** [comment]
Thanks. I guess you can close this if you want. Else it still does make sense to me to offer this via component API
