### ISSUE TITLE
How to  set input value from component.ts and  check dropdown value? 

### ISSUE THREAD

**Issue by sohelasique** [ng-select/ng-select#1301]
I am using ng select multi select  option .   input field data  is 000123 but database data 123  i can not set  componet.ts file to  setValue in input  so i find data form dropdown.  also i can't select  input data trought component.ts only when  html view   select that time select data.

**Comment by sohelasique** [comment]
How to clear  search value use  multiselect  .

**Comment by sohelasique** [comment]
![issue (1)](https://user-images.githubusercontent.com/53220308/62681603-b3f81d00-b9d7-11e9-97c2-373836018aeb.jpg)
Please see this image .

**Comment by sohelasique** [comment]
i am using     <ng-select    
				  [ngClass]="{'ng-error':(f.product.touched || f.product.dirty || submitted) && f.product.errors?.required }" [typeahead]="filter" placeholder="Select Product# *" [addTag]="addTag" [clearOnBackspace]="true" [dropdownPosition]="'bottom'" [items]="ProductDropDownList" bindLabel="_source.value"  bindValue="_source.value" [loading]="ProductnameLoading" formControlName="product"  (change)="onSelectProduct($event)" (keyup)="onProductNameSearch($event)"    [multiple]="true" [(ngModel)]="seletedproductList"  >  

this is my html code .  al the first   i have some product id 5267,52678,42150 ,521 but exel show 05267, 52678, 42150,00521 any one manual  search   i remove 00   call api  data show but ng select input not found data ,  
![issue4](https://user-images.githubusercontent.com/53220308/62761875-6e098a80-baa5-11e9-9d9d-1ae7a5d354b2.png) how to disable enter select filed   .how to block if json have no data  match   can't add  this value  [(ngModel)]="seletedproductList"  field .

**Comment by varnastadeus** [comment]
I find it extremely hard to understand what problems do you have, pasting screenshots and code doesn't help. Please structure and formulate it as simple as possible

**Comment by sohelasique** [comment]
<ng-select
[ngClass]="{'ng-error':(f.product.touched || f.product.dirty || submitted) && f.product.errors?.required }" [typeahead]="filter" placeholder="Select Product# *" [addTag]="addTag" [clearOnBackspace]="true" [dropdownPosition]="'bottom'" [items]="ProductDropDownList" bindLabel="_source.value" bindValue="_source.value" [loading]="ProductnameLoading" formControlName="product" (change)="onSelectProduct($event)" (keyup)="onProductNameSearch($event)" [multiple]="true" [(ngModel)]="seletedproductList" >
1st problem)
if u check i am using  keyup event   when i got same in service i am push data  this.seletedproductList variable . but i could not able to empty search  filled ;
  we use  angular input field  setValue  when we need blank input  so we set input.setValue(null) in component.ts . 
can there  is any option when we search input  field blank  (not in text-area  only search value remove)

2nd problem      in this  section we also use barcode scanner  to paste in in input filled and enter. 
if barcode not detect  manual input .  so i want to add every data through add.component.ts .
if drop down  list data select and also i create event in my add.component.ts  so same key multiple times insert. 
3 rd problem input search  key validation 1st letter not zero .

**Comment by varnastadeus** [comment]
🔝 this doesn't make any sense to me. 

> I am using ng select multi select option . input field data is 000123 but database data 123 i can not set componet.ts file to setValue in input so i find data form dropdown. also i can't select input data trought component.ts only when html view select that time select data.

you should use `[compareWith]`
