### ISSUE TITLE
Ability to disable infinite scroll

### ISSUE THREAD

**Issue by Simon245** [ng-select/ng-select#1302]
**Describe the solution you'd like**
Infinite scroll is a great feature but it would be great if it could be turned off.

Have a boolean to turn off infinite scroll with a default set to true.

**Comment by varnastadeus** [comment]
it is already implemented

**Comment by Simon245** [comment]
> it is already implemented and it is turned off by default

Thanks for answering. Have I mistaken what infinite scroll is?
The issue I have is if you're using the arrow keys and get to the bottom of the list it jumps back up to the top. This feature is great but I would like to be able to turn it off if required. In the docs, it says there is a feature for infinite scroll and I thought it was that, but there is no API to turn it on and off.

**Comment by varnastadeus** [comment]
that's not infinite scroll, it is scroll to marked which is currently enabled by default
