### ISSUE TITLE
promise rejections in addTag get swallowed

### ISSUE THREAD

**Issue by hahn-kev** [ng-select/ng-select#1303]
**Describe the bug**
When using the add tag callback function, if the promise is rejected then the exception is swallowed, it should be logged to the console or something.

**Reproducbile example**
[Example](https://stackblitz.com/edit/angular-dk1acp?file=src/tags-backend-example.component.ts) which reproduces described behaviour

**To Reproduce** 
Steps to reproduce the behavior (if example is not provided):
1. Type in a new value
2. press enter
3. see loading
4. See there's no error in console even though there should be

**Expected behavior**
The rejection should be reported somewhere.

**Comment by varnastadeus** [comment]
ng-select has no interest in errors that's why the error should be handled on the client-side

```js
addTagPromise = (name) => {
        this.backendCall()
          .then(() => {
            // handle success
          })
          .catch(error => {
            // handle error
            console.log(error);
          })
    }
```
