### ISSUE TITLE
Show 2 values with <ng-template> in dropdown list

### ISSUE THREAD

**Issue by aaron170** [ng-select/ng-select#1304]
**Describe the solution you'd like**
Need to show 2 values in the dropdown list e.g. ID - Name

**Here is my code
`<ng-select #businessUnits [items]="model.businessUnits" placeholder="Select Business User" [searchable]="false" bindLabel="name" bindValue="id">
                  <ng-template ng-header-tmp>
                    <input class="form-control" type="text" (input)="businessUnits.filter($event.target.value)">
                  </ng-template>
                  <ng-template ng-label-tmp let-item="item" let-index="index">
                    {{item.id}} - {{item.name}}
                  </ng-template>
                </ng-select>`

Any help would be appriciated.

An Example

![select-example](https://user-images.githubusercontent.com/19680243/62620523-2bc23b00-b937-11e9-8a4f-d6264fd68159.jpg)

Thanks

**Comment by varnastadeus** [comment]
what help do you need? looks like you already figured it out

**Comment by yacinesouilah** [comment]
If I understand what you mean, just use the <br> tag.

<ng-template ng-label-tmp let-item="item" let-index="index"> 
     {{item.id}} - {{item.name}} <br>
     {{ whatever }}
</ng-template>

**Comment by yacinesouilah** [comment]
If I understand what you mean, just use the break tag <br>.

`<ng-template ng-label-tmp let-item="item" let-index="index">
        {{item.id}} - {{item.name}} <br>
        {{ whatever }}
</ng-template>`

**Comment by aaron170** [comment]
Thank guys for the help.

Actually the ID was not displaying in the dropdown list that is generated.
Got the solution like this.

`<ng-select #businessUnits 
[items]="model.businessUnits" 
placeholder="Select Business User" 
[searchable]="false" bindLabel="name" 
bindValue="id"> 
        <ng-template ng-header-tmp> <input class="form-control" type="text"
         (input)="businessUnits.filter($event.target.value)"> </ng-template> 
        
        <ng-template **ng-option-tmp** let-item="item" let-index="index"> {{item.id}} - {{item.name}} 
        </ng-template> 

</ng-select>`

Just changed ng-label-tmp --->   ng-option-tmp... worked for me.

Thanks
