### ISSUE TITLE
change event fires multiple times when using custom search input field

### ISSUE THREAD

**Issue by cciccole** [ng-select/ng-select#1305]
**Describe the bug**
When using a custom search input field with ng-header-tmp, there is an issue with the change event firing multiple times and its payload being incorrect, sometimes holding an event object instead of the current model.

**Reproducible example**
[Stackblitz example](https://stackblitz.com/edit/angular-8aoakb?file=src/template-search-example.component.html)

Note that this stackblitz is a minimally edited version of [this example from the demos](https://github.com/ng-select/ng-select/tree/master/src/demo/app/examples/template-search-example). It has only been changed to input a `(change)` event monitor.

**To Reproduce** 

1. Navigate to the stackblitz example.
1. Open the console to see messages printed there.
1. Open the ng-dropdown
1. Type in some characters to filter the list. For example, `kau`
1. Click on an item to select it. **Note that multiple change messages print to the console, and one of them is an event object itself**

**Note** that this issue doesn't happen when using the native search functionality given by `[searchable]`.

**Note** that  a similar problem occurs with deselecting when `[multiple]` is true.

**Expected behavior**
There should only be one change event.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OSX 10.12.6
 - Browser: chrome 75.0.3770.142 (Official Build) (64-bit), firefox 68.0.1 (64-bit)

**Comment by varnastadeus** [comment]
this happens because of inputs change event is also propagated so you need to add 
```html
<input (change)="$event.stopPropagation()"></input>
```

**Comment by Simon245** [comment]
This is odd. I can make the stopPropagation work on [Stacklbitz](https://stackblitz.com/edit/angular-crfjtg) but I can't get it working on my app.

I thought that it might be that I am using Angular v7 and ng-select v2.16.2 but Stackblitz is fine with those versions.

**Comment by nikkonduru88** [comment]
I tried this: <input (change)="$event.stopPropagation()"></input>

But it did not work for me. It still fires change event multiple times.

**Comment by ayhtut** [comment]
same for me, it is still triggering twice even after $event.stopPropagation() is added.
What I did to overcome this issue is to validate with $event.

> `<ng-select (change)="filterChange($event)">
> 
> public filterChange(arg:any){
> if(arg.type == 'change') return;
> console.log('filter change');
}`

**Comment by seb9465** [comment]
I'm having the same issue on the `change` event of the `ng-select` instance (with multiple being set to true only).
My first event being my newly selected items model and my second event being a classic event (with target, srcElement and other properties).
Not having found any solutions for the moment.

**Comment by Simon245** [comment]
> I'm having the same issue on the `change` event of the `ng-select` instance (with multiple being set to true only). My first event being my newly selected items model and my second event being a classic event (with target, srcElement and other properties). Not having found any solutions for the moment.

I couldn't get the stopPropogation working either so I just went with checking the value. I knew that it needed to have two specific values so checked them first.

```
onChange(event: any): void {
  if (!event.id && !event.title) {
    return;
  }
  ...
}
```

At some point I then removed this, I didn't need it anymore, I think it's after I upgraded to Angular 11 and ng-select 6.1

**Comment by prom00** [comment]
I've had a simular issue. It turned out to not be an issue with ng-select.

When creating a new (test) function in my *.ts file I then added a console.log(event). This turned out to be triggered only once. The issue was in my following code which also edited the value.

**Comment by textheader** [comment]
Try this https://hypertexter.space/questions/trigger-the-function-in-ng-change-each-time-the-same-option-is-clicked-repeatedly
