### ISSUE TITLE
Some ng-templates using *ngif directive don't work properly

### ISSUE THREAD

**Issue by AdamsEric** [ng-select/ng-select#1306]
**Describe the bug**
After ng-select has been updated to make it compatible with angular 8 (ng-select 3.0.6), some templates are not working properly when using the ngIf directive for conditional treatment.

**Reproducbile example**
https://stackblitz.com/edit/ng-select-template-error?file=src/multi-select-custom-example.component.html

**To Reproduce** 
Add a condition with `*ngIf` in anyone of the following templates:

`ng-label-tmp`
`ng-multi-label-tmp`
`ng-option-tmp`

**Expected behavior**
If condition is true, `ng-template` should be considered.

**Additional context**
Works in ng-select 2.1.0

**Comment by varnastadeus** [comment]
Most of the time you define your template and during the lifetime of ng-select, it doesn't change. If, let say your option needs to have different look you should define ng-option-tmp once and do the conditions inside of the template - that's why they are kept static.
