### ISSUE TITLE
Remove/hide the ng-value list when multiple options are selected

### ISSUE THREAD

**Issue by jmaroa** [ng-select/ng-select#1308]
I'm using the [multiple] option and the custom template to add checkbox for each item in the dropdown list to toggle the selection.

It works pretty neat but I need to know if there is any good approach to remove or hide the selected items from the input list (besides the search input)?

This is the list:
<img width="198" alt="Screen Shot 2019-08-08 at 5 53 14 PM" src="https://user-images.githubusercontent.com/8010072/62744830-9cd02400-ba05-11e9-8ed5-ab5650945f51.png">

Or to be even more clear this from your demo:
<img width="717" alt="Screen Shot 2019-08-08 at 6 00 40 PM" src="https://user-images.githubusercontent.com/8010072/62745085-97bfa480-ba06-11e9-9095-fbbd456a5cd3.png">

the ones marked in red box are the lib's default selected items I want to remove and keep showing the placeholder instead.

Thanks in advance.

**Comment by jmaroa** [comment]
I used this approach:

`
.ng-select.multiselect-dropdown .ng-select-container {
  &.ng-has-value .ng-placeholder {
    display: block;
  }
  .ng-value-container {
    .ng-value {
      display: none;
    }
  }
}
`

But I don't like this css workaround.

**Comment by varnastadeus** [comment]
you can use empty  `ng-multi-label-tmp` with static placeholder inside
```html
<ng-select
    <ng-template ng-multi-label-tmp>
      <span style="display:block" class="ng-placeholder">Select items</span>
    </ng-template>
</ng-select>
```

**Comment by jmaroa** [comment]
@varnastadeus Great!

that's the best approach definitely. Thank you!

**Comment by madushaRavishani** [comment]
@varnastadeus Thanks a lot

**Comment by sudarshansb143** [comment]
@varnastadeus You approach works perfectly, but what if I want to deselect a single item (which is previously selected) ?

![image](https://user-images.githubusercontent.com/43947282/168576224-cec624ba-f60d-4f8d-b254-47d121c42822.png)

I have selected two options and applied hiding functionality. Now, I want to select single item ex. `jaczk Sparrow` then how should I do it ?

One way would be clearAll option which is already there but is there any alternative?

**Comment by antoine1003** [comment]
@varnastadeus You approach works but the place holder is not hiding when typing

![image](https://github.com/ng-select/ng-select/assets/15017551/fb92ca11-066a-497f-955d-cc618300720e)

**Comment by antoine1003** [comment]
Fixed with :

```css
.ng-select.ng-select-multiple.ng-selected-filtered .ng-select-container .ng-value-container .ng-placeholder {
        display: none !important;
}
```
