### ISSUE TITLE
The close callback function does not run within Angular zone.

### ISSUE THREAD

**Issue by frankfajardo** [ng-select/ng-select#1309]
**Describe the bug**
The close callback function does not run within Angular zone. This was not the behaviour on v.2.16.3. It was changed on v.2.20.1 or later, specifically with PR #1188 where it runs the emit outside of Angular zone.

**Reproducbile example**
[See this Stackblitz demo](https://stackblitz.com/edit/ng-select-b32qme?file=package.json) 

**To Reproduce** 
Using the demo link above:
1. Go select 2 city names from the dropdown
2. Click outside of the dropdown to close it.
3. The city names will not be printed. This is the error.
4. If you click on the dropdown without changing the selection, the selected city names will be printed.

**Expected behavior**
It should print the city name as soon as the dropdown closes.

The error will not occur if you do either of these:
- Change the ng-select version to v.2.16.3
- Change the `selectedCities variable within Angular zone.

**Additional context**
I'm not sure if you consider this an error or bug. However, I believe this needs to, at least, be indicated in the component README.

**Comment by frankfajardo** [comment]
Thank you @varnastadeus

**Comment by dbdkoptro** [comment]
@frankfajardo @varnastadeus exactly what I tried to explain here: [1261](https://github.com/ng-select/ng-select/issues/1261) Thank you so much for describing and solving the problem guys!
