### ISSUE TITLE
[searchable] - doesn't find

### ISSUE THREAD

**Issue by xTaz1** [ng-select/ng-select#131]
How I can disable search ? [searchable] - doesn't find

**Comment by varnastadeus** [comment]
use `[searchable]="false"`

**Comment by xTaz1** [comment]
@varnastadeus 
`[ERROR ->][searchable]="false"`

Angular 4.4.4
Angular CLI 1.4.9

**Comment by varnastadeus** [comment]
what version you are using? @xTaz1 it was added in 0.6.0

**Comment by xTaz1** [comment]
@varnastadeus Yes, I used  v 0.4.1.  Amazing, but I installed this library a few weeks ago. Thanks for you help.
