### ISSUE TITLE
Calling writeValue from nested control causes ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by CobusKruger** [ng-select/ng-select#1310]
**Describe the bug**
I needed an ng-select in a nested control and therefore cannot directly use `formControlName` on the ng-select (the form itself is inaccessible). Since there is no API function specifically to set the value, I'm calling `writeValue`.

That works very well in most scenarios, but initial form values cause an ExpressionChangedAfterItHasBeenCheckedError.

**Reproducbile example**
https://stackblitz.com/edit/angular-uir8lt

There are some comments in the code to show what I've tried. The money shot is in `select-container.component.ts`.

**Expected behavior**
The control should display the value specified in the form's initialization (that part works) without the ExpressionChangedAfterItHasBeenCheckedError (that part doesn't).

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 75.0.3770.142

**Additional context**
All this works swimmingly as long as I can bind directly to the form control. But nested controls can't do that.

**Comment by varnastadeus** [comment]
First of all `writeValue` is part of [ControlValueAccessor](https://angular.io/api/forms/ControlValueAccessor) and it is not intended to be called directly. Secondly, I think this issue doesn't fall under bug/feature description and you should seek help at stackoverflow. (how to wrap angular control correctly)

**Comment by CobusKruger** [comment]
@varnastadeus Thanks for responding so soon. 

I just want to clarify a few things:

First, this is not a general "how to wrap a component in Angular" problem. My example was contrived and simply wrapped an ng-select in an empty container, but the problem remains in real-world cases where you have a reusable sub-form containing one or more ng-select components.

Second, the reason I called writeValue, is because there is no separate API call to set the value. If I had instead used [(ngModel)], it would amount to the same thing and cause a call to writeValue. The problem is not the call to writeValue, but that writeValue forces change detection by calling ChangeDetectorRef.markForCheck().

I don't know the context or reasoning behind that, but it certainly isn't required or even very common as part of most writeValue implementations. For example, I have actually wrapped most of Telerik's controls for a previous project, and the same problem doesn't exist there. Not that I'm saying you should copy them (ng-select is awesome), but it unless your writeValue absolutely requires change detection to run at that point, it probably shouldn't.

**Comment by varnastadeus** [comment]
`markForCheck` doesn't forces change detection, it only marks view to be checked when the next change detection cycle will run and it is there for a reason.

There is no direct API to change the value since you should use `ngModel/formControlName` for that purpose which in your case would stop the error to be thrown.

Issues are caused by `ngAfterViewInit()` which is completely unnecessary in your case. You can call `writeValue` directly on ng-select if you set your template resolution as `{ static: true }` which it is. That's why I pointed out to seek for more information on how to wrap component correctly.
