### ISSUE TITLE
Selecting more than 5 thousand record's checkbox in Multi select dropdown.

### ISSUE THREAD

**Issue by Amarnath92** [ng-select/ng-select#1311]
I am trying to select all the items in the drop-down, where it has more than 5 thousand records(two drop-down) in a modal. The modal is taking more time(10 sec aprox) to open, where it is not taking more time if i am not selecting (checked)the items. For selection(what are all the items should be selected) i am binding through the [(ngModel)]. Could you please provide your input this?

**Comment by varnastadeus** [comment]
You need to enable virtualscroll and limit number of shown selected items as shown in examples
