### ISSUE TITLE
Pre-select option not yet loaded in search async

### ISSUE THREAD

**Issue by ChaudhryAtif** [ng-select/ng-select#1312]
This one is similar to custom search example for Template forms, but with different bind and label values: https://ng-select.github.io/ng-select#/search

Say I link an album to its artist. On add, it's fine because I can use the search and save it. In edit mode, I should be able to see my previously selected/saved choice already populated in the field. How do I go about doing that?

Somewhat of a demo of the issue:
https://stackblitz.com/edit/angular-u5gmny?file=src/forms-async-data-example.component.ts

Albums 21-30 are loaded, but album 2 (in selectedAlbum) should be pre-populated.

I can set the form's album control's value to specified id (bindValue), but the bindLabel appears to be the issue.

Hopefully I am making some sense. Let me know if I need to clarify anything.

**Comment by varnastadeus** [comment]
in your case, `ng-select` resolves selected model from items based on the id. 
Since there is no item with id `2` there is no way to resolve item and display label from items array. In that case, your model should have label and id provided.

**Comment by ChaudhryAtif** [comment]
@varnastadeus I do have the label and id that needs to be pre-selected, but I am not able to show it in the select.

**Comment by varnastadeus** [comment]
in other words - your model should be an object
