### ISSUE TITLE
Template for selected option

### ISSUE THREAD

**Issue by Nouxx** [ng-select/ng-select#1315]
**Is your feature request related to a problem? Please describe.**
I'd like to edit the css style of the options I have selected. In the HTML rendering, it refers to `ng-option-selected` css class

**Describe the solution you'd like**
I'm thinking of a template (something like `<ng-template ng-option-selected-tmp...`) to style it the way we want.

**Describe alternatives you've considered**
Having an attribute on the item (selected) to use with *ngIf inside the `ng-option-tmp`.

It can be applied for 'marked' option as well

The only workaround I found is to use *ngIf on the following condition : is my item present in my selected items list ? It's working great but I feel like it could be cleaner

Thanks !

**Comment by varnastadeus** [comment]
what stops you from editing  css style of the options right now?

**Comment by Nouxx** [comment]
Nothing, but my changes aren’t only css linked, for instance, add an icon next to the option value.
I found workarounds but I just thought it would be more straightforward to have a template

**Comment by varnastadeus** [comment]
there is already a template for options`ng-option-tmp`. Also there is `$item` property which has selected flag.

```html
<ng-template ng-option-tmp let-item$="item$" >
       {{item$.selected}}
</ng-template>
```

**Comment by davyalex** [comment]
### 

> ### _tyyuu
Duplicate of #_
