### ISSUE TITLE
close dropdown on blur

### ISSUE THREAD

**Issue by d3x47** [ng-select/ng-select#1319]
I am using ng-select  **ng-footer-tmp** items and when i click on the item a bootstrap modal is opened, at that time i want to close the ng-select dropdown which stays opened in the background. 

How do i close this dropdown panel programmatically on click event.

```
<ng-select ........>
        <ng-template ng-footer-tmp>
                  <div  data-toggle="modal"
                        [attr.data-target]="'#ExclusionLookup_Modal">Lookup Exclusion Clauses                 
                  </div>
        </ng-template>
</ng-select>
```

**Comment by d3x47** [comment]
I found the feature in this example: https://stackblitz.com/run?file=src/forms-async-data-example.component.html

`<ng-select  #select>
(click)="closeSelect(select)"`

` closeSelect(select: NgSelectComponent) {
        select.close();
    }`

**Comment by teja-mindmaster** [comment]
> I found the feature in this example: https://stackblitz.com/run?file=src/forms-async-data-example.component.html
> 
> `<ng-select #select> (click)="closeSelect(select)"`
> 
> ` closeSelect(select: NgSelectComponent) { select.close(); }`

Thanks, it works
