### ISSUE TITLE
How to disable element

### ISSUE THREAD

**Issue by xTaz1** [ng-select/ng-select#132]
I want to disable changing on the some pages. How I can disable `ng-select`?

**Comment by varnastadeus** [comment]
@xTaz1 
use `[disabled]="true/false"` 
or if you use reactive forms, use `enable()/disable()` methods of formGroup. There are examples in demo page.

**Comment by xTaz1** [comment]
works, thank you

**Comment by chrisbenseler** [comment]
@xTaz1 any clue on why in my app the [disabled] is not recognized? The console outputs
Can't bind to 'disabled' since it isn't a known property of 'ng-select'.
My package.json has the latest package
"@ng-select/ng-select": "^0.26.0",

All other properties (from https://github.com/ng-select/ng-select#api) works correctly.

**Comment by Moulde** [comment]
I have this exact issue as well, im on version 0.30.0

**Comment by varnastadeus** [comment]
probably your are missing FormsModule in your app.

**Comment by gsteiner89** [comment]
Because i got the same problem, i was referenced to this Issue. Im using this approach:   https://netbasal.com/disabling-form-controls-when-working-with-reactive-forms-in-angular-549dd7b42110

Maybe it helps someone!

**Comment by suhailvs** [comment]
if you are using `reactiveforms`, then you have to use:

    name: [{value: '', disabled: true}, Validators.required],

or 

    this.form.controls['name'].disable();

[source](https://stackoverflow.com/a/44548569/2351696)

**Comment by Archi20** [comment]
For anyone who searching for this, ng-select have property **readonly**, it works for me.
`[readonly]="condition"`
