### ISSUE TITLE
Send Extra parameter with addTagPromise

### ISSUE THREAD

**Issue by RanjeetEppa18** [ng-select/ng-select#1321]
I have multiple dropdowns, How Can I come to know from which dropdown addTagPromise is fired?

**Comment by varnastadeus** [comment]
pass param and return another function in `addTagFn`

```ts
addTagFn(param: any) {
    return (label) => ({ name: label, tag: true });
}
```

**Comment by jtomek** [comment]
This reply @varnastadeus didn't the attention it deserved. This should be documented somewhere. Such a common case to want to pass extra params.
