### ISSUE TITLE
Additional material form elements support

### ISSUE THREAD

**Issue by bigbro1221** [ng-select/ng-select#1322]
**Is your feature request related to a problem? Please describe.**
No
**Describe the solution you'd like**
`<mat-error>` and `<mat-hint>` support

**Describe alternatives you've considered**
Additional spans but I am afraid that is not an option

**Additional context**
We are using `<ng-select>` amongside other material form fields and designing forms would cause us less pain if those elements were available in your components.

**Comment by varnastadeus** [comment]
as far as I know <mat-error> and <mat-hint> are part of material UI and I don't see why this should be included in ng-select

**Comment by nzbin** [comment]
> **Is your feature request related to a problem? Please describe.**
> No
> **Describe the solution you'd like**
> `<mat-error>` and `<mat-hint>` support
> 
> **Describe alternatives you've considered**
> Additional spans but I am afraid that is not an option
> 
> **Additional context**
> We are using `<ng-select>` amongside other material form fields and designing forms would cause us less pain if those elements were available in your components.

I have made a material form field wrapper of ng-select [`mtx-select`](https://ng-matero.github.io/extensions/select)
