### ISSUE TITLE
How can I add a new option in multiple="false"?

### ISSUE THREAD

**Issue by elementalPRESS** [ng-select/ng-select#1328]
Is it possible to add a new element (option) when I'm using a single selectable list (multiple="false")?

best regards,
Lars

**Comment by varnastadeus** [comment]
use `addTag`

**Comment by elementalPRESS** [comment]
> use `addTag`

Hi, I did it and it works. But (add)="..." doesn't fire and event. I used now (change)="" but should (add) an event too?
