### ISSUE TITLE
conditional styling to options

### ISSUE THREAD

**Issue by noonesstudios** [ng-select/ng-select#1329]
**Is your feature request related to a problem? Please describe.**
Stumbled into the requirement when a person can choose an option, although under flagged circumstances - needs to adhere a reassurance procedure. (are you sure? y/n)

**Describe the solution you'd like**
perhaps expose a `[classes]` input that will be passed on to the `*ngFor` later on ?
example [classes]: Object = {'class-1': findFlagFn1, 'class-2', findFlagFn2};

**Describe alternatives you've considered**
I will have to get all options later on and programatically append a class by comparing each option to its initial object in my array, which is currently passed `| async` to `[items]`

**Comment by varnastadeus** [comment]
what stops you from conditionally style options right now?

**Comment by noonesstudios** [comment]
information about how can I append a class / property depending on a flag inside the option object, which is passed as a whole into `[items]`...
Is it already possible and I miss a fundamental angular trick?

**Comment by noonesstudios** [comment]
Ok. I got the hang of it using the well documented but slightly hidden elaborated component apis.
`<ng-template ng-option-tmp etc.../>` nailed it.

sorry for the touchle, thanks
