### ISSUE TITLE
"this" keyword is undefined in searchFn

### ISSUE THREAD

**Issue by ybmt** [ng-select/ng-select#1330]
**Describe the bug**
"this" keyword is undefined in searchFn

**To Reproduce** 
Steps to reproduce the behavior (if example is not provided):
1. Use "this" keyword in searchFn

**Expected behavior**
"this" should not be undefined in searchFn

**Screenshots**
![Screen Shot 2019-08-22 at 11 40 22 AM](https://user-images.githubusercontent.com/24570782/63541219-7f558c80-c4d2-11e9-8fab-bc93dd0222ae.png)
![Screen Shot 2019-08-22 at 11 38 39 AM](https://user-images.githubusercontent.com/24570782/63541280-a1e7a580-c4d2-11e9-86c7-fa3f33591fb5.png)

**Desktop (please complete the following information):**
 - OS: MAC
 - All Browsers

**Comment by varnastadeus** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

**Comment by dsnoeck** [comment]
For anyone else landing here, here is the correct syntax:
```
searchFn = (term: string, item: any) => {
  console.log(this);
  return true;
}
```

**Comment by rubenheymans** [comment]
for anyone else landing here, a decent example:

```
public searchFn(term: string, pigeon: Pigeon): boolean {
    return (
      pigeon.ringNumber.indexOf(term) !== -1 || pigeon.name.indexOf(term) !== -1
    );
  }
```
