### ISSUE TITLE
[Bug] Cannot do HostBinding on disabled ng-select property on custom directive

### ISSUE THREAD

**Issue by koljagava** [ng-select/ng-select#1333]
**Describe the bug**
doing @HostBinding on disabled property there is a compilation error

**Reproducbile example**
https://stackblitz.com/edit/ng-select-bug1
there is also a workaround example commented

**Expected behavior**
expecting to interact with hostbinding to disabled ng-select property

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser : Firefox, Chrome
 - Version : 3.0.7 and 2.20.0

regards
  kolja

**Comment by pavankjadda** [comment]
This can no longer be reproduced. See https://stackblitz.com/edit/stackblitz-starters-dgyp3r for working example
