### ISSUE TITLE
Emit change event on patchValue for FormGroup

### ISSUE THREAD

**Issue by D1mitry** [ng-select/ng-select#1335]
I used nested drop downs with reactive form (values for second drop down uploads based on selection in the first). I have **change** event for the first drop down, so when I select value in it, new list for the second drop down uploads. This works good when I'm doing this in browser, however, when I **patchValue** in FormGroup it doesn't emit **change** event on first drop down.

Please find an example here: https://stackblitz.com/edit/angular-wk27yu?file=src/forms-multi-select-example.component.html

**Expected behavior**
Based on angular documentation, change event should be emitted by default, also if **emitEvent** option set to **true**. It shouldn't be emitted just in case  **emitEvent** option is **false**.

**Comment by varnastadeus** [comment]
can you provide a link to that documentation?

**Comment by D1mitry** [comment]
Sure https://angular.io/api/forms/FormControl#setvalue

**Comment by varnastadeus** [comment]
I think that you mixed up some definitions, you provided documentation about `FormControl` and as it states: 

> emitEvent: When true or not supplied (the default), both the **statusChanges** and **valueChanges** observables emit events with the latest status and value when the control value is updated. When false, no events are emitted. 

This has nothing to do with ng-select `change` event and it should not fire when you change model programmatically.
