### ISSUE TITLE
[feat]Enhance the theme system

### ISSUE THREAD

**Issue by liwonder** [ng-select/ng-select#1336]
**Is your feature request related to a problem? Please describe.**
Yes, now we can only import one theme file, either the default or the material.
All the two themes would be a global overriding theme. If I want some custom style in part of
my app, I need to use custom class, but this 'class' will not working when the dropdown are append to 'body'(we are using this in many places).

**Describe the solution you'd like**
I think if we have a [theme] input in the <ng-select> tag,
eg, <ng-select [theme]='material'></ng-select>, in the deep level, this would use a method like the current custom 'class' does, add the 'theme' class to the select element and the dropdown. Thus if we can implement custom style to customise the dropdown in either conditions.

**Describe alternatives you've considered**
Or maybe a simple solution, add the custom 'class' user add to the 'dropdown' panel. Then we can also customise the dropdown panel with the custom 'class' scope, without affecting other normal select.

**Additional context**
none.

**Comment by liwonder** [comment]
@varnastadeus Thanks a lot!

**Comment by varnastadeus** [comment]
If you add custom class, then it will also work for dropdown panel with appendTo

**Comment by liwonder** [comment]
@varnastadeus, yes, but if we want to customise the dropdown panel, that would be global overriding. We want the style change only apply to dropdown panel when we set custom class.

**Comment by liwonder** [comment]
How can we do that?

**Comment by liwonder** [comment]
![Screen Shot 2019-08-28 at 2 19 21 PM](https://user-images.githubusercontent.com/10594457/63830504-e1186980-c99e-11e9-8ec0-fbd5b0c5c073.png)
When 'appendTo' body, how can I customise the dropdown panel with custom class?

**Comment by varnastadeus** [comment]
simple as this: 

```html
<ng-select class="custom" appendTo="body"></ng-select>
```
```css
.ng-dropdown-panel.custom {
  border-color: red;
}
```

**Comment by liwonder** [comment]
@varnastadeus I see, thanks!
