### ISSUE TITLE
while pressing enter it is clearing the selected value in multiselect

### ISSUE THREAD

**Issue by santhoshraju621** [ng-select/ng-select#1339]
Hi

  I used ng-select with multi select option. i selected an option in multiselect. and i am going to select another option. so i pressed enter button. the selected option is getting deselected.

the behavior here  is we shouldn't deselect the existing selected option by pressing enter button.

**Comment by varnastadeus** [comment]
while pressing enter in multi-select, enter toggles current selection. This is by design

**Comment by santhoshraju621** [comment]
but the behaviour is it shouldn't remove element from list right?

**Comment by varnastadeus** [comment]
it shouldn't

**Comment by santhoshraju621** [comment]
then it is removing from the list while clicking on enter button

**Comment by varnastadeus** [comment]
If by _list_ you mean selected items, then yes, it adds or removes (toggles) current selection

**Comment by santhoshraju621** [comment]
ok you are saying it is the default behavior of the plugin. am i right?

**Comment by varnastadeus** [comment]
yes
