### ISSUE TITLE
Improvement: Please use class instead of ng-select tag stylelint set error for typo type

### ISSUE THREAD

**Issue by arun-maddheshia** [ng-select/ng-select#134]
Please fill below information if issuing a bug report. 
### Expected behaviour
In css def please use a class name instead of ng-select default tag.

### Actual behaviour
If css using ng-select getting warning:
Unexpected unknown type selector "ng-select" (selector-type-no-unknown)

**Comment by anjmao** [comment]
@arun-maddheshia Thanks for suggesting, action this is a good idea to add .ng-select class on host element.
