### ISSUE TITLE
ng-select drop down is partially hidden in the limits of mat-accordion

### ISSUE THREAD

**Issue by kfirufk** [ng-select/ng-select#1340]
Hi :)

I have ng-select component at a bottom of a mat-accordion and I would still like the drop down to open below the component, the problem is that the drop down is being clipped but the limits of the mat-accordion, how can I do that the entire dropdown will be visible ? 

thanks!

**Comment by varnastadeus** [comment]
`appendTo="body"`

**Comment by Raviniki** [comment]
i am still facing same issue don't understand the answer

**Comment by Raviniki** [comment]
can you provide more clarification

**Comment by caiolv** [comment]
I got it working doing 

```javascript
<ng-select appendTo="body">
```
