### ISSUE TITLE
can't use getter property as data source

### ISSUE THREAD

**Issue by cojocaru-dragos-alexandru** [ng-select/ng-select#1342]
I've tried this example: https://stackblitz.com/run?file=src/data-source-array-example.component.html

And made the following simple change:

instead of:
`simpleItems = [true, 'Two', 3];`

I've added:
```
get simpleItems()
    {
      return [true, 'Two', 3];
    };
```

The problem is that with this change, I can no longer click any items in the dropdown.

**Comment by varnastadeus** [comment]
you shouldn't use getter, https://github.com/ng-select/ng-select/issues/777
