### ISSUE TITLE
Variants of templates stopped working

### ISSUE THREAD

**Issue by piernik** [ng-select/ng-select#1344]
**Describe the bug**
I just updated from `2.18` to `3.0.7` and variants of templates stopped working.
What do I mean.
I have one general components for handling complex select input that uses Your `ng-select`. There I have different variants of templates (`label-tmp` and `option-tmp`) which is picked by `[ngSwitch]`

```
<ng-container [ngSwitch]="wariant">
    <ng-container *ngSwitchCase="'kolory'">
      <ng-template ng-label-tmp let-item="item" let-clear="clear">
        <span class="ng-value-icon left" (click)="clear(item)" aria-hidden="true">×</span>
        <span class="ng-value-label ng-select-label-with-color text-white"
              [style.background-color]="item.kolor">{{item.text}}</span>
      </ng-template>

      <ng-template ng-option-tmp let-item="item">
        <span class="badge text-white" [style.background-color]="item.kolor">{{item.text}}</span>
      </ng-template>
    </ng-container>

    <ng-container *ngSwitchCase="'sugestieObiektow'">
      <ng-template ng-option-tmp let-item="item">
        <app-obiekty-sugestia [obiektId]="obiektId" [id]="item.id"></app-obiekty-sugestia>
      </ng-template>
    </ng-container>
   // ...
</ng-container>
```
All worked until `2.20.5`: 
![select-2](https://user-images.githubusercontent.com/420691/64162857-6937bc80-ce40-11e9-85fe-72e04b381b45.png)

But after upgrading to `3.0.7` templates are ignored: 
![select-3](https://user-images.githubusercontent.com/420691/64163308-4b1e8c00-ce41-11e9-9e78-94f2e63e62a7.png)

**Reproducbile example**
https://stackblitz.com/edit/angular-essany?file=src%2Ftemplate-label-example.component.html

**To Reproduce** 

**Expected behavior**
Should work as earlier

**Screenshots**

**Desktop (please complete the following information):**
 - Windows
 - Chrome
 - 3.0.7, angular 8

**Comment by varnastadeus** [comment]
check closed issues, there was plenty regarding this problem
