### ISSUE TITLE
CompositionEnd not triggered on certain devices (mobile)

### ISSUE THREAD

**Issue by SublimePotato** [ng-select/ng-select#1345]
#1274 

Since [this commit](https://github.com/ng-select/ng-select/commit/5bf42a6c901ad39c93d93156cc656a9d45cfd808)  the filtering does not work on at least the following devices. 

**Devices**
- Xiaomi MI 2s (Android 9 Chrome 76)
- Xiaomi Mi 9 (Android 9 Kiwi)

**Minimal Reproduction**
`<ng-select [items]="['item 1', 'item 2']"></ng-select>`

**Debugging Info**
The `input` event is triggered but the `this._isComposing` flag is never `false`.

https://github.com/ng-select/ng-select/blob/3d2479129f164546f1c434127ff46ff6e329bac7/src/ng-select/lib/ng-select.component.ts#L527-L529

The `compositionEnd` event is fired sporadically (for example by pressing "ctrl + a" while remote debugging) but on the mobile device itself I did not find a way to enforce it. 

Using the version `3.0.3` the filtering works as it should (since the `compositionEnd` logic is not implemented yet)

Is there any way I can work arround this? Maybe we can make the `_isComposing` check optional?

**Comment by varnastadeus** [comment]
duplicate #1296
