### ISSUE TITLE
"state" id for input fires autosuggestions on Chrome

### ISSUE THREAD

**Issue by sarnecki-cic** [ng-select/ng-select#1346]
**Describe the bug**
When you click input, it opens autosuggestions dropdown with US states because of "state" id for this input. Unfortunately, inputAttrs cannot overwrite id.

**Reproducible example**
If your Chrome browser learned about the state field it should show you autosuggestion dropdown above ng-select one.

**Screenshots**
![Screen Shot 2019-09-03 at 10 21 23 AM](https://user-images.githubusercontent.com/27813025/64237481-ba0ceb00-cefc-11e9-8877-5ab78c1011e2.png)

**Desktop (please complete the following information):**
 - OS: mac OS
 - Browser: Chrome
 - Version: 76.0.3809.132

**Comment by varnastadeus** [comment]
have you checked https://github.com/ng-select/ng-select/issues/269? Also, reproducible demo is missing

**Comment by sarnecki-cic** [comment]
It duplicates #269 sorry.
