### ISSUE TITLE
Open nested group/level in another doropdown

### ISSUE THREAD

**Issue by oferah** [ng-select/ng-select#1347]
Something like that:
![image](https://user-images.githubusercontent.com/31686553/64320100-78e10d80-cfc6-11e9-8819-329d355f2e5b.png)

**Comment by sandrooco** [comment]
@oferah Did you find a solution to this yet? I'm looking for the same thing!

**Comment by oferah** [comment]
@sandrooco Unfortunately not. Eventually, I used a component I wrote myself, specially for my needs.

**Comment by sandrooco** [comment]
@oferah Thanks for your feedback. Did you completely drop the library and wrote your own thing or did you use "[custom option template](https://ng-select.github.io/ng-select#/templates)" for it?
