### ISSUE TITLE
add the ability disabled the entire group

### ISSUE THREAD

**Issue by djadjavit** [ng-select/ng-select#1348]
Good day to all.
We at our project use the ng-select library. Excellent library, thanks to all developers for a quality product.
It is very convenient that in ng-select there is a multi-select mode with checkboxes and grouping by groups.
https://ng-select.github.io/ng-select#/multiselect-checkbox
Tell me please. How can I disabled the entire group at once? The attribute is disabled, works on options, but does not work on groups ((
Thank you in advance.

**Comment by marcos-bah** [comment]
do you have a soluction for it?
