### ISSUE TITLE
Add translation option for label binding

### ISSUE THREAD

**Issue by timrasche** [ng-select/ng-select#1349]
In applications that uses client-side translation i need often the possibility to translate the label from attached array<object>

**Comment by varnastadeus** [comment]
use `<ng-option></ng-option>` or mutate your array after language change (https://github.com/ng-select/ng-select#change-detection)

**Comment by timrasche** [comment]
I dont ask for some alternative dude... i known this. Its what the type of issue says: FEATURE REQUEST!
