### ISSUE TITLE
Cannot use content projection (ng-content) into ng-select

### ISSUE THREAD

**Issue by vuongnguyen-agilityio** [ng-select/ng-select#1351]
**My source example**
```
Component: form-select

<ng-select
  class="default-form-select"
  [ngClass]="customClass"
  [items]="options"
  [(ngModel)]="selectedOption"
  (change)="onSelectValue($event)"
  [bindLabel]="filterBy"
  [clearable]="isClearable"
  [searchable]="isSearchable"
  [placeholder]="config?.placeholder">
      <ng-content></ng-content>
</ng-select>
```

I inject `ng-template` into `form-select` but it doesn't effective. 
I have tried with an html tag likes div, ng-content work correctly.
So, my assumption is ng-select doesn't support content projection, isn't it?

If I wrong, please give me a life to  add content projection into ng-select. 🙏

**Comment by varnastadeus** [comment]
It doesn't. What do you want to project though?

**Comment by vuongnguyen-agilityio** [comment]
Just my desire to reuse ng-select by make it as a template, then using ng-content to inject custom template into it without creating another component.

For example, your demo source with custom template is:
```
<ng-select [items]="cities" [(ngModel)]="selectedCity" bindLabel="name" bindValue="name">
    <ng-template ng-label-tmp let-item="item">
        <img height="15" width="15" [src]="item.avatar"/>
        {{item.name}}
    </ng-template>
</ng-select>
```

I will split it into 2 components

component-a.ts
```
<ng-select [items]="cities" [(ngModel)]="selectedCity" bindLabel="name" bindValue="name">
    <ng-content></ng-content>
</ng-select>
```

component-b.ts
```
<component-a>
    <ng-template ng-label-tmp let-item="item">
        <img height="15" width="15" [src]="item.avatar"/>
        {{item.name}}
    </ng-template>
</component-a>
```

It doesn't work.

**Comment by vuongnguyen-agilityio** [comment]
Found out the solution.
We should apply ng-content into templates

**Comment by ap-greenfly** [comment]
@vuongnguyen-agilityio care to share your solution?

**Comment by vuongnguyen-agilityio** [comment]
An example regarding to ng-select. No need to try to use ng-content in almost case. I thought.
```
<ng-select class="select-day-multiple">
  <ng-template ng-multi-label-tmp let-items="items" let-clear="clear">
    <p>{{ daysSelected }}</p>
  </ng-template>
  <ng-template ng-option-tmp let-item="item"let-index="index">
    <p class="status-item">
      {{item[filterBy]}}
      <span class="checked-icon"></span>
    </p>
  </ng-template>
</ng-select>
```

### I didn't have a chance to try with this idea:
```
<ng-select class="select-day-multiple">
  <ng-template ng-multi-label-tmp let-items="items" let-clear="clear">
    <ng-content></ng-content> //insert ng-content here.
  </ng-template>
  <ng-template ng-option-tmp let-item="item"let-index="index">
    <p class="status-item">
      {{item[filterBy]}}
      <span class="checked-icon"></span>
    </p>
  </ng-template>
</ng-select>
```

**Comment by ap-greenfly** [comment]
@vuongnguyen-agilityio thanks for the response. I didn't have any luck with your latter attempt, but I did find a workable solution here: https://github.com/ng-select/ng-select/issues/1497#issuecomment-582911992 using content child and template references.
