### ISSUE TITLE
OnTab select focus on next control/input is not working.

### ISSUE THREAD

**Issue by FaisalAyub** [ng-select/ng-select#1352]
![image](https://user-images.githubusercontent.com/39180705/64790207-23d96480-d58f-11e9-9953-9f17819def69.png)

After highlighted select value focus not move on next control.

**Comment by FaisalAyub** [comment]
Actually, on selection of dropdown, i want the value highlighted to be selected and the focus to move to next control.
the ng-select is applied on the 2nd last field.

**Comment by varnastadeus** [comment]
use `[selectOnTab]="true"`

**Comment by FaisalAyub** [comment]
I have done that already. while [selectOnTab]="true" selects the value, The focus of the ng-select doesnt move to next field. I want the next field to be also highlighted on tab press
