### ISSUE TITLE
Custom pipe on [items]

### ISSUE THREAD

**Issue by diegodesouza** [ng-select/ng-select#1353]
**Is your feature request related to a problem? Please describe.**
I'm unable to to filter my data using a pipe, is this possible? what am i missing

**Describe the solution you'd like**
I have tried using the `ng-template ng-option-tmp>`
```
    <label for="types">Types</label>
      <ng-select
        id="types"
        [items]="types"
        [clearable]="true"
        labelForId="types"
        formControlName="types"
        placeholder="Show All"
      >
        <ng-template ng-option-tmp>
          <div *ngFor="let type of types">
            {{type | removeCharacterPipe}}
          </div>
        </ng-template>
      </ng-select>
```

**Describe alternatives you've considered**
Filtering the data before sending it to the `ng-select`

**Comment by varnastadeus** [comment]
create reproducible example

**Comment by diegodesouza** [comment]
I have identified where I went wrong. I am able to use the pipe now after creating the triage
