### ISSUE TITLE
Having Trouble with Angular 7 

### ISSUE THREAD

**Issue by ohabash** [ng-select/ng-select#1354]
I would like to use ng-select in my Angular 7 project. Here are the problems im having with the various versions

## "@ng-select/ng-select": "^2.0.7",
>ERROR in ./node_modules/@ng-select/ng-select/fesm5/ng-select-ng-select.js
Module build failed: Error: ENOENT: no such file or directory, open '....../node_modules/@ng-select/ng-select/fesm5/ng-select-ng-select.js'

## "@ng-select/ng-select": "^3.0.7",
> WARNING in ./node_modules/@ng-select/ng-select/fesm5/ng-select-ng-select.js 266:56-74
"export 'ɵɵdefineInjectable' was not found in '@angular/core'

Is there sweet spot for my environment?

```
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cli                      7.3.9
@angular/fire                     5.0.0
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0
```

**Comment by varnastadeus** [comment]
Just use latest 2.x version

**Comment by MiftahulxHuda** [comment]
> Just use latest 2.x version

What's specific version 2?
