### ISSUE TITLE
ngOptionHighlight error about regexp

### ISSUE THREAD

**Issue by AVPavlov111** [ng-select/ng-select#1358]
When i try to search something like '+' or '[' with enabled ngOptionHighlight directive, then i receive error

SyntaxError: Invalid regular expression: /+/: Nothing to repeat
    at new RegExp (<anonymous>)
    at NgOptionHighlightDirective.push../node_modules/@ng-select/ng-option-highlight/fesm5/ng-select-ng-option-highlight.js.NgOptionHighlightDirective._highlightLabel (ng-select-ng-option-highlight.js:54)
    at NgOptionHighlightDirective.push../node_modules/@ng-select/ng-option-highlight/fesm5/ng-select-ng-option-highlight.js.NgOptionHighlightDirective.ngAfterViewInit (ng-select-ng-option-highlight.js:33)
    at callProviderLifecycles (core.js:21413)
    at callElementProvidersLifecycles (core.js:21387)
    at callLifecycleHooksChildrenFirst (core.js:21377)
    at checkAndUpdateView (core.js:29447)
    at callViewAction (core.js:29679)
    at execEmbeddedViewsAction (core.js:29642)
    at checkAndUpdateView (core.js:29439)

**Comment by anjmao** [comment]
Hi @AVPavlov111, could you provide more infor with stackblitz example?

**Comment by AVPavlov111** [comment]
I Have code like this:

`<ng-select bindLabel="name"
    [items]="states$ | async" [typeahead]="statesFilterInput$"
    [(ngModel)]="value">
    <ng-template ng-option-tmp let-item="item" let-search="searchTerm">
        <span class="ng-option-label" [ngOptionHighlight]="search">{{item.name}}</span>
    </ng-template>
</ng-select>`

When i type to input '+' or another regexp special symbol i receive  error
SyntaxError: Invalid regular expression: /+/: Nothing to repeat

I fixed it by adding pipe to search that escape special symbols:

`<ng-select bindLabel="name"
    [items]="states$ | async" [typeahead]="statesFilterInput$"
    [(ngModel)]="value">
    <ng-template ng-option-tmp let-item="item" let-search="searchTerm">
        <span class="ng-option-label" [ngOptionHighlight]="search | escapeRegExp">{{item.name}}</span>
    </ng-template>
</ng-select>`

And pipe code:

`@Pipe({name: 'escapeRegExp'})
export class EscapeRegExpPipe implements PipeTransform {
    public transform(term: string): string {
        if (term) {
            return term.replace(/[-[\]{}()*+?.,\\^$|#]/g, '\\$&');
        }
        return term;
    }
}`

**Comment by jardapan** [comment]
Hi, I have exactly the same problem. You can check your own Stackblitz example: https://stackblitz.com/run?file=src/forms-async-data-example.component.html
When using [ngOptionHighlight] the app throws errors to console. To simulate, just enter plus (+) or backslash (\) into search input.
If it was possible to bind to search term to filter unwanted characters or perhaps if I could enter regex pattern for underlying input field, that could be a fix too.
Otherwise, I love this component. Thanks a lot.
Cheers
Jarda

**Comment by boltex** [comment]
@jardapan , @AVPavlov111  i was stuck at version 0.0.2 of ngOptionHighlight . updated to 0.0.6 and all's good now.
