### ISSUE TITLE
Multiselection with sorting

### ISSUE THREAD

**Issue by mixalistzikas** [ng-select/ng-select#1359]
**Is your feature request related to a problem? Please describe.**
When you multiselect items it would be a good idea if you could sort them (change order)

**Describe the solution you'd like**
1) You could drag and drop the selecte item
2) Or you could select with click and sort with arrows keys <left><right>

**Comment by anjmao** [comment]
Hi @mixalistzikas, what is the use case for this? This sounds like a complex feature.

**Comment by mixalistzikas** [comment]
fox example, I have an article and I want to connect some other articles to it, but the order matters...

**Comment by YZahringer** [comment]
Same need, I assign multiple values and the order must be editable. 
Like drag and drop on [Select2](https://select2.github.io/select2/) component.

**Comment by YZahringer** [comment]
Please re-open issue

**Comment by NESTicle** [comment]
This could be an awesome feature to be implemented

**Comment by inloox-dev** [comment]
+1

**Comment by leonid-dashko** [comment]
Please re-open issue

**Comment by Jelledb** [comment]
I would also love this feature. We let users type in their own values, which can be quite a lot, and they want to influence the order of items without having to delete and re-enter everything.

**Comment by emekaelo** [comment]
Necessary feature.
For my use case, I want to render the selected options according to the order they are arranged in the selected view of multiple ngselect. I want the order of the rendered items to change according to how the selected items are ordered.
Thanks
