### ISSUE TITLE
Multiselect accepting custom values

### ISSUE THREAD

**Issue by ShinDarth** [ng-select/ng-select#136]
Hello, I was wondering if it's possible to use the Multiselect allowing the user to insert any value instead of just providing the values from a fixed list of options.

For example:

![image](https://user-images.githubusercontent.com/75517/33171393-3a93287c-d04c-11e7-863f-6511f6f33d2d.png)

in this example there is not any list providing the numbers, the user is able to insert any number.

**Comment by varnastadeus** [comment]
Yes, it is possible, if you check API, there is binding [tag]=true

**Comment by ShinDarth** [comment]
thanks for your answer! I'll check it soon
