### ISSUE TITLE
Allow custom css classes to be added to ng-dropdown-panel

### ISSUE THREAD

**Issue by pfms84** [ng-select/ng-select#1361]
**Is your feature request related to a problem? Please describe.**
I need to pass a custom css class to the ng-dropdown-panel since I'm using a third party library that uses a class to prevent a behavior.

**Describe the solution you'd like**
Add an input to ng-select for additional dropdown classes and pass them to the ng-dropdown-panel component.

**Comment by varnastadeus** [comment]
classes are propagated when you are using `appendTo`. Otherwise adding class on ng-select should be enough.

```css
.ng-select.custom .ng-dropdown-panel {
    // ....
}
```

**Comment by hkkhchan** [comment]
I alway face this issue. but I need to append the drop down panel to the body.
@varnastadeus 's solution not fit for my case.
