### ISSUE TITLE
Xss vulnerability on firefox

### ISSUE THREAD

**Issue by adrienpessu** [ng-select/ng-select#1363]
**Describe the bug**
On firefox only, there is an XSS vulnerability with the payload `<marquee loop=1 width=0 onfinish=confirm(1)>XSS</marquee>`

**Reproductible example**
[Example](https://stackblitz.com/edit/angular-mxfbgk?file=src%2Fapp%2Fapp.component.html) which shows how to reproduce the issue, but it doesn't seem to work on stackblitz. 

Please note that the issue is only on Firefox.

**Expected behavior**
The content of ngModel should be display as it is

**Comment by varnastadeus** [comment]
ng-select already sanitizes your data, but since your example is not correct it fails to do that. Your `[items]` must be present or you should use `<ng-option>` otherwise control is useless.
```
<ng-select  appendTo="body"
    [items]="[]"
    [ngModel]="tmp">
</ng-select>
```

**Comment by adrienpessu** [comment]
I have updated the [example](https://stackblitz.com/edit/angular-mxfbgk?file=src%2Fapp%2Fapp.component.html) on stackblitz.

I have added `<ng-option>` and the XSS is still there. 
```
  <ng-select  appendTo="body"
              [ngModel]="tmp">
    <ng-option value="none">
      nope
    </ng-option>
  </ng-select>
```

**Comment by KerNIM** [comment]
Is there any updates regarding this issue?
I have overcome the same issue but up until there is not any solution towards this.

**Comment by Chocobozzz** [comment]
If using `<ng-option>` ng-select doesn't sanitize option values which is fine. But it doesn't sanitize the `selectedItems` either, which lead to XSS if the parent doesn't check the injected `ngModel` or patch ng-select input with untrusted value.
When using `ng-option`, ng-select should ensure the item of `selectedItems` is included in the list of available options. If not, it should escape it.

https://github.com/ng-select/ng-select/blob/master/src/ng-select/lib/ng-select.component.ts#L729 seems the line where we can `escapeHTML`.
