### ISSUE TITLE
Enabling Horizontal scroll inside the input box instead of infinitely expanding the input box in case of multi-select.

### ISSUE THREAD

**Issue by harshit-bhimsaria-coviam** [ng-select/ng-select#1364]
**Is your feature request related to a problem? Please describe.**
My form gets distorted because of the infinitely expanding input box when I use the multi-select option.

**Describe the solution you'd like**
It would be better to have an to disable auto-grow, instead use horizontal scroll inside the input box.

**Describe alternatives you've considered**
Other than my preferred solution if instead of auto-grow and horizontal scroll, we could also use an option of fixed number of rows and vertical scroll.

**Comment by varnastadeus** [comment]
there was a similar issue already. Basically, you need to set a fixed height on the container and enable overflow all done using plain css.

**Comment by kavinda1995** [comment]
For anyone looking for the css solution what I did was unset the white-space wrap on ng-option using global css

`.ng-dropdown-panel .ng-dropdown-panel-items .ng-optgroup, .ng-dropdown-panel .ng-dropdown-panel-items .ng-option {
  white-space: unset !important;
}`
