### ISSUE TITLE
if addTag is set to a function, "this" points to the NgSelectComponent

### ISSUE THREAD

**Issue by cojocaru-dragos-alexandru** [ng-select/ng-select#1366]
As per this example, https://stackblitz.com/run?file=src/tags-backend-example.component.html
in the "addTagPromise" function, "this" points to the NgSelectComponent, making it impossible to access any services that the parent component has.

**Comment by varnastadeus** [comment]
It has been answered in previous questions, please check closed issues

**Comment by Arkiiateam** [comment]
@varnastadeus it would be better if you reference the closed issue

**Comment by keyuls** [comment]
@Arkiiateam have you found a reference issue for this?

**Comment by cojocaru-dragos-alexandru** [comment]
just define your function in typescript like so:

addNewItem = (name: string) =>yourApiCallToAddNewItem(name).toPromise();
