### ISSUE TITLE
Option values doesn't update with pipe transform call

### ISSUE THREAD

**Issue by majadinjar** [ng-select/ng-select#1368]
**Describe the bug**
Ng-option value is not updating when pipe transform is called dynamically.
When page renders, pipe transforms values in default language and it's working okay. But when updating service with language change pipe is called again and values are transformed, but ng-option values stay in inital language.

When using ng-template value is updating, but search is not working.

**Reproducbile example**
[Example]https://stackblitz.com/edit/ng-select-angular6-b5ru39

**To Reproduce** 
Steps to reproduce the behavior (if example is not provided):
1. Click on button to change language.
2. Check both menus, first one doesn't change values, and second changes values to selected language.

**Expected behavior**
I expect that ng-option updates when pipe transforms its values or that search is working fine when using ng-template and pipe.

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [77.0.3865.90 (Official Build) (64-bit)]

**Comment by aneudysamparo** [comment]
Same problem here!

**Comment by varnastadeus** [comment]
This is by design, if you are using `[items]` you need to mutate reference of your array to address the changes. If that's not an option, use declarative style of ng-options:

```html
<ng-select>
    <ng-option>{{ item.name | lowerCase }}</ng-option>
</ng-select>
```
