### ISSUE TITLE
Is it possible to edit a custom tag after creation?

### ISSUE THREAD

**Issue by jeandat** [ng-select/ng-select#1371]
If i read the doc correctly, you can't edit a custom tag after creation, for instance, by double clicking it ? Am I right? That would be a nice addition.

**Comment by poddarkhushbu07** [comment]
> If i read the doc correctly, you can't edit a custom tag after creation, for instance, by double clicking it ? Am I right? That would be a nice addition.

Is this feature going to be added in future or this is not included in roadmap?
