### ISSUE TITLE
click on outside should close the dropdown

### ISSUE THREAD

**Issue by aitboudad** [ng-select/ng-select#138]
Please fill below information if issuing a bug report. 
### Expected behaviour
click on outside should close the dropdown when component is set to OnPush detection strategy.

### Actual behaviour
dropdown still open when use click outside of the ng-select

### More Info
ng-select version: `0.8`

browser: chrome

reproducible in demo page: YES

see https://stackblitz.com/edit/angular-wnnhjl

**Comment by anjmao** [comment]
@aitboudad Good catch! I will fix it today,I just need to call detect changes and it would be a good idea to add demo with component using OnPush :)
