### ISSUE TITLE
Initiate a search from the code

### ISSUE THREAD

**Issue by GitHubish** [ng-select/ng-select#1389]
How to launch a search from the component? I explain myself, the case I encounter: the user fills a form, if he does not find the item he wants in a drop-down list (which I name "List A") then he has the possibility to make an extended search that will open a modal in which there is a NgSelect drop-down list that performs the extended search. I would like to be able to initialize the search with its previous search (List A). But I can't find any method to define the search. If I go through the value of the input and do "open()" it doesn't do the research and the placeholder is not hidden. 

How to do this?

**Comment by GitHubish** [comment]
This feature would be really handy. If I can take the time in 2020 I'll try to see how to implement it.

**Comment by varnastadeus** [comment]
you just need to set your [items] list? 🤔 There is nothing to implement

**Comment by GitHubish** [comment]
@varnastadeus sorry for the silence. I'll rephrase it and hope my request is clearer.

step 1: I have a component in which I use ng-select which allows me to select an entry against "known" entries (an array). 

step 2: When the user doesn't find what he's looking for he clicks on a button that will open a modal in which I have another ng-select that will make an http call that will retrieve another list. What I'm trying to do is to pre-type the field so that ng-select displays the filtered list with what the user had previously typed in step 1. 

Is my request clearer?

The code that worked for a while was this one, but it doesn't work anymore (and it was ugly...):

```
of(true).pipe(delay(200),
      tap(() => {
        this.ngSelectRef.open();
        this.ngSelectRef.focus();
      }),
      tap(() => {
        this.ngSelectRef.searchTerm = this.data.searchTerm;
        this.ngSelectRef.searchable = true;
        this.ngSelectRef.onCompositionEnd(this.data.searchTerm);
        this.ngSelectRef.detectChanges();
      })
    ).subscribe();
```

Thanks
