### ISSUE TITLE
scrollToEnd Not Firing

### ISSUE THREAD

**Issue by thebmusic** [ng-select/ng-select#1395]
I was upgrading from v2.20.0 to v3.3.0 as part of an upgrade to Angular 8 and noticed some broken behavior.  I'm using [typeahead], [virtualScroll], and (scrollToEnd) to load new page of search results based on a search term when scrolling to the end.  In v2.20.0 this worked fine, but it's hit and miss in v3.30.  The reason appears to be the calculation determining if we've reached the end or not.

Here's the code method calculating that:
`    private _fireScrollToEnd(scrollTop: number) {
        if (this._scrollToEndFired || scrollTop === 0) {
            return;
        }
        const padding = this.virtualScroll ?
            this._virtualPadding :
            this._contentPanel;
        if (scrollTop + this._dropdown.clientHeight >= padding.clientHeight) {
            this._zone.run(() => this.scrollToEnd.emit());
            this._scrollToEndFired = true;
        }
    }`

Here's a screen shot when I've scrolled to the end, note the math doesn't add up to emit scrollToEnd.  It feels like it would work if scrollTop was rounded up.

![ng-select](https://user-images.githubusercontent.com/26719817/67427861-9718c200-f5a2-11e9-963e-6d114bdcc301.png)

**Comment by janstadt** [comment]
related to https://github.com/ng-select/ng-select/issues/1018

https://github.com/ng-select/ng-select/issues/1018#issuecomment-545605422

**Comment by AlmaniaM** [comment]
I'm having the same issue. Is anyone working on it?

**Comment by janstadt** [comment]
bump. Any update on this?

**Comment by john-hynes** [comment]
I've just upgraded to version 4.0.0 and found the scroll event not firing any more. Is this the same issue?

**Comment by varnastadeus** [comment]
I think this issue is out of date, check the latest version and create a new one if the issue persists

**Comment by meanwhileinsantacruz** [comment]
This issue is very clearly written, the problematic piece of code is marked out and a one-line patch is explicitly on the table - of course, it might require further analysis.
Yet, it is closed and "Needs triage" labeled. 

I am willing to caption the obvious so here is a patchy workaround.
Subscribe to the NgSelectComponent#scroll event emitter and execute : 

```typescript
// When the select component states if the scroll event reached the end of the "virtual scroll",
// it does not round up the "scrollTop" parameter value.
// Thus, it might miss the "scrollToEnd" threshold. 
// The workaround is to shunt the original "_fireScrollToEnd" method to submit a ceiled value.
// Note : execute this workaround in the "scroll" event so NgSelectComponent#dropdownPanel is available. 
const select = this.selectComponent as any;
if (select?.dropdownPanel && ! select.dropdownPanel._fireScrollToEndOrig) {
	// Store the original function to _fireScrollToEndOrig.
	select.dropdownPanel._fireScrollToEndOrig = select.dropdownPanel._fireScrollToEnd;
	
	// Replace the existing _fireScrollToEnd function.
	select.dropdownPanel._fireScrollToEnd = (scrollTop: number) => {
		// Submit the input parameter, rounded up, to the original function.
		select.dropdownPanel._fireScrollToEndOrig(Math.ceil(scrollTop));
	}
} 
```

**Comment by nrcdmovliaiko** [comment]
any updates?
