### ISSUE TITLE
Patchs in version 2.x.x

### ISSUE THREAD

**Issue by crissty** [ng-select/ng-select#1399]
**Is your feature request related to a problem? Please describe.**
I would like to do use of the patch "ng-option: handle label updates (634c804), closes #649", but it is not present in version 2.x.x with Angular 7

**Describe the solution you'd like**
Include some patch related with the functionality in 2.x branch and release a new version in order  to continue supporting angular v6 / v7

**Comment by varnastadeus** [comment]
we generally don't backport fixes to an older version, angular tries its best to make the upgrade process as easy as possible so I don't see any reason why you won't do that, just don't be lazy ;] 

If upgrading is not an option for you, you can open PR with this fix ported to an older branch 😉
