### ISSUE TITLE
Groups with one member only: Option to hide group labels

### ISSUE THREAD

**Issue by xErik** [ng-select/ng-select#1401]
Thank you for providing this module!

**Problem**

My model contains many groups. But some groups have only one member. Resulting in many group labels introducing just a single SELECT-option.

Which clutters the dropdown with iterations of:

```
+ group label
  - member label
+ group label
  - member label
+ group label
  - member label
...
```

**Feature**

I'd like group labels to appear only if there is more than one member in a group.

**Possible Implementations**

1. A boolean option like:

`groupLabelsUponMoreThanOneMember = true`

2. An option stating a minimum number of members for the group to appear might be a generalized approach:

`groupLabelsUponMinMemberCount = 4`

3. Allowing the function `groupValue` to return `null` values or the empty string. And subsequently not put out a group label.

I tried the to suppress any groups with `name` or `group` attribute set to `null` or empty string, but the group gets rendered:

```javascript
  groupValue(groupKey, children) {
    console.log(groupKey, children);
    return { name: null };
  }
```

**What I try to avoid**

Looking at the examples, groups are not rendered if in the model the `groupBy-value` is set to undefined. However, I'd like not to tamper with my model, as this would be a workaround to make `ng-select` fulfill my feature.

```
{ name: 'Jill', email: 'jill@email.com', age: 15, country: undefined, child: { state: 'Active' } },
{ name: 'Henry', email: 'henry@email.com', age: 10, country: undefined, child: { state: 'Active' } },
{ name: 'Meg', email: 'meg@email.com', age: 7, country: null, child: { state: 'Active' } },
{ name: 'Adam', email: 'adam@email.com', age: 12, country: 'United States', child: { state: 'Active' } },
{ name: 'Homer', email: 'homer@email.com', age: 47, country: '', child: { state: 'Active' } },
```

**Comment by varnastadeus** [comment]
at this point what you can do is to check if item has more than 
```ts
groupByFn = (item) => {
    return groupCountMap[item.groupKey] > 1 ? item.name : null
}
```
