### ISSUE TITLE
Options not clickable if extracted from set via component method

### ISSUE THREAD

**Issue by kokmok** [ng-select/ng-select#1405]
When I wanted to use items from a set, I created a component method to transform the set in an array. ng-select seems to accept it, but my options are not clickable. I can select it with tab.

**Reproducbile example**
https://stackblitz.com/edit/angular-vfjaav

**Expected behavior**
The options should be clickable

**Desktop (please complete the following information):**
 - OS: Ubuntu18.04
 - Browser Chromium
 - Version 77.0.3865.90 (Build officiel) Built on Ubuntu , running on Ubuntu 18.04 (64 bits)

**Comment by varnastadeus** [comment]
You shouldn't use a function as your data source. Even if there is no problem, I would say it is a bad practice. You can get more info here https://github.com/ng-select/ng-select/issues/1342

**Comment by kokmok** [comment]
ok. Could it be a good idea to support Set as data source ? The options in a select are unique.
