### ISSUE TITLE
Ng-select in mat-dialog resizes dialog on selection change

### ISSUE THREAD

**Issue by akvaliya** [ng-select/ng-select#1408]
**Describe the bug**
After opening mat-dialog when we select items. Dropdwn width changes which results expanding dialog. It shouldn't resize. 

**Reproducbile example**
[Example](https://stackblitz.com/edit/angular-suutiy) which reproduces described behaviour

**Expected behavior**
Once items reaches dropdown size it's either wrap or add some text like 1+

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 78.0.3904.70 (Official Build) (64-bit)

**Comment by varnastadeus** [comment]
this is default behavior which is defined in css. To make it fixed width just define your own css rules.

**Comment by rubenheymans** [comment]
for future ref 
add to ng-select: `appendTo="body"`
add css:
```
::ng-deep .ng-dropdown-panel {
  z-index: 2000 !important;
}
```

**Comment by smchichou** [comment]
thanks @rubenheymans
