### ISSUE TITLE
Angular 9 roadmap

### ISSUE THREAD

**Issue by biltongza** [ng-select/ng-select#1412]
With Angular 9 hitting RC last week, is there any roadmap for Angular 9 support? I see the package explicitly specifies @angular/common>=8.0.0 <9.0.0 and I am wondering if there is any specific reason 9 is excluded.

I don't need this right now, I'm just trying to see what my project will need for when Angular 9 does eventually hit GA.

**Comment by varnastadeus** [comment]
If there are no breaking changes we can just increase version ranges. Otherwise, we need to adjust to that changes and release new major version on our side.

**Comment by pwilkowski** [comment]
Basic version works, I haven't used any advanced features but basic functionality works on Angular 9 RC3.

**Comment by rob3c** [comment]
There's a new related issue #1499 that's still open for anyone following this that's still interested, now that this is closed as stale.
