### ISSUE TITLE
Event toggling ng-select

### ISSUE THREAD

**Issue by CzerwinskiMarcin** [ng-select/ng-select#1414]
**Is your feature request related to a problem? Please describe.**
I'm working with aplication on Angular 6 and Electron. 
The event in charge of expand/close ng-select is **_mousedown_**. While testing the aplication with _**Spectron**_ there is no possibility to toggle the ng-select. Click events in this API simulates _**click**_ not **mousedown**. Is there any reason why we are using _**mousedown**_ event type instead of _**click**_?

**Describe the solution you'd like**
Change event listener from **_mousedown_** to _**click**_.

**Describe alternatives you've considered**
Make event listener configurable.

**Comment by varnastadeus** [comment]
I don't see a reason why `there is no possibility to toggle the ng-select.` Can you elaborate?

**Comment by CzerwinskiMarcin** [comment]
I this example will be the best elaboration of my problem.
 
Let me take you to ng-select [demo site](https://ng-select.github.io/ng-select#/data-sources).

This will be quite straightforward.

The selector of the first select is like this: 
`const selectSelector = 'data-source-backend-example  ng-select div';`

Create two MouseEvents - one with **_click_** and one with **_mousedown_**

`const clickEvent = new MouseEvent('click');`
`const mousedownEvent = new MouseEvent('mousedown');`

Get the select:
`const select = document.querySelector(selectSelector);`

And to main point: 

1. `select.click();` - do not expand select,
2. `select.dispatchEvent(clickEvent);` - do not expand select,
3. `select.dispatchEvent(mousedownEvent);` = expands select


As for the **_Spectron_** APIs there only simulate _**click**_ not _**mousedown**_ events (as far as I know).


Entire code to follow:

`const selectSelector = 'data-source-backend-example  ng-select div';`
`const select = document.querySelector(selectSelector);`
`const clickEvent = new MouseEvent('click');`
`const mousedownEvent = new MouseEvent('mousedown');`
`setTimeout(() => {select.click(); console.log('Click method')}, 0);`
`setTimeout(() => {select.dispatchEvent(clickEvent); console.log('Dispatch MouseEvent click method')}, 2000);`
`setTimeout(() => {select.dispatchEvent(mousedownEvent); console.log('Dispatch MouseEvent mousedown method')}, 4000);`

**Comment by varnastadeus** [comment]
> select.dispatchEvent(mousedownEvent); = expands select

so what's the problem with this approach?

**Comment by CzerwinskiMarcin** [comment]
With this approach - nothing. 
Testing with **_Angular/Electron_** app with **_Spectron_** where I can not have access to _document/dispatch event_ and have to do some workaround with components to get response on click event is troblesome.
Therefore can we do something about this _mousedown_ event select toggle or not?
