### ISSUE TITLE
Close on value container click

### ISSUE THREAD

**Issue by SuleimanShaloudi1** [ng-select/ng-select#1415]
Hi,
The dropdown panel open through clicking on the container value, but does not close upon that also. Can you add this feature please?

**Comment by varnastadeus** [comment]
you can close by clicking `arrow`

**Comment by SuleimanShaloudi1** [comment]
Yes i know, but it's a requirement to close by clicking upon the value container again. Is there any way of doing this?

**Comment by SuleimanShaloudi1** [comment]
@varnastadeus Can you please respond to this?

**Comment by varnastadeus** [comment]
you can close manually using select`s `close` event also

**Comment by SuleimanShaloudi1** [comment]
@varnastadeus, I tried to create a custom close function using (focus) and check isOpen property of the component. Thence, call the close method. But it did not work (close method does nothing). However, the close method works when i use (click) event.

**Comment by varnastadeus** [comment]
you don't need to have a custom close function, using current API should allow you to achieve this

**Comment by SuleimanShaloudi1** [comment]
The API works fine using the click event. However, it does not using the focus event
