### ISSUE TITLE
Virtual scroll = true and on search drop-down list position disturbs

### ISSUE THREAD

**Issue by deepender87** [ng-select/ng-select#1416]
https://stackblitz.com/edit/angular-pzw5i4?file=app%2Fapp.component.html

Ngselect with virtualscroll = true and on search list goes away.
If the dropdown list cannot open below, It will open on above of it. I am using ng-select in ag grid. I am facing this issue, when I start searching it.

`<ng-select class="mm-ng-select" [items]="names" appendTo="body" [multiple]="false"
    placeholder="'selectName'" [(ngModel)]="selectedName" [clearable]="false"
    (change)="onNameSelection()"  [virtualScroll]="true">
  </ng-select>`

Please check the attached image.

![dropdownposition](https://user-images.githubusercontent.com/3591114/68369564-a3834a00-0160-11ea-9a04-5ba3187d2fe5.PNG)

**Comment by deepender87** [comment]
Please check this issue. It was simply closed without any proper solution.

https://github.com/ng-select/ng-select/issues/463

**Comment by varnastadeus** [comment]
use latest version of ng-select
