### ISSUE TITLE
[bug] Cursor stay at beginning 

### ISSUE THREAD

**Issue by indraraj26** [ng-select/ng-select#1419]
**Describe the bug**
Cursor stay at beginning even after selecting from dropdown

**Reproducbile example**
[reactive form example](https://stackblitz.com/run?file=src/forms-async-data-example.component.html) which reproduces described behaviour

**To Reproduce** 
Steps to reproduce the behavior (if example is not provided):
1. Go to https://stackblitz.com/run?file=src/forms-async-data-example.component.html
2. Select any from dropdown.

**Expected behavior**
Cursor should be in end of selected items.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by varnastadeus** [comment]
this is by design

**Comment by indraraj26** [comment]
but this is really quite confusing for users if it is possible for you to adapt above feature in near future, you can tag this as milestone.

**Comment by varnastadeus** [comment]
It will be even more confusing to put it to the end since item is not editable by default. It only makes sense to put it at the end when item is editable and there is separate task for it #1156
