### ISSUE TITLE
How I can add an icon in the option and open a box with click on it when drop down is opened

### ISSUE THREAD

**Issue by fpichlou** [ng-select/ng-select#1421]
Hi everyone; I want to show the option description inside of the drop down with click on the option's icon like the following image:

![46751177-5664-430d-8049-be670b2b440a](https://user-images.githubusercontent.com/56465485/68527495-bd599400-02fc-11ea-9e70-c58e46dbafe7.png)

How can I do it?

**Comment by varnastadeus** [comment]
Just check demo page
