### ISSUE TITLE
with reactive forms, when there is a value, the placeholder's div still exists

### ISSUE THREAD

**Issue by steve3d** [ng-select/ng-select#1422]
**Describe the bug**
it's a obvious bug, and you can see it from official examples here: https://ng-select.github.io/ng-select#/forms

also here
<img width="782" alt="截屏2019-11-1121 02 31" src="https://user-images.githubusercontent.com/670687/68589446-d9a92c80-04c6-11ea-846a-6eac448c7e52.png">

placeholder `Select item` and the selected value `Batman` both visible, this is because, there is no `ng-has-value` class, don't know if this is an ng-select bug or angular.

**Reproducbile example**
https://ng-select.github.io/ng-select#/forms

**Comment by stanvanheumen** [comment]
I am experiencing this as well when using the multiple property.

**Comment by Brianvdb** [comment]
Priority issue

**Comment by tonivj5** [comment]
I have downgrade to `3.3.0` where it's working properly... while this issue is fixed :+1:

**Comment by varnastadeus** [comment]
@tonivj5 what about 3.5.0?

**Comment by tonivj5** [comment]
`3.5.0` is working properly too. I downgraded to `3.3.3` because I update from that version.

The issue comes from `.ng-has-value` class, which it isn't being well-binded :confused: 

Maybe, because of the use of `[class.ng-has-value]="hasValue"` and `class="ng-appearance-{{appearance}}"` at the same time. [Ref](https://github.com/ng-select/ng-select/commit/af4c6bb951b135d3f6f3df649a966714a3561367#diff)

**Comment by MrNocTV** [comment]
This issue still remains, please fix it.

**Comment by kavinda1995** [comment]
I'm using version 3.7.3 and this issue comes up anyway

**Comment by 006parth** [comment]
i've tried every versions 3.X.X and this issue is coming in every versions

**Comment by Anu-Priya07** [comment]
I am still facing this issue with every version

**Comment by abhilashfancy** [comment]
Still facing this issue with version 6.1.0

**Comment by raduhawk** [comment]
Same issue with version 6.1.0

**Comment by aslam-angular-dev** [comment]
I have this issue with 6.1.0

**Comment by gilljunior** [comment]
I fixed it by adding this style to version 1.6.0:

.ng-has-value .ng-placeholder {
  display: none;
}

**Comment by psanketdev2020** [comment]
its working after this solution..
.ng-has-value .ng-placeholder {
display: none;
}

**Comment by iHazCode** [comment]
Above shim solves the issue with version 4.0.4 I am currently relegated to using:
.ng-has-value .ng-placeholder {
display: none;
}

Thanks gang!
