### ISSUE TITLE
Placeholder is not showing while using FormGroup

### ISSUE THREAD

**Issue by mrSingh007** [ng-select/ng-select#1424]
**Describe the bug**
Placeholder is not showing on first render if formControlName is used. 
At FormGroup have required field as 
```
...
form: FormGroup = this.fb.group(
    {
      titleCode: ['', Validators.required],  //initial value is empty
.... 
```
and the html code like:
```
                <ng-select formControlName="titleCode" [clearable]="false" [items]="titles" bindLabel="name"  bindValue="PK"  placeholder="hello world">
                </ng-select>
            
```
This html code will not show placeholder.
I thought, this might happen because in formgroup titleCode have initial empty value so I also tried to pass null and also tried to use only validators.required. But still not working.

If I do not use formControlName then it works perfectly 

**Expected behavior**
placeholder should be shown if no any value is selected 

**Screenshots**
![Screen Shot 2019-11-11 at 17 16 50](https://user-images.githubusercontent.com/16721438/68602744-34329080-04a7-11ea-8a33-302fa7c3c6fd.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome (latest)
 - repo version: 3.5.0

**Comment by varnastadeus** [comment]
Empty string is valid value

**Comment by mrSingh007** [comment]
@varnastadeus 
using ```  titleCode: [Validators.required] ``` also producing same issue

**Comment by mrSingh007** [comment]
providing null  ```titleCode: [null, Validators.required]``` works. Is empty value should not be taken as non-value?
you may close the issue, if its expected behaviour
