### ISSUE TITLE
Rename property readonly to readOnly

### ISSUE THREAD

**Issue by stefanlange** [ng-select/ng-select#1426]
**Describe the bug**
`readonly` is a reserved keyword in TypeScript. Therefore the property should be renamed to i.e. `readOnly` (camel case). You could still use `readonly` as the binding property name so that users don't have to update their templates:

`@Input('readonly') readOnly:boolean;`

**Comment by varnastadeus** [comment]
typescript doesn't have any problems with this naming so I don't any need to rename it, correct me if I am wrong
