### ISSUE TITLE
autoCorrect and autoCapitalize

### ISSUE THREAD

**Issue by piyushkantm** [ng-select/ng-select#1427]
**Describe the bug**
This was once a part of the API. But was removed in v3.0.0

https://github.com/ng-select/ng-select/commit/c7dd2ac1f5deb5821fe4fd5f10767a3e88078fd0
https://github.com/ng-select/ng-select/blob/master/CHANGELOG.md#300-2019-07-08

**Expected behavior**
The changelog does mention it's removal but there was no reason mentioned as why this was removed. I was just curious as why this was removed.

**Comment by varnastadeus** [comment]
this was replaced with 
- pass custom input attributes using inputAttrs (1614aa7), closes #1222
