### ISSUE TITLE
Missing Documentation for filterInput

### ISSUE THREAD

**Issue by piyushkantm** [ng-select/ng-select#1428]
**Describe the bug**
There was a change in the public APIs in v3.0.0 and it is not documented anywhere:

https://github.com/ng-select/ng-select/commit/643cf520093a7c703731152f3e689bbf837d431e#diff-921c534603535d54ff52e45a33a6aceaL170

**Expected behavior**
The change should have been documented in: https://github.com/ng-select/ng-select/blob/master/CHANGELOG.md#300-2019-07-08

**Comment by varnastadeus** [comment]
filterInput was not documented anywhere, therefore it is not recommended to use it directly
