### ISSUE TITLE
Allow to change dropdown positioning (auto, above and below)

### ISSUE THREAD

**Issue by aitboudad** [ng-select/ng-select#143]
Please fill below information if issuing a bug report. 
### Expected behaviour
Allow setting dropdown postion (above and below), the default option is `auto`.

### Actual behaviour
Dropdown appear only below the root component

**Comment by anjmao** [comment]
@aitboudad Thanks for suggestion :) Can you describe the use case of changing dropdown position on scroll? One use case can be to scroll whole viewport if opened dropdown can't fit and not all options are visible.

**Comment by aitboudad** [comment]
@anjmao I don't have a use case for scroll maybe not really useful, for me what I want is just auto guess the position when opening the dropdown.

**Comment by aitboudad** [comment]
changed description, keep it simple :)!
