### ISSUE TITLE
Placeholder is not hiding when value selected

### ISSUE THREAD

**Issue by sudarsan900** [ng-select/ng-select#1431]
Placeholder is not hiding when value selected

**Reproducbile example**
Stackblitz editor URL- https://stackblitz.com/edit/angular-xwek2c
App URL- https://angular-xwek2c.stackblitz.io

**To Reproduce** 
Just used Reactive Form and it doesn't work

**Expected behavior**
On value select placeholder should hide

**Screenshots**
![image](https://user-images.githubusercontent.com/25909149/68770377-09357180-064c-11ea-8426-344309d42cbd.png)

**Versions**
"@angular/core": "~8.2.3",
"@ng-select/ng-select": "^3.6.0",

**Comment by paolosanchi** [comment]
I think is a dup of this:
https://github.com/ng-select/ng-select/issues/1422

**Comment by ashwanizsktm** [comment]
I am also facing the same iuuse when simply using ng-select.
![ng-select](https://user-images.githubusercontent.com/48983045/118101502-50ddba80-b3f5-11eb-97cd-bae09a14a36d.PNG)

**Comment by sudarsan900** [comment]
@ashwanizsktm issue was from ng-select side. There was some particular version which was having this issue, so I skipped latest version and downgraded to  previous version and started working fine. Later this issue was fixed from ng-select side and I never faced this issue again.

**Comment by ashwanizsktm** [comment]
Can You just tell me which version is working fine. because as per the instructions I have already tried version 3.3.3 and 3.5.0. 
none of these versions seems working fine. you let me know the exact version that would be better.

**Comment by arun-maddheshia** [comment]
@ashwanizsktm use version `v3.7.3`
