### ISSUE TITLE
Dropdown searchable property true. After selecting the dropdown value sucrose show before the selected text(value).

### ISSUE THREAD

**Issue by rohit64Singh222** [ng-select/ng-select#1432]
Dropdown searchable property true. After selecting the dropdown value sucrose show before the selected text(value).
PFA.
![image](https://user-images.githubusercontent.com/57747188/68838160-04bc9780-06e4-11ea-9ac0-0da81b0ae743.png)

**Comment by varnastadeus** [comment]
#1419
