### ISSUE TITLE
Disabled items are selected when you select a group

### ISSUE THREAD

**Issue by NicolasPennie** [ng-select/ng-select#1434]
**Describe the bug**
When a group is selected that contains disabled items the disabled items are selected. Afterwards there is no way to unselect the disabled items unless you de-select the group.

I would propose that groups should be disabled if they contain any disabled items. This would make the group not selectable. If you want any help I'd be happy to put together a PR.

**Reproducbile example**
Click on the Italy group to trigger the bug: [Stackbliz repro](https://stackblitz.com/edit/angular-sdpzjc)

**To Reproduce** 
Steps to reproduce the behavior (if example is not provided):
1. Use ng-select with groupBy and selectableGroup enabled
2. Set an item within a group to disabled
3. Click on the group
4. Disabled item is now selected, even though it is not selectable. It can not be unselected unless you click the group again.

**Expected behavior**
Groups should be disabled if they contain any disabled items

**Screenshots**
![image](https://user-images.githubusercontent.com/17098781/68866633-bea30c00-06c2-11ea-84b9-ad82d9df1c3e.png)

**Comment by varnastadeus** [comment]
this should be resolved by #1437
