### ISSUE TITLE
[Feature] Clear user search programatically if specific value is selected  

### ISSUE THREAD

**Issue by J1445** [ng-select/ng-select#1438]
Description : 
Well  I am trying to clear  the search value in the ng-select field in multi select mode if value includes a specific text 

Solution :
Is there any event  property that can be triggered if the user selects from the dropdown and based on the selection clear input field which the user was searching 

UseCase : 
This is a  general purpose selection field grouped by chemical properties   Say i have a group of light metals when user selects oganesson in the field i want to clear the search field which he would have searched for light metals  and let him search and select from next group of item

**Comment by varnastadeus** [comment]
you can achieve this with the current API

**Comment by J1445** [comment]
thanks @varnastadeus  for your timely response  i realized i have onAdd functionality but how do i clear text programmatically without  clearSearchOnAdd api's dynamic boolean reference 

So it might be useful to manipulate the user search content like title-casing  or similar

**Comment by varnastadeus** [comment]
Just clear `searchTerm`

**Comment by J1445** [comment]
thank you
