### ISSUE TITLE
Hide added tags (addTag) from the dropdown items

### ISSUE THREAD

**Issue by ricky2k7** [ng-select/ng-select#1445]
I'm trying to use ng-select as both an item selection and a search field.
My issue is that i can't enter a value that's not available in the select list without using addTag. I know this my seem strange, but I don't want to add new items to the list, just use it to search the inputed value.

Currently i'm using the following settings:
`<ng-select placeholder="{{ title }}" [multiple]="true" [(ngModel)]="filters[id]" (change)="changeFilter($event, id)" [clearable]="true" [searchable]="true" [addTag]="true" [selectOnTab]="true" [hideSelected]="true">
              <ng-option *ngFor="let filterData of getFilterData(id)" [value]="filterData">
                {{getFilterLabel(filterData, title)}}</ng-option>
            </ng-select>`

So, what i would like to know is, how i can add a tag but not show it in the dropdown list?

**Comment by varnastadeus** [comment]
You don't need to add an item to be able to search for it, check typeahead example in demo page
