### ISSUE TITLE
ng-select material directive not working with formControlName in reactive form 

### ISSUE THREAD

**Issue by Vicksdev** [ng-select/ng-select#1446]
My issue is its not working in reactive forms if I am using formControlName
`<mat-form-field appearance="outline" fxFlex="50" class="pr-4">
                                    <mat-label>Organization Type</mat-label>
                                    <ng-select ngSelectMat formControlName="organization_type" [items]="organization_type"
                                    placeholder="Organization Type"
                                    bindLabel="itemName" bindValue="id" [(ngModel)]="searchedOrganizationDetails.organization_type"></ng-select>
                                    
                                </mat-form-field>`

The floating label comes back to its position after ng-select losses the focus and the selected value and label overlap on each other (check the image)
![ng-select overlap issue](https://user-images.githubusercontent.com/34940881/69246886-883c2400-0bcf-11ea-91b5-91d49198ca6b.PNG)

**Comment by flohw** [comment]
@varnastadeus What type of info do you need? I just experiment the same issue. The difference is I don't use the ngModel directive on ng-select.

```html

    <form-group label="Commercial principal" [required]="true" [errors]="errors.defaultCommercial">
        <ng-select [items]="areaCommercials" [class.is-invalid]="errors.defaultCommercial.length"
                   bindLabel="fullName" bindValue="id" formControlName="defaultCommercial"></ng-select>
    </form-group>
```

My form-group element only renders a label, ng-content and a div to display errors.
The items are a dynamic list wich I build like so:
```typescript

    get areaCommercials(): Array<Commercial> {
        return this.form.value.commercials.filter((c: (Commercial & {checked: boolean})) => c.checked);
    }
```

Other parts works fine.

I don't have the css issue but I can't click on items to select one of them. The only mothod working is to type "enter" on one of them to select.
