### ISSUE TITLE
Dropdown not opening after limit reach

### ISSUE THREAD

**Issue by dhananjaykaushik** [ng-select/ng-select#1447]
In multi select dropdown when limit is reached. It doesn't open.
If that is a feature. Shouldn't It be optional or input based.
It is not correct for every use case

**Comment by varnastadeus** [comment]
it is by design

**Comment by dhananjaykaushik** [comment]
But that is a bug for me. I'm just asking for it to be made optional

**Comment by dhananjaykaushik** [comment]
Is that a big architectural change for you guys cause I love this dropdown and don't wanna switch ?
Please help me if there is any trick or something that can be done

**Comment by varnastadeus** [comment]
Why do you want to open it if nothing can be done? Just show a warning that maximum selection reached

**Comment by dhananjaykaushik** [comment]
I want to show selected items. SO, he can uncheck them in dropdown only.
I am not showing all items selected, just the count of total selected items.
So can't remove selected item easily. Thats why I want to open the dropdown.

Last dropdown I used was material select with some custom search implementation. In that I didn't let user select more than limit and show error.
I kinda want same functionality.
I am attaching screenshot on how I am currently using ng-select.
![Ng-Select Closed](https://user-images.githubusercontent.com/16631541/69694250-219e9500-10fe-11ea-8950-0b990390c0a9.png)
<img width="320" alt="Ng-Select open" src="https://user-images.githubusercontent.com/16631541/69694251-219e9500-10fe-11ea-9913-d15979e8b04d.png">

**Comment by dhananjaykaushik** [comment]
If limit is reached. Dropdown won't open and I can't remove a specific selection.
So, this feature is working like a bug for me

**Comment by dhananjaykaushik** [comment]
@varnastadeus do you get my issue ??

**Comment by leon-marzahn** [comment]
@varnastadeus I have the same issue as @dhananjaykaushik is it possible to make this as an optional feature?

**Comment by lacroixdavid1** [comment]
Having the same issue here. I also consider this as a bug.

**Comment by anth-git** [comment]
It's ridiculous "it's a feature not a bug". 

```Why do you want to open it if nothing can be done?```
I want to open it in order to deselect items, duh....

Fortunately, a workaround is pretty simple, just handle (add) event, and remove item from the selected items collections if max number is exceeded.

**Comment by willroxby** [comment]
+1 on this :)

**Comment by Corsseir** [comment]
Having the same issue.

**Comment by amoroso81** [comment]
When you use the label template, you could possibly disable the view of the selected items and add just a counter there. That's why a similar option could be really useful. It makes this library easily customizable without recurring to potentially bugged workarounds. Thanks.
