### ISSUE TITLE
Getting eedefineInjectable and Uncaught TypeError: Object(...) is not a function errors

### ISSUE THREAD

**Issue by darnoldi** [ng-select/ng-select#1448]
Hi,

I am trying to use ng-select in an angular 7 project, but on build, I am getting the following warning:

> WARNING in ./node_modules/@ng-select/ng-select/fesm5/ng-select-ng-select.js 321:56-74
"export 'ɵɵdefineInjectable' was not found in '@angular/core'

and in Chrome dev tools the following error 

> ng-select-ng-select.js:321 Uncaught TypeError: Object(...) is not a function
    at ng-select-ng-select.js:321
    at Module../node_modules/@ng-select/ng-select/fesm5/ng-select-ng-select.js (ng-select-ng-select.js:323)
    at __webpack_require__ (bootstrap:83)
    at Module../src/app/shared.module.ts (static-page.service.ts:12)
    at __webpack_require__ (bootstrap:83)
    at Module../src/app/app.module.ts (app.component.ts:8)
    at __webpack_require__ (bootstrap:83)
    at Module../src/main.ts (main.ts:1)
    at __webpack_require__ (bootstrap:83)
    at Object.0 (main.ts:12)

The chrome error displays immediately on execution, and the page is empty.

My current package.json is:
``{
  "name": "app-cadac",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/cdk": "^7.3.7",
    "@angular/common": "~7.0.0",
    "@angular/compiler": "~7.0.0",
    "@angular/flex-layout": "^7.0.0-beta.24",
    "@angular/forms": "~7.0.0",
    "@angular/http": "~7.0.0",
    "@angular/material": "^7.3.7",
    "@angular/material-moment-adapter": "^7.3.7",
    "@angular/platform-browser": "~7.0.0",
    "@angular/platform-browser-dynamic": "~7.0.0",
    "@angular/router": "~7.0.0",
    "@aspnet/signalr": "^1.1.4",
    "@ncstate/sat-popover": "^3.2.0",
    "@ng-bootstrap/ng-bootstrap": "^4.1.0",
    "@ng-select/ng-select": "^3.6.1",
    "@ngx-translate/core": "^11.0.1",
    "@swimlane/ngx-datatable": "^14.0.0",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.5.4",
    "hammerjs": "^2.0.8",
    "jquery": "^3.3.1",
    "jwt-decode": "^2.2.0",
    "moment": "^2.24.0",
    "ng-pick-datetime": "^7.0.0",
    "ng7-dynamic-breadcrumb": "^1.0.5",
    "ngx-cookie-service": "^2.1.0",
    "ngx-gallery": "^5.10.0",
    "ngx-pagination": "^3.2.1",
    "ngx-tinymce": "^7.0.0",
    "perfect-scrollbar": "^1.4.0",
    "prismjs": "^1.16.0",
    "rxjs": "~6.3.3",
    "web-animations-js": "^2.3.1",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.10.7",
    "@angular/animations": "~7.2.14",
    "@angular/cli": "~7.3.8",
    "@angular/common": "^7.2.14",
    "@angular/compiler-cli": "~7.0.0",
    "@angular/core": "~7.2.14",
    "@angular/language-service": "~7.0.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^2.0.5",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.1.1"
  }
}

On searching, I saw a few posts suggesting to remove the ee part from 'ɵɵdefineInjectable' in  ./node_modules/@ng-select/ng-select/fesm5/ng-select-ng-select.js. Doing this though just changes the error to :

> Uncaught ReferenceError: defineInjectable is not defined

I have also read that going back to version 2 could fix this. If I install using npm i -s @ng-select/ng-select@2.20.5, the build warning disappears, the app home page once again renders, but as soon as I click on the link to the page with the relevant form the error changes to:

> core.js:15724 ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'items' since it isn't a known property of 'ng-select'.
1. If 'items' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("ss="col-sm-11">
                                                                        <ng-select [ERROR ->][items]="allItemsList" formControlName="upsellItemId"
                                              "): ng:///AdminAppModule/ItemsEditComponent.html@550:83
Can't bind to 'selectableGroup' since it isn't a known property of 'ng-select'.
1. If 'selectableGroup' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("upBy="productCode"
                                                                                [ERROR ->][selectableGroup]="true"
                                                                           "): ng:///AdminAppModule/ItemsEditComponent.html@554:80
Can't bind to 'selectableGroupAsModel' since it isn't a known property of 'ng-select'.
1. If 'selectableGroupAsModel' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("tableGroup]="true"
                                                                                [ERROR ->][selectableGroupAsModel]="false"
                                                                   "): ng:///AdminAppModule/ItemsEditComponent.html@555:80
Can't bind to 'multiple' since it isn't a known property of 'ng-select'.
1. If 'multiple' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("upAsModel]="false"
                                                                                [ERROR ->][multiple]="true"
                                                                                [c"): ng:///AdminAppModule/ItemsEditComponent.html@556:80
Can't bind to 'closeOnSelect' since it isn't a known property of 'ng-select'.
1. If 'closeOnSelect' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. (" [multiple]="true"
                                                                                [ERROR ->][closeOnSelect] = "false"
                                                                          "): ng:///AdminAppModule/ItemsEditComponent.html@557:80
'ng-select' is not a known element:
1. If 'ng-select' is an Angular component, then verify that it is part of this module.
2. If 'ng-select' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("   <div class="col-sm-11">
                                                                        [ERROR ->]<ng-select [items]="allItemsList" formControlName="upsellItemId"
                                   "): ng:///AdminAppModule/ItemsEditComponent.html@550:72
Can't bind to 'items' since it isn't a known property of 'ng-select'.
1. If 'items' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("col-sm-11">
                                                                            <ng-select [ERROR ->][items]="allItemsList" formControlName="upsellItemId"
                                              "): ng:///AdminAppModule/ItemsEditComponent.html@610:87
Can't bind to 'selectableGroup' since it isn't a known property of 'ng-select'.
1. If 'selectableGroup' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("="productCode"
                                                                                    [ERROR ->][selectableGroup]="true"
                                                                           "): ng:///AdminAppModule/ItemsEditComponent.html@614:84
Can't bind to 'selectableGroupAsModel' since it isn't a known property of 'ng-select'.
1. If 'selectableGroupAsModel' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("eGroup]="true"
                                                                                    [ERROR ->][selectableGroupAsModel]="false"

The errors are leading me to believe that the component is not being included properly somehow, but I definitely have it in app.module.ts as well as shared.module.ts.

``import { NgSelectModule } from '@ng-select/ng-select';
.
.
.
 imports: [
.
.
 NgSelectModule,
.
.

I am thinking this is a versioning issue, but have tried everything that I can think of and would appreciate some input if possible.

Many thanks

**Comment by varnastadeus** [comment]
because version 3.x is not compatible with angular 7
