### ISSUE TITLE
Huge problem with compositionStart/end 

### ISSUE THREAD

**Issue by steve3d** [ng-select/ng-select#1449]
**Describe the bug**
I know this is a new feature in 3.6.0, but this caused me huge problem, my main platform is pc, and you know there are so many differenent browser exists, and the all processing the compositionStart/end with small difference. for example, one of my client has 90% chances there is no display after single  select with `searchable = true`, and I also encountered some.

and seems I've found a problem, your code here
```
    onCompositionEnd(term: string) {
        if (this.searchWhileComposing) {
            return;
        }
        this._isComposing = false;
        this.filter(term);
    }
```

`searchWhileComposing` are default to true, so the `this._isComposing` is never set to false, and this will cause `ng-select-filtered` will never be removed, and so, the select value will have `visibility` to `hidden`.

I think you should change the code to
```
    onCompositionEnd(term: string) {
        this._isComposing = false;
        if (!this.searchWhileComposing) {
              this.filter(term);
        }
    }
```
and this will make sure  `this._isComposing` can be correctly set to false and remove `ng-select-filtered`

and I'm Chinese user, we always need a IME on any OS.

**Reproducbile example**
really hard to reproduce, on latest chrome there are 95% chance it work, but on one of my client's browsers(he tried 4 different browsers), there are 95% chance it won't work, selected value is hidden.

**Comment by steve3d** [comment]
and I'm confirmed with my clients, my modification works perfect, the orginal code has problem, which will never set `_isComposing` to false when `searchWhileComposing` is true.

**Comment by vesauimonen** [comment]
I can reproduce this issue consistently on an older Android 7 smartphone with Chrome v78.
