### ISSUE TITLE
Selected value not shown, when keyboard has suggestion strip enabled on Android

### ISSUE THREAD

**Issue by vesauimonen** [ng-select/ng-select#1451]
**Describe the bug**
When searching and selecting a value from an ng-select input, the selected value is not shown in the input. This happens only on Android, when the virtual keyboard has suggestion strip on.

**To Reproduce** 
1. Go to [ng-select demo page](https://ng-select.github.io/ng-select#/data-sources)
2. Click on the select under *Backend data with async pipe*
3. Write for example "me"
4. Click "Mendoza Ruiz"
5. See empty select input

**Expected behavior**
The selected value is displayed.

**Screenshots**

![ng-select-bug 2019-11-25 17_07_59](https://user-images.githubusercontent.com/1443031/69551907-2cdead00-0fa6-11ea-9b12-78fd82ace869.gif)

**Desktop:**
 - Does not reproduce on desktop

**Smartphone:**
 - Device: Pixel 2
 - OS: Android 10
 - Browser: Chrome
 - Version: 78
 - **Suggestion strip has to be enabled**, for instance on Pixel device in *Settings → System → Languages & input → Virtual keyboard → Gboard → Text correction → Show suggestion strip*

**Additional context**
It seems that the `compositionstart` event is fired, but a subsequent `compositionend` is never fired on the search input, when the option is clicked:

https://github.com/ng-select/ng-select/blob/87908d3903d8afdfe538c0f7ee1afcbd3d42bcef/src/ng-select/lib/ng-select.component.html#L38

This means, that the internal `this._isComposing` flag does not get turned off:

https://github.com/ng-select/ng-select/blob/87908d3903d8afdfe538c0f7ee1afcbd3d42bcef/src/ng-select/lib/ng-select.component.ts#L538-L545

This results in the selected value not being displayed due to:

https://github.com/ng-select/ng-select/blob/87908d3903d8afdfe538c0f7ee1afcbd3d42bcef/src/ng-select/lib/ng-select.component.ts#L179

**Comment by i-aleksandrov** [comment]
My client alerted me that he has this behavior on his Pixel 3, but works fine on an iPhone, I ran tests on AWS Device farm on Pixel 2 and Pixel 3 XL and could only reproduce the bug on Pixel devices, I tried on Galaxy S10+ and it worked fine, and also it works fine on any other device such as my laptop.

**Comment by iRipVanWinkle** [comment]
Hotfix:
`<ng-select #select (close)="select.blur()"></ng-select>`

**Comment by jeroenvheel** [comment]
@iRipVanWinkle you fix is working !!

**Comment by esaesa** [comment]
Same problem on android 9.0 latest chrome. Samsung Galaxy

**Comment by Hagith** [comment]
@iRipVanWinkle @jeroenvheel it's working, but disturbs keyboard navigation.

**Comment by vesauimonen** [comment]
This issue still reproduces. Are there plans for fixing this? Currently this is blocking us from upgrading from v3.0.4.

**Comment by vltansky** [comment]
As I mentioned in https://github.com/ng-select/ng-select/pull/1556 there is also a CSS hotfix:

`.ng-select.ng-select.ng-select-single.ng-select-filtered:not(.ng-select-opened) .ng-select-container.ng-has-value .ng-value-container .ng-value{ visibility: visible; }`

**Comment by jpvanhal** [comment]
Could you please reopen this? The issue is still valid and there has been activity in this issue since the bot marked this stale.

**Comment by ssvvd** [comment]
I have same problem, not in Android,
in  Windows.

Angular - version 9
ng-select - version 4.0.0
I tried to apply all recommendations , but the problem didn't solved.

**Comment by ssvvd** [comment]
My code:
**appdetails.component.html:**
`<ng-select  class="custom" [items]="arrdiameter" 
                                        [virtualScroll]="true"                           
                                        bindLabel="Description"                           
                                        bindValue="Value"                                                                                                         
                                        (change)="onChange($event)"
                                        appendTo = 'body'
                                        >                            
                                </ng-select>`

**appdetails.component.scss:**
`.ng-select.custom {
    border:0px;
    min-height: 0px;
    border-radius: 0;
}
.ng-select.custom .ng-select-container  {            
    min-height: 0px;
    border-radius: 0;  
}

.ng-select.custom ::ng-deep .ng-select-container  {            
    min-height: 0px;
    border-radius: 0;    
}

ng-select.ng-invalid.ng-touched .ng-select-container {
    border-color: #dc3545;
    box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 0 3px #fde6e8;
}`

**appdetails.component.ts:**
` export interface DiameterHole
{
  Value:number;
  Description:string;
}

this.eventsSubscription.add(this.srv_DataLayer.holediameterdrilling(this.srv_appsetting.Units).subscribe((res: any) => {
      this.arrdiameter= JSON.parse(res);    
      }
      )
    ); `

before select:
![1](https://user-images.githubusercontent.com/30229013/80298262-1924b600-8793-11ea-9bf2-24511c22364e.png)

after select:

![2](https://user-images.githubusercontent.com/30229013/80298279-48d3be00-8793-11ea-8e06-121d962f13ce.png)

**Comment by vltansky** [comment]
@ssvvd is it a screenshots taken from phone or desktop?
Did you try to add
`
.ng-select.ng-select.ng-select-single.ng-select-filtered:not(.ng-select-opened) .ng-select-container.ng-has-value .ng-value-container .ng-value{ visibility: visible; }
`
to `styles.scss`?
Could you upload your example to stackblitz.
I tried to prepare an example based on your code https://stackblitz.com/edit/angular-neepmy?

**Comment by ssvvd** [comment]
It's a screenshots from desktop.

I tried to add to styles.scss this code but it's not help.
I checked  this example 
[https://stackblitz.com/run?file=src/data-source-backend-example.component.html](url) in my project too. ( I copied all files to my  project ).
and this control from example  is displayed not correct in my project.

May be it is problem of Angular version or the project's settings?
 
Thanks.
Hag sameah!

**Comment by vltansky** [comment]
> It's a screenshots from desktop.
> 
> I tried to add to styles.scss this code but it's not help.
> I checked this example
> [https://stackblitz.com/run?file=src/data-source-backend-example.component.html](url) in my project too. ( I copied all files to my project ).
> and this control from example is displayed not correct in my project.
> 
> May be it is problem of Angular version or the project's settings?
> 
> Thanks.
> Hag sameah!

Stackblitz example based on Angular 9.1.4, so I don't think its a problem with an Angular version.
Which version of angular & ng-select are you using?
It looks to me like a problems in your project settings. 
In this example I see that your background color is gray
![image](https://user-images.githubusercontent.com/5851280/80788718-8caf3480-8b92-11ea-9925-b47b92ac13bc.png)

but in CSS that you are using I cant see what's making it gray.
```css
.ng-select.custom {
border:0px;
min-height: 0px;
border-radius: 0;
}
.ng-select.custom .ng-select-container {
min-height: 0px;
border-radius: 0;
}

.ng-select.custom ::ng-deep .ng-select-container {
min-height: 0px;
border-radius: 0;
}

ng-select.ng-invalid.ng-touched .ng-select-container {
border-color: #dc3545;
box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 0 3px #fde6e8;
}
```
Do you have any extra css that can influence ng-select? 
For example, if I will apply gray background to `input` or `.ng-select` it will reproduce your bug.
Try adding to your `styles.scss`
```css
.ng-select .ng-select-container .ng-value-container .ng-input, .ng-select .ng-select-container .ng-value-container .ng-input>input{
 background: none!important;
}
```
if it doesn't help try removing all your CSS and see if it's still reproduces.
![image](https://user-images.githubusercontent.com/5851280/80788937-3989b180-8b93-11ea-9995-fe7ecbc6ec6e.png)


Is your project open source / can you upload it to GitHub, so we'll be able to see whats going on?
If you want you can share it with me in private, i'd try to help. vl.tansky@gmail.com
