### ISSUE TITLE
ng-select-ng-select has no exported member 'NG_SELECT_DEFAULT_CONFIG'

### ISSUE THREAD

**Issue by khteh** [ng-select/ng-select#1453]
**Describe the bug**

Migrating to the latest package results in the build error.

**Reproducbile example**
[Example](https://stackblitz.com) which reproduces described behaviour

**To Reproduce** 
Steps to reproduce the behavior (if example is not provided):

**Expected behavior**
No build error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 19.10
 - Version [e.g. 22] `"@ng-select/ng-select": "3.6.2",`

**Smartphone (please complete the following information):**

**Additional context**
```
src/app/global.module.ts:23:26 - error TS2305: Module '"../../node_modules/@ng-select/ng-select/ng-select-ng-select"' has no exported member 'NG_SELECT_DEFAULT_CONFIG'.

23 import { NgSelectModule, NG_SELECT_DEFAULT_CONFIG } from '@ng-select/ng-select';
```
I can probably remove the symbol import but how about the providers?
```
	providers: [
		{
			provide: NG_SELECT_DEFAULT_CONFIG,
			useValue: {
				notFoundText: 'Not found',
				loadingText: 'Processing',
				placeholder: 'Please input'
			}
		}
	]
```

**Comment by varnastadeus** [comment]
this was never exported and shouldn't be used directly
