### ISSUE TITLE
Ability to disable "back to top" or "top to down" of selection mark 

### ISSUE THREAD

**Issue by patron** [ng-select/ng-select#1455]
I can't exactly describe whether it bug or feature. But I think ng-select needs such feature a lot, especialy when data is loaded dynamicaly from remote server and it loaded page by page. I think it's unnescessary to put mark back to top or viceversa. Sorry for my English (cause I'm not native speaker) if something left misunderstood there is link from StackOwerFlow thread with the same issue: https://stackoverflow.com/questions/55834860/prevent-select-field-from-infinite-scrolling-ng-select-angular and StackBlitz Example: https://stackblitz.com/edit/ng-select-mbnngu
 I hope I'll give you PR with solution of this issue soon. Thanks for reading.

**Comment by patron** [comment]
If there some bads in my code I always ready to correct it

**Comment by varnastadeus** [comment]
How you considered using `[keyDownFn]` instead of introducing API changes?

**Comment by patron** [comment]
@varnastadeus No, I didn't but anyway I don't think that `[keyDownFn]` handler is helpful in my case. How can I turn off cyclic keyboard navigation through the lis using `[keyDownFn]` ? please help me with example if I misunderstood something. So that's why I've introduced some API changes. Anyway, IMHO I think users of ng-select need easier way to turn of anoying way of keyboard navigation. Thanks for response!

**Comment by patron** [comment]
@varnastadeus I tried to turn off keyboard events when bottom of option list reached and data started to load but that wasn't helpful too.

**Comment by varnastadeus** [comment]
pseudo code:
```js
function keyDownFn() {
    if markedItem == last
        return false
     return true
}

```

**Comment by patron** [comment]
@varnastadeus I undertand what you want suggest to me, but this pseudo code can't help me to fix problem because I haven't any clue how to pass `markedItem` into `keyDownFn()` can you tell me how? I don't suggest to break any compability of API I just suggest simpler way to turn off endless loop keyboard scrolling. Everything is OK with mouse scrolling, but why keyboard scrolling is need to be looped?

**Comment by patron** [comment]
Even native HTML select for is not looped by default so I think it's good idea to make ng-select not looped by default too. Or add feature simply to turn off looped scroling.

**Comment by patron** [comment]
@varnastadeus I don't want to break something or make code or API bloated or buggy. All I need is solving loop keybord navigation problem. So if API can't be changed I decided to turn you pseudo code example to real code. All I need to implement solution is way how to **get marked element** in dropdown. Thanks for reading

**Comment by varnastadeus** [comment]
```ts
select.itemsList.markedItem
```

`select` is `@VIewChild`

**Comment by patron** [comment]
Hi @varnastadeus thanks a lot for answers. But there I tried to use `keyDownFn` handler but there no any way to pass anything to it cause `keyDownFn`  is arrow fuction so I can only pass `KeyboardEvent` to it and I needed to update my ng-select package to last version. I got items  using `select.itemsList.markedItem` but there is no way to use them in `keyDownFn` handler. `keyDownFn` can't see Component's `this`.  Thanks for answers.

**Comment by patron** [comment]
UPD: I've found how to pass component's `this` scope to `keyDownFn`. I found that it can be done by code like this: [keyDownFn]="keyDownHandlerFunction.bind(this)".   
I tried to implement your pseudo-code solution into real code and got this code:
`  public preventLoopNavigation(event: KeyboardEvent) {
    if (this.ngSelect.itemsList.markedItem === 
 this.ngSelect.itemsList.items[this.ngSelect.itemsList.items.length - 1] && event.key === "ArrowDown") {
return false;
    } else if (this.ngSelect.itemsList.markedItem === 
 this.ngSelect.itemsList.items[0] && event.key === "ArrowUp") {
return false;
    }
return true;
  }`
But unfortunately that code wasn't helpful because IMHO `_getNextItemIndex(steps: number)` method and others executes faster then `keyDownFn` handler. So I think my solution described in my PR is more reliable and simple. Thanks for answers

**Comment by patron** [comment]
Hi @varnastadeus ! So I tried to implement solution using pseudo-code provided by you, but unfortunately it doesn't work. Is there some other solution of this problem? Thanks!

**Comment by varnastadeus** [comment]
it should work, `keyDownFn` executes before any other logic

**Comment by patron** [comment]
@varnastadeus yeah it works, but it's not enough. Finally I found what wrong with this solution.  The problem is when the bottom of **dropdown is reached** and **new portion of data (options) is loaded** from server **mark disappearing** and **then it puts it to the first element** as by default.  But when mouse cursor is inside dropdown - mark doesn't disappear and everything work as I want.  So is there way to save mark inside of dropdown after data loaded using only keyboard? I use code like that to load data:
 `  public currentPageLoad(rows: number, page: number, search?: string): void {
    this.symbolsService.loadOptions({ rows: rows, page: page, search: search }).subscribe(data => {
      this.options = this.options.concat(data);
    });
  }`
Am I doing something wrong?
Thanks for answer.

**Comment by patron** [comment]
@varnastadeus Hi! So is there any solution? :)

**Comment by patron** [comment]
@varnastadeus Hi! May be you are to busy so may be there is someone else who can help me with this issue? I like ng-select and I work on some project which hardly depends on it. So I need help :(

**Comment by varnastadeus** [comment]
I am closing this as an original issue have been answered, if you have other problems create a separate issue

**Comment by ilapavuluri** [comment]
Thanks @patron the above worked for me, but observed one small issue, while doing keyboard navigation with the above code already selected value is vanishing.

Appreciate your response

**Comment by patron** [comment]
@ilapavuluri Hi! The only way to solve this problem is to write such buggy code: `
import { NgOption, NgSelectComponent } from '@ng-select/ng-select'; // Import ng-select as component
@ViewChild('ngSelect', { static: true }) public selectComponent: NgSelectComponent; // put ngSelect directive or selector in template

    // These select and unselect methods calls fix unmarking of last item after options loaded (DO NOT REMOVE NEXT 2 lines of code)
 if (this.symbols.length > 0) {
this.selectComponent.itemsList.select(this.selectComponent.itemsList.items[this.selectComponent.itemsList.items.length - 1]);      this.selectComponent.itemsList.unselect(this.selectComponent.itemsList.items[this.selectComponent.itemsList.items.length - 1]);}
`
Hope that was helpful

**Comment by ilapavuluri** [comment]
@patron Thank you so much patron, it resolved my issue.

I recently upgraded to Angular 9 (ng-select 4) after that scrolldown is not returning proper results with filter condition, the reason for this is select.filterValue is returning undefined, this was working fine in old version.
Appreciate your help

Please refer the below(the below was working fine in ng-select 2.x and not working in 4.x)
https://stackblitz.com/edit/ng-select-infinite
https://github.com/ng-select/ng-select/issues/700

**Comment by patron** [comment]
@ilapavuluri I looked to stackblitz and I don't know accurate answer. Try to write such code: 
```
import { NgOption, NgSelectComponent } from '@ng-select/ng-select'; // Import ng-select as component
@ViewChild('ngSelect', { static: true }) public selectComponent: NgSelectComponent; // put ngSelect directive or selector in template

  public keyDownHandler(event: KeyboardEvent) {
    this.currentlyMarkedItem = this.selectComponent.itemsList.items[
      this.selectComponent.itemsList.items.indexOf(this.selectComponent.itemsList.markedItem) + 1
    ];
    if (
      this.selectComponent.itemsList.markedItem === this.selectComponent.itemsList.items[this.selectComponent.itemsList.items.length - 1] &&
      event.key === 'ArrowDown'
    ) {
      return false;
    } else if (this.selectComponent.itemsList.markedItem === this.selectComponent.itemsList.items[0] && event.key === 'ArrowUp') {
      return false;
    }

    return true;
  }
```
And don't forget to add `[keyDownFn] `to your `ng-select `like this:  `<ng-select [keyDownFn]="keyDownHandler.bind(this)">`
-----------------
Try to find the reason why you get `undefined` may be everything filtered alrightly, maybe not. Maybe problem is that you should use `static: false` in line `@ViewChild('ngSelect', { static: true }) public selectComponent: NgSelectComponent;` or try to use lifecycle hooks. I don't tried latest Angular versions lates version I worked with is 8 but I don't think that there are breaking changes in Angular 9. Unfortunately I was fired from previous work because I spent to much time fixing such stupid bugs.

**Comment by ilapavuluri** [comment]
Thank you @patron  for your help!

**Comment by patron** [comment]
@ilapavuluri ask me for help I'll answer if I can
