### ISSUE TITLE
Custom tags improvements

### ISSUE THREAD

**Issue by anjmao** [ng-select/ng-select#146]
1. Show `Add item "value"` in all cases except if exact match is found. Currently it is shown only if no other items are found, but then it is not possible to add you Custom tag in most cases.
In this case I want to add tag `kas` but it is not allowed.
![image](https://user-images.githubusercontent.com/3028012/33255732-9ba04b14-d357-11e7-8585-f563163ad83e.png)

2. Custom tags are always present in the dropdown when searching with typeahead, we need to hide them on search if they do not match.

**Comment by varnastadeus** [comment]
also 
1. select show selected values, even if they don't match filter term
2. opening filter, shows last added tag
<img width="843" alt="screen shot 2017-11-26 at 16 30 10" src="https://user-images.githubusercontent.com/17824796/33240910-2bf63d4a-d2c7-11e7-8f84-bd95f2b3003c.png">

**Comment by varnastadeus** [comment]
4. check if tag exists among selected values also.
