### ISSUE TITLE
(clear) not being triggered in IE 10 and deleting value does not work

### ISSUE THREAD

**Issue by St3v3oh** [ng-select/ng-select#1461]
Hello everyone,

i'm experiencing a bug in IE in IE 10 Document Mode - the selected value cannot be removed by pressing the clear-button (the small x).

This particular issue is with version 2.20.5 - however this also applies to your latest version which (I'm guessing) is showcased on your git page.

Very easily reproducable, just visit your own site 
https://ng-select.github.io/ng-select#/data-sources
with an IE version and select IE 10 Docmode in the browsers developer console under the tab "emulation" (naming might differ, browser isnt set to english)

I've tried logging something in console when (clear) is executed but that point is never reached.

Hope this is enough information

**Comment by varnastadeus** [comment]
latest IE we "support" is 11

**Comment by St3v3oh** [comment]
That is unfortunate because basically every single feature works except for this one.

**Comment by vladimirverbitski** [comment]
@St3v3oh have you got a solution for this?

**Comment by St3v3oh** [comment]
@vladimirverbitski Unfortunately the only workaround I found was checking for the browser and dynamically displaying a button users could use to clear the dropdown from there
