### ISSUE TITLE
Ant Design theme problems, angular 8

### ISSUE THREAD

**Issue by patricknazar** [ng-select/ng-select#1462]
**Describe the bug**
The Ant Design theme works ok in the website demo, but not in a modified stackblitz example or in my app

**Reproducible example**
[Example](https://stackblitz.com/edit/angular-sdwjvr?file=styles.css)

**To Reproduce** 
Hover over the select, the dropdown icon doesn't appear properly and neither does the clear x icon

**Expected behavior**
It should work, at least as good as the website when Ant Design theme is selected

**Screenshots**
![ant-design-theme-ng-select](https://user-images.githubusercontent.com/5165547/70347872-94093500-18b5-11ea-8326-328c9316a725.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 
 - Version 78.0.3904.108

**Additional context**
Tested on 3.7.0 but I also tested way back and the problem still exists. I've imported the theme by `@import`ing in `styles.scss` and I've tried it in `angular.json` too same problem.

**Comment by jwright04** [comment]
This is also an issue with the demo on Stackblitz example: https://stackblitz.com/run?file=src/group-default-example.component.html

**Comment by aklaffenboeck** [comment]
Is there any solution or at least activity on this topic? A fix or workanround would be very nice :)

**Comment by r0fest** [comment]
@patricknazar , @aklaffenboeck Basic styles overwrite theme styles, since the order of their placement in the HTML structure is violated.

The problem can be solved by dynamically connecting theme styles to the end of the head tag, as is done in the demo ng-select.

The second solution is to force overwrite the styles.
```
.ng-select .ng-arrow-wrapper .ng-arrow {
  width: 8px !important;
  height: 8px !important;
}

.ng-select .ng-clear-wrapper {
  position: absolute !important;
  width: 12px !important;
}

.ng-select .ng-clear-wrapper .ng-clear {
  font-size: 12px !important;
  line-height: 12px !important;
}
```
