### ISSUE TITLE
Clear selectbox after is clicked

### ISSUE THREAD

**Issue by senzacionale** [ng-select/ng-select#1467]
I have a question. Is it possible to clear seletbox after you select one elemnt from selectbox so no one is preselected again?

**Comment by duzenko** [comment]
is this repo dead?

**Comment by hayleymdawson** [comment]
@duzenko i guess it is which is a shame. that said
@senzacionale in *some* cases it is possible to clear on click, by hooking into the (open) emit and clearing your model (or your search value there's apparently a way to do that too another issue documented it). 

I doubt that solves all cases by any means, but it will solve *some* of them (it solved mine).
