### ISSUE TITLE
ng-option and angular-svg-icon do not work together

### ISSUE THREAD

**Issue by alyalin** [ng-select/ng-select#1468]
**Describe the bug**
ng-option does not display SVG icon via angular-svg-icon

**Reproducbile example**
[Example](https://stackblitz.com/edit/ng-select-svg-issue) which reproduces described behaviour

**Expected behavior**
ng-option renders the icon from angular-svg-icon just like img tag

**Desktop (please complete the following information):**
 - OS: Mac Os 10.15.2
 - Browser: Chrome
 - Version: 78.0.3904.108

**Comment by varnastadeus** [comment]
update to latest version

**Comment by alyalin** [comment]
in stackblitz I use ng-select@3.7.0

**Comment by varnastadeus** [comment]
oh, you can only use pure html with ng-options, that's current limitation
