### ISSUE TITLE
Fails to compile with noImplicitAny:true in tsconfig.js

### ISSUE THREAD

**Issue by travis1234** [ng-select/ng-select#147]
### Actual behavior
I got the below error when trying to compile my application, I was able to workaround the issue by setting noImplicitAny to false in my tsconfig.ts file but it would be good to get a fix for this.

```
ERROR in node_modules/@ng-select/ng-select/ng-select/ng-select.component.d.ts(29,25): error TS7006: Parameter 'term' implicitly has an 'any' type.
```

### More Info
ng-select version: 0.10.0 (Latest)

browser: IE11, Firefox Nightly

**Comment by anjmao** [comment]
@travis1234 You need to change you tsconfig to exclude node modules or add skipLibCheck because you don't want to compile 3th party applications.

```
{
  "compilerOptions": {
    "noImplicitAny": true,
    "skipLibCheck": true,
    ...
}
```
