### ISSUE TITLE
Template does not reflect search term changes

### ISSUE THREAD

**Issue by jbgroce21** [ng-select/ng-select#1472]
**Describe the bug**
When displaying dynamic data in the template, that data is not displayed when the search term changes if the item remains in the list.

**Reproducbile example**
https://stackblitz.com/edit/ng-select-cgi3jz

**To Reproduce** 
Steps to reproduce the behavior (if example is not provided):
1. Focus on select box to reveal all items with no tags listed
2. Type 'fishy' to see empty message
3. Click backspace to see all items and their tags
4. Type 'fi' ('fishfi' as the search term)

**Expected behavior**
The tag string should be calculated every time the search string is updated. The 'search' variable is not even updated in the template.

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser: Chrome
 - Version:  78.0.3904.108

**Comment by varnastadeus** [comment]
please use latest version and check if it is still reproducible

**Comment by jbgroce21** [comment]
I've updated the code on the stackblitz link with the following versions and I'm still seeing the issue.
"@ng-select/ng-select": "3.7.0",
"@ng-select/ng-option-highlight": "0.0.4"

**Comment by Stadus** [comment]
Any updates regarding this bug?
Currently having this as well...

"@ng-select/ng-select": "2.20.5"
"@ng-select/ng-option-highlight": "0.0.4"
