### ISSUE TITLE
How to set input field value?

### ISSUE THREAD

**Issue by elementalPRESS** [ng-select/ng-select#1473]
Hi there,

I really love ng-select but I have one problem to set the value of the input element. I'm searching on a list (list of objects) of people like shown in the code, which works perfectly.

Doing the search is via a typeahead that is stored in listinput$ which is initialized via

	this.listinput$ = new BehaviorSubject(this.fullname);

The expected behaviour is that ng-select is doing the REST-request and when an object is found that it is selected. Works great!

If the search fails or it returns an empty result I'd like to see the original input value still in the ng-select input field. But unfortunately the field is cleared. How can I prevent this?

	<ng-select [items]="list$ | async"
		bindLabel="fullname"
		[placeholder]="placeholder"
		[loading]="listLoading"
		[typeahead]="listinput$"
		[virtualScroll]="true"
		[(ngModel)]="item"
		[disabled]="disabled"
		appendTo="body"
		(change)="selectSearch($event)"
		(focus)="onFocus($event)"
		(clear)="clear($event)"
	>

	this.list$ = concat(
		of([]), // default items
		this.listinput$.pipe(
			debounceTime(200),
			distinctUntilChanged(),
			tap(() => this.listLoading = true),
			switchMap(term => this.searchService.search(term, this.gender, this.nationality)
						 .pipe(
					  		tap(response => console.log(response) ),
					  		catchError(() => of([])), // empty list on error
					  		tap(() => this.listLoading = false)
						)
			)
		)
	);

**Comment by SavageCore** [comment]
Did you ever figure this out?
