### ISSUE TITLE
Can't change the style of .ng-select-container

### ISSUE THREAD

**Issue by joekaiser** [ng-select/ng-select#1474]
**Describe the bug**
_I'm not sure if this belongs here. Maybe it is a quirk with angular or something else._   
You can't override the style of `.ng-select-container` in a components stylesheet. I took a look at #718, but I am pretty sure my specicifity should be higher than what is used in the deafult style sheet. One thing I find odd is that the dev tools extension doesn't even show the rule as matching and being ignored because another rule is more specific.

You are able to override `.ng-select-container` in the top level stylesheet (shown as green in the example)  but not in a component's stylesheet.

**Reproducbile example**

In this example I am trying to make the border red, but what I really want to do is get rid of the `border-[top][bottom]-right-radius` 

https://stackblitz.com/edit/angular-tr3x7f

**To Reproduce** 
Try to override the style of .ng-select-containter from the stylesheet of a component

**Expected behavior**
The style is overridden as defined in CSS. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Chrome  and Brave

**Comment by varnastadeus** [comment]
explained here https://github.com/ng-select/ng-select#custom-styles

**Comment by Yagneshdxt** [comment]
> explained here https://github.com/ng-select/ng-select#custom-styles

How can I overwrite "ng-dropdown-panel" with your custom example we are not able to overwrite dropdown panel.

Just a suggestion why can't ng-select refer to css/scss file instead of appending css/scss in head>style tag. referencing scss/css file will add so much flexibility to customize css and scss
