### ISSUE TITLE
Error Binding object({"id":"90277b90-1298-11ea-8d71-362b9e15566"7,"language":"English"}) with bindValue is not allowed.

### ISSUE THREAD

**Issue by thedevankit-0** [ng-select/ng-select#1477]
**Describe the bug**
while using ngselect with fromcontrol its not sets the selected value. 
` <ng-select [items]="languages" formControlName="userLanguages" bindLabel="language" bindValue="id"
                  [multiple]="true" (add)="onLanguageAdd($event)" (remove)="onLanguageRemove($event)"
                  notFoundText="No such language found">
                </ng-select>   `
**Expected behavior**
It should show the pre selected values from fromcontrol. 

**Desktop (please complete the following information):**
 - OS: win 10
 - Browser: chrome]
 - Version: v3.x

**Additional context**
My array looks like below.
`Selected language is[{"id":"90277b90-1298-11ea-8d71-362b9e155667","language":"English"},{"id":"90277cc6-1298-11ea-8d71-362b9e155667","language":"Hindi"},{"id":"90277e10-1298-11ea-8d71-362b9e155667","language":"Arabic"},{"id":"90277f6e-1298-11ea-8d71-362b9e155667","language":"Portuguese"}]
`

**Comment by varnastadeus** [comment]
You can't use bindvalue and set object at the same time

**Comment by varnastadeus** [comment]
https://github.com/ng-select/ng-select/issues/148
