### ISSUE TITLE
Ability to disable infinite scrolling

### ISSUE THREAD

**Issue by patron** [ng-select/ng-select#1479]
@varnastadeus Hi! I created Issue https://github.com/ng-select/ng-select/issues/1455 some time ago. And you suggested solution, but it doesn't work. Using `[keyDownFn]` improves ng-select's behaviour but doesn't solve issue completely. The issue is infinite scroll navigation. I think it should be configurable. When I code `[keyDownFn]`  handler it **work only when mouse cursor is inside of dropdown**. But **when I use keyboard only navigation - mark disapering on the last item and then put to the first item**.  So I suggested PR to solve this problem. But I think it won't be merged or accepted. I tried to hack ng-select but I have no clue what to do with private method (how to replace it). Unfortunately project I work with hardly depends on ng-select, so the only way to solve the problem is making corporative fork of ng-select :( . Thanks for your attention.

**Comment by patron** [comment]
@varnastadeus finally I found the way to solve the problem. The problem wasn't that I haven't used `[keyDownFn] ` . I wrote `  public keyDownHandler(event: KeyboardEvent) {
    if (
      this.selectComponent.itemsList.markedItem === this.selectComponent.itemsList.items[this.selectComponent.itemsList.items.length - 1] &&
      event.key === 'ArrowDown'
    ) {
      return false;
    } else if (this.selectComponent.itemsList.markedItem === this.selectComponent.itemsList.items[0] && event.key === 'ArrowUp') {
      return false;
    }

    return true;
  }`
to disable loop. And then I faced one another problem. The problem was that after loading next portion of element from the server mark was maggicaly disapering. After writing code below all my problems was solved `    this.selectComponent.itemsList.select(this.selectComponent.itemsList.items[this.selectComponent.itemsList.items.length - 1]);
    this.selectComponent.itemsList.unselect(this.selectComponent.itemsList.items[this.selectComponent.itemsList.items.length - 1]);`
But solution is to late so I will by fired from my job next month :( Thanx anyway and Happy New Year

**Comment by ilapavuluri** [comment]
Thanks @patron the above worked for me, but observed one small issue, while doing keyboard navigation with the above code already selected value is vanishing.

Appreciate your response
