### ISSUE TITLE
Cursor jumps to end of input text on safari browser.

### ISSUE THREAD

**Issue by RanjeetEppa18** [ng-select/ng-select#1480]
https://ng-select.github.io/ng-select#/data-sources

If you keep the cursor in the middle of the text and start typing, the cursor moves to the end.
It doesn't happen on other browsers though. 
provide some solutions please.

**Comment by boddhin** [comment]
The same issue is also in IE11, please help.

**Comment by wzc0415** [comment]
same issue in safari, please fix it

**Comment by armved** [comment]
Same thing on Safari.

**Comment by RanjeetEppa18** [comment]
@wzc0415 @armved Solution is way simple. All has to be done is using `ngmodel` instead of `input`. If you have forked this repo, change `input` to `ngmodel` and the problem will be solved.
