### ISSUE TITLE
the selected option isn't visible on mobile devices

### ISSUE THREAD

**Issue by sanghviyash** [ng-select/ng-select#1482]
I am using **v3.7.1**

Issue: On mobile devices, if a selection is cleared and new selection is done then the selected option isn't visible. This problem doesn't occur while doing responsive testing in Chrome.

The screen recording of the ng-select website is available [here](https://drive.google.com/file/d/1stFyWIywRu-oAfM8Vyuo4qEDGLXXFdOB/view?usp=sharing).

Possible Reason: The option statys invisble due to `visibility:hidden` on `.ng-select.ng-select-single.ng-select-filtered .ng-select-container .ng-value-container .ng-value` classes when inspected.

Workaround and it's issue: I tried setting `visibility:visible`, which made it work but then the pre-selected option and new search is overlapping.

**Comment by varnastadeus** [comment]
I think it is dup of https://github.com/ng-select/ng-select/issues/1451

**Comment by sanghviyash** [comment]
[Solution](https://github.com/ng-select/ng-select/issues/1451#issuecomment-565190419)
