### ISSUE TITLE
Multiselect checkbox tab key accessibility issues

### ISSUE THREAD

**Issue by Romko775** [ng-select/ng-select#1486]
Hi!
When I was using <ng-select [multiple]="true"> the multiple checkbox items can`t be focused by tab and the clear 'X' either

**Comment by varnastadeus** [comment]
should be addressed here #699

**Comment by Romko775** [comment]
@varnastadeus I see @brunano21 PR, but https://ng-select.github.io/ng-select#/multiselect-checkbox here it is not working
