### ISSUE TITLE
how i can use [inputAttrs]

### ISSUE THREAD

**Issue by necati12** [ng-select/ng-select#1487]
hi,

I want add a special directive to input.
**sample:**
```
<input AutoSizeInput 
       [includeBorders]="false"
       [includePlaceholder]="sec"
       (keyup)="onKeyup($event.target)">
```

**above attributes** i want add to the
  ```
<div class="ng-input">
      <input role="combobox" type="text">
   </div>
```

https://stackblitz.com/edit/angular-nbkvfs edit in this stackblitz link
how i can do it.. please help me..

**Comment by varnastadeus** [comment]
[inputAttrs] is used for HTML input attributes only, any directives won't be interpolated

**Comment by necati12** [comment]
> [inputAttrs] is used for HTML input attributes only, any directives won't be interpolated

Thank u for reply

But how i can do it? Have another way?

**Comment by varnastadeus** [comment]
you can try having directive based on special class and append that class to the ng-select's input
