### ISSUE TITLE
Request - Two new event methods

### ISSUE THREAD

**Issue by carlhussey** [ng-select/ng-select#149]
I am using the `multiple=true` attribute on my input and was looking for possibly having an extra two event triggers added.

The first would be `onAdd` method. The current `change` method exists but it returns the full object containing all of the values selected. I was looking or a way to just get an `$event` object for the item that was selected from the multiple selection list.

The second would be an `onRemove` method. Much like the first, when removing an item from a multi select, it would be nice to know which specific item was being removed, not having to look through the whole result object to find out the difference.

If there are any easier ways to accomplish these, let me know.

**Comment by anjmao** [comment]
@carlhussey Thanks for suggestion, that are indeed needed events, I will add them as soon as I can :)

**Comment by anjmao** [comment]
@carlhussey I released new version 0.11.0 with new events, add, remove and clear

**Comment by carlhussey** [comment]
Works great, thanks so much!
