### ISSUE TITLE
Make API

### ISSUE THREAD

**Issue by Romko775** [ng-select/ng-select#1492]
It would be great to have the following functionality as API:

- scrollToTop() // method that scrolls to top, etc. Like `ngselect.api.scrollToTop()`
- scrollToBottom() // method that scrolls to bottom by script
- scrollToEl(el || index) // method that scrolls to N element by script
- focusEl(el || index) // method that focus needed N element

**Comment by varnastadeus** [comment]
most of these methods are already public so all you need is to get ng-select's ref and call methods underneath there is no need for `api` like objects.
