### ISSUE TITLE
Need two line to display 

### ISSUE THREAD

**Issue by candorthor** [ng-select/ng-select#1493]
**Describe the bug**
I tried to create the options value in two lines. 
Say first line consists of car name , second line consists of car price.
code is below.
But only the Car name is visible in the options. Price is not visible. (i.e only first line is visible). But I wanted to make both the lines visible. Screenshot is attached.

```
<ng-select [items]="carData"
                               bindLabel="name"
                               bindValue="index"
                               placeholder="Select Car"
                               name="item">
                        <ng-template ng-header-tmp>
                            Header Text
                        </ng-template>
                        <ng-template ng-option-tmp let-item="item">
                            <div><p>{{item.name}}</p>
                            <span>{{item.price}}</span></div>
                        </ng-template>
                    </ng-select>
```
					
					
					
					```
carData = [
        {index: '1', name: 'Audi', price: '$60000' },
        {index: '2', name: 'BMW', price: '$95000'},
        {index: '2', name: 'Jaguar', price: '$75000'},
        {index: '4', name: 'Chevrolet', price: '$50000'},
        {index: '5', name: 'Ferrari', price: '$80000'},
        {index: '6', name: 'Ford', price: '$89000'},
    ];
```

**Screenshots**

![image](https://user-images.githubusercontent.com/49184671/73334142-e5b8b500-4291-11ea-83d9-606bd58e96bc.png)

**Comment by Komock** [comment]
@candorthor Hi, you should use `ng-option-tmp`.
[https://stackblitz.com/edit/angular-2r6rgd?file=src%2Ftemplate-label-example.component.html](https://stackblitz.com/edit/angular-2r6rgd?file=src%2Ftemplate-label-example.component.html)

**Comment by candorthor** [comment]
@Komock 

Thanks a lot for the help. It helped me.
And also I had adjusted the line-height inorder to display 2 lines.

Thank you
