### ISSUE TITLE
Not displaying selected options

### ISSUE THREAD

**Issue by BIINBELLLO** [ng-select/ng-select#1495]
I think there are currently no API for setting the input not to display any selected item. For instance, I have a multi select dropdown, I want to be able to select items without them displaying on the input with that x button, but display somewhere else on the page. I am able to implement showing the selected options on another part of the page, but the input fields is still filled with selected items which can be very unpleasant.

Let me know if any exists though. I have scouted your documentation and couldn't find any.

See below image for better understanding
![ngSelectPackageIssueRaised](https://user-images.githubusercontent.com/22405338/73545448-a7f79000-443b-11ea-9191-785b041abc3a.jpg)

On the image above, I want to be able to disable seeing the selected options on the input and have it displayed on the card below the input.

**Comment by Komock** [comment]
@BIINBELLLO I don't think it's an often case. And you can use CSS to hide these items

**Comment by varnastadeus** [comment]
you can use empty 
```html
<ng-template ng-multi-label-tmp let-items="items" let-clear="clear">
</ng-template>
```
