### ISSUE TITLE
freeze when having an array with many items in it

### ISSUE THREAD

**Issue by MetaiR** [ng-select/ng-select#1496]
**Describe the bug**
I have a system which shows some flights in it and each one of them, has a source and target airport; so I have a select element for source and one have for target for each one
the airports array's length is 8k
so when I use this array for the [items] property, my web application become very slow and sometime it is freezing specialy when I open the select element to search in options.
I tried to use virtual scroll but there were 2 problems:
1, because all of the airports weren't loaded, the [(ngModel)] didn't select the default option correctly
2, again because all of the airports weren't loaded, the search is not working correctly too

so what should I do? is it a bug or I am missing something?

**Comment by varnastadeus** [comment]
use [virtualScroll]
