### ISSUE TITLE
Transcluded for ng-template not working

### ISSUE THREAD

**Issue by MacGyver27** [ng-select/ng-select#1497]
Hello,
Trying to implement trancluded for the template but it is ignored.. That component is a wrapper for reactive forms and this approach works for other type of inputs.. Any feedback will be appreciated. Thanks

Angular7/ng-select^2.20.5

[From:](https://stackblitz.com/run?file=src/template-label-example.component.html)
```html
<ng-select [items]="cities" [(ngModel)]="selectedCity" bindLabel="name" bindValue="name">
    <ng-template ng-label-tmp let-item="item">
        <img height="15" width="15" [src]="item.avatar"/>
        {{item.name}}
    </ng-template>
</ng-select>
```

To:
```html
/// parent using custom component and passing ng-template
<ngdc-form-item [form]="form" [item]="item('city')">
    <ng-template ng-label-tmp let-item="item">
        <img height="15" width="15" [src]="item.avatar"/>
        {{item.name}} [{{item.id}}]
    </ng-template>
</ngdc-form-item>

/// component template
<ng-container>
    <ng-select
        [loading]="item.ctrl.dropdownOptions.isLoading"
        [items]="item.ctrl.dropdownOptions.list"
        [bindLabel]="item.ctrl.dropdownOptions.text"
        [bindValue]="item.ctrl.dropdownOptions.value"
        [multiple]="item.ctrl.dropdownOptions.multiple"
        [placeholder]="item.ctrl.placeholder"
        [maxSelectedItems]="item.ctrl.dropdownOptions.maxSelectedItems"
        [formControlName]="item.field"
        [(ngModel)]="form.value[item.field]"
    >
        <ng-content></ng-content>
    </ng-select>
</ng-container>
```

**Comment by Komock** [comment]
@MacGyver27 Hi, you can do it with `<ng-template *ngTemplateOutlet>`.

Like in our ng-select wrapper:
[https://github.com/evotor/Evo-UI-Kit/blob/master/projects/evo-ui-kit/src/lib/components/evo-autocomplete/components/evo-autocomplete.component.html#L53](https://github.com/evotor/Evo-UI-Kit/blob/master/projects/evo-ui-kit/src/lib/components/evo-autocomplete/components/evo-autocomplete.component.html#L53)

**Comment by MacGyver27** [comment]
@Komock Sorry I dont follow.. I dont see you using `<ng-content></ng-content>` for transcluding the template.. Would you please show me on my example what you mean? Thanks..

**Comment by Komock** [comment]
@MacGyver27 To pass template down you don't need `<ng-content>` use  `<ng-template *ngTemplateOutlet>` instead.

```
// Parent component template
<ngdc-form-item [form]="form" [item]="item('city')">
    <ng-template #labelTemp let-item="item">
        <img height="15" width="15" [src]="item.avatar"/>
        {{item.name}} [{{item.id}}]
    </ng-template>
</ngdc-form-item>
```

```
// ngdc-form-item component
@ContentChild('labelTemp') labelTemp: TemplateRef<any>;
```

```
// ngdc-form-item template
<ng-select>
  <!-- Selected Item Template -->
  <ng-template *ngIf="labelTemp" ng-label-tmp let-item="item">
    <ng-template *ngTemplateOutlet="labelTemp; context: { item: item }"></ng-template>
  </ng-template>
</ng-select>
```

**Comment by MacGyver27** [comment]
Thanks for your patience with me! I got it now and works this way.

**Comment by MacGyver27** [comment]
BTW worth mentioning here, that having `<ng-select>` within a component taking advantage of `<ng-content>` breaks the transclusion from the parent.. Somewhere at the begining of the `ngdc-form-item` template I had `<ng-template></ng-template>` and it stopped working.. when I removed ng-select from the view (completely unrelated block) it worked again.. anybody understanding the reason behind?

**Comment by ap-greenfly** [comment]
@Komock thanks for providing your example, this was exactly what I needed. The only gotcha for me though, was I was unable to use `*ngIf` on the parent `<ng-template>`, but was able to get it working using `<ng-container>`. Angular would throw a compile error. I'm not sure why exactly since ng-select uses this same technique to output the custom templates. Here was my final code snippet:
```
<ng-select>
    <ng-container *ngIf="optionTmp">
        <ng-template ng-option-tmp let-item="item" let-index="index" let-searchTerm="searchTerm">
            <ng-template *ngTemplateOutlet="optionTmp; context: { item: item, index: index, searchTerm: searchTerm }"></ng-template>
        </ng-template>
    </ng-container>
</ng-select>
```
