### ISSUE TITLE
Angular 9 Support

### ISSUE THREAD

**Issue by RomanHubyak** [ng-select/ng-select#1499]
npm WARN @ng-select/ng-select@3.7.2 requires a peer of @angular/common@>=8.0.0 <9.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by timrasche** [comment]
+1

**Comment by datasage** [comment]
It may be a matter of updating the package constraints. My quick tests show that it works just fine.

**Comment by varnastadeus** [comment]
have anyone done full test to see if everything works as expected?

**Comment by pickaneym** [comment]
would be awesome to have the v9 support for this awesome lib! <3

**Comment by timrasche** [comment]
its aleady done. v9 working. issue can be closed

**Comment by leon-marzahn** [comment]
> its aleady done. v9 working. issue can be closed

I don't think so

```
"@angular/common": ">=8.0.0 <9.0.0",
"@angular/core": ">=8.0.0 <9.0.0",
"@angular/forms": ">=8.0.0 <9.0.0"
```

**Comment by timrasche** [comment]
> > its aleady done. v9 working. issue can be closed
> 
> I don't think so
> 
> ```
> "@angular/common": ">=8.0.0 <9.0.0",
> "@angular/core": ">=8.0.0 <9.0.0",
> "@angular/forms": ">=8.0.0 <9.0.0"
> ```

Only versions needs to be updated. Library works as expected.

**Comment by andrejm7** [comment]
update please

npm WARN @ng-select/ng-select@3.7.2 requires a peer of @angular/common@>=8.0.0 <9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ng-select/ng-select@3.7.2 requires a peer of @angular/core@>=8.0.0 <9.0.0 but none is installed. You must install peer dependencies 
yourself.
npm WARN @ng-select/ng-select@3.7.2 requires a peer of @angular/forms@>=8.0.0 <9.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by leon-marzahn** [comment]
> > > its aleady done. v9 working. issue can be closed
> > 
> > 
> > I don't think so
> > ```
> > "@angular/common": ">=8.0.0 <9.0.0",
> > "@angular/core": ">=8.0.0 <9.0.0",
> > "@angular/forms": ">=8.0.0 <9.0.0"
> > ```
> 
> Only versions needs to be updated. Library works as expected.

So why does that make this issue closable again?

**Comment by andzejsw** [comment]
> update please
> 
> npm WARN @ng-select/ng-select@3.7.2 requires a peer of @angular/common@>=8.0.0 <9.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN @ng-select/ng-select@3.7.2 requires a peer of @angular/core@>=8.0.0 <9.0.0 but none is installed. You must install peer dependencies
> yourself.
> npm WARN @ng-select/ng-select@3.7.2 requires a peer of @angular/forms@>=8.0.0 <9.0.0 but none is installed. You must install peer dependencies yourself.

So your suggestion is to downgrade project from Angular 9 to 8 because only of this plugin!? LOL...
Issue can't be closed and isn't done till it is fixed and fix is in production! And project downgrade is never solution!!!

**Comment by leon-marzahn** [comment]
> > update please
> > npm WARN @ng-select/ng-select@3.7.2 requires a peer of @angular/common@>=8.0.0 <9.0.0 but none is installed. You must install peer dependencies yourself.
> > npm WARN @ng-select/ng-select@3.7.2 requires a peer of @angular/core@>=8.0.0 <9.0.0 but none is installed. You must install peer dependencies
> > yourself.
> > npm WARN @ng-select/ng-select@3.7.2 requires a peer of @angular/forms@>=8.0.0 <9.0.0 but none is installed. You must install peer dependencies yourself.
> 
> So your suggestion is to downgrade project from Angular 9 to 8 because only of this plugin!? LOL...
> Issue can't be closed and isn't done till it is fixed and fix is in production! And project downgrade is never solution!!!

I don't even really know what this means. He just showed that he doesn't have angular installed at all 😆

**Comment by timrasche** [comment]
wtf are you talking about? are you sure that you know what is an peer dependency? this log output doesn't say they hasn't installed angular by the way

@andzejsw He never said he wanted to downgrade his project

**Comment by romanryasne2** [comment]
It means he installed Angular 9. Since this library needs peers of diferrent version npm generates the warning.

**Comment by leon-marzahn** [comment]
> wtf are you talking about? are you sure that you know what is an peer dependency? this log output doesn't say they hasn't installed angular by the way
> 
> @andzejsw He never said he wanted to downgrade his project

@ng-select/ng-select@3.7.2 requires a peer of @angular/forms@>=8.0.0 <9.0.0 **but none is installed**. I don't know about you, but that sounds like he doesn't have angular installed

**Comment by timrasche** [comment]
> > wtf are you talking about? are you sure that you know what is an peer dependency? this log output doesn't say they hasn't installed angular by the way
> > @andzejsw He never said he wanted to downgrade his project
> 
> @ng-select/ng-select@3.7.2 requires a peer of @angular/forms@>=8.0.0 <9.0.0 **but none is installed**. I don't know about you, but that sounds like he doesn't have angular installed

thats totally wrong, please read what is a peer dependency...

**Comment by andzejsw** [comment]
> wtf are you talking about? are you sure that you know what is an peer dependency? this log output doesn't say they hasn't installed angular by the way
> 
> @andzejsw He never said he wanted to downgrade his project

My mistake. Was fast looking and saw that he suggested to install. That was my mistake. At least i didn't say that issue is fixed and should be closed, while it is obviously not.

**Comment by andzejsw** [comment]
> > > wtf are you talking about? are you sure that you know what is an peer dependency? this log output doesn't say they hasn't installed angular by the way
> > > @andzejsw He never said he wanted to downgrade his project
> > 
> > 
> > @ng-select/ng-select@3.7.2 requires a peer of @angular/forms@>=8.0.0 <9.0.0 **but none is installed**. I don't know about you, but that sounds like he doesn't have angular installed
> 
> thats totally wrong, please read what is a peer dependency...

And you please learn what is fixed issue.

**Comment by leon-marzahn** [comment]
> > > wtf are you talking about? are you sure that you know what is an peer dependency? this log output doesn't say they hasn't installed angular by the way
> > > @andzejsw He never said he wanted to downgrade his project
> > 
> > 
> > @ng-select/ng-select@3.7.2 requires a peer of @angular/forms@>=8.0.0 <9.0.0 **but none is installed**. I don't know about you, but that sounds like he doesn't have angular installed
> 
> thats totally wrong, please read what is a peer dependency...

Fair enough, forgot the error message was a bit wonky
