### ISSUE TITLE
Unable to apply input attributes on v2.x

### ISSUE THREAD

**Issue by peasandwell** [ng-select/ng-select#1500]
The API for this module details the [inputAttrs] input, allowing developers to apply attributes to the rendered `input`. This is particularly important as it would allow the addition of `aria` attributes to the input (such as `aria-required`, `aria-describedby`, `aria-invalid` etc.)

This works fine in v3.x, however as the version of Angular I'm using on this project is below 8, I am forced to use v2.x which does not seem to support this.

When using I get the error:

```
Error in /turbo_modules/@angular/compiler@6.1.10/bundles/compiler.umd.js (1098:21)
Template parse errors:
Can't bind to 'inputAttrs' since it isn't a known property of 'ng-select'.
1. If 'inputAttrs' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
bindLabel="name"
bindValue="id"
[ERROR ->][inputAttrs]="{'required': true}"
[(ngModel)]="selectedPlanetId"></ng-select>"): ng:///AppModule/AppComponent.html@5:2
```

**Example**
https://stackblitz.com/edit/angular-uzugat

** Additional information**
I have raised this as a bug as it's listed as an option in the docs, however it does not seem to be working, and I'm not sure if this is intentional or not.

**Comment by varnastadeus** [comment]
we don't backport new features to older versions

**Comment by peasandwell** [comment]
@varnastadeus I appreciate the response however I feel that the documentation should be updated to clarify what is and isn't available for different versions to avoid further confusion.
