### ISSUE TITLE
ng-select: unable to select multiple items having same label but different object

### ISSUE THREAD

**Issue by gauravd1** [ng-select/ng-select#1502]
**Describe the bug**
I'm trying to patch multiple selected items in ng-select drop down. I have not specified any bindValue, so the items should be bind by object (as specified at https://www.npmjs.com/package/@ng-select/ng-select)

But while trying to do this the items do not get selected depending on the object but by the label displayed. Also only the first label gets selected.

**Reproducbile example**
Have example running here : https://stackblitz.com/edit/angular-szel64?file=src%2Fapp%2Fapp.component.ts

**To Reproduce** 
Using reactive form, create a ng-select drop down.
create a list of objects for the drop down.
This list should have unique objects, but some having same label that needs to be displayed.
Do not use bindValue (so the item will be bind to object by default).
Use bindLabel to display the item label with some property. 
Now patch the value (from .ts) of this objects to get them selected.
You will see that only the first object gets selected, that also on the basis of label.

Example:
app.component.html

```
<form [formGroup]="group">
	<div class="form-group" formGroupName="school">
		<ng-select labelForId="school" placeholder="Select school" [items]="schools" formControlName="code"
			bindLabel="displayLabel" multiple="true" groupBy="city">
		</ng-select>
	</div>
</form>
```

app.component.ts

```
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, FormControl, Validators } from '@angular/forms';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  group: FormGroup;
  schools = [];
  constructor(private fb: FormBuilder) { }

  ngOnInit() {
    this.initSchools();
    const formModel = {
      school: new FormGroup({
        code: new FormControl(null, Validators.required)
      })
    }
    this.group = this.fb.group(formModel);
    this.group.patchValue({
      school: {
        code:
          [
            {
              schoolId: 'SC003',
              displayLabel: 'Test-3 school',
              city: "City1"
            },
            {
              schoolId: 'SC005',
              displayLabel: 'Test-3 school',
              city: "City5"
            }
          ]
      }
    });
  }

  initSchools() {
    this.schools.push(
      {
        schoolId: 'SC001',
        displayLabel: 'Test-1 school',
        city: "City1"
      },
      {
        schoolId: 'SC002',
        displayLabel: 'Test-2 school',
        city: "City2"
      },
      {
        schoolId: 'SC003',
        displayLabel: 'Test-3 school',
        city: "City3"
      },
      {
        schoolId: 'SC004',
        displayLabel: 'Test-4 school',
        city: "City4"
      },
      {
        schoolId: 'SC005',
        displayLabel: 'Test-3 school',
        city: "City5"
      }
    );
  }
}

```

**Expected behavior**
Expecting that when the value for bindValue is not provided then the items should get bind by object. Even when the object has bindLabel and the value for this bindLabel can be same, but the objects are unique. 

**Screenshots**
![image](https://user-images.githubusercontent.com/56404577/74305044-c25b3300-4d84-11ea-9846-70a092817fdc.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome

**Additional context**
1. am i doing it the right way. Is the ways i am binding the value or label correct.
2. If the values had to be bind by object why all unique objects are not getting selected.

Any other suggestions that may be helpful.

**Comment by varnastadeus** [comment]
by default ng-select tries to find item by label if anything else is provided, you need to provide `compareWith` function to describe on which properties items should be matched.

**Comment by gauravd1** [comment]
@varnastadeus Thanks for pointing that out. This is useful. Now i can bind objects and it gets selected depending on the function provided with compareWith option.

Below are my changes in case anyone lands into same problem

app.component.html
```
<form [formGroup]="group">
	<div class="form-group" formGroupName="school">
		<ng-select labelForId="school" placeholder="Select school" [items]="schools" formControlName="code"
			bindLabel="displayLabel" multiple="true" groupBy="city"
      [compareWith]="compareFunction">
		</ng-select>
	</div>
</form>
```
app.component.ts

```
...
  compareFunction(item, selected) {
// any logic to compare the objects and return true or false
    return item.schoolId === selected.schoolId
  }
...
```
