### ISSUE TITLE
Remove clear all - cross icon from single selection dropdown

### ISSUE THREAD

**Issue by todarmal17** [ng-select/ng-select#1503]
I need to remove the cross icon from single selection dropdown.

**Version**
angular2-multiselect-dropdown:  ^4.6.3

**Expected Behaviour**
A clear all - cross icon can be removed from the dropdown.

**Similar bug Reported - #710**
The answers here are not applicable anymore.

**Screenshot** 

<img width="213" alt="Screenshot 2020-02-13 at 11 17 53 AM" src="https://user-images.githubusercontent.com/24956193/74405528-4a0f7300-4e53-11ea-8e95-b94342180d99.png">

**Comment by varnastadeus** [comment]
wrong repo `angular2-multiselect-dropdown: ^4.6.3`
