### ISSUE TITLE
When selecting the item it triggers a new search

### ISSUE THREAD

**Issue by elvispdosreis** [ng-select/ng-select#1504]
**Describe the bug**
I am having an undesirable behavior, for research, I am doing a remote search, however when selecting the item, ng-select triggers a new remote search event, with term = null.

I would like that when selecting an item from the list it does not send an event for research.

```
<ng-select [items]="cidadePrestacao$ | async" [hideSelected]="true" bindLabel="nome"
                                       formControlName="prestacao"
                                       [loading]="cidadePrestacaoLoading"
                                       [typeahead]="cidadePrestacaoInput$"
                                       typeToSearchText="Digite para pesquisar"
                                       (change)="onChangeCidadePrestacao($event)"
                            >
```

````
    ngOnInit() {
        this.loadCidade();
    }

    public loadCidade() {
        const that = this;
        that.cidadePrestacao$ = concat(
            of([]), // default items
            this.cidadePrestacaoInput$.pipe(
                debounceTime(500),
                distinctUntilChanged(),
                tap(() => this.cidadePrestacaoLoading = true),
                switchMap(term => this.dataService.getCidade(term).pipe(
                    catchError(() => of([])), // empty list on error
                    tap(() => this.cidadePrestacaoLoading = false)
                ))
            )
        );
    }
````

**Comment by jbuiquan** [comment]
Hello,

I have the same problem here, I was looking to understand why would the associated typeahead emit `null` as it is typed as `Subject<string>`.
I understand the logic to clear the search when selecting the element but why is the subject type not including `null` ?
This typing is misleading and I see that it hasn't been fix in latest versions. 
The private `_changeSearch` function accept a string and just above in the `_clearSearch` we pass `null`..
https://github.com/ng-select/ng-select/blob/a20e5fbf36017919debc71065546ed592f28c2e9/src/ng-select/lib/ng-select.component.ts#L1035
Any reasons ?
