### ISSUE TITLE
Placeholder Template

### ISSUE THREAD

**Issue by tiagomsmagalhaes** [ng-select/ng-select#1505]
**Describe the solution you'd like**
Customize the placeholder as we would do for selected item

**Comment by Komock** [comment]
@tiagomsmagalhaes  Hi, you need a custom template for the placeholder? 🤔 
Could you explain where you need this feature? 
Any examples?

**Comment by tiagomsmagalhaes** [comment]
In the same fashion I can define the label template, The placeholder could be customizable to give a sense of what information would have if I select the dropdown and select an Item.

I have a dropdown where I would want to have a name of an animal and below that the scientific name below (or after).


I have tried to do it on my own and make a PR, but I think i'm halfway through

**Comment by tiagomsmagalhaes** [comment]
Hi @Komock. Meanwhile I have managed to get a working example on a [branch](https://github.com/tiagomsmagalhaes/ng-select/tree/ng-placeholder-tmp). I need to add a test and before creating a PR

**Comment by Komock** [comment]
> Hi @Komock. Meanwhile I have managed to get a working example on a [branch](https://github.com/tiagomsmagalhaes/ng-select/tree/ng-placeholder-tmp). I need to add a test and before creating a PR

I think it makes sense. 
You should add a test [here](https://github.com/ng-select/ng-select/blob/master/src/ng-select/lib/ng-select.component.spec.ts) and submit PR

**Comment by tiagomsmagalhaes** [comment]
The current test suite is crashing apparently as detailed on #1513. Should I wait on that fix?

```
❯ yarn run test
yarn run v1.12.3
$ ng test ng-select --code-coverage
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
 40% building 3/3 modules 0 active19 02 2020 20:34:33.626:INFO [karma-server]: Karma v4.4.1 server started at http://0.0.0.0:9876/
19 02 2020 20:34:33.628:INFO [launcher]: Launching browsers Chrome with concurrency unlimited
19 02 2020 20:34:33.631:INFO [launcher]: Starting browser Chrome

ERROR in lib/ng-select.component.spec.ts:2999:77 - error TS2554: Expected 0 arguments, but got 1.

2999             expect(fixture.componentInstance.onSearch).toHaveBeenCalledWith({ term: 'term', items: [] });
                                                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~
lib/ng-select.component.spec.ts:3039:77 - error TS2345: Argument of type 'string | Object' is not assignable to parameter of type 'Event | AsymmetricMatcher<any>'.
  Type 'string' is not assignable to type 'Event | AsymmetricMatcher<any>'.

3039             expect(fixture.componentInstance.onChange).toHaveBeenCalledWith(select.selectedItems[0].value);
                                                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
lib/ng-select.component.spec.ts:3076:74 - error TS2554: Expected 0 arguments, but got 1.

3076             expect(fixture.componentInstance.onAdd).toHaveBeenCalledWith(fixture.componentInstance.cities[0]);
                                                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
lib/ng-select.component.spec.ts:3111:77 - error TS2554: Expected 0 arguments, but got 1.

3111             expect(fixture.componentInstance.onRemove).toHaveBeenCalledWith(fixture.componentInstance.cities[0]);
                                                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Komock** [comment]
> The current test suite is crashing apparently as detailed on #1513. Should I wait on that fix?
> 
> ```
> ❯ yarn run test
> yarn run v1.12.3
> $ ng test ng-select --code-coverage
> Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
>  40% building 3/3 modules 0 active19 02 2020 20:34:33.626:INFO [karma-server]: Karma v4.4.1 server started at http://0.0.0.0:9876/
> 19 02 2020 20:34:33.628:INFO [launcher]: Launching browsers Chrome with concurrency unlimited
> 19 02 2020 20:34:33.631:INFO [launcher]: Starting browser Chrome
> 
> ERROR in lib/ng-select.component.spec.ts:2999:77 - error TS2554: Expected 0 arguments, but got 1.
> 
> 2999             expect(fixture.componentInstance.onSearch).toHaveBeenCalledWith({ term: 'term', items: [] });
>                                                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~
> lib/ng-select.component.spec.ts:3039:77 - error TS2345: Argument of type 'string | Object' is not assignable to parameter of type 'Event | AsymmetricMatcher<any>'.
>   Type 'string' is not assignable to type 'Event | AsymmetricMatcher<any>'.
> 
> 3039             expect(fixture.componentInstance.onChange).toHaveBeenCalledWith(select.selectedItems[0].value);
>                                                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> lib/ng-select.component.spec.ts:3076:74 - error TS2554: Expected 0 arguments, but got 1.
> 
> 3076             expect(fixture.componentInstance.onAdd).toHaveBeenCalledWith(fixture.componentInstance.cities[0]);
>                                                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> lib/ng-select.component.spec.ts:3111:77 - error TS2554: Expected 0 arguments, but got 1.
> 
> 3111             expect(fixture.componentInstance.onRemove).toHaveBeenCalledWith(fixture.componentInstance.cities[0]);
>                                                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ```

I think you can skip it and check out your test with `fdescribe`
