### ISSUE TITLE
NgModel not binding selected value in angular 8 with ng-select 3.7.1

### ISSUE THREAD

**Issue by Sonal824** [ng-select/ng-select#1507]
**Describe the bug**
I am using Ng-select in my project in which i am setting options data using Directive, it was working fine till now with Angular version 7.0.4 and Ng-Select Version 2.12.1. 
After upgrading my project to Angular Version 8.2.14 along with Ng-Select Version 3.7.1, selected items are not rendering. After further analysis i found that it works fine if i initialize **[items]** property as blank array in ng-select element. but in your [official document](https://github.com/ng-select/ng-select#api) it is mentioned under API section that by default code initialize **items** property as [] array. so why we need to initialize again to make it work ?

**Reproducbile example**
https://stackblitz.com/edit/ng-select-update-from-directive-u5yyea

**To Reproduce** 
Steps to reproduce the behavior (if example is not provided):
1. Go to https://stackblitz.com/edit/ng-select-update-from-directive-u5yyea
2. Change Ng-select version to 2.12 along with Angular version 7.0.4 it will work fine 
3. After upgrading to Angular 8.2.14 with Version 3.7.1 same code wont work, selected item wont render until you specify [items] property.

**Expected behavior**
it should work without initializing **[items]** property, as it was working in earlier version of Ng-Select.

**Comment by varnastadeus** [comment]
I am not sure when it changed, but ng-select is intended to be used with either `[items]` or `<ng-option></ng-option>`

**Comment by Sonal824** [comment]
@varnastadeus 
just curious..!!
so its must to initialize **[items]** property in an element as blank array as per latest version code?

**Comment by varnastadeus** [comment]
yes, you need to set items explicitly through API in on the ways mentioned above

**Comment by Ramarjunan** [comment]
Hi i need some clarifications.

If i use multiple number of dropdown in one page means.

How can i initialize items
