### ISSUE TITLE
Searching with Typeahead is malfunctioning in 2.20.5

### ISSUE THREAD

**Issue by nealyip** [ng-select/ng-select#1508]
My project was built with Angular7 with @ng-select/ng-select 2.13.0 last year.

Recently I've updated the ng-select version to the 2.20.5 but the searching function no longer worked as expected.
After an investigation, I found the latest version that worked properly was 2.19.0

In the below links, I reproduced the issues with 2.19.0 and 2.20.5 respectively.
In 2.19.0, the lazy loading and searching work perfectly. By typing Cisco/Oil or other possible keywords, the list can be correctly filtered and displayed.

In 2.20.5, however, the fetchMore method didn't seem to be triggered by (scollToEnd) for the second times, as a result, the list stops at 100 items. The search function is not working either, for example, I type Cisco, it shows 1 instead of Cisco Systems, Inc.

https://stackblitz.com/edit/ng-select2190?file=src%2Fapp%2Fapp.component.html
https://stackblitz.com/edit/ng-select2205?file=src%2Fapp%2Fapp.component.html

Thanks

**Comment by varnastadeus** [comment]
you should use latest version, older version are not really supported
