### ISSUE TITLE
Multiselect binding

### ISSUE THREAD

**Issue by dima12qw** [ng-select/ng-select#151]
Please fill below information if issuing a bug report. 
### Expected behaviour
Multiselect binding. So I have two multiselect in this way: 
<ng-select [items]="items" [(ngModel)]="selectedItems"></ng-select>
<ng-select [items]="selectedItems" [(ngModel)]="selectedItems2"></ng-select>

So..the second multiselect have some issues. When I select in the first, the items in second not binding, or they not appears all of them.And if appears, I have to double-click on them to select in second. How to resolve this?

### More Info
ng-select version: [0.11.0]

browser: [INSERT BROWSER INFO HERE]

reproducible in demo page: [YES/NO]

**Comment by anjmao** [comment]
@dima12qw This happens because we use OnPush change detection. I created plunkr example for your case https://plnkr.co/edit/AJD0zh?p=preview

You need to change selectedItems array reference for second select so angular can trigger change detection.

**Comment by dima12qw** [comment]
ok..thanks..but  it's still need to double-click in the 2nd multiselect

**Comment by anjmao** [comment]
@dima12qw I updated my example. See plunkr https://plnkr.co/edit/AJD0zh?p=preview
 
You need to copy object and set each item.selected = false. 

```ts
export class CitiesPageComponent {
    cities: NgOption[] = [
        {id: 1, name: 'Vilnius'},
        {id: 2, name: 'Kaunas'},
        {id: 3, name: 'Pabradė'}
    ];
    cities2 = [];
    selectedCities: any;
    selectedCities2: any;
    
    onFirstSelectChange() {
      this.cities2 = this.selectedCities.map(x => {
        const item = Object.assign({}, x);
        item.selected = false;
        return item;
      });
    }
}
```
