### ISSUE TITLE
Hide place holder when user starts entering text

### ISSUE THREAD

**Issue by pavankjadda** [ng-select/ng-select#1510]
**Is your feature request related to a problem? Please describe.**
When the user starts entering text, please hide the place holder instead of showing it on the top. This feels redundant since the user is already entering text and never goes away even after he moves away to the new field. 

**Describe the solution you'd like**
Please give use the input option to hide it as soon as the user starts entering the text

**Describe alternatives you've considered**
when `mat-autocomplete` used with `mat-placeholder`, the placeholder can be hidden using the input value from `mat-autocomplete`

**Comment by varnastadeus** [comment]
this is based on material theme design, you can hide it using CSS if for some reason you don't want to follow their design.

**Comment by pavankjadda** [comment]
@varnastadeus Since the placeholder div generated dynamically, Do you know how to hide it using CSS?

**Comment by varnastadeus** [comment]
placeholder div has static CSS selectors, use those
