### ISSUE TITLE
Add the ability to show ng-select dropdown and label on same row

### ISSUE THREAD

**Issue by pavankjadda** [ng-select/ng-select#1511]
**Is your feature request related to a problem? Please describe.**
Right now the Label for ng-select and the actual dropdown appear on 2 different lines. Please add the ability to show ng-select dropdown and label on the same line

**Describe the solution you'd like**
Please add the ability to show ng-select dropdown and label on the same line

**Describe alternatives you've considered**
I tried to use the bootstrap grid structure, col-3 for label and col-9 for ng-select, but couldn't get it working

**Comment by pavankjadda** [comment]
Update: I was able to achieve using this bootstrap grid structure, but it would be nice If I can give it as input to ng-select

```
  <div class=" form-inline col-xs-12  col-sm-12 col-md-12 col-lg-12 col-xl-12">
            <div class="col-xs-12 col-sm-12 col-md-2 col-lg-2 col-xl-2">
              <label class="col-form-label">Employee:</label>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3 col-xl-3">
              <ng-select [items]="allEmployees"
                         style="max-width: 250px;"
                         bindLabel="number"
                         autofocus
                         bindValue="number"
                         appearance="outline"
                         (change)="fetchEmployeeInformation($event)">
              </ng-select>
            </div>
</div>
```

**Comment by varnastadeus** [comment]
I think this issue is unrelated, ng-select is separate component and you should handle such stuff on your side.
