### ISSUE TITLE
Use a valid selector prefix instead of "ng" as it's not @angular scope library

### ISSUE THREAD

**Issue by ibenjelloun** [ng-select/ng-select#1512]
`ng-select` selector for the select component is frustrating as the `ng` prefix should only be used in the @angular scope libraries.

I would suggest using another prefix, example : `adv-select` (advanced), `pow-select` (power)...

**Comment by varnastadeus** [comment]
`ng-select` was built long before angular... 
Also, you can wrap `ng-select` in your own component and call it `any-prefix-you-desire-select` ✌️

**Comment by ibenjelloun** [comment]
Never too late to improve :
`@angular/material` changed their prefix from `md` to `mat` in v2.0.0 https://github.com/angular/components/blob/master/CHANGELOG.md#deprecation-of-md-prefix

What does the `ng` prefix stands for in `ng-select` ?
What do you mean by :
> `ng-select` was built long before angular...

This is just a suggestion, I'm not willing to use `ng-select` in any project I'm working on.
Feel free to close it if you think that it's not relevant ^_^)

**Comment by varnastadeus** [comment]
I was just kidding :] 

In `ng-select` `ng` stands for `angular` which means  - this is not regular `<select>` component it is an advanced angular component which is built exactly with angular that's why I don't see any problem using `ng` prefix.
