### ISSUE TITLE
Ng-Options outside of ng-select scope

### ISSUE THREAD

**Issue by Dquaglio** [ng-select/ng-select#1514]
Hi, I created a dropdown menu that when the user click outside of it, it will close automatically. 
Inside of it I added the `ng-select` component, when the user click one of the `ng-options`, the menu closes since the options are not considered inside the main container that i keep track of with `@ViewChild`.
I think that this is not the right behaviour since I want that `ng-select` and it's children to be inside of the father scope.
Here is an example of the problem https://stackblitz.com/edit/angular-8m1ta5?file=src%2Fapp%2Fapp.component.ts

**Comment by varnastadeus** [comment]
ng-select is inside your container,  your condition fails since the dropdown panel is not kept inside DOM when control is closed. That's the design decision that won't be changed - you need to adjust your condition based on that.
