### ISSUE TITLE
Template to override both item and header.

### ISSUE THREAD

**Issue by pdrakos** [ng-select/ng-select#1516]
There is a need right now to display typeahead data in a datatable with sorting.  
Currently it is implemented creating 2 different tables one using the header template and one using the option. But this is just a workaround , since what we trully need is to use something like prime-ng table. 

I would love if there was a way to completely override both header and item with a custom template.

**Comment by varnastadeus** [comment]
you can already override header and item, or I got something wrong? 🤔

**Comment by pdrakos** [comment]
What I need is to create a data-grid with sorting , but if a draw it to the item template then it will be drawn once per item. If I do it in the header, then won't have the items.

**Comment by varnastadeus** [comment]
:hushed: ng-select is not intended to be used as data-grid

**Comment by pdrakos** [comment]
Indeed, but what I need is the data rendering when I use typeahead from ng-select to be in a grid format.
