### ISSUE TITLE
Ability to toggle the visibility of the dropdown arrow

### ISSUE THREAD

**Issue by TheSamsterZA** [ng-select/ng-select#1517]
**Is your feature request related to a problem? Please describe.**
I have a basic need to be able to show or hide the dropdown arrow programmatically.

**Describe the solution you'd like**
Similar to how the [clear 'x' in the input can be toggled off](https://github.com/ng-select/ng-select/blob/ae8a04051f4054258714f0bddff84199c5458491/src/ng-select/lib/ng-select.component.html#L59), I want to be able to toggle the arrow in the same way.

**Describe alternatives you've considered**
I have tried [setting CSS as described here](https://github.com/ng-select/ng-select/issues/544#issuecomment-389168319), but that does not seem to work. Alternatively, I also tried using `::ng-deep` but that didn't work either, and looks like it is [planned to be removed from Angular](https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep) in the future.

**Additional context**
N/A

**Comment by AndrewBogushevich** [comment]
css way works, but as soon as it requires to use `::ng-deep` It would be nice if we have an input for this.

**Comment by TheSamsterZA** [comment]
I have figured out how to apply my CSS to the `ng-select` in order to hide the dropdown arrow. I think it's pretty clean, so I thought I'd share:

**Component HTML:**
```html
<ng-select
  ...
  [class.hide-arrow]="hideArrow">
</ng-select>
```

**Component TS:**
```typescript
@Input('hide-arrow') hideArrow: boolean = false;
```

**Component CSS:**
```css
.hide-arrow {
  .ng-arrow-wrapper {
    display: none;
  }
}
```

I still think adding an `Input` on `ng-select` to show/hide the arrow is useful in and of itself, but if others think differently, I am happy to rescind my PR and close this issue.

**Comment by AndrewBogushevich** [comment]
In case this CSS class is part of library then it's ok. But in case of input when we use lib we have autocomplete and typechecking so it is safer
