### ISSUE TITLE
Search terms highlighted (improvement)

### ISSUE THREAD

**Issue by rgiosa** [ng-select/ng-select#152]
It would be interesting to have the option of the search result having the search terms highlighted.

_Finally a component that works! Thank you!_

**Comment by anjmao** [comment]
@rgiosa Thanks for suggestion. This is indeed a good feature to add to the list :)

**Comment by BenjaminLefevreGithub** [comment]
Would be nice to have this functionality!

**Comment by rgiosa** [comment]
Nice! Great work!
