### ISSUE TITLE
For multi selection mode, selected items with large labels are not been displayed correctly

### ISSUE THREAD

**Issue by thiagobitencourt** [ng-select/ng-select#1520]
**Describe the bug**
When using the multiple selection mode and select one or more items that have a large label, the text are being truncated at the limit of the component and the clear/loading/dropdown icon is not displayed.

**Reproducbile example**
In [this example](https://stackblitz.com/edit/angular-yibzzj) you will be able to see that happening.

**To Reproduce** 
In the example linked above:
1.On the "Select multiple elements" component
2. Select one or more items with a large label
3. Observe that the "clear" icon and the "dropdown" icon disapears

**Expected behavior**
I think it should limit the size of the label and add an ellipsis at the end to represents that the label was truncated, and the icons on the right should stay in the same place, just like the "single selection mode" does.

**Comment by thiagobitencourt** [comment]
I believe this is related to this situation with flex layout: https://css-tricks.com/flexbox-truncated-text/.
I tried to apply the proposed solution but with no success.

**Comment by weikaitps** [comment]
The following rewriting will work:

1.HTML: add id (ex: multi) in <ng-multiselect-dropdown> for using css selector
        <ng-multiselect-dropdown id="multi" [placeholder]="'Choose...'" [settings]="multiDropDownData.dropdownSettings"
          [data]="multiDropDownData.dropdownList" [(ngModel)]="multiDropDownData.selectedItem" >
        </ng-multiselect-dropdown>

2.CSS: using ::ng=deep + id (ex: #multi) selector with the others
::ng-deep {
    #multi .multiselect-dropdown .dropdown-btn .selected-item-container .selected-item {
        margin-bottom: 4px;
        max-width: 250px;  //key point!!!!!!!
    }
}
