### ISSUE TITLE
Change the order in which events are emitted

### ISSUE THREAD

**Issue by Michele-91** [ng-select/ng-select#1521]
I need to let the (remove) and (add) events fire/emit before the (change) event does. (change) gets fired any time an (add) or a (remove) happens, which limits the ways in which I can manipulate the data I need and separate concerns.
I would like to have the possibility to order the way at least these three events interact with each other, especially the order in which they are emitted.

Thank you.

**Comment by varnastadeus** [comment]
That's by design and I don't see any valid reason why this should be other way around for now.
