### ISSUE TITLE
Clearing custom tags from list

### ISSUE THREAD

**Issue by magoarcano** [ng-select/ng-select#1522]
**Is your feature request related to a problem? Please describe.**

In my form, a <ng-select> single-select component has an [addTag] attribute that is true/false depending on a value of other field. Let say the other fieldname is 'canTag'.

So when canTag is true, I can add a custom tag that is not in my list. If then I switch canTag=False, I cannot add a new tag , that's ok, but the thing is that I can still choose the previous added custom tag.

**Describe the solution you'd like**
The component should have a clearCustomTags() or resetCustomTags() method. So I can execute it when I detect canTag=False

**Describe alternatives you've considered**
If current behaviour is considered a bug, the component should automatically clear custom tags if [addTag] coerces to False, not showing them in the list.

**Comment by varnastadeus** [comment]
you need to mark your custom added tags with any way to be able to identify them and then just filter them out from items.
`items = item.filter(x => x.isTag == false)` and that's it. There is no need for any additional API's.
