### ISSUE TITLE
The searched keyword remains after selecting an item

### ISSUE THREAD

**Issue by rostamiani** [ng-select/ng-select#1523]
**Describe the bug**
When 'multiple' and 'closeOnSelect' are both true and there is a search term typed, the term is not removed after selecting one of items

**Reproducbile example**
https://stackblitz.com/edit/angular-un8gg4

**To Reproduce** 
Just type 'k' in the input and hit Enter. The 'k' word is remained but should be removed after selecting.

**Screenshots**
![image](https://user-images.githubusercontent.com/1157108/75155106-84ff8980-5724-11ea-8a95-90484284a544.png)

**Comment by varnastadeus** [comment]
this is the default behaviour when 'closeOnSelect' is false. set `[clearSearchOnAdd]=true`
