### ISSUE TITLE
Option panel containing actions

### ISSUE THREAD

**Issue by anbaran** [ng-select/ng-select#1524]
I'm using ng-select(3.7.2) with Angular 8 and I would like to be able to call actions within the options panel without selecting items and making the panel to close.

The reason for this is that I want to let users mark items favorite when clicking on action (panel should not close, no selecting items)

I a user clicks on the item instead then normal select behaviour should happen (selecting item, panel closed

Look at the stackblitz to see what I want to achive. https://stackblitz.com/edit/angular-6r89u6

Any hint would be appreciated :)

**Comment by varnastadeus** [comment]
your solution is `<a  (click)="$event.stopPropagation()" (click)="action()">(Mark Favorite)</a>`
