### ISSUE TITLE
Pagination / server filtering

### ISSUE THREAD

**Issue by bruenor41** [ng-select/ng-select#1526]
Hi people,

I use ng-select in several projects without issues, but now I am working against really many data. So I like to ask

1. Is possible turn on "next/forward" buttons for paging and bind on them custom sever loading logic?
2. is there method in which I can hook on filter typing and update data from server?

Looking at API I don't see related methods, maybe I only don't see them.
Many thanks

**Comment by varnastadeus** [comment]
You can add those buttons to the header or footer if you want, what you need to do is to replace `items` array with new page items that's all API you need. Also there is virtual scroll example which simulates new page fetch when reaching bottom of scroll.

**Comment by bruenor41** [comment]
Many thanks, and what about filtering when typing? For example i like to update items if I type 3 letters.

**Comment by varnastadeus** [comment]
check `Search and autocomplete` examples
