### ISSUE TITLE
Enable select all option

### ISSUE THREAD

**Issue by slavede** [ng-select/ng-select#1528]
**Is your feature request related to a problem? Please describe.**
Similiar as we have clear selection I would like to select all with one click

**Describe the solution you'd like**
Add one button near clear items for selecting all items

**Describe alternatives you've considered**
Where to add this select all, inside dropdown, or near clear all items

**Additional context**
I'm already preparing this solution, will soon provide PR

![image](https://user-images.githubusercontent.com/2838038/75263833-cb211f80-57ee-11ea-96eb-8de2e5d79809.png)

**Comment by varnastadeus** [comment]
there is an example in templates with that already. All you need is to set your `ngModel` with all the items you are displaying. There is no need for any additional API's.
`yourModelProperty = [...items];`

**Comment by slavede** [comment]
Oh I see...well, if that's the case, we don't need this one. I just though it would be nice feature to have out of the box. It also works in a way it selects only filtered items.  Your call...

**Comment by koreem** [comment]
> there is an example in templates with that already. All you need is to set your `ngModel` with all the items you are displaying. There is no need for any additional API's.
> `yourModel = [...items]`
> 
> <img alt="Screenshot 2020-03-02 at 17 21 31" width="757" src="https://user-images.githubusercontent.com/17824796/75689721-58122000-5caa-11ea-9d93-5095f7219ba8.png">

I tried this solution and I think this doesn't work together with the multi select checkbox example. When you select all, the checkboxes stay empty.

**Comment by varnastadeus** [comment]
`(search) | Fired while typing search term. Outputs search term with filtered items` you can use items from search event. I am closing this as the feature is already available.

**Comment by OT-YCLiao** [comment]
One issue is the custom buttons in the option list are not accessible by keyboard. It will jump out when press Tab key.
