### ISSUE TITLE
Allow to change Clear All button title

### ISSUE THREAD

**Issue by rgiosa** [ng-select/ng-select#153]
It would be nice to have the option to change Clear All button title.

**Comment by anjmao** [comment]
Thanks for reporting. I'm adding this as a bug because all texts in ng-select should be translatable.

**Comment by janstadt** [comment]
On the same topic, it might be worthwhile to be able to set the `x` as well. Our clients seem to not be aware of the x (or to hover over it for that matter) so it would be nice to do something like this:
![image](https://user-images.githubusercontent.com/1872087/42826065-2465f46e-89a9-11e8-9435-a511d1386b3f.png)
