### ISSUE TITLE
group by on object

### ISSUE THREAD

**Issue by sdns** [ng-select/ng-select#1541]
Hi, I am using ng-select to show and select my user's list and their teams.  I used `Grouped multi select with checkboxes` demo:
https://ng-select.github.io/ng-select#/multiselect-checkbox
then I have these options and I used `groupBy="team_name"`:
```
Team 1
  - User 1
  - User 2
Team 2
  - User 3
```
but some users can be in multiple teams. For example, `User 1` is both a member of `Team 1` and a member of `Team 2`. then team is an object.
What I can do?

**Comment by varnastadeus** [comment]
GroupBy can be function so you can group by anything you want
