### ISSUE TITLE
editableSearchTerm input is not available

### ISSUE THREAD

**Issue by HamzaMoiyadi** [ng-select/ng-select#1545]
**Describe the bug**
On adding [editableSearchTerm], compilation fails with `Can't bind to 'editableSearchTerm' since it isn't a known property of 'ng-select'.`

**Reproducbile example**
[Example](https://stackblitz.com) which reproduces described behaviour

**To Reproduce** 
Steps to reproduce the behavior (if example is not provided):

**Template**
```
<ng-select 
	class="flex-grow" 
	[searchable]="true" 
	[items]="options" 
	bindLabel="sub_division"
	bindValue="value"
	[placeholder]="msg"
	[searchFn]="customSearchFn" 
	[clearable]="false"
	[editableSearchTerm]="!locked" 
	[readonly]="locked"
	(change)="selectValue($event)"
	[(ngModel)]="value"
	>
	<ng-template ng-option-tmp let-item="item">
		{{item['sub_division']}} <br />
		<small>{{item['division']}}</small>
	</ng-template>
</ng-select>
```

**Expected behavior**
It's supposed to work as it's documented.

**Screenshots**
![Screenshot (1)](https://user-images.githubusercontent.com/17302799/76225583-be66e780-6242-11ea-8782-e86af5ba422c.png)

**Desktop**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 80

**Comment by varnastadeus** [comment]
you should use latest version
