### ISSUE TITLE
Cannot read property 'nativeElement' of undefined at NgDropdownPanelComponent (Angular 9)

### ISSUE THREAD

**Issue by anjildhamala** [ng-select/ng-select#1550]
**Describe the bug**
When I click on ng-select field to bring up the dropdown, I see this error.

Here's how my ng-select looks
```
<ng-select
                  [labelForId]="'state_' + itemIndex + '-' + stateIndex"
                  [name]="'state_' + itemIndex + '-' + stateIndex"
                  appendTo=".facility-management"
                  [items]="statesForCurrentItem(item.areaServed, stateIndex)"
                  bindLabel="stateProvinceName"
                  placeholder="Select a State"
                  [required]="item.levelOfCare && stateIndex === 0"
                  (change)="onStateChange(stateCounty);"
                  [clearable]="false"
                  [(ngModel)]="stateCounty.stateProvince">
</ng-select>
```

Upon debugging, I found that `scrollElementRef` in `calculateDimension` method is undefined.

```
 NgDropdownPanelComponent.prototype._calculateDimensions = /**
     * @param {?=} index
     * @return {?}
     */
    function (index) {
        if (index === void 0) { index = 0; }
        return this._virtualScrollService.calculateDimensions(this.items.length, index, this.scrollElementRef.nativeElement, this.contentElementRef.nativeElement);
    };

```
![file](https://user-images.githubusercontent.com/13681582/76338797-337c0080-62c7-11ea-80c9-b6d2e0e0adf5.png)

 - OS: OSX Catalina
 - Browser Chrome

My package.json

"dependencies": {
        "@agm/core": "~1.0.0-beta.5",
        "@angular/animations": "9.0.0",
        "@angular/common": "9.0.0",
        "@angular/compiler": "9.0.0",
        "@angular/core": "9.0.0",
        "@angular/forms": "9.0.0",
        "@angular/http": "~7.2.16",
        "@angular/platform-browser": "9.0.0",
        "@angular/platform-browser-dynamic": "9.0.0",
        "@angular/router": "9.0.0",
        "@ng-select/ng-select": "^3.7.3",
        "@ngrx/effects": "~8.2.0",
        "@ngrx/entity": "~8.2.0",
        "@ngrx/store": "~8.2.0",
        "core-js": "~3.2.0",
        "ngrx-store-freeze": "~0.2.4",
        "ngrx-store-logger": "~0.2.2",
        "ngx-cookie": "~4.1.1",
        "normalize.css": "~8.0.0",
        "provider-shared": "file:../shared/dist",
        "ramda": "~0.26.1",
        "rxjs": "~6.5.2",
        "zone.js": "~0.10.1"
    },
    "devDependencies": {
        "@angular-devkit/build-angular": "~0.900.1",
        "@angular/cli": "~9.0.1",
        "@angular/compiler-cli": "^9.0.0",
        "@angular/language-service": "^9.0.0",
        "@nguniversal/express-engine": "^9.0.0",
        "@types/express-serve-static-core": "^4.17.2",
        "@types/jasmine": "3.4.0",
        "@types/jasminewd2": "~2.0.3",
        "@types/node": "~12.7.1",
        "@types/ramda": "github:types/npm-ramda#dist",
        "@types/googlemaps": "^3.39.2",
        "@types/tween.js": "~17.2.0",
        "codelyzer": "~5.1.0",
        "concurrently": "~4.1.0",
        "jasmine-core": "3.4.0",
        "jasmine-spec-reporter": "~4.2.1",
        "karma": "~4.2.0",
        "karma-chrome-launcher": "~3.0.0",
        "karma-coverage-istanbul-reporter": "~2.1.0",
        "karma-jasmine": "~2.0.1",
        "karma-jasmine-html-reporter": "~1.4.0",
        "nodemon": "~1.19.1",
        "protractor": "~5.4.0",
        "ts-node": "~8.3.0",
        "tslint": "~5.18.0",
        "tslint-config-airbnb": "~5.11.1",
        "typescript": "3.7.5"
    }

**Comment by varnastadeus** [comment]
angular 9 is not supported yet but this could be useful for #1519
