### ISSUE TITLE
User should be able to perform some actions to the selected option (e.g. Delete...)

### ISSUE THREAD

**Issue by testfas** [ng-select/ng-select#1553]
**Problem:**
I want for e.g. to **_DELETE_** an item/option from the list directly from the drop-down menu

**Solution**
Should be something like the attached ⬇️picture⬇️  
(clickable icons to the right side, `onClick` they should maybe bring a confirmation dialog) 

![Inkeddelete location example_LI](https://user-images.githubusercontent.com/62105237/76529925-3f0c2a80-6473-11ea-8b32-3c9591546e22.jpg)

_alternatives:_
Swipe left to delete with animation

**Comment by varnastadeus** [comment]
that's totally doable with current control as custom templates are available, except swiping and animation

**Comment by testfas** [comment]
> that's totally doable with current control as custom templates are available, except swiping and animation

Thanks for your reply, can you please give me hints how to create an Icon and hang it to the right side? (is there an existing built-in code or I need to use CSS)

**Comment by varnastadeus** [comment]
Use css
