### ISSUE TITLE
Wrong <option> selected for multiple options having same name

### ISSUE THREAD

**Issue by houbi56** [ng-select/ng-select#1560]
**Describe the bug**
When setting the ngModel of a ng-select to an object and multiple items have the same value for property defined by bindLabel, the first option in the list matching the label is selected. 

**Reproducbile example**
https://stackblitz.com/edit/angular-jbqicg?file=src%2Fdata-source-backend-example.component.html

**Expected behavior**
Correct option is selected

**Comment by varnastadeus** [comment]
use `compareWith` for that case

**Comment by sburnicki** [comment]
Would be great if a hint can be added to the documentation.
The documented default value suggests that the whole object will be compared, as it says: `(a, b) => a === b` but it really seems to be `a === b || label(a) === label(b)`
