### ISSUE TITLE
Hope to upgrade compatible angular9

### ISSUE THREAD

**Issue by luoxiao-xy** [ng-select/ng-select#1561]
Hope to upgrade compatible angular9

**Comment by daniel-seitz** [comment]
Hi,
1) please look if there are already open issues about this. What about this: https://github.com/ng-select/ng-select/issues/1519
2) If that doesn't fit, provide a detailed description since we can't guess what is wrong.

**Comment by luoxiao-xy** [comment]
#1519 Mentioned the problem, but did not solve it very well。We should not modify package.json。
The question should be ng-select Versions supports it

**Comment by luoxiao-xy** [comment]
> Hi,
> 
> 1. please look if there are already open issues about this. What about this: #1519
> 2. If that doesn't fit, provide a detailed description since we can't guess what is wrong.

#1519 Mentioned the problem, but did not solve it very well。We should not modify package.json。
The question should be ng-select Versions supports it
