### ISSUE TITLE
Add tag in angular form send value as null

### ISSUE THREAD

**Issue by joakDA** [ng-select/ng-select#1562]
**Describe the bug**
If I select an existing option when I retrieve the form value, it has the correct value, but if I add a new tag, it is automatically selected, but on the form values, the value is null.

**Reproducbile example**
[Demo](https://angular-nrqcch.stackblitz.io)

**To Reproduce** 
Steps to reproduce the behavior (if example is not provided):
1. Select an exiting item and fill username and password fields. The button "Save" will be enabled.
2. Add a new item. The button "Save" remains disabled.
3. If the validation of the select field is disabled, when you click the button, its value remains null. If an existing item is selected, it contains the value selected.

**Expected behavior**
The form must be validated successfully and it will show the value when a new tag is added.

**Screenshots**
![](https://cdn.mathpix.com/snip/images/_48qfozz9-naZU3ghXMAr8ca8dLl-S5-RRAVxCuI_Y0.original.fullsize.png)

**Comment by andreiButenka** [comment]
Hi, joakDA did you find a solution? I'm facing the same problem.

**Comment by varnastadeus** [comment]
your `addDeviceTagFn` just return new object. You should set that object as your form control value

**Comment by sabloger** [comment]
I have this problem too
