### ISSUE TITLE
Dropdown value problem when value not present in items array

### ISSUE THREAD

**Issue by dhavalsolankislk** [ng-select/ng-select#1563]
Hello 
     We are using ng-select in our application. When we are setting default value in dropdown so that user doesnot have to select it, and at that time if value is not present in items array then dropdown is seen as shown in image below
![image](https://user-images.githubusercontent.com/59446200/77298216-967e8600-6d10-11ea-8b6a-07b923cbc953.png)

So is there any way we can show dropdown like below if value is not present in items array 
![image](https://user-images.githubusercontent.com/59446200/77298435-ef4e1e80-6d10-11ea-897a-58cfe1f543f5.png)

**Comment by varnastadeus** [comment]
you can add custom class when selected is not present among items

**Comment by mbshingala28** [comment]
@varnastadeus 
Can you please give a demo or any reference link for this type of custom class?
