### ISSUE TITLE
ngSelect use relational data instead of field value as tag names

### ISSUE THREAD

**Issue by ohabash** [ng-select/ng-select#1565]
Only ids are saved in the database `field.value` how can i use these ids to look-up relational data `field.list` from another db to be used as tag names instead of the ids used in the field val)?

## conponent.html

    <ng-select
        [items]="field.list" 
        [addTag]="true"
        (change)="newTag(field.value)"
        [hideSelected]="true"
        multiple="true"
        bindLabel="name"
        [(ngModel)]="field.value"
    ></ng-select>

## conponent.ts

    newTag(e) {
        // save only ids as new value
        let lastIndex = e.length - 1;
        let last = e[lastIndex];
        this.field.value[lastIndex] = last.id;
        console.log('relational this.field', e);
        this.saveValue()
    }

## key
```
field.list: `[{...},{...},{...}]`
field.value: `[string, string, string]`
```

**Comment by varnastadeus** [comment]
your `ngModel` can be only `ids` if use use `bindValue` but `[items]` should contain object with labels. 
```js
items  = [{id: 1, label: "text"}]
model = [1]
```
all you need
```html
<ng-select [items]="items" bindValue="id" ></ng-select>
```
