### ISSUE TITLE
On focus open dropdown

### ISSUE THREAD

**Issue by chalupabatman07** [ng-select/ng-select#157]
More of a suggestion than an issue, but I was wonder if there is any current way or future improvement where on focus the dropdown multiselect will open. This is especially helpful if you're using keyboard navigation and tabbing to the dropdown. The current behavior is you tab to the dropdown and you need to press the arrow down key in order to see the list. 

Thanks

**Comment by GoNode5** [comment]
Then an option auto open yes/no. I have a form with 10 ng selects and when people tab they don't really want all fields opened (and closed) when tab to navigate...

**Comment by chalupabatman07** [comment]
Yeah an option to auto open. I have a project with a use case where auto opening is requested when using tab navigation.

**Comment by varnastadeus** [comment]
Currently it works similar to native `select` control, you can open with space or arrow key.
Your suggestion is based on very specific use case and I don't see any value supporting it generally. 

Btw, you can achieve this anyway: 
```html
<ng-select #select [items]="cities"
    bindLabel="name"
    bindValue="id"
    (focus)="select.open()"
    placeholder="Select city"
    [(ngModel)]="selectedCityId">
</ng-select>
```

**Comment by chalupabatman07** [comment]
Cool your suggestion worked! Thanks for the tip!
