### ISSUE TITLE
angular 9.1 upgrade 

### ISSUE THREAD

**Issue by wahyufadz** [ng-select/ng-select#1572]
after update from 9.0.1 to 9.1 i get warning from npm like this
**npm WARN @ng-select/ng-select@3.7.3 requires a peer of @angular/common@>=8.0.0 <9.0.0 but none is installed. You must install peer dependencies yourself.** 
it seems same with #1499

and another warning from ng update like this
**Error: Error when flattening the source-map "C:/Users/x/Documents/web/smartbizapp/node_modules/@ng-select/ng-select/lib/ng-templates.directive.d.ts.map" for "C:/Users/x/Documents/web/smartbizapp/node_modules/@ng-select/ng-select/lib/ng-templates.directive.d.ts": RangeError: Maximum call stack size exceeded**

we don't implement ng-select yet but will use it in our next feature, will it cause serious problem ?
thanks

**Comment by mzellho** [comment]
You must have also received this warning before your migration to 9.1 (>=8.0.0 <9.0.0)?

Anyways, I tested it with each Angular 9 version so far and did not face any issues other than the warning you mentioned, however - there is an open issue for making it Angular 9 compatible at https://github.com/ng-select/ng-select/issues/1499

**Comment by wahyufadz** [comment]
no we were just starting this project about 3 month ago and this is the first time we upgade angular,...
thanks for help....

**Comment by mzellho** [comment]
still, npm install with 9.0.1 must have resulted in the same warning since 9.0.1 is not < 9.0.0

**Comment by wahyufadz** [comment]
haha maybe i miss the warning back then...
