### ISSUE TITLE
doesnt update items with hideSelected=true

### ISSUE THREAD

**Issue by Cobr3n** [ng-select/ng-select#1573]
Hello!
The problem only occurs when hideSelected is added.

case:
https://stackblitz.com/edit/angular-kur93x
1) open select type **1**, wait response select item
2) type **2**, Items Should have been replaced but this does not happen

can anyone help me?

**Comment by varnastadeus** [comment]
`(search)='debSearch($event.term)'` just emits event and is not inteded to be used to override `[items]`

**Comment by Cobr3n** [comment]
this emit `selectSearch` function as debounce, check console i tried to console all steps

**Comment by Cobr3n** [comment]
without **hideSelected=true** 
everything works correctly

**Comment by varnastadeus** [comment]
there is example with `[hideSelected]` with https://ng-select.github.io/ng-select#/search
