### ISSUE TITLE
Version >  2.0.0 is not working on scroll for old Firefox versions

### ISSUE THREAD

**Issue by CosminBalosache** [ng-select/ng-select#1575]
For old Firefox on _handleScroll function we need to have instead of e.scrElement => e.target || e.srcElement because just e.srcElement is is undefined

**Comment by ElenaPetrache** [comment]
I am having the same issue

**Comment by varnastadeus** [comment]
what do you mean by old firefox?

**Comment by CosminBalosache** [comment]
For e.g FirefoxESR 52.4.0(64 bits), when I scroll in virtual scrolling I have a crush because e.srcElement in function _handleScroll is undefined, I saw that for some version of browsers we should have e.target instead of e.srcElement or to use both like (e.srcElement || e.target)
