### ISSUE TITLE
NPM install warning for @angular/localize

### ISSUE THREAD

**Issue by sebastianhaeni** [ng-select/ng-select#1576]
When installing version 4 of ng-select, I get the following warning from NPM:

```
npm WARN @ng-select/ng-select@4.0.0 requires a peer of @angular/localize@>= 9.0.0 <10.0.0 but none is installed. You must install peer dependencies yourself.
```

In my project I'm not using `@angular/localize` at all and I'm not planning to. Is there a way for you to remove it from `peerDependencies` so the warning is not displayed anymore?

It's just a minor cosmetic thing.

**Comment by jjamaral** [comment]
+1
