### ISSUE TITLE
create theme bootstrap 5.0

### ISSUE THREAD

**Issue by andrejm7** [ng-select/ng-select#1577]
if the theme 4.0 is difficult .. who knows 5.0

:(

**Comment by andrejm7** [comment]
@anjmao 
release pr bootstrap 4.0

**Comment by jelmerjellema** [comment]
For what it's worth, I just made this scss to make ng-select perform as a form-control. Just add this scss in some global .scss file and add class="form-control" to the ng-select.

ng-select.form-control {
  padding-right: 0 !important;

  .ng-select-container {
    //deze auto hoogte en geen border
    height: auto !important;
    min-height: 0;
    border: none;
    border-color: inherit;
    box-shadow: none !important;

    .ng-value-container {
      padding-left: 0;

      .ng-input {
        top: auto !important;
        padding-left: 0 !important;
      }
    }
  }
}
