### ISSUE TITLE
No way currently to override right-click (context menu) behavior

### ISSUE THREAD

**Issue by aks1994** [ng-select/ng-select#1578]
There has been an existing issue (#948) and a pull request (#1379) related to this but both have gone stale and the pull request has not been merged.

Not sure if I should be opening a new issue for this but there have been no replies on either of the other two issues for several months now.

Simply need a feature to disable the default opening of the ng select on right click press and I believe the pull request accomplishes this. Hope that it can be merged soon

**Comment by anjmao** [comment]
Let's keep discussions on #948
