### ISSUE TITLE
disable select options by custom field 

### ISSUE THREAD

**Issue by mokey1** [ng-select/ng-select#158]
in default way for disable ng-select options i use  "disabled:true" in my json objects.
is there any way to determine other field for disable ng-select options ?
for example i want use "isDefault" field to disable ng-select options

**Comment by varnastadeus** [comment]
Currently only available option is to iterate your array and set `disabled` property based on your desired condition.

**Comment by anjmao** [comment]
We can add public method setOptionState(option) so it is possible to access this method and set any property you like.

**Comment by varnastadeus** [comment]
@anjmao I think iterating and setting disabled is more than enough. Another option to achieve this would be to have custom dropdown template #69

**Comment by mokey1** [comment]
@varnastadeus "[disabled]" not work in custom dropdown template.
my custom template:
<ng-template  ng-option-tmp let-item="item" let-index="index">
                    <button mat-button [disabled]="!item.isDefault"  >{{item.title}}</button>
                </ng-template>

but this code only disable button and when click option it's select very well!

**Comment by mokey1** [comment]
@varnastadeus ["disabled"] not work in custom template

**Comment by varnastadeus** [comment]
You need to iterate in your component, not in html

**Comment by wlievens** [comment]
Is there a reason `<ng-option [disabled]="..."></ng-option>` is not possible?

**Comment by varnastadeus** [comment]
@wlievens `ng-option` is still very new so it lacks features

**Comment by wlievens** [comment]
Thanks for the speedy reply. So it is possible this will be implemented in the future? I prefer not to manipulate my data model for UI purposes.

**Comment by varnastadeus** [comment]
@wlievens `ng-option` mimics html select `option`, so things like `selected`, `disabled` etc. should be supported.

**Comment by anjmao** [comment]
Closing as issue is already solved in #236.
