### ISSUE TITLE
Async pipe does not compile with strictTemplates

### ISSUE THREAD

**Issue by Perflectie** [ng-select/ng-select#1580]
**Describe the bug**
If the strictTemplates option is true (tsconfig.json > angularCompilerOptions), and a async pipe is used in the [items] input, the build does not compile.
A workaround is to add an empty array fallback, but it's not ideal.

**Reproducbile example**
[Example](https://stackblitz.com) which reproduces described behaviour

**To Reproduce** 
Steps to reproduce the behavior (if example is not provided):
1. tsconfig.json: set angularCompilerOptions.strictTemplates = true
2. Create a template with `<ng-select [items]="items$ | async"></ng-select>
3. Try to compile

**Expected behavior**
I expect [items] to be typed `any[] | null`.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: n/a

**Additional context**

**Comment by docwhite** [comment]
Hello @Perflectie, I am having the same issue.

Can I ask you how did you solve it? By setting `strictTemplates` to `false` in the `tsconfig.json`?

Thanks!

**Comment by Perflectie** [comment]
I did not, unfortunately. We have customized the tsconfig.json settings so it compiled again.
