### ISSUE TITLE
Select with server-side data loading is triggering request with null term on option select

### ISSUE THREAD

**Issue by delyan-georgiev** [ng-select/ng-select#1582]
**Describe the bug**
When using single select with server loaded options the component triggers a request call on option select

**Reproducible example**
https://stackblitz.com/edit/angular-xq5yrg?file=src%2Fsearch-autocomplete-example.component.html

**To Reproduce** 
1. Open developer tools console
2. Go to the select and start typing to initiate a search
3. You should see the correct request log whit correct term in the console
3. Select one of the matched items
4. You should see a second request log with null as a term value

**Expected behavior**
I expect that there should be only requests with  the search term that the user is entering

**Screenshots**
![image](https://user-images.githubusercontent.com/6060805/78714335-63e5a780-7924-11ea-8dfe-e405697fb289.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kimdah3** [comment]
This is probably intended behaviour as you can see in this previous issue #1420

**Comment by serlopez46** [comment]
I do not think this is the intended behavior, there is a clear difference between the user manually clearing the search input and the user selecting an option.
As #1420 states, when the user manually clears the search input a search with null value should be triggered, this is working correctly.

The current problem is that when the user selects an option and the `clearSearchOnAdd` property is true (default behavior) then the `_clearSearch` function is called and ultimately a new search is done with null value. 
This makes no sense as there is no need to call for a new search after selecting an option and will only consume more server resources.

**Comment by eduardoleopoldino** [comment]
Is there a fix or workaround for this issue?

**Comment by sebastian-zarzycki-es** [comment]
From my observation, the typeahead subject value is pushed with null when item is selected from the list, even when clearSearchOnAdd is set to false. That is definitely a not intended behavior.

**Comment by luiza-avelino** [comment]
My workaround was to put a filter on mine implementation.

Follows a screenshot:

![image](https://user-images.githubusercontent.com/53008706/150388364-6af92673-64ab-40e5-ba11-352bbd537b53.png)
