### ISSUE TITLE
Accesibility Issue: Cannot access to ng-footer-tmp content with tabstop or via keyboard

### ISSUE THREAD

**Issue by MiguelCh24** [ng-select/ng-select#1583]
**Describe the bug**
When using ng select with custom header and footer using **ng-header-tmp** and/or **ng-footer-tmp** cannot access to content of those template via keyboard ( tabstop or any other key )

**Reproducible example**
https://stackblitz.com/edit/angular-xoaspu

To Reproduce
1. Execute the example in stackblitz.
2. Try to access buttons of **ng-footer-tmp** via keyboard.

**Expected behavior**
I hope to access the navigable elements that are inside the ng-footer-tmp.

NOTE: With the changes implemented in the PR [#1026](https://github.com/ng-select/ng-select/pull/1026), some accessibility issues have been resolved, but not 100% covered.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome, Mozila

**Smartphone (please complete the following information):**

**Additional context**

**Comment by brunano21** [comment]
The reason is that the focus never leaves the input when the dropdown is open: the focus in any of the list items is a visual/fake focus and not the HTML native focus one. The panel itself is not focusable.

**Comment by MiguelCh24** [comment]
So, does that mean that could I not access some accessibility behavior for this component (specifically this problem that I am raising)?

**Comment by brunano21** [comment]
Not at the moment, some accessibility implementation needs to be put in place indeed.

**Comment by gayathrirajendran** [comment]
Any improvements on this ?

**Comment by abisleem** [comment]
Is there an intention to resolve this?

**Comment by alanschwaner** [comment]
Any update on this ?

**Comment by anurag-roy** [comment]
Also facing the same issue, currently is there any workaround/hack to make it somehow work?

**Comment by PrabagaranSaminathan** [comment]
Any updates on this?

**Comment by h1ghland3r** [comment]
Any updates guys? It's a matter o accessibility issue.
