### ISSUE TITLE
How can I deactivate the selection of a group?

### ISSUE THREAD

**Issue by GitHubish** [ng-select/ng-select#1584]
I have the ability to select a group of items. But I have a case where a group should not be selectable. Could this feature be added for example with the addition of an attribute on the ng-template (ng-optgroup-tmp).

Thanks

**Comment by marcos-bah** [comment]
do you have a solution?

**Comment by GitHubish** [comment]
I did not find any unfortunately...

**Comment by marcos-bah** [comment]
> 

same problem here :/ thanks
