### ISSUE TITLE
bindLabel subobject

### ISSUE THREAD

**Issue by koss89** [ng-select/ng-select#159]
Good afternoon.
faced such a problem:
I need in bindLabel to withdraw from the object inside the object for example I have an object:
**{
   id: "2334",
   tags: {
      name: "test"
   }
}**
Accordingly I do **bindLabel = "tags.name"** but I get empty lines

**Comment by koss89** [comment]
I'm sorry solved using templates:
**<ng-select [items]="_lines"
        [(ngModel)]="_selectedline">
        <ng-template ng-label-tmp let-item="item">
            {{item.tags.name}}
        </ng-template>
        <ng-template ng-option-tmp let-item="item">
            {{item.tags.name}}
        </ng-template>
      </ng-select>**

**Comment by varnastadeus** [comment]
@koss89 good catch, I think it should be supported with `tags.name` expression so I am reopening this.

**Comment by koss89** [comment]
in the process revealed another feature in the version that I described above, the filter is not working, so this is another plus to re-opening

**Comment by elVengador** [comment]
tu can use this: 
```
<ng-select [(ngModel)]="_selectedline">
   <ng-option *ngFor="let item of items" [value]="item.id">{{item.tags.name}}</ng-option>
</ng-select>
```
