### ISSUE TITLE
Cannot open dropdown if items empty array and hideSelected true

### ISSUE THREAD

**Issue by Serrulien** [ng-select/ng-select#1592]
**Describe the bug**
Cannot open the dropdown if items is an empty array and hideSelected is true.

**Reproducible example**
https://stackblitz.com/edit/ng-select-issue-hideselected-empty-items-no-items-not-found

**Expected behavior**
As a user it is confusing not to be able to open the dropdown. We should see "no items founds".
The dropdown does appear if hideSelected is false.

**Screenshots**
hideSelected is true
![image](https://user-images.githubusercontent.com/16616176/79890387-b385a200-83ff-11ea-8182-4885ef36d95a.png)
hideSelected is false
![image](https://user-images.githubusercontent.com/16616176/79890428-c304eb00-83ff-11ea-829d-7db1c2914b13.png)

Windows 10 Firefox 75 (64bits)
Windows 10 Chrome 81.0.4044.113

**Comment by Chinna2405** [comment]
I am also facing the same issue.Thanks in Advance

**Comment by Serrulien** [comment]
**Workaround:**
set hideSelected to false only if items is empty, otherwise set it to true.
https://stackblitz.com/edit/ng-select-issue-hideselected-empty-items-liuli

**Comment by Adrug** [comment]
Similar problem with long data request. 
First focus doesn't open dropdown.

https://stackblitz.com/edit/angular-seelaz?file=data.service.ts

**Comment by keyone-zen** [comment]
Similar problem with 9.0.2

**Comment by szaszendre** [comment]
Still present in 10.0.4 but the workaround suggested by @Serrulien still works
`[hideSelected]="items.length > 0 && otherConditions"`
