### ISSUE TITLE
Highlighting displays encoded text if it contains ampersand character.

### ISSUE THREAD

**Issue by prasadc82** [ng-select/ng-select#1593]
**Describe the bug**
Highlighting displays encoded text if it contains '&' ( ex: 'Vilnius & Pavilnys' )

**Reproducbile example**
https://stackblitz.com/edit/angular-g5ufg4

**To Reproduce** 
Steps to reproduce the behavior (if example is not provided):
1. Go to https://stackblitz.com/edit/angular-g5ufg4
2. start search, by typing in 'a'
3. You can view `&amp;` inside the first option

**Expected behavior**
Should not see `&amp;`

**Screenshots**

<img width="574" alt="Screen Shot 2020-04-21 at 4 41 05 PM" src="https://user-images.githubusercontent.com/1889047/79925477-4bc75b00-83ef-11ea-8fa7-d722500e598e.png">

**Comment by borismavrodiev** [comment]
I am facing the same issue here.

**Comment by DaanTul** [comment]
Same issue

**Comment by DaanTul** [comment]
Issue can be traced back to `ng-option-highlight-directive`

```js
    private _escapeRegExp(str: string): string {
        return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    }

    private _highlightLabel() {
        const label = this.label;
        if (!this.term) {
            this._setInnerHtml(label);
            return;
        }

        const alternationString = this._escapeRegExp(this.term).replace(' ', '|');
        const termRegex = new RegExp(alternationString, 'gi');
        this._setInnerHtml(label.replace(termRegex, `<span class=\"highlighted\">$&</span>`))
    }
```

The RegExp doesn't handle ampersands correctly when with highlighted span

**Comment by DaanTul** [comment]
Nevermind, the RegExp is fine. It is related to the Renderer2 not handling setting ampersands correctly on innerhtml. As the highlighting seems to work fine but the setting of the innerHtml leads to html encoding of the ampersand character..

**Comment by simonpweller** [comment]
Despite this going stale, I think this issue still persists in the latest version of `ng-option-highlight-directive`. I played around with it a bit more and I don't think it's related to the Renderer2.

To me it looks like getting the label using innerHTML is what causes the issue: 

```
ngAfterViewInit() {
    this.label = this.element.innerHTML;
    if (this._canHighlight) {
        this._highlightLabel();
    }
}
```

The innerHTML of an element with the text Vilnius & Pavilnys is "Vilnius &amp; Pavilnys". Running _highlightLabel on that with a as the search term will match the a in `&amp;`. I've tested this locally and it looks like using innerText instead to get the label from the element would fix the issue.

Are you open to a pull request in this direction?

**Comment by Chrisw32** [comment]
Hi, Could the linked PR please be merged? we've tested it out internally and it does fix the issue with the special characters. Thanks.
