### ISSUE TITLE
Unable to bind duplicate values by default in ng-select multiselect

### ISSUE THREAD

**Issue by shinchan305** [ng-select/ng-select#1595]
Hi All,

I am using multiselect option for ng-select in angular 9.

The items array looks like this:
var items = [
    {
      name: "a"
    },
    {
      name: "a"
    },
    {
      name: "b"
    },
    {
      name: "b"
    }, {
      name: "c"
    },
    {
      name: "c"
    }, {
      name: "c"
    }
  ]

I have a default array, which I am using as ngModel for this. The default array looks like this:
selectedItems = ["a", "a", "b", "b"]

<ng-select        name="items"
                         [items]="items"
                         bindLabel="name"
                         bindValue="name"
                         [multiple]="true"
                         [(ngModel)]="selectedItems">
</ng-select>

The ng-select control displays this:
["a", "b"]

ng-select is filtering out the duplicates automatically when binding for the first time. 
Is there a setting which can be turned on or off so that my entire set of entries are visible when binding for the first time?

Thank you for your help in advance!

**Comment by varnastadeus** [comment]
you can't select the exact same item multiple times, you need to have some sort distinction.
