### ISSUE TITLE
NgSelectComponent filterValue does not exist 

### ISSUE THREAD

**Issue by FontanyLegall-Brandon** [ng-select/ng-select#1596]
Hello, 

When i made the upgrade of ngSelect, i get this error : 
`Property 'filterValue' does not exist on type 'NgSelectComponent'`

I dont find the **getter**, did there is a **getter** in the new version ? :thinking: 
I want for example make a function as this : 
`(scrollToEnd)="onScrollToEnd(ngSelect.filterValue)"`

Thanks in advance for your answer ! :smile:

**Comment by varnastadeus** [comment]
it is renamed to `searchTerm`

**Comment by FontanyLegall-Brandon** [comment]
Many thanks @varnastadeus

**Comment by Parth7030** [comment]
Angular v7 to V8
OR
searchInput: ElementRef<HTMLInputElement>; to "@ng-bootstrap/ng-bootstrap": "5.3.0"

`filterInput: ElementRef;`

is changed to: 

`searchInput: ElementRef<HTMLInputElement>;`
