### ISSUE TITLE
No provider for NgSelectConfig!

### ISSUE THREAD

**Issue by dsmerrikin** [ng-select/ng-select#1602]
app.module.ts
`import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { NgSelectModule } from '@ng-select/ng-select';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { HeaderComponent } from './components/header/header.component';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import { HeroComponent } from './components/hero/hero.component';
import { DescriptionComponent } from './components/description/description.component';
import { FeaturetteComponent } from './components/featurette/featurette.component';
import { EventsComponent } from './components/events/events.component';
import { FeaturedProjectComponent } from './components/featured-project/featured-project.component';
import { WhyComponent } from './components/why/why.component';
import { FooterComponent } from './components/footer/footer.component';
import { MayaComponent } from './components/maya/maya.component';
import { HomeComponent } from './routes/home/home.component';
import { PageNotFoundComponent } from './routes/page-not-found/page-not-found.component';
import { EventsrouteComponent } from './routes/eventsroute/eventsroute.component';
import { WhoswhorouteComponent } from './routes/whoswhoroute/whoswhoroute.component';
import { BlogrouteComponent } from './routes/blogroute/blogroute.component';
import { ResourcesrouteComponent } from './routes/resourcesroute/resourcesroute.component';
import { SearchrouteComponent } from './routes/searchroute/searchroute.component';
import { AlertsComponent } from './components/alerts/alerts.component';
import { PanelComponent } from './components/panel/panel.component';
import { BlogpostsComponent } from './components/blogposts/blogposts.component';
import { PrimenuComponent } from './components/primenu/primenu.component';
import { CommunityStructureComponent } from './components/community-structure/community-structure.component';
import { LeadershipTeamComponent } from './components/leadership-team/leadership-team.component';
import { AllMembersComponent } from './components/all-members/all-members.component';
import { AlphabeticalPipe } from './pipes/alphabetical.pipe';

@NgModule({
  declarations: [
    AppComponent,
    HeaderComponent,
    HeroComponent,
    DescriptionComponent,
    FeaturetteComponent,
    EventsComponent,
    FeaturedProjectComponent,
    WhyComponent,
    FooterComponent,
    MayaComponent,
    HomeComponent,
    PageNotFoundComponent,
    EventsrouteComponent,
    WhoswhorouteComponent,
    BlogrouteComponent,
    ResourcesrouteComponent,
    SearchrouteComponent,
    AlertsComponent,
    PanelComponent,
    BlogpostsComponent,
    PrimenuComponent,
    CommunityStructureComponent,
    LeadershipTeamComponent,
    AllMembersComponent,
    AlphabeticalPipe
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    HttpClientModule,
    FontAwesomeModule,
    FormsModule,
    NgSelectModule,
    ReactiveFormsModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule {

}
`
component.html
`<ng-select [items]="filters$ | async"
           bindLabel="name"
           autofocus
           bindValue="id"
           [(ngModel)]="selectedPersonId">
        </ng-select>`

component.ts
`import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'leadership-team',
  templateUrl: './leadership-team.component.html',
  styleUrls: ['./leadership-team.component.scss']
})
export class LeadershipTeamComponent implements OnInit {
    filters$ = [
      {name:'Expertise',id:'1'}, {name:'Department',id:'2'}, {name:'Red',id:'3'}];
    constructor() {
     
    }
    ngOnInit() {
    }

}
`
package.json
`{
  "name": "hexd",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.2.14",
    "@angular/common": "~8.2.14",
    "@angular/compiler": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "@fortawesome/angular-fontawesome": "^0.6.1",
    "@fortawesome/fontawesome-free": "^5.13.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.28",
    "@fortawesome/free-solid-svg-icons": "^5.13.0",
    "@microsoft/microsoft-graph-client": "^2.0.0",
    "@ng-bootstrap/ng-bootstrap": "^5.3.1",
    "@ng-select/ng-select": "^4.0.0",
    "bootstrap": "^4.4.1",
    "cookie-parser": "^1.4.5",
    "express-generator-api": "^6.0.0",
    "jquery": "^3.5.0",
    "moment": "^2.24.0",
    "path": "^0.12.7",
    "rxjs": "~6.4.0",
    "rxjs-compat": "^6.5.5",
    "tslib": "^1.10.0",
    "uid-safe": "^2.1.5",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.803.26",
    "@angular/cli": "^8.3.26",
    "@angular/compiler-cli": "~8.2.14",
    "@angular/language-service": "~8.2.14",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^8.10.60",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "^5.4.4",
    "ts-node": "^7.0.1",
    "tslint": "~5.15.0",
    "typescript": "^3.6.5"
  }
}
`

I'm getting the following error when compiling:

`ERROR Error: Uncaught (in promise): NullInjectorError: StaticInjectorError(AppModule)[NgSelectComponent -> NgSelectConfig]: 
  StaticInjectorError(Platform: core)[NgSelectComponent -> NgSelectConfig]: 
    NullInjectorError: No provider for NgSelectConfig!
NullInjectorError: StaticInjectorError(AppModule)[NgSelectComponent -> NgSelectConfig]: 
  StaticInjectorError(Platform: core)[NgSelectComponent -> NgSelectConfig]: 
    NullInjectorError: No provider for NgSelectConfig!
    at NullInjector.get (core.js:855)
    at resolveToken (core.js:17514)
    at tryResolveToken (core.js:17440)
    at StaticInjector.get (core.js:17266)
    at resolveToken (core.js:17514)
    at tryResolveToken (core.js:17440)
    at StaticInjector.get (core.js:17266)
    at resolveNgModuleDep (core.js:30393)
    at NgModuleRef_.get (core.js:31578)
    at resolveDep (core.js:32143)
    at resolvePromise (zone-evergreen.js:797)
    at resolvePromise (zone-evergreen.js:754)
    at zone-evergreen.js:858
    at ZoneDelegate.invokeTask (zone-evergreen.js:391)
    at Object.onInvokeTask (core.js:39680)
    at ZoneDelegate.invokeTask (zone-evergreen.js:390)
    at Zone.runTask (zone-evergreen.js:168)
    at drainMicroTaskQueue (zone-evergreen.js:559)
    at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:469)
    at invokeTask (zone-evergreen.js:1603)
`

Any advice on how to fix this is greatly appreciated. Thank you.

**Comment by thsiung** [comment]
I was having the same issue. Then I've realized I should've used ng-select ^3.0.0 instead of ^4.0.0 since I am also using Angular version 8 instead of version 9. Just change your package.json from "@ng-select/ng-select": "^4.0.0" to "@ng-select/ng-select": "**^3.0.0**". It works for me!

**Comment by sbk181** [comment]
Did you ever solve this issue? I'm having the same problem. And the change in package.json did not help me. Thanks.

**Comment by sbk181** [comment]
I figured it out. I had to include ConsoleService, which ng-select exports as "es"

So, in my app.module.ts, I had to add:
import { NgSelectConfig } from '@ng-select/ng-select';
import { ɵs } from '@ng-select/ng-select';

And in providers, I added: NgSelectConfig and es
