### ISSUE TITLE
Add icon along with the drop-down 'icon' 

### ISSUE THREAD

**Issue by monis001** [ng-select/ng-select#1607]
**Is your feature request related to a problem? Please describe.**
How can I add icons in ng-select along with the drop-down,  icons like 'filter icon', 'search icon' etc, etc.
**Describe the solution you'd like**
To provide a more appealing and UX perspective to drop-down.

**Describe alternatives you've considered**
Added icon with CSS positioning BUT that interferes with the selected item. e.g.
[Icon]
![image](https://user-images.githubusercontent.com/46885793/80964697-f6e40580-8e2e-11ea-91a3-bd9a4417f50c.png)
[Interference]
![image](https://user-images.githubusercontent.com/46885793/80964762-0cf1c600-8e2f-11ea-958f-dc1355be4cc6.png)

Any other possible way or this feature if is in pipeline.

Thanks

**Comment by aseer-ws** [comment]
+1
