### ISSUE TITLE
Not possible to clear the list when [items] is an Observable

### ISSUE THREAD

**Issue by jethas-bennettjones** [ng-select/ng-select#1608]
**Describe the bug**
When the [items] property is a Observable it cannot be cleared when the handleClearClick method is called.

**Reproducible example**
https://stackblitz.com/edit/angular-wct2se

**To Reproduce** 
1. Type into the text box a person that you would like to find
2. Select the person
3. Click the Clear Input box
4. Note that the field is now empty
5. Click the select box's dropdown and note that the dropdown list still contains entries from the previous search.

**Expected behavior**
When handleClearClick is called, or as a separate function or property, the dropdown list should be cleared as well.

**Desktop (please complete the following information):**
 - OS: Windows 10 1909
 - Browser Chromium Edge
 - Version 81.0.416.68

**Comment by varnastadeus** [comment]
`handleClearClick` does nothing with `[items]` nor observable, you should handle it by yourself if you want clear searched items. https://stackoverflow.com/questions/52065615/angular-clear-observable-on-click
