### ISSUE TITLE
Autosize dropdown panel with virtual scroll enabled doesn't work.

### ISSUE THREAD

**Issue by e93rtP** [ng-select/ng-select#1612]
When virtual scroll is enabled width: auto doesn't work. 
```
.ng-dropdown-panel` {
    width: auto!important;
 }
```
Dropdown should take the largest width of ng-option.

**Desktop**
 - OS: Windows 10
 - Browser: Chrome
 - Version:  80.0.3987.149

**Comment by Surya0550** [comment]
I'm on Angular v10.2.3 and ng-select v5.1.0, I can still see this issue

**Comment by uthmanrahimi** [comment]
Could you solve this issue?

**Comment by Zahen** [comment]
I re-create the same issue heree : https://github.com/ng-select/ng-select/issues/2198
