### ISSUE TITLE
Update ngModel on dropdown close

### ISSUE THREAD

**Issue by scarigor** [ng-select/ng-select#1614]
**Is your feature request related to a problem? Please describe.**
I'm using ng-select components (which are great) with ReactiveFormsModule in my project. 
The form has quite a lot of form controls, some controls (let name it **ct1**) retrieve options for themselves via external API based on values selected in another ones (**ct2**, **ct3)** [(multiselect checkboxes).](https://ng-select.github.io/ng-select#/multiselect-checkbox). The problem is that each time user selects / deselects checkbox -> models of form controls (**ct2**, **ct3**) get updated (i use **valueChanges** stream along with **merge** and **switchMap**) and causes options retrieval for  **ct1**. And such behavior cause undesired network load in my case.

Of course we could debounce it for some time and get used to request cancelling because of switchMap, but It would be great to even don't do them.

**Describe the solution you'd like**
Would be nice to have some input property **updateNgModelOnClose** (but with better naming) and trigger model update only on close.

**Describe alternatives you've considered**
For now, I'm handling such issue with additional stream **selectClosed$** which emits value (name of control) each time dropdown closes. 

Example (details omitted): 
**HTML**
``<ng-select formControlName="city" (close)="onClose('city')">...</ng-select>
<ng-select formControlName="year" (close)="onClose('year')">...</ng-select>``

```javascript
onClose(controlName) {
  selectClosed$.next(controlName)
}

watchForControls() {
  return merge(
    selectClosed$.pipe(filter(name => name === 'city')),
    selectClosed$.pipe(filter(name => name === 'year'))
  ).pipe(switchMap(() => getOptionsForThirdControls()))
}
```

Potentially there will be more similar controls, so such approach seems not so good.

**Additional context**
![chrome-capture](https://user-images.githubusercontent.com/15365823/81437262-8b25d380-9173-11ea-9f51-7c5244b66929.gif)

**Comment by varnastadeus** [comment]
have you tried https://angular.io/api/forms/AbstractControlOptions `updateOn?: 'blur`. Should solve your case
