### ISSUE TITLE
An accessor cannot be declared in an ambient context

### ISSUE THREAD

**Issue by dillibk777** [ng-select/ng-select#1615]
```
ERROR in node_modules/@ng-select/ng-select/lib/items-list.d.ts(10,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ng-select/ng-select/lib/items-list.d.ts(12,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ng-select/ng-select/lib/items-list.d.ts(14,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ng-select/ng-select/lib/items-list.d.ts(15,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ng-select/ng-select/lib/items-list.d.ts(16,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ng-select/ng-select/lib/items-list.d.ts(17,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ng-select/ng-select/lib/items-list.d.ts(18,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ng-select/ng-select/lib/items-list.d.ts(19,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ng-select/ng-select/lib/ng-dropdown-panel.component.d.ts(41,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ng-select/ng-select/lib/ng-dropdown-panel.component.d.ts(43,17): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ng-select/ng-select/lib/ng-dropdown-panel.component.d.ts(44,17): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ng-select/ng-select/lib/ng-dropdown-panel.component.d.ts(45,17): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ng-select/ng-select/lib/ng-dropdown-panel.service.d.ts(14,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ng-select/ng-select/lib/ng-option.component.d.ts(6,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ng-select/ng-select/lib/ng-option.component.d.ts(7,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ng-select/ng-select/lib/ng-option.component.d.ts(16,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ng-select/ng-select/lib/ng-select.component.d.ts(64,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ng-select/ng-select/lib/ng-select.component.d.ts(65,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ng-select/ng-select/lib/ng-select.component.d.ts(66,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ng-select/ng-select/lib/ng-select.component.d.ts(67,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ng-select/ng-select/lib/ng-select.component.d.ts(68,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ng-select/ng-select/lib/ng-select.component.d.ts(69,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ng-select/ng-select/lib/ng-select.component.d.ts(101,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ng-select/ng-select/lib/ng-select.component.d.ts(102,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ng-select/ng-select/lib/ng-select.component.d.ts(121,17): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ng-select/ng-select/lib/ng-select.component.d.ts(128,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ng-select/ng-select/lib/ng-select.component.d.ts(129,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ng-select/ng-select/lib/ng-select.component.d.ts(130,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ng-select/ng-select/lib/ng-select.component.d.ts(131,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ng-select/ng-select/lib/ng-select.component.d.ts(157,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ng-select/ng-select/lib/ng-select.component.d.ts(187,17): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ng-select/ng-select/lib/ng-select.component.d.ts(188,17): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ng-select/ng-select/lib/selection-model.d.ts(12,9): error TS1086: An accessor cannot be declared in an ambient context.
```

package.json

`{
  "name": "@coreui/coreui-free-angular-admin-template",
  "version": "2.5.2",
  "description": "CoreUI Free Angular 2+ Admin Template",
  "author": {
    "name": "Łukasz Holeczek",
    "url": "http://holeczek.pl",
    "github": "https://github.com/mrholek",
    "twitter": "https://twitter.com/lukaszholeczek"
  },
  "contributors": [
    {
      "name": "Andrzej Kopański",
      "url": "https://github.com/xidedix"
    }
  ],
  "homepage": "https://coreui.io/angular",
  "copyright": "Copyright 2019 creativeLabs Łukasz Holeczek",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve --proxy-config proxy.conf.json",
    "build": "ng build --prod --aot --buildOptimizer --commonChunk --vendorChunk --optimization --progress",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^8.2.11",
    "@angular/cdk": "^8.2.3",
    "@angular/common": "^8.2.11",
    "@angular/compiler": "^8.2.11",
    "@angular/core": "^8.2.11",
    "@angular/forms": "^8.2.11",
    "@angular/http": "^8.0.0-beta.10",
    "@angular/material": "^8.2.3",
    "@angular/platform-browser": "^8.2.11",
    "@angular/platform-browser-dynamic": "^8.2.11",
    "@angular/router": "^8.2.11",
    "@coreui/angular": "^2.6.1",
    "@coreui/coreui": "^2.1.12",
    "@coreui/coreui-plugin-chartjs-custom-tooltips": "^1.3.1",
    "@coreui/icons": "0.3.0",
    "@ng-bootstrap/ng-bootstrap": "^5.1.1",
    "@ng-select/ng-select": "latest",
    "@swimlane/ngx-datatable": "^16.0.2",
    "angular-2-data-table": "^0.1.2",
    "angular-6-datatable": "^0.8.0",
    "angular-bootstrap-md": "^8.4.0",
    "angular-tag-select": "latest",
    "angular-user-idle": "^2.2.1",
    "angular-webstorage-service": "^1.0.2",
    "angular2-datatable": "^0.6.0",
    "angular2-multiselect-dropdown": "latest",
    "angularx-qrcode": "^1.6.4",
    "angularx-social-login": "^2.2.1",
    "bootstrap": "^4.3.1",
    "chart.js": "^2.8.0",
    "core-js": "^2.6.10",
    "file-saver": "latest",
    "flag-icon-css": "^3.4.2",
    "font-awesome": "^4.7.0",
    "jqwidgets-ng": "^8.3.2",
    "jqwidgets-scripts": "^8.3.2",
    "mat-select-filter": "^2.3.6",
    "moment": "^2.24.0",
    "mutationobserver-shim": "^0.3.3",
    "ng-block-ui": "^2.1.8",
    "ng2-charts": "^2.3.0",
    "ng2-data-table": "^1.4.0",
    "ngx-bootstrap": "^5.2.0",
    "ngx-daterangepicker-material": "~2.1.10",
    "ngx-perfect-scrollbar": "^8.0.0",
    "rxjs": "^6.5.3",
    "rxjs-observable": "0.0.7",
    "saturn-datepicker": "8.0.1",
    "simple-line-icons": "^2.4.1",
    "ts-helpers": "^1.1.2",
    "tsickle": "^0.35.0",
    "tslib": "^1.10.0",
    "uuid": "^3.3.3",
    "web-animations-js": "^2.3.1",
    "xlsx": "latest",
    "zone.js": "^0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.800.3",
    "@angular/cli": "^8.3.12",
    "@angular/compiler-cli": "^8.2.11",
    "@angular/language-service": "^8.2.11",
    "@types/jasmine": "^3.4.4",
    "@types/jasminewd2": "^2.0.8",
    "@types/node": "^12.11.2",
    "codelyzer": "^5.1.2",
    "jasmine-core": "^3.5.0",
    "jasmine-spec-reporter": "^4.2.1",
    "karma": "^4.4.1",
    "karma-chrome-launcher": "^2.2.0",
    "karma-coverage-istanbul-reporter": "^2.0.5",
    "karma-jasmine": "^2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "^5.4.2",
    "ts-node": "^8.4.1",
    "tslint": "^5.20.0",
    "typescript": "~3.5.3"
  },
  "engines": {
    "node": ">= 12",
    "npm": ">= 6"
  }
}
`

**Comment by dillibk777** [comment]
resolved by change version to 
  `  "@ng-select/ng-select": "^3.7.3"`

**Comment by artyuum** [comment]
I also encountered the same issue on Angular 8.2.14 and downgrading to ^3.7.3 worked.
@dillibk777 Would be cool if you could re-open the issue as downgrading version is not actually a fix. We need to investigate on why the error happened (unless someone else already mentioned the error and they are working on it).
