### ISSUE TITLE
NullInjectorError: StaticInjectorError(AppModule)[NgSelectComponent -> ConsoleService]

### ISSUE THREAD

**Issue by hainguyen81** [ng-select/ng-select#1616]
![image](https://user-images.githubusercontent.com/13741282/81810426-1ffe4780-954d-11ea-827c-f458b54550ee.png)
I could not inject ConsoleService, because its path is in lib.
I already import NgSelectModule to application module.
Please help me

**Comment by BrusGarka** [comment]
hi guys, same happen to me. angular 9x here. tried ng-select 4.x and 5.x. please help

**Comment by AbiSadhasivam** [comment]
Same problem for me as well. Any resolution?

**Comment by BrusGarka** [comment]
i make a downgrade and worked for me, @AbiSadhasivam. The ng-select version list in the readme didin't worked.

**Comment by varnastadeus** [comment]
`ConsoleService` is not exported and shouldn't be used outside of ng-select
