### ISSUE TITLE
Dynamic class for the dropdown panel

### ISSUE THREAD

**Issue by ndovnar** [ng-select/ng-select#1619]
Hello, first of all, thanks a lot for your job!
It would be handy if the component had the capability to set a dynamic class for the dropdown panel, use case:
I am using this select with `appendTo` input and in some cases, I have to set a fixed width for the dropdown component, I can't use `class` because it's needed not for all of them.

**Comment by varnastadeus** [comment]
it is already possible, if you set class on `ng-select` it is propagated to dropdown panel.

**Comment by ndovnar** [comment]
@varnastadeus, You are right, but I am trying to use that with [ngClass] and it doesn't work, it looks like it is propagated only initial classes, here is an example https://stackblitz.com/edit/angular-ivy-9pxhre?file=src%2Fapp%2Fapp.component.html
