### ISSUE TITLE
can I add show button in each option

### ISSUE THREAD

**Issue by ahmedkhairydev** [ng-select/ng-select#1620]
I want to see the details of each option without select the option like this photo.
![image](https://user-images.githubusercontent.com/15922118/82132267-41299700-97de-11ea-87f4-6c830acfceab.png)

**Comment by babsley** [comment]
@ahmedkhairydev, hello, I think event.stopPropagation() can help you with that.

**Comment by ahmedkhairydev** [comment]
@babsley Hello, I tried it and it's working fine. Thank you, bro ♥
