### ISSUE TITLE
Cursor jumps to end of input text on safari browser

### ISSUE THREAD

**Issue by suchitak** [ng-select/ng-select#1622]
https://ng-select.github.io/ng-select#/data-sources

If you keep the cursor in the middle of the text and start typing, the cursor moves to the end.
It doesn't happen on chrome.

Can you please help with this issue?

Same as this issue - https://github.com/ng-select/ng-select/issues/1480

**Comment by philhinco** [comment]
Experiencing the same issue here. Does not seem to happen on Firefox or Chrome.

**Comment by wzc0415** [comment]
Same issue in Safari

**Comment by armved** [comment]
Having the same issue on Safari. I think this should be fixed.
