### ISSUE TITLE
When [selectableGroup]="true", groups should be searchable

### ISSUE THREAD

**Issue by armved** [ng-select/ng-select#1623]
**Describe the bug**
When using this control for selecting geography, like some of US states or USA itself, it's not possible to search for USA because selectable groups are not being respected when typing.

**Reproducbile example**
[Example](https://stackblitz.com/run?file=src/group-selectable-example.component.html) which reproduces described behaviour

**To Reproduce** 
Try to search by country name like "United States" or "Colombia".

**Expected behavior**
Selectable groups should be highlighted if search term matches their name.

**Screenshots**
![image](https://user-images.githubusercontent.com/20437842/82327982-e95e7c00-99e7-11ea-812e-9dd49a9bc45b.png)

**Additional context**
We should include selectable groups in search if [selectableGroup]="true". And we should respect [bindLabel] as well.

The only question here is about should we show children as well when searching for parent or we shouldn't. I think we should just show parent (i.e. selectable group)

**Comment by armved** [comment]
I will try to fix this by myself.

**Comment by kingwillowix** [comment]
Is there an update on this please ;-). Thanks

**Comment by Bobby106** [comment]
I am also facing same issue, not able to search by group name if no child associate.

**Comment by armved** [comment]
> I am also facing same issue, not able to search by group name. is there any solution to fix this ?

Unfortunately there is no solution for this. I've made PR for my solution but is not being commented.

**Comment by idasabel** [comment]
I made a workaround for this.
```
<ng-select ... 
           [bindLabel]="ngSelectBindLabel"
           [groupBy]="ngSelectGroupBy"
           [searchFn]="ngSearchFn"
           ... </ng-select>
```
```
public ngSearchFn = (searchTerm: string, item: any) => {
  if (this.ngSelectGroupBy) {
    return item[this.ngSelectGroupBy].toLowerCase().indexOf(searchTerm) > -1 || item[this.ngSelectBindLabel].toLowerCase().indexOf(searchTerm) > -1;
  } else {
    return item[this.ngSelectBindLabel].toLowerCase().indexOf(searchTerm) > -1;
  }
}
```

**Comment by pavankjadda** [comment]
> I made a workaround for this.
> 
> ```
> 
> <ng-select ... 
> 
>            [bindLabel]="ngSelectBindLabel"
> 
>            [groupBy]="ngSelectGroupBy"
> 
>            [searchFn]="ngSearchFn"
> 
>            ... </ng-select>
> 
> ```
> 
> ```
> 
> public ngSearchFn = (searchTerm: string, item: any) => {
> 
>   if (this.ngSelectGroupBy) {
> 
>     return item[this.ngSelectGroupBy].toLowerCase().indexOf(searchTerm) > -1 || item[this.ngSelectBindLabel].toLowerCase().indexOf(searchTerm) > -1;
> 
>   } else {
> 
>     return item[this.ngSelectBindLabel].toLowerCase().indexOf(searchTerm) > -1;
> 
>   }
> 
> }
> 
> ```

For now use this workaround
