### ISSUE TITLE
Class isn't propagated to dropdown-panel via [ngClass] directive

### ISSUE THREAD

**Issue by ndovnar** [ng-select/ng-select#1627]
**Describe the bug**
Class isn't propagated to the dropdown-panel via [ngClass] directive

**Reproducible example**
https://stackblitz.com/edit/angular-ivy-9pxhre?file=src%2Fapp%2Fapp.component.html

**To Reproduce** 
Steps to reproduce the behavior (if example is not provided):
Just check that dropdown-panel doesn't have the class `test`

**Expected behavior**
The class from `ng-select` should be propagated to the dropdown-panel even via `[ngClass]` directive 

**Additional context**
I didn't get the answer here https://github.com/ng-select/ng-select/issues/1619, so I duplicated it.

**Comment by pboutin44** [comment]
Hello If the problem is to select dropdown-panel with css when appendTo is activated, I propose a pr that should solve the problem: https://github.com/ng-select/ng-select/pull/2187
