### ISSUE TITLE
Flexible autocomplete property distinctUntilChanged() does not exist on type Observable<string>

### ISSUE THREAD

**Issue by abelardolg** [ng-select/ng-select#163]
Hi,
I wanted to reproduce this example:
https://plnkr.co/edit/KFpvA9?p=preview
but this message was showed:
'Property distinctUntilChanged() does not exist on type Observable<string>'

### Expected behaviour
It shouldn't show any error message

### Actual behaviour
It gives this message: error TS2339: Property distinctUntilChanged() does not exist on type Observable<string>' 
If it is removed, another similar message is showed but with 'switchMap' property.

### More Info
ng-select version: @ng-select/ng-select@0.12.0

browser: Versión 62.0.3202.94 (Build oficial) (64 bits) Google Chrome

reproducible in demo page: NO

**Comment by varnastadeus** [comment]
Hi, if you are using newer angular version, RxJS introduced lettable operators so you need to use different syntax.
You can read more here: https://blog.angularindepth.com/rxjs-understanding-lettable-operators-fe74dda186d3
