### ISSUE TITLE
ng-select is not updating it is items while i am searching with numbers

### ISSUE THREAD

**Issue by santhoshraju621** [ng-select/ng-select#1632]
Hii
ng-select is not updating the items. while I am searching with the numbers. same is updating while i am searching with text.

here is the below code. I used in my project

`<ng-select [items]="loc" [loading]="preferredLocationsLoading" bindLabel="text" bindValue="text"  
                  placeholder="Pref Locations" [searchable]="true"
                  [closeOnSelect]="true" [multiple]="false"
                  (input)="getPrefLocations($event.target.value)" formControlName="filterCity" >`

here is the code to fetch results from API.

`getPrefLocations(cities) {
      this.preferredLocationsLoading = true;
     this.loc = [];
      this.multikeyservice.getPrefereedCities(cities, this.paramscountryCode).subscribe(res => {
        res.body.map.preferredCities.forEach(element => {
           this.loc = [...this.loc, element];
         });
        this.preferredLocationsLoading = false;
      });
  }`

the same code is working fine for while I am giving input as text Ex: 'new york' and not working for text Ex: '12345'.

Please help me to resolve the issue.
Thnaks in Advance.

**Comment by dazzzed** [comment]
@santhoshraju621 I'm facing the same issue, can you share how did you manage to fix it?

**Comment by dazzzed** [comment]
I fixed this by passing my custom [searchFn] that would return the current items list as I am making a custom search and updating the list in the (search) event, this way we override the ng-select filtering functions and it works.
