### ISSUE TITLE
How to change the style of the select field when an option is selected

### ISSUE THREAD

**Issue by axell9641** [ng-select/ng-select#1634]
When I select an option in the select I got this blue outline in the select component
![image](https://user-images.githubusercontent.com/637311/83360272-a6849880-a345-11ea-9134-292a80da90d9.png)

I need to customize this to match the style in my other components. 
I tried changing the outline property in the two classes you mention in the Custom Styles section, but nothing happens

Is there any way I can change the color and size of that blue outline? What class should I use?

Thanks.

**Comment by varnastadeus** [comment]
https://github.com/ng-select/ng-select#custom-styles

**Comment by arlopezg** [comment]
For anyone having issues specifically with this highlight, you just got to override the `box-shadow` rule for this selector

```css
.ng-select.ng-select-focused:not(.ng-select-opened)>.ng-select-container
```

I thought I was going crazy while looking for borders or outlines.
