### ISSUE TITLE
Preload default option with async / typeahead

### ISSUE THREAD

**Issue by cristiammercado** [ng-select/ng-select#1636]
**Describe the bug**
Hi,

I'm not sure if it's a bug or not, but I really can't figure out how to preload information in the select from an object list property associated with `bindValue`. This list is loaded via async with an observable and it has an asynchronous search with typeahead. 

I am using `ReactiveFormsModule` for the form and all the examples are done with `[(ngModel)]`, but according to Angular compiler: 

> Support for using the ngModel input property and ngModelChange event with reactive form directives has been deprecated in Angular v6 and will be removed in Angular v7.

When in the formControlName of the select property I set the ID of the object that I want to render initially, it shows `null, undefined` in my specific case, indicating that te component can't find the associated object.

I need a little help with this issue. Thank you.

**Reproducible example**
[Stackblitz link](https://stackblitz.com/edit/angular-ngselect-bug) which reproduces described behaviour

**To Reproduce** 
1. Create form with default data (in this case, the `id`)
2. Wait for the form to render the option selected by default.
3. The component doesn't correctly render the element associated to the ID.

**Expected behavior**
The component correctly render the element associated to the ID.

**Screenshots**
Current:
![image](https://user-images.githubusercontent.com/4806666/83695467-b4dde900-a5bf-11ea-8fa3-3bc15a8e1a08.png)

Expected:
![image](https://user-images.githubusercontent.com/4806666/83695510-cd4e0380-a5bf-11ea-90b5-39d5f47a449f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome (or any modern browser)
 - Version 83.0.4103.61

**Comment by varnastadeus** [comment]
when you are building your observable you should start with not an empty array - `of(myCityArray),`

**Comment by alexartwww** [comment]
@varnastadeus  Could you provide code example?

E.g. I have typeahead observable and of(...) observable for preselected items. It's still not working properly.
