### ISSUE TITLE
Deburr support on search results

### ISSUE THREAD

**Issue by segux** [ng-select/ng-select#1638]
**Is your feature request related to a problem? Please describe.**
Im using some latin languages on my app that needs searches with or without some special characters like : à ò ó í ô....
Should be nice to deburr like lodash do for all searches.

  
**Describe the solution you'd like**
Using lodash deburr or simply applying a custom method for deburr.
https://lodash.com/docs/4.17.15#deburr

**Describe alternatives you've considered**
With custom search i can do the implementation, but if i have 100 ng-selects on my app and all selects can be dynamically changed on different languages with i18n.
 It's hard to be controllable, and a bad idea to implement search custom method on every ng-select.

**Comment by varnastadeus** [comment]
I am not sure why you are writing this issue since it was supported from the beginning by default. 
![image](https://user-images.githubusercontent.com/17824796/83939963-a246f800-a7e9-11ea-9828-66d911aa5d4d.png)

**Comment by segux** [comment]
Well, you have support to remove diacritics on search input string. 

But what happens when binded label has diacritics?
You dont have support to that.

For example:

I tyed doza

and one results have Mendôza
