### ISSUE TITLE
Hiding the selected elements from the dropdown

### ISSUE THREAD

**Issue by ShinDarth** [ng-select/ng-select#164]
is there a way to hide the already-selected items from the dropdown menu?

**Comment by anjmao** [comment]
Hi @ShinDarth, currently it is not supported, but it would be a nice feature to have a flag like `showSelectedOptions` which is be default true and if setting it to false it will hide multiselect items from drodpwn.

**Comment by shyamal890** [comment]
+1

**Comment by BenjaminLefevreGithub** [comment]
I agree, easy to achieve. 

I would suggest to not display selected items by defaut (showSelected="false") which makes senses since this is the usual behaviour. Example: http://jedwatson.github.io/react-select/

**Comment by shyamal890** [comment]
@anjmao This a must needed feature. Would appreciate your thoughts.

**Comment by BagumEpmak** [comment]
While this most expected feature not implemented you can try this ugly workaround in your main css file:
.ng-select-dropdown-outer .ng-select-dropdown .ng-option.selected {
    display: none;
}
