### ISSUE TITLE
Selected Value not displayed after Filtering on Mobile

### ISSUE THREAD

**Issue by Friedrich-Mocker** [ng-select/ng-select#1642]
**Describe the bug**
When filtering on mobile chrome and then selecting a value, the class `ng-select-filtered` stays on and sets `visibility: hidden` on the selected value. This is due to `(compositionend)="onCompositionEnd(searchInput.value)"` not firing when typing. It only fires when you close the keyboard on mobile which you obviously don't.
**Reproducbile example**
Filter List on mobile then select a value. Value is not visible.

**To Reproduce** 
Steps to reproduce the behavior (if example is not provided):
1. Clone Repo and Run `ng serve --host 0.0.0.0`. Remote Debug your Android device.
2. first dropdown
3. type 'k'
4. select any value, before closing your keyboard

**Expected behavior**
The selected value should be visible after selection.
**Screenshots**
<img width="617" alt="Screenshot 2020-06-07 at 02 16 28" src="https://user-images.githubusercontent.com/19273717/83957088-e9be9a00-a864-11ea-9160-e3a5ff3b1671.png">

**Smartphone (please complete the following information):**
 - Device: Samsung S10 Plus, OnePlus X
 - OS: android
 - Browser chrome
 - Version latest

**Additional context**
I could fix this by replacing 
`(compositionend)="onCompositionEnd(searchInput.value)"` with
`(input)="onCompositionEnd(searchInput.value)"`in `src/ng-select/lib/ng-select.component.html`

**Comment by Friedrich-Mocker** [comment]
*Which is obviously not a real "fix" :)

**Comment by hadaj** [comment]
> *Which is obviously not a real "fix" :)

I still have the same issue :)

**Comment by hadaj** [comment]
> **Describe the bug**
> When filtering on mobile chrome and then selecting a value, the class `ng-select-filtered` stays on and sets `visibility: hidden` on the selected value. This is due to `(compositionend)="onCompositionEnd(searchInput.value)"` not firing when typing. It only fires when you close the keyboard on mobile which you obviously don't.
> **Reproducbile example**
> Filter List on mobile then select a value. Value is not visible.
> 
> **To Reproduce**
> Steps to reproduce the behavior (if example is not provided):
> 
> 1. Clone Repo and Run `ng serve --host 0.0.0.0`. Remote Debug your Android device.
> 2. first dropdown
> 3. type 'k'
> 4. select any value, before closing your keyboard
> 
> **Expected behavior**
> The selected value should be visible after selection.
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> <img alt="Screenshot 2020-06-07 at 02 16 28" width="617" src="https://user-images.githubusercontent.com/19273717/83957088-e9be9a00-a864-11ea-9160-e3a5ff3b1671.png">
> 
> **Smartphone (please complete the following information):**
> 
> * Device: Samsung S10 Plus, OnePlus X
> * OS: android
> * Browser chrome
> * Version latest
> 
> **Additional context**
> I could fix this by replacing
> `(compositionend)="onCompositionEnd(searchInput.value)"` with
> `(input)="onCompositionEnd(searchInput.value)"`in `src/ng-select/lib/ng-select.component.html`

I still have the same issue :)

**Comment by vltansky** [comment]
#1556 fixes this
#1451 related

CSS solution:
```css
.ng-select.ng-select.ng-select-single.ng-select-filtered:not(.ng-select-opened) .ng-select-container.ng-has-value .ng-value-container .ng-value{
            visibility: visible;
}
```
