### ISSUE TITLE
Can custom tag be made selectable?

### ISSUE THREAD

**Issue by poddarkhushbu07** [ng-select/ng-select#1646]
In ng-select, custom tags are not editable or selectable after tags are added.

It will be a nice and helpful feature if we can at least select the tag data. 
Currently tag text is **not** selectable.

![ng-select](https://user-images.githubusercontent.com/31128078/84265516-94260e00-ab40-11ea-9883-a3b8f3218116.gif)

**Comment by varnastadeus** [comment]
why it should be selectable? what should happen when you select an item?

**Comment by Chevindu** [comment]
I think he might be referring to highlighting the text in a tag, a wild guess.

**Comment by poddarkhushbu07** [comment]
@varnastadeus While editing the form having  ng-select tags, if values are larger and users want to edit a single tag value from multiple tags then user have to remove that whole tag and add new tag with edited value. Instead, if at least tags are selectable then user won't have to type whole value again. It would be of help in case of multiple tags.

**Comment by olicooper** [comment]
For my use-case, I would like a click/highlight event to be raised when I click the item so that I can bring up a modal to customise additional meta data relating to the selected item.
