### ISSUE TITLE
Extraneous properties added to object values

### ISSUE THREAD

**Issue by rdicroce** [ng-select/ng-select#165]
### Expected behaviour
I have a ng-select set up where the ngModel is the whole object, and bindLabel is set so the label is a string within the object. When I select a value, the object emitted by ngModelChange should exactly match the object I provided as part of the items list.

### Actual behaviour
The value emitted by ngModelChange contains extra unwanted properties like "index" and "selected".

### More Info
ng-select version: 0.12.0

browser: FF 57

reproducible in demo page: Yes. Go to "Filter and autocomplete". Under "Default search", select any name from the list and you'll see that extra properties are added. "Custom search" also demonstrates the problem, as the initial value when the page loads doesn't have the extra properties, but then as soon as you do something to either input (even just focusing the field), the extra properties are added.

**Comment by varnastadeus** [comment]
Hi, yes, it is known issue and will be fixed with #159
