### ISSUE TITLE
Unable to disable ng-select with reactive forms

### ISSUE THREAD

**Issue by trdyer** [ng-select/ng-select#1650]
**Describe the bug**
When using reactive forms it is not possible to disable the ng-select control

**Reproducbile example**
https://w4fkwp.run.stackblitz.io

**To Reproduce** 
This is a minor change from the multiselect/disabled example on the demo site found here: https://awgkph.run.stackblitz.io

**Expected behavior**
When setting `[disabled]='true'` i expected the control to become disabled

**Desktop (please complete the following information):**
 - OS: mac OSX
 - Browser Chrome
 - Version 83

**Comment by varnastadeus** [comment]
When you are using reactive forms, you should disable in reactive way. There is example on demo page
