### ISSUE TITLE
Dropdown list is not displayed at the bottom of a pop-up

### ISSUE THREAD

**Issue by HenningH-DEV** [ng-select/ng-select#1653]
**Describe the bug**
With ng-select as the lowest component on a pop-up, the result list is not displayed if `dropdownPosition="auto"` and `dropdownPosition="top"` are selected. Only with `dropdownPosition="bottom"` it is visible. In this case, a part of the list is cut off by the lower edge of the browser and is therefore not visible. The ng-select is located in a separate `<div class="row">` in the component.

**Reproducbile example**
Screenshots instead of an example

**To Reproduction** 
Create an ng-select with `dropdownPosition="auto"` in a row at the bottom of the component, so that the result list cannot be displayed completely downwards. In this case the list is not displayed at all, instead of above the input field.

**Expected behavior**
Display of the result list above the input field

**Screenshots**
`dropdownPosition="auto"`:
![image](https://user-images.githubusercontent.com/67090273/84991254-90991500-b146-11ea-8b73-58f0752589af.png)

`dropdownPosition="bottom"`:
![image](https://user-images.githubusercontent.com/67090273/84991268-97278c80-b146-11ea-9eaf-80394cf2ac46.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Latest stable version of Chrome 
 - Version 4.0.1 (same problem with 3.7.3)

**Additional context**
None

**Comment by DepickereSven** [comment]
@HenningH-DEV could you give some more details about how you set up your element?
What appendTo property did you use?

**Comment by HenningH-DEV** [comment]
We have the ng-select in a separate component. I'm hoping that the code from that will help.

```
<div [formGroup]="formGroup">
    <label for="{{name}}">{{label}}
        <span [hidden]="!isRequired()" class="text-danger">*</span>
    </label>

    <div class="icon icon-info-grey icon-20 align-text-bottom ml-2"
         [hidden]="!showInfoIcon" [popoverTitle]="infoHeader" [ngbPopover]="infoText"
         container="body">
    </div>

    <ng-select #input class="xy-disableable"
               (search)="field.search$.next($event.term)" [items]="field.suggestions"
               (clear)="field.search$.next('')"
               (open)="field.search$.next('')"
               [ngClass]="{'is-ng-invalid': showRequiredField && !isValid()}"
               [addTag]="allowAdd"
               [addTagText]="'AddValue' | translate"
               [appendTo]="'body'"
               [notFoundText]="allowAdd ? undefined : 'NotFound' | translate"
               dropdownPosition="auto"
               virtualScroll="true"
               formControlName="{{name}}" id="{{name}}" labelForId="{{name}}">
        <ng-template let-index="index" let-item="item" let-search="searchTerm" ng-option-tmp>
            <span [ngOptionHighlight]="search">{{item}}</span>
        </ng-template>
    </ng-select>

    <small [hidden]="isValid() || !showRequiredField"
           class="text-danger">{{invalidErrorText | translate}}</small>
</div>
```

**Comment by ikbenignace** [comment]
I also have the same issue here
