### ISSUE TITLE
Allow custom value not inside [items]

### ISSUE THREAD

**Issue by f3l1xss** [ng-select/ng-select#1655]
Hi,
At the moment I cannot find any way to let User type any custom value and validate based on
that. My requirement is that User should be able to type any value (as if its a regular input text) and also select value from dropdown and validation should be applied to whatever value is at input box.

Currently, validation is only applied once item is selected from dropdown.

Edit: I have seen tagging feature but it would still require enter to confirm the value, I would prefer user not having to press enter

**Comment by baylrock** [comment]
+1 It would be good option to have.

To make it work right now I have to add user input as first element of items array to make it work.

```ts
    this.typeAhead.pipe(
      debounceTime(200),
      distinctUntilChanged(),
      tap(() => this._loading = true),
      switchMap(searchString =>
        this.searchService.search(searchString)
          .pipe(
            map(response => {
              if (response.results.find(user => user.name.toLowerCase() == searchString.toLowerCase())) {
                return response.results
              }
              return [{name: searchString} as Item, ...response.results];
            }),
            catchError(() => of([{name: searchString} as Item]))
          )
      ),
      tap(() => this._loading = false)
    )
```

**Comment by baylrock** [comment]
**Use case example.**

Feature requirements I have in real app:
- typeahead, single value select, dropdown
- items of dropdown are dynamic, e.g. usernames of a huge user pull 
- it is impossible to preload entire user pull for dropdown (natural limits, e.g. typeahead value can match more items than backend can return)

In my specific case, output of ng-select used as search condition for other thing, and input string can be used as well as fully matched item from ng-select.
Tagging feature of ng-select does almost what I need, but 
 - it adds tags in the end
 - user should be able just press (enter) to select string as valid value (this is why user input added as first item of array)
