### ISSUE TITLE
Ng-select placeholder alignment issue

### ISSUE THREAD

**Issue by poddarkhushbu07** [ng-select/ng-select#1657]
I am using ng-select with autocomplete feature. But if I click on ng-select input and again click outside without typing anything (see attached GIF), placeholder does not get reset to original (centre) position. I tried looking at CSS properties but I found nothing which is affecting placeholder position after click. And also, I verified the value of ng-select. It is undefined both the times.

_Value of search is **undefined** before and after clicking on input._

![ng-select-placeholder](https://user-images.githubusercontent.com/31128078/85124995-79425080-b248-11ea-90e0-92fecefb0dad.gif)

`<ng-select
        [(ngModel)]="search"
        [items]="searchResultList$ | async"
        [minTermLength]="3"
        [typeahead]="result$"
        class="wid-240 shadow-none h-auto"
        placeholder="Search Here..." typeToSearchText="Enter 2 or more characters to Search" #seacrhInput>`

**Comment by poddarkhushbu07** [comment]
This issue is fixed. I changed the line-height property.

**Comment by sgbenav** [comment]
@poddarkhushbu07 awesome! May I ask where did you change the line-height and what value did you use? Thanks!
