### ISSUE TITLE
Binding items not updated unless it's new array

### ISSUE THREAD

**Issue by ShinDarth** [ng-select/ng-select#166]
```
<ng-select [items]="myArray"></ng-select>
```

### Expected behaviour

When you add/remove items to `myArray`, the changes should be detected and reflected in the `ng-select`.

### Actual behaviour

If the items contained in `myArray` change (remove or add items), the changes are not reflected to the `ng-select`. 

A workaround is to first change `myArray` contents and then do `this.myArray = this.myArray.slice()`. This will generate a **new** array, so the changes are finally detected.

### More Info
ng-select version: `^0.8.0`
browser:  Chrome

reproducible in demo page: [NO]

**Comment by varnastadeus** [comment]
Hi @ShinDarth, it works by design, please read https://github.com/ng-select/ng-select#change-detection why this works as you described.

**Comment by ShinDarth** [comment]
ok, thanks for your answer

**Comment by GondilOndro** [comment]
What about changing items in array?
I have something like this:
```
onSelectAdd($event) {
  for (let item in this.myItems) {
    if (item.value !== $event.value && item.concurrentGroup === $event.concurrentGroup && !item.disabled) {
      item.disabled = !item.disabled;
    }
  }
}
```
Basically when some item in ng-select is selected i need to check all other items for property concurrentGroup and disable it. concurrentGroup is used for restricting only one item from one concurrentGroup could be selected. However these items are not detected that they was disabled.

**Comment by GondilOndro** [comment]
Finally was successfull with following. Is it correct approach? 
```
onSelectAdd($event) {
    let tmp = [];

    this.myItems.forEach((item: any) => {
      if (item.value !== $event.value && item.concurrentGroup === $event.concurrentGroup && !item.disabled) {
        item.disabled = true;
      }
      tmp.push(item);
    });

    this.myItems= [...tmp];
  }
```
