### ISSUE TITLE
Model value does not get cleared, if selected item is removed from [items]

### ISSUE THREAD

**Issue by mmmichl** [ng-select/ng-select#1661]
Have a ng-select with a list of items. Select a item from the list. Now update the [items] list where the selected item is not present anymore.

I would expect that the selected value is cleared, as it is not an option anymore. This is of course only for the cases, where you have to select an item from the list.

Example:
https://stackblitz.com/edit/angular-bnj9h5-ubhgdp
Wait for 10 seconds to see the effect. The lists get updated after 4 sec and again after additional 4 seconds. After the second update I would expect the value to be cleared.

Maybe a duplicate of #1651
Maybe related to #1587

**Comment by varnastadeus** [comment]
I think there was an issue some time ago about this, and the conclusion was that changing `[items]` should not impact selected item and I don't see any valid reason for that to change. You can check if your new items contain selected value, and clear model if it is not.

**Comment by razvan-urs** [comment]
@varnastadeus I find this to be quite important. Even the <select> tag works like that: if the selected value is not in the options list anymore it gets deselected or automatically selects the first option. Is there a chance to get this feature to ng-select?

**Comment by razvan-urs** [comment]
@varnastadeus Is there a chance to get this feature? Clearing selection if it's no longer in the [items] list
