### ISSUE TITLE
Angular 10 Support

### ISSUE THREAD

**Issue by pavankjadda** [ng-select/ng-select#1662]
**Is your feature request related to a problem? Please describe.**
When I upgrade my project to Angular 10 I see following warning  message
```
Package "@ng-select/ng-select" has an incompatible peer dependency to "@angular/common" (requires ">=9.0.0 <10.0.0", would install "10.0.0")
Package "@ng-select/ng-select" has an incompatible peer dependency to "@angular/core" (requires ">=9.0.0 <10.0.0", would install "10.0.0")
Package "@ng-select/ng-select" has an incompatible peer dependency to "@angular/forms" (requires ">=9.0.0 <10.0.0", would install "10.0.0")

```
**Describe the solution you'd like**
Update **ng-select** package to support Angular 10

**Comment by andrejm7** [comment]
yes.. i need too

**Comment by lWeRl** [comment]
yes it will be nice

**Comment by CesarD** [comment]
I need this as well.. Trying to upgrade to Angular v10.

**Comment by harunergul** [comment]
I want to migrate our project to Angular v10.  Support for v10 will be very good for us.

**Comment by Compactis** [comment]
yes.. i need too

**Comment by andrejm7** [comment]
need too suport boostrap 4.5

**Comment by fjc2112** [comment]
I have been using this library for a long time. Today I started a new project with Angular 10 and I found that it does not support it.
I really love this library and refuse to use another one.

**Comment by hisham** [comment]
ng-select is still functional with angular 10 but you just see this warning right? I haven't run into any functionality issues with angular 10.

**Comment by harunergul** [comment]
> ng-select is still functional with angular 10 but you just see this warning right? I haven't run into any functionality issues with angular 10.

I hava problem with projected content

**Comment by fjc2112** [comment]
> ng-select is still functional with angular 10 but you just see this warning right? I haven't run into any functionality issues with angular 10.

You're right, I don't know what I did wrong the first time, but now I tried again and it worked. I'm happy :D

**Comment by Rene4100** [comment]
The ng-option-highlight could also use an upgrade, as it does not go well with Ivy. 
I get the following error:

```
ERROR in node_modules/@ng-select/ng-option-highlight/lib/ng-option-highlight.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

This likely means that the library (@ng-select/ng-option-highlight) which declares NgOptionHighlightModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
```

**Comment by jcmag** [comment]
> The ng-option-highlight could also use an upgrade, as it does not go well with Ivy.
> I get the following error:
> 
> ```
> ERROR in node_modules/@ng-select/ng-option-highlight/lib/ng-option-highlight.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.
> 
> This likely means that the library (@ng-select/ng-option-highlight) which declares NgOptionHighlightModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
> ```

I've just installed ng-select and I have the same error...
my package.json has: 

`  "@ng-select/ng-option-highlight": "0.0.5", `
`  "@ng-select/ng-select": "^5.0.7",`

What am I doing wrong?
