### ISSUE TITLE
How to set an entire group as the default value

### ISSUE THREAD

**Issue by githubkuni** [ng-select/ng-select#1666]
I have setup multiple select with checkboxes as below

 <ng-select [items]="availableOrganizations" [multiple]="true" bindLabel="Name"
                            [selectableGroup]="true" [closeOnSelect]="false" bindValue="Id" groupBy="parentOrg"
                            [(ngModel)]="selectedOrganizations">
                            <ng-template ng-optgroup-tmp let-item="item" let-item$="item$" let-index="index">
                                <input id="item-{{index}}" type="checkbox" [ngModel]="item$.selected" /> {{item.parentOrg}}
                            </ng-template>
                            <ng-template ng-option-tmp let-item="item" let-item$="item$" let-index="index">
                                <input id="item-{{index}}" type="checkbox" [ngModel]="item$.selected" />
                                {{item.Text}}
                            </ng-template>
                        </ng-select>

 availableOrganizations = [
    {Id: 1, Name: 'COM1', ParentOrg: 'ALL ORGS'},
    {Id: 2, Name: 'COM2', ParentOrg: 'ALL ORGS'},
    {Id: 3, Name: 'COM3', ParentOrg: 'ALL ORGS'},
    {Id: 4, Name: 'COM4', ParentOrg: 'ALL ORGS'},
    {Id: 5, Name: 'COM5', ParentOrg: 'ALL ORGS'},
....
....
....
  {Id: 100, Name: 'COM100', ParentOrg: 'ALL ORGS'},
  ];

   
Its works perfectly. But I am having trouble to set default value on page load.

I need to set the entire group to be the default value. It shows all the org checkboxes as seleted.
But it show the tags for all the orgs instead of only "ALL ORGS" tag.

Or maybe it is possible to add a tag using addTag "ALL ORGS".

Please let me know how to achieve this.

**Comment by varnastadeus** [comment]
please check demo page, there are examples of this.

**Comment by mikila85** [comment]
Thanks for putting a link.. now everyone that gets here can find it quickly

**Comment by mikila85** [comment]
if somone reaches here, this is the example: https://github.com/ng-select/ng-select/blob/master/src/demo/app/examples/group-selectable-example/group-selectable-example.component.ts

there is a bug in group selection when selecting a group, the unselecting an element then reselecting it .. it no longer says "group name" but.. 38 elements selected (even though all of the group is selected...) boo component..

**Comment by mikila85** [comment]
if somone reaches here, this is the example: https://github.com/ng-select/ng-select/blob/master/src/demo/app/examples/group-selectable-example/group-selectable-example.component.ts

they force you to implement the compare mechanism by your self
