### ISSUE TITLE
How to use FormArray in ng-select as form data input.

### ISSUE THREAD

**Issue by impulsenok** [ng-select/ng-select#1667]
**Describe the bug(request)**
I wanna to find out if i'm able to use FormArray as input in ng-select. 

**Additional context**
I mean i have FormArray-type 'conditionValues' formControl, and i wanna ng-select to work with it, each formArray item(formControl) as separate ng-select list item.
If u have any examples, just share them with me.

I already read about similar title issues, but there are separate ng-selects which are collecting data to one formArray(not my case)

**Comment by varnastadeus** [comment]
please use StackOverflow for this type of question

**Comment by impulsenok** [comment]
There is nothing about such issue on stuckOverflow. That's why i'm here.
