### ISSUE TITLE
Can't bind to 'minTermLength' since it isn't a known property of 'ng-select'

### ISSUE THREAD

**Issue by Jai-Kumaresh** [ng-select/ng-select#1672]
`Can't bind to 'minTermLength' since it isn't a known property of 'ng-select'`

I have the above issue and I can't use the 'minTermLength' props

Anyone have solution kindly tell me.

**Comment by varnastadeus** [comment]
check the version it was released, probably you are using old one.

**Comment by jessemorton** [comment]
@varnastadeus I don't see `minTermLength` shown in the change log.

**Comment by jessemorton** [comment]
But now I see it at https://github.com/ng-select/ng-select/commit/b06fc5fd7a26e89f224f5fd9ff74f79e14259531
