### ISSUE TITLE
Template for input search, when we enable searchable

### ISSUE THREAD

**Issue by CrackerakiUA** [ng-select/ng-select#1675]
**Is your feature request related to a problem? Please describe.**
Template for input search to have custom back-end search would be nice to have.

**Describe the solution you'd like**
I guess one more template which would replace input where we show when we enable option searchable.

**Describe alternatives you've considered**
I found template `ng-typetosearch-tmp` which looks to not replace input search.

**Comment by varnastadeus** [comment]
There is example in demo page with custom search control. Also, to have custom backend search you don't need a template, you should use typeahead which is available in demo page as well.
