### ISSUE TITLE
Custom scrollbar for NgDropdownPanelComponent

### ISSUE THREAD

**Issue by canqel** [ng-select/ng-select#1684]
**Is your feature request related to a problem? Please describe.**
I would like to use a custom scrollbar for the select's dropdown. I'm using `ngx-scrollbar` library (https://github.com/MurhafSousli/ngx-scrollbar/) in my project and after some analysis, I don't think it's currently possible.

![image](https://user-images.githubusercontent.com/45739053/87772071-817ab500-c821-11ea-92b3-19da84c7246a.png)

**Describe the solution you'd like**
I think there would need to be a possibility to pass a template to the `ng-select` component defining the container element for:
```
<div #scroll class="ng-dropdown-panel-items scroll-host">
   ...
</div>
```
(it's a fragment of NgDropdownPanelComponent)

However, I suppose it's not that simple. Perhaps, there's another possibility to achieve that.

**Additional context**
This is how looks the usage of `ngx-scrollbar` library:
```
<ng-scrollbar>
  <!-- content -->
</ng-scrollbar>
```

**Comment by gongAll** [comment]
I implemented something similar which sort of works, like so:

First create the directive
```
import {Directive, ElementRef, Input} from "@angular/core";
import OverlayScrollbars from 'overlayscrollbars';

@Directive({
  selector: '[customScrollDetector]'
})
export class ScrollDetectorDirective {
  @Input() scrollSelectors: string[] = [];
  @Input() configs: MutationObserverInit = {
    childList: true, subtree: true, attributes: true
  };
  private observer: MutationObserver;

  constructor(private elRef: ElementRef) {
  }

  ngAfterViewInit() {
    this.observer = new MutationObserver(mutations => {
      mutations.forEach(() => {
        if (!this.scrollSelectors
          || !Array.isArray(this.scrollSelectors)
          || !this.scrollSelectors.length) {
          return;
        }

        this.scrollSelectors.forEach(selector => {
          OverlayScrollbars(document.querySelectorAll(selector), {});
        });
      });
    });

    this.observer.observe(this.elRef.nativeElement, this.configs);
  }
}
```

Then use it like so:
```
<ng-select customScrollDetector [scrollSelectors]="['.ng-dropdown-panel-items']" ... >
</ng-select>
```
There is 1 major downsides to this approach: virtualScroll: true seems to break with it.

Hope this helps you.

**Comment by MKaranusic** [comment]
Even though the issue is closed I feel like this is a valuable question.
Scrollbar still remains one of the browser specific elements difficult to style for browsers not suporting 
[::-webkit-scrollbar selector](https://caniuse.com/?search=%3A%3A-webkit-scrollbar) (mozilla and IE11).

Workaround is a javascript library scrollbar implementation.
However, unfortunately there are no resources on the matter.

Any ideas or help would be greatly appreciated :)
