### ISSUE TITLE
How to show more rows

### ISSUE THREAD

**Issue by jjfellers** [ng-select/ng-select#1687]
With these options, it only shows 6 rows (with scroll). If I wanted to change the size, so it shows, say 10 rows, how would I accomplish that?
`<ng-select [items]="InventoryItems"
    #select
    bindLabel="DESCRIPTION"
    dropdownPosition="auto"
    labelForId="DESCRIPTION"
    placeholder="Select Item(s)"
    [multiple]="true"
    [hideSelected]="true"
    [closeOnSelect]="false"
    [virtualScroll]="true"
    [(ngModel)]="SelectedItems">`

**Comment by varnastadeus** [comment]
just increase height of dropdown panel using css.
