### ISSUE TITLE
ngSelect is not hiding the selected value if the items is set programatically on initial load ?

### ISSUE THREAD

**Issue by dheerajm91** [ng-select/ng-select#1689]
Hi,

**Scenario 1:  [Works fine using [items] property in Html ]**
Lets say service - "API-1" gives me the value to bind the ngModel for ngSelect. 
// Once data from API-1 (service call) is received it sets the"this.selectedValue" to bind the ngmodel:

`Ex: this.selectedValue = API-1.selectedValue; `

now Lets say that service - "API-2" gives me the data to bind the drop down values.
// Once dropdown data from API-2 (service call) is received it sets the"this.items" to set it to [items] property of ng-select:

 `Ex: this.items = API-1.dropdownData; `

Its works fine and dropdown also hides the selected values and  if i use it like below:

HTML CODE:
`
        <ng-select name="select1" placeholder="Select option"
          [items]="items"
          [(ngModel)]="selectedValue"
          bindLabel="displayName"
          multiple="true" 
          hideSelected="true" 
          appendTo="body">
        </ng-select>
`

**Scenario-2: [Not working if dropdown data is set programmatically - Selected value is not hiding from the dropdown]**

 I have a use case where i will have to set the "[items]/ dropdown data" programmatically and not through HTML.

Html code: Not using [items] property for dropdown and will use "ngSelectReferenceEle" to set the dropdown data.
`
        <ng-select name="select1" placeholder="Select option"
          #ngSelectReferenceEle
          [(ngModel)]="**selectedValue**"
          bindLabel="displayName"
          multiple="true" 
          hideSelected="true" 
          appendTo="body">
        </ng-select>
`

Stackbiltz => Reproducible example : https://stackblitz.com/edit/dheeraj-ngselect-hide-reproducible

I believe that this is a bug as the change detection is not happening when the dropdown data is loaded programmatically. Please suggest if this can be considered as bug ?

Thanks,
DJ

**Comment by varnastadeus** [comment]
the methods you are using are not intended for public use unless you know what you are doing - use public api (https://github.com/ng-select/ng-select#api)  and it will work as expected

**Comment by SeanDKendle** [comment]
I'm using the public API and it's doing exactly what DJ reported. I have the items being filled using | async, and I'm binding the value on page load with ngModel.

First of all, I have to use a hack with a timeout to get the values to actually show up, and then once I do, the values are still available in the list of items, so you can add duplicate values.
