### ISSUE TITLE
'NgSelectModule' contains the error at @ng-select/ng-select/ng-select.ts(39,10).

### ISSUE THREAD

**Issue by iCodr8** [ng-select/ng-select#169]
I am running the following script to build my application for production:

```bash
ng build --environment=prod --aot=true --stats-json=true --output-path="dist/web" --base-href="/"
```

and get the following error:

```
ERROR in Error during template compile of 'SharedModule'
  Reference to a non-exported function in 'NgSelectModule'
    'NgSelectModule' contains the error at @ng-select/ng-select/ng-select.ts(39,10).
```

When I import the module only with `NgSelectModule` instead of `NgSelectModule.forRoot({...})` then it is working.

### More Info
ng-select version: 0.13.0

browser: none => console

reproducible in demo page: NO

**Comment by anjmao** [comment]
@iCodr8 Hi, can you paste how your shared module configuration looks ? Thanks :)

**Comment by iCodr8** [comment]
Thank you @anjmao
