### ISSUE TITLE
Unable to select and/or copy text in ng-value-label

### ISSUE THREAD

**Issue by jancoow** [ng-select/ng-select#1690]
Hi,

I'm using the example 'Tags without dropdown panel' from [https://ng-select.github.io/ng-select#/tags](https://ng-select.github.io/ng-select#/tags) in my application. However, as you can see in the example code, it's not possible to select and/or copy the text in the dynamically added tags. Why is this? I'm unable to find an option to disable this. Neither can I find any css styling to fix this.

**Comment by smile2014** [comment]
https://js.devexpress.com/Demos/WidgetsGallery/Demo/SelectBox/SearchAndEditing/Angular/Light/

**Comment by jancoow** [comment]
@smile2014 this has nothing to do with ng-select. I just want to select the text in the visible tags.
