### ISSUE TITLE
Can I use the clear icon to only clear the search string but not the selected options?

### ISSUE THREAD

**Issue by ilapavuluri** [ng-select/ng-select#1692]
**Describe the bug**
I want to clear the search string when the user clicks the 'x' icon. Based on current behavior 'x' icon only appears when I set 'clearable: true' and clicking that always resets the model. Is there a way to provide custom behavior to the 'x' icon?
**Reproducbile example**
[Example](https://stackblitz.com) which reproduces described behaviour

**To Reproduce** 
Steps to reproduce the behavior (if example is not provided):

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ilapavuluri** [comment]
Hi Team,

Any update on this?

Thanks
Ashok.

**Comment by ilapavuluri** [comment]
Hi Team,

Any update on this?

Thanks
Ashok.

**Comment by ilapavuluri** [comment]
@varnastadeus appreciate your thoughts on this.

Thanks
Ashok.

**Comment by varnastadeus** [comment]
You can't, icon is used to clear selected items

**Comment by ilapavuluri** [comment]
Thank you @varnastadeus for the quick response, I have a requirement where I need to only clear the search text not the selected items.
Is there any way to handle this?, something like adding another icon(custom icon) just to clear the searched text.
I tried to add an icon and able to clear the searched text, but unable to position it inside the search area.
Really appreciate your help.

Thanks
Ashok.
