### ISSUE TITLE
ios13 input chinese keyword Will produce two or three and more...

### ISSUE THREAD

**Issue by codyliou** [ng-select/ng-select#1694]
**Describe the bug**
ios13 input chinese keyword Will produce two or three

**Screenshots**
![image](https://user-images.githubusercontent.com/5194005/88379101-e2cbf680-cdd4-11ea-8d51-91669c856005.png)

is movie
http://cms.brightideas.com.tw/test/617276116.989040.mp4

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone X]
 - OS: [e.g. iOS 13]
 - Browser [safari, chrome]

**Comment by mfchk** [comment]
+ 1
MacOS Safari have such issue as well

**Comment by llccing** [comment]
```js
searchWhileComposing="false"
```
can resolve problem.
