### ISSUE TITLE
unable to add html inside ng-option-label span

### ISSUE THREAD

**Issue by raoulnair** [ng-select/ng-select#1698]
Not if this feature is supported but would like to have a way to add html element like span inside ng-option.
I tried to add a span inside ng-option but its not getting display in UI as well as DOM

Please find below stackblitz like for the same where I tried to implement the above scenario.
https://stackblitz.com/edit/angular-qxeabg-xagepf

**Comment by grzegorzsobocinski2397** [comment]
You can create custom template by following these instructions:
https://ng-select.github.io/ng-select#/templates

Here's an example with your custom span text: 
https://stackblitz.com/edit/angular-qxeabg-r6fdut

**Comment by raoulnair** [comment]
> You can create custom template by following these instructions:
> https://ng-select.github.io/ng-select#/templates
> 
> Here's an example with your custom span text:
> https://stackblitz.com/edit/angular-qxeabg-r6fdut

Thanks a lot
