### ISSUE TITLE
How to always have an "add New Item" being displayed?

### ISSUE THREAD

**Issue by williamxsp** [ng-select/ng-select#1701]
Im developing an application where a user can search for a name. They can pick one or add a new, even if its already exists.

When I type a name that doesnt have an exact match, it show the "add Item" option
![image](https://user-images.githubusercontent.com/3438192/89053023-f8897080-d32c-11ea-9f8e-0d992200e57b.png)

But when theres an exact match this option goes away
![image](https://user-images.githubusercontent.com/3438192/89052819-a7797c80-d32c-11ea-8928-cd4eb9551dd6.png)

**Comment by miki995** [comment]
@williamxsp Please, have a look at how to file an issue in the repository, then write a good one with example to reproduce, steps etc. Then I will help asap. Best.
