### ISSUE TITLE
When using compareWith, because model != item, how to get selected value from options

### ISSUE THREAD

**Issue by magoarcano** [ng-select/ng-select#1702]
I have a complex form with a dynamic length array of group of fields.
Each line has a ngSelect. The other fields of the line uses some information of the selected data in order to show different options or making calculations in different ways.
When submitting the form I save only some fields of the selected object in the ngSelect. So when loading the form with saved data, I use a `compareWith` function to show the correct item in the ngSelect.

Everything works fine, except I cannot get the whole data of the selected object so I can make the calculations in the other fields. With `field.value` I can get only the limited data I use to tell ngSelect what item is selected, not the item is selected.

I made a small [stackblitz here](https://stackblitz.com/edit/ngselect-comparewith?file=src%2Fbindings-default-example.component.ts).
Here you can see that if you select 'Flip flops' from the list, it shows all the fields of the selected object. But if you click on the button 'Choose flip flops', it shows only 'value' and 'label'. Is there some workaround to get all the data so I can make the calculations?
In my app options is an Observable.

Thanks!

**Comment by varnastadeus** [comment]
this is how ng-select works, it tries to map your selected value with items in the array based on `compareFn` but it doesn't modify the value you provide when the comparison was successful. You can map the value yourself if that is intended.
