### ISSUE TITLE
Multiselect checkbox does not work with reactive forms

### ISSUE THREAD

**Issue by ILL35T** [ng-select/ng-select#1703]
Multiselect checkbox does not work with reactive forms
See example here:
https://stackblitz.com/edit/ng-select-reactive-form-4ibic6

**Comment by imamasurya** [comment]
@ILL35T when you set multiple is `true` then you will get array as a result. So, in your case, you need to wrap your value in array when setValue in form.
see: 
https://stackblitz.com/edit/ng-select-reactive-form-skxmdx

hope this help you. cheers!

**Comment by miki995** [comment]
@ILL35T the issue does not follow the specs, please write steps to reproduce...

**Comment by varnastadeus** [comment]
just check the console, you are mixing reactive forms with ngModel

**Comment by Falx** [comment]
I had this issue too when using ReactiveForms, just adding the solution here:
Replace the ng-template with this:
```
 <ng-template ng-option-tmp let-item="item" let-item$="item$" let-index="index">
     <input id="item-{{index}}" type="checkbox" [checked]="item$.selected"/> {{item.id}}
 </ng-template>
 ```
 Note the `[checked]` instead of `[ngModel]`

**Comment by gaurav-sharma07** [comment]
> I had this issue too when using ReactiveForms, just adding the solution here: Replace the ng-template with this:
> 
> ```
>  <ng-template ng-option-tmp let-item="item" let-item$="item$" let-index="index">
>      <input id="item-{{index}}" type="checkbox" [checked]="item$.selected"/> {{item.id}}
>  </ng-template>
> ```
> 
> Note the `[checked]` instead of `[ngModel]`

But in that case, clicking on checkboxes doesn't work
