### ISSUE TITLE
15502 error 404 Not Found - GET https://registry.npmjs.org/@ng-select/ng-select/-/ng-select-4.0.0.tgz

### ISSUE THREAD

**Issue by babupca** [ng-select/ng-select#1705]
**The library is failing if i try to install, it is saying 404.**  There is some problem with your publishing, i request ng-select team to re-publish it, as the build is failing...

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@ng-select/ng-select/-/ng-select-3.7.3.tgz
npm ERR! 404
npm ERR! 404  '@ng-select/ng-select@3.7.3' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'CVX-Portal-Client'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\barumugam2\AppData\Roaming\npm-cache\_logs\2020-08-06T08_52_59_648Z-debug.log

![image](https://user-images.githubusercontent.com/2504343/89516256-d5ac0000-d7f5-11ea-87f2-4622af42582c.png)

![image](https://user-images.githubusercontent.com/2504343/89516988-beb9dd80-d7f6-11ea-95d8-93ab94154761.png)

**Comment by SerTsar** [comment]
Same problem

**Comment by varnastadeus** [comment]
it already works, seems like npm issue
