### ISSUE TITLE
Flickering on async loading of items

### ISSUE THREAD

**Issue by Schwankenson** [ng-select/ng-select#1711]
**Is your feature request related to a problem? Please describe.**
When using an observable to pass the items to ng-select, e.g. with `[items]="suggestions$ | async"`, there is always a short flickering of the suggestion dropdown which shows "loading", while the request is executed. This is not beautiful 

**Describe the solution you'd like**
It should be possible to have a input like "DoNotShowLoadingOnAsync", which disables this behaviour, and keeps the old suggestions in the dropdown until the new ones have been loaded.

**Describe alternatives you've considered**
My workaround is to just subscribe to the observable, and setting the local variable "suggestion" then, and passing this (not async) to ng-select. This does not show a flickering on change. But I have to pass an empty searchFn, to disable javascript filtering.

    <ng-select class='custom' 
            [items]="suggestions"
            [typeahead]="typeaheadTextInput"
            [loading]="tokensAreLoading"        
            [isOpen]="openSuggestionDropdown"        
            [searchFn]="customSearchFn"
            bindLabel="name"
            placeholder="Gib hier Zutaten und Stichworte ein"
            notFoundText="Keine Zutaten oder Stichworte gefunden"
            loadingText="Lade..."
            [multiple]="true"
            [hideSelected]="true"        
            [(ngModel)]="tokens"
            (change)="tokensChanged()"
            [inputAttrs]="{autocomplete: 'off'}">

  

 	import { Component, OnInit, EventEmitter, Output, Input, forwardRef } from '@angular/core';
	import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';
	import { ActionSheetController } from '@ionic/angular';

	import { Observable } from 'rxjs';
	import { catchError, map, debounceTime, filter } from 'rxjs/operators';

	import { Token, TokenResult } from '../../classes/token';
	import { BeTokenService } from '../../services/backend/be-token.service';

	@Component({
	  selector: 'app-token-input',
	  templateUrl: './token-input.component.html',
	  styleUrls: ['./token-input.component.scss'],
	  providers: [
	    { 
	      provide: NG_VALUE_ACCESSOR,
	      useExisting: forwardRef(() => TokenInputComponent),
	      multi: true
	    }
	  ]
	})
	export class TokenInputComponent implements OnInit, ControlValueAccessor {
	  /*
	  This control has been implemented by using this tutorial:
	  https://blog.thoughtram.io/angular/2016/07/27/custom-form-controls-in-angular-2.html

	  There are more steps todo, if you want to include this control to a template-driven or 
	  model-driven form. Those steps are described in the tutorial.
	  */

	  suggestions$: Observable<Token[]>;
	  suggestions: {}[] = [];

	  typeaheadTextInput = new EventEmitter<string>();
	  @Output() onChange = new EventEmitter<{}>();

	  tokens: Token[];
	  propagateChange = (_: any) => {};

	  @Input() excludedTokens: Token[] = [];

	  openSuggestionDropdown: boolean = false;
	  tokensAreLoading: boolean = false;

	  constructor(private beTokenService: BeTokenService, public actionSheetController: ActionSheetController) {  }
	  
	  ngOnInit() {
	    // Load suggestions on input text change
	    this.typeaheadTextInput.subscribe(searchtext => {      
	      if (searchtext) {
	        // Allow Suggestion dropdown to be opened
	        this.openSuggestionDropdown = true;

	        // Show loading, if there are no suggestions yet
	        if (this.suggestions.length == 0) {
	          this.tokensAreLoading = true;
	        }
	        
	        // Load the suggestions for the searchtext
	        this.refreshSuggestions(searchtext)        
	      }
	      else {
	        // Close dropdown if no search text given. Showing dropdown with text from input 'typeToSearchText'
	        // seems disturbing, the placeholder text is enough
	        this.openSuggestionDropdown = false;

	        // Clear suggestions
	        this.suggestions = []
	      }
	    });
	  }

	  // The server does the filtering (not javascript). So we disable filtering 
	  // by javascript, by always returning true
	  customSearchFn(term: string, item: any) {
	    return true;
	  }

	  refreshSuggestions(searchtext: string) {
	    // Load suggestions
	  	this.suggestions$ = this.beTokenService.getSuggestions(
	        searchtext, 
	        10, 
	        Token.TYPE_SLUGS.join(","), 
	        this.excludedTokens
	      ).pipe(map(val => {
	        return val["items"];
	      }))
	    
	    // Set suggestions. We do not pass the observable directly to ng-select, because we have a flickering 
	    // then (it shows the "Loading..." label for a short time)
	    this.suggestions$.subscribe(items => { 
	      this.suggestions = items;
	      this.tokensAreLoading = false;
	    });
	  }

	  tokensChanged() {
	    this.openSuggestionDropdown = false;    
	  }

	}

**Comment by varnastadeus** [comment]
there is no flickering in demo page, I guess this is how you implemeted it
