### ISSUE TITLE
Allow dropdown to open if max items are selected

### ISSUE THREAD

**Issue by biltongza** [ng-select/ng-select#1714]
I have a material themed ng-select dropdown with multi select enabled. If I set the max number of items, the dropdown stops working until I clear the selection.

Our dropdown looks like this:

![image](https://user-images.githubusercontent.com/2845704/90253462-79725d00-de41-11ea-8d68-b09e938e4525.png)

Note the use of checkboxes inside the dropdown panel to indicate which items are selected.

When multiple items are selected, we don't show them in the input, we show how many are selected, like this:

![image](https://user-images.githubusercontent.com/2845704/90253567-a45cb100-de41-11ea-9e0b-28ad36557fcd.png)

Judging from the example here: https://ng-select.github.io/ng-select#/multiselect it appears the expected behaviour is that you can deselect items in the input. This is incompatible with our design.

The culprit is the `this.itemsList.maxItemsSelected` check here:
https://github.com/ng-select/ng-select/blob/39f7537365a4f17a94de83912d27de4534b9d568/src/ng-select/lib/ng-select.component.ts#L409

Would it be possible to include an option for this behaviour?

**Comment by varnastadeus** [comment]
#1447
