### ISSUE TITLE
sideEffects: false causes imported SCSS file to be optimized away by Webpack 4+

### ISSUE THREAD

**Issue by jaydiablo** [ng-select/ng-select#1717]
**Describe the bug**
I'm importing the SCSS file for this component in the JS of my app like so:

`import '@ng-select/ng-select/scss/default.theme.scss';`

Which works fine, until a production build is done. This component's `package.json` file has this line in it:

```
"sideEffects": false,
```

Which tells Webpack 4 that if there are unused imports, they can be optimized away (tree shaken: https://webpack.js.org/guides/tree-shaking/), and since this SCSS file isn't exported or used in the app directly, Webpack just removes the import during the production build.

There might be something I can do in the app to prevent this from happening (import to a variable and export that maybe, or override that sideEffects setting locally (not sure if that's possible, but going to try)), but I think the better solution is for this component to change the `sideEffects` property in the dist `package.json` to something like this:

```
"sideEffects": ["*.scss","*.css"],
```

Which would allow any consumers of this component to import the CSS/SCSS files in Webpack and not have them tree-shaken away.

I'm using version 3.7.3 of this component, but I suspect that this issue applies to all versions.

This Github issue in the webpack project explains the issue well, and shows the fix for a different library that exhibited the same issue: https://github.com/webpack/webpack/issues/8814

Thanks!

**Comment by varnastadeus** [comment]
this actually brakes the demo page so I reverted it. Also, I am not sure how this is related to the component itself when themes are completely separated from component

**Comment by jaydiablo** [comment]
Just curious, how did it break the demo page?  Did it break when using `ng serve` or just when you deployed to github pages?

Even though the themes are separate, because they live in the same NPM package as the `package.json` file that has `sideEffects: false` in it, webpack will tree-shake out the CSS files when using an import statement inside the app as I did above.

I'll try to see if I can get a small example repo put together that exhibits this.

**Comment by varnastadeus** [comment]
when deployed to github pages, but you can reproduce it locally. Just run `yarn build:demo` and then serve demo locally
