### ISSUE TITLE
Bind value selected to input text

### ISSUE THREAD

**Issue by carscx** [ng-select/ng-select#172]
I do not know if it is a bug or improvement of the plugin. Excuse me if I'm making a mistake. But I want to know how to improve this behavior

### Expected behaviour
When I selected a item, then I want to edit this value for a new search. The input text of search is empty

### Actual behaviour
In Demo

https://ng-select.github.io/ng-select#/filter

When you filter and the item is selected, the focus is at the beginning of the input.

### More Info
ng-select version: 0.5.0

browser: Chrome 63, Firefox 57

reproducible in demo page: YES

**Comment by varnastadeus** [comment]
@carscx why are you using 0.5.0 version?

**Comment by maznag** [comment]
It works well with the latest version 0.14.1. Thanks for this work

**Comment by anjmao** [comment]
@carscx I'm closing this issue, feel free to reopen it if you have any problem.
