### ISSUE TITLE
While using multiple = true, Virtual scroll = true, selection is remains the same! crucial bug

### ISSUE THREAD

**Issue by Napster2019** [ng-select/ng-select#1723]
**Describe the bug**
When we search and search for whole object and select it then, it wouldn't change the dropdown list to initial it remains the same. Attaching the example with to reproduce the behavior steps
**Reproducbile example**
example here [Stackbliz](https://stackblitz.com/edit/ng-select-infinite-rkfg15?embed=1&file=src/app/app.component.html)

**To Reproduce** 
Steps to reproduce the behavior (if example is not provided):
1. Search for reprehenderit est deserunt velit
2. Select the searched object, now deselect the object and see the dropdown it would show the last selected object only instead of whole item list ----> Major BUG
3. TERM has last searched term in it.

**Expected behavior**
After selection or deselection of the object, dropdown should show whole list item again. So that user search for the new item.

**Comment by Napster2019** [comment]
@varnastadeus please look its your created example with multiple select

**Comment by varnastadeus** [comment]
I don't see any bug here, it works exactly as expected:
```js
  onSearch() {
    this.input$.pipe(
      debounceTime(200),
      distinctUntilChanged(),
      switchMap(term => this.fakeService(term))
    )
      .subscribe(data => {
        this.photosBuffer = data.slice(0, this.bufferSize); // <--------------------------- HERE
      })
  }
```

On each search, you override your items array so no wonder next time you open you have only items you last searched for. You need to add logic to reset items if thats expected.
