### ISSUE TITLE
Wrong position of dropdown when removing item while dropdown is open

### ISSUE THREAD

**Issue by jcubic** [ng-select/ng-select#1725]
**Describe the bug**
When dropdown is added to body and when items are in rows removing items while dropdown is open don't refresh dropdown position.

**Reproducbile example**
https://ng-select.github.io/ng-select#/append-to-element

**To Reproduce** 
1. Inspect the element and set css `.card { width: 300px }` so the items appear in multiple rows.
2. Add 3 items to second select that have dropdown on body
4. Open dropdown
5. Remove the item so the input will shrink
6. The position of the dropdown is in wrong position (don't refreshed)

**Expected behavior**
I expect the dropdown to be moved, to be below the input.

**Screenshots**

![ng-select](https://user-images.githubusercontent.com/280241/91989790-37965180-ed31-11ea-9519-9714f6d6d230.png)

**Comment by jcubic** [comment]
I can try to provide the fix, if you want.

**Comment by jcubic** [comment]
Awesome, 3 years closed as not planed.

**Comment by pavankjadda** [comment]
> Awesome, 3 years closed as not planed.

If you can send a PR that's great. Otherwise please create new issue with issue template.

**Comment by jcubic** [comment]
I don't use Angular anymore, and I don't want to touch Angular code.

**Comment by jcubic** [comment]
Also it looks like the demo https://ng-select.github.io/ng-select#/append-to-element don't even work, so I don't really care.

![Przechwycenie obrazu ekranu_2024-05-26_00-19-42](https://github.com/ng-select/ng-select/assets/280241/94441b9e-7765-4f7a-b9c9-534b933f6b40)

**Comment by adam-marshall** [comment]
a workaround for this was calling the following 'on clear'

```
    this.ngSelect['_onSelectionChanged']();
```


using `[popover]` instead of `[appendTo]`, this is still an issue, logged separately https://github.com/ng-select/ng-select/issues/2791
