### ISSUE TITLE
Tabbing issue in latest version ng-select

### ISSUE THREAD

**Issue by rohit64Singh222** [ng-select/ng-select#1742]
Hello,
  We getting issue on tabbing on ng-select dropdown version we using @ng-select/ng-select : ^5.0.1

Issue generate in this demo : https://angular-j8rtum.stackblitz.io

Issue not generate older version @ng-select/ng-select : ^2.16.0

Demo URL : https://ng-select-womgrh.stackblitz.io

Video For reference : https://www.awesomescreenshot.com/video/1067006?key=f688c47b2f15be669dbeed5997937055

**Comment by mahendra1608** [comment]
Any Update?

**Comment by rohit64Singh222** [comment]
Any Update?

**Comment by rohit64Singh222** [comment]
Any Update ?

**Comment by rohit64Singh222** [comment]
Hello,

Any Update ?
