### ISSUE TITLE
Padding between ng-select and ng-dropdown

### ISSUE THREAD

**Issue by balandinve** [ng-select/ng-select#1746]
Hi.
There is padding bw main ng-select component and ng-dropdown.
![image](https://user-images.githubusercontent.com/7070809/94526160-53711280-025f-11eb-8d3a-df04718fed2c.png)
It is awailable on [Demo -> AppendTo (second example)](https://ng-select.github.io/ng-select#/append-to-element)
How to remove it?

**Comment by tommasomarchionni** [comment]
You can remove padding-bottom to ng-select element.

**Comment by balandinve** [comment]
> You can remove padding-bottom to ng-select element.

Can you do that?  Stackblitz link in topic.
I cant.

**Comment by tommasomarchionni** [comment]
As a workaround to fix all autocomplete dropdown position you can add this style in component style section:

`::ng-deep body > ng-dropdown-panel,
::ng-deep .scrollable-box ng-dropdown-panel {
  margin-top: -20px;
}`

[Demo](https://stackblitz.com/edit/angular-svsdft?file=src%2Fappend-to-example.component.scss)
