### ISSUE TITLE
ERROR in getInternalNameOfClass() called on a non-ES5 class: expected NgItemLabelDirective to have an inner class declaration

### ISSUE THREAD

**Issue by anibalardid** [ng-select/ng-select#1748]
**Describe the bug**
When run npm start i get this error:
WARNING in Invalid constructor parameter decorator in node_modules/@ng-select/ng-select/fesm2015/ng-select-ng-select.js:
 () => [
    { type: ElementRef }
]

ERROR in getInternalNameOfClass() called on a non-ES5 class: expected NgItemLabelDirective to have an inner class declaration

**To Reproduce** 
Steps to reproduce the behavior (if example is not provided):
1. npm install --save @ng-select/ng-select
2. add to app.module.ts:
```
import { FormsModule } from '@angular/forms';
import { NgSelectModule } from '@ng-select/ng-select';

@NgModule({
    imports: [
        xxxxxx,
        xxxxxx,
        FormsModule,
        NgSelectModule,
    ],
```
3. npm start
4. error....

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 20.04

Angular CLI: 9.0.3
Node: 12.18.4
OS: linux x64
Angular: 9.0.2

**Comment by varnastadeus** [comment]
you are potentially using wrong version, v5 is for angular 10

**Comment by anibalardid** [comment]
@varnastadeus  ouch, thanks ! I will try with correct version :)
