### ISSUE TITLE
Remove single item from multi select does not work when custom label template is used

### ISSUE THREAD

**Issue by andreasfranz** [ng-select/ng-select#175]
### Expected behaviour
When using the option [multiple]="true" in combination with a custom template it should be possible to remove single selected items.

### Actual behaviour
Cannot remove single items anymore. Reproducible on the demo page https://ng-select.github.io/ng-select#/multiselect (Custom label templates)

### More Info
affected ng-select version: 0.13.0, 0.14.0, 0.14.1

browser: Chrome 63.0.3239.108

reproducible in demo page: YES

**Comment by varnastadeus** [comment]
Thanks for a catch, will fix it today
