### ISSUE TITLE
ng-select multiple type "Clear All" icon is not clickable and not clearing selected items instead it opens options list 

### ISSUE THREAD

**Issue by anil-ghub** [ng-select/ng-select#1767]
**Describe the bug**
Am using ng-select multiple type control with custom templates when i am trying to click on exactly on top of  clear all icon ..its not getting clear all the selected items  due not clickable 

**Reproducbile example**
https://stackblitz.com/edit/ng-select-ni1xnb?file=app/app.component.ts

**To Reproduce** 
Steps to reproduce the behavior (if example is not provided):
1. Add items available from the option list 
2. Now go to "Clear All" icon and click on top of the icon exactly,( you can see only mouse pointer at this moment not hand symbol with tool tip "clear all")
3. Instead of it should clear selected items , it opens options list. (refer screen shot "not_clear.png")
4. But i can clear all if i positioned mouse pointer at 1px distance below the close all icon.. (refer screen shot "clear_all.png")

**Expected behavior**
By clicking on clear all icon 
1. It should clear selected list of items
2.  Hand cursor pointer should be display by positioning on top of the icon 

**Screenshots**

![clear_all](https://user-images.githubusercontent.com/72564733/95490482-ea537280-09b5-11eb-9639-7318e6d47dd4.PNG)
![not_clear](https://user-images.githubusercontent.com/72564733/95490523-f5a69e00-09b5-11eb-8a7f-fc3613474207.PNG)

**Comment by topalavlad** [comment]
@anil-ghub do you see the same behavior in the stackblitz link you posted? I just tried on Firefox and Safari and they both show the pointer correctly. 

Do you think it could be related to your styling? Can you inspect and see what size the span with the clear icon has?

**Comment by anil-ghub** [comment]
Yes @topalavlad , i was able to see same behaviour even in stackblitz,  please try in chrome browser and  click as similar I did in  attached screen print. 
And one more thing you can catch the said use case if you try first time once the component loaded placing mouse pointer exactly on top of the close icon.
Once after option list opens and then click on cross icon it will works.
When I debug it ..there was a wrapper class which is getting cover on top of clear icon class.
In attached screen shots , you can clearly see ther is no hand symbol and clear all tool tip when I positioned mouse pointer on icon . Which you have to try the same. Please let me know if you need any details further. Thanks

**Comment by anil-ghub** [comment]
Hi Team, Can i have any update on my issue? please let me know. Thanks

**Comment by anil-ghub** [comment]
> @anil-ghub do you see the same behavior in the stackblitz link you posted? I just tried on Firefox and Safari and they both show the pointer correctly.
> 
> Do you think it could be related to your styling? Can you inspect and see what size the span with the clear icon has?

Hi - Can you please find my response below

**Comment by varnastadeus** [comment]
just saw that you are using a very old version, this should be fixed on older versions. If that's not an option for you, adjusting css style might help.

**Comment by anil-ghub** [comment]
Version could be older because I updated one of online stackblitz example to repro the problem. So what could be resolution for my issue? I already tried with car but no luck because ng-clear wrapper css is blocking the actual class. Please advise to overcome this issue..
