### ISSUE TITLE
Dynamic Items List

### ISSUE THREAD

**Issue by Aspersion** [ng-select/ng-select#177]
Improvement / Issue
### Expected behaviour
Using a dynamic list of items should update the model correctly.

### Actual behaviour
When I'm using a dynamic list of items with single select, listItem[index] is selected even if the list changes, so you can not select the same index again when you filter a second time.

With multiselect, when you filter a second time, if you don't have the selected items in that list, they are selected items are overwritten.

### More Info
ng-select version: 0.14.2

browser: Google Chrome 63.0.3239.132

reproducible in demo page: Yes for multiselect
https://ng-select.github.io/ng-select#/forms (Set 0-10 albums -> Set 10-20 albums)

**Comment by varnastadeus** [comment]
Hi @Aspersion, can you add more details what you are trying to achieve?

**Comment by Aspersion** [comment]
Yes, sorry about that. This is mostly to do with loading async data.

For single select:
I couldn't replicate this in the demo, but my issue is this: When loading async multiple times some of the items are unselectable. For example, you search for a city, you get only 1 result and you select that one, then you change your mind, you search for another city, you get 1 result, but you can't select it because the component thinks that it is already selected.

`    NgSelectComponent.prototype.select = function (item) {
        if (!item.selected) {
            this.itemsList.select(item);
            this.clearSearch();
            this.updateModel();
            this.addEvent.emit(item.value);
        }
        if (this.single) {
            this.close();
        }
    };`

When NgSelectComponent.prototype.select is triggered a second time, item.selected will be true.

For multiselect:
If you look at the demo on https://ng-select.github.io/ng-select#/forms, you'll see that if you change the [items] input with a different list, the model gets changed as well. I was wondering if this intended or an issue.

Hope this was helpful enough.

**Comment by varnastadeus** [comment]
@Aspersion I have found an issue and I am planning to fix it today, thanks for examples

**Comment by varnastadeus** [comment]
@Aspersion version 0.14.3 should fix this issue and for demo page when you click `Set 10-20 albums` it deliberately selects first item from array

**Comment by Aspersion** [comment]
@varnastadeus Thanks a lot for the fix and explanation. I will close the issue. Have a great day.
