### ISSUE TITLE
ng-select styles are not working in modal popup

### ISSUE THREAD

**Issue by rami14c** [ng-select/ng-select#1771]
I'm working on angular 6 project and I have included all the imports which are required to run ng-select and it is working as expected.

But the problem is with modal popup, when I add the ng-select in modal popup and created that as a new component, the styles are not applying to it.
Any suggestions here.

**Comment by Pocciox** [comment]
I solved this issue by pasting this line:

`@import "~@ng-select/ng-select/themes/default.theme.css";
`
in the styles.scss file in my angular project.

For some reason, doing:
```

            "styles": [
              "./node_modules/@ng-select/ng-select/themes/default.theme.css",
              "./node_modules/@angular/material/prebuilt-themes/indigo-pink.css",
              "src/styles.scss"
            ],

```
wasn't working for me.
I had to manually import the styles in scss to make it work.
