### ISSUE TITLE
Bind label should be ignored if template is used for formatting so that an item of the items array may be undefined

### ISSUE THREAD

**Issue by Ryland42** [ng-select/ng-select#178]
Please fill below information if issuing a bug report. 
### Expected behaviour
Template is used for formatting of the items array and the bindLabel is completely ignored in code.  This becomes an issue if one of the elements of the items array is undefined.

### Actual behaviour
I have an ng-select defined which contains an ng-template for formatting.  In some instances I need to have one item in the items array be undefinedl.  This causes an exception in ItemsList.prototype.resolveNested.
ERROR TypeError: Cannot read property 'label' of undefined
    at ItemsList.Array.concat.ItemsList.resolveNested (ng-select.es5.js:1432)
    at ng-select.es5.js:1419
    at Array.map (<anonymous>)
    at ItemsList.Array.concat.ItemsList.mapItems (ng-select.es5.js:1410)
    at ItemsList.Array.concat.ItemsList.setItems (ng-select.es5.js:1228)
    at NgSelectComponent.Array.concat.NgSelectComponent.setItems (ng-select.es5.js:1889)
    at NgSelectComponent.Array.concat.NgSelectComponent.ngOnChanges (ng-select.es5.js:1564)
    at checkAndUpdateDirectiveInline (core.js:12092)
    at checkAndUpdateNodeInline (core.js:13598)
    at checkAndUpdateNode (core.js:13541)

### More Info
ng-select version: 0.14.1

browser: Google Chrome 63.0.3239.84

reproducible in demo page: YES https://plnkr.co/edit/FX7NDgAS3POgEEunjnc8?p=preview

**Comment by anjmao** [comment]
Hi @Ryland42 , thanks for reporting. HI can simply filter elements to be defined
`items.filter(item => !!item)`, but can you provide some background what is your use case?

**Comment by Ryland42** [comment]
From an existing project which I was changing from a select to ng-select so that I could modify how the list was presented to the end user.  I have a list of items to select from but in some cases I need a special "Any" selection which in the old codebase had a value of undefined so that we wouldnt send any data back to the server for the selection.

**Comment by varnastadeus** [comment]
@Ryland can you add some code?

**Comment by varnastadeus** [comment]
@Ryland can you add some code?

**Comment by varnastadeus** [comment]
@Ryland can you add some code?

**Comment by anjmao** [comment]
@Ryland42 Have you tried setting Any value as undefined?

```ts
const items = [
   { label: 'Any', value: undefined },
   { label: 'Item1': value: 'its value'
]
```

**Comment by Ryland42** [comment]
Here is the ng-select as I have it defined:
`<ng-select class="shift-select" [items]="shiftList" [searchable]="false" [clearable]="false" [ngModel]="value" (ngModelChange)="changeValue($event)">
		<ng-template ng-label-tmp let-item="item">
			<div *ngIf="item">
				<div>{{item.start | amDateFormat: 'lll'}} -</div>
				<div>{{!item.end ? 'Current' : item.end | amDateFormat: 'lll'}}</div>
			</div>
			<div *ngIf="!item">
				Any
			</div>
		</ng-template>
		<ng-template ng-option-tmp let-item="item" let-index="index">
			<div *ngIf="item">
				<div>{{item.start | amDateFormat: 'lll'}} -</div>
				<div>{{!item.end ? 'Current' : item.end | amDateFormat: 'lll'}}</div>
			</div>
			<div *ngIf="!item">
				Any
			</div>
		</ng-template>		
	</ng-select>`

Definition of shiftList:

	`shiftList: Shift[];`

The data passed to it, shiftList, contains objects which when an item from the list is selected the entire object is emitted or if Any is selected then 'undefined' is emitted.

**Comment by anjmao** [comment]
@Ryland42 You can do the following:

Set first item as object with label property.

```ts
shiftList: Shift[] = [
   { label: 'Any' },
   ... rest normal items
]
```
Change you html to check if item.start is defined
```html
<ng-select class="shift-select" [items]="shiftList" [searchable]="false" [clearable]="false" [ngModel]="value" (ngModelChange)="changeValue($event)"> 
<ng-template ng-label-tmp let-item="item">
   <div *ngIf="item.start">
      <div>{{item.start | amDateFormat: 'lll'}} -</div>
      <div>{{!item.end ? 'Current' : item.end | amDateFormat: 'lll'}}</div>
   </div>
   <div *ngIf="!item.start">{{item.label}}</div>
</ng-template>
<ng-template ng-option-tmp let-item="item" let-index="index">
   <div *ngIf="item.start">
      <div>{{item.start | amDateFormat: 'lll'}} -</div>
      <div>{{!item.end ? 'Current' : item.end | amDateFormat: 'lll'}}</div>
   </div>
   <div *ngIf="!item.start">{{item.label}}</div>
</ng-template>
</ng-select>
```

Now you only need to handle case then user selects All you send null to server side.
```ts
changeValue() {
   if (!this.value.start) {
      // user selected All.
   }
}

```

**Comment by Ryland42** [comment]
And that works with a few other tweaks, like changing shiftList to an array of any instead of of Shift since typescript throws errors if I dont make that change.

**Comment by Ryland42** [comment]
That gets me around the error I was seeing but now when I select Any I end up with the ng-select being empty unless I select Any a second time.  The correct info is sent to the server in either case (ng-select empty or showing Any).  I have attached a picture of what I mean.

![image](https://user-images.githubusercontent.com/8311358/34829945-5bb4c42c-f6b0-11e7-94e9-2a66a17d94ca.png)

**Comment by anjmao** [comment]
@Ryland42 Probably you are doing something wrong. Here is working sample https://plnkr.co/edit/hCGUUr6xxas8806sOrMR?p=preview

**Comment by Ryland42** [comment]
The blank being selected is associated with emitting of 'undefined'.  If I remove that line then Any is selected.  I put a breakpoint in ng-select.es5.js at line 1674 and found that NgSelectComponent.prototype.writeValue is being called with a value of 'undefined'  but never with any other values contained in the select.

**Comment by anjmao** [comment]
@Ryland42 
Can you create a simple plunker or paste code what changeValue() method is doing ?

**Comment by Ryland42** [comment]
Sorry about the delay in responding.  Work spun out of control in another direction and Im finally back on this.  Here is the code as being used which ends up causing writeValue to be called.  In that case this.value is set to undefined.

	```
@Output()
	valueChange: EventEmitter<Shift> = new EventEmitter();
	value: Shift;

	changeValue (value: Shift): void {
		if (value && value.start) {
			this.value = value;
		} else {
			this.value = undefined;
		}
		this.valueChange.emit(this.value);
	}
```

**Comment by anjmao** [comment]
@Ryland42 Hi, sorry for delay. Could you try creating plunker sample from issue template https://plnkr.co/edit/hjZX6W?p=preview and demonstrate this use case as it is not clear to find out the problem.

**Comment by Ryland42** [comment]
No problem.  Im filling out this plunker https://plnkr.co/edit/FRHc4ysWS5xDtuIi0rtx?p=preview trying to reproduce what I am seeing.  Its currently not showing the same behavior I see so I will let you know when/if Ive reproduced the issue in the plunker.

**Comment by varnastadeus** [comment]
@Ryland42 I am closing this issue. If you will be able to reproduce it, please create new issue and provide plunker.
