### ISSUE TITLE
Unable to get property 'length' of undefined or null reference

### ISSUE THREAD

**Issue by kamilchlebek** [ng-select/ng-select#1780]
**Describe the bug**

This commit: https://github.com/ng-select/ng-select/commit/057a5ac5e17c250b64ebc0219550ef71e3772295 introduced incompatibility with IE11. 

```
const path = e.path || (e.composedPath && e.composedPath());
const scrollTop = path.length === 0 ? e.target.scrollTop : path[0].scrollTop
```

`path` is undefined on IE11. 

**Reproducbile example**

https://ng-select.github.io/ng-select#/data-sources

**To Reproduce** 

Open dropdown, try to scroll. 

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Internet Explorer
 - Version: 11

**Comment by ashifur-malia** [comment]
im getting this same error on firefox now. 

using 
"@ng-select/ng-select": "^8.1.1",
"@angular/core": "~13.3.10",

firefox version: 107.0.1(64-bit)

error thrown at :
function name: _handleScroll() 
line:  const scrollTop = !path || path.length === 0 ? e.target.scrollTop : path[0].scrollTop; 

on firefox console 
![image](https://user-images.githubusercontent.com/19757099/206957358-553a5f85-2517-497a-a6c9-00058d22a258.png)
