### ISSUE TITLE
An accessor cannot be declared in an ambient context

### ISSUE THREAD

**Issue by rmcsharry** [ng-select/ng-select#1781]
Please re-open:

https://github.com/ng-select/ng-select/issues/1615

It occurs with angular 8.2.14 and ng-select 3.7.3

In my case it is specific to NgOptionHighlightModule in:
`../node_modules/@ng-select/ng-option-highlight/lib/ng-option-highlight.directive.d.ts:13:17`

**Comment by kaka4** [comment]
I had the same issue. 
I used "@ng-select/ng-option-highlight": "0.0.4", instead of 0.0.5 to solve that.

**Comment by varnastadeus** [comment]
check the comment to solve that or upgrade to the latest version
