### ISSUE TITLE
ios13 input chinese keyword Will produce two or three and more...

### ISSUE THREAD

**Issue by PelnHigh** [ng-select/ng-select#1783]
Describe the bug
ios13 input chinese keyword Will produce two or three

is movie
http://cms.brightideas.com.tw/test/617276116.989040.mp4

Smartphone (please complete the following information):

Device: [e.g. iPhone X]
OS: [e.g. iOS 13]
Browser [safari, chrome]

**Comment by PelnHigh** [comment]
--

**Comment by llccing** [comment]
> --

hi , do you resolve this problem, i also met..

**Comment by llccing** [comment]
```js
searchWhileComposing="false"
```
can resolve problem.
