### ISSUE TITLE
how can I show field label by default in <ng-select> multiple type ? in Angular7

### ISSUE THREAD

**Issue by anil-ghub** [ng-select/ng-select#1788]
Hi,
 I have a requirement to build a search filter as per the given design (PFA image). I was figuring out to display label text by default with  below **"ng-multi-label-tmp**" but its only display when we select any item from the option list. But i should display  at very first time the control is bind to angular form as like other input fields labels.

 <ng-template ng-multi-label-tmp  *ngIf="true" let-unselect="unselect"> {{ placeholderText }} </ng-template>

  Also tried to display with [(ngModel)] as well but no luck.  Please suggest

Expected behavior :   static label text needs to be displayed for <ng-select> multiple type control Eg:  **Status Filters (2)**
=============

![multiselect](https://user-images.githubusercontent.com/72564733/98017583-76c24b00-1e25-11eb-836a-33e1d179c21a.PNG)
</ng-template>

**Comment by varnastadeus** [comment]
use "placeholder"
