### ISSUE TITLE
How do i use ngIf in ng-option-tmp ?

### ISSUE THREAD

**Issue by JohanurRahman** [ng-select/ng-select#1789]
<ng-template ng-option-tmp let-item="item" let-index="index" let-search="searchTerm">
                    <div class="profile-container" *ngIf="item.status === 'active'">
                        <img class="image img-fluid" [src]="item.profile ? item.profile.pro_pic : null">
                        <div>
                            <p class="title" [ngOptionHighlight]="search">{{ item.profile.name }}</p>
                            <span class="subtitle">{{ item.designation }}, {{ item.department }} </span>
                        </div>
                    </div>
                </ng-template>

What i want to do is i would like to show only those item where item.status === 'active'. That is only for the ng-option-tmp. If i try to do this in the ng-template it says status is undefined.

**Comment by varnastadeus** [comment]
you should filter out inactive items if you want to show only those :]
