### ISSUE TITLE
@ng-select/ng-option-highlight has incorrect peer dependencies

### ISSUE THREAD

**Issue by bjornharvold** [ng-select/ng-select#1796]
warning " > @ng-select/ng-option-highlight@0.0.5" has incorrect peer dependency "@angular/common@~9.1.0".
warning " > @ng-select/ng-option-highlight@0.0.5" has incorrect peer dependency "@angular/core@~9.1.0".
warning " > @ng-select/ng-option-highlight@0.0.5" has incorrect peer dependency "tslib@^1.10.0".

Is it possible to bump this to 10.x and tslib 2.x?

Thank you

**Comment by varnastadeus** [comment]
#1704
