### ISSUE TITLE
be able to multiselect items with shift key (or add shift key to events)

### ISSUE THREAD

**Issue by cciccole** [ng-select/ng-select#1797]
It would be nice if there were an option for contiguous items to be selected with a shift click. Same for deselection.

I'll leave out further details on exactly how it should work because this pattern is very common.

A reasonable workaround would be to add the `shift` attribute to the `(add)` and `(remove)` events. Then the intended functionality could at least be implemented within a custom wrapper for `ng-select`.

Currently the only workaround (besides forking `ng-select`) that I can think of is to also put the native `(click)` event on the component and then add in logic to detect it approximately simultaneously with the `(add)` or `(remove)` events and act accordingly. Any other ideas?

**Comment by bhaskerchari** [comment]
Hi,

Are there any chances that this may be supported in near future at least??

**Comment by ibha** [comment]
This is very commonly used feature in multi-select. Is it possible to reopen the issue
