### ISSUE TITLE
ERROR in 'ng-select' is not a known element

### ISSUE THREAD

**Issue by amanda7227** [ng-select/ng-select#1800]
**Describe the bug**
1. I execute "npm install --save @ng-select/ng-select"
2. after install, I just set <ng-select></ng-select> in my html file
3. I run "npm start"
4. I get the error below

ERROR in 'ng-select' is not a known element:
1. If 'ng-select' is an Angular component, then verify that it is part of this module.
2. If 'ng-select' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("[ERROR ->]<ng-select></ng-select>
")

package.json
 "@angular/compiler": "~9.1.1",
 "@angular/core": "~9.1.1",
 "@angular/forms": "~9.1.1",
 "@ng-select/ng-select": "^5.0.8",

What can I do?

**Comment by vladsolomon** [comment]
> "@angular/core": "~9.1.1"

You can try to use "@ng-select/ng-select": "4.0.4" that compatible with angular 9 according to readme
