### ISSUE TITLE
Add Angular 11 Support

### ISSUE THREAD

**Issue by pavankjadda** [ng-select/ng-select#1803]
**Is your feature request related to a problem? Please describe.**
No, not a feature request. Please add support for Angular 11

**Comment by SkrupSulten** [comment]
It seems to work just fine for Angular 11, but official support would be great!

**Comment by zakiarahimi** [comment]
@varnastadeus @SkrupSulten 
after updating angular to version 11 I faced with this error
 **Error: node_modules/ng2-select2/ng2-select2.component.d.ts:2:88 - error TS2724: Module '"../@angular/core/core"' has no exported member 'Renderer'. Did you mean 'Renderer2'?**

**Comment by dezsiszabi** [comment]
This probably depends on ng-bootstrap/ng-bootstrap#3897

**Comment by inexuscore** [comment]
Is this repo actively maintained? I wanna upgrade from Angular 10 to 11 and the only blocking package is **ng-select**. I could fork and submit a PR but I'm not sure if PRs are being actively maintained.

**Comment by luoxiao-xy** [comment]
We hope to follow up angular11 as soon as possible

**Comment by inexuscore** [comment]
@luoxiao-xy fantastic, looking forward to it. meanwhile, I have been able to upgrade to Angular 11 without a problem. Thank you very much.

**Comment by doublemcz** [comment]
+1

**Comment by bsarkadi** [comment]
+1

**Comment by WuglyakBolgoink** [comment]
up

**Comment by Tea-Ice** [comment]
So does this work with Angular 11 or not? We want to upgrade our project, but we need this package working with it first....

**Comment by rooby** [comment]
@Tea-Ice 

Seems to work fine using the current version but you get some build warnings about the version mismatch.

As always with these kinds of questions though, the best way to be sure is upgrade your app to angular 11 and test it to make sure your specific usage doesn’t have any issues.

**Comment by jerone** [comment]
Our tests indicates that everything works fine with Angular 11. 

Would love to get ride of those warnings.

**Comment by sebastian-zarzycki-es** [comment]
Any progress with that?

**Comment by doublemcz** [comment]
I can confirm, that it I haven't found any issue with Ng 11. I use this plugin in couple of projects (heavily, with many of its feautres).

**Comment by sebastian-zarzycki-es** [comment]
Same here. So bumping the peer dependency would be nice, there's nothing else needed, I believe.

**Comment by Jelledb** [comment]
Same here, works great but getting rid of those peer dependencies warnings would be awesome :-)

**Comment by sebastian-zarzycki-es** [comment]
One thing I've noticed with Angular 11 is that when HMR attempts to restore input values, for some reason it opens all ng-select popups in the process (and the value is not restored anyway). Not a terrible problem, though, given that's is just developer's convenience.
