### ISSUE TITLE
Accessibility requirement - Clear all [x] button need "role" setting

### ISSUE THREAD

**Issue by DandelionWenjing** [ng-select/ng-select#1805]
**Describe the bug**
Clear all x button have no "Role" setting for accessibility.

**Reproducbile example**
[Example](https://stackblitz.com) which reproduces described behaviour

**To Reproduce** 
Steps to reproduce the behavior (if example is not provided):
1. select one option in ng-select drop down.
2. right side have Clear all X button.
3. Open Dev Tools, select element in page to inspect it, hover X button.
4. There is no role setting for this button.

**Expected behavior**
There will be "Role" setting for the Clear All X button, or there is a way to set it.

**Screenshots**
![image](https://user-images.githubusercontent.com/33156672/99067689-16ca6200-25e6-11eb-92fa-67589b501700.png)

**Desktop (please complete the following information):**
Windows 10, Chrome, 3.7.0

**Smartphone (please complete the following information):**

**Additional context**

**Comment by varnastadeus** [comment]
what role to you expect? 🤔

**Comment by artopaavola** [comment]
> what role do you expect? 🤔

The role should be "button" but more importantly the control itself should be keyboard operable. The safest bet would be to make it a `<button type="button">` instead of a `<span>`.

**Comment by skrzepij** [comment]
Same problem here. Any changes regarding this issue? 

@artopaavola did you found any workaround to manually add keyboard support to the `clear` button?

**Comment by netdjw** [comment]
same problem here

**Comment by DandelionWenjing** [comment]
As this bug is auto closed, will open a new one and track it here. Thanks! https://github.com/ng-select/ng-select/issues/2020
