### ISSUE TITLE
get previous value on clear all event

### ISSUE THREAD

**Issue by Cobr3n** [ng-select/ng-select#1808]
Hello! Can i get previous model value after clear all event ?

**Comment by varnastadeus** [comment]
you can, just store it before clearing your items :]

**Comment by LefterisHytiroglou** [comment]
How would we know which dropdown was cleared if there are multiple dropdowns?
(So that we know which of the stored values we should use)

If the clear all button triggered click event, too for example, it would be really easy to access the old value.

**Comment by SRVikash** [comment]
Tried using **(clear) | Fired** on clear icon click and check that this helped me.
