### ISSUE TITLE
how to set maxItems count when use multiselect true

### ISSUE THREAD

**Issue by bvshivaji** [ng-select/ng-select#181]
Please fill below information if issuing a bug report. 
### Expected behaviour
Describe how you think it should work

### Actual behaviour
Describe how it actually works or create example using [Plunker](https://plnkr.co/edit/hjZX6W?p=preview) issue template

### More Info
ng-select version: [INSERT HERE]

browser: [INSERT BROWSER INFO HERE]

reproducible in demo page: [YES/NO]

**Comment by varnastadeus** [comment]
@bvshivaji please add normal description or close this issue because now it make no sense. Issue template is added to save both our time, and yours.

**Comment by anjmao** [comment]
@varnastadeus It is clear from the title. It's a simple feature there you want to control how many items you can allow to select.

@bvshivaji Currently there is no such options. I can think of new `@Input` like `[maxSelectedItems]`.

**Comment by bvshivaji** [comment]
i have checked ngx-chips module so same like that ur module working also be
same than its have more features

**Comment by BenjaminLefevreGithub** [comment]
proposal: https://github.com/ng-select/ng-select/pull/239
