### ISSUE TITLE
Document a recommended protractor testing approach for virtual scrolling

### ISSUE THREAD

**Issue by mathpunk** [ng-select/ng-select#1811]
Some E2E tests I wrote for our application recently broke when we started using virtual scrolling. The new behavior is, when I type into a search select I see options to select from, but when using protractor and using `sendKeys` on the input, no options appear. 

I write almost no Angular code myself, just the E2E tests, but near as I can tell from today's googling, the data I am looking for might be in the "shadow DOM" somewhere. I do not know what changes I need to make to my test code in order to be able to view and select items from the ng-select.

I don't think there is any code that needs to change but I would really appreciate some direction, from someone who understands how this useful component is implemented, on how I can repair my tests. Thanks!

**Comment by varnastadeus** [comment]
I think you should use StackOverflow for this type of questions :]
