### ISSUE TITLE
When using the groupBy attribute, 2nd search for an item does not allow it to be selected

### ISSUE THREAD

**Issue by tannenbaums** [ng-select/ng-select#1812]
**Describe the bug**
Using the latest version 5.0.9 (but this issue was there in previous versions as well). 
We are using ng-select with hierarchal data (using the groupBy attribute) , when I search for an item a second time, comes up in bold and doesn't get selected

**To Reproduce** 
Search for an item and select it --> select a different item --> search for the first item again (comes up in bold) --> try to select, doesn't go, it will not get selected!!

**Expected behavior**
2nd search should allow for the item to get selected exactly like the first time

**Desktop (please complete the following information):**
 - OS: Windows 8
 - Browser chrome
 - Version: the latest 87.0.4280.66

**Additional context**
This seems to only happen with hierarchal data. We are using this control all over our app with no issues, it's just this specific one. Here's the html code for it:

`<ng-select #childList id="childList" [(ngModel)]="Manager.selectedChildId" bindLabel="name" [required]="Manager.required" (open)="Manager.ChildListOpen(childList)" [clearable]="false" groupBy="parent" [dropdownPosition]="'bottom'"> <ng-option [value]="-1" *ngIf="!Manager.hasOneEntityOnly">All Entities</ng-option> <ng-template ngFor let-entityParent [ngForOf]="Manager.childListData"> <ng-option [disabled]="true" value="parent" *ngIf="!Manager.hasOneChildOnly && !Manager.hasOneParentOnly">--{{parent.name}}--</ng-option> <ng-option *ngFor="let child of parent.children" [value]="child.id">{{child.name}}</ng-option> </ng-template> </ng-select>`

**Comment by tannenbaums** [comment]
So this component doesn't seem to be actively supported??? No one seems to be responding... I really like this one, it's got a lot of nice features and a clean api. But I guess I'll have to look for another one, because my users are complaining about this issue... Oh well :(

**Comment by tannenbaums** [comment]
My bad, the html above is not following the documentation. I'm using it correctly now and it works like a charm!!

**Comment by Antony-jeban** [comment]
Hi, I am also facing the same issue. Can you share me what changes you made to resolve this?

**Comment by Antony-jeban** [comment]
> My bad, the html above is not following the documentation. I'm using it correctly now and it works like a charm!!

Hi, I am also facing the same issue. Can you share me what changes you made to resolve this?

**Comment by tannenbaums** [comment]
Sure! Instead of this (using ngFor):
<ng-select id="list" [(ngModel)]="itemId" bindLabel="name" groupBy="group">
<ng-template **ngFor** let-group [ngForOf]="data">
      <ng-option [disabled]="true" value="group">--{{group.displayName}}--</ng-option>
      <ng-option ***ngFor**="let child of group.children" [value]="child.id">{{child.displayName}}</ng-option>

I now do this:

  <ng-select id="list" 
            [items]="data" 
            [(ngModel)]="itemId" 
            [closeOnSelect]="true"
            bindLabel="displayName" 
            bindValue="id"
            groupBy="children"
            [multiple]="false"
            [selectableGroup]="false"
            [dropdownPosition]="'bottom'"
            [searchFn]="facSearchFn"
            placeholder="All Facilities"
            >
    <ng-template ng-optgroup-tmp let-item="item">
      {{item.displayName}}
  </ng-template>
  <ng-template ng-option-tmp let-item="item">
      {{item.displayName}}
  </ng-template>
  <ng-template ng-label-tmp let-item="item">
    {{item.displayName}}
</ng-template>
</ng-select>

Hope this helps!!
