### ISSUE TITLE
error TS2339: Property 'name' does not exist on type 'unknown'

### ISSUE THREAD

**Issue by olivierMansencal** [ng-select/ng-select#1815]
Hi,

When I try to build (with Ivy) the example "Custom template for all selected items using **ng-multi-label-tmp**" I've got this error : 
`error TS2339: Property 'avatar_url' does not exist on type 'unknown'`

If I disable Ivy, it compiles.
Is there a way to allow this example to compile ?
It seems like **let-items="items"** in the declaration of **ng-multi-label-tmp** doesn't keep the type of [items]

I use this example in my project and would like to build it using Ivy.
Here is my code : 
```
<div class="col-12 col-sm-6 col-md-4 col-xl p-2" *ngFor="let filter of filters">
    <ng-select
        [placeholder]="filter.name"
        [items]="filter.items"
        bindLabel="name"
        bindValue="filter"
        groupBy="groupValue"
        [selectableGroup]="true"
        [selectableGroupAsModel]="false"
        [multiple]="true"
        [closeOnSelect]="false"
        (change)="applyChange()"
        [(ngModel)]="userSelections[filter.name]"
        class="input-xs"
        >
        <ng-template ng-optgroup-tmp let-item="item">
            {{item.groupValue || ''}}
        </ng-template>
        <ng-template ng-option-tmp let-item="item" let-item$="item$" let-index="index">
            <input id="item-{{index}}" type="checkbox" [ngModel]="item$.selected"/> {{item.name}}
        </ng-template>
        <ng-template ng-multi-label-tmp let-items="items" let-clear="clear">
            <div class="ng-value" *ngFor="let item of items | slice:0:filter.maxItems">
                <span *ngIf="items.length < filter.maxItems">
                <span class="ng-value-label">{{item.name}}</span>
                <span class="ng-value-icon right" (click)="clear(item)" aria-hidden="true">×</span>
                </span>
            </div>
            <div class="ng-value" *ngIf="items.length > filter.maxItems">
                <span class="ng-value-label">{{items.length - filter.maxItems}} de plus...</span>0
            </div>
        </ng-template>
    </ng-select>
</div>
```
Thanks for your help.

**Comment by romainSaya** [comment]
I have the same problem in angular 11

**Comment by Exerlol** [comment]
Same here, any updates on this?

**Comment by promoter0100** [comment]
> Same here, any updates on this?
> Btw if someone is struggling with this, dirty solution would be usage of `{{$any(item).name}}`. It will make compiler happy again.
> 
> example:
> 
> ```
> <ng-select [multiple]="true" [items]="cities" formControlName="city"
>    [closeOnSelect]="false" placeholder="Select city" bindLabel="name" bindValue="id">
>       <ng-template ng-multi-label-tmp let-items="items" let-clear="clear">
>           <div class="ng-value" *ngFor="let item of items | slice:0:2">
>               <span class="ng-value-label"> {{$any(item).name}}</span>
>               <span class="ng-value-icon right" (click)="clear(item)" aria-hidden="true">×</span>
>           </div>
>           <div class="ng-value" *ngIf="items.length > 2">
>               <span class="ng-value-label">{{items.length - 2}} more...</span>
>           </div>
>       </ng-template>
> </ng-select>
> ```

you can try item["name"]. I don't know but it's works

**Comment by evandersar** [comment]
> item["name"]

item["name"] still produce error in angular 13

**Comment by anuj9196** [comment]
I'm also facing this issue and have already spent hours to find a solution to it. This issue should re reopened to fix.

Error
```
Error: src/app/@style-guide/components/form/select/select.component.html:36:43 - error TS2571: Object is of type 'unknown'.

36           <span class="ng-value-label">{{ item[bindLabel] }}</span>
```

code
```typescript
bindLabel = 'value';
```
```html
<ng-template let-clear="clear" let-items="items" ng-multi-label-tmp>
        <div *ngFor="let item of items | slice:0:sliceCount" class="ng-value">
          <span class="ng-value-label">{{ item[bindLabel] }}</span>
          <span (click)="clear(item)" aria-hidden="true" class="ng-value-icon right px-1">×</span>
        </div>
</ng-template>
```

**Comment by Sravana-Synthesis** [comment]
any solution on this issue. facing same issue, but if we use '$any' solution it's working fine. I'm using Angular 16/ng-select 11
