### ISSUE TITLE
Validation while adding new  item to dropdown using [addTag]=true

### ISSUE THREAD

**Issue by kmanikandanmca2008** [ng-select/ng-select#1816]
**Problem:**

Would like to check the possibility of the validation mechanism on every new item added dynamically to the ng-select component. This we need while enabling the **addTag** property to true.

**For example,**

I want to use this ngselect inside our reactive angular form which will be created dynamically based on the server side json payload. So We augment ngselect in another component where we implement the '**ControlValueAccessor**' interface from '@angular/forms' . The validations hint we are getting form backend like **{ 'min': 18 , 'max': 100}** . So i need this validation hint to be honored by the ng-select.  Currently i dont have any clue that how to implement since this validations should be run on every item added dynamically.

**Comment by bazter** [comment]
I have implemented this today using combination of _addTag_ input and _search_ event. _addTag_ accepts boolean or a function, which you can use to decide if the item should be added or not. In the function you need to validate the search term (comes in fn as argument) and return the term (it's gonna be added) or false (it's not gonna be added). To add some final polish, I have also added some error indicator, which is updated when _search_ event emits.

**Comment by kmanikandanmca2008** [comment]
@bazter Is it possible to share the above code snippet.
