### ISSUE TITLE
key binding input for "disabled"

### ISSUE THREAD

**Issue by Phantoll** [ng-select/ng-select#1818]
When I have a given dataCollection like

```
const dummyData = [
	{id: 1, displayValue: 'Foo Bar'}, 
	{id: 2, displayValue: 'Hello World', isDisabled: true},
	{id: 3, displayValue: 'Lorem Ipsum'},
]
```
So if I want to disable the entries in the dropdown panel I have to map the dataCollection first.

It would be good if you (optional) had the possibility to pass the key for the disabled state as input parmeter.

Could be looks like...
```
<ng-select
    [ngModel]="..."
    [items]="dummyData"
    bindLabel="displayValue"
    bindValue="id"
    bindDisable="isDisabled" <--same key pattern as for label and value-->
>
</ng-select>
```
![grafik](https://user-images.githubusercontent.com/32959361/100858641-8b2e4d80-348e-11eb-8a74-7449c37b7876.png)

**Comment by saurabh47** [comment]
I'm also looking for the same feature.
It will be very useful
