### ISSUE TITLE
please move mouseDown event to host

### ISSUE THREAD

**Issue by steve3d** [ng-select/ng-select#1821]
**Is your feature request related to a problem? Please describe.**
I see in source here:
https://github.com/ng-select/ng-select/blob/dea311f42fca222e640966877cb787ecf251ac22/src/ng-select/lib/ng-select.component.html#L2
the mousedown event is bind to `ng-select-container`'s div, but if I want to make some style change, like add padding to `ng-select`'s element, then when click on the padding space won't open the dropdown, but if `handleMousedown` is a `HostListener` then there will be no problem, it will work better than before.

**Describe the solution you'd like**
make `handleMousedown` a `HostListener` instead of listen to the inner div.

**Describe alternatives you've considered**
seems there is no alternative way when add padding to `ng-select` element.

**Comment by varnastadeus** [comment]
Seems wrong that clicking on an empty space should open a dropdown 🤔

**Comment by steve3d** [comment]
<img width="243" alt="截屏2021-01-08 12 03 22" src="https://user-images.githubusercontent.com/670687/103973068-85bcd500-51a9-11eb-8e92-d166b9b90bde.png">


well, how about this kind of design? I have padding under `ng-select`, the `.ng-container` is in side the padding. 

current design only opens when clicking the container, but is has a padding, click on padding won't open the dropdown.

If i set margin to `ng-container` then I have to set border-radius to every thing inside.

**Comment by steve3d** [comment]
<img width="249" alt="截屏2021-01-08 12 07 54" src="https://user-images.githubusercontent.com/670687/103973335-2612f980-51aa-11eb-8ec1-3f9f70521c68.png">

rendering result.
