### ISSUE TITLE
Custom BindValue

### ISSUE THREAD

**Issue by elvispdosreis** [ng-select/ng-select#1828]
i need my bindvalue to have an object different from the selected one, is that possible?
create a custom function for bindvalue

current results
Selected city: { "id": 2, "name": "Kaunas", **"county": "BRA"** }

expected result
**Selected city: { "id": 2, "name": "Kaunas"}**

[stackbliz](https://stackblitz.com/edit/ng-select-y8hts1)

**Comment by akanzari** [comment]
how can use the output (change)

 <ng-select  [items]="cities"  bindLabel="name"  placeholder="Select city"  [(ngModel)]="selectedCity" (change)="onChange($event)" >

onChange(event) {
    this.selectedCity = { id: event.id, name: event.name }
}
