### ISSUE TITLE
Multiselect placeholder is above the input

### ISSUE THREAD

**Issue by Aspersion** [ng-select/ng-select#183]
Please fill below information if issuing a bug report. 
### Expected behaviour
The placeholder text should not be selectable.

### Actual behaviour
When using the multiselect, you can click on the placeholder and it doesn't allow you to write in the input. This is a bit undesired if the placeholder is as big as the container.

https://plnkr.co/edit/fyFfwCTAUnjdKykfyLub?p=preview

You can try it in the plunkr. Double click on the placeholder, after the dropdown is shown.

### More Info
ng-select version: 0.14.3

browser: Google Chrome 63.0.3239.132 (64-bit)

reproducible in demo page: No

**Comment by anjmao** [comment]
@Aspersion Yeah, good catch. @varnastadeus I'm changing as a bug.
