### ISSUE TITLE
 1000 Record bug: serarch not showing result correctly on certain amount of records

### ISSUE THREAD

**Issue by specchiasoft** [ng-select/ng-select#1831]
**Search  + Virtualscoll not showing records** 

When search a word sometime it does not display anything or does not correctly display the results in the list.
It seems to depend on how many input records we have  for example it is 1000 records it shows nothing the list is too small. But on 1500 or 800 is better.
If disable VirtualScroll the search is slow but show correctly results list.

**Reproducbile example**
in the example search **CER 15**  and see the behavior of the dropdown
https://stackblitz.com/edit/angular-ng-selct-virtualscrollissue?file=src%2Fapp%2Fapp.component.html

**Comment by varnastadeus** [comment]
it happens because 1st item is an empty string which results in an empty span that has no height - since height is not correct, we calculate dropdown height incorrectly :]

**Comment by specchiasoft** [comment]
Thank you very mutch

**Comment by specchiasoft** [comment]
> it happens because 1st item is an empty string which results in an empty span that has no height - since height is not correct, we calculate dropdown height incorrectly :]

the fix for the first empty record worked partially, if you scroll with the down key on the keyboard the scrollbar does not scroll the list.
To investigate this problem I forked ng-select and see that it only tries the first element of the input array, but i think you reduce possibility of empry value  testing some other record. Example : normally the input list is sorted and the first and last do not have the same value testing the last is goood idea but...
If we don't have a complete array but a stream then we might think about testing some other record (the second, and or the third etc) this reduce possibilities of blank record.  
`     const [first,second,third] = this.items;`

The code below is if we have the whole list and in any case it is not the final solution, it reduces the possibility of height error by also measuring the last record.

ng-dropdown-panel.component.ts:

``` 
   private _measureDimensions(): Promise<PanelDimensions> {
        if (this._panelService.dimensions.itemHeight > 0 || this.itemsLength === 0) {
            return Promise.resolve(this._panelService.dimensions);
                                                                                                                                 }

        const [first] = this.items;
        const [last] = this.items.slice(-1); // get last element

        this.update.emit([first, last]);

        return Promise.resolve().then(() => {
            const option = this._dropdown.querySelector(`#${first.htmlId}`);
            const text = option.textContent.replace(/\s+/, ''); // replace empty spaces
            let optionHeight = 16; //  default
// if length of first text is 0 try to get the length of last element 
            if (text.length === 0) {
                const option2 = this._dropdown.querySelector(`#${last.htmlId}`);  
             optionHeight =  option2 == null ?  optionHeight = option.clientHeight : option2.clientHeight;
            } else {
             optionHeight = option.clientHeight;
            }
           this._virtualPadding.style.height = `${optionHeight * this.itemsLength}px`;
            const panelHeight = this._scrollablePanel.clientHeight;
            this._panelService.setDimensions(optionHeight, panelHeight);

            return this._panelService.dimensions;
        });
    }

 ```
