### ISSUE TITLE
update to 11.1.0

### ISSUE THREAD

**Issue by pasblin** [ng-select/ng-select#1843]
**Describe the bug**
HI , 

Could you upgrade package.json angula dependencies versions to 11.1.0?

Regards.

**Reproducbile example**
[Example](https://stackblitz.com) which reproduces described behaviour

**To Reproduce** 
Steps to reproduce the behavior (if example is not provided):

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by varnastadeus** [comment]
#1803

**Comment by pasblin** [comment]
Hi,

In the documentation it says:

>=10.0.0 <11.0.0 | v5.x


But not support 11.1.0 and and this is my question

Regards.
