### ISSUE TITLE
[addTag] fails to allow duplicates

### ISSUE THREAD

**Issue by duzenko** [ng-select/ng-select#1845]
**Describe the bug**
None of the four demo examples allows adding the second item with the same name as the first one.

**Reproducbile example**
[Example](https://ng-select.github.io/ng-select#/tags) which reproduces described behaviour

**To Reproduce** 
Steps to reproduce the behavior (if example is not provided):
1. Go to Demo link above
2. Add 'qwe' to any of the four select's by typing the text
3. Type the same text 'qwe' again. 
4. The control allows to select the first item, but won't add the second one.

**Expected behavior**
There should be some way to add an item with the same text as already contains in the option list

**Screenshots**
![image](https://user-images.githubusercontent.com/1481807/105834075-b2a71f80-5fd2-11eb-85f6-95c0b25bfcab.png)
![image](https://user-images.githubusercontent.com/1481807/105834094-b89d0080-5fd2-11eb-8e74-d3fe9d921f3f.png)

**Comment by varnastadeus** [comment]
you need to make your items unique, then you will be able to add items with the same label. I already answered this question with a code snippet to achieve this behaviour, take a look into old issues.

**Comment by duzenko** [comment]
@varnastadeus A link would be good, or at least a search keyword. Goes without saying I did my search work before posting this.
