### ISSUE TITLE
Initial or default value

### ISSUE THREAD

**Issue by sljovshin** [ng-select/ng-select#1848]
**Is your feature request related to a problem? Please describe.**
The Ng-Select component would be a perfect fit for my project if there was an option to dictate an initial value. Say you are submitting a bug, and you use the Ng-Select to say who the submittion is on behalf of. Most of the time it would be the logged in user(as a initial or default value with label and value). Another scenario is that if I were to open an existing bug, i would like to have the Ng-Select alrady "selceted" with the existing submitter.

**Describe the solution you'd like**
I would like there to be an option to set a "default value" or an "initial value" as you can in the "value" prop om react-select.

**Describe alternatives you've considered**
I tired using NgBind to set an initial value, but it dosent show up in the select.

Thank you
Best Regards
Sondre Ljovshin

**Comment by sljovshin** [comment]
Another scenario is that if I were to open an existing bug, i would like to have the Ng-Select alrady "selceted" with the existing submitter.

**Comment by varnastadeus** [comment]
just set your NgModel with a default value and voilà

**Comment by sljovshin** [comment]
> just set your NgModel with a default value and voilà

Does this work when the default value have a diffrent value and label?

example:
{
     value: "5782833e-67a8-474b-a2f1-46a6edeec520",
     label: "sljovshin"
}
