### ISSUE TITLE
Unexpected extra option in dropdown!

### ISSUE THREAD

**Issue by liwonder** [ng-select/ng-select#185]
Please fill below information if issuing a bug report. 
### Expected behaviour
Can change option items without adding extra one that bind to 'ngModel'.

### Actual behaviour
Step1: Set up 'ng-select' don't set 'bindValue'.
Step2: Select one option in dropdown.
Step3: Change the 'ng-select' option items to a new array.
Step4: You will find the prior selected object was added to the new option list.

### More Info
ng-select version: [0.14.3]

browser: [Chrome 63]

reproducible in demo page: [NO]

**Comment by varnastadeus** [comment]
@liwonder it works as expected. If your selected model doesn't exists among options list, it gets added to list so you can have pre-selected model even if your data is not loaded yet.

**Comment by liwonder** [comment]
@varnastadeus Thanks for your reply! I understand the design, but it will an annoying feature for me. What can I do to prevent the pre-selected model add to my data list? It seems setting the model to 'undefined' doesn't work.

**Comment by varnastadeus** [comment]
@liwonder are you using async data?

**Comment by liwonder** [comment]
@varnastadeus yes, I am using async data, but I think the point is there is demand that to change the dataset of the select during run time. So the data will not always be the initial data.

I have three 'ng-select' in one page, and they are linkage, the selection of previous select will change the dataset of next one to a new array of data, so when the data set is changed I don't want the previous selection add the current option list. Do I make this situation clear?

**Comment by varnastadeus** [comment]
@liwonder yes, it's pretty much clear. Have you tried clearing your `NgModel` before setting new items?

**Comment by sieglejp** [comment]
@liwonder I had this same issue when using ngModel, I switched to reactive forms and the previously selected item from the old data list does not get added to end of the new data list.

**Comment by varnastadeus** [comment]
@anjmao there is actual bug here. Even if you clear selected model, selected items are added to options since `writeValue` is executed after `ngOnChange`.

https://plnkr.co/edit/KfEuBt9TdawYEDoKMBNc?p=preview

**Comment by anjmao** [comment]
@varnastadeus thanks for good repro. I will have a look.

**Comment by liwonder** [comment]
@anjmao Thanks for your repo to clarify this issue! It's really a busy week, rarely have time to check my unread list, sorry for that!

**Comment by anjmao** [comment]
@liwonder Hi, I just pushed ng-select 0.16 version to npm which should fix this bug. Feel free to reopen it or create new one if you still have issues :)

**Comment by liwonder** [comment]
@anjmao Thanks, I will check it out!
