### ISSUE TITLE
@ng-select/ng-option-highlight" has an incompatible peer dependency to "@angular/core" (requires "^>=10.0.0 <11.0.0", would install "11.1.2")

### ISSUE THREAD

**Issue by bjornharvold** [ng-select/ng-select#1853]
Bump Angular version peerDependency on ng-option-highlight

**Comment by EddieBenji** [comment]
Yes, please. A similar fix has been pushed to @ng-select/ng-select lib (https://github.com/ng-select/ng-select/issues/1803)
That would be great.
Thanks

**Comment by cristiammercado** [comment]
Hi, 

Any workaround for this?

**Comment by rogerza** [comment]
Can you publish this, please? 🙏🏼  
https://github.com/ng-select/ng-select/pull/1844

**Comment by terencehonles** [comment]
@varnastadeus can we get `@ng-select/ng-option-highlight` published? We're also right near Angular 12, so we may need a subsequent publish not too much later.

**Comment by terencehonles** [comment]
Alternatively does it make sense to merge this back into @ng-select/ng-select so it can be released at the same time? Tree shaking should handle code minification and merging it back in will help with the lack of updates this package has had.

**Comment by jspivack** [comment]
This seems like an easy fix, is there a reason it can't move forward? The incompatibility is breaking our entire dependency chain.

**Comment by niteshgoyal27390** [comment]
Stuck with only this legacy peer dependency. Trying to upgrade Angular to v14 and stuck with this error - 
```
`Could not resolve dependency:
npm ERR! peer @angular/common@">=13.0.0 <14.0.0" from @ng-select/ng-option-highlight@0.0.7
npm ERR! node_modules/@ng-select/ng-option-highlight
npm ERR!   @ng-select/ng-option-highlight@"0.0.7" from the root project`
```

Any leads other than using the command with --force, or --legacy-peer-deps
