### ISSUE TITLE
NgSelectConfig notFoundText cannot update

### ISSUE THREAD

**Issue by emreyavuz369** [ng-select/ng-select#1855]
**Describe the bug**
I want to change notFoundText on config. I have onChangeLang subscription and i change ngSelectConfig notFoundText but text is not changing.

**Reproducbile example**
[Example]https://stackblitz.com/edit/ng-select-not-fount-text-not-working?file=src/bindings-default-example.component.ts

**To Reproduce** 
1. Go to 'https://stackblitz.com/edit/ng-select-not-fount-text-not-working?file=src/bindings-default-example.component.ts'
2. Click on 'select combo'
3. Search something not in data and show 'Not Found' text
4. Put 'Change Text' button (it adds number to text)
5. See text has not changed

**Expected behavior**
Expect to change text

**Desktop (please complete the following information):**
 - Browser [chrome]
 - Version [6.0.0]

**Comment by varnastadeus** [comment]
config is not something you can change dynamically

**Comment by emreyavuz369** [comment]
So i write everywhere [notFoundText]?

**Comment by varnastadeus** [comment]
if you want to change it dynamically, then yes
