### ISSUE TITLE
Options not show properly when wrapped inside mat-expansion-panel

### ISSUE THREAD

**Issue by esdegan50000** [ng-select/ng-select#1858]
https://stackblitz.com/edit/angular-fdfftg?file=src/data-source-array-example.component.html

![Selection_085](https://user-images.githubusercontent.com/42486685/107735724-f7e98200-6d32-11eb-9d6f-2089a42c99c7.png)

**Comment by tndungu** [comment]
Also experiencing same issue.

**Comment by varnastadeus** [comment]
use `appendTo="body"`

**Comment by Spri85** [comment]
if we appended to body, we will get another issue duaring scrolling

**Comment by Spri85** [comment]
![image](https://user-images.githubusercontent.com/12323679/116707950-e467c200-a9d7-11eb-97f1-0cb7f8fbf5ab.png)
