### ISSUE TITLE
Request: Children

### ISSUE THREAD

**Issue by jocelynduc** [ng-select/ng-select#186]
I would like to use ng-select with "children" as we can do with:
https://optimistex.github.io/ng2-select-ex/

Is this available? on the roadmap?

**Comment by varnastadeus** [comment]
@jocelynduc it doesn't seem to work there. Can you describe what this feature is about?

**Comment by jocelynduc** [comment]
I put a new example where the feature is actually working:
https://optimistex.github.io/ng2-select-ex/

The idea of this feature is to group options. In the example, you can see that the cities are grouped by country. Have a look at it, it speaks by itself
It should act the same as <optgroup /> in a pure <select /> element.

Only the children are effectively selectable.
```
public items: any[] = [
    {
      id: 100,
      text: 'Austria',
      children: [
        {id: 54, text: 'Vienna'}
      ]
    },
    {
      id: 200,
      text: 'Belgium',
      children: [
        {id: 2, text: 'Antwerp'},
        {id: 9, text: 'Brussels'}
      ]
    },
   ...
}
```

**Comment by varnastadeus** [comment]
I think you can achieve similar result with custom option templates, since it is just styling.

**Comment by anjmao** [comment]
@varnastadeus If you will be able to create example on demo page with items grouping and custom templates that would be great.

**Comment by carlhussey** [comment]
Any update on this? I believe it will just need to act the same as **optgroup** in vanilla html.

```
<select>
  <optgroup label="Swedish Cars">
    <option value="volvo">Volvo</option>
    <option value="saab">Saab</option>
  </optgroup>
  <optgroup label="German Cars">
    <option value="mercedes">Mercedes</option>
    <option value="audi">Audi</option>
  </optgroup>
</select>
```

**Comment by anjmao** [comment]
Hi @carlhussey, I started working on this, home will implement it during this or next week.

**Comment by MadJlzz** [comment]
I made a simple workaround to do what you're expecting while waiting for the native feature.

    <ng-select class="custom"
               [searchable]="true"
               placeholder="Select Option Type">
      <ng-template ngFor let-optionType [ngForOf]="optionTypeMock">
        <ng-option [disabled]="true" value="optionType">-- {{ optionType.category }} --</ng-option>
        <ng-option *ngFor="let style of optionType.styles" value="style">{{ style }}</ng-option>
      </ng-template>
    </ng-select>

With a JSON object:

```
optionTypeMock = [
  {
    category: 'VANILLA',
    styles: [
      'EUROPEAN'
    ]
  }
];
```

**Comment by anjmao** [comment]
I just pushed support for grouping items with `groupBy` https://ng-select.github.io/ng-select#/grouping Now internals are ready for children  support.

**Comment by MadJlzz** [comment]
@anjmao Updated your library version and already using it !

**Comment by achimha** [comment]
I'm very much favor of an `optgroup` tag! There are situations where it's much more convenient to use markup to define the list than a data structure and benefit from the template engine in Angular.

**Comment by newprogrammer1991** [comment]
Hi, Can I make like dropdown  - click by country and show citiyes ?

**Comment by newprogrammer1991** [comment]
??

**Comment by saurabh47** [comment]
I'm also looking for `ng-option-group` tag.
so we can define template like. **Is this tag available in this library ?**
```
<ng-select>
  <ng-option-group label="Swedish Cars">
    <ng-option value="volvo">Volvo</ng-option>
    <ng-option value="saab">Saab</ng-option>
  </ng-option-group>
  <ng-option-group label="German Cars">
    <ng-option value="mercedes">Mercedes</ng-option>
    <ng-option value="audi">Audi</ng-option>
  </ng-option-group>
</ng-select>
```
