### ISSUE TITLE
Label not showing after value change

### ISSUE THREAD

**Issue by all2pie** [ng-select/ng-select#1863]
**Description**

When value is changed programatically after the initialization of the component, the ng-select dose not show the label.

**Reproducbile example**
[Example](https://stackblitz.com/edit/ng-select-jtyjte?file=app/app.component.ts) which reproduces described behaviour

**Comment by nmifzal** [comment]
Add this CSS to ur style.css or your root CSS file


`.ng-select.ng-select-single .ng-select-container .ng-value-container, .ng-select.ng-select-single .ng-select-container .ng-value-container .ng-value {
  z-index: 1;
}`

**Comment by all2pie** [comment]
Hi, tried this but it's not a style issue, as i inspected and there isn't
any value in html also.
