### ISSUE TITLE
Material theme does not match official material controls

### ISSUE THREAD

**Issue by shawnshaddock** [ng-select/ng-select#1868]
When using the material theme, ng-select looks "similar" to official material components such as mat-select, but not exactly. This is an issue when using ng-select with other angular material components as it stands out. The most prominent issue is the size of the control. The height is taller than a mat-select. It's most noticeable when two components are placed side by side, you can see they don't line up. I've attached a screenshot demonstrating the issue.

![image](https://user-images.githubusercontent.com/6936864/110057629-ec381c80-7d2e-11eb-97a0-d61c20ecfe69.png)

**Comment by swetankrathi** [comment]
Same issue here. I am applying appearance="outline" and differences are quite visible. IN the screenshot attached, at the left I have _mat-select_ and at the right it is _ng-select_.

![Screenshot from 2021-03-08 13-36-39](https://user-images.githubusercontent.com/12524146/110293031-12520b00-8014-11eb-816f-18b529be8e43.png)

**Comment by swetankrathi** [comment]
@varnastadeus 
Any plan to fix this in near future?
