### ISSUE TITLE
Can't input blanks when hideSelected is true and items are empty

### ISSUE THREAD

**Issue by Thessi** [ng-select/ng-select#1869]
**Describe the bug**
Blanks/Spaces can't be input if the list of items is empty (null / empty array) and the hideSelected option is set.

**Reproducible example**
https://stackblitz.com/edit/angular-xeeavj?file=src/app/app.component.html

**Desktop:**
Tested on
 - OS: Windows 10
 - Browser: Chrome
 - Version: 88

**Comment by Thessi** [comment]
The hideSelected comes into play here https://github.com/ng-select/ng-select/blob/master/src/ng-select/lib/items-list.ts#L45
which in turn makes this condition true https://github.com/ng-select/ng-select/blob/master/src/ng-select/lib/ng-select.component.ts#L412
Since it returns here, `isOpen` will never be set to true (three lines below) if the result list is empty.
Because of this, this condition will always be false https://github.com/ng-select/ng-select/blob/master/src/ng-select/lib/ng-select.component.ts#L879
and the input will therefore always be prevented.

Can someone explain why we would ever `preventDefault` here? https://github.com/ng-select/ng-select/blob/master/src/ng-select/lib/ng-select.component.ts#L883
Git blame didn't give me a hint either.

An example use case to give this more context:
Say we use ng-select to search for movies. Those are dynamically loaded from a backend. Because of the large number of movies, we only start the search once the user has input four or more characters.
If the user wants to search for "The Dark Knight", he/she will input "The", but pressing space, nothing happens. This is unexpected and breaks the select, since the dropdown will only open once data was loaded, which happens on the fourth character input.

**Comment by daviian** [comment]
We face the exact same issue at the moment. Does nobody care about this?
