### ISSUE TITLE
[(ngModel)] not works: Can't bind to 'ngModel' since it isn't a known property of 'ng-select'.

### ISSUE THREAD

**Issue by Nekmo** [ng-select/ng-select#187]
I'm trying to use the official example, but I can not make it work. The example and the page not load. This error message appears in console:

```
Uncaught Error: Template parse errors:
Can't bind to 'ngModel' since it isn't a known property of 'ng-select'.
1. If 'ngModel' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("

           placeholder="Select city"
           [ERROR ->][(ngModel)]="selectedItem"
           >
</ng-select>
"): ng:///SalesModule/SaleListComponent.html@5:11
    at syntaxError (compiler.js:485)
    at TemplateParser.parse (compiler.js:24661)
    at JitCompiler._parseTemplate (compiler.js:34601)
    at JitCompiler._compileTemplate (compiler.js:34576)
    at eval (compiler.js:34477)
    at Set.forEach (<anonymous>)
    at JitCompiler._compileComponents (compiler.js:34477)
    at eval (compiler.js:34347)
    at Object.then (compiler.js:474)
    at JitCompiler._compileModuleAndComponents (compiler.js:34346)
```

My code:

```

<ng-select [items]="cities"
           bindLabel="name"
           bindValue="id"

           placeholder="Select city"
           [(ngModel)]="selectedItem"
           >
</ng-select>
```

And:
```
import { Component, OnInit } from '@angular/core';
import {NgOption} from "@ng-select/ng-select";

@Component({
  selector: 'sale-list',
  templateUrl: './sale-list.component.html',
  styleUrls: ['./sale-list.component.css']
})
export class SaleListComponent implements OnInit {

    cities: NgOption[] = [
        {id: 1, name: 'Vilnius'},
        {id: 2, name: 'Kaunas'},
        {id: 3, name: 'Pabradė'},
        {id: 3, name: 'Klaipėda'},
        {id: 3, name: 'Nida'}
    ];
    selectedItem: any;

  constructor(
  ) { }

  ngOnInit() {
      this.selectedItem = this.cities[0].id;
  }

}
```

The example works fine when I remove the label ``[(ngModel)]``. The page also works and there is no error using `(ngModel)`, but the one-bind does not seem to work. ``[ngModel]`` also causes the error.

Packages:

```{
  "name": "xxxxx",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve --proxy-config proxy.conf.js",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.1.0",
    "@angular/common": "^5.1.0",
    "@angular/compiler": "^5.1.0",
    "@angular/core": "^5.1.0",
    "@angular/forms": "^5.1.0",
    "@angular/http": "^5.1.0",
    "@angular/platform-browser": "^5.1.0",
    "@angular/platform-browser-dynamic": "^5.1.0",
    "@angular/router": "^5.1.0",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-beta.9",
    "@ng-select/ng-select": "^0.11.0",
    "bootstrap": "^4.0.0-beta.3",
    "core-js": "^2.4.1",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@angular/cli": "1.6.4",
    "@angular/compiler-cli": "^5.1.0",
    "@angular/language-service": "^5.2.0",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3"
  }
}
```
Project using Angular Cli.
ng-select version: latest version and 0.11.0.
browser: Chromium 63.0.3239.108
reproducible in demo page: NO

**Comment by Nekmo** [comment]
Resolved including modules:

```
        FormsModule,
        ReactiveFormsModule,
```

**Comment by akshayinnopix** [comment]
@Nekmo do I include these modules in `app.module.ts` or in the component I want to add ng-select.

**Comment by fayazrehmani** [comment]
@Nekmo 
It would be nice if you can specify which file you have added the code. As I am having same issue while doing angular sample project from angular.io. Since I have just started angular don't have any clue of its core terms that's why.

**Comment by Nekmo** [comment]
Add to your module file.

**Comment by apostrophesoftware** [comment]
@Nekmo, @fayazrehmani is correct!  Please show how you have resolved this with a code snippet.  I am seeing the same problem and am unable to get the reference to be recognised with this lines added to app.modules.ts
`import { FormsModule } from '@angular/forms';
import { ReactiveFormsModule } from '@angular/forms';
`

Thanks

**Comment by ATR3U5** [comment]
Hey guys! I just ran into the same issue and thought i'd clear it up, since this thread still seems to be going on!
In the Angular tutorial, you need to add "FormsModule" to your app.module.ts file -> this will resolve everything. 

**Here's what your code should look like in app.module.ts at this point:**

import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppComponent } from './app.component';
import { HeroesComponent } from './heroes/heroes.component';
import {FormsModule} from '@angular/forms';

@NgModule({
  declarations: [
    AppComponent,
    HeroesComponent
  ],
  imports: [
    BrowserModule,
    _FormsModule_
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

**All I did was add "FormsModule" below "BrowserModule". Cheers and happy learning!**

**Comment by jbiddulph** [comment]
I'm having this issue, I added FormsModule and ReactiveFormsModule to app.module.ts and to the actual module file... I am still getting the error?!

**Comment by kokoosso** [comment]
@jbiddulph  add form modules to you app-routing modules, that work with me

**Comment by Hearen** [comment]
check this [answer](https://stackoverflow.com/a/54198136/2361308)

**Comment by PatelAshish1** [comment]
import { FormsModule } from '@angular/forms';

[...]

@NgModule({
imports: [
[...]
FormsModule
],
[...]
})

Full Source Code At [Here](https://icetutor.com/question/cant-bind-to-ngmodel-since-it-isnt-a-known-property-of-input)

**Comment by joandylevi** [comment]
import { FormsModule } from '@angular/forms';

[...]

@NgModule({
imports: [
[...]
FormsModule
],
[...]
})

Full code Available [Here](https://icetutor.com/question/cant-bind-to-ngmodel-since-it-isnt-a-known-property-of-input/)

**Comment by kmkrish007** [comment]
after importing the fomrsmodule issue resolved.

import { FormsModule } from '@angular/forms';

**Comment by Alnooria** [comment]
> I'm having this issue, I added FormsModule and ReactiveFormsModule to app.module.ts and to the actual module file... I am still getting the error?!

am also having the same issue

**Comment by Awais-mohammad** [comment]
ng serve again :P

**Comment by shahnisargweb** [comment]
i dont but i also add  formsmodule and reactiveformsmodule but still getting error in angular9
if i can unistall and install agin it will not giveme errors for some time i dont whats happen with it 
pl give me supoort .......

**Comment by notreniev** [comment]
> @jbiddulph add formModule to you app-routing modules, that work with me

It also worked for me but I don't understand why... Why this worked injecting FormsModule on app-routing?

**Comment by shahnisargweb** [comment]
i found exact and best solution 
(1) ...  you shoude add forms module in your component module 
(2)  you must call your module in app module file
(3) check your rxjs version 
(4) go to package.json file and 
in rxjs setting 
do this 
"rxjs": "6.5.4", 
remove ~ this 
before : "rxjs": "~6.5.4",
after :"rxjs": "6.5.4",
 thank you if you like follow me 
https://github.com/shahnisargweb

**Comment by shahnisargweb** [comment]
> I'm having this issue, I added FormsModule and ReactiveFormsModule to app.module.ts and to the actual module file... I am still getting the error?!

https://github.com/ng-select/ng-select/issues/187#issuecomment-936022886

**Comment by stephangopaul** [comment]
For me I had to update VS Code. 🤷🏾‍♂️

**Comment by halilnevzat** [comment]
> For me I had to update VS Code. 🤷🏾‍♂️

there no updates for me im still having the issue. im gonna lose my mind.

**Comment by shahnisargweb** [comment]
THIS IS NOT issue of vs code update maybe its isuue something  differe email your code so i can check or give me link of github

**Comment by KarameiOmid** [comment]
If you are using Angular lazy loading you need to import "FormsModule" in each module instead of "app.module.ts" otherwise you keep getting this error.

**Comment by rondeniable** [comment]
For this to work, you have to have the FormsModule properly installed as noted by @ATR3U5. 

That said, while this made the application work for me, I found that VSCode was still reporting the error in sub-components. To solve, I upgraded VSCode.

**Comment by afrasamrin** [comment]
I have tried many things, imported FormsModel in all components, ......., But adding this worked for me in Angular.

import { NgModule, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core'; add schemas: [ CUSTOM_ELEMENTS_SCHEMA `],```

import { NgModule, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { HttpClientModule } from '@angular/common/http';

import { AppRoutingModule } from './app-routing.module';


@NgModule({
  declarations: [
    AppComponent,
    
  ],
  imports: [
    BrowserModule,
    FormsModule,
    ReactiveFormsModule,
   
  ],
  schemas: [
    CUSTOM_ELEMENTS_SCHEMA
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

**Comment by FelipeCarriel** [comment]
In my case, the problem was the version of the VSCode extension: Angular Language service
