### ISSUE TITLE
keyDownFn does not work with alphanumeric characters

### ISSUE THREAD

**Issue by danwellman** [ng-select/ng-select#1874]
**Describe the bug**
Function added using `[keyDownFn]` only work with non-alphanumeric keys like enter, escape, and space

**Reproducbile example**
https://angular-ivy-nprxag.stackblitz.io

**To Reproduce** 
Steps to reproduce the behavior (if example is not provided):
1. Go to https://angular-ivy-nprxag.stackblitz.io
2. Open the StackBlitz console at the bottom of the emdedded browser
3. Click on the ng-select to open the menu
4. Type a letter key and observe that there are no logs in the console
5. Press ESC, or ENTER, or SPACE and observe that logs appear in the console

**Expected behavior**
Any key should trigger the keyDownFn, or the documentation should be updated to describe that the handler you assign to keyDownFn will only trigger on non-alphanumeric key-strokes. Optionally, make the keyDownFn function work with alphanumeric keys

**Desktop (please complete the following information):**
 - OS: Windows 10 (and whatever OS stackblitz is using)
 - Chrome (and whatever browser is embedded in stackblitz)

**Comment by Vijay-Nirmal** [comment]
+1 It won't work for Function keys as well
