### ISSUE TITLE
filter on multiple fields

### ISSUE THREAD

**Issue by jpmyob** [ng-select/ng-select#188]
### Feature request
Would be nice to "filter" on multiple fields, such as "firstName" and "lastName" - so that "John" would match John Smith, and Victor Johnson.

**Comment by varnastadeus** [comment]
@jpmyob it is already possible, you just need to use typeahead and subscribe to term change, and after that filter on any items you want.

**Comment by jpmyob** [comment]
Hum, ok i;ll try

**Comment by varnastadeus** [comment]
@jpmyob I updated demo page showing how to achieve this, you can check here https://github.com/ng-select/ng-select/blob/master/demo/app/examples/search.component.ts
