### ISSUE TITLE
Mouse over drop-down items triggers change detection throughout whole application

### ISSUE THREAD

**Issue by vladislavaleksic88** [ng-select/ng-select#1886]
When the mouse is moved over drop-down items of ng-select, change detection is triggered in the whole application. This is causing every method in every component that is not with the "onPush" change detection strategy to be recalculated. This is causing big performance issues.

**Reproducible example**
[https://stackblitz.com/edit/angular-ivy-4dmxmn?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-ivy-4dmxmn?file=src/app/app.component.ts)
This is a simple example. the "ng-select" element is added via ExampleComponent. You can check the "someTemplateMethod()" method in AppComponent. There is a console log that shows the bug when you mouse over drop-down items.

**Comment by sviluppo** [comment]
+1 
Any news regarding this bug??
