### ISSUE TITLE
ng-tag-label translation

### ISSUE THREAD

**Issue by Mario-Greiner** [ng-select/ng-select#1888]
Is there a way that i can translate/change the text from span with class ng-tag-label?

**Comment by sandhyaranihegde** [comment]
Following up in the @Mario-Greiner comment. I wanted to change ng-tag-label value dynamically and translate it. Is it possible ?

**Comment by sandhyaranihegde** [comment]
@Mario-Greiner  did you manage to find any way to change/translate the text on  ng-tag-label?

**Comment by Mario-Greiner** [comment]
> @Mario-Greiner did you manage to find any way to change/translate the text on ng-tag-label?

Sorry wasn't on GitHub for a while. I don't remember if I have a solution but I will check my code again and post it here if I have on.
