### ISSUE TITLE
Upgrade to Angular 12

### ISSUE THREAD

**Issue by Tea-Ice** [ng-select/ng-select#1901]
**Is your feature request related to a problem? Please describe.**
This package causes peer dependency issues on Angular 12, but the component seems to work fine if I force the warnings.

**Describe the solution you'd like**
Update the peer dependencies, maybe looking into converting it into an Ivy Component

**Comment by tam-4xlabs** [comment]
yeah, I got the same issue. Pls update on this.

Thank you!

**Comment by sebastian-zarzycki-es** [comment]
Bump!

**Comment by pavankjadda** [comment]
@varnastadeus Any update on this. Please merge the PR #1903

**Comment by keyone2693** [comment]
Any update on this ؟

**Comment by buleglay** [comment]
Bump +1

**Comment by anthonyliriano** [comment]
Bump +1

**Comment by gopak** [comment]
Bump +1

**Comment by lionel-meunier** [comment]
+1

**Comment by aintnomoreloyalty** [comment]
Bump +1

**Comment by pavankjadda** [comment]
@varnastadeus Even after updating to 7.0.0 I still see the following error

<img width="1275" alt="Screen Shot 2021-06-11 at 11 27 01 AM" src="https://user-images.githubusercontent.com/17564080/121710834-f6915180-caa7-11eb-9974-ec95df74d14a.png">

**Comment by sysmat** [comment]
Generating browser application bundles (phase: setup)...Processing legacy "View Engine" libraries:

@ng-select/ng-select [es2015/esm2015] (git+https://github.com/ng-select/ng-select.git)

ng 13
