### ISSUE TITLE
Can't use 'text-overflow: ellipsis' in 'ng-multi-label-tmp'

### ISSUE THREAD

**Issue by Xaspy** [ng-select/ng-select#1905]
I have table and multiple select filter for one of the row. Then I change my resolution to small ng-multi-table-tmp doesn't have overflow - it's just moving clear button out from block and few pixels down (I tried change css, but it isn't works). In single select long text have been overflowing.
Simulate small resolution by long text, stackblitz here: https://stackblitz.com/edit/ng-select-problem?file=app/app.component.ts

**Comment by WilliamAguera** [comment]
That's because you must have a defined width on ng-value class -> `max-width : 200px;`
and then, on your "chosen-num" class ->  `overflow: hidden; text-overflow: ellipsis;`
![image](https://user-images.githubusercontent.com/1606954/120333482-1c5b7100-c2c6-11eb-8758-664196bc8347.png)

**Comment by Xaspy** [comment]
@WilliamAguera Hi! Thanks for your answer. Do you know any techniques where I can keep number of selected things with overflow text ellipsis?
