### ISSUE TITLE
Selected value and Drop down options are not visible with Angular v11 Testing. 

### ISSUE THREAD

**Issue by ambujkhanna** [ng-select/ng-select#1909]
Hi

Functionality is perfectly working but when I am writing test cases then it is not working.

Case 1: Selected Values are defined to variable and printing in console but tokens are not visible

Case 2: Dropdown list is assigned but when clicking on dropdown icon then List is not found/visible.

Is there anything needs to import or declare for testing purpose?
```

<ng-select
        [items]="items" 
        [multiple]="multiple" 
        [disabled]="disabled" 
        [hideSelected]="hideSelected"
        [(ngModel)]="activeItems"
        (change)="onData($event)"
        (remove)="onRemove($event)"
        (add)="onSelect($event)" 
        (search)="onSearch($event)" 
        placeholder="{{ placeholder | translate }}" 
        class="custom-multiselect" 
        bindLabel="text"
        bindValue="id" 
    >

        <ng-template ng-label-tmp let-item="item" let-clear="clear">
        <span class="ng-value-label">{{ getItemDisplayText(item.text) | translate }}
        </span>
        <span class="ng-value-icon right" (click)="clear(item)" aria-hidden="true">
            <fa-icon [icon]="faTimes"></fa-icon>
        </span>
    </ng-template>

    <!-- Dropdown Suggestion list -->
    <ng-template ng-option-tmp let-item="item" let-search="searchTerm">
        <span [ngOptionHighlight]="search">{{ getItemDisplayText(item.text) | translate }}</span>
    </ng-template>
    </ng-select>
```

**Comment by ambujkhanna** [comment]
@varnastadeus Do we need to mock anything or Dropdown?

**Comment by ambujkhanna** [comment]
I got the solution of my query.
It did not listen `click` event on `ng-select` element or it's child DIV elements so I target to Input Element and triggered `input` event instead `click`. Finally it worked for me.

```
const NG_SELECT_INPUT_ELEMENT= By.css('.ng-input input');

const uiSelectSearchDropdownMenu = fixture.debugElement.query(NG_SELECT_INPUT_ELEMENT);

uiSelectSearchDropdownMenu.nativeElement.dispatchEvent(new Event('input'));
```

I hope it may help someone!

**Comment by JeviScript** [comment]
> I got the solution of my query. It did not listen `click` event on `ng-select` element or it's child DIV elements so I target to Input Element and triggered `input` event instead `click`. Finally it worked for me.
> 
> ```
> const NG_SELECT_INPUT_ELEMENT= By.css('.ng-input input');
> 
> const uiSelectSearchDropdownMenu = fixture.debugElement.query(NG_SELECT_INPUT_ELEMENT);
> 
> uiSelectSearchDropdownMenu.nativeElement.dispatchEvent(new Event('input'));
> ```
> 
> I hope it may help someone!

I love you man, I spent an entire day trying to figure it out why my unit tests don't want to work with ng-select via click events. I still don't get it why, but at least I made it work with 'input' event
