### ISSUE TITLE
@ng-select/ng-option-highlight has not been bumped/published after upgrading to Angular 11

### ISSUE THREAD

**Issue by kfrancois** [ng-select/ng-select#1911]
**Describe the bug**

The peerDependencies of `ng-option-highlight` were bumped in https://github.com/ng-select/ng-select/commit/d368b3ef30a6739e43eb7bbac223aa6fb1f3cb12 but unfortunately no new version of this package has been released. This leads to issues on NPM 7 when installing dependencies as `@ng-select/ng-option-highlight@0.0.6` expects `@angular/common` to be on version 10.

This can by bypassed by either

- Using NPM 6
- Installing with `--legacy-peer-deps` so NPM 7 ignores the unmet peerdependency

**To Reproduce** 
1. Start an Angular 11 project
2. Install @ng-select/ng-option-highlight

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/17174086/119893207-61387e00-bf3b-11eb-9555-ff93f4c63a50.png)

**Desktop:**
- Node version: `15.12.0`
- NPM version: `7.8.0`

**Comment by ambujkhanna** [comment]
I installed around 2 week back in my project and it is working for me with Angular v11
`"@ng-select/ng-option-highlight": "0.0.6",`

**Comment by kfrancois** [comment]
Sorry, I didn't mention my Node/NPM versions - I'll update the original message as this is only an issue as of NPM 7

**Comment by rogerza** [comment]
Still getting this error with node `14.17.4` with npm  `7.20.3`. Can you please update the package version? 🙏🏼

**Comment by daniel-seitz** [comment]
Fyi: There is a change and I believe a PR for this however nobody seems to be able to merge/publish.

For this reason and because I have this since ng11, I created a workaround you can find in https://github.com/ng-select/ng-select/issues/1943

Maybe that's helpful. I just think: If this is such a small functionality, we shouldn't be waiting forever and just implement the highlight ourselves.

**Comment by daniel-seitz** [comment]
Well actually this is not resolved yet. Who has the rights to do this?
