### ISSUE TITLE
dropdown height cuts off multiline values

### ISSUE THREAD

**Issue by jpike88** [ng-select/ng-select#1916]
Using latest ng-select:

See image:

<img width="439" alt="Screenshot 2021-06-11 at 7 10 58 PM" src="https://user-images.githubusercontent.com/9585787/121684348-c28a5080-cae8-11eb-95fb-4dbb765be593.png">

It would be better if the dropdown knew where to cut off, so it's not cutting off partially through an item.

**Comment by ricking007** [comment]
Ainda tenho o memo problem, alguém me ajuda?? socorro.....
