### ISSUE TITLE
Need option to add new item

### ISSUE THREAD

**Issue by arun-maddheshia** [ng-select/ng-select#192]
### Expected behaviour
I select an address from list suppose if I want to add a new address which is not in list I have a button to add the new address upon click on it I have a modal or some page to add my new address.

### Actual behaviour
There is no option to add a custom button inside dropdown to perform other actions.

### More Info
ng-select version: LATEST

**Comment by anjmao** [comment]
Hi @arun-maddheshia There is Pull Request which will allow to have custom header and footer templates https://github.com/ng-select/ng-select/issues/184 Is this is what you are looking for?

**Comment by arun-maddheshia** [comment]
not sure how footer template works, so I need something a custom button in footer on which I perform my basic click actions.

**Comment by arun-maddheshia** [comment]
@anjmao when you plan to merge the #193

**Comment by anjmao** [comment]
After it passed code review. It will be merged today or tomorrow :)

**Comment by anjmao** [comment]
@arun-maddheshia checkout 0.15.1 npm version.

**Comment by arun-maddheshia** [comment]
Yo It's work like charm!

**Comment by arun-maddheshia** [comment]
can we change its fixed position to at the bottom of list if possible.

**Comment by varnastadeus** [comment]
@arun-maddheshia what do you mean?

**Comment by arun-maddheshia** [comment]
for now the `ng-footer-tmp` is fixed to bottom I just want to move it in virtual scroll so its looks like it is in item array option

**Comment by varnastadeus** [comment]
@arun-maddheshia I think you are using wrong templates, `ng-footer-tmp` is designed specifically for footer. Have you tried using `ng-option-tmp` and then adding your custom html there?

**Comment by arun-maddheshia** [comment]
@varnastadeus but in this case my custom stuff comes inside the first index, and my custom stuff has an event. any way close it I go with footer template its ideal case.
