### ISSUE TITLE
Showing loading indicator on the options

### ISSUE THREAD

**Issue by chandrn** [ng-select/ng-select#1928]
**Is your feature request related to a problem? Please describe.**
Is it possible to show the loading indicator over the options?
The use case I have is that new options are fetched on an external action while the dropdown is still open by setting the property `[closeOnSelect]="false"`
As shown in the last example here [Templates](https://ng-select.github.io/ng-select#/templates), loading indicator shows only on the label and the user can still select the options.
![image](https://user-images.githubusercontent.com/22908067/124118458-fc6ac900-da8e-11eb-93fd-ec874b792fd2.png)

**Describe the solution you'd like**
An option to show the loading indicator over the options.

**Describe alternatives you've considered**

- Disabling all the options until new options are fetched.
- Hiding the entire element

**Comment by mgohin** [comment]
Can it be reopened ?
