### ISSUE TITLE
Multiple inputs in a form prevents addition of tags on Android

### ISSUE THREAD

**Issue by Chocobozzz** [ng-select/ng-select#1932]
Hi,

First of all thanks for this library. It's really useful for our project.

**Describe the bug**

In tag mode, we can't add tags on Chrome Android if the `ng-select` input is in a form and has a next input element.
The issue I think is that chrome detects a classic input, so the `Go` button becomes a `Next` button in the AOSP keyboard. Then, instead of firing an `Enter` key event, Chrome just moves the cursor in the next element.

**To Reproduce** 
Steps to reproduce the behavior (if example is not provided):
1. Go to https://stackblitz.com/edit/angular-hcjucj using Chrome on Android
2. Click on the first input, write a tag and press enter
3. The cursor is moved in the second element and the tag is not added

**Expected behavior**

A tag should be added in the first element instead.

**Smartphone (please complete the following information):**
 - Device: Moto G4
  - OS: Android 10
 - Browser: Chrome
 - Version: 91

**Additional context**

I'm not sure how to fix this behaviour, since chrome does not fire any event in this context...

**Comment by Chocobozzz** [comment]
Still an issue

**Comment by Chocobozzz** [comment]
Still an issue

**Comment by Chocobozzz** [comment]
Still an issue

**Comment by Chocobozzz** [comment]
Still an issue

**Comment by Chocobozzz** [comment]
Still an issue

**Comment by averymd** [comment]
Still an issue.

**Comment by Chocobozzz** [comment]
Still an issue

**Comment by Chocobozzz** [comment]
Still an issue

**Comment by Chocobozzz** [comment]
Still an issue

**Comment by xundeenergie** [comment]
This is still an issue un June 2024
