### ISSUE TITLE
Selected value not get cleared  when setValue the form control when using editableSearchTerm

### ISSUE THREAD

**Issue by ackalhan** [ng-select/ng-select#1933]
**Describe the bug**
Set the ng-select _editableSearchTerm_ to true. and then try to setValue the from control, actual value of the control gets update correctly but in the ui, previous selected value is still there

**Reproducbile example**
https://stackblitz.com/edit/angular-zjjan7

- Select an option - **Value of the control:** gets updated to correct selected value.
- Click reset button - **Value of the control:** gets updated to correct value, but in the ui old selected value is still selected.
- Remove _editableSearchTerm_ and do the above steps - All working fine as expected.

**Expected behavior**
When doing setValue the formControl. It should clear the selected value in ui.

**Comment by hade94** [comment]
+1
