### ISSUE TITLE
ng-option-highlight after Angular12 update

### ISSUE THREAD

**Issue by kkappis** [ng-select/ng-select#1937]
after updating to angular12 and ng-select 7.2.0 i get this fields when installing ng-option-highlight.
here is apparently not yet a version for Angular 12.

**To Reproduce** 
```
npm install --save @ng-select/ng-option-highlight
```

**Error**
```
>npm install --save @ng-select/ng-option-highlight
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: base@0.0.1
npm ERR! Found: @angular/common@12.1.2
npm ERR! node_modules/@angular/common
npm ERR!   peer @angular/common@"^12.1.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@">=10.0.0 <11.0.0" from @ng-select/ng-option-highlight@0.0.6
npm ERR! node_modules/@ng-select/ng-option-highlight
npm ERR!   @ng-select/ng-option-highlight@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Kappis\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Kappis\AppData\Local\npm-cache\_logs\2021-07-20T11_09_05_145Z-debug.log
```

or is there another way ?
--legacy-peer-deps but I don't want to use it

**Comment by Kirbylix** [comment]
I have the same problem, is there already a solution?

**Comment by kfrancois** [comment]
This was mentioned in https://github.com/ng-select/ng-select/issues/1937 too (which was marked as stale). Seems like an easy solution to just bump this version and publish it as it has been an issue since Angular 11.

**Comment by kkappis** [comment]
> This was mentioned in #1937 too (which was marked as stale). Seems like an easy solution to just bump this version and publish it as it has been an issue since Angular 11.

where was this mentioned ? the #1937 is this one

**Comment by rogerza** [comment]
maybe they are out sick or on vacation

**Comment by daniel-seitz** [comment]
There is a change and I believe a PR for this however nobody seems to be able to publish.

For this reason and because I have this since ng11, I created a workaround you can find in https://github.com/ng-select/ng-select/issues/1943

Maybe that's helpful. I just think: If this is such a small functionality, we shouldn't be waiting forever and just implement the highlight ourselves.
