### ISSUE TITLE
Prevent dropdown when the input only receives focus

### ISSUE THREAD

**Issue by billmcknight1953** [ng-select/ng-select#1958]
Is it possible to prevent ng-select from opening the dropdown of options when you merely give the input focus?  I am using a custom search function and have a preset list of options, but I don't want to show these options when the user clicks in the ng-select input.  I want the options to show only if a search term is entered (or at least after a few characters).

**Comment by plessbd** [comment]
I had to do the same thing in my project

This is how I was able to achieve the effect
```typescript

onOpen(elm: any){
        if(elm.searchInput.nativeElement.value == ""){
            elm.close();
        }
}
```
