### ISSUE TITLE
Priority values

### ISSUE THREAD

**Issue by c2ofh** [ng-select/ng-select#1967]
**Is your feature request related to a problem? Please describe.**
We have a dropdown with all countries. Sometimes you have to scroll very far, even though the country has already been selected many times. An automatic priority would be great. So that the most popular countries appear at the top.

**Describe the solution you'd like**
An option, to set a Array with some values with the Top10 values. Those items will be seperated at the top of the dropdown.

**Describe alternatives you've considered**
Currently, I need to reorder the data and programmatically move the top10 entries to the top. But then you don't see that these are separated from all the other countries and don't follow the alphabetical sorting. At first glance, you might think that the list is sorted wildly. 

**Additional context**
example
![image](https://user-images.githubusercontent.com/10913793/131687599-3de6fb1b-4087-482c-9bf2-c3ea873fa45f.png)

**Comment by custompro12** [comment]
I think you can already achieve what you're looking for by setting the `groupBy` property to something like "Top 10" on your top 10 items.
[StackBlitz Example](https://stackblitz.com/edit/angular-ivy-mtsrcs?file=src/app/app.component.ts)

This automatically adds a little bit of indentation to help them appear visually separated, but you can also add a vertical line between grouped items and regular items by adding a CSS snippet to your component:
```CSS
::ng-deep .ng-option-child + :not(.ng-option-child) {
  border-top: 1px solid #ddd;
}
```

_Note that you still have to sort the list to make sure items that have your `groupBy` key are at the beginning of your array._

Screenshot of StackBlitz:
![image](https://user-images.githubusercontent.com/12768953/134219543-8db53d5a-2a05-41b5-88aa-d72eb7568616.png)
