### ISSUE TITLE
The field is not cleared when the control is updated with editableSearchTerm

### ISSUE THREAD

**Issue by JakaRua** [ng-select/ng-select#1971]
**Describe the bug**
When using the editableSearchTerm parameter when updating the control, or rather using the reset function, the value remains in the selection.

**To Reproduce** 

```
<ng-select
  class="w-100"
  bindLabel="name"
  bindValue="id"
  appearance="outline"
  placeholder="Select category"
  virtualScroll="true"
  [clearable]="true"
  [searchable]="true"
  [editableSearchTerm]="true"
  [items]="items$ | async"
  [formControl]="control"
  (click)="onClick()"
  (search)="getTaxonomies($event)"
  [loading]="itemsLoading$ | async"
>
  <ng-template ng-label-tmp let-item="item">
    {{item.name}}
  </ng-template>
  <ng-template ng-option-tmp let-item$="item$.value" let-searchTerm="searchTerm">
    <span *ngFor="let pathName of item$.path; let i = index">
      <span
        [class.bold]="i === item$.path.length - 1"
        [innerHTML]="pathName | highlightPipe: searchTerm"
      >
      </span>
      <span *ngIf="i < item$.path.length - 1"> > </span>
    </span>
  </ng-template>
</ng-select>
<mat-error>
  <field-error [formControl]="control"></field-error>
</mat-error>
```

```
 @Input()
  public set taxonomyId(taxonomyId: number | null) {
    if (!taxonomyId && this.ngSelect) {
      this.control.reset();
      return;
    }
    this.control.patchValue(taxonomyId, { emitEvent: false });
  }
```

If the value is empty, the form is reset, but the value remains as in the screenshot. If you remove editableSearchTerm, then everything works out adequately.

**Screenshots**
![image](https://user-images.githubusercontent.com/10262515/132841578-17c90c9e-8ee3-4f3c-9e71-96cbbf2b5cba.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version: 93.0.4577.63

**Comment by earshinov** [comment]
We are also interested in this issue. We would expect

```
formControl.setValue(null)
```

to clear the control, but with `[editableSearchTerm]="true"` nothing changes visually for the user, because ng-select still displays `searchText` derived from the last selected item
