### ISSUE TITLE
Can't npm install ng-option-highlight

### ISSUE THREAD

**Issue by benjamin-thomas** [ng-select/ng-select#1977]
Hello, I can't install this package into my Angular 11 project

Command:

    npm install --save @ng-select/ng-option-highlight

Output:

```
...
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@">=10.0.0 <11.0.0" from @ng-select/ng-option-highlight@0.0.6
npm ERR! node_modules/@ng-select/ng-option-highlight
npm ERR!   @ng-select/ng-option-highlight@"*" from the root project
...
```

It seems @david-shortman forgot to upgrade the package version here: https://github.com/ng-select/ng-select/blame/9fb09df501e4386eee5e1c10b26a2c0fcfb8bac3/src/ng-option-highlight/package.json

And it looks like somebody forgot to push to the npm repos.

**Comment by BkSouX** [comment]
yes, could be great to publish it @david-shortman

**Comment by david-shortman** [comment]
I'm not a maintainer of this repo 😅. 
Paging @jwmcgettigan

**Comment by benjamin-thomas** [comment]
Gotta love those bots :roll_eyes:
