### ISSUE TITLE
dropdown-panel does not render items if you set max-height

### ISSUE THREAD

**Issue by Deprotype** [ng-select/ng-select#1984]
I used the solution explained in this ticket: https://github.com/ng-select/ng-select/issues/1113  to set number of rendered options in the dropdown list. The problem is that if you first get exactly one item in the search result and then search for something else with multiple results, the dropdown list has the wrong height and the items are not rendered correctly.

To reproduce this bug you have to copy paste something to the ng-select that produces exactly one result. Then you can delete the pasted string and write a search-string that creates multiple (more than max view) results.

In the screenshot the scrollbar is correct, as there are multiple items. But the items are not rendered on the whole dropdown-panel. If you scroll down, new items are rendered in the smaller window, but it should be rendered in the whole dropdown-panel.

![image](https://user-images.githubusercontent.com/92386093/136983433-f1561f8f-7457-4917-8f96-9fe76f2e0cf7.png)

**Comment by daviian** [comment]
@jwmcgettigan Can you have a look at this? I've the same issue as well...

**Comment by t0m-4** [comment]
i've the same issue with the version 13.9.1. Any news about this issue?
