### ISSUE TITLE
QUESTION/ BUG:  labelForID and ID does not work together

### ISSUE THREAD

**Issue by rseiffert** [ng-select/ng-select#1993]
**Describe the bug**
It seems like if labelForId is used in a ng-Select which also has an ID it does not work.

If I do not put an ID in the definition of the ng-select it works, but my IDE (intelliJ) throws an "invalid id reference" (look at attached image)

**To Reproduce** 
```
div class="row margin-top-25">
    <div class="col-4">
        <label for="one">One (WORKS 😊 but makes the IDE red)</label>
    </div>
    <div class="col-8">
        <ng-select
                labelForId="one">
            <ng-option>Dog</ng-option>
            <ng-option>Cat</ng-option>
        </ng-select>
    </div>
</div>

<div class="row margin-top-25">
    <div class="col-4">
        <label for="two">Two (DOES NOT WORK ☹️)</label>
    </div>
    <div class="col-8">
        <ng-select
                id="two"
                labelForId="two">
            <ng-option>Dog</ng-option>
            <ng-option>Cat</ng-option>
        </ng-select>
    </div>
</div>
```

**Screenshots**
![04-11-_2021_16-32-46](https://user-images.githubusercontent.com/1698356/140363098-aba10111-e783-4f25-a7e7-c9969723cd33.png)

**Any workaround?**

**Comment by varnastadeus** [comment]
`<label for="">` works only with "labelable" elements like input so `id` should be set on the `input` element. To propagate id on the input, `labelForId` is used. As this is custom element, your IDE will show an error and it is okay.

**Comment by rseiffert** [comment]
You are right. It is rather a cosmetic flaw in IDE than a Bug.

Thank you for your clarification!
