### ISSUE TITLE
Virtual scroll - wrongly rendered after items count increased

### ISSUE THREAD

**Issue by adros** [ng-select/ng-select#1994]
If the items count is changed from lower number (e.g. 1) to larger, wrong number of items is rendered.

I believe that problem is in method `_measureDimension`
 
https://github.com/ng-select/ng-select/blob/37b589a29ff8e668dd3f36b4ad27bf432d739926/src/ng-select/lib/ng-dropdown-panel.component.ts#L340
which quick returns with previous `dimensions` object if `itemHeight > 0` and property `itemsPerViewport` stays unchanged (and should be updated)  

![image](https://user-images.githubusercontent.com/914548/140485580-9b6b9a82-85cd-408d-bce0-b38c86fcc5e9.png)

**Comment by adros** [comment]
For anyone dealing with same issue - workaround is setting the `bufferAmount` to same number as expected number of visible items in list.

**Comment by adros** [comment]
some activity (not to be closed by bot)

**Comment by Glursh** [comment]
I had the same problem today, with version 13.9.1.
The @adros workaround helped me a lot : https://github.com/ng-select/ng-select/issues/1994#issuecomment-961733540
