### ISSUE TITLE
dropdownPosition and appendTo don't work correctly together

### ISSUE THREAD

**Issue by denisr-w** [ng-select/ng-select#2008]
Hi, im using angular version `12` and `ng-select` version `7.4.0`. If setting `dropdownPosition` to `right` or `left` and  `appendTo` to `body`, dropdown isn't positioned correctly. If setting `dropdownPosition` to `top` or `bottom `  and  `appendTo` to `body`, everything works as expected. It looks like that callculated styles for `right` or `left` were not implemented correctly for this case.

Any known solution how to fix this?

**Comment by Dark0rion** [comment]
The only solution I found was to remove the "appendTo". As you mention, they don't work well together.

> Hi, im using angular version `12` and `ng-select` version `7.4.0`. If setting `dropdownPosition` to `right` or `left` and `appendTo` to `body`, dropdown isn't positioned correctly. If setting `dropdownPosition` to `top` or `bottom ` and `appendTo` to `body`, everything works as expected. It looks like that callculated styles for `right` or `left` were not implemented correctly for this case.
> 
> Any known solution how to fix this?

The only solution I found was to remove the "appendTo". As you mention, they don't work well together.

**Comment by Dark0rion** [comment]
The only solution I found was to remove the "appendTo". As you mention, they don't work well together.
