### ISSUE TITLE
Disable dropdown opening

### ISSUE THREAD

**Issue by maranmaran** [ng-select/ng-select#2015]
**Is your feature request related to a problem? Please describe.**
I would like to disable opening of dropdown on ng-select component

**Describe the solution you'd like**
`<ng-select [disableDropdown]="true"></ng-select>`

**Describe alternatives you've considered**
Fetching childView of ng-select and assignment of noop to open function . 
  - Works like I would like to but for whatever reason it disables ability to press space on the text input?
 - `this.ngSelect.open = noop`

Do you guys have any workarounds for me ? Thanks, I appreciate everyones time.

**Comment by varnastadeus** [comment]
have you tried`[isOpen]` ?
