### ISSUE TITLE
selectableGroupAsModel="true" group name issue

### ISSUE THREAD

**Issue by Romko775** [ng-select/ng-select#2018]
**Describe the bug**
With selectableGroupAsModel="true" selected options working wrong

**To Reproduce** 
<ng-select 
   ...
   [selectableGroup]="true"
   [selectableGroupAsModel]="true".  <--- must be true
>

![image](https://user-images.githubusercontent.com/94640418/144999627-a769fce2-ca41-451e-b904-1928d4989063.png)

on start it works as expected
and if we deselect a child also work expected like shown here

![image](https://user-images.githubusercontent.com/94640418/144999768-33b8efbd-26b4-4697-97ae-a0a4519c1860.png)

but when selecting back this child, the input not changing back to group name, instead added this child to array

![image](https://user-images.githubusercontent.com/94640418/144999922-6e800922-1ab5-4771-a2d7-97fcd887f99f.png)

**Expected behavior**
Return back the group name if all children are selected

**Comment by varnastadeus** [comment]
I believe this is the way it's supposed to be. If you start by selecting child elements until all are selected, you will not get `group` selected either.
