### ISSUE TITLE
Accessibility requirement - Clear all [x] button need "role" setting

### ISSUE THREAD

**Issue by DandelionWenjing** [ng-select/ng-select#2020]
**Describe the bug**
Clear all x button have no "Role" setting for accessibility.

**Reproducbile example**
[Example](https://stackblitz.com) which reproduces described behaviour

**To Reproduce** 
Steps to reproduce the behavior (if example is not provided):
1. Select one option in ng-select drop down.
2. right side have Clear all X button.
3. Open Dev Tools, select element in page to inspect it, hover X button.
4. There is no role setting for this button.

**Expected behavior**
There will be "Role" setting for the Clear All X button, or there is a way to set it.

**Screenshots**
![image](https://user-images.githubusercontent.com/33156672/145759026-71d2b411-f715-4c87-8a1a-654be7b681ef.png)

**Desktop (please complete the following information):**
Windows 10, Chrome, 3.7.0

**Additional context**

**Comment by JAVA-MSDT** [comment]
I am working on Accessibility for remove items, and also for the clear all text button
