### ISSUE TITLE
Extra white space with VirtualScroll true

### ISSUE THREAD

**Issue by Chandu-kundarapu** [ng-select/ng-select#2023]
Reopening the Extra white space with VirtualScroll true #1941 issue,

Can anyone help with this issue...??

**Comment by bhaskerchari** [comment]
Even we are facing this issue currently in many places through out our application as we deal with large datasets and we infact enable virtualScroll for all usages of ng-select.

I think this is an important issue as it makes the UI look ugly on dropdown open with white space and should definitely be fixed.
