### ISSUE TITLE
Elemento sumindo ao atualizar pagina

### ISSUE THREAD

**Issue by InterConectDigital** [ng-select/ng-select#2024]
Estou ultilizando a ultimiza versão e quando atualizo a pagina com a tecla f5 ou atravez de link de direcionamento o plugin simplemente quebra conforme a imagem.

Estou mandando uma imagem com sem atualizar pagina inicial, mais quando direciono para outras pagina que tem outra masterpage atraves de um link acontece isso.

Estou usando a implementação conforme este link 
https://github.com/ng-select/ng-select

![ev3](https://user-images.githubusercontent.com/53632931/147351139-b354ed4a-c6f8-4b75-b1f6-46e826df0e91.png)
![ev](https://user-images.githubusercontent.com/53632931/147350645-84742111-d8f6-4f8c-a943-30dcf4b26cad.png)
![ev2](https://user-images.githubusercontent.com/53632931/147350648-a69c75ba-7994-4518-9f0e-814930810981.png)

**Comment by luiza-avelino** [comment]
@InterConectDigital eu tive problema parecido. Pra mim resolveu qd eu movi o import do @import '~@ng-select/ng-select/themes/default.theme.css'; para meu arquivo principal do sass. Antes eu estava carregando o arquivo somente no sass do meu componente, depois que movi para meu global.scss resolveu.
