### ISSUE TITLE
ngModel not selecting multiple items having same description but with different id 

### ISSUE THREAD

**Issue by bhaskerchari** [ng-select/ng-select#2026]
**Describe the bug**
ngSelect is not showing all the items as selected when there are multiple items with same description even though they are part of ngModel data that is specified.

In the sample I have not specified bindValue="id" intentionally because I want the ngModel to bind to the whole object not just a single property. But some reason ngSelect is internally trying to mark selections based on bindLabel="name" which is specified and if there are duplicates it is not selecting all but one with same name.

I can work around this problem by adding bindValue="id" but then my ngModel will bind to only "id" property in the object but not the whole object. I want "selectedPeople" which is binded to ngModel contain array of objects and not array of numbers (id's).

So is there a way where I can fix the problem of multi selecting all the duplicate name items and selectedPeople(ngModel) contains array of objects??

**Reproducible example**
https://stackblitz.com/edit/angular-lxlzxq-oxrgpq

**Comment by TrinTragula** [comment]
I'm having the same exact problem, did you find any workaround for this bug?

**Comment by SIRAAJ-UI** [comment]
I'm having the same exact problem, did you find any workaround for this bug?

**Comment by darkmark1991** [comment]
@bhaskerchari @TrinTragula @SIRAAJ-UI 

came across same issue, solved it by removing the bindLabel param from ng-select and adding ng-label-tmp 

`<ng-select
              [items]="items"
              ....>
              <ng-template ng-option-tmp let-item="item">
                  <div>{{item.name}}</div>
              </ng-template>
              <ng-template ng-label-tmp let-item="item" let-clear="clear">
                <span (click)="clear(item)">&times;</span>
                {{ item.name }}
              </ng-template>
</ng-select>`

**Comment by terencehonles** [comment]
I believe this is fixed by #1957 which was originally #1652 but has still been waiting review and I'm not sure this project is maintained anymore.

**Comment by terencehonles** [comment]
The alternative is to define a `compareWith` and that's what we've done, but my PR would allow the default `compareWith` to work for most people (but you may still need to define your own if `===` isn't actually appropriate for your bindings)

**Comment by Tiny-core-linux-all-powe** [comment]
https://scriptwriteraromatic.github.io/p0uJEVe9z/ Here’s the answer—take a look

**Comment by daboudii** [comment]
> https://scriptwriteraromatic.github.io/p0uJEVe9z/ Here’s the answer—take a look

DO NOT OPEN THIS LINK, 

@terencehonles plz delete comment
