### ISSUE TITLE
Hide header template when options are empty

### ISSUE THREAD

**Issue by lohiaad** [ng-select/ng-select#203]
[x] bug

### Expected behaviour
when options are empty then header template should be hidden and notFoundText should be shown

### Actual behaviour
header template and not text found are shown 
https://plnkr.co/edit/DNtepk8l8m4u4gwVMdOS?p=preview

### More Info
ng-select version: [0.15.2]

**Comment by varnastadeus** [comment]
@lohiaad not sure if it must be hidden by default. If you do that, then we will lose flexibility since some users may want to show header even if there are no items. Now we have full control and hide header if it is desired, e.g.

```html
<ng-template *ngIf="cities.length" ng-header-tmp>
    <div>header</div>
</ng-template>
```

**Comment by anjmao** [comment]
@lohiaad Thanks for reporting. I'm closing this as @varnastadeus make sense.

**Comment by sangecz** [comment]
@anjmao, @varnastadeus it does not work for me as items (cities in this case) are not filtered at all, same length all the time. is that right behaviour, what could be the case?
