### ISSUE TITLE
Error when using a trusted-types CSP rule

### ISSUE THREAD

**Issue by Sirz3chs** [ng-select/ng-select#2037]
**Describe the bug**
I'm trying to use a CSP rule with trusted-types and i have an error that i'm not able to fix with ng-select. I have just a simple select with typeahead and when i click on it to select a value, nothing displays and i have multiple error in console about an `innerHTML` property. 

**Reproducbile example**
[Example](https://stackblitz.com/edit/angular-ivy-enbsqj?devtoolsheight=33&file=src/app/app.component.html) which reproduces described behaviour

**To Reproduce** 
1. Click on `select` input
2. See error in console

**Expected behavior**
No error in console and the `select` input content should displays.

**Screenshots**
![image](https://user-images.githubusercontent.com/23245718/151976459-aedbe9d4-fd80-4eb3-8c49-50ba678918fa.png)
![image](https://user-images.githubusercontent.com/23245718/151976608-6297c24e-31ae-4cc4-94a8-732988221067.png)

**Desktop (please complete the following information):**
 - OS: linux
 - Browser: chrome
 - Version: 97.0.4692.99 (Official Build) (64-bit)

**Comment by bolemeus** [comment]
We're running into thesame problem
