### ISSUE TITLE
ngModel is not working.

### ISSUE THREAD

**Issue by Kalpesh300** [ng-select/ng-select#204]
### Expected behaviour
I am setting first option as default selected using ngModel.
I want to remove this first option when I first open dropdown.

Here is my code:
` <ng-select class="normal-text h4"
        [(ngModel)]="selectedProjects"
        bindLabel="name"
                [items]="projects"
                [multiple]="true" 
                (open)="projectsOpened($event)"
                (focus)="projectsFocused($event)">
        </ng-select>`
Item array:
`  projects = [
    { name: 'All' },
    {name : 'sapper'} ,
    {name: 'cubi'}
  ];`
My Constructor:
`constructor() {
    this.selectedProjects.push(this.projects[0]);
  }`
Events: 
` projectsOpened($event) {
    this.selectedProjects.pop() ;
  }`
`
  projectsFocused($event) {
    this.selectedProjects.pop();
  }`

**Comment by varnastadeus** [comment]
Hi @Kalpesh300. It works, you just need to set new reference for NgModel. 

```javascript
this.selectedCities.pop();
this.selectedCities = [...this.selectedCities];
```
