### ISSUE TITLE
Dropdown drops "up" when there is no room for dropdown in either direction.

### ISSUE THREAD

**Issue by PolarbearDK** [ng-select/ng-select#2044]
**Describe the bug**
Dropdown drops "up" when there is no room for dropdown, nether up or down. 
This makes part of the dropdown impossible to see by any means..  
It should drop down when there is no room, because then you can scroll to see the rest of the dropdown.

**Reproducible example**
[Using NG-Select example](https://ng-select.github.io/ng-select#/virtual-scroll)

**To Reproduce** 

Open https://ng-select.github.io/ng-select#/virtual-scroll
Open ng-select dropdown.
Decrease height of browser window until lower part of dropdown disappears.
Close dropdown
Open dropdown again.
Now the dropdown drops "up" but the top portion is not visible (The part with "Loading 50 of 5000").

**Expected behavior**
When there is no room for dropdown in any direction, it should prefer "down".

**Screenshots**
![image](https://user-images.githubusercontent.com/5196920/153755166-93551021-9730-4125-b764-e62d23b6713d.png)

**Desktop (please complete the following information):**
 - OS: Any (seen on Windows)
 - Browser Any (seen in chrome, edge]
 - Version Any
 
 Fix is available in pull request #1945

**Comment by taivnn9** [comment]
I have same issue, seems have no one approve your PR.
