### ISSUE TITLE
npm installation of @ng-select ng-option-highlight with Angular 12

### ISSUE THREAD

**Issue by deptford** [ng-select/ng-select#2051]
**Describe the bug**
When installing via npm with Angular 12 and wanting the option-hightlight we have a package.json file like this:
```
"@ng-select/ng-option-highlight": "^0.0.6",
"@ng-select/ng-select": "^7.4.0",
```
However, neither 0.0.6 nor 0.0.7 of ng-option-highlight will install without `--force` as:

`@ng-select/ng-option-highlight 0.0.6 has peerDependency @angular/core": "^>=10.0.0 <11.0.0`
and
`@ng-select/ng-option-highlight 0.0.7 has peerDependency @angular/core": "^>=12.0.0 <13.0.0`

This git repo does have a version of src/ng-option-highlight/package.json with the correct peer dependencies, as expected for tag 7.4.0: [https://github.com/ng-select/ng-select/blob/v7.4.0/src/ng-option-highlight/package.json](https://github.com/ng-select/ng-select/blob/v7.4.0/src/ng-option-highlight/package.json)

However, this version is not available in any of the [npm versions](https://www.npmjs.com/package/@ng-select/ng-option-highlight), as there is just a single release of 0.0.6 even though that version straddles multiple angular peer dependency versions.

Is it possible for you to update npm to release a version of ng-option-highlight compatible with ng-select/7.4.0 - angular 12?

Alternatively, if there are any clean workarounds, these would also be appreciated.

Thanks

**Comment by ebakep** [comment]
faced the same issue, it seems that `ng-option-highlight` versioning is quite different from `ng-select` and right now its impossible to use `ng-option-highlight` with angular 11/12, the only way is to ignore peer's rules by package manager itself

Any comment's here ?

**Comment by Smootium** [comment]
I'm also running into this issue with our library and unfortunately, we have to tell anyone who is using npm version 7+ who tries to install our package, that they have to use either --force or --legacy-peer-deps switch when installing  :(
