### ISSUE TITLE
Allow deselect of option when [multiple]="false"

### ISSUE THREAD

**Issue by Tlepel** [ng-select/ng-select#2053]
**Is your feature request related to a problem? Please describe.**
It seems to me that the ng-select for `[multiple]="true"` should behave the same as the ng-select for `[multiple]="false"`.
However, it doesn't seem possible to deselect an option from the dropdown when only one option can be selected.

**Describe the solution you'd like**
What I would like to have is an option, such as `@Input() clickOptionToDeselect: boolean` for the ng-select, that can toggle this behaviour. This could apply to ng-selects that allow multiple options as well as ng-selects with only a single selected option allowed.

When `false`, clicking on an `<ng-option>` would not deselect it. It only selects the option if it isn't currently selected.
When `true`, clicking on an `<ng-option>` would toggle the selection, regardless of the `multiple` property.

When the `multiple` property is `true`, the value of the proposed `clickOptionToDeselect` would be `true`; when `multiple` is set to `false`, the default value could be `false`, which would then mimic the current behaviour and ensure that current usage doesn't have to change if it is not needed.

**Describe alternatives you've considered**
I've considered rewriting my implementation using the `ng-option-tmp` template, however this makes for a very dirty fix for this issue, while it would be much simpler to implement it in the library.

This implementation would consist of adding a click listener to a `div` inside the template, which would call the `handleClearClick()` method of the ng-select. However, this would not actually change the value of the ng-select for some reason. Only after adding a `close()` after the `handleClearClick()` would the value of the ng-select change.

Therefore this feature in the library would make more sense.

**Additional context**
Some additional notes: in my project, the clear-all button is removed because of the styling, and I'm trying to fix this without putting that button back in.

**Comment by Tlepel** [comment]
I haven't done anything to this PR as there haven't been any reviews, but I think it shouldn't be stale because of that?

**Comment by Tlepel** [comment]
I couldn't reopen the issue since it's been closed for a long time now, however I've run into the same problem again after making a workaround the first time. However, I still think it'd be neat if the library could fix this instead of requiring a workaround.

**Comment by anurag-roy** [comment]
This issue should not be closed, ran into the same problem
