### ISSUE TITLE
Positioning of dropdown with [appendTo] inside scrollable container

### ISSUE THREAD

**Issue by mfig** [ng-select/ng-select#2055]
**Describe the bug**
There are cases when I want to append dropdown to a scrollable container so that it stays fixed. In such cases dropdown is positioned at invalid height.
From issue #1350 (appendTo part) it looks like it used to work before.

**Reproducbile example**
[Example](https://stackblitz.com/edit/angular-13-template-ie4jey) which reproduces described behaviour

**To Reproduce** 
Steps to reproduce the behavior (if example is not provided):
1. Open dropdown inside scrollable container

**Expected behavior**
Dropdown should be positioned next to input 

**Screenshots**
![image](https://user-images.githubusercontent.com/8777355/157424590-81e0890e-ec77-4f5d-b19b-f4fa087ba5f1.png)

**Comment by oobleck** [comment]
This is still an issue in v10.0. I'd like to propose it get reopened.

**Comment by Eugeno** [comment]
This is still relevant in v13.2.0

**Comment by Eugeno** [comment]
I encountered the same issue in version 13.2.0. As a quick workaround, I used the following code:
```html
<ng-select
  ...
  appendTo="some-container"
  (open)="onOpen()"
/>
```
```typescript
protected onOpen(): void {
  const container: HTMLElement = this.document.querySelector('some-container')!;
  queueMicrotask(() => { // `ng-dropdown-panel` is not yet present in DOM when `open()` event is triggered
    const dropdown: HTMLElement = container.querySelector('ng-dropdown-panel')!;
    const delta = container.scrollTop;
    dropdown.style.transform = `translateY(${delta}px)`;
  });
}
```
