### ISSUE TITLE
how to use autocomplete in ngFor

### ISSUE THREAD

**Issue by awais786327** [ng-select/ng-select#2058]
@varnastadeus help needed: we are looking a way to know how to differentiate each autocomplete in ngFor loop as we have seen the desired example from well described templates but the issue is when we try to type something in any of autocomplete input it trigger search event for all list rendering in ngFor as it is known because of using same **[typeahead]="compositionInput$"** and **[items]="compositions | async"** 

![image](https://user-images.githubusercontent.com/12613564/158027626-5a19d057-e7d8-4300-8418-d8f1dfe3f689.png)

![image](https://user-images.githubusercontent.com/12613564/158027664-bf786609-db3e-4204-8d27-79478ea4b099.png)

**Comment by AlmaniaM** [comment]
You should probably provide a different subject for each ng-select and concat those. However, you can do something with a Pipe. An example is:

```
@Pipe({
  name: 'columnTypeahead'
})
export class ColumnTypeaheadPipe implements PipeTransform {

  transform(subject: Subject<{search: string, columnName: string}>, columnName: string): Subject<string> {
    const newSubject = new Subject<string>();
    const oldNext = newSubject.next;
    // This will replace the old next() function and call the compositionInput$ subject with the search value and column name
    // You can do a subcription here as well but you'll have to figure out how to unsubscribe whenever a new subject is generated for that ng-select
    newSubject.next = (search: string) => {
      subject.next({ search, columnName });
      oldNext(search);
    }

    return newSubject;
  }

}
```

Then use it like so `[typeahead]="compositionInput$ | columnTypeahead: col.attributeId"`. You can use whatever infomation you want to differentiate each subject. It doesn't have to be col.attributeId.
