### ISSUE TITLE
Promise resolve not working for addTag when resolved inside an observable

### ISSUE THREAD

**Issue by adeete-zeotap** [ng-select/ng-select#2061]
I'm trying to implement a scenario where, when user clicks on addTag, he get's a warning message to proceed. If he clicks on proceed only then the typed value should be added.

```
addCustomField = 
    (fieldToBeValidated: string) => {
      this.searchField.emit(fieldToBeValidated);
      return new Promise((resolve, reject) => {
        this.service.addCustomField().subscribe((addTag) => {
          console.log(addTag, 'Add tag');
          resolve(fieldToBeValidated);
        });
      });
   }
```

```
<ng-select [items]="items"
           [addTag]="addCustomField"
           [bindLabel]="'name'"
           [(ngModel)]="selectedItem">
</ng-select>
```

The console statement is getting printed but the effect of resolve cannot be seen.

**Comment by lakshanmamalgaha** [comment]
Faced the same and got resolved by binding the promise to the component
<ng-select [items]="items"
           [addTag]="addCustomField.bind(this)"
           [bindLabel]="'name'"
           [(ngModel)]="selectedItem">
</ng-select>

**Comment by adeete-zeotap** [comment]
Didn't work. I'm able to access all the variables in the component. But the resolve inside subscribe isn't working. If i move it outside the subscription then it works.

**Comment by adeete-zeotap** [comment]
It works with setTimeout, but not with observable subscription

**Comment by fzs1994** [comment]
I'm still facing the issue.

**Comment by fzs1994** [comment]
> Faced the same and got resolved by binding the promise to the component <ng-select [items]="items" [addTag]="addCustomField.bind(this)" [bindLabel]="'name'" [(ngModel)]="selectedItem">

Thanks. This works for me
