### ISSUE TITLE
Stackblitz examples crash

### ISSUE THREAD

**Issue by moniuch** [ng-select/ng-select#2073]
**Describe the bug**

**Reproducbile example**
[Example](https://stackblitz.com) which reproduces described behaviour
I think all the Stackblitz examples from the demo page (at least all that I have picked randomly) are crashing.

**To Reproduce** 
Steps to reproduce the behavior (if example is not provided):
1. Go to https://ng-select.github.io/ng-select
2. Select any random chapter
3. Click on any Stackblitz icon

**Expected behavior**
Should work.

**Screenshots**
![image 2022-04-12 21-51-02](https://user-images.githubusercontent.com/681956/163042341-65064ef6-385c-4ae9-981c-19bd0882b096.png)

**Desktop (please complete the following information):**
 - irrelevant - tested on a couple of browsers/OS

**Smartphone (please complete the following information):**
Desktop

**Additional context**

Limits the ways to try out the library options before using.

**Comment by Deliana90** [comment]
still error

**Comment by csimpi** [comment]
Is this library abandoned?

**Comment by cloakedninjas** [comment]
Was about to post the same issue

> Is this library abandoned?

Looks like it's starting to die

**Comment by moniuch** [comment]
> Is this library abandoned? All the examples bugged/crashed, this ticket has been closed :/

I don't think this library is abandoned, judging by the ng14 compatibility update.
And I also understand the difficulty in solving stackblitz problems or even reaching them for help.

The way of handling users' concerns though is much below par, very discouraging from using this lib.
