### ISSUE TITLE
selected value not in line with cursor

### ISSUE THREAD

**Issue by lgawron** [ng-select/ng-select#2083]
With the simplest ng-select configuration + material theme the value selected is not in the same position as the search cursor

[example](https://stackblitz.com/edit/angular-yfe4s4?file=src/app/app.component.html)

![image](https://user-images.githubusercontent.com/673159/169696353-5e8e1dbe-2736-414e-96ff-5e641733b91f.png)

**Comment by AlonsoK28** [comment]
same for me

![image](https://user-images.githubusercontent.com/37458700/175797031-1196dd6a-ceb8-4738-8c14-a4ecb5cade26.png)
