### ISSUE TITLE
Value should allow "any" value not "string"

### ISSUE THREAD

**Issue by jessycormier** [ng-select/ng-select#209]
Please fill below information if issuing a bug report. 
### Expected behaviour
When binding we shouldn't force the type for value to be "string" This limits the ability as well as makes the code in TS vert strange having to ToString ID's if binding to values from a DB return.

Thoughts?

**Comment by varnastadeus** [comment]
Hi @jessycormier. Currently there is no such forcing or I am missing something. Can you elaborate more what are you binding?

**Comment by anjmao** [comment]
@jessycormier Closing this one. Please reopen if you still have any issue, thanks.
