### ISSUE TITLE
Demo page is not working

### ISSUE THREAD

**Issue by jeannuel** [ng-select/ng-select#2095]
**Describe the bug**
The demo page ( https://ng-select.github.io/ng-select/ ) is not working.

**Reproducible example**
Just go to the demo page: https://ng-select.github.io/ng-select/

**Screenshots**
<img width="1680" alt="Screen Shot 2022-06-09 at 3 37 25 PM" src="https://user-images.githubusercontent.com/93395506/172939850-c6d4a8e3-dcbb-4123-9363-cd4e94ea6d8e.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 102

**Comment by varnastadeus** [comment]
@pavankjadda can you check this please?
