### ISSUE TITLE
Mark item when entering filter

### ISSUE THREAD

**Issue by varnastadeus** [ng-select/ng-select#21]
Currently when filtering items, you can't select item which best fits your search 

![image](https://user-images.githubusercontent.com/17824796/29944184-25024cd8-8ea5-11e7-87a2-06d02dd132cb.png)

**Comment by anjmao** [comment]
To solve this we need to select first filtered item on enter click.

**Comment by andrea-spotsoftware** [comment]
It would be also useful to let user select the best matching item with tab key

**Comment by varnastadeus** [comment]
@andrea-spotsoftware #31 solves this issue and implements suggested selection on tab key
