### ISSUE TITLE
Detect item value change on page load

### ISSUE THREAD

**Issue by arun-maddheshia** [ng-select/ng-select#210]
Please fill below information if issuing a bug report. 
### Expected behaviour
How to detect if items array changed on time of page load

### Actual behaviour
Currently no callback on item change on load time

### More Info
ng-select version: Latest
angular version: 5
browser: Chrome

**Comment by varnastadeus** [comment]
@arun-maddheshia why do you need callback if items change only when you set them and you have full control of it?

**Comment by arun-maddheshia** [comment]
The problem is my select is relative with another select so when data come from API the dropdown value of select A change onInit but the relative select B data is not updated because its not detect the change value on load

**Comment by varnastadeus** [comment]
@arun-maddheshia can't you just update both selects on init?

**Comment by arun-maddheshia** [comment]
no because B is dependent on A value

**Comment by varnastadeus** [comment]
Please add some code

**Comment by arun-maddheshia** [comment]
close it I just manage to call the change function onInit
