### ISSUE TITLE
Custom style for ng-select-container NOT work

### ISSUE THREAD

**Issue by Spaceman2019** [ng-select/ng-select#2105]
Hi, I use the version 8.1.1 in this moment and want to change the default style.

ViewEncapsulation ist set to None.

My html-code:
<ng-select class="custom"
           [items]="cars"
           [clearable]="false"
           placeholder="placeholder"
           bindLabel="name"
           bindValue="id"
           [(ngModel)]="selectedCar"
           id="field-1"
           >
</ng-select>

My scss-code:
.ng-select.custom {
    border:0px;
    min-height: 0px;
    border-radius: 0;
    border: 1px solid blue;
    margin-top: 0.50rem;
}

.ng-select.custom .ng-select-container  {            
    min-height: 0px;
    border-radius: 0;
    border: none;
}

I expected that there is no border for the ng-select-container, but I can see it on the screen.

![grafik](https://user-images.githubusercontent.com/53607207/176122119-23c5a3af-5f0e-4d54-ae69-30492cdecc0b.png)

This need to be fix.

Thanks

**Comment by Exclamation-mark** [comment]
I  confused by the same problem.
