### ISSUE TITLE
Items with value 0

### ISSUE THREAD

**Issue by LukaszKubiak** [ng-select/ng-select#211]
### Expected behaviour
When i select item on component side and it's value is equal to item in array passed to ng-select it should select that item.

### Actual behaviour
When value of selected item is equal to 0 ng-select doesn't choose that item.
[Plunker](https://plnkr.co/edit/0Zm0RIPIbZ24XaXaYcEH?p=preview)

### More Info
ng-select version: [0.15.2]

**Comment by varnastadeus** [comment]
I see the issue, probably will fix it today. Thanks for reporting
