### ISSUE TITLE
ng-option-highlight for Angular 14

### ISSUE THREAD

**Issue by jecraig** [ng-select/ng-select#2111]
**Describe the bug**
ng-option-highlight 0.0.7 does not install with Angular 14. Can you publish a new version that doesn't restrict Angular 14.

**Error**
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@">=13.0.0 <14.0.0" from @ng-select/ng-option-highlight@0.0.7
npm ERR! node_modules/@ng-select/ng-option-highlight
npm ERR!   @ng-select/ng-option-highlight@"0.0.7" from the root project

**Comment by sandrooco** [comment]
I just saw that the dependency bump is actually there - it just needs to be released. This would be great to have so we don't need to use `npm i --legacy-peer-deps`

**Comment by Arrakis-Lux** [comment]
Small bump on that ?

**Comment by ganholete** [comment]
Same problem here.

**Comment by blendmaker** [comment]
would love to bump this issue as well

**Comment by hartwig-wutscher-ibm** [comment]
Same problem here.

**Comment by dianalo** [comment]
Just ran into the same problem. A new release would be great!

**Comment by mcieplucha** [comment]
+1 for this one

**Comment by DanielJRaine** [comment]
> I just saw that the dependency bump is actually there - it just needs to be released. This would be great to have so we don't need to use `npm i --legacy-peer-deps`

Seriously. I'm not able to run --legacy-peer-deps in my CI system, so this tiny issue is preventing our entire department from upgrading to Angular 14.

**Comment by nareynolds** [comment]
+1

**Comment by hisham** [comment]
+1

**Comment by hisham** [comment]
This can be resolved temporarily for now via https://www.npmjs.com/package/patch-package (with --exclude 'nothing' option - see https://github.com/ds300/patch-package/issues/311)

**Comment by JCErasmus** [comment]
Bump. For issue persisting in Angular 15

**ERR! Found: @angular/common@15.1.2**
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^15.1.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! **peer @angular/common@">=13.0.0 <14.0.0"** from **@ng-select/ng-option-highlight@0.0.7**
npm ERR! node_modules/@ng-select/ng-option-highlight
npm ERR!   @ng-select/ng-option-highlight@"*" from the root project

**Comment by Jin4444** [comment]
+1

**Comment by juliasleeps** [comment]
+1

**Comment by cah-renan-ferreira** [comment]
+1

**Comment by vinlos** [comment]
please, update `ng-option-highlight` to be compatible with Angular 15

**Comment by juliasleeps** [comment]
+1

**Comment by mstefan78** [comment]
+1

**Comment by mstefan78** [comment]
Please, update ng-option-highlight to be compatible with Angular 14 - 15. This seems to be outdated for at least one year.

**Comment by AccessViolator** [comment]
+1

**Comment by kheos31** [comment]
+1

**Comment by Gjuju** [comment]
+1 
npm published package seems not updated :

![image](https://user-images.githubusercontent.com/1523359/232710060-57d2af3b-33a8-4876-9b5f-c632e4229828.png)

**Comment by andriwandres** [comment]
Is anyone still maintaining this issue?

**Comment by Prabukmca** [comment]
Able to install using --legacy-peer-deps but unable to use in Angular 15, facing the below issue. Kindly suggest any solution for this issue.

![image](https://github.com/ng-select/ng-select/assets/20346782/009b590a-5be8-4e7a-b7ef-a54f1e508c72)

**Comment by paulo-zacarias** [comment]
@pavankjadda It seems that ng-option-highlight is not being release as it is ng-select, because even thought dependency bump is done, the latest publish version seems to be 0.0.7 which is 2 years old and compatible only up to Angular 13.
Any change this can be fixed, to enable us to upgrade to Angular 14?

**Comment by ayyoubelkanaany** [comment]
Hi, there is any change here?

**Comment by MatDepInfo** [comment]
+1

**Comment by pavankjadda** [comment]
New version [released](https://www.npmjs.com/package/@ng-select/ng-option-highlight/v/11.1.1) with v16 compatibility

**Comment by tomasz-smigielski** [comment]
> New version [released](https://www.npmjs.com/package/@ng-select/ng-option-highlight/v/11.1.1) with v16 compatibility

well, and what about Angular 15 :-(

**Comment by pavankjadda** [comment]
> > New version [released](https://www.npmjs.com/package/@ng-select/ng-option-highlight/v/11.1.1) with v16 compatibility
> 
> well, and what about Angular 15 :-(

Unfortunately no, I don't have direct access to NPM. This is the least we can do at the moment.

**Comment by jecraig** [comment]
@tomasz-smigielski Just override it in your package.json. There's no code conflict, it's just a declarative issue.

`	"overrides": {
		"@ng-select/ng-option-highlight": {
			"@angular/common": ">=13.0.0",
			"@angular/core": ">=13.0.0"
		}
	},`
