### ISSUE TITLE
Custom option added with addTag not getting appended to the dropdown list

### ISSUE THREAD

**Issue by adeete-zeotap** [ng-select/ng-select#2113]
**Describe the bug**
Option added with addTag not getting appended to the dropdown list.
I have a list of dropdowns in my component. If an option is selected in one dropdown, it should be removed from dropdown list of others. For achieving that, i have added a filter pipe to the items which will only show options which have selected set to false.

```
<ng-select
  [items]="fruits | filterAttribute: selectedFruit"
  bindLabel="value"
  bindValue="value"
  [addTag]="true"
  [(ngModel)]="selectedFruit"
  (change)="onAttributeChange($event)"
  [placeholder]="'Select fruit'"
></ng-select>
```
**Reproducbile example**
https://stackblitz.com/edit/ng-select-bug-addtags-label-8wgk1u  which reproduces described behaviour

**Expected behavior**
Custom option should get appended to the list

**Comment by cloakedninjas** [comment]
Ran into this myself, probably same as #2050 

`bindValue` and `addTag` cannot be used together. Custom options are added to the form value as `null`
