### ISSUE TITLE
Extra white space with VirtualScroll true

### ISSUE THREAD

**Issue by aj-hops** [ng-select/ng-select#2116]
Describe the bug

Reproducible example
https://stackblitz.com/edit/angular-uuvic8?file=styles.css

To Reproduce
Steps to reproduce the behavior (if example is not provided):
Override CSS for word-wrap:
.ng-dropdown-panel .ng-dropdown-panel-items .ng-optgroup, .ng-dropdown-panel .ng-dropdown-panel-items .ng-option { white-space: normal !important; word-wrap: break-word !important; }

Expected behavior
There should not be extra space****

![127499555-d606094f-5a5c-48f4-a8af-4157e0c7b7e3](https://user-images.githubusercontent.com/109080101/179526159-fcbd6798-e936-4dde-8003-46c3d5a37385.png)

**Desktop (please complete the following information):**
OS: Windows
Browser: Chrome
Angular: V11.0.4
Boostrap: V4.0.0

**Comment by AjeetUI** [comment]
> Describe the bug A clear and concise description of what the bug is.
> 
> Reproducible example https://stackblitz.com/edit/angular-uuvic8?file=styles.css
> 
> To Reproduce Steps to reproduce the behavior (if example is not provided): Override CSS for word-wrap: .ng-dropdown-panel .ng-dropdown-panel-items .ng-optgroup, .ng-dropdown-panel .ng-dropdown-panel-items .ng-option { white-space: normal !important; word-wrap: break-word !important; }
> 
> Expected behavior There should not be extra space****
> 
> ![127499555-d606094f-5a5c-48f4-a8af-4157e0c7b7e3](https://user-images.githubusercontent.com/109080101/179526159-fcbd6798-e936-4dde-8003-46c3d5a37385.png)
> 
> **Desktop (please complete the following information):** OS: Windows Browser: Chrome Angular: V11.0.4 Boostrap: V4.0.0
