### ISSUE TITLE
ng-select-dropdown does not collapse if it is on modal with stopPropagation

### ISSUE THREAD

**Issue by korsar1** [ng-select/ng-select#212]
Please fill below information if issuing a bug report. 
### Expected behaviour
ng-select-dropdown should be collapsed on outer click.

### Actual behaviour
I show ng-select on modal page which has $event.stopPropagation(), and I suppose because of it, if I click on modal box content ng-select-dropdown does not collapse. 

### More Info
ng-select version: 0.14.1

browser: Chrome

reproducible in demo page: NO

**Comment by varnastadeus** [comment]
As you answered yourself, `$event.stopPropagation()` causes this behaviour. You could try closing dropdown yourself.
```html
<modal (click)="select.close()"></modal>
<ng-select #select ></ng-select>
```

**Comment by anjmao** [comment]
@korsar1 Closing this one as solution is clear. Feel free to reopen if you still have any problems.

**Comment by korsar1** [comment]
Maybe it would be better if I would be able to specify to which element by css selector click event should be added, like in appendTo.

**Comment by varnastadeus** [comment]
@korsar1 while you are stopping event propagation it doesn't matter on which element you will bind click event

**Comment by korsar1** [comment]
Correct me if I am wrong, but if I would add click handler on element which are lower in dom hierarchy then the one with stopPropagation then it will be fired.

**Comment by korsar1** [comment]
I tried the solution with 
<modal (click)="select.close(); $event.stopPropagation()"></modal>
But it is not working because when I press on the input, but not on the arrow to open combo, the popup appears but hides on hover on it, because the event on modal was fired also. If I click on arrow to open combo then everything is fine

**Comment by varnastadeus** [comment]
@korsar1 answering your previous question, it could work, but still it won't solve your issue since dropdown won't close while clicking on higher dom elements.
