### ISSUE TITLE
<ng-content></ng-content> into ng-select

### ISSUE THREAD

**Issue by egarciaf2** [ng-select/ng-select#2124]
ng-content does not render.

I am creating a custom component with ControlValueAccessor, where I use ng-select,
the problem arises when I want to send the options inside the label, 
and in ngSelect I show them with a < ng-content>< /ng-content>, the options are not rendered.

This is my custom component
![image](https://user-images.githubusercontent.com/46494114/183276527-f84c409c-e220-4c31-855c-1fab53e97c56.png)

Here using my component
![image](https://user-images.githubusercontent.com/46494114/183276513-8041dd77-ea59-4d41-a9da-3f1968341eb9.png)

**Comment by lockiie** [comment]
did you find any solution? I have the same problem
