### ISSUE TITLE
ng-select: micro frontends in isolation and shadow dom append

### ISSUE THREAD

**Issue by pavliy** [ng-select/ng-select#2126]
Let's look at real case related to company-x:
- They have shell which hosts series of micro frontends. 
- The purpose of shell is let the user get it, click on link and see micro frontend app inside
- There is micro frontend app "mfe-1" which uses ng-select inside.
    - For isolation - mfe1 is shared as web component with view encapsulation 'ShadowDom' enabled.
    - mfe1 uses ng-select and injects css for it directly to web component css
 
 With existing ng-select version - when ng-select gets opened - dropdown is appended to body. Okay, we can specify selector via appendTo, but it won't work for mfe1, because it's web component with ShadowDom. As result - styles for ng-select are hosted in ShadowDom and do not affect added dropdown in scope of document.

To resolve - it's needed to insert dropdown into ShadowDom as well. Then styles are applied well.

Proposed merge request (https://github.com/ng-select/ng-select/pull/2123) - provides new property appendToShadowRoot which allows to specify shadow root parent. And after that appendTo will work in context of ShadowRoot.

**Comment by pavliy** [comment]
Please, review

**Comment by davidoween** [comment]
I need to fix this problem. I use microfront

**Comment by goranvujanovic** [comment]
We also need this fix in our app.
