### ISSUE TITLE
bump version to be in range with angular

### ISSUE THREAD

**Issue by tamusjroyce** [ng-select/ng-select#2127]
**Is your feature request related to a problem? Please describe.**
when upgrading angular, your versions don't match angular versions. So it is difficult to determine when it needs upgraded.

**Describe the solution you'd like**
please write a quick script that would fail if the version doesn't match. Or something that will upgrade/downgrade to match angular version. Could be a git commit or push hook. Manually ran. Something.

backport it across versions

**Comment by marvin-w** [comment]
Why not just read the docs? https://github.com/ng-select/ng-select#versions
