### ISSUE TITLE
Items must be set before selected value when using reactive form approach.

### ISSUE THREAD

**Issue by MartinKutz** [ng-select/ng-select#2130]
Items must be set before selected value when using reactive form approach.

If using the reactive form approach with formControlName, the items must be set before the selected value. Otherwise it results in empty selection.
The items are loaded asynchronous and later available then the selected value.

ng-select version: 9.0.2

**Screenshot of the empty selection:**
![image](https://user-images.githubusercontent.com/17049656/186619980-ce49377c-a99d-4cff-babc-0404d9289372.png)

**Comment by Tinadim** [comment]
I'm experiencing the same issue. Is this per design?
