### ISSUE TITLE
ng-select works only with "arrows" key and "return". 

### ISSUE THREAD

**Issue by dashie** [ng-select/ng-select#214]
If I compile my project and import the library using the angular cli, the control does not work well. I'm not able to digit the text or to filter the results by typing. I'm only able to select the items using arrows keys (up and down) and press "return".

**Comment by dashie** [comment]
I discovered the problem: I was mapping in `items` a getter

```
get myOptions() {
return [
    {label: 'Belgium', value: 'BE'},
    {label: 'Luxembourg', value: 'LU'},
    {label: 'Netherlands', value: 'NL'}
];
}
```

In that way the `ng-select` show me all the options but it does not fully work.

**Comment by varnastadeus** [comment]
@dashie what version you are using? add html code also

**Comment by dashie** [comment]
Version: 0.16.0

Sample:
```
<ng-select
    [items]="myOptions"
    bindValue="value"
    [(ngModel)]="value">
  </ng-select>

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';
  value: any;
  get myOptions() {
  return [
    {label: 'Belgium', value: 'BE'},
    {label: 'Luxembourg', value: 'LU'},
    {label: 'Netherlands', value: 'NL'}
  ];
  }
}
```

**Comment by varnastadeus** [comment]
@dashie just don't use getter and it works as expected. https://plnkr.co/edit/LzKE4r6bpst8DbyVZpmR?p=preview
