### ISSUE TITLE
ng-select dropdown position is not correct in scrollable div

### ISSUE THREAD

**Issue by alabanu** [ng-select/ng-select#2146]
**Describe the bug**
I am facing an issue with ng-select when it is used inside perfect-scrollbar component. I am trying to reset ng-select 
onScroll event of scrollbar selector. 

**Reproducbile example**
[Stackblitz Example](https://stackblitz.com/edit/ng-select-s69xdr) which reproduces described behavior

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome 
 - Version 106.0.5249.119

**Comment by Rohith-T** [comment]
@alabanu Hey could i pick up this issue?

**Comment by alabanu** [comment]
Yes @Rohith-T thank you.

**Comment by alabanu** [comment]
Hi @Rohith-T
Closing dropdown and resetting the arrow position should be the suitable behavior .
Thanks for the effort.
