### ISSUE TITLE
ng-multi-label-tmp is not showing when multiple=true but no item selected

### ISSUE THREAD

**Issue by KarinWin** [ng-select/ng-select#2148]
**Is your feature request related to a problem? Please describe.**
I want to overwrite the label for multiselct, to show how many items the user has selected. But the lable is not showing when no item is selected.

**Describe the solution you'd like**
label should be still visible, even no item is selected

**Comment by zee-18** [comment]
Hi @KarinWin, which label your are talking about?
This 
![image](https://user-images.githubusercontent.com/115869344/197336216-467cbf4f-d1fa-4e74-935c-726269ae94cf.png)
can u provide a screenshot

**Comment by zee-18** [comment]
![image](https://user-images.githubusercontent.com/115869344/197397538-6223fd10-5988-4d53-84e7-2062c4383fb3.png)
This is how label will look like when there's no item selected and then you cant use placeholder as well.
