### ISSUE TITLE
Toggle dropdown programmatically 

### ISSUE THREAD

**Issue by progtarek** [ng-select/ng-select#2150]
**Describe the bug**
I am trying to toggle the dropdown throw a label above, it opens fine but the close not working properly it's flashing and opening again.

here is a code snippet
```
<label (click)="orgSelector?.isOpen ? orgSelector.close() : orgSelector.open()">Trigger</label>

<ng-select [(ngModel)]="selectedCar" #orgSelector>
  <ng-option *ngFor="let car of cars" [value]="car.id">{{
    car.name
  }}</ng-option>
</ng-select>
```

**Reproducbile example**
[[Example](https://stackblitz.com) which reproduces described behaviour](https://stackblitz.com/edit/angular-2zx9i5?file=src/app/app.component.html)

**To Reproduce** 
Steps to reproduce the behavior (if example is not provided):
1. Go to the Stackblitz link attached above
2. Click on the label
3. dropdown opens successfully
4. trying to click again to close, it flashes and disappears for a sec and appears again.

**Expected behavior**
it should toggle properly
 
**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome
 - Version Latest

**Comment by krunal-ctrl** [comment]
`isOpen` is use to open and close it's `@Input` parameter not property of ng-select you can not use it like that below I have attached snippet to get behavior you want 
```
<label (click)="this.isOpen = !this.isOpen">Trigger</label> 
<ng-select [(ngModel)]="selectedCar" #orgSelector [isOpen]="isOpen"> <ng-option *ngFor="let car of cars" [value]="car.id">{{ car.name }}</ng-option> </ng-select> ```

Declare `isOpen` in ts file by default false
