### ISSUE TITLE
Published v10 package not compatible with Angular 15

### ISSUE THREAD

**Issue by luke1992** [ng-select/ng-select#2168]
**Describe the bug**
Published version 10.0.0 on npmjs.org seems to have the wrong peerDeps

**To Reproduce** 
Steps to reproduce the behavior (if example is not provided):
1. `npm install @angular/core@15 @ng-select/ng-select@10` in a blank folder throws the following error:
`
[...]
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/core@"14.2.12" from @angular/common@14.2.12
npm ERR! node_modules/@angular/common
npm ERR!   peer @angular/common@"<15.0.0" from @ng-select/ng-select@10.0.0
npm ERR!   node_modules/@ng-select/ng-select
npm ERR!     @ng-select/ng-select@"10" from the root project`

(same goes for trying the same with a package.json requiring Angular 15 and ng-select v10)

**Expected behavior**
@ng-select/ng-select v10 should support Angular 15 as peer dependency

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser N/A
 - Version N/A
 - NPM Version: 8.11.0
 - Node Version 16.15.1
 
**Additional context**
Inspecting the package.json of the downloaded package from npmjs.org shows:
`"peerDependencies": {
    "@angular/common": "<15.0.0",
    "@angular/core": "<15.0.0",
    "@angular/forms": "<15.0.0"
  },`

**Comment by Kaizodo** [comment]
i am having same issue just installed latest angular 15 and try to install select v10  but it throws following error : 
``
npm ERR! code ERESOLVE

npm ERR! ERESOLVE unable to resolve dependency tree

npm ERR!

npm ERR! While resolving: sacroz-admin@0.0.0

npm ERR! Found: @angular/common@15.0.1

npm ERR! node_modules/@angular/common

npm ERR!   @angular/common@"^15.0.0" from the root project

npm ERR!

npm ERR! Could not resolve dependency:

npm ERR! peer @angular/common@"<15.0.0" from @ng-select/ng-select@10.0.0

npm ERR! node_modules/@ng-select/ng-select

npm ERR!   @ng-select/ng-select@"*" from the root project

npm ERR!

npm ERR! Fix the upstream dependency conflict, or retry

npm ERR! this command with --force, or --legacy-peer-deps

npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

``
