### ISSUE TITLE
Unhandled Promise rejection: Cannot read properties of null (reading 'clientHeight') ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read properties of null (reading 'clientHeight')

### ISSUE THREAD

**Issue by ammad172** [ng-select/ng-select#2177]
We have recently upgraded to Angular 14.2.12 and install ng-select version 9.1.0. Whenever I Open dropdown this error appeared and dropdown wont open unless I click it again to open. This only happens first time but 2nd time if click ,it start working fine.
Below is the error detail and my packages detail which I am right now.

Unhandled Promise rejection: Cannot read properties of null (reading 'clientHeight') ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read properties of null (reading 'clientHeight')
    at ng-select-ng-select.mjs:1709:41
    at _ZoneDelegate.invoke (zone.js:375:26)
    at Zone.run (zone.js:134:43)
    at zone.js:1278:36
    at _ZoneDelegate.invokeTask (zone.js:409:31)
    at Zone.runTask (zone.js:178:47)
    at drainMicroTaskQueue (zone.js:588:35)
    at ZoneTask.invokeTask [as invoke] (zone.js:494:21)
    at invokeTask (zone.js:1664:18)
    at globalCallback (zone.js:1695:29) TypeError: Cannot read properties of null (reading 'clientHeight')
    at http://localhost:4200/vendor.js:197540:35
    at _ZoneDelegate.invoke (http://localhost:4200/polyfills.js:8240:158)
    at Zone.run (http://localhost:4200/polyfills.js:7977:35)
    at http://localhost:4200/polyfills.js:9325:28
    at _ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:8273:171)
    at Zone.runTask (http://localhost:4200/polyfills.js:8030:37)
    at drainMicroTaskQueue (http://localhost:4200/polyfills.js:8482:23)
    at ZoneTask.invokeTask [as invoke] (http://localhost:4200/polyfills.js:8368:11)
    at invokeTask (http://localhost:4200/polyfills.js:9792:12)
    at globalCallback (http://localhost:4200/polyfills.js:9829:21)
    
    Below is the screen of line of code where it throws error and wont work
    
    
![image](https://user-images.githubusercontent.com/35794500/207522578-48284bc8-079b-4ee7-b0bf-4df4665fe6d0.png)

here are my installed packages details

"dependencies": {
    "@angular/animations": "^14.2.12",
    "@angular/cdk": "^8.0.0",
    "@angular/common": "^14.2.12",
    "@angular/compiler": "^14.2.12",
    "@angular/core": "^14.2.12",
    "@angular/forms": "^14.2.12",
    "@angular/localize": "^15.0.2",
    "@angular/platform-browser": "^14.2.12",
    "@angular/platform-browser-dynamic": "^14.2.12",
    "@angular/platform-server": "^14.2.12",
    "@angular/router": "^14.2.12",
    "@ng-bootstrap/ng-bootstrap": "^7.0.0",
    "@ng-select/ng-select": "^9.1.0",
    "@popperjs/core": "^2.11.6",
    "@types/underscore": "^1.11.4",
    "angular-user-idle": "^2.0.0",
    "angular2-text-mask": "^9.0.0",
    "bootstrap": "^4.3.1",
    "cdk-drag-scroll": "0.0.6",
    "chart.js": "^4.0.1",
    "core-js": "^3.25.5",
    "dompurify": "^2.4.1",
    "font-awesome": "^4.7.0",
    "g": "^2.0.1",
    "intl": "^1.2.5",
    "jquery": "^3.6.2",
    "mdn-polyfills": "^5.20.0",
    "moment": "^2.29.4",
    "ng-recaptcha": "^11.0.0",
    "ng2-file-upload": "^1.3.0",
    "ng2-pdf-viewer": "^9.1.3",
    "ng2-signalr": "^10.1.0",
    "ngx-color-picker": "^13.0.0",
    "ngx-image-cropper": "^6.3.1",
    "ngx-order-pipe": "^2.0.2",
    "ngx-pipes": "^2.7.5",
    "ngx-treeview": "^10.0.2",
    "ngx-virtual-scroller": "^4.0.3",
    "p": "^0.2.0",
    "prettier": "^2.8.0",
    "rimraf": "^3.0.2",
    "rxjs": "^7.6.0",
    "signalr": "^2.4.3",
    "storage-emitter": "^2.0.1",
    "tslib": "^2.4.1",
    "underscore": "^1.13.6",
    "webpack-dev-server": "^4.11.1",
    "zone.js": "^0.12.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^14.2.10",
    "@angular/cli": "^14.2.10",
    "@angular/compiler-cli": "^14.2.12",
    "@angular/language-service": "^14.2.12",
    "@types/jasmine": "^4.3.1",
    "@types/jasminewd2": "^2.0.10",
    "@types/jquery": "^3.5.14",
    "@types/node": "^18.11.14",
    "@types/quill": "^2.0.10",
    "codelyzer": "^6.0.2",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "^6.4.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-cli": "^2.0.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "node-sass": "^7.0.3",
    "protractor": "~7.0.0",
    "rxjs-tslint": "^0.1.7",
    "ts-node": "~4.1.0",
    "typescript": "^4.8.4",
    "webpack": "^5.75.0"
  }
  
  Right now none of the versions are working and throwing same error.
  maybe there is any compatibility issue with zone.js or typescript version.

**Comment by Niket16** [comment]
I'm also facing the same issue with Angular 10 and the ng-select 5.X version.

**Comment by ammad172** [comment]
> I'm also facing the same issue with Angular 10 and ng-select 5.X version.

Yes this issue is maybe due to some compatibility or something else i am in 14 of angular version and no idea why it happening. none of the versions of this control are working.

**Comment by ammad172** [comment]
can we open this issue plz
