### ISSUE TITLE
Custom Tag styling

### ISSUE THREAD

**Issue by shyamal890** [ng-select/ng-select#218]
In ng-tags-input we could change the style of tag selected: http://embed.plnkr.co/CcUh1S9kMVxnEI0pfmrn/preview

How to obtain the same in ng-select?

**Comment by varnastadeus** [comment]
@shyamal890 use custom option template

**Comment by varnastadeus** [comment]
Why do you need to add custom class? Just override css as described here https://github.com/ng-select/ng-select#custom-styles

**Comment by shyamal890** [comment]
Depending on a object property say `colorId` I need to modify the background color of the tag. This requires dynamic class.

**Comment by varnastadeus** [comment]
```html
<ng-template ng-label-tmp let-item="item">
    <div [customClassExpression]>label</div>
</ng-template>
```
won't this solve your use case?

**Comment by shyamal890** [comment]
Checkout this plunker: https://plnkr.co/edit/OlzcTF?p=preview

The border styling of `.ng-value` div is still applied.

**Comment by varnastadeus** [comment]
https://plnkr.co/edit/OMdlT4RpJV4DlDMd7gTN?p=preview
just remove borders with your custom css
