### ISSUE TITLE
Pasting multiple values (either COMMA separated or SPACE separated) are not treated as separate tags. Those are treated as a single tag.

### ISSUE THREAD

**Issue by sachinkkarande** [ng-select/ng-select#2195]
**Describe the bug**
Pasting multiple values (either COMMA separated or SPACE separated) are not treated as separate tags. Those are treated as a single tag.

The use case is that, the user wants to paste multiple COMMA-separated items and the expectation is those should be treated as separate tags/values.
(User has some other application providing values in COMMA-separated format and user wants to feed them at once to our component)
But the current implementation treats the whole string as a single tag.
e.g. Pasting “A, B, C” creates a single tag like ”A, B, C”. Expectation is “A” “B” “C”. 

**To Reproduce** 
1. Go to 'https://ng-select.github.io/ng-select#/tags'
2. Copy some comma separated values from text pad like "A, B, C"
3. Paste those values in "Custom tags" component.
4. See that only one tag is getting created like "A, B, C".
5. Expectation is, three tags should get created with value "A", "B" and "C" 

**Current behavior**
<img width="840" alt="One Tag" src="https://user-images.githubusercontent.com/83701351/216967940-bb182d22-a4e7-4345-86ff-c34c31f9fa20.png">

**Expected behavior**
<img width="840" alt="Three Tags" src="https://user-images.githubusercontent.com/83701351/216967958-ae73ac83-7488-4c7e-bba9-e5175cbadb05.png">

Does current component supports this behaviour with some attribute value change?
OR
How can we achieve this functionality?

**Comment by lordnino** [comment]
@sachinkkarande I don't think this behavior is currently supported. One way you could solve it is that you can add an event listener to listen to the select and add your custom logic "created tags" based on your conditions  "commas".

**Comment by kalpeshhpatel** [comment]
> @sachinkkarande I don't think this behavior is currently supported. One way you could solve it is that you can add an event listener to listen to the select and add your custom logic "created tags" based on your conditions "commas".

@lordnino could you please help with some code snippets with the event that we should listen on and use?

Thanks
