### ISSUE TITLE
Feature Request: Handle tag before adding

### ISSUE THREAD

**Issue by shyamal890** [ng-select/ng-select#220]
`onTagAdding` - Expression to evaluate that will be invoked before adding a new tag. The new tag is available as $tag. This method must return either a boolean value or a promise. If either a false value or a rejected promise is returned, the tag will not be added.

In conjunction with `onTagAdding`, `onTagAdded` can also be added.

**Comment by varnastadeus** [comment]
@shyamal890 thanks for feature requests. Can you add some use cases why this would be useful?

**Comment by shyamal890** [comment]
Say a new tag is to be created but before it is added to the list it has be alloted a specific id by the server. 
If the tag is restricted from being created by server.. promise would be rejected.

**Comment by shyamal890** [comment]
Hi @varnastadeus any thoughts on this.

**Comment by varnastadeus** [comment]
Hi @shyamal890. I think this is valid feature and we already had some thoughts about it. `[addTag]` currently accepts function which returns object, it could also return `promise` so this way user could check with server.

**Comment by shyamal890** [comment]
@varnastadeus Any thoughts on when this would be available? Seriously need it asap as its preventing me from implementing a lot of scenarios.
