### ISSUE TITLE
How to change the color of blue highlight

### ISSUE THREAD

**Issue by BoredBrick** [ng-select/ng-select#2208]
I would like to change the color of the blue underline when I click on an ng-select field. Any idea what to change in css?

![obrázok](https://user-images.githubusercontent.com/67233864/223448921-9a79f3f2-512a-411c-95b8-2202c043925a.png)

**Comment by MilesAl** [comment]
Yes, you can explicitly override the style with scss like so:

::ng-deep .ng-select.ng-select-focused .ng-select-container:after {
  border-color: red !important;
  border-width: 2px;
}

**Comment by BoredBrick** [comment]
Works, thank you.
