### ISSUE TITLE
Feature Request: Handling Tag before removal

### ISSUE THREAD

**Issue by shyamal890** [ng-select/ng-select#221]
`onTagRemoving` |- Expression to evaluate that will be invoked before removing a tag. The tag is available as $tag. This method must return either a boolean value or a promise. If either a false value or a rejected promise is returned, the tag will not be removed.

With `onTagRemoving` another event `onTagRemoved` can also be added for expression to be evaluated after tagRemoval

**Comment by varnastadeus** [comment]
@shyamal890 thanks for feature requests. Can you add some use cases why this would be useful?

**Comment by shyamal890** [comment]
Say a new tag is to be created but before it is added to the list it has be alloted a specific id by the server. 
If the tag is restricted from being created by server.. promise would be rejected.


 
 
  On Thu, Feb 1, 2018 at 12:32 AM, Tadeuš Varnas<notifications@github.com> wrote:   
@shyamal890 thanks for feature requests. Can you add some use cases why this would be useful?

**Comment by shyamal890** [comment]
Say a user doesn't have permission to remove a particular tag like `Critical` this should be handle before removing the tag.

**Comment by anjmao** [comment]
Probably we should include all items not only tag, it could be `onItemRemoving` and `onItemRemoved`

**Comment by shyamal890** [comment]
@varnastadeus Can we have the same code which we have for `onTagAdding` here too.

**Comment by shyamal890** [comment]
Would appreciate your thoughts on when this would be available. Trying to migrate from [ng-tags-input](https://github.com/mbenford/ngTagsInput) currently there are no alternates in `ng-select` to features like `onTagAdding` and `onTagRemoving`.
