### ISSUE TITLE
@ng-select/ng-option-highlight is not compatible with Angular v14

### ISSUE THREAD

**Issue by niteshgoyal27390** [ng-select/ng-select#2210]
`npm ERR! Could not resolve dependency: npm ERR! peer @angular/common@">=13.0.0 <14.0.0" from @ng-select/ng-option-highlight@0.0.7 npm ERR! node_modules/@ng-select/ng-option-highlight npm ERR!   @ng-select/ng-option-highlight@"0.0.7" from the root project`

**Comment by AccessViolator** [comment]
Duplicate of https://github.com/ng-select/ng-select/issues/2111

**Comment by niteshgoyal27390** [comment]
@AccessViolator Thanks! Ok, closing this bug and will watch the #2111
