### ISSUE TITLE
Demo page down

### ISSUE THREAD

**Issue by gkamperis** [ng-select/ng-select#2212]
Demo page is not loading on latest Chrome - Win 10.

**Comment by pavankjadda** [comment]
No, I can access it

**Comment by gkamperis** [comment]
I still cannot

**Comment by pavankjadda** [comment]
> @pavankjadda  I still cannot

Try in another browser. Are you connected to VPN?

**Comment by gkamperis** [comment]
no VPN. same for firefox, edge and chrome
