### ISSUE TITLE
Not able to select different values when duplicate values are present in ng-select dropdown.

### ISSUE THREAD

**Issue by Teja0191** [ng-select/ng-select#2214]
To ng-select I am providing array of objects which has different Ids and names. In that I have 2 objects with different Ids but same name. I am using **bindLabel** as name property. Now when I try to select duplicate value, I am able to see only the first occurrence being highlighted even though I have selected second occurrence. 

**Reproducible example**
[[Example](https://stackblitz.com) which reproduces described behaviour](https://stackblitz.com/edit/ng-select-d9ju42?file=polyfills.ts,app%2Fapp.component.ts)

**To Reproduce** 
Steps to reproduce the behavior (if example is not provided):
1. Provide an array of objects with some duplicate items(same names unique Ids) to ng-select and also provide bindLabel as name property of the object.
2. Provide a change event to ng-select.
3. In the call back provided to the change event, reset the items as well as selected item provided in ng-modal.
4. Open the ng-select dropdown and select the last occurrence of the duplicate name.
5. reopen the dropdown and observe that first occurrence is being highlighted.

**Expected behavior**
The selected item from the dropdown needs to be highlighted irrespective of any number of duplicates.

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Version : 111

**Comment by bhaskerchari** [comment]
Hi, I am also facing similar issue. Any solution or work around would be appreciable.

Thanks in advance!

**Comment by bhaskerchari** [comment]
I have resolved the problem myself by using [compareWith] ng-select input function.
