### ISSUE TITLE
demo webpage cannot accessible

### ISSUE THREAD

**Issue by shakib04** [ng-select/ng-select#2215]
**Describe the bug**
I cannot access  the demo page: https://ng-select.github.io/ng-select

This webpage is showing:
Stop!
This website is blocked
The administrator of this network has restricted access to sites categorized as Spyware & Malware.

If you think this is incorrect, you may [suggest a different category.](https://ng-select.github.io/ng-select#)

**Comment by geromegrignon** [comment]
Hello, the demo page is blocked on your side due to a firewall (using a corporate proxy?).
The demo page works as expected.
