### ISSUE TITLE
when click on ng-select to select a value whole FORM scrolls to top

### ISSUE THREAD

**Issue by Saqib92** [ng-select/ng-select#2216]
**Describe the bug**
i have multiple `ng-select` options in my form. when user clicks on any ng-select to select an options my form scrolls to top and ng-select goes down the screen any if click it again it stays where it is. 
I am using it in my Ionic mobile application. 
and this happens only on IOS. 

```
<ng-select [ngClass]="pltfrm == 'ios' ? 'custom-ng-select-ios' : 'custom-ng-select-md'" [items]="challengeList"
          bindLabel="name" bindValue="id" [dropdownPosition]="'top'" [multiple]="true" [closeOnSelect]="false" placeholder="Challenge"
          [searchable]="false" formControlName="challenges">

          <ng-template ng-multi-label-tmp let-items="items">
            <div class="d-flex" *ngFor="let item of (items ? items.slice(0,3): [])">
              <span>
                &nbsp;{{ item.name }},&nbsp;
              </span>
            </div>
            <ng-container *ngIf="items.length > 3">
              <span>{{items.length - 3}} more...</span>
            </ng-container>
          </ng-template>

          <ng-template ng-option-tmp let-item="item" let-index="index" let-item$="item$">
            <div class="d-flex"
              [ngStyle]="{'color': item$.selected ? 'var(--ion-color-primary)': 'var(--ion-color-dark)'}">
              <div style="width: 80%;">{{item.name}}</div>
              <div style="text-align: center; width: 20%;">
                <ion-icon name="checkmark-outline" *ngIf="item$.selected"></ion-icon>
              </div>
            </div>
          </ng-template>
        </ng-select>
```

**Expected behavior**
it should not scroll form when selecting value. 

**Smartphone (please complete the following information):**
 - Device:  Iphone
 - OS: ios 15+

**Comment by didikk** [comment]
Got the same issue, any update to solve this?

**Comment by Saqib92** [comment]
> Got the same issue, any update to solve this?

Unfortunately No, but if you are using ionic framework you can use `ion-select-option` for dropdown selection.

**Comment by didikk** [comment]
> > Got the same issue, any update to solve this?
> 
> Unfortunately No, but if you are using ionic framework you can use `ion-select-option` for dropdown selection.

I'm using Angular, but looks like it's possible to use ionic component in Angular. Thank you for your suggestion.

**Comment by AbhimanyuShrestha** [comment]
# You can adjust in the app.component.ts
NgSelectComponent.prototype.focus = function () {
      if (!this.searchInput.nativeElement.readOnly) {
        this.searchInput.nativeElement.focus();
      };
    };
