### ISSUE TITLE
Dropdown ngModel is not updated

### ISSUE THREAD

**Issue by sale1234** [ng-select/ng-select#2218]
So I have ngModel, which I am trying to populate with data when I click on the button below. I know data ng-select uses the OnPush strategy, but can I somehow override this or is there any workaround besides changing the reference ( this approach is working btw)?
I tried with https://angular.io/api/core/ChangeDetectorRef#markForCheck but it's working.

The value that is inside the model(from above) should be should inside the dropdown.

![image](https://user-images.githubusercontent.com/57576357/231199350-556d6d70-d0e2-446e-bd02-2a08d0edb590.png)

- OS: Windows 10
 - Browser: every
 - Version: last version of ng-select

**Comment by bhaskerchari** [comment]
Hi @sale1234 ,

Your question is not very clear it's probably better if you can share some sample code or create a sample and show case your problem that would be helpful in addressing your problem.

**Comment by aparzi** [comment]
Hi issue still present. It looks similar to this #2285. Please find a possible solution or fix
