### ISSUE TITLE
Demo page is broken

### ISSUE THREAD

**Issue by clement911** [ng-select/ng-select#2228]
The [demo link](https://ng-select.github.io/ng-select) seems to be broken 

![image](https://user-images.githubusercontent.com/3426504/236998102-61d3e605-79f3-460c-8e66-815524ba72d0.png)

**Comment by JonasDev17** [comment]
I can confirm, the demo page seems to be down

**Comment by sannyjacobsson** [comment]
Same issue 

![image](https://github.com/ng-select/ng-select/assets/11787831/6a3dcc7b-2a2e-4a64-8e63-3939efaffc21)

**Comment by sannyjacobsson** [comment]
For some reason "Network Protection with Trend Micro" decided to block the demo page. You may want to check your spam/phishing filters.

**Comment by pavankjadda** [comment]
It's working fine for me.

**Comment by clement911** [comment]
It's still happening for me @pavankjadda.
I tried both in Chrome and Edge.

![image](https://github.com/ng-select/ng-select/assets/3426504/ffe5c9e5-2b71-4137-93f4-acd0238fcfc7)

**Comment by pavankjadda** [comment]
> It's still happening for me @pavankjadda. I tried both in Chrome and Edge.
> 
> ![image](https://user-images.githubusercontent.com/3426504/241080964-ffe5c9e5-2b71-4137-93f4-acd0238fcfc7.png)

It is hosted in github.io domain, so probably an issue with your browser. Can you try in mobile?

**Comment by mikesimmonds** [comment]
I was experiencing a similar issue.
It turned out that my ISP (NOW Broadband, UK) was blocking the site with its default security.

I had to specifically whitelist the site to be able to access it.
