### ISSUE TITLE
how to get outputs if (close) event fired?

### ISSUE THREAD

**Issue by vahidsamimi** [ng-select/ng-select#2232]
I want to get item(s), that is already selected by user when the dropdown is closed. 

but [here ](https://github.com/ng-select/ng-select/blob/97bb1ff8962300599d534c2806e88be12d6c58a9/src/ng-select/lib/ng-select.component.ts#L446) the closeEvent does not send any data as output.

**Comment by tomer953** [comment]
the selected items is binded to a property you choose:

[(ngModel)]="selectedCar"

 so when you receive the event, just read the value of selected Car
