### ISSUE TITLE
ng-select: "X"(Clear all) button in the dropdown is not accessible through   the keyboard "Tab" key. [It is only accessible through Mouse]

### ISSUE THREAD

**Issue by sachinkkarande** [ng-select/ng-select#2239]
**Describe the bug**
ng-select: "X"(Clear all) button in the dropdown is not accessible through the keyboard "Tab" key. [It is only accessible through Mouse]
Testes with latest version of ng-select 10.0.4. Same thing is observed.

**Reproducbile example**
* Editor URL:
https://stackblitz.com/edit/angular-diubgn-vwtxy7?file=src/template-search-example.component.html
* Application URL:
https://angular-diubgn-vwtxy7.stackblitz.io

**To Reproduce** 
Steps to reproduce the behavior :
1. Do not use Mouse
2. Use only keyboard to navigate to the ng-select dropdown
3. from ng-select dropdown select any option
4. Use keyboard "Tab" key to select the "x" clear all button
5. Observe that "X" Clear all button does not receive keyboard focus and not accessible

**Expected behavior**
"X" Clear All button should be keyboard accessible. So that User using only keyboard will able to access the button.

**Screenshots**
Check GIF: "ng-select X clear all button not selectable through keyboard tab.gif"
![ng-select X clear all button not selectable through keyboard tab](https://github.com/ng-select/ng-select/assets/83701351/58726598-2b3a-4206-b463-631e436df079)

**Desktop (please complete the following information):**
 - OS: macOS Ventura version 13.3.1
 - Browser: Chrome, FF, Safari.

**Additional context**

**Comment by WaseemSabir** [comment]
what would be better experience? 
1. Esc clears the text 
2. Tab moves to focus on the “X” button

I want to contribute, can I take this? @pavankjadda

**Comment by pavankjadda** [comment]
Sure. Take itThanks and Regards Pavan Kumar JaddaOn May 28, 2023, at 4:26 PM, Waseem Sabir ***@***.***> wrote:﻿
what would be better experience?

Esc clears the text
Tab moves to focus on the “X” button

I want to contribute, can I take this? @pavankjadda

**Comment by sachinkkarande** [comment]
Hi,

As per accessibility requirment, X should be focusable using TAB key. And
ENTER key on X should mimic click behaviour.

Thank you!

**Comment by luanadeoliveira** [comment]
The X clear all "button" is in a span tag... so I wonder if just adding the attribute  `role="button"` and `tabindex="0"` or just updating the tag from span to button.

**Comment by simon-asp** [comment]
Hello! Any news on this? Working for an organization where accesibility is very high prio, this would help :) 

I agree that the "X" button should be focusable with the tab key

**Comment by pavankjadda** [comment]
Merged

**Comment by LAURENS-Damien** [comment]
Hi,

I think the point "Tab moves to focus on the “X” button" need to be enhanced for "Shift tab" because currently, users are blocked in the component instead to be able to focus previous element in the DOM.
Are you ok with my proposition?
