### ISSUE TITLE
&amp; showing instead of & in input 

### ISSUE THREAD

**Issue by tayyab-1** [ng-select/ng-select#2241]
**Describe the bug**
One option in ng-select statement is `H&M`, while it is showing fine in the dropdown when it is selected &amp; shows instead of & in input.

**Reproducbile example**
this is code for ng-select
```
<ng-select class="text-left-last option-field"
                         placeholder="{{'companies.parent-company' | translate}}" formControlName="parent_id"
                          [clearable]="false" [editableSearchTerm]="true"
                          [ngClass]="{ 'errCls':companyForm.value['parent_id'] == null && isSubmit }">
                          <ng-option *ngFor="let parentCompany of companyService.allParentCompaniesList | async"
                            [value]="parentCompany.id" [innerHTML]="parentCompany.name | safeHtml"></ng-option>
                        </ng-select>
```

**Expected behavior**
It should show `H&M` in input too.

**Screenshots**
<img width="249" alt="Screenshot 2023-05-26 at 12 23 33 AM" src="https://github.com/ng-select/ng-select/assets/119036071/7b428cab-2bcc-48c5-bee0-d64c0bba75c6">
<img width="276" alt="Screenshot 2023-05-26 at 12 23 48 AM" src="https://github.com/ng-select/ng-select/assets/119036071/89367bd5-400b-4a36-8721-7ad7d4e6bb2d">

**Desktop (please complete the following information):**
 - OS: Mac Os
 - Browser: Chrome
 - ng-select Version: 10.0.1

**Comment by pavankjadda** [comment]
Can you share reproducible StackBlitz example?

**Comment by tayyab-1** [comment]
I have `[editableSearchTerm]="true"` so as soon as I click on ng select container, its value becomes editable in an input field which in turn changes & to &amp;
