### ISSUE TITLE
 cannot remove selected dropdown single value from typescript in angular for  [(ngModel)]="selectedPersons"

### ISSUE THREAD

**Issue by PRANEEESH-REDDY** [ng-select/ng-select#2249]
**Describe the bug**
 cannot remove selected dropdown single value from typescript in angular for  [(ngModel)]="selectedPersons"         

**Reproducbile example**

[(ngModel)]="selectedPersons"  
here when we pop a single item form array of selectedPersons we cannot get cahnges of those in frontend.

  

**Expected behavior**
but we want it to change the values in frontend dynamically

**Screenshots**
<img width="1271" alt="image" src="https://github.com/ng-select/ng-select/assets/63895094/faf4b9d2-f0df-4271-8291-f8fcae5526f5">

Solution i found 👍 
when we make the toatal array to empty and again populate it we can see the change in frontend to. but it sholud not be like that

**Comment by PRANEEESH-REDDY** [comment]
help bug

**Comment by brynnlow** [comment]
try this

```
this.selectedCompanies.pop()
this.selectedCompanies = [...this.selectedCompanies];
```

**Comment by PRANEEESH-REDDY** [comment]
thanks for clarification.... 👍 (:
