### ISSUE TITLE
Touched is not set when Mouse clicking into Select

### ISSUE THREAD

**Issue by RanadeepPolavarapu** [ng-select/ng-select#225]
### Expected behaviour
On clicking into a select, `touched` should be set.

### Actual behaviour
On Tabbing into the select and losing focus, it triggers the `formControl` to be `touched`. Right now, clicking into a select and losing won't set `touched`. `Touched` is only set when you click into a select AND select an option. Normal HTML select field will be touched as soon as the user interacts with it whether it's by keyboard or mouse click.

### More Info
ng-select version: `0.16.0`

browser: Chrome 63

reproducible in demo page: Yes

**Comment by anjmao** [comment]
@RanadeepPolavarapu Thanks for reporting. Indeed I was able to reproduce it. It should be a quick fix and probably will be fixed today.
