### ISSUE TITLE
Search is not working properly

### ISSUE THREAD

**Issue by AndrVdov** [ng-select/ng-select#2254]
Hello.
I use this in my project:
https://ng-select.github.io/ng-select#/virtual-scroll
It works well, but I have a problem.
If we use the search, we will see that it is only looking for that small piece of data that is currently available in the options.
It is obvious that this does not work correctly, the search should be on all elements of the "photos" array, not "photosBuffer".
Passing in [items]="photos" instead of photosBuffer is a bad idea. This way we will lose the lazy loading effect.

**Comment by high54** [comment]
Hello,

you need to provide a custom search function that searches in the list of all items and update the buffer according to the results found.

`<ng-select [items]="itemsBuffer$ | async" [virtualScroll]="true" (search)="filter($event)" ...></ng-select>`

In this search function, you'll need to pay particular attention to groups, child elements and duplicate elements.

And with virtual scroll, if you're listening to the scroll event, you'll also need to take care that the number of elements filtered by the search is less than the number of elements the virtual scroll should load.

At this point, the virtual scroll will constantly try to load more elements, which is annoying.

I hope this helps
