### ISSUE TITLE
Style Validation not formatted

### ISSUE THREAD

**Issue by brux88** [ng-select/ng-select#227]
Hi, 
thank you for this control, is very prestty and beautifull
![2018-02-02_1924](https://user-images.githubusercontent.com/3495339/35748580-c730dc68-084e-11e8-999b-cc5495c5327e.png)

I added the validation class for css. work in any control, but in this control. it does not show well.

this is my css class:
`.ng-valid[required], .ng-valid.required  {
    border-left: 5px solid #42A948; /* green */
}

.ng-invalid:not(form)  {
    border-left: 5px solid #a94442; /* red */
}`

how can i fix this?

i added a screenshot

**Comment by varnastadeus** [comment]
@brux88 we don't define validation style in bundle, just change css in your app.
