### ISSUE TITLE
Change event is being called twice when using custom search

### ISSUE THREAD

**Issue by HigorMichelotti** [ng-select/ng-select#2274]
**Describe the bug**
Change event is being called twice when using custom search

**Reproducbile example**
Example: https://stackblitz.com/edit/angular-6bd5zv?file=src%2Ftemplate-search-example.component.html
Error: Notice that in the console it is possible to see the change being executed twice

**To Reproduce** 
To view the error just filter an element and then select one of the filtered elements, for some reason it fires the change event twice instead of once.

Note: sometimes it doesn't happen the first time, you must redo the filter and select a filtered element again to see the change event being executed twice.

Note: this does not occur when we are not using the custom search

**Expected behavior**
The correct thing to happen in this scenario is that the change event was executed only once

**Desktop (please complete the following information):**
 - Browser [Chrome]
 - Version [115.0.5790.110]
 
**GIF**
![2023-08-16-16-53-05](https://github.com/ng-select/ng-select/assets/39974390/cf6f05b4-c4bd-408c-918b-d282c0fbfa09)

**Comment by ricardomac** [comment]
up

**Comment by pavankjadda** [comment]
This is caused by using 
```
@Output('change') changeEvent = new EventEmitter();
``` 

same name as default HTML `change()` event. This causes name collision and triggers events 2 times. There is nothing we can do since it will break many apps if we try to rename it.
