### ISSUE TITLE
Safari 16.0 jumps to top when clicking on dropdowns with searchable turned off

### ISSUE THREAD

**Issue by tructuthien** [ng-select/ng-select#2279]
**Describe the bug**
The same as the bug described in the issue
[Safari 16.0 jumps to top when clicking on dropdowns with searchable turned off](https://github.com/ng-select/ng-select/issues/2133)
**Expected behavior**
Fix it in the v9.x

**Comment by Trung19091997** [comment]
I am facing the same problem. For some reason, I can not upgrade my project to ng-select v10. Could you release it to v9 please?
Thank you.

**Comment by kheos31** [comment]
Hello, FYI the "correction" for the linked issue introduce a new bug https://github.com/ng-select/ng-select/issues/2221.
