### ISSUE TITLE
Non matching items in dropdown still show

### ISSUE THREAD

**Issue by fl4kez** [ng-select/ng-select#2283]
**Description**
Dropdown always show all items and not only ones found with searched value.
EDIT: Seems like the [typeahead] property is the problem here. No clue why though :/
For example:
Search value: "me"
Found: ["Karyn Wright","Rosales Russel","Mendoza Ruiz","Franklin James"]

**Expected behavior**
Dropdown only shows items that are found with searched value.
For example:
Search value: "me"
Found: ["Mendoza Ruiz","Franklin James"]

**Screenshots**
![image](https://github.com/ng-select/ng-select/assets/37409166/e3405096-4eec-44dd-9890-a09851beb543)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
HTML-Code:
```
<ng-select [items]="allModels" [(ngModel)]="searchModel" (change)="searchChanged()" placeholder="Search..."
  bindLabel="name" bindValue="name"  [typeahead]="searchAhead" typeToSearchText="Search...">
    <ng-template ng-option-tmp let-item="item" let-index="index" let-search="searchTerm">
      <div class="card-body row">
        <div class="col-2">
          <h6 class="card-title" [ngOptionHighlight]="search">{{item.name}}</h6>
          <img style="max-width: 64px;border: solid #dee2e6 1px;display: block" [src]="item.image" alt="{{item.name}}-image">
        </div>
        <div class="col-5">
            <ng-container *ngFor="let type of item.types|keyvalue">
              <div style="float:left;text-align: center;">
                <img src="../../assets/images/{{ type.key }}.png"  alt="{{ GetValueFromMap(type.key) }}" ngbTooltip="{{ GetValueFromMap(type.key) }}" style="padding: 3px;max-width: 20px;" class="img-fluid">
                <br>
                <ng-container *ngIf="type.value == 1; else typeUnavailable">
                  <i class="bi bi-check h5" style="color:green"></i>
                </ng-container>
                <ng-template #typeUnavailable>
                  <i class="bi bi-x-circle h5" style="color:red"></i>
                </ng-template>
              </div>
            </ng-container>
        </div>
        <div class="col-5">
          <app-tag-input [enteredTags]="item.tags" [isRemoveable]="false" [tagPlaceholder]="emptyString" [disable]="true" [hideForm]="true" [getTags]="false"></app-tag-input>
        </div>
      </div>
    </ng-template>
  </ng-select>
```

**Comment by DashiShoyu** [comment]
This is because if typeahead is detected, itemList will not trigger filter, and it will rely on filtering through the back-end instead. I've stumbled upon this and there's 2 options to take:
1. Create a personal patch through patch-package and remove "this.istypeahead" from this line:
`if (this.isOpen && isDefined(this.searchTerm))`
2. filter results through a pipe
