### ISSUE TITLE
Can't bind to 'bindLabel' since it isn't a known property of 'ng-select' in Angular 15

### ISSUE THREAD

**Issue by ammad172** [ng-select/ng-select#2286]
I have migrated my Project to Angular 15 and than I have updated ng-select to the latest version which is 11.1.1 and than why I am trying to run the project all the files containing ng select giving errors that they cannot bind the property since it is not the known prop of ng select

![image](https://github.com/ng-select/ng-select/assets/35794500/a33c6bfe-5f0d-4239-b05a-55d9b0fb4b0a)

These are my project stats

![image](https://github.com/ng-select/ng-select/assets/35794500/49a72991-7b98-4778-b7da-63b6c8ae6fe1)

if you go to the definition of ng select all the props exists but the components are throwing errors that they cant bind them as they unknown

**Comment by pavankjadda** [comment]
Can you share StackBlitz example?

**Comment by wwarby** [comment]
Same issue for me after upgrading from ng-select 10.0.4 to 11.2.x. No Angular upgrade for me yet - still on 14, so this is a pure ng-select breaking change. My code works in 10.x and not in 11.x with no other changes.

**Comment by ammad172** [comment]
issue is still there
