### ISSUE TITLE
Stop Enter From Selecting

### ISSUE THREAD

**Issue by DOrsulak-SOLIEL** [ng-select/ng-select#2287]
Is it possible to prohibit the enter key from selecting/ unselecting a select option when mult select is enabled?

Here is what I tried (it did not help):

Note keydown.enter failed was not an option for me:
      "Event keydown.enter is not emitted by any applicable directives nor by ng-select element"

```
<ng-select (keydown)="keydownInDropdown($event)">

  keydownInDropdown(event: any) {
    if (event.key === 'Enter') {
      event.preventDefault();
      event.stopImmediatePropagation();
      event.stopPropagation();
    }
  }
```

version: "@ng-select/ng-select": "^9.1.0",

**Comment by pavankjadda** [comment]
This is intended bahaviour. Why do you not want that?

**Comment by ivanmonteiro** [comment]
> This is intended bahaviour. Why do you not want that?
@pavankjadda I'm not the OP but I want this because using a barcode scanner.
It sends a carriage return (enter) immediately after the barcode. 
So it selects the first option... of which the user would want to see the dropdown list and choose one of the product variants available :/
