### ISSUE TITLE
Groups should be searchable

### ISSUE THREAD

**Issue by emir7** [ng-select/ng-select#2290]
**Is your feature request related to a problem? Please describe.**
Currently the problem is that you can not search items by group names. This prevents me from autocompleting group elements and users can not search by them. 

**Describe the solution you'd like**
When user enters a term that matches a group name item or an item name within a group, corresponding group with its items should be displayed.

**Describe alternatives you've considered**
The only alternative that comes into my mind is to manually filter and pass a new items array every time a user types something, but I think that this should be handled by the `filter` function.

**Comment by emir7** [comment]
@pavankjadda a simple reproduction example can be found at https://ng-select.github.io/ng-select#/grouping 
you can type any group name and it won't be displayed in search result.
I can try and pick this issue if you consider it as a feature. I can add a config boolean (shouldAutocompleteGroups or something similar) so that current behaviour won't change.

**Comment by pavankjadda** [comment]
> @pavankjadda a simple reproduction example can be found at https://ng-select.github.io/ng-select#/grouping 
> 
> you can type any group name and it won't be displayed in search result.
> 
> I can try and pick this issue if you consider it as a feature. I can add a config boolean (shouldAutocompleteGroups or something similar) so that current behaviour won't change. 

I am able to search groups. Perhaps add a gif or video?

**Comment by emir7** [comment]
![Screenshot 2023-10-22 at 21 34 52](https://github.com/ng-select/ng-select/assets/
![Screenshot 2023-10-22 at 21 35 06](https://github.com/ng-select/ng-select/assets/55662365/d5b43677-552a-4f41-80b9-fe05ffa1146d)
55662365/f51591a3-0916-423e-996f-43cde5763166)
well lets take this example.. if you try and type "project b" it won't be found 
(if you repeat the same same steps with any other example the result will be the same)

**Comment by rahulbinari** [comment]
hi @emir7  you can make custom search for group options. check this example 
https://ng-select.github.io/ng-select#/search
