### ISSUE TITLE
Backwards tabbing broken with Clear Button keyboard accessibility fix 

### ISSUE THREAD

**Issue by danielsefton** [ng-select/ng-select#2301]
**Describe the bug**
After the release of [PR2445](https://github.com/ng-select/ng-select/pull/2245) I can no longer tab backwards, the focus remains cycling between the select box and the clear button.

**Reproducbile example**
The official [demo page ](https://ng-select.github.io/ng-select)

**To Reproduce** 
1. Tab to the select box with TAB
2. Keep pressing SHIFT + TAB
3. Notice the focus is captured between the select box and the clear button

**Expected behavior**
Pressing SHIFT + TAB while the select box is focused should focus the previous tabbable element on the page.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version: Latest

**Additional context**
I would say this is a high priority fix as it will break the keyboard accessibility of every web app that uses the component.

**Comment by smorandi** [comment]
yes indeed, very annoying :|

**Comment by boltex** [comment]
@pavankjadda is it possible to disable the 'focus on clear button' with tab key?
