### ISSUE TITLE
Keyboard focus jumps to mouse position

### ISSUE THREAD

**Issue by tvaittin** [ng-select/ng-select#2307]
Using keyboard arrow keys, scrolling the dropdown to the last visible item in the dropdown and pressing the down arrow key once more, the list items move up one step and reveal one more list item on the bottom (as they should). If one has moved the mouse cursor outside of the dropdown, the keyboard focus moves to the new last visible item (as it should). 

But if one has left the mouse cursor on top of one of the list items in the dropdown, the keyboard focus jumps to the list item the mouse is hovering and one has to press the down arrow key several times to get back to the bottom of the visible items to get the list scroll again. This makes the scrolling much slower and is quite unexpected behavior for the users.

This happens for example on the [official demo page examples](https://ng-select.github.io/ng-select#/data-sources) (and on our implementations). 

 - OS: Mac & Windows
 - Browser: Chrome, Safari, Edge

**Comment by AndreyChayko** [comment]
We also faced with this issue, this should be reopened !
