### ISSUE TITLE
Can't access header or footer area in dropdown with keyboard

### ISSUE THREAD

**Issue by simon-asp** [ng-select/ng-select#2312]
**Describe the bug**
Hello! We have many keyboard users in our app, and value a11y in our organization. We have noticed that interactive elements inside headers or footers inside the ng-select dropdown can't be accessed via keyboard.

**Reproducbile example**
[Example](https://ng-select.github.io/ng-select#/templates) on ng-select demo page (Custom header footer template) or,
[Stackblitz example](https://stackblitz.com/run?file=src%2Ftemplate-header-footer-example.component.html) of the same demo.

**To Reproduce** 
Steps to reproduce the behavior (if example is not provided):
1. Focus to the input field with the header example
2. Press enter or space to open the dropdown
3. Use arrows to navigate the dropdown, and use tab to close the dropdown.

**Expected behavior**
We expect interactive elements inside header/footer area to be accessible with the tab key.

With both header and footer we think it should work like this:
1. Open the ng-select dropdown.
2.  First interactive element should be focused (either in header area, or the select values if no header area)
4. Hit tab key - Any interactive element in the footer area should be focused.
5. Hit tab again - the dropdown should be closed (after the last interactive element)

**Screenshots**
Here is an example from the Swedish Public Employment Service (Sorry, in Swedish). Try using the keyboard to focus the footer area inside the dropdown, it works like I explained above.
https://designsystem.arbetsformedlingen.se/komponenter/digi-form-filter/oversikt
<img width="413" alt="image" src="https://github.com/ng-select/ng-select/assets/20322882/c42791da-b235-4774-a020-71a081024cb6">

**Desktop (please complete the following information):**
 - OS: MacOs 13.2.1
 - Browser: Chrome
 - Version: 119.0.6045.105

**Comment by simon-asp** [comment]
Anyone?

**Comment by ettlitetlov** [comment]
We have the same issue, accessing interactive items in footer/header is not possible. The expected behaviour, using TAB, when select drop down is open, is to be able to tab through all interactive elements, until reaching the last element, where the next tab click will result in drop down closing and selecting next interactive element on page. The current behaviour is just instantly closing the drop down and targeting the next interactive element in the DOM.
