### ISSUE TITLE
Win10 with the input method, 360 browsers enter Chinese

### ISSUE THREAD

**Issue by jansonlwj** [ng-select/ng-select#232]
https://pan.baidu.com/s/1i6MCUSd

**Comment by varnastadeus** [comment]
Can you explain the issue?

**Comment by anjmao** [comment]
@jansonlwj Please add normal description and do not add such links which looks like a virus.

**Comment by jansonlwj** [comment]
Win10 input method, input Chinese, under 360 browsers will enter a lot of English letters
