### ISSUE TITLE
The arrow is not displayed correctly with "ant.design" theme

### ISSUE THREAD

**Issue by ShiJuuRoku** [ng-select/ng-select#2321]
**Describe the bug**

The arrow is not displayed correctly with "ant.design" theme

**https://ng170xempty-c4h0--4200--6843a59c.local-corp.webcontainer.io/**

**Reproducbile example**

1. Import the theme
  `@import "@ng-select/ng-select/themes/ant.design.theme.css";`

2. Create a simple component
```
import { Component } from "@angular/core";
import { FormsModule } from "@angular/forms";
import { NgSelectModule } from "@ng-select/ng-select";

@Component({
    selector: 'app-ng-select',
    standalone: true,
    imports: [FormsModule, NgSelectModule],
    template: `
        <p> Ng-Select component </p>
        <ng-select [items]="cars" 
           bindLabel="name" 
           bindValue="id" 
           [(ngModel)]="selectedCar"
        ></ng-select>
    `
})
export default class NgSelectComponent {
    protected selectedCar?: number;

    protected readonly cars = [
        { id: 1, name: 'Volvo' },
        { id: 2, name: 'Saab' },
        { id: 3, name: 'Opel' },
        { id: 4, name: 'Audi' },
    ];
}
```

**Expected behavior**
Like the default theme the arrow should be displayed correctly

**Screenshots**

![image](https://github.com/ng-select/ng-select/assets/3122358/26b3eecb-a09d-48bc-a4f1-4e80c3ee372e)
![image](https://github.com/ng-select/ng-select/assets/3122358/caf15c8c-6a0c-480d-b9c3-ffa6307c814f)

**Workaround**
Import the theme into any selector, in this way the scope will be more precise so the theme applies correctly 
```
body {
  @import "@ng-select/ng-select/themes/ant.design.theme.css
}
```

**Desktop :**
 - Angular 17.0.4
 - @ng-select/ng-select 12.0.4
 - Browser Chrome

**Comment by andersonmmendes** [comment]
Hi @ShiJuuRoku.

I had the same issue in my Angular 18 app. To display the arrow, I added the following style in my styles.scss:

```
.ng-select .ng-arrow-wrapper .ng-arrow {
  width: 8px !important;
  height: 8px !important;
}

.ng-select .ng-clear-wrapper {
  position: absolute !important;
  width: 12px !important;
}

.ng-select .ng-clear-wrapper .ng-clear {
  font-size: 12px !important;
  line-height: 12px !important;
}
```

Solution suggested by **r0fest**: https://github.com/ng-select/ng-select/issues/1462#issuecomment-617726128
