### ISSUE TITLE
scrollToEnd not getting emitted after initial emit.

### ISSUE THREAD

**Issue by vinaymerugu13** [ng-select/ng-select#2323]
**Describe the bug**
When I scrolled down in dropdown panel( first time), scrollToEnd is getting emitted. After that, when changes are made in the items list, it stopped getting emitted.
**Reproducbile example**

[Example](https://stackblitz.com) which reproduces described behaviour

**To Reproduce** 
Steps to reproduce the behavior (if example is not provided):
2. Click on 'ng-select'
3. Scroll down to 'end'

**Expected behavior**
Every time scroll reaches its end, scrollToEnd should emit.
**Screenshots**

**Desktop (please complete the following information):**
 - macOS
 -  chrome
 - 119.0.6045.199

**Additional context**
Once you reach the end of dropdown panel, you could see scrollToEnd getting emitted. Then add another 50 same items to the list. 
Now scroll to end, you will see scrollToEnd is not emitted.
I have debugged the code and found out that  _scrollToEndFired is not getting set to false, after true, upon item changes in _onItemsChange method.
In _fireScrollToEnd, it is getting returned.

**Comment by pavankjadda** [comment]
@vinaymerugu13 the link takes me to https://stackblitz.com not your example

**Comment by vinaymerugu13** [comment]
https://github.com/ng-select/ng-select/pull/2324 This is the PR I raised after raising the issue. I did it from my different GitHub account. Please checkout.

**Comment by vinaymerugu13** [comment]
What happened @varnastadeus please update
