### ISSUE TITLE
Safari 16.0 or 17.0 jumps to top when clicking on dropdowns

### ISSUE THREAD

**Issue by dernich** [ng-select/ng-select#2334]
Describe the bug
Using Safari 16 or 17, all dropdowns that have searchable turned off makes the page jump to the top.

To Reproduce
Steps to reproduce the behavior (if example is not provided):
angular: v17.0.9
ng-select: v12.0.4

Ensure to have page with scroll bar and the select field is located at the end of the page.
Click on the select input to display the dropdown options.
The scroll is reset at the top of the page.

Expected behavior
Should open dropdown without the page scroll.

Desktop (please complete the following information):
OS: MacOS 14.1.2
Browser Safari
Version 17.1.2

**Comment by dernich** [comment]
Indeed the following commit fix the issue: https://github.com/ng-select/ng-select/pull/2134/commits/524d8a73a2f36d8883fc4146691620165ecbb100

But, it has been reverted due to an accessibility issue. (see following commit https://github.com/ng-select/ng-select/pull/2229/commits/7ca64cea03baf5c4f6efaaefe0b11441a8a21404)

**Comment by dernich** [comment]
@pavankjadda any news ?

**Comment by mvanholstyn** [comment]
I ran into this issue this week as well.

**Comment by daniemo2** [comment]
Also facing this issue - any update here?

**Comment by matteo-minerva** [comment]
fyi: you can easily fix the issue by setting `user-select: unset;` via CSS on the inner readonly input

**Comment by dernich** [comment]
@matteo-minerva Yes this is working. Thank you
