### ISSUE TITLE
Search term does not update when ngModel is updated

### ISSUE THREAD

**Issue by etherfactor** [ng-select/ng-select#2340]
**Describe the bug**
Whenever an ng-select component with `[editableSearchTerm]="true"` is touched, the search term value is not updated. As a result, any touched ng-select component will not display any changes to ngModel until the component is clicked again. Inspecting the component at runtime, the `<span class="ng-value-label">` is successfully updated whenever ngModel changes, but the `<input #searchText>` is not.

**Reproducible example**
[Example](https://github.com/etherfactor/ng-select-ngmodel) which reproduces described behavior.

**Expected behavior**
Whenever ngModel is updated, if `[editableSearchTerm]="true"`, the text display matches the label of the newly-selected item. By extension, the `<input #searchText>` displays what is being displayed (but hidden) via `<span class="ng-value-label">`.

**Desktop**
 - OS: Windows
 - Browser: Chrome
 - Version: 120

**Additional context**
N/A

**Comment by jessicabarbalho** [comment]
I'm facing the same issue

**Comment by shayanpaul** [comment]
I am facing the same issue. I can see others have reported the same issue earlier. I am not sure why no action has been taken. Does ng-select is not maintainable anymore?

**Comment by LuxD88** [comment]
I am still facing the same issue with version 13.9.1
