### ISSUE TITLE
Text stay after enter when add Tag

### ISSUE THREAD

**Issue by MatDepInfo** [ng-select/ng-select#2346]
I have v12 and when I add an item manually with [addTag], the value I entered is not cleared.
![Capture d’écran 2024-02-12 à 14 50 59](https://github.com/ng-select/ng-select/assets/13313050/c58e9d7f-6980-46c0-bec8-28db5667fc39)

**Comment by MatDepInfo** [comment]
Hum closed... But the problem is still present...

**Comment by pavankjadda** [comment]
> Hum closed... But the problem is still present...

In that case send us reproducible Stackblitz example.

**Comment by MatDepInfo** [comment]
Here it is: https://stackblitz.com/edit/angular-jck7c4?file=src%2Fmulti-select-default-example.component.html
When you type anything to add a new element, then "enter" to add, you will see that the new tag is well added, but the text il not cleared.
