### ISSUE TITLE
Bug in reactive forms with custom template

### ISSUE THREAD

**Issue by ayaankhan98** [ng-select/ng-select#2353]
**Describe the bug**
there is breaking UI in reactive forms with custom template when you press open in model button and try to choose a favorite photo, please refer to the screenshot below to see the breaking UI.

**Reproducbile example**
[Example](https://stackblitz.com) which reproduces described behaviour

**To Reproduce** 
Steps to reproduce the behavior (if example is not provided):
1. Go to https://ng-select.github.io/ng-select#/forms
2. scroll down to reactive forms with custom template
3. click on open in model
4. click on select photo under favorite photo.

**Expected behavior**
It should open a select box to choose between different available options.

**Screenshots**
![bug](https://github.com/ng-select/ng-select/assets/43348292/277f1732-0b57-4b70-92c6-c97d5733b07d)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux x86_64
 - Browser: Mozilla Firefox 122.0
 - Version 122.0

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pavankjadda** [comment]
@ayaankhan98 Apart from demo, where else do you see this?

**Comment by ayaankhan98** [comment]
Perhaps I have seen this only in demo section, If I'll come across somewhere else, I will update the issue.
