### ISSUE TITLE
tabIndex backwards not working with clear button

### ISSUE THREAD

**Issue by RobinAraCom** [ng-select/ng-select#2366]
**Describe the bug**
when you have the dropdown in focus and press tab, you get to the clear button as expected.
when you press shift + tab you get back to the dropdown as expected.
when you press shift + tab (from the dropdown) you are supposed to get to the previous input, but you get to the clear button (the next elemet).

**Reproducbile example**
live demo, probably everywhere work for me on the first dropdown I saw.

**more info**
when you spam shift + tab it toggels between the dropdown and the clear button. Even tho there are alot of other inputs on the page.

**Comment by lssbq** [comment]
Same issue encounted, it trapped the focus and prevent user navigate back by keyboard.
I can only focus backward by 'shift + tab' on the dropdown panel opened.

**Comment by jucasoft** [comment]
> > Hello everyone, thank you for the work done. I was just looking for a solution to this problem. Would it be possible to apply this fix also for versions 11 and 12? I have a project with Angular 16, and if I try to install ng-select 13, I encounter compatibility issues.
> > Would you recommend installing ng-select 13 with Angular 16 anyway, or should I fix the problem in another way?
> 
> Forza l'installazione v13, dovresti essere a posto.

By forcing the installation of the latest version 13.2.0, the Angular project does not start. However, when installing the previous version 13.1.1, everything works fine. 
Thank you for your support.
