### ISSUE TITLE
Style issue when styling with custom height

### ISSUE THREAD

**Issue by MilosLbr** [ng-select/ng-select#2369]
**Describe the bug**
Selected option looks a little misaligned when custom height of the dropdown is selected via css rules

**Reproducbile example**
https://stackblitz.com/~/github.com/nemanja010/ng-select-height-example

**To Reproduce** 
I tried to reduce the height of ng-select-container by targeting it with css as seen in the stackblitz example.
When the selected height is small, e.g. less that 25px, and you select something from the dropdown, the selected option looks a bit misaligned and asymmetrical.

**Screenshots**
![image](https://github.com/ng-select/ng-select/assets/30806102/17e242cc-e064-490b-9fca-3baf5d5d3c01)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: Chrome Version 124.0.6367.119 

**Additional context**
I am trying to support the design that has different sizes of the dropdown component for different views.

**Comment by abdallahmmu** [comment]
you can also try to restyle  .ng-select.ng-select-single .ng-select-container .ng-value-container .ng-input,  by make the top to 0px 

I think when the input focused it added some class that made the select or the placeholder go top  you just need to make it 0px 

I hope this helps you let me try if not.

**Comment by MilosLbr** [comment]
> you can also try to restyle .ng-select.ng-select-single .ng-select-container .ng-value-container .ng-input, by make the top to 0px
> 
> I think when the input focused it added some class that made the select or the placeholder go top you just need to make it 0px
> 
> I hope this helps you let me try if not.

Removing the top 5px kinda works for the small dropdown from the example, but it looks misaligned again when you want a bigger dropdown:

![image](https://github.com/ng-select/ng-select/assets/30806102/dcda4690-e2a5-4e6a-b2c2-eb0b2dffc78c)

**Comment by hatsantos** [comment]
Just hit the wall when customizing the height... xD

@MilosLbr did you find a solution?

**Comment by MilosLbr** [comment]
@hatsantos , I don't remember, unfortunately, haven't worked with this component in a while...
