### ISSUE TITLE
feat: dropdownPosition=auto

### ISSUE THREAD

**Issue by mnewmedia** [ng-select/ng-select#237]
I'm Migrating from angularjs to angular 5, there I used [ui-select](https://github.com/angular-ui/ui-select) and they also had this needed feature.

`[dropdownPosition]="'auto'" `

The relevant code part is:
https://github.com/angular-ui/ui-select/blob/master/src/uiSelectDirective.js#L371

and here:
https://github.com/ng-select/ng-select/blob/master/src/ng-select/ng-select.component.ts#L499

**Comment by varnastadeus** [comment]
@mnewmedia this could be good opportunity for you to contribute 😉

**Comment by mnewmedia** [comment]
@varnastadeus I knew you would say that. 🤣 
So here it is. 🎉

**Comment by anjmao** [comment]
@mnewmedia Thanks for contributing, nice job, it works, but there are few issues, added some comments :)
