### ISSUE TITLE
Custom template for each selected item using ng-label-tmp

### ISSUE THREAD

**Issue by ishwar-panchariya** [ng-select/ng-select#2376]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I can't customize the appearance of each selected item in my dropdown menu. Currently, I'm limited to a plain text with image or text with checkbox representation, which doesn't provide enough visual context or interactivity. For example, I want to include images, values, and checkboxes within the dropdown selections to improve user experience and make the selections more informative and engaging.

1. ![image](https://github.com/ng-select/ng-select/assets/66506913/d7777f48-0ca0-4c53-899c-7350eae6258a)
2. ![image](https://github.com/ng-select/ng-select/assets/66506913/71532d4e-4e0c-42e6-aced-9fba16bd7f0a)

**Describe the solution you'd like**
I would like to have the ability to use ng-option-tmp to define custom templates for each selected item in the dropdown. This template should support embedding an image, displaying a specific value (ng-value), and including a checkbox for each item. The custom template should be flexible and easy to define, allowing for a combination of HTML and Angular expressions.

**Describe alternatives you've considered**
It must have input checkbox inside the ng-option-tmp.

**Comment by pavankjadda** [comment]
Not sure if this falls under scope of the project
