### ISSUE TITLE
Select All should only select filtered items

### ISSUE THREAD

**Issue by nook24** [ng-select/ng-select#2391]
### Is your feature request related to a problem? Please describe

The current select all methods do always select **all** options in the select element or all options of a option group.
For example if a user filter the options for `w` the select show the results `Karyn Wright` and `Jodie Bowman`, if you click on select all, all options are selected, not only the two that where displayed. (See gif below)

Examples:
- https://ng-select.github.io/ng-select#/multiselect-checkbox
- https://ng-select.github.io/ng-select#/templates

### Describe the solution you'd like

The select all methods should consider the filter and only select matching options.

As far as i understand the current implementation simply select all options, that are not selected or disabled:

https://github.com/ng-select/ng-select/blob/6714b6535518834034bdf5d4b9a6e26b5049d546/src/ng-select/lib/ng-select.component.ts#L484-L500

The `(click)="toggleItem(item)` call is outside of the scope of optgroupTemplate and can not be overwritten.

To not introduce a breaking change, I think a switch like `selectableGroupWithFilter` to enable/disable this behavior would be good.

### Describe alternatives you've considered

Currently this would only be possible by implementation a custom method for each select in the application.

### Discussed in https://github.com/ng-select/ng-select/discussions/2390

<div type='discussions-op-text'>

<sup>Originally posted by **nook24** May 27, 2024</sup>
When using the "Select all" option for group selections, how can I implement this to only select the filtered options?
For me it does not make any sense so select all options, even if the user has entered a search string.

![2024-05-27 11-17-28](https://github.com/ng-select/ng-select/assets/9019992/376555fd-4cb6-4531-9dfb-4a9de751a8c6)

Many thanks!</div>

**Comment by pavankjadda** [comment]
@nook24 feel free to send PR

**Comment by pavankjadda** [comment]
@nook24 I just checked, we no longer have the issue

**Comment by nook24** [comment]
@pavankjadda thanks for the update.
The linked demo example in my first post still have this issue.

For now I switched to https://github.com/primefaces/primeng as a workaround.
