### ISSUE TITLE
Ability to close or open the drop down only on clicking on arrow icon.

### ISSUE THREAD

**Issue by TejeswaraReddy836** [ng-select/ng-select#2394]
### Is your feature request related to a problem? Please describe

There is user who requested to handle open or close functionality only based on arrow icon in ng select, nothing else should close the dropdown like clicking on outside of dropdown or anywhere on the screen.

### Describe the solution you'd like

Arrow Icon should handle the open close functionality of dropdown.

### Describe alternatives you've considered

I am currently looking for an alternative or a solution for it.

**Comment by mahipureti** [comment]
@TejeswaraReddy836 This is expected behavior and common in all combo boxes or auto completes. See React version of this https://mui.com/material-ui/react-autocomplete/

**Comment by pavankjadda** [comment]
@TejeswaraReddy836 This is expected behavior and common in combo box or auto complete. See React version of this https://mui.com/material-ui/react-autocomplete/
