### ISSUE TITLE
Version 13.0.2 Breaks custom header with input field

### ISSUE THREAD

**Issue by AlbertoMontalesi** [ng-select/ng-select#2395]
### Describe the bug

We have a custom header with an input field inside. With the changes introduced in 13.0.2 a click event causes the dropdown to be closed

### Steps to Reproduce

- create a custom header with `ng-header-tmp`. 
- include an input field inside of the header
- on click inside of the input the `close` event on ng-select is triggered

### Please provide a link to a minimal reproduction of the bug. StackBlitz, CodePen or CodeSanBox

.

### Expected behaviour

Same behavior as version prior to 13.0.2, don't close the header

### What version of the library you see this issue?

13.0.2

### What version of Angular are you using?

Angular 18

**Comment by jpike88** [comment]
false alarm, can close this one
