### ISSUE TITLE
Dropdown-panel is not recalculating its position when removing selected value

### ISSUE THREAD

**Issue by lllen** [ng-select/ng-select#2399]
### Describe the bug

Dropdown-panel is not being set with updated its position(meaning values in styles: top or bottom) when removing values which causes user to see space between selectbox input and dropdown-panel
<img width="550" alt="Screenshot 2024-06-17 at 16 44 49" src="https://github.com/ng-select/ng-select/assets/23261377/6c95a7c2-7692-49a8-8d56-2bb27b6de3c9">

### Steps to Reproduce

1. add param: `appendTo="body"` to `ng-select`
3. open the ng-select and choose a lot values to make at least 2 lines in the input
<img width="552" alt="Screenshot 2024-06-17 at 16 43 12" src="https://github.com/ng-select/ng-select/assets/23261377/05c3c90a-6154-467d-a8f2-677b5f44627c">

4. remove some values to make it 1 line by clicking cross icon on the value itself
<img width="526" alt="Screenshot 2024-06-17 at 16 43 59" src="https://github.com/ng-select/ng-select/assets/23261377/08365e31-6b33-4d71-86dc-ddd01920b8d5">

Actual behaviour:
Dropdown-panel is not being set with updated its position (meaning values in styles: top or bottom) and user see space between selectbox input and dropdown-panel
<img width="550" alt="Screenshot 2024-06-17 at 16 44 49" src="https://github.com/ng-select/ng-select/assets/23261377/6c95a7c2-7692-49a8-8d56-2bb27b6de3c9">

### Please provide a link to a minimal reproduction of the bug. StackBlitz, CodePen or CodeSanBox

https://stackblitz.com/edit/angular-fykrsw?file=src%2Fdata-source-options-example.component.ts

### Expected behaviour

Dropdown-panel position should be recalculated and set. Please notice that the bug is not reproduced when removing values by deselcting value in the dropdown-panel, in this case dropdown-panel position is recalculated correctly.

### What version of the library you see this issue?

13.2.0

### What version of Angular are you using?

Angular 18

### Screenshots

https://github.com/ng-select/ng-select/assets/23261377/8dff2099-17f0-4bb5-89d4-03dc3a394316

**Comment by pavankjadda** [comment]
@lllen Can you try latest version? Works fine for me https://stackblitz.com/edit/angular-1rekot?file=src%2Fdata-source-options-example.component.ts
