### ISSUE TITLE
Instead of ngClass being propagated to dropdown-panel, utilize dropdownClass property

### ISSUE THREAD

**Issue by shyamal890** [ng-select/ng-select#2409]
### Is your feature request related to a problem? Please describe

https://github.com/ng-select/ng-select/pull/2401 propagates `ngClass` to dropdown panel. 

However, `ngClass` is expected to apply class only to the root ng-select component and shouldn't be propagated further.

Infact, if ngClass is propagated to dropdown-panel, there no reason why default classes too shouldn't propagate to dropdown-panel. However, that would be a grave mistake. 

### Describe the solution you'd like

A way to apply class to dropdown-panel is definitely needed. 

A better property name would be  `dropdownClass` which is also a property utilized by ng-bootstrap to apply class specifically to dropdown panel. 

### Describe alternatives you've considered

NA

**Comment by pavankjadda** [comment]
Feel free to create PR for this
