### ISSUE TITLE
ng-option-disabled class should not be used where there are no results

### ISSUE THREAD

**Issue by goldmont** [ng-select/ng-select#2411]
### Is your feature request related to a problem? Please describe

Hi,

I'm unable to style `ng-option` when there are no results. The `ng-option-disabled` class is applied and there is no difference between a disabled option and a warning like "No results found"

### Describe the solution you'd like

Use a class like `ng-option-empty` where there are no results

### Describe alternatives you've considered

Use `ng-option-empty` class in companion with `ng-option-disabled`

**Comment by pavankjadda** [comment]
@goldmont can you send StackBlitz example that shows the current behaviour?
