### ISSUE TITLE
First letter is over-written and value says SA instead of USA

### ISSUE THREAD

**Issue by arun-maddheshia** [ng-select/ng-select#242]
Please fill below information if issuing a bug report. 
### Expected behaviour
Tab into a dropdown,  say a country start typing USA, Press enter again type USA the first letter is overlaped

### Actual behaviour
Tab into a dropdown,  say a country start typing USA, Press enter again type USA the first letter is overlaped/cut

### More Info
ng-select version: Latest

browser: Chrome

reproducible in demo page: [YES]
![1](https://user-images.githubusercontent.com/5073214/35958370-78ee8682-0cc6-11e8-9d54-aa21e650d9a9.png)
![2](https://user-images.githubusercontent.com/5073214/35958371-79b29bee-0cc6-11e8-9b88-e9731236aad3.png)

**Comment by anjmao** [comment]
Hi @arun-maddheshia, that is a good catch!

**Comment by arun-maddheshia** [comment]
@anjmao can we get a quick fix please.

**Comment by anjmao** [comment]
@arun-maddheshia Checkout ng-select 0.20.1 version, it should work as expected now.
