### ISSUE TITLE
Placeholder disappeared on value selection

### ISSUE THREAD

**Issue by sambu004** [ng-select/ng-select#2429]
### Describe the bug

We are using a multi select drop-down for our application which displays a placeholder and minimized on value selection.

We are migrating to Angular 18 for which ng-select needs to be upgraded to 13+ version and after upgrade we noticed that the placeholder is getting removed on value selection.

For our application the placeholder is crucial. Please do look into the issue and provide a solution for displaying the placeholder after value selection.

### Steps to Reproduce

Open a multi select drop-down with placeholder.
Once the panel appears with option for selection, place holder minimized to top left corner.
Now select a value in drop-down.

The place holder disappears.

### Please provide a link to a minimal reproduction of the bug. StackBlitz, CodePen or CodeSanBox

..

### Expected behaviour

On selection of values in drop-down the placeholder should continue to show as minimized text at top left corner.

### What version of the library you see this issue?

13.x.x

### What version of Angular are you using?

Angular 18

**Comment by AbhimanyuShrestha** [comment]
facing the same issue.

**Comment by bajanbentley** [comment]
We noticed this at my company as well, the issue started in 13.6.0.
You can drop down to 13.5.2 for now until a maintainer can fix it.

Here's another ticket that was submitted at the same time.
https://github.com/ng-select/ng-select/issues/2430
