### ISSUE TITLE
notFoundText shouldn't be displayed when loading async data

### ISSUE THREAD

**Issue by shyamal890** [ng-select/ng-select#243]
When `[loading]` flag is set `notFoundText` shouldn't be triggered as the `[items]` array is still waiting to be populated by an async operation.

Example Plunker: https://plnkr.co/edit/XU3qdu?p=preview 

Checkout the first example.

**Comment by anjmao** [comment]
@shyamal890 Thanks for reporting, good catch!

**Comment by anjmao** [comment]
This line here is missing some logic https://github.com/ng-select/ng-select/blob/master/src/ng-select/ng-select.component.ts#L369, need to add check if !isLoading
