### ISSUE TITLE
Bug: Floating label does not persist after selection (Issue started in 13.6.0)

### ISSUE THREAD

**Issue by AllanM246** [ng-select/ng-select#2430]
### Describe the bug

After a selection is made the floating label does not persist

### Steps to Reproduce

Click the drop down and chose an option

### Please provide a link to a minimal reproduction of the bug. StackBlitz, CodePen or CodeSanBox

https://stackblitz.com/~/github.com/AllanM246/ng-select-bug

### Expected behaviour

Floating label should persist after selection.

### What version of the library you see this issue?

13.7.0

### What version of Angular are you using?

Angular 18

### Screenshots

![Screenshot from 2024-08-20 14-06-57](https://github.com/user-attachments/assets/db419325-671b-4512-aab8-28084548b64a)
![Screenshot from 2024-08-20 14-07-18](https://github.com/user-attachments/assets/c8df71ce-9b56-4686-b5a4-690a7b5a5028)

### Desktop? Please complete the following information

Device: Lenovo ThinkPad L15 Gen 
OS: Pop!_OS 22.04 LTS
Browser: Google Chrome
Version 127.0.6533.119 (Official Build) (64-bit)

**Comment by giusliso** [comment]
> ### Describe the bug
> After a selection is made the floating label does not persist
> 
> ### Steps to Reproduce
> Click the drop down and chose an option
> 
> ### Please provide a link to a minimal reproduction of the bug. StackBlitz, CodePen or CodeSanBox
> https://stackblitz.com/~/github.com/AllanM246/ng-select-bug
> 
> ### Expected behaviour
> Floating label should persist after selection.
> 
> ### What version of the library you see this issue?
> 13.7.0
> 
> ### What version of Angular are you using?
> Angular 18
> 
> ### Screenshots
> ![Screenshot from 2024-08-20 14-06-57](https://private-user-images.githubusercontent.com/178934460/360426234-db419325-671b-4512-aab8-28084548b64a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MTgxNTAsIm5iZiI6MTcyNjgxNzg1MCwicGF0aCI6Ii8xNzg5MzQ0NjAvMzYwNDI2MjM0LWRiNDE5MzI1LTY3MWItNDUxMi1hYWI4LTI4MDg0NTQ4YjY0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQwNzM3MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTc1ODY1YTkzMGUwODM0MGI1NGM5YTkxMzdkOGY1ZWI1YTIzZjA1YWY4YzQzY2UwN2I1YWY4N2JmZTEzYjFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dSfd0JTDzugmWzscBAIEnZDMjjtBT-4Zj_p-lMD7BXQ) ![Screenshot from 2024-08-20 14-07-18](https://private-user-images.githubusercontent.com/178934460/360426259-c8df71ce-9b56-4686-b5a4-690a7b5a5028.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MTgxNTAsIm5iZiI6MTcyNjgxNzg1MCwicGF0aCI6Ii8xNzg5MzQ0NjAvMzYwNDI2MjU5LWM4ZGY3MWNlLTliNTYtNDY4Ni1iNWE0LTY5MGE3YjVhNTAyOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQwNzM3MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NWVkZTM0YmM5NTRiNDYzMjFkYzA4NTEyOGVjYzliNTdhZGI2OThhN2ExYjhjZWRiNGE1MmE2YjM1NjhkZDZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.iKO85h4sSmeuPzRwxvv1PKH7r4EBjLEKRIxsF_CGtqs)
> 
> ### Desktop? Please complete the following information
> Device: Lenovo ThinkPad L15 Gen OS: Pop!_OS 22.04 LTS Browser: Google Chrome Version 127.0.6533.119 (Official Build) (64-bit)
> 
> ### Mobile? Please complete the following information
> _No response_
> 
> ### Anything else?
> _No response_

Fixed in 13.8.0 with #2443
