### ISSUE TITLE
After upgrading to Angular 18 i can't type a whitespace character in the input field

### ISSUE THREAD

**Issue by MPruntel** [ng-select/ng-select#2435]
### Describe the bug

After upgrading to Angular 18 i can't type a whitespace character in the input field

Downgrading to Angular 17 solves this problem

### Steps to Reproduce

Upgrade to Angular 18

### Please provide a link to a minimal reproduction of the bug. StackBlitz, CodePen or CodeSanBox

None

### Expected behaviour

Should allow spaces as input

### What version of the library you see this issue?

13.7.1

### What version of Angular are you using?

Angular 18

**Comment by pavankjadda** [comment]
@MPruntel Every bug report needs StackBlitz reproduction. Without this I am unable to help you.

**Comment by pavankjadda** [comment]
@MPruntel Every bug report needs StackBlitz reproduction. Without this I am unable to help you.
