### ISSUE TITLE
Show placeholder even when an item is selected

### ISSUE THREAD

**Issue by keyvanabd** [ng-select/ng-select#2440]
### Is your feature request related to a problem? Please describe

![image](https://github.com/user-attachments/assets/7f5a2866-9854-4c35-8326-5ac0dadb67a9)

I would like the input field to display the placeholder even when an item is selected. Currently, once an item is selected, the placeholder disappears, which can be frustrating in some UI contexts where keeping the placeholder visible provides better user experience.

### Describe the solution you'd like

I would like an option or configuration to allow the placeholder to remain visible, even after an item has been selected from the dropdown. This would give more flexibility in customizing the UI based on specific needs.

### Describe alternatives you've considered

I have considered using custom styles or scripts to manually manage the placeholder visibility, but this approach requires additional work and may not be as clean or maintainable as a built-in option.
Another alternative is showing a label or hint outside the input, but it doesn't solve the issue for those wanting to keep the placeholder inside the input.

**Comment by pavankjadda** [comment]
Closed as part of #2443
