### ISSUE TITLE
Always show items

### ISSUE THREAD

**Issue by anuj9196** [ng-select/ng-select#2444]
### Is your feature request related to a problem? Please describe

In my application, I want the ng-select to work without an input field and behave like a list of checkboxes, showing all options available. This will help in using the ng-select in feedback collection screens.

### Describe the solution you'd like

<img width="362" alt="Screenshot 2024-09-20 at 9 31 46 AM" src="https://github.com/user-attachments/assets/7b41ff27-bc95-4f6c-92d3-ac6e8128f30a">

### Describe alternatives you've considered

I am looping over items and rendering HTML `<input type="checkbox">`  for now.

**Comment by jaydeep28fos** [comment]
+1

**Comment by pavankjadda** [comment]
That is expected behaviour. And checkbox is correct for it.
