### ISSUE TITLE
error with installation

### ISSUE THREAD

**Issue by vicabelotelova** [ng-select/ng-select#245]
I performed the installation and connected the component to my APP module. As a result, there was such an error, what could be the problem? Any additional dependencies? or does it work only with Angular 4+?
i have angular "^2.4.10"
![image](https://user-images.githubusercontent.com/20780164/36027370-1db76bbc-0dac-11e8-8869-ebd64f525d0e.png)

### More Info
ng-select version: ["@ng-select/ng-select": "^0.20.1"]

browser: [google chrome]

**Comment by varnastadeus** [comment]
@vicabelotelova it works from 4.0.0+ version
