### ISSUE TITLE
clearSearchOnAdd so why not clearSearchOnRemove ?

### ISSUE THREAD

**Issue by nicoayci** [ng-select/ng-select#2455]
### Is your feature request related to a problem? Please describe

clearSearchOnAdd is a useful feature indeed but why have the same behaviour when an item is unselected?

### Describe the solution you'd like

add clearSearchOnRemove so that once i found and removed the one item I wanted to remove I can see the full list of items again

### Describe alternatives you've considered

add clearSearchOnChange if we do not want to make a distinction between adding and removing

**Comment by pavankjadda** [comment]
I don't think this is in scope of the project. Feel free to comment if you disagree and explain more.
