### ISSUE TITLE
Typeahead event should be triggered on focus

### ISSUE THREAD

**Issue by shyamal890** [ng-select/ng-select#246]
**Current Behavior:** 
Using async operation to bind items, when the user clicks on the `ng-select` input, `asyc` event isn't triggered.

**Expected Behavior**
It should be triggered on input focus itself. 

**Workaround:** 
`                   (focus)="typeahead.emit()"`

**Comment by anjmao** [comment]
Hi @shyamal890, can tell more about your use case?

**Comment by shyamal890** [comment]
We need to realize users don't really know what typeaheads are. They think its just a dropdown with additional capabilities. Given this backdrop, when a non technical user clicks on the typeahead input he expects it to work as a dropdown. Not seeing any options he believes there's nothing to select here and moves on. Look at the GIF below for example?!

![i](https://user-images.githubusercontent.com/6606965/36036813-d58a2dea-0de0-11e8-92f0-a11b83944508.gif)

This is where prompting with available options is a must.  React Select repo too has attribute `autoload` to load asyc options on load.

**Comment by anjmao** [comment]
You can emit value to typeahead on init or on focus and preload items, this does not look like a workaround. In react select there is autoload because you do not use rxjs, here you have full power and flexibility.

**Comment by shyamal890** [comment]
So `(focus)="typeahead.emit()"` is the way to do that or is there a better alternative?

**Comment by recaihazer** [comment]
`<ng-select [items]="items$ | async"
                   bindLabel="name"
                   [loading]="loading"
                   [typeahead]="itemsInput$"
                   [(ngModel)]="selectedItems">
</ng-select>`

@shyamal890 How could I implement workaround? by adding custom input?
