### ISSUE TITLE
Preventing Alt+Enter from Selecting First Item in Dropdown

### ISSUE THREAD

**Issue by yasmina-s** [ng-select/ng-select#2461]
### Describe the bug

I'm encountering an issue with ng-select where pressing Alt+Enter while the dropdown is open automatically selects the first item in the list. I would like to prevent this behavior to allow Alt+Enter to serve a different function in my application.

Note: I have a HostListener for window:keydown that triggers Alt+Enter to send a request to my backend. This functionality should not be affected by the dropdown behavior.

### Steps to Reproduce

1- Open the dropdown in ng-select.
2- Press Alt+Enter.
3- Observe that the first item is automatically selected.

### Please provide a link to a minimal reproduction of the bug. StackBlitz, CodePen or CodeSanBox

https://stackblitz.com/edit/ng-select?file=app%2Fapp.component.ts

### Expected behaviour

Pressing Alt+Enter should not trigger any selection in the dropdown when it is open.

### What version of the library you see this issue?

10.0.4

### What version of Angular are you using?

Angular 15

**Comment by pavankjadda** [comment]
This is the expected behavior of the library and don't think it is in scope of the project to support niche use cases like this. Feel free to comment if you disagree
