### ISSUE TITLE
Not able to run examples using stackblitz code option

### ISSUE THREAD

**Issue by kishoreandra** [ng-select/ng-select#2463]
### Describe the bug

For e.g. https://ng-select.github.io/ng-select#/multiselect-checkbox when I go to this link and click on stackblitz button to run the code in a sandbox I get errors but nothing

### Steps to Reproduce

Go to any e.g. from docs, https://ng-select.github.io/ng-select#/multiselect-checkbox for sample and click on stackblitz button and run it there (installing deps etc.,)

### Please provide a link to a minimal reproduction of the bug. StackBlitz, CodePen or CodeSanBox

https://angular-b1yrpy.stackblitz.io

### Expected behaviour

Code should run from the sandbox provided 

### What version of the library you see this issue?

13.9.0

### What version of Angular are you using?

Angular 18

### Screenshots

![image](https://github.com/user-attachments/assets/39502b75-6b9e-4c3d-8959-873fd6adb24e)
![image](https://github.com/user-attachments/assets/50c868b3-b382-442f-9cb7-6524c157a5fe)

### Desktop? Please complete the following information

Windows 10
Chrome - latest

**Comment by kratharth-1999** [comment]
Every StackBlitz example seems to show a discrepancy between the selector name in the component decorator and the template name in the app component's decorator.

@pavankjadda I would be happy to take a look into this if you are okay with it and this would be a great first open source contribution for me too

**Comment by pavankjadda** [comment]
> Every StackBlitz example seems to show a discrepancy between the selector name in the component decorator and the template name in the app component's decorator.
> 
> 
> 
> @pavankjadda I would be happy to take a look into this if you are okay with it and this would be a great first open source contribution for me too
> 
> 
> 
> 

Sure

**Comment by pavankjadda** [comment]
Closed in #2464
