### ISSUE TITLE
appendTo="body" causes ng-dropdown-panel to close on mouse up

### ISSUE THREAD

**Issue by jpike88** [ng-select/ng-select#2467]
### Describe the bug

We use `appendTo="body" ` because our ng-select components are in overflow hidden divs. However we have noticed an unpleasant side effect which is causing a major problem on both web and mobile pages.

### Steps to Reproduce

https://ng-select.github.io/ng-select#/append-to-element

Mousedown over either of the last two inputs (it seems like appending to another element, not just the body element has the same problem).
Keeping the mouse down, move the cursor the dropdown then release the mouse click.
The dropdown disappears.

### Please provide a link to a minimal reproduction of the bug. StackBlitz, CodePen or CodeSanBox

https://ng-select.github.io/ng-select#/append-to-element

### Expected behaviour

https://ng-select.github.io/ng-select#/data-sources

On mousedown over an ng-select input, it will open.
Keeping the mouse down, move the cursor to the dropdown then release the mouse click.
The dropdown should stay open.

### What version of the library you see this issue?

13.9.1

### What version of Angular are you using?

Angular 19

### Desktop? Please complete the following information

happens on all platforms and browsers

### Mobile? Please complete the following information

happens on all platforms and browsers

### Anything else?

The problem code path seems to be all in https://github.com/ng-select/ng-select/blob/master/src/ng-select/lib/ng-dropdown-panel.component.ts:

when setting `appendTo='body'`

`_handleOutsideClick` is fired, which then calls `_checkToClose`.

Then in `_checkToClose`, `$event.target` === the body element. 

```
if (this._select.contains($event.target) || this._dropdown.contains($event.target)) {
			return;
		}
```

This code will then always be skipped because the body element is the top level element, nothing can contain it.

Lastly, I also notice that setting `appendTo` then sets `this._parent`, and that is never considered in _checkToClose.

@oliverguenther @pavankjadda this might be related to what https://github.com/ng-select/ng-select/pull/2442 is trying to fix.

**Comment by jpike88** [comment]
closing because it seems work ok on that PR

**Comment by hagerk720** [comment]
it happen with me i used those versions
13.0.0
13.9.1
14.2.0
and i am using angular 19 
i tried to remove` appendTo="body" ` but it still happen 

https://github.com/user-attachments/assets/55a6764c-de13-4a7c-9f4c-7617f4d7993b

**Comment by PhilKoepfer** [comment]
Hi, we had the same problem... When the dropdown needs to open to 'top', it closed directly.. It took us a while to figure out whats happening. It happens when the body is not relative. 

<img width="861" alt="Image" src="https://github.com/user-attachments/assets/536a4449-a9e4-4fbb-9768-fc0bf57ebd13" />
