### ISSUE TITLE
I18n aria-label of ng-dropdown

### ISSUE THREAD

**Issue by V700278** [ng-select/ng-select#2470]
### Is your feature request related to a problem? Please describe

The aria-label of ng-dropdown have a fixe value, aria-label="Options list".

### Describe the solution you'd like

Simply add a variable to change it.
In ng-select.component.ts
`@Input() ariaLabelDropdown: string= 'Options list';`

In ng-select.component.html
`[attr-ariaLabel]="ariaLabelDropdown"`

### Describe alternatives you've considered

None

**Comment by pavankjadda** [comment]
@V700278 care to contribute?
