### ISSUE TITLE
Display value as fallback when multiple=true and element's bindValue not in items

### ISSUE THREAD

**Issue by lchan-computer-talk** [ng-select/ng-select#2471]
### Is your feature request related to a problem? Please describe

For the following Angular example, if the ng-select is
```html
<ng-select
  [items]="myItems"
  [(ngModel)]="mySelection"
  [multiple]="true"
  bindValue="value"
  bindLabel="name">
</ng-select>
```
with
```js
myItems = [
  { name: "Apple", value: "apple" },
  { name: "Orange", value: "orange" },
  { name: "Banana", value: "banana" },
  { name: "Kiwi", value: "kiwi" },
];

mySelection = [
  "apple",
  "watermelon"
];
```
the `apple` value will show up fine as the name `Apple`, but the `watermelon` value will be blank with no label.
![image](https://github.com/user-attachments/assets/97afa2cd-6508-4e4b-bd43-769f67f108ef)

Some reasons the `ngModel` might have extra values would be the `items` being dynamically generated based on configurations that could change, and the additional elements in `ngModel` were set before the configuration was updated to remove it.

Updating the `ngModel` to remove missing elements when the configuration for `items` is updated not an option because the elements should remain of the configuration is reverted.

Filtering out elements from `ngModel` if they are missing from items before displaying is not an option either because the element should be shown as it might be desired to indicate it is there. 

### Describe the solution you'd like

There should be a way to enable displaying the `ngModel` element's value in the multiple select values so it isn't just a blank value.

So adding an attribute like `[multipleValueNoItem]="true"` will have second value display as `watermelon` in the first example
![image](https://github.com/user-attachments/assets/3eca08a2-5a7d-41ec-8e21-82d4ac374253)
or `5` in the second example.
![image](https://github.com/user-attachments/assets/49c65da8-5e20-461b-bbc3-533bc3c26be0)

### Describe alternatives you've considered

I have thought of checking all elements in the `ngModel` and adding them to the `items` if they're missing, but that would lead to the user seeing that as a selection in drop down and be able to select it. This could be resolved by updating `items` by deleting the additional ones when they are removed from the `ngModel`, but that requires keeping track of what is provided and what is new.

Another solution would be removing the `bindValue` and `bindLabel` from the `items`, but then the ability to display something different from element value in `ngModel` would be gone.
```js
myItems = [
  "apple",
  "orange",
  "banana",
  "kiwi",
];
```
![image](https://github.com/user-attachments/assets/9803469d-108b-4f65-9c3a-9b56b3ad8dde)

This is especially an issue when the `items`' value are numbers from an enum, so displaying only the value is not user friendly.

```js
myItems = [
  { name: "Read", value: 1 },
  { name: "Write", value: 2 },
  { name: "Execute", value: 3 },
  { name: "Share", value: 4 },
];

mySelection = [
  1,
  5
];
```
![image](https://github.com/user-attachments/assets/c562cb16-e414-434c-841f-9d584a03bb99)
```js
myItems = [
  1,
  2,
  3,
  4,
];
```
![image](https://github.com/user-attachments/assets/67451fac-aa0d-4bcf-9353-adc2930da1e4)

**Comment by pavankjadda** [comment]
The `mySelection` ngModel should be based on existing set not the other way around. If you disagree, LMK

**Comment by lchan-computer-talk** [comment]
Hi @pavankjadda, I agree that effort should be made by the application to ensure the `mySelection` ngModel only contains values in `myItems` items, either through filtering `mySelection` to be a subset of `myItems` or ensuring that `myItems` have all the possible `mySelection` values.

Looking further into the [ng-select.component.ts](https://github.com/ng-select/ng-select/blob/b6da4d3a187729152f95ce505406df7100ca7372/src/ng-select/lib/ng-select.component.html#L16C1-L25C11), I was able to implement the desired label display with a template as:

```html
<ng-select
  [items]="myItems"
  [(ngModel)]="mySelection"
  [multiple]="true"
  bindValue="value"
  bindLabel="name">
  <ng-template ng-multi-label-tmp let-items="items" let-clear="clear">
    <div *ngFor="let item of items" class="ng-value">
      <span class="ng-value-icon left" (click)="clear(item)" aria-hidden="true">×</span>
      <span class="ng-value-label">{{ item.name || item.value }}</span>
    </div>
  </ng-template>
</ng-select>
```

to achieve my desired display.
![image](https://github.com/user-attachments/assets/cf0a4b0e-a121-4059-bf9a-e420a765945f)

This is an acceptable workaround, but it is quite verbose to add the fallback display and could break if there are changes to the provided classes. Would it be possible to add an fallback to [ng-option.component.ts's label](https://github.com/ng-select/ng-select/blob/b6da4d3a187729152f95ce505406df7100ca7372/src/ng-select/lib/ng-option.component.ts#L31) to accept an override to the empty string?
