### ISSUE TITLE
Resizing cells when using ng-select in a table

### ISSUE THREAD

**Issue by robinlopez** [ng-select/ng-select#2472]
### Describe the bug

When using the ng-select component inside an HTML table (`<table>`), I observe that the table cells (`<td>`) change width depending on the selected value within the ng-select. Setting a fixed width for the column does not resolve the issue.

Upon investigating, I found that this behavior is likely related to the white-space: nowrap; CSS property, specifically within the following CSS in the library:

```
.ng-select.ng-select-single .ng-select-container .ng-value-container,
.ng-select.ng-select-single .ng-select-container .ng-value-container .ng-value {
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}

```

This nowrap style prevents line breaks for the selected value to keep the input height consistent, which is logical, but it appears to cause resizing issues for table cells.

### Steps to Reproduce

1. Place an ng-select component within a table cell (<td>) in an HTML table (<table>).
2. Set a fixed width for the table column (this step is functional and applies the width correctly to the column).
3. Select different values in the ng-select.
4. Observe how the cell width changes according to the selected value, despite the fixed width setting.

### Please provide a link to a minimal reproduction of the bug. StackBlitz, CodePen or CodeSanBox

https://ng-select-kw885d.stackblitz.io/

### Expected behaviour

The table cell width should remain consistent and not vary based on the selected value in ng-select, especially when a fixed width is defined for the column.

### What version of the library you see this issue?

11.2.0

### What version of Angular are you using?

Angular 17, Angular 6

### Screenshots

https://github.com/user-attachments/assets/91a408e5-ef52-480b-b010-b06699f66b88

**Comment by pavankjadda** [comment]
@robinlopez the component expands based on the size. If you don't prefer this, add a parent element like bootstrap md-6 or xl-6 that fixes the size.

**Comment by robinlopez** [comment]
@pavankjadda I am talking about an issue specific to using an ng-select inside a . Even when setting the size of the cell or the width of the ng-select, the problem still persists.
