### ISSUE TITLE
Validate [items] input

### ISSUE THREAD

**Issue by pupizoid** [ng-select/ng-select#248]
Hi again, guys! I've met another strange behavior. For some reasons I need to build several select that represents choice for some classes and their attributes. So, I have two selects and a custom function passed to `[items]` which filters class's attributes (I don't want to show `Object` like attr).

When I select a class, the second select with class attributes is rendered. But when I try to select any attribute - it wont let me do it... Seems that some event is not processed correctly (or I'm doing something completely wrong😅).

I'm using version 0.17.2 and [Plunker](https://plnkr.co/edit/WOvnOuqmpZI6rNBBKJSX?p=preview) with latest version reproduces the same behavior as my app.

Browser: Chorme 63.0.3239.132

**Comment by anjmao** [comment]
Hi @pupizoid , ng-select input does not accept function, you should pass array of objects or use observable with async pipe. Passing function is in general bad for performance because it will be called a lot of times for any async event which triggers change detection. 
We can addd validation to check what is the type of items input to throw error if it is a function.

**Comment by pupizoid** [comment]
@anjmao, now I see... I was really confused because there was no error, so type validation is a good idea. Thanks for the answer!

**Comment by pupizoid** [comment]
@anjmao, well the problem still remains. I've rewritten my code to use component's attr passed to the ng-select instead of function. But I still can't select an item in the second ng-select... 

I've updated [Plunker](https://plnkr.co/edit/LnxLTwbYzLs8FhlkqX9I?p=preview) not to use function

**Comment by anjmao** [comment]
Here is working sample https://plnkr.co/edit/JrhbFzZE6mKjlhTB3PEJ?p=preview
I highly do not recommend to use ngDoCheck if you can perform action on some action change, in this case just add (change)="onCityChange" to first dropdown.

**Comment by pupizoid** [comment]
Wow, i've definitely "shot into my leg"... Thanks for explaining such situation!

**Comment by varnastadeus** [comment]
closing as inactive
