### ISSUE TITLE
Use textarea input with ng-select, allow user to search and select many options and stack them all in a textarea.

### ISSUE THREAD

**Issue by dadoadk** [ng-select/ng-select#2489]
### Is your feature request related to a problem? Please describe

I was not able to find an example to append or change the ng-select component to display as <textarea> type.

### Describe the solution you'd like

Add an input type attribute [type]="textarea" which would render a <textarea> element on the page with all the select options and search features as with type of text.

### Describe alternatives you've considered

The alternative could be appending the ng-select component to an existing <textarea> element on the page.

**Comment by dadoadk** [comment]
Any comments on this issue, is it possible to have a text area element?

**Comment by pavankjadda** [comment]
Sorry, this is out of the scope for the project. Feel free to create a fork and implement

**Comment by dadoadk** [comment]
No problem, thank you.
