### ISSUE TITLE
Dropdown off from screen

### ISSUE THREAD

**Issue by junibrosas** [ng-select/ng-select#256]
Please fill below information if issuing a bug report. 
### Expected behaviour
Dropdown should be displayed inside the screen.

### Actual behaviour
Dropdown is off when user focuses on screen especially if the select component is on the bottom on the screen.

![issue-02-12-2018](https://user-images.githubusercontent.com/1171482/36089552-821421f0-1017-11e8-8ad7-30582542a70d.PNG)

**Comment by anjmao** [comment]
@junibrosas Thanks for reporting. As for now until this is fixed you can use native dom `scrollTop` property to scroll page a bit then this dropdown is opened or you could set position='auto' for dropdown to be set to top if it can't fit the page.

**Comment by anjmao** [comment]
Will be fixed https://github.com/ng-select/ng-select/issues/306
