### ISSUE TITLE
IE wrong positioning of <div class="ng-value">

### ISSUE THREAD

**Issue by korsar1** [ng-select/ng-select#257]
### Expected behaviour
selected value should be shown on the same place as placeholder was. 

### Actual behaviour
If you select an item on IE then selected item is moved up by ng-input, thus you have two rows inside ng-select: one for selected value (which is moved upper with all the spans and also can be cut by ng-value-container) and ng-input is shown in correct place.

### More Info
ng-select version: 0.20.2

browser: IE 10

reproducible in demo page: YES

**Comment by korsar1** [comment]
For me helped setting: 
            >.ng-input {
                top: 0px;
            }

**Comment by varnastadeus** [comment]
This commit should fix this issue. [f94f4e6](https://github.com/ng-select/ng-select/commit/f94f4e6a0225b4a076cf38a5caffde19c1a5c7c3). I have checked on IE11 and it looks fine.
