### ISSUE TITLE
Close select when inside label not working

### ISSUE THREAD

**Issue by MikaStark** [ng-select/ng-select#259]
### Expected behaviour
When you wrap ng-select inside a label, it doesn't close on selection (even if closeOnSelect = true)

### Actual behaviour
You can try it on [your Plunker](https://plnkr.co/edit/NaQ27M?p=preview) if you put a ng-select inside a label (by default it's outside)

### More Info
ng-select version: 0.20.2

browser: Chrome Version 63.0.3239.132 (Build officiel) (64 bits)

reproducible in demo page: YES

**Comment by anjmao** [comment]
@MikaStark Hi, thanks for reporting, it is strange bug. In general I don't know any case there you would like to put component inside label except checkbox input.  If you look at any css framework like bootstrap label contains only text. Solution for now would be to not place it inside label as it is in general good practice.

**Comment by varnastadeus** [comment]
this should be fixed in the latest version.
