### ISSUE TITLE
Mouse interferes with key presses

### ISSUE THREAD

**Issue by andreasfranz** [ng-select/ng-select#260]
### Expected behaviour
It should be possible to navigate through the available item with keyboard key

### Actual behaviour
I created a short [video](https://www.youtube.com/watch?v=AeMOGqV16sc) that shows the issue. The issue only occurs if virtual scroll ist active.

1. Go to the [demo page](https://ng-select.github.io/ng-select#/virtual-scroll) 
2. Open the dropdown and hover an item
3. Use the arrow keys to navigate through the list
4. The list is "stuck" and you cannot move to the end of the list as the mouse forces a scroll back when the key down would actually scroll the list further down

### More Info
ng-select version: 0.20.2

browser: Google Chrome 64.0.3282.140

reproducible in demo page: YES

**Comment by varnastadeus** [comment]
Hi @andreasfranz, I have seen this behaviour before, will check what can be done here.

**Comment by varnastadeus** [comment]
closing in favor of #1167
