### ISSUE TITLE
Request: group by

### ISSUE THREAD

**Issue by maxkorz** [ng-select/ng-select#263]
Hello. Great plugin! Best among the alternatives. I have a request. Can I count on the implementation of the following functionality?

I have a flat list of items I'd like to group them by some property. For example:

List of items:
```js
[
  { name: 'Adam',      email: 'adam@email.com',      age: 12, country: 'United States' },
  { name: 'Amalie',    email: 'amalie@email.com',    age: 12, country: 'Argentina' },
  { name: 'Estefanía', email: 'estefania@email.com', age: 21, country: 'Argentina' },
  { name: 'Adrian',    email: 'adrian@email.com',    age: 21, country: 'Ecuador' },
  { name: 'Wladimir',  email: 'wladimir@email.com',  age: 30, country: 'Ecuador' },
  { name: 'Samantha',  email: 'samantha@email.com',  age: 30, country: 'United States' },
  { name: 'Nicole',    email: 'nicole@email.com',    age: 43, country: 'Colombia' },
  { name: 'Natasha',   email: 'natasha@email.com',   age: 54, country: 'Ecuador' },
  { name: 'Michael',   email: 'michael@email.com',   age: 15, country: 'Colombia' },
  { name: 'Nicolás',   email: 'nicole@email.com',    age: 43, country: 'Colombia' }
]
```

Expected behavior:  http://angular-ui.github.io/ui-select/demo-group-by.html ([plunker](http://plnkr.co/edit/pYkwTkNujo3jnSP5XJNB?p=preview))

This issue https://github.com/ng-select/ng-select/issues/186 suggests having "children" property. My request is a bit different so I created a separate issue.

**Comment by anjmao** [comment]
Hi, @maxkorz. Yes, I started to work on this one.
