### ISSUE TITLE
Aot Error

### ISSUE THREAD

**Issue by mujahidali** [ng-select/ng-select#264]
Please fill below information if issuing a bug report. 
### Expected behaviour
Adding ng-select module causes errors when compiling with -aot

ERROR in (1,1): : Directive NgSelectComponent, Property '_hasValue' is private and only accessible within class 'NgSelectComponent'.
node_modules\@ng-select\ng-select\ng-select.d.ts.NgSelectComponent.html(23,26): : Expected 0 arguments, but got 1.
node_modules\@ng-select\ng-select\ng-select.d.ts.NgSelectComponent.html(24,26): : Expected 0 arguments, but got 1.

### More Info
 angular/animations: ^5.2.3
    angular/common: ^5.2.3
    angular/compiler: ^5.2.3,
    angular/core: ^5.2.3
    angular/forms: ^5.2.3
    angular/http: ^5.2.3
    angular/platform-browser: ^5.2.3
    angular/platform-browser-dynamic: ^5.2.3
    angular/router: ^5.2.3
    ng-select/ng-select: ^0.20.2

Angular CLI: 1.6.6
Node: 9.3.0
OS: win32 x64

**Comment by varnastadeus** [comment]
@mujahidali thanks for reporting, will fix it today.

**Comment by mujahidali** [comment]
@varnastadeus Thank you!

**Comment by mujahidali** [comment]
@varnastadeus  Can you please provide any timeline on an upcoming release that will include this fix. Thanks

**Comment by varnastadeus** [comment]
@mujahidali check new version
