### ISSUE TITLE
Detecting end of available scroll for asynchronous loading 

### ISSUE THREAD

**Issue by LiamDotPro** [ng-select/ng-select#265]
Hello!

We are currently using the same underlying library to implement virtual scrolling in a card view on our application and using the change event and other events given by the scrolling loading up extra elements. As this combo box uses the exact same lib I was expecting we would also have the ability to detect the same changes so we can asynchronously load more elements into the list. Is this a limitation of the current combo box or are we missing something?

Our main reasoning for this is that while it works great on large datasets to large very large sets of data it's crucial that our backend api doesn't send all 50k items straight away but rather in chunks of 100 or so, we also need to figure out serverside filtering but I think that's trivial in comparison. 

Thanks for the great opensource project.

**Comment by anjmao** [comment]
Hi @LiamDotPro, I copy paste code from original angular virtual scroll component, but also removed bunch of not needed code. In original code there is end event https://github.com/rintoj/angular2-virtual-scroll/blob/master/src/virtual-scroll.ts#L375 I can add it back.

**Comment by LiamDotPro** [comment]
@anjmao If you can add it tomorrow that would be splendid thank you!

**Comment by anjmao** [comment]
@LiamDotPro you can see example with loading items in chunk here https://ng-select.github.io/ng-select#/virtual-scroll
