### ISSUE TITLE
Required validation without Reative Forms

### ISSUE THREAD

**Issue by penihel** [ng-select/ng-select#268]
How do a validation without Reative forms. I did not find a demo. I tried this:
```
<ng-select [items]="serverSideFilterItems"
           bindLabel="label"
           bindValue="id"
           required
           (change)="onChange($event)"
           [notFoundText]="'Nenhum resultado encontrado'"
           [typeToSearchText]="'Digite para pesquisar'"
           [typeahead]="itemsTypeahead">
</ng-select>

```

But, dont work it. The validation state never chagnes

**Comment by varnastadeus** [comment]
@penihel it does work, if you inspect element you would see `ng-invalid`. It just doesn't have any class in default bundle so you need to set it yourself.

**Comment by davidoween** [comment]
It happens exactly the same. That same example does not work. the input class is ng-valid

**Comment by varnastadeus** [comment]
@davidoween add plnkr to see what are you doing wrong.

**Comment by dannygoncalves** [comment]
@varnastadeus what happens if you don't wanna add any style but instead display a message? 
Can't access to the error state on ng-select.
