### ISSUE TITLE
appendTo doesn't allow to select multiple items at once

### ISSUE THREAD

**Issue by VShkotin** [ng-select/ng-select#270]
Sorry for my English... but I'll try to explain my issue

<ng-select 
    [items]="items"
    **multiple="true"
    [closeOnSelect]="false"**
    [searchable]="false"
    (close)="onClose()"
    (change)="onFilterChange($event)"
    [(ngModel)]="filterModel"
    **appendTo="body"**
  >

And also I have ng-header-tmp template

And I got this issues - 
1. I can just choose 1 item and then dropdown close;
2. When I click on my header block - dropdown close;

### Expected behaviour
I think I should have ability to select few element, because I add [closeOnSelect]="false" this parameter

### Actual behaviour
Dropdown close every time when I click inside select element

### More Info
ng-select version: 0.20.2

browser: Chrome 64.0.3282.140

**Comment by varnastadeus** [comment]
@VShkotin thanks for reporting, will try to fix it today.

**Comment by VShkotin** [comment]
Hi @varnastadeus ! What about this issue? Have you looked on it?

**Comment by varnastadeus** [comment]
@VShkotin I have the fix. I just need to align with #240 since it depends on that fix.
