### ISSUE TITLE
Detecting  Height

### ISSUE THREAD

**Issue by Kalpesh300** [ng-select/ng-select#272]
This is a question about detecting height of dropdown.
I want the height of dropdown after element is added or removed.
I tried using change, remove and add event.
But problem is it shows previous height of dropdown.
When I add any element I am calling a method  on "change" event. It first call the method and then add element to the list on page. Therefore it shows previous height.
The question is is there anyone way to detect latest height?

**Comment by varnastadeus** [comment]
@Kalpesh300 you can try with timeout, since this events doesn't reflect visual changes
