### ISSUE TITLE
Required attribute is not working

### ISSUE THREAD

**Issue by volkantas** [ng-select/ng-select#277]
### Expected behaviour
Required input is necessary for material and default theme.

### Actual behaviour
User can't set required field. [required]="true" is not working.

### More Info
ng-select version: 0.21.0

browser: Mac OS, Chrome

**Comment by varnastadeus** [comment]
@volkantas it works,  just your custom styling https://github.com/ng-select/ng-select#validation-state

**Comment by KiranRachumalla** [comment]
I am getting an error I get when i try to conditionally apply required attribute on ng-select. This is what I used [required]="locationRequired".

Error: Template parse errors:
Can't bind to 'required' since it isn't a known property of 'ng-select'

**Comment by zevlio** [comment]
Indeed, it seems we cannot bind to required on ng-select. So a workaround is to use *ngIf. Not pretty but it works:
`
<div *ngIf="locationRequired">
    <ng-select [items]="locations" required></ng-select>
</div>
<div *ngIf="!locationRequired">
    <ng-select [items]="locations"></ng-select>
</div>
`

**Comment by majedur-rahaman** [comment]
There is no build-in `required` attribute in `ng-select`. I always validate it through form validation.
In angular2 or above you can use `ng-select` with `ngNativeValidate `directive for template driven form.

```
<form #registerUser="ngForm" ngNativeValidate (ngSubmit)="onSubmit()">  

   <ng-select
    class="col-md-8 required"
    [items]="options" 
    bindLabel="label" 
    bindValue="value"
    [multiple]="true" 
    name="skills"
    placeholder="Select Skills" 
    [(ngModel)]="registerUserData.skills"                                       
    required>
</ng-select>
<div *ngIf="!registerUserData.skills" class="invalid-feedback">
    Skills are required
</div>

<button type='submit' [disabled]="!registerUser.valid" [isFormValid]="!registerUser.valid">Submit</button>

</form>
```
I am also using custom style to red mark field when `untouched `or `touched `and `invalid`. You can put it in global `scss `or `css `file to work as same all `component`.

> SCSS:

```
ng-select.required.ng-invalid.ng-touched {
    .ng-select-container{
        border-color: #dc3545;
        box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 0 3px #fde6e8;
    }
}
ng-select.required.ng-invalid.ng-untouched {
    .ng-select-container{
        border-color: #dc3545;
        box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 0 3px #fde6e8;
    }
}
```

> CSS:

```
ng-select.required.ng-invalid.ng-touched .ng-select-container{
 
    border-color: #dc3545;
    box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 0 3px #fde6e8;
}
ng-select.required.ng-invalid.ng-untouched .ng-select-container {

    border-color: #dc3545;
    box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 0 3px #fde6e8;
}
```

**Comment by Tomal991** [comment]
Is there any other way of doing the required validation other than @majedur-rahaman answer.I desperately need this issue solved.Anyone?

**Comment by ramanachari** [comment]
> box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 0 3px #fde6e8;
this CSS is always showing to the form field even though didn't click on the submit button
