### ISSUE TITLE
Search not selecting option when a previous option was selected

### ISSUE THREAD

**Issue by FritzHerbers** [ng-select/ng-select#278]
### Expected behaviour
When an option was selected before, a new search should be capable to automatically select a searched option, so that only ENTER needs to be pressed (not going down in the list and select an option with the mouse or ENTER).

### Actual behaviour
https://plnkr.co/edit/PUeANT?p=preview
Reproducing the Issue and explanation can be found in the Plunker.

### More Info
0.21.0

**Comment by varnastadeus** [comment]
@FritzHerbers thanks for plnkr and good explanation. In this case, when ABC is entered, ABC option should be marked and pressing enter should be enough to select it.

**Comment by FritzHerbers** [comment]
When implementing the fix, beware that when the user escapes the search, the previously selected option should be chosen/still be valid.
