### ISSUE TITLE
Feature Request: expose this._focusSearchInput();

### ISSUE THREAD

**Issue by marvinosswald** [ng-select/ng-select#279]
Please fill below information if issuing a bug report. 
### Expected behaviour
Make select focusable from outside with an input on [focus]

basically expose this._focusSearchInput(); through that input

### Actual behaviour
not implemented

### More Info
ng-select version: [INSERT HERE]

browser: [INSERT BROWSER INFO HERE]

reproducible in demo page: [YES/NO]

**Comment by varnastadeus** [comment]
@marvinosswald can you add use case for it?

**Comment by marvinosswald** [comment]
i have ng-select embeded in a modal so i want it to be focused when i open the modal

**Comment by anjmao** [comment]
@marvinosswald It is public now https://github.com/ng-select/ng-select/blob/master/src/ng-select/ng-select.component.ts#L410:5
