### ISSUE TITLE
Searchable server side tags clears ngmodel on search

### ISSUE THREAD

**Issue by asadaries** [ng-select/ng-select#282]
Please fill below information if issuing a bug report. 
### Expected behaviour
My old selected values should have been retained in select area

### Actual behaviour
Tags are loaded from server side, using code from examples. I search for tag select some. Then i research it clear my model values.

**Comment by asadaries** [comment]
searchInit() {
        this
            .checklistSearchEvent
            .pipe(distinctUntilChanged(), debounceTime(500), switchMap(term => this.checklistService.getAll(this.state.params.tenantId, {
                PageNumber: 1,
                PageSize: 50,
                SearchTerm: term
            })))
            .subscribe(x => {
                this
                    .cd
                    .markForCheck();
                // tried this 
                //this.checklists.Data = [...x.Data];
               // same issue with this as well
                this.checklists = x;
            }, (err : Error) => {
                this
                    .tostr
                    .error(err.Message);
            });
} // Sample code i am using

**Comment by varnastadeus** [comment]
@asadaries you are probably overriding `ng-model` on load. Just do everything like in https://github.com/ng-select/ng-select#flexible-autocomplete

**Comment by learning-angular-project** [comment]
@asadaries Have you find a solution to get it working. I've the same probleme my ng-model values are cleared

**Comment by varnastadeus** [comment]
@learning-angular-project thanks for plunker, I will check it out.

**Comment by anjmao** [comment]
Probably this line causing this issue https://github.com/ng-select/ng-select/blob/master/src/ng-select/ng-select.component.ts#L415. Will try to remove it.

**Comment by asadaries** [comment]
@varnastadeus Yup, i identified the same issue i-e bindValue clears ngModel. I opted to not provide any explicit bindValue options.

**Comment by anjmao** [comment]
I'm working on a fix for this.
