### ISSUE TITLE
Appending to body doesn't align the dropdown correctly.

### ISSUE THREAD

**Issue by adamk33n3r** [ng-select/ng-select#283]
When appending to body, the dropdown isn't aligned correctly.
### Expected behaviour
Dropdown lines up correctly

### Actual behaviour
The dropdown position is shifted. It seems to depend on `<body>` and other elements at the start of the doc to not have any margins. It is positioned `8px` off in both x and y due to the `<body>` margins. If the first element in `<body>` is an `<h1>`, which has top and bottom margin of `21.44px`, the dropdown is positioned `21.44px` too high.

Here is an example of the issue on [StackBlitz](https://stackblitz.com/edit/ng-select-appendtobody-bug?file=app/app.component.html)

### More Info
ng-select version: 0.21.0

browser: chrome, firefox

**Comment by varnastadeus** [comment]
@adamk33n3r for now simplest solution would be to set body `position: relative`

**Comment by adamk33n3r** [comment]
Interesting! I wouldn't have thought that could "fix" it.

**Comment by anjmao** [comment]
@varnastadeus As we talked, you can update readme add add a note that appenTo element should be relative to work correctly.

**Comment by varnastadeus** [comment]
We decided to keep `position: relative` as solution since it works in all cases and doesn't have any implications on codebase. Other solution would require traversing dom to get right offset which seems like overkill considering `body` usually doesn't have any margins.
