### ISSUE TITLE
Transparent backgorund

### ISSUE THREAD

**Issue by akhilsahu** [ng-select/ng-select#285]
Please fill below information if issuing a bug report. 
### Expected behaviour
No transparent background and there's issue in with chrome autofill
 
 

browser:  Chrome

 Tried disabling autofill and also tried adding css nothing works

Following `css`

`.ng-select.custom {
    border:0px;
    min-height: 0px;
    border-radius: 0;background-color: teal;
}
.ng-select.custom .ng-control  {            
    min-height: 0px;
    border-radius: 0;background-color: teal;
}
 ng-select  ng-option  {            
    min-height: 0px;
    border-radius: 0;background-color: teal;
}
.ng-select-dropdown-outer {
    background-color: teal;
}
.custom ng-template {
	background-color: teal;
}`

**Comment by jorgelub12** [comment]
I have the same problem when I see the component from phone

**Comment by varnastadeus** [comment]
@akhilsahu I don't see how it doesn't works.. https://plnkr.co/edit/OMdlT4RpJV4DlDMd7gTN?p=preview
