### ISSUE TITLE
[Typeahead] reset item list on input blur

### ISSUE THREAD

**Issue by aitboudad** [ng-select/ng-select#288]
### Actual behaviour
![ng-select-typeahead](https://user-images.githubusercontent.com/1753742/36643009-2b08e266-1a3e-11e8-87a6-64f190be5de6.gif)

### More Info

reproducible in demo page: YES

https://ng-select.github.io/ng-select#/filter

**Comment by varnastadeus** [comment]
@aitboudad I don't see issue here. Typeahead usually is used to get data from backend so you see what you load. If you are using typeahead for custom search then you have to handle all filtering cases yourself. I updated demo for this case.
