### ISSUE TITLE
Add dynamic items heights support

### ISSUE THREAD

**Issue by anjmao** [ng-select/ng-select#291]
Currently virtual scroll is not supporting items with dynamic height. If dynamic height is used scroll is not working correct. This happens because we need to know total scroll height and each item height in order to scroll to selected item. 

- [x] Make virtual scroll disabled by default. This will allow to scroll to selected items with disabled virtual scroll. (Easy to implement because all items are rendered in the DOM)
- [ ] Investigate possible solutions for dynamic heights (Virtual DOM, [react virtualized](https://github.com/bvaughn/react-virtualized))

**Comment by djmarquette** [comment]
Is there going to be any follow up on this issue?  We have similar issue with virtual-scroll being needed, and the labels being quite long and needing CSS to wrap them.  When we wrap, the scroll exhibits a lot of "jankiness" and is not usable.  We've had to remove wrapping, and lose some visibility of our list items.
