### ISSUE TITLE
Feature Request: Click event for tags

### ISSUE THREAD

**Issue by shyamal890** [ng-select/ng-select#292]
How to run a function on tag click?

Tried `let-` on `ng-template` didn't work: https://plnkr.co/edit/aqM7LN?p=preview

**Comment by varnastadeus** [comment]
@shyamal890 you don't need to assign click using `let`, just use `(click)` on div.

**Comment by shyamal890** [comment]
Need to pass function from parent though.

**Comment by shyamal890** [comment]
1.
