### ISSUE TITLE
Set width with appendTo body

### ISSUE THREAD

**Issue by ksamborn** [ng-select/ng-select#293]
Hi - 

Is it possible to specify the width of the dropdown with appendTo?  This is independent of the selection box.

From this code, I think the answer is "no", but I decided to ask if there is some workaround:

```
  private _updateDropdownPosition() {
        const parent = document.querySelector(this.appendTo) || document.body;
        const selectRect: ClientRect = this._selectElementRef.nativeElement.getBoundingClientRect();
        const dropdownPanel: HTMLElement = this._elementRef.nativeElement;
        const boundingRect = parent.getBoundingClientRect();
        const offsetTop = selectRect.top - boundingRect.top;
        const offsetLeft = selectRect.left - boundingRect.left;
        const topDelta = this.currentPosition === 'bottom' ? selectRect.height : -dropdownPanel.clientHeight;
        dropdownPanel.style.top = offsetTop + topDelta + 'px';
        dropdownPanel.style.bottom = 'auto';
        dropdownPanel.style.left = offsetLeft + 'px';
        dropdownPanel.style.width = selectRect.width + 'px';
    }

```

thanks, 
Kevin

**Comment by varnastadeus** [comment]
Hi @ksamborn, why not use css?

**Comment by ksamborn** [comment]
Thanks, @varnastadeus, but does CSS work here?   doesn't the _updateDropdownPosition use inline styles to overwrite the CSS?   

I understand I can use !important, but will the rest of the calculations will interfere?

Sorry if I'm missing something.  

Thanks for your help!

Kevin

**Comment by varnastadeus** [comment]
@ksamborn yes, you can use !important and it should work, tested my self.

**Comment by ksamborn** [comment]
OK, @varnastadeus, I will try it.   thanks
