### ISSUE TITLE
Support for angular [compareWith]

### ISSUE THREAD

**Issue by Kevin2iBi** [ng-select/ng-select#294]
Please fill below information if issuing a bug report. 
### Expected behaviour
Describe how you think it should work

### Actual behaviour
Describe how it actually works or create example using [Plunker](https://plnkr.co/edit/hjZX6W?p=preview) issue template

### More Info
ng-select version: [INSERT HERE]

browser: [INSERT BROWSER INFO HERE]

reproducible in demo page: [YES/NO]

**Comment by varnastadeus** [comment]
@Kevin2iBi why do you need this? Can you add use case?

**Comment by Kevin2iBi** [comment]
I wanted this in case you may already have an element selected in the selection field from a value set in the form controls but fortunately your component already has this functionality. thank you so much

**Comment by anjmao** [comment]
@Kevin2iBi glad it works, closing this.
