### ISSUE TITLE
Placeholder is visible with selected value

### ISSUE THREAD

**Issue by anjmao** [ng-select/ng-select#297]
### Expected behaviour
Placeholder should not be visible if selected value is set

### Actual behaviour
Placeholder is visible
![image](https://user-images.githubusercontent.com/3028012/36739122-dbed641c-1be7-11e8-9f8f-3eb622d2ed97.png)

reproducible in demo page: [YES]

**Comment by anjmao** [comment]
possible bug in angular https://github.com/angular/angular/issues/22560

**Comment by monis001** [comment]
Hi, 
any update on this or any workaround, facing the same issue 
Thanks

**Comment by MEChasle** [comment]
Issue still here in `5.0.9`.
Any updates ?

**Comment by Saqib92** [comment]
Adding following in `style.scss` fixed it. 
@import "~@ng-select/ng-select/themes/default.theme.css";

**Comment by ManikandanManohar** [comment]
> Adding following in `style.scss` fixed it. @import "~@ng-select/ng-select/themes/default.theme.css";
 its  Working...Super Dude
