### ISSUE TITLE
Request to Improvement Auto Fill(Auto select if single option)

### ISSUE THREAD

**Issue by SunilKumar5** [ng-select/ng-select#298]
Please fill below information if issuing a bug report. 
### Expected behaviour
After filtering the options based on input values. If only one option is left it should auto select the option.

### Actual behaviour
Right now the user has to click enter to make the option selected even there is a single option.

### More Info
This might not be a default functionality but can be added as a feature by setting a Boolean parameter
ng-select version: 0.23.1

browser: chrome

reproducible in demo page: Not Applicable

**Comment by varnastadeus** [comment]
@SunilKumar5 why item should be selected? Usually when you search, you don't know what you looking for, so selecting item sounds very confusing and unintuitive. I don't see much value in this feature and I doubt that we will support it. What do you think @anjmao?

Anyway you could achieve this with `typeahead` custom search, just set your `NgModel` with the value left after filtering.

**Comment by SunilKumar5** [comment]
@varnastadeus Thanks for your suggestion. I was able to figure out when only one option is left and I'm assigning the value to the NgModel. I'm having trouble in making the NgModel value as selected value and close the dropdown after it is assigned, on the DOM side. Can you please give any suggestions on how this can be achieved.

**Comment by varnastadeus** [comment]
@SunilKumar5 you could get `select` using `@VIewChild` and call `close` method on it.

**Comment by SunilKumar5** [comment]
@varnastadeus Thanks, that worked.

**Comment by paulng93** [comment]
@SunilKumar5 could you provide a code snippet/example of your solution? I have the same problem
