### ISSUE TITLE
valueKey: By default binds to whole object

### ISSUE THREAD

**Issue by sebaranowski** [ng-select/ng-select#30]
Not sure why but when I use the package via `npm install` inside my application and try your example from the demo `select-bindings.component.ts`:

```
<label>Bind model to object</label>
        <ng-select [items]="cities"
                   labelKey="name"
                   placeholder="Select value"
                   [clearable]="false"
                   [(ngModel)]="selectedCity">
        </ng-select>
```
I have to add `valueKey="this"` to get the same result as in the demo. I guess this was the behavior prior d976c37cb3397d45d853459da31ddc6af2ab7cf6 ? This is really weird since I checked the version number in my project (`node_modules/@ng-select/ng-select/package.json`) and it matched `0.0.5`.

**Comment by sebaranowski** [comment]
Oh, I see the 0.0.5 is 5a2a94f.. npm registers the tagged versions I guess? So better use another branch like `develop` if master docs differ from tagged/npm-registered version... please ack and close :)

**Comment by anjmao** [comment]
@sebaranowski Thanks for report. Released new version with updated documentation :)
