### ISSUE TITLE
It's a bloatware - the size is too big for a single component - 208KB gzipped / minified

### ISSUE THREAD

**Issue by fssrepository** [ng-select/ng-select#300]
![image](https://user-images.githubusercontent.com/33239584/36746347-6b13e918-1bf2-11e8-940c-54462406d47f.png)

I generated released map files with ionic:
./node_modules/@ionic/app-scripts/bin/ionic-app-scripts.js build --prod --generateSourceMap true
and checked
source-map-explorer main.js{,.map}

It's a luxury that a select cost 200KB. I have reimplemented ionic, and every component of mine cost 150KB. I hate node libraries it's just a waste of time.

To be able to send a service message with firebase it cost 600KB. If you use the select on a webpage, it's not feasible.

I had problems with the ngModel on select multiple, now i need to implement. My experience is on all node libraries, to reimplement it's easier and faster method, instead of fixing bugs, or looking for performance issues.

That's why i'm pretty soon deprecating the whole ionic.

**Comment by anjmao** [comment]
Hi @fssrepository, last time I checked it was only 45kb minified, will check this as soon as possible, it looks some rxjs operators may take a lot of size.

**Comment by anjmao** [comment]
I can confirm that one recent feature caused this problem.

**Comment by anjmao** [comment]
@fssrepository Checkout new version. Now it is only 15KB gzipped.
```
-rw-r--r--  1  staff    15K Feb 28 09:41 ng-select.umd.js.gz
-rw-r--r--  1  staff  140K Feb 28 09:41 ng-select.umd.js.map
-rw-r--r--  1  staff    46K Feb 28 09:41 ng-select.umd.min.js
-rw-r--r--  1  staff  128K Feb 28 09:41 ng-select.umd.min.js.map
```

**Comment by fssrepository** [comment]
Yes, the first thing what i replaced in my framework was the rxjs. Thanks for your response.
