### ISSUE TITLE
How to set the active item on load?

### ISSUE THREAD

**Issue by tosehee75** [ng-select/ng-select#301]
Thanks for the great components. I was using the valor's ng-select, but surprised by this component's features, decided to move onto this.

One of the key feature that I need to figure out is how to set the default active items.

I looked through the code and examples, but can't figure out how to do that.

In short, I need to load the items in <ng-select>, but also pre-select the active item(s) as needed.

How can I do this?

**Comment by tosehee75** [comment]
Okay.

Just played with it more and figured out that I can use "ngModel" for it. How does it work in multiple selection?

Do I use the ngModel with object type of any []? or ?

**Comment by varnastadeus** [comment]
@tosehee75 for multiple just set your `ngModel` with `any[]`. There are plenty examples, why do you need to create issues?
