### ISSUE TITLE
Reset after selection

### ISSUE THREAD

**Issue by ksamborn** [ng-select/ng-select#302]
Hi - is it possible to set the ngModel to null within the (change) event?

Here is a plunker - https://plnkr.co/edit/4vVcBF?p=preview

Basically, we want the behavior of the "Pick & clear" - after the user has chosen an item, we make some changes elsewhere on the screen and we want to "reset" the model by setting it to null.

For some reason, this works only on the first time.   The second time, last last selected value appears in the ng-select.  You can reproduce this by picking an item from the dropdown (ie. Vilnius) and then picking it again (ie. Vilnius).  The name of the city still appears in select box, even though we set the model to null.  (The "resetable" version implements the behavior we want, but we don't want a separate button.)

I suspect the issue is that the ng-select's ControlValueAccessor is not called the second time.  I put a breakpoint in writeValue() and it was never called.   Any ideas?

Thanks,
Kevin

**Comment by anjmao** [comment]
Hi @ksamborn This is interesting. If I add timeout then it works.

```ts
private change($event): void {
      this.pickedCity = $event;
      setTimeout(() => {
        this.selectedCity = null;
      })
    }
```

**Comment by ksamborn** [comment]
Thanks @anjmao, I figured that out from SO, specifically this one: https://stackoverflow.com/a/43339577

But something still seems very weird, and I don't know why it isn't working.   I updated the Plunker 

In our application, we are in fact using ngModel and ngModelChange, the latter with a setTimeout, like this:

```
	private change(value: any): void {
		this.selectedItem = value;

		if (value) {
			this.select.emit(value);

			if (this.clearOnSelect) {
				setTimeout(() => this.selectedItem = null);
			}
		}
	}
```

And, it seems to work for us, although it doesn't in the Plunker.

As far as I can see, we are just doing a transformation on the new value coming through the ngModelChange.   What really bothers me is that the standard Angular documentation does something very similar - they transform the value to upper case: 

https://angular.io/guide/template-syntax#ngmodel---two-way-binding-to-form-elements-with-ngmodel

So I don't know why I need the setTimeout().

It's almost like the parent's version of the model is kept in sync with ngModelChange, but that doesn't necessarily transfer down to the child through writeValue()

**Comment by anjmao** [comment]
@ksamborn 

1) You select value in ng-select
2) ng-select use onChange() to notify your ngModel and update with selected value
3) At the same time ng-select also fires change event
4) You are subscribing to change event and setting ngModel back to null
5) All that happens on the same change detection cycle
6) By using setTimeout you are forcing to execute your code on next check detection cycle

Home this helps.

**Comment by ksamborn** [comment]
OK, I guess it works so I can live with it.  Thanks, @anjmao

**Comment by xxis** [comment]
i understand this question is closed, but is this functionality something being worked on. i am very interested in this. i am using the autocomplete as a navigation 'jump to' function and its not ideal that it doesn't have a clear on set option.

**Comment by Saqib92** [comment]
Any Update on this issue?

**Comment by GillesVercammen** [comment]
I need this exact same behaviour in an application i'm working on, i'd rather avoid using setTimeout if possible.
Is there any other solution to this problem  as of yet?

**Comment by sdfreeland** [comment]
I had a similar need and got around it by using setting [multiple]="true" and [clearSearchOnAdd]="true" even though I'm using it as a single selection input.  It has the visual effect as selecting a single item and clearing it.  For the ngModel binding I used just a dummy array of null data.  Then on the change you can get what item was selected because it will be the first item in the array and then instantly clear the dummy array.  
On the ng-select:
`(change)="dataChange($event)" [multiple]="true" [clearSearchOnAdd]="true"  [(ngModel)]="dummyData"`

```
dataChange(selectedOption)
{
    //whatever you want to do with the selectedOption[0]
    this.dummyData = [];
}
```
