### ISSUE TITLE
Dropdown doesnt open upwards if no space

### ISSUE THREAD

**Issue by Gillardo** [ng-select/ng-select#306]
You can replicate this on the plunkr demo, if you go to the dropdown at the end of the page, where there is not enough room for the dropdown to appear, i think the dropdown list should open upwards.  This is how a native dropdown would work.

Is this possible?  It is an extra setting that isnt applied to the plunkr demo?  I think it should do this automatically

**Comment by varnastadeus** [comment]
Check out the API section

**Comment by anjmao** [comment]
Currently default dropdown position is set to bottom, it make sense to change it to `auto`.

**Comment by Gillardo** [comment]
Thanks for reply.  I think auto should be default. great component btw!

**Comment by anjmao** [comment]
Includes https://github.com/ng-select/ng-select/issues/367
