### ISSUE TITLE
Not opening when called

### ISSUE THREAD

**Issue by Gillardo** [ng-select/ng-select#307]
Please fill below information if issuing a bug report. 
### Expected behaviour
I want to reopen the select component once a value is selected.  To do this i use the (change) event to reopen the component

### Actual behaviour
The dropdown items do now appear, although the arrow seems to change like it is open.  If you click anywhere on the page, you see the list for a brief moment and then it disappears. Plunkr below demonstrates

https://plnkr.co/edit/fnMHFl?p=preview

### More Info
ng-select version: Latest version, downloaded today via npm: 0.23.2

browser: Google Chrome

reproducible in demo page: [YES/NO] - Do not think there is an example

**Comment by varnastadeus** [comment]
@Gillardo why you are doing this? There is `[closeOnSelect]` input property.

**Comment by anjmao** [comment]
@Gillardo Thanks for reporting, there is indeed a bug for open() method, fix is simply, will be fixed in https://github.com/ng-select/ng-select/pull/299

**Comment by Gillardo** [comment]
Sorry didn't think about using closeOnSelect. I am porting over from a different ngSelect component and this was the way it had to be done.  I will try this instead. Glad I found a bug though 😁

**Comment by Gillardo** [comment]
Thanks for the tip about [closeOnSelect].  Instead of using open, i have used [closeOnSelect]="false" and then called close() when i needed the dropdown closed.

**Comment by anjmao** [comment]
`open` method fixed with https://github.com/ng-select/ng-select/commit/ea6b636efe6bc7ee96d50fdfa4b809ed3d529069
