### ISSUE TITLE
Clicking outside dropdown does not revert

### ISSUE THREAD

**Issue by ksamborn** [ng-select/ng-select#308]
Please fill below information if issuing a bug report. 
### Expected behaviour
Clicking outside the dropdown should revert to the previous selected item.   This should be the same as hitting "Escape"

this is the behavior in 0.22.0

### Actual behaviour
In 0.23.2, clicking outside the dropdown leaves the entered text as the selected text.

For example, if you go to the Data Sources demo, and start typing (ie. "Roch" or "jwef") the dropdown will change appropriately.   If you click outside the dropdown, the entered text remains.   If you try the same thing and hit "Escape", the value and text reverts to the previous vale

### More Info
ng-select version: 0.23.2

browser: Chrome - Version 64.0.3282.167 (Official Build) (64-bit)

reproducible in demo page: YES

**Comment by varnastadeus** [comment]
#299 this PR has the fix, thanks for reporting.

**Comment by anjmao** [comment]
@ksamborn 0.24.0 version is pushed to npm with this fix

**Comment by ksamborn** [comment]
@anjmao @varnastadeus thanks
