### ISSUE TITLE
typeahead stop workin after an error

### ISSUE THREAD

**Issue by learning-angular-project** [ng-select/ng-select#310]
Please fill below information if issuing a bug report. 
### Expected behaviour
When I use the autocomplete with typeahead and I get a 400 error from ther server I should be able to enter new data in the select field

### Actual behaviour
After a 400 error when I enter data in the select field no more request are triggered to the server

### More Info
ng-select version:0.23.2

browser: firefox 58.0.2

reproducible in demo page: [YES/NO]

**Comment by anjmao** [comment]
See https://github.com/ng-select/ng-select/issues/311
