### ISSUE TITLE
loading icon still present

### ISSUE THREAD

**Issue by learning-angular-project** [ng-select/ng-select#311]
### Expected behaviour
When I use the autocomplete with typeahead and I remove rapidlly the data ine the select box the loader is still present even if the select has no more focus

### Actual behaviour
The loader should not display

### More Info
ng-select version: 0.23.2

browser: firefox 58.0.2

reproducible in demo page: YES
https://plnkr.co/edit/KFpvA9?p=preview

**Comment by anjmao** [comment]
Hi @learning-angular-project Thanks for reporting. It is also related to https://github.com/ng-select/ng-select/issues/310
