### ISSUE TITLE
Multiple Dropdowns:Click on 2nd Dropdown does not open it as the first Dropdown was open

### ISSUE THREAD

**Issue by SunilKumar5** [ng-select/ng-select#313]
Please fill below information if issuing a bug report. 
### Expected behaviour
When there are multiple drodpdowns on the same screen. First click on a dropdown opens options and clicking directly on other dropdown should have opened the second dropdown.

### Actual behaviour
Now First click on a dropdown opens options and clicking directly on other dropdown closes the first dropdown options but does not open second dropdown options.
This can be found in the demo app also.

### More Info
ng-select version: [0.24.0]

browser: [Chrome 64]

reproducible in demo page: [YES]

**Comment by anjmao** [comment]
Hi @SunilKumar5 ,
We added technique like in angular material which adds overlay on whole page. This allows to easily close dropdown by clicking on overlay, so you don't need to listen to global document click events, but in your case it requires extra click. It is still working fine when using tabs navigation. I will keep this open for now and investigate possible solutions.

**Comment by anjmao** [comment]
https://github.com/angular/material2/issues/10232

**Comment by varnastadeus** [comment]
@anjmao @SunilKumar5 native html select works this way so I am perfectly fine with this behaviour.

**Comment by anjmao** [comment]
@varnastadeus If native html sucks it doesn't mean what we also should.

**Comment by anjmao** [comment]
I looked at some popular select components and they all handle dropdown closing without overlay. Will need to fix this behaviour.
