### ISSUE TITLE
addTag adds an object not a string?

### ISSUE THREAD

**Issue by LeahPike** [ng-select/ng-select#315]
### Expected behaviour
I'm binding to a list of string, when I enable addTag and add a new value ( Purple )  it should add just a string to the array.
> [ "Red", "Green", "Blue", "Purple", "Yellow" ]

### Actual behaviour
It's adding an object to the array.
> [ "Red", "Green", "Blue", { "label": "Purple" }, "Yellow" ]

### More Info
If I add an existing tag ( Yellow ), it just adds the string.
```
    onAdd(value) {
        console.log(value);
    }
```
> {label: "Purple"}
> Yellow

ng-select version: 0.23.3

browser: Chrome Version 64.0.3282.186 (Official Build) (64-bit)

reproducible in demo page:  N/A

**Comment by varnastadeus** [comment]
@LeahPike you are probably using `bindLabel` which is not necessary since you have simple strings and `tagging` creates same object to match it after creation.

**Comment by LeahPike** [comment]
I tried not setting the bindLabel at all, or setting it to empty, but it was persistent about wanting to add new tags as an object with a label property.

**Comment by varnastadeus** [comment]
ok, I can confirm it is a bug.

**Comment by LeahPike** [comment]
Thank you :)
