### ISSUE TITLE
click event on ng-option triggering click event on ng-control?

### ISSUE THREAD

**Issue by SunilKumar5** [ng-select/ng-select#316]
Hi,
Really appreciate your help. when i click on an option the value is selected and the drop-down is still open. When I debugged, I found out that the click on ng-option works fine but the click event on ng-control is getting triggered with the same click. Can you please help me in understanding what might be the reasons for this?

### More Info
ng-select version: [0.24.0]

browser: [chrome]

reproducible in demo page: [NO]

**Comment by anjmao** [comment]
Hi @SunilKumar5,
In order to help you I would ask to create reproducible sample using simple plunker template https://plnkr.co/edit/hjZX6W?p=preview

Thanks.

**Comment by anjmao** [comment]
@SunilKumar5 Closing this. Feel free to create new issue if you still have any problem.
