### ISSUE TITLE
karma test fails

### ISSUE THREAD

**Issue by armache** [ng-select/ng-select#319]
Hello,

Has anyone succeed to test this control with Karma? I am getting the below error:

![image](https://user-images.githubusercontent.com/22368645/36969558-bb5c751a-205d-11e8-8424-fb5cec489ea8.png)

**Comment by varnastadeus** [comment]
@armache you need to import NgSelectModule into your testing module..

**Comment by armache** [comment]
Thanks!!! That was it, missed the obvious :)
