### ISSUE TITLE
Can't bind to 'markFirst' since it isn't a known property of 'ng-select'.

### ISSUE THREAD

**Issue by AmineBena17** [ng-select/ng-select#320]
### Expected behaviour
set the first item as a default option

### Actual behaviour

i'm using  [markFirst] and i got this error :

`ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'markFirst' since it isn't a known property of 'ng-select'.

If 'markFirst' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. (" <ng-select [multiple]="false" class='w-100'
[ERROR ->][markFirst]="true" #addressSelection name="addressSelection" [required]="field?.required === '1'"
"): ng:///OnlineFormsModule/OnlineFormsComponent.html@134:44
Error: Template parse errors:
Can't bind to 'markFirst' since it isn't a known property of 'ng-select'.
If 'markFirst' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. (" <ng-select [multiple]="false" class='w-100'
[ERROR ->][markFirst]="true" #addressSelection name="addressSelection" [required]="field?.required === '1'"
"): ng:///OnlineFormsModule/OnlineFormsComponent.html@134:44`

### More Info
ng-select version: "2.0.0",

browser: Chrome or Mozilla

reproducible in demo page: NO

**Comment by varnastadeus** [comment]
@AmineBena17 there is no 2.0.0 version 😄

**Comment by AmineBena17** [comment]
i'm really sorry, i put my issue in the wrong library. i'm using another one
