### ISSUE TITLE
Object doesn't support property or method 'remove' error in IE

### ISSUE THREAD

**Issue by compozedani06** [ng-select/ng-select#321]
Please fill below information if issuing a bug report. 

ng-select not working in  IE

ng-select version: 0.23.0

browser: IE11

**Comment by varnastadeus** [comment]
@compozedani06 use latest version

**Comment by prabhathAmila** [comment]
https://recalll.co/ask/v/topic/javascript-Object-doesn%27t-support-property-or-method-%27remove%27/5a7bbca51126f4ac718b6019
