### ISSUE TITLE
Template for value container 

### ISSUE THREAD

**Issue by dzNavitski** [ng-select/ng-select#323]
It will be nice if we can render multiple selected options in `value container` not only with tags but with text. For example, if selected 5 options show `Selected 5`, not five tags.

**Comment by anjmao** [comment]
Hi @dzNavitski, that is good suggestion.
Currently `<ng-template ng-label-tmp let-item="item"></ng-template>` works for both single and multi select. Probably this can be solved by adding new template called something like `ng-multi-label-tmp`

```html
<ng-template ng-multi-label-tmp let-items="items">
    Selected {{items.length}}
</ng-template>`
```

**Comment by varnastadeus** [comment]
#350

**Comment by kalani96746** [comment]
Can this multi select template be added to the demo?
