### ISSUE TITLE
ng-select not display 0 when [items] list contains 0 as number 

### ISSUE THREAD

**Issue by martinmicunda** [ng-select/ng-select#326]
Please fill below information if issuing a bug report. 
### Expected behaviour
The ng-select should display 0 in the select drop-down list.
![2018-03-07_22-02-23](https://user-images.githubusercontent.com/1643606/37120796-48e90e06-2253-11e8-9ea5-040cd1c87991.jpg)

### Actual behaviour
```html
<ng-select [searchable]="false"
                 [clearable]="false"
                 [items]="[0, 30, 60, 90, 120, 180, 240]"
                 formControlName="break">
</ng-select>
```

![2018-03-07_21-56-54](https://user-images.githubusercontent.com/1643606/37120653-e4c3781c-2252-11e8-9933-fd237f30f186.jpg)

### More Info
ng-select version: 0.26.0

browser: Chrome

If I add 0 as string to the list it works, however, I need `[items]` to contains the list of Number and not string.

```html
<ng-select [searchable]="false"
                 [clearable]="false"
                 [items]="['0', 30, 60, 90, 120, 180, 240]"
                 formControlName="break">
</ng-select>
```

**Comment by varnastadeus** [comment]
There is issue in label formatting, will fix it, thanks.

**Comment by anjmao** [comment]
https://github.com/ng-select/ng-select/blob/master/src/ng-select/items-list.ts#L183 use isDefined helper
