### ISSUE TITLE
bug(grouping): ng-optgroup should not be marked on open

### ISSUE THREAD

**Issue by maxkorz** [ng-select/ng-select#330]
### Expected behaviour
I think `ng-optgroup` should not have css class `marked` on select dropdown open.
Instead, the first `ng-option` should have it.

### Actual behaviour
https://stackblitz.com/edit/angular-bmmcbi?file=app%2Fapp.component.ts

`disabled ng-optgroup` is marked
 <img src="https://i.imgur.com/OQkiYhD.png">

### More Info
ng-select version: 0.26.1
browser: Google Chrome
reproducible in demo page: [yes](https://ng-select.github.io/ng-select#/grouping) (clear select and open it )

**Comment by anjmao** [comment]
@maxkorz Thanks, I agree.

**Comment by maxkorz** [comment]
Hmm... I didn't know about the `[selectableGroup]` input.
I assume `ng-optgroup` should be `marked` on open when `[selectableGroup]` is `true`
