### ISSUE TITLE
ng-select imports nodejs util module

### ISSUE THREAD

**Issue by maxkorz** [ng-select/ng-select#331]
https://github.com/ng-select/ng-select/blob/master/src/ng-select/ng-select.component.ts#L42

```
import { isDefined, isFunction, isPromise } from './utils';
import { isObject } from 'util';
```
I think there's an error. `IsObject` should be imported form `'./utils`.

The [plnkr demo](https://plnkr.co/edit/hjZX6W?p=preview) doesn't work because of this bug

**Comment by anjmao** [comment]
@maxkorz Thanks. Naming file utils was bad idea. Renamed to value-utils.ts
