### ISSUE TITLE
Update angular version in peerDependencies

### ISSUE THREAD

**Issue by maxkorz** [ng-select/ng-select#333]
In version 0.23.2 [ng-packagr was updated to version "^2.1.0"](https://github.com/ng-select/ng-select/pull/304/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L66).
But [Version 2 of ng-packagr is targeting Angular 5 (and beyond).](https://github.com/dherges/ng-packagr/blob/master/CHANGELOG.md#200-2018-02-05)

Therefore [package.json](https://github.com/ng-select/ng-select/blob/master/src/package.json) should be updated to something like
```
  "peerDependencies": {
    "@angular/common": ">=5.0.0 <6.0.0",
    "@angular/core": ">=5.0.0 <6.0.0",
    "@angular/forms": ">=5.0.0 <6.0.0"
  },
```

**Comment by anjmao** [comment]
@maxkorz Thanks for update 👍
