### ISSUE TITLE
Custom label and option and optgroup demo looks broken

### ISSUE THREAD

**Issue by maxkorz** [ng-select/ng-select#336]
Demo https://ng-select.github.io/ng-select#/templates
Section "Custom label and option and optgroup"
Looks like this part
```html
    <ng-template ng-optgroup-tmp let-item="item" let-index="index">
        <img height="15" width="15" [src]="item.avatar"/>
        <b [innerHTML]="item.name"></b>
    </ng-template>
```
is broken somehow. `item.name` in `ng-optgroup-tmp` is not displayed

<img src="https://i.imgur.com/54G6yn7.png">

**Comment by varnastadeus** [comment]
@maxkorz because optGroup doesn't have name property, there is mistake in demo.

**Comment by anjmao** [comment]
I did it on purpose. Items are grouped by avatar url, but it may look confusing, will remove `<b [innerHTML]="item.name"></b>` 😄

**Comment by maxkorz** [comment]
@varnastadeus yes, as I pointed out in the issue title, the demo itself looks broken. I don't think there's anything wrong with the plugin code. Just a simple mistake in demo.

**Comment by maxkorz** [comment]
Wait, maybe there's a bug in the plugin. Perhaps the `ng-opgroup` item should have all properties that `ng-option` has? So the demo should work fine
