### ISSUE TITLE
Feature Request: Flag to remove/hide add tag option from list

### ISSUE THREAD

**Issue by lohiaad** [ng-select/ng-select#338]
[x] feature request

I want to use addtag functionality but don't want to show "add tag 'tagname'" as option in dropdown.

Thanks

**Comment by anjmao** [comment]
Hi, how are you suggesting to add tag ten? :)

**Comment by varnastadeus** [comment]
@lohiaad have you tried setting `addTagText` to empty string?

**Comment by lohiaad** [comment]
@varnastadeus  yes. it shows "tagname" in the option
@anjmao by keyboard enter.

i am using ng-select as search/typeahead in my app. User type keywords in ng-select and press enter which filters datagrid. i want to listen that enter event. right now i am thinking of using addTag as promise to achieve this. if there is any other way to track enter event that would also help.

Thanks

**Comment by shyamal890** [comment]
@lohiaad This is another option: https://github.com/ng-select/ng-select/issues/309

**Comment by anjmao** [comment]
@lohiaad Yep, you have a good usecase. We should support adding tags similary here https://angular-mfppay.stackblitz.io/

**Comment by varnastadeus** [comment]
I think this is already supported with https://github.com/ng-select/ng-select/commit/ab6c388
