### ISSUE TITLE
enter event in dropdown leads to call (ngSubmit).

### ISSUE THREAD

**Issue by aadii104** [ng-select/ng-select#339]
Please fill below information if issuing a bug report. 
### Expected behaviour
Enter on a dropdown content should just select the field.

### Actual behaviour
The enter on drodown leads to calling function defined (ngSubmit).

### More Info
ng-select version: [^5.2.1]

browser: [Chrome]

reproducible in demo page: [No]

**Comment by anjmao** [comment]
@aadii104 Hi, thanks for reporting.
