### ISSUE TITLE
Tag input support with adding of non exist text in the list

### ISSUE THREAD

**Issue by shipon-eye** [ng-select/ng-select#34]
First of all, thanks for the nice component.
By the way, it would be better if this component support tag-input feature.
As a tag input component , if the searched query text not matched with the provided list, it will allow to add query text as new item.

**Comment by anjmao** [comment]
@shipon-eye Thanks for your input. Yes this is planned feature and will be implemented in the near feature :)

**Comment by anjmao** [comment]
Possible implementation would be to have output event like this:
```js
@Component({
    template: `
        <ng-select [items]="items" (tag)="onTag(term)">
        </ng-select>
    `
})
class TagsExampleComponent {
    tag = new EventEmitter();
    items = [];
    onTag(term) {
        this.items.push({id: 'custom', name: term});
    }
}
```

**Comment by Hesesses** [comment]
This feature would be super awesome!
