### ISSUE TITLE
Prevent removing a single (predefined) multi-select item

### ISSUE THREAD

**Issue by mjacobson7** [ng-select/ng-select#340]
I would like to submit a feature request.  I have been reading through the docs and don't see that this is currently possible.

What I'm looking for is the ability to disable one multiple select item from being removed.  My use-case, is I have a multi-select input on a users' profile.  Some users (such as admins) have the ability to add or remove roles for themselves or other users.  The default role is the 'user' role.  This is required in order for the user to have access to the site, as it's a system-assigned role. 

![2018-03-10_19-42-51](https://user-images.githubusercontent.com/18683764/37249009-c163046e-249b-11e8-80af-b54e68718e84.png)

Let me know your thoughts and if this fits in with the direction of this tool.

Thanks!

**Comment by varnastadeus** [comment]
@mjacobson7 have you tried setting `user` item as disabled? Or you could use custom template and hide `x` button for user.

**Comment by mjacobson7** [comment]
@varnastadeus I must have overlooked that! Thank-you, this helps immensely! I set the disabled: true in the user object and now it behaves as expected.
