### ISSUE TITLE
Custom items are duplicated when setting ngModel multiple times

### ISSUE THREAD

**Issue by ycros** [ng-select/ng-select#343]
### Expected behaviour
When setting a new ngModel containing custom items, the UI should update to match the items that were set.

### Actual behaviour
Demo: https://plnkr.co/edit/dJEGGTFv9Uug9WsuOhF3?p=preview - press "Set model" several times to cause the bug.

Custom items end up duplicated if they are already present when setting an ngModel. However, if you manually add a custom item by typing it in (ie. type in and add Tokyo in the demo above) and then set the ngModel afterwards, the custom items are no longer duplicated from that point on.

### More Info
ng-select version: 0.26.2

browser: Google Chrome Version 65.0.3325.124 (Official Build) beta (64-bit)

reproducible in demo page: YES

**Comment by anjmao** [comment]
Hi @ycros Thanks for reporting.
