### ISSUE TITLE
Limit the max shown number of labels? 

### ISSUE THREAD

**Issue by liwonder** [ng-select/ng-select#344]
Please fill below information if issuing a bug report. 
### Expected behaviour
Can we limit the max label shown number? 
Like this:
![screen shot 2018-03-13 at 1 31 40 pm](https://user-images.githubusercontent.com/10594457/37324217-1898aa8a-26c3-11e8-9d1a-3944a9f52bed.png)

### Actual behaviour
![screen shot 2018-03-13 at 1 34 02 pm](https://user-images.githubusercontent.com/10594457/37324228-3944b120-26c3-11e8-9e4c-519923dcd157.png)

### More Info
ng-select version: [INSERT HERE]

browser: [INSERT BROWSER INFO HERE]

reproducible in demo page: [NO]

**Comment by liwonder** [comment]
Actually, this is a feature request, and I have implemented this feature in our own fork repository. I can make PR for this feature if you are interested.

**Comment by anjmao** [comment]
Hi @liwonder 
There is similar request https://github.com/ng-select/ng-select/issues/323 which would allow to customize whole label container so you can even have text like `Selected 5 items`.

**Comment by liwonder** [comment]
Thanks @anjmao, I will try it.

**Comment by maxkorz** [comment]
I'm looking forward for this! @liwonder it'd cool if you'd make a PR for this feature.

**Comment by anjmao** [comment]
@liwonder I will implement custom label template for multiselect :)

**Comment by liwonder** [comment]
@anjmao Awesome work! 💯
