### ISSUE TITLE
Can I use alternative property for labels?

### ISSUE THREAD

**Issue by liwonder** [ng-select/ng-select#345]
Please fill below information if issuing a bug report. 
### Expected behaviour
Sometime we have this demand, we want full text in option list and a shorten one in label area.
We have two property to store all the info we need, but I don't find this feature is supported.
![screen shot 2018-03-13 at 2 31 57 pm](https://user-images.githubusercontent.com/10594457/37326136-b8547eb6-26cb-11e8-99fc-77fafffe140f.png)

### Actual behaviour
![screen shot 2018-03-13 at 2 40 25 pm](https://user-images.githubusercontent.com/10594457/37326326-86d01c3c-26cc-11e8-908b-a7d89d0fa1aa.png)

### More Info
ng-select version: [INSERT HERE]

browser: [INSERT BROWSER INFO HERE]

reproducible in demo page: [YES]

**Comment by anjmao** [comment]
Hi @liwonder 

You can use custom label template. When using it on multiselect it will be applied for each item  so you can use another field to show short text https://ng-select.github.io/ng-select#/multiselect See custom labels example.

**Comment by liwonder** [comment]
Nice! Thanks @anjmao 👍
