### ISSUE TITLE
Label style fails

### ISSUE THREAD

**Issue by liwonder** [ng-select/ng-select#354]
### Expected behaviour
![screen shot 2018-03-15 at 10 15 03 am](https://user-images.githubusercontent.com/10594457/37440951-1138821a-283a-11e8-9c9c-a39ce973fac5.png)

### Actual behaviour
![screen shot 2018-03-15 at 10 11 23 am](https://user-images.githubusercontent.com/10594457/37440997-34aafd86-283a-11e8-9d29-2c6493759d8a.png)

### More Info
We have a body element style set like this:
`body {
    line-height: 1.3;
    font-size: 14px;
}`

Now I added a css below for a temporary fix: 
`ng-select .ng-value span {
    display: inline-block;
}`

And I am using:
`@import "~@ng-select/ng-select/themes/default.theme.css";`

ng-select version: [0.27.1]

browser: [ Chrome Version 65.0.3325.162 (Official Build) (64-bit)]

reproducible in demo page: [NO]

**Comment by liwonder** [comment]
I also have a worked plunker here:
https://plnkr.co/edit/8bVrc1da11A2AebUrLZQ?p=preview

**Comment by bioub** [comment]
I have the same issue, incoming PR.

**Comment by bioub** [comment]
I've removed some paddings to prevent this from happening, could you try with this PR ?
