### ISSUE TITLE
[closeOnSelect]="true" not working in multi select with custom template

### ISSUE THREAD

**Issue by manimurugank** [ng-select/ng-select#355]
Please fill below information if issuing a bug report. 
### Expected behaviour
Describe how you think it should work

### Actual behaviour
Describe how it actually works or create example using [Plunker](https://plnkr.co/edit/hjZX6W?p=preview) issue template

### More Info
ng-select version: [INSERT HERE]

browser: [INSERT BROWSER INFO HERE]

reproducible in demo page: [YES/NO]

**Comment by nareshpingale** [comment]
@manimurugank Refer example [demo page](https://ng-select.github.io/ng-select#/multiselect) for implementation. In case of an issue in some particular case please provide details or steps to reproduce.

**Comment by varnastadeus** [comment]
@manimurugank `[closeOnSelect]="true"` is the default value. Whats the issue here?

**Comment by manimurugank** [comment]
ng-select version:  "@ng-select/ng-select": "^0.15.2",

browser: chrome
reproducible in demo page:  No

**Comment by etay-schur-apolicy** [comment]
having the same issue , set closeOnSelect to true with custom template just don't work ..
the dropdown menu always stay open after selection 
anything new with this issue ?
