### ISSUE TITLE
ng: Member 'clear' is not callable

### ISSUE THREAD

**Issue by maxkorz** [ng-select/ng-select#356]
### Expected behaviour
Member clear should have correct typescript type

### Actual behaviour
<img src="https://i.imgur.com/rmfg2YO.png">

### More Info
ng-select version: 0.29.1
browser: N/A
reproducible in demo page: NO (you need to use IDE to see the error)

P.S. I'm not sure if it's possible to fix it.

**Comment by maxkorz** [comment]
Sorry, false alarm.

**Comment by ikismail** [comment]
I'm getting the same error how did you solved this ?

**Comment by shrujal-shah** [comment]
Duplicate of #428

**Comment by ehsanshrz** [comment]
I had this problem too. Does anyone have a solution?
