### ISSUE TITLE
Clear button in Custom template opens the dropdown

### ISSUE THREAD

**Issue by maxkorz** [ng-select/ng-select#357]
### Actual behaviour
The dropdown opens when I click on Clear button in custom template
<img src="https://i.imgur.com/dqnncdk.png">

### More Info
ng-select version: 0.29.1
browser: google chrome
reproducible in demo page: YES https://ng-select.github.io/ng-select#/multiselect

**Comment by varnastadeus** [comment]
it is missing `$event.stopPropagation()` on click event

**Comment by varnastadeus** [comment]
fixed in #359
