### ISSUE TITLE
Material Design Style: Placeholder should float to top and not disappear

### ISSUE THREAD

**Issue by juristr** [ng-select/ng-select#358]
Please fill below information if issuing a bug report. 
### Expected behaviour

When using the material design style, the placeholder should float to the top and stay there, just as in the native material design guidelines. Adding a label doesn't work, as that stays at the very top

![material-form](https://user-images.githubusercontent.com/542458/37452233-4469cb4a-2834-11e8-8455-019f653236b1.gif)

### Actual behaviour

When using the placeholder, the placeholder correctly floats to the top of the autocomplete, but then disappears once the value has been selected.

![material-ng-select](https://user-images.githubusercontent.com/542458/37452351-9e8bd03c-2834-11e8-885e-299d894e43e9.gif)

### More Info
ng-select version: 0.29.1

browser: Chrome

reproducible in demo page: https://stackblitz.com/edit/angular-ng-select-style

**Comment by aitboudad** [comment]
if it's for angular material integration, the better way is to provide a custom form field control, see https://material.angular.io/guide/creating-a-custom-form-field-control.

**Comment by aitboudad** [comment]
here is a quick example with `@ngx-formly/material` integration but without using ng-select style (to be done by yourself :smirk:),
https://stackblitz.com/edit/angular-gcxzly

**Comment by juristr** [comment]
@aitboudad You're everywhere 🎉. 

> if it's for angular material integration, the better way is to provide a custom form field control

Yep it's for Angular Material integration. Depends on the scope of `ng-select`, if it's intended to work with other material styles (and not just the `@angular/material` components), then probably a fix needs to be added here. Otherwise I agree, then a custom material form field needs to be implemented.

> here is a quick example with @ngx-formly/material integration but without using ng-select style (to be done by yourself 😏),
https://stackblitz.com/edit/angular-gcxzly

Yep, found this weird behavior while integrating it into my @ngx-formly setup 😄. Thx for the Stackblitz example. I've done it similarly. Now I'm verifying again

**Comment by chicomarques90** [comment]
@juristr about that

> Yep, found this weird behavior while integrating it into my @ngx-formly setup 😄. Thx for the Stackblitz example. I've done it similarly. Now I'm verifying again

Did you have any progress?

**Comment by Saqib92** [comment]
how can i keep it floated even before selected values?
