### ISSUE TITLE
Set Focus on ng-select by Code

### ISSUE THREAD

**Issue by frozenmaiden** [ng-select/ng-select#365]
I create 2 ng-select on 1 page like below

`<ng-select [items]="dataOffice"
                                                    bindLabel="office_name"
                                                    bindValue="office_code"
                                                    placeholder="- Select -"
                                                    #office="ngModel"
                                                    (keydown.enter)="keytab($event, 'customer')"
                                                    name="office">
                                                </ng-select>`

`<ng-select [items]="dataCustomer"
                                                    bindLabel="customer_name"
                                                    bindValue="customer_code"
                                                    placeholder="- Select -"
                                                    #customer="ngModel"
                                                    id="customer"
                                                    name="customer">
                                             </ng-select>`

and then i set event (keydown.enter) on office so when i press enter the focus will change to customer 

`keytab(event, target)
{
            let nextElm = this.renderer2.selectRootElement('#' + targetElm);
            nextElm.focus();
}`

Its work on input or normal select, but when on ng-select the focus not changed to customer dropdown and the dropdown become blank.

Can you advice?

**Comment by varnastadeus** [comment]
@frozenmaiden you could use `#select.focusSearchInput()`

**Comment by BruneXX** [comment]
@varnastadeus where focusSearchInput() was added in https://github.com/ng-select/ng-select/blob/master/src/ng-select/ng-select.component.ts I cannot see that method? is in some PR that need to be merged yet?

**Comment by BruneXX** [comment]
If it helps someone, I've managed to set focus on ng-select input element this way:

`this.ngSelectInput.filterInput.nativeElement.focus();`

**Comment by varnastadeus** [comment]
there is no need, latest version has method `focus`. `#select.focus()`

**Comment by mulaczos** [comment]
@varnastadeus focus is only applicable to static # tags in html. How to get focus on dynamically added ng-select element? I'm using them with *ngFor. Could you provide an example? I couldn't find any solution..

**Comment by varnastadeus** [comment]
which one you are planning to focus if they are dynamic? You could use `ContentChildren`
```ts
@ContentChildren(NgSelectComponent) selects: QueryList<NgSelectComponent>;
```

**Comment by ashiqqa** [comment]
```

focusNextField(ngSelectElementId){
    var element =document.getElementById(ngSelectElementId)
    .firstElementChild.firstElementChild.lastElementChild
    .getElementsByTagName('input');
    
    if(element.item(0)){
      element.item(0).focus();
    }
  }
```

**Comment by suhailvs** [comment]
```
@ViewChild('productsearch', {static: false}) productsearch;
...
public ngAfterViewInit() {
    this.productsearch.focus();
}
```
