### ISSUE TITLE
Dont focus on ng-select when option is choosen

### ISSUE THREAD

**Issue by domara** [ng-select/ng-select#368]
Please fill below information if issuing a bug report. 
### Expected behaviour
When I choose a value in select I would expect not to have blinking sign in select box

### Actual behaviour
When I choose value I have focus on input.

reproducible in demo page: [YES]

####################
Is there a possibility to have a searchable dropdown and don't focus on the element after the value is selected?

**Comment by anjmao** [comment]
Hi @domara, thanks for reporting. I also noticed this issue.

**Comment by anjmao** [comment]
@domara Finally I was able to figure out how to fix it, fix is quit simple https://github.com/ng-select/ng-select/issues/368
