### ISSUE TITLE
Suggestion: Consider changing the overlay technique to prevent double click to focus another element

### ISSUE THREAD

**Issue by markheron91** [ng-select/ng-select#369]
Just started using your library and have a small suggestion to do with the feature of closing the select component when another area of the screen is clicked. Currently it looks like an invisible overlay is placed over the screen content that has a click event to close the open select. However, this stops me from focusing on another input or select, or clicking a button as the first click closes the overlay. I then need to click again to perform the action I wanted.

My suggestion, if possible is to alter the strategy so that an immediate action can be taken in the same click as closing the currently open ng-select component.

Thanks.

Please fill below information if issuing a bug report. 
### Expected behaviour
Whilst having an ng-select component open, clicking on another element (an ng-select element or other input/button etc) should immediately perform the relevant action.

### Actual behaviour
Describe how it actually works or create example using [Plunker](https://plnkr.co/edit/hjZX6W?p=preview) issue template
Clicking outside of an open ng-select removes the overlay and then you have to click again on an element to focus/peform action.

### More Info
ng-select version: 0.28.1

browser: Chrome|Firefox|Edge|IE11

reproducible in demo page: Yes

**Comment by anjmao** [comment]
Hi @markheron91, before it was working as expected, but at some point we refactored to use overlay as it is works the same in native HTML5 select and does not require to listen to global click events but as we see there are some drawbacks. Here is original issue https://github.com/ng-select/ng-select/issues/313
