### ISSUE TITLE
IE Translate not working

### ISSUE THREAD

**Issue by learning-angular-project** [ng-select/ng-select#372]
### Expected behaviour
It sould use translate data
 providers: [
    {
      provide: NG_SELECT_DEFAULT_CONFIG,
      useFactory: (translate: TranslateService) => {
        return {
          notFoundText: translate.instant('label.no-result'),
          loadingText: translate.instant('label.loading'),
        };
      },
      deps: [TranslateService]
    }
  ]

### Actual behaviour
Translate data is ok in firefox and chrome but in IE I see the sentence lable.loading instead of the good translation

### More Info
ng-select version: 0.30.1

browser: IE

reproducible in demo page: [YES/NO]

**Comment by anjmao** [comment]
Hi @learning-angular-project, I think it is not related to ng-select. It seems that something is wrong with TranslateService itself.
