### ISSUE TITLE
groupBy on object 

### ISSUE THREAD

**Issue by dottodot** [ng-select/ng-select#375]
Using the latest version I'm trying to use groupBy, but the value I want to group by is in an object rather than a string. I've tried a few things such dot notation `groupBy="parent.title"` and custom templates but can't figure it out. It might not even be possible.

**Comment by dottodot** [comment]
Yes that's correct so something like 

```
{
 title: 'My title',
parent: {
  title: 'Title to group by',
 }
}
```

**Comment by anjmao** [comment]
If you are grouping by nested object property where will you put all parent properties? I think this can’t be implemented, but there is another iprovement to allow setting children array.

**Comment by dottodot** [comment]
I got around it just by mapping the value i wanted into a new attribute at the top level, which works for my purposes.

**Comment by overworks-be** [comment]
I have made a PR for fix the issue.

**Comment by anjmao** [comment]
Hi @overworks-be  Thanks for contributing. I wrote some comments 👍
