### ISSUE TITLE
aot

### ISSUE THREAD

**Issue by MartynenkoA** [ng-select/ng-select#376]
when i buil with aot i have error, 
WARNING in ./src/app/rules/rules.module.ngfactory.js
67:5825-5831 "export 'ɵn' (imported as 'i26') was not found in '@ng-select/ng-select'

**Comment by varnastadeus** [comment]
@MartynenkoA can you provide your `angularCompilerOptions`?

**Comment by varnastadeus** [comment]
@MartynenkoA add tsconfig from src folder.

**Comment by MartynenkoA** [comment]
i reopened ide, and error will not plat) tnx
