### ISSUE TITLE
Dropdown doesn't close when selecting outside the box or selecting other dropdown

### ISSUE THREAD

**Issue by xigolle** [ng-select/ng-select#378]
Please fill below information if issuing a bug report. 
### Expected behaviour
Whenever the user clicks outside the dropdown or when opening/selecting another input the dropdown should be closed again.

### Actual behaviour
The dropdown stays open (only closes when you select a value) and when you open multiple dropdowns the overlap each other.

### More Info
ng-select version: 0.30.1

browser: Google Chrome

reproducible in demo page: NO

**Comment by varnastadeus** [comment]
@xigolle please make reproducible plnkr or stackblitz, otherwise we can't do much.
