### ISSUE TITLE
How to prevent selection of value that is already selected in sibling ng-select?

### ISSUE THREAD

**Issue by mirzal** [ng-select/ng-select#379]
I have a group of few `<ng-select>`. They all share single `items` list from parent component. But user should be able to select any item only once - if it was selected in first `<ng-select>`, it shouldn't be selectable in all other `<ng-select>`s. Ideally, it would just disappear from their `items` list, but making it blocked is OK as well.

Is such setup possible? What would be the best way to approach it?

Thanks!

**Comment by varnastadeus** [comment]
It is possible but there is no easy way, I think you should have your `items` separated and handle each select by removing selected from corresponding `items`.

**Comment by mirzal** [comment]
Thank you for your answer. Too bad that there is no easy way to do that, but I understand this is far from primary use-case.
