### ISSUE TITLE
Add public method to change option state

### ISSUE THREAD

**Issue by anjmao** [ng-select/ng-select#38]
Problem: 
Because we are using OnPush change detection it is not possible to change option state and set it disabled, selected or marked programmatically.

Possible solution: 
Create public method `setOptionState(option)` in ng-select component which would allow to change option state and trigger change detection.

**Comment by varnastadeus** [comment]
I would argue if this is needed
1) `Selected`, `Marked` is redundant since marked is more of internal stuff, and selected is achieved by setting your model with desired value
2) You can set option disabled by repopulating your items, e.g.
```javascript
this.companies[0].disabled = true;
this.companies = [...this.companies];
```

**Comment by anjmao** [comment]
Agree.
