### ISSUE TITLE
Material Design Style: Selected value above clear and dropdown icons

### ISSUE THREAD

**Issue by SergeyCherman** [ng-select/ng-select#381]
Please fill below information if issuing a bug report. 
### Expected behaviour
When using the material design style, the selected text should be on the same line as the icons.

![image](https://user-images.githubusercontent.com/10699293/37830777-a28354e4-2e79-11e8-8949-f994e7ad15b9.png)

I'll issue a PR this weekend.

### Actual behaviour
The selected value is above the "clear" and dropdown icons

![screen shot 2018-03-23 at 9 05 54 am](https://user-images.githubusercontent.com/10699293/37830730-7622a594-2e79-11e8-81dc-342b198d6746.png)

### More Info
ng-select version: 0.30.1

browser: Chrome
reproducible in demo page: YES
https://stackblitz.com/edit/angular-ng-select-style-w7cxcc

**Comment by varnastadeus** [comment]
It is not reproducible in demo and there is something wrong with your example, since it is missing default font, and line-height sizes.
```
body {
  font-size: 16px;
  line-height: 24px;
}
```
fixes the problem

**Comment by Tindermere** [comment]
Why was this closed? I have the same issue and the bug is in the demo.
