### ISSUE TITLE
No value accessor for form control with unspecified name attribute

### ISSUE THREAD

**Issue by iObsidian** [ng-select/ng-select#383]
Using Yarn

installed ng-select, everything went O.K.

Now when I add

    <label>City</label>
    <ng-select [items]="cities"
               bindLabel="name"
               bindValue="id"
               placeholder="Select city"
               [(ngModel)]="selectedCityId">
    </ng-select>
    <p>
        Selected city ID: {{selectedCityId}}
    </p>

to my template and

     cities = [
            {id: 1, name: 'Vilnius'},
            {id: 2, name: 'Kaunas'},
            {id: 3, name: 'Pabradė'}
        ];
        selectedCityId: any;

to my typescript, I get this error 

`ERROR Error​columnNumber: 11​fileName: "http://localhost:9000/app/vendor.bundle.js line 47 > eval"​lineNumber: 2505​message: "No value accessor for form control with unspecified name attribute"​ngDebugContext: Object { view: {…}, nodeIndex: 5, nodeDef: {…}, … }​ngErrorLogger: function bound ()​stack: "_throwError@webpack-internal:///./node_modules/@angular/forms/esm5/forms.js:2505:11\nsetUpControl@webpack-internal:///./node_modules/@angular/forms/esm5/forms.js:2375:9\nNgModel.prototype._setUpStandalone@webpack-internal:///./node_modules/@angular/forms/esm5/forms.js:6281:9\nNgModel.prototype._setUpControl@webpack-internal:///./node_modules/@angular/forms/esm5/forms.js:6250:32\nNgModel.prototype.ngOnChanges@webpack-internal:///./node_modules/@angular/forms/esm5/forms.js:6178:13\ncheckAndUpdateDirectiveInline@webpack-internal:///./node_modules/@angular/core/esm5/core.js:12562:9\ncheckAndUpdateNodeInline@webpack-internal:///./node_modules/@angular/core/esm5/core.js:14093:20\ncheckAndUpdateNode@webpack-internal:///./node_modules/@angular/core/esm5/core.js:14036:16\ndebugCheckAndUpdateNode@webpack-internal:///./node_modules/@angular/core/esm5/core.js:14929:55\ndebugCheckDirectivesFn@webpack-internal:///./node_modules/@angular/core/esm5/core.js:14870:13\nView_ServerComponent_0/<@ng:///RealmSpyServerModule/ServerComponent.ngfactory.js:32:5\ndebugUpdateDirectives@webpack-internal:///./node_modules/@angular/core/esm5/core.js:14855:12\ncheckAndUpdateView@webpack-internal:///./node_modules/@angular/core/esm5/core.js:14002:5\ncallViewAction@webpack-internal:///./node_modules/@angular/core/esm5/core.js:14353:21\nexecComponentViewsAction@webpack-internal:///./node_modules/@angular/core/esm5/core.js:14285:13\ncheckAndUpdateView@webpack-internal:///./node_modules/@angular/core/esm5/core.js:14008:5\ncallViewAction@webpack-internal:///./node_modules/@angular/core/esm5/core.js:14353:21\nexecEmbeddedViewsAction@webpack-internal:///./node_modules/@angular/core/esm5/core.js:14311:17\ncheckAndUpdateView@webpack-internal:///./node_modules/@angular/core/esm5/core.js:14003:5\ncallViewAction@webpack-internal:///./node_modules/@angular/core/esm5/core.js:14353:21\nexecComponentViewsAction@webpack-internal:///./node_modules/@angular/core/esm5/core.js:14285:13\ncheckAndUpdateView@webpack-internal:///./node_modules/@angular/core/esm5/core.js:14008:5\ncallWithDebugContext@webpack-internal:///./node_modules/@angular/core/esm5/core.js:15256:39\ndebugCheckAndUpdateView@webpack-internal:///./node_modules/@angular/core/esm5/core.js:14793:12\nViewRef_.prototype.detectChanges@webpack-internal:///./node_modules/@angular/core/esm5/core.js:11774:13\nApplicationRef.prototype.tick/<@webpack-internal:///./node_modules/@angular/core/esm5/core.js:6106:58\nApplicationRef.prototype.tick@webpack-internal:///./node_modules/@angular/core/esm5/core.js:6106:13\nnext/<@webpack-internal:///./node_modules/@angular/core/esm5/core.js:5939:99\nZoneDelegate.prototype.invoke@webpack-internal:///./node_modules/zone.js/dist/zone.js:388:17\nonInvoke@webpack-internal:///./node_modules/@angular/core/esm5/core.js:4948:24\nZoneDelegate.prototype.invoke@webpack-internal:///./node_modules/zone.js/dist/zone.js:387:17\nZone.prototype.run@webpack-internal:///./node_modules/zone.js/dist/zone.js:138:24\nNgZone.prototype.run@webpack-internal:///./node_modules/@angular/core/esm5/core.js:4765:54\nnext@webpack-internal:///./node_modules/@angular/core/esm5/core.js:5939:69\nEventEmitter.prototype.subscribe/schedulerFn<@webpack-internal:///./node_modules/@angular/core/esm5/core.js:4534:36\nSafeSubscriber.prototype.__tryOrUnsub@webpack-internal:///./node_modules/rxjs/_esm5/Subscriber.js:245:13\nSafeSubscriber.prototype.next@webpack-internal:///./node_modules/rxjs/_esm5/Subscriber.js:192:17\nSubscriber.prototype._next@webpack-internal:///./node_modules/rxjs/_esm5/Subscriber.js:133:9\nSubscriber.prototype.next@webpack-internal:///./node_modules/rxjs/_esm5/Subscriber.js:97:13\nSubject.prototype.next@webpack-internal:///./node_modules/rxjs/_esm5/Subject.js:66:17\nEventEmitter.prototype.emit@webpack-internal:///./node_modules/@angular/core/esm5/core.js:4514:24\ncheckStable@webpack-internal:///./node_modules/@angular/core/esm5/core.js:4913:13\nonHasTask@webpack-internal:///./node_modules/@angular/core/esm5/core.js:4961:21\nZoneDelegate.prototype.hasTask@webpack-internal:///./node_modules/zone.js/dist/zone.js:441:21\nZoneDelegate.prototype._updateTaskCount@webpack-internal:///./node_modules/zone.js/dist/zone.js:461:17\nZone.prototype._updateTaskCount@webpack-internal:///./node_modules/zone.js/dist/zone.js:285:17\nZone.prototype.runTask@webpack-internal:///./node_modules/zone.js/dist/zone.js:205:25\ndrainMicroTaskQueue@webpack-internal:///./node_modules/zone.js/dist/zone.js:594:25\nZoneTask.invokeTask@webpack-internal:///./node_modules/zone.js/dist/zone.js:499:21\ninvokeTask@webpack-internal:///./node_modules/zone.js/dist/zone.js:1536:9\nglobalZoneAwareCallback@webpack-internal:///./node_modules/zone.js/dist/zone.js:1562:17\n"​__proto__: Object { … } ServerComponent.html:1:21
`

if I add 'ngDefaultControl' I get no error but my dropdown is still not showing

**Comment by varnastadeus** [comment]
@iObsidian don't forget to add theme.

**Comment by varnastadeus** [comment]
@iObsidian if you are still experiencing any issues, create new issue with reproducible stackblitz.
