### ISSUE TITLE
Need option to search label text by matching from the start of the label

### ISSUE THREAD

**Issue by mingluochicago** [ng-select/ng-select#387]
It will be very helpful to have an option (maybe a property in the control) to allow user to search the label text by matching with the start of the label rather than matching anywhere in the label.

Take the following options as an example:
<ng-select [(ngModel)]="staticValue">
    <ng-option value="Volvo">Volvo</ng-option>
    <ng-option value="Saab">Saab</ng-option>
    <ng-option value="Opel">Opel</ng-option>
    <ng-option value="Audi">Audi</ng-option>
    <ng-option value="Honda">Honda</ng-option>
</ng-select>

Type "o" in the search textbox.

### Actual behaviour
The search result will display three items with "o" as part of the text:
Volvo
Opel
Honda

### Expected behaviour
With this option turned on, I expect to see only one result that starts with "o":
Opel

**Comment by anjmao** [comment]
Hi @mingluochicago, you can use typeahead input to filter as you want, have you tried it ? :)

**Comment by mingluochicago** [comment]
Yeah, but our client also wants the functionality of a dropdown control so that they pick items as they want.

**Comment by mingluochicago** [comment]
@anjmao I think I misunderstood what you meant. Indeed this control has typeahead capability. The problem I have is I am using the ng-select control in many places in our application. It would be impossible for me to implement typeahead one by one. It would be much better if ng-select control itself have this functionality embedded.

**Comment by anjmao** [comment]
What do you think if ng-select can have input [searchFn] so you can pass function expression like this

```ts
startsWithSearchFn(item, term) {
     return item.startsWith(term);
}
```

```html
<ng-select [searchFn]="startsWithSearchFn"></ng-select>
```

**Comment by mingluochicago** [comment]
@anjmao That will be perfect!

**Comment by varnastadeus** [comment]
I think this feature could cover #167 also
