### ISSUE TITLE
Export theme scss files in npm package and use more variables

### ISSUE THREAD

**Issue by tomgruszowski** [ng-select/ng-select#388]
This seems to be the best select2 angular control, it is also extremely actively updated.

Would like to be able to plug scss and replace some colors via variables rather than overwriting the generated css. Reasons: maintainability and ease

**Comment by anjmao** [comment]
Hi @tomgruszowski, thanks for suggestion :)

**Comment by piernik** [comment]
Any news on this??

**Comment by anjmao** [comment]
Would be great if somebody could help with this improvement 👍

**Comment by smasala** [comment]
Agree, would be nice if the `scss` files were exported so that the following deprecation warning is gone when using `node-sass`:

```
Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.
```

**Comment by varnastadeus** [comment]
with #946 sass will be shipped with npm package
