### ISSUE TITLE
Can I add a dropdown list as a sample data table?

### ISSUE THREAD

**Issue by smile2014** [ng-select/ng-select#389]
I use the ag-grid, it seems impossible to achieve a custom template

**Comment by anjmao** [comment]
@smile2014 Hi, you can look at https://github.com/ng-select/ng-select/blob/master/demo/app/examples/custom-templates.component.ts#L27 I was able to put bootstrap card inside dropdown.

**Comment by smile2014** [comment]
@anjmao  I understand what you said, but the effect I want is as follows. It is estimated that you will change your source code.

https://www.jeasyui.com/demo-angular/main/index.php?plugin=ComboGrid&theme=material&dir=ltr&pitem=&sort=

**Comment by anjmao** [comment]
@smile2014 hah, this looks interesting. I'm not sure if current custom templates would allow to do something like this, but I'm keeping this open for now.

**Comment by smile2014** [comment]
@anjmao The data model can not be customized, now must have index and label, but the back end is usually code, name or id, name

**Comment by varnastadeus** [comment]
As @anjmao mentioned before to achieve this you need to use custom templates and style each option as it would be table row. For table header use `ng-header-tmp`.

**Comment by smile2014** [comment]
@varnastadeus  It is difficult to have a selection effect with styles, and it is more appropriate to combine third-party datatable.
