### ISSUE TITLE
WARNING in Circular dependency detected:

### ISSUE THREAD

**Issue by smile2014** [ng-select/ng-select#394]
WARNING in Circular dependency detected:
src\app\ng-select\ng-select.component.ts -> src\app\ng-select\ng-dropdown-panel.component.ts -> src\app\ng-select\ng-select.component.ts

**Comment by anjmao** [comment]
This is normal , but I didn't found time to check how to disable it.

**Comment by rcalazansn** [comment]
Hi @anjmao, how are you?
about this item "circular dependency detected" I recived this message when build my project, are there some fix?
thanks
