### ISSUE TITLE
Autoposition inside container with overflow

### ISSUE THREAD

**Issue by michalturak** [ng-select/ng-select#395]
### Expected behaviour
It should be possible to pass parent container which should be considered when calculating autoposition

### Actual behaviour
When i have container inside body with overflow hidden, dropdown is calculating position top|bottom based on document.documentElement.clientHeight and dropdown is cutted off

### More Info
ng-select version: v0.32.0 

plunker: https://plnkr.co/edit/aioU5QDs9S2Uhhk5fawU?p=preview
(plunker is probably with older version but its still an issue in v.0.32.0)

**Comment by rodrigorellana** [comment]
hi
i have a similar problem
using a template that b ng-select there are a problem with margin bottom page
on desktop and mobile view, it cut dropdown look

GIF: https://imgur.com/a/ovytEK4

greetings

**Comment by varnastadeus** [comment]
I think this issue is resolved with appendTo='body'
