### ISSUE TITLE
How to properly use the input items array

### ISSUE THREAD

**Issue by karljv** [ng-select/ng-select#396]
Hello,

I am trying to properly use the input items array. As the documentation states, the [items] input is Array<NgOption>. 

My use case is that I have an array of tags

```
class TagModel {
    public id: number;
    public name: string;
    public isChecked: boolean;
    public ngOption: NgOption;
}
```

The ngOption on the tag is initialized as such

```
public initNgOption() {
         this.ngOption = {
             name: this.name,
             //index?: number,
             selected: this.isChecked,
             //disabled?: boolean,
             //marked?: boolean,
             label: this.name,
             value: this,
             //parent?: NgOption,
             //hasChildren?: boolean,
        };
    }
```

And I want to pass these tags to the <ng-select> component as such

```
<ng-select  class="classic m--b-12 m--r-12"
                                [multiple]="true"
                                [items]="tagsArray"
                                [bindValue]="'ngOption'"
                                [(ngModel)]="tags">
</ng-select>
```

It works as in, I have as many options as I have input tags, but the they have no labels and if I pass in a row of selected tags as ngModel, it does not register.

What am I doing wrong here? Should I skip creating the NgOption properties on the tags and just use the tags themselves as input, without the bindValue (Which, I am not sure whether I am using correctly anyway).

**Comment by anjmao** [comment]
@karljv Hi, your code looks incorrect. Could you please create Plunker or stackblitz repro, because parts of your code are missing and so it is hard to tell from there to start 😆
