### ISSUE TITLE
Make [loading] compatible with typeahead (or provide a [minimumInputLength] option)

### ISSUE THREAD

**Issue by bioub** [ng-select/ng-select#399]
### Expected behaviour
I would like to have the abitity to indicate loading manually with a typeahead or have a [minimumInputLength] option. 
I think we should have [loading] compatible with [typeahead] or provide a [minimumInputLength] option (as in select2).
I can do the PR if you tell me which option you prefer.

### Actual behaviour
In this example ng-select shows loading even if I filter my typeahead (minLength 3) :
[https://stackblitz.com/edit/ng-select-minimuminputlength](https://stackblitz.com/edit/ng-select-minimuminputlength)

### More Info
ng-select version: 0.34

browser: All

reproducible in demo page: NO

**Comment by varnastadeus** [comment]
I think the best way would be  disregard "automatic" loading if user has `[loading]` defined.

**Comment by lohiaad** [comment]
@varnastadeus agreed. need more control on [loading]
