### ISSUE TITLE
GroupBy property issue

### ISSUE THREAD

**Issue by Puex** [ng-select/ng-select#400]
### Expected behaviour
I want to use the groupBy property on the ng-select.

### Actual behaviour
It doesn't work, it says in my console that groupBy isn't a known property of ng-select. Am I missing something ? Maybe I didn't add a special dependency or a declaration in my appmodule ?

### More Info
ng-select version: 0.34.2

**Comment by anjmao** [comment]
Hi @Puex You don't need any other dependency, probably there is a bug in your code? Could you create plunker sample or paste you html code?

**Comment by varnastadeus** [comment]
maybe you are using wrong library, lol

**Comment by BearandYoon** [comment]
Hi @varnastadeus 
Groupby feature doesn't work on ng-select version 0.18.0?
I am using version 0.18.0, Angular 4.2.6 and groupby feature doesn't work for me.
