### ISSUE TITLE
Which version to use for Angular4?

### ISSUE THREAD

**Issue by osajidui** [ng-select/ng-select#402]
Getting below error after change from Nov26.
`/ng-select@0.34.2 requires a peer of @angular/common@>=5.0.0 `

**Comment by varnastadeus** [comment]
same as you used before?

**Comment by Phota16** [comment]
It's not compatible with Angular version 4. Can you please make it. When I run in angular 4, it run for 1st time. In 2nd build it's gives error 
![image](https://user-images.githubusercontent.com/20189130/38639667-8933881a-3d97-11e8-8d29-824cc6053005.png)
