### ISSUE TITLE
style(default.theme.scss) Disabled elements should have a margin left

### ISSUE THREAD

**Issue by bioub** [ng-select/ng-select#406]
### Expected behaviour
Disabled elements should have a margin left

<img width="430" alt="capture d ecran 2018-04-02 a 14 05 11" src="https://user-images.githubusercontent.com/1698236/38195690-1ab4c026-367f-11e8-984d-c3a8fb6118ed.png">

### Actual behaviour
Individual disabled elements don't have any margin left

<img width="424" alt="capture d ecran 2018-04-02 a 14 05 26" src="https://user-images.githubusercontent.com/1698236/38195687-170336a6-367f-11e8-94aa-45f717d14b36.png">

### More Info
ng-select version: 0.34.3

browser: all

reproducible in demo page: NO (don't have individual disabled elements)

I can't do the PR and stay compatible with #354 and existing code

**Comment by varnastadeus** [comment]
Not sure if this issue still valid, on the demo page margins are present. 
<img width="659" alt="screen shot 2018-05-06 at 11 37 28" src="https://user-images.githubusercontent.com/17824796/39671481-eb6ab90c-5121-11e8-93ee-586822c0bade.png">

**Comment by bioub** [comment]
@varnastadeus It only affect individual disabled items (not the case on the demos page).

Check out this demo : https://angular-zkmecv.stackblitz.io/
