### ISSUE TITLE
RROR in Metadata version mismatch for module ../node_modules/@ng-select/ng-select/ng-select.d.ts, found version 4, expected 3, resolving symbol AppModule

### ISSUE THREAD

**Issue by johns24** [ng-select/ng-select#408]
**Expected behaviour**
ng serve starts an Angular application (using ng-select) with no problems

**Actual behaviour**
Upon ng serve, error occurs:

ERROR in Metadata version mismatch for module /node_modules/@ng-select/ng-select/ng-select.d.ts, found version 4, expected 3, resolving symbol AppModule in /src/app/app.module.ts, resolving symbol AppModule in /src/app/app.module.ts

Here is my package.json:

`{
  "name": "vr",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular-generic-table/core": "^4.7.0",
    "@angular/animations": "^4.0.0",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "@ng-select/ng-select": "^0.33.0",
    "@types/jquery": "^2.0.42",
    "@types/node": "^6.0.72",
    "angular-calendar": "^0.11.0",
    "angular2-csv": "^0.2.5",
    "core-js": "^2.4.1",
    "datatables.net": "^1.10.16",
    "essence-ng2-print": "^1.1.0",
    "jquery": "^3.2.1",
    "mdn-polyfills": "^3.4.0",
    "mydatepicker": "^2.0.13",
    "ng-packagr": "^2.0.0",
    "ng2-cookies": "^1.0.12",
    "ng2-quill-editor": "^2.0.0",
    "primeng": "^5.0.0-rc.0",
    "rxjs": "^5.5.8",
    "ts-helpers": "^1.1.1",
    "underscore": "^1.8.3",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.0.0",
    "@angular/compiler-cli": "^4.0.0",
    "@types/jasmine": "2.5.38",
    "@types/jquery": "^2.0.48",
    "@types/node": "~6.0.60",
    "@types/quill": "0.0.29",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.0"
  }
}
`

**Comment by anjmao** [comment]
Hi @johns24 since ng-select is not in v1 yet and angular 4 is quit old now, there is no much point to support older angular versions. Migration from 4 to 5 is pretty simply in any why.
