### ISSUE TITLE
Allow to clear filter text value

### ISSUE THREAD

**Issue by andrea-spotsoftware** [ng-select/ng-select#41]
Hello @anjmao, i'm evaluating your component in a project that i'm working on.
It's almost perfect for my needs, but there is an issue that I found about the behavior of the input (that is actually empty) when an option item is selected.

In your opinion, it's hard to do something like this?
http://plnkr.co/edit/l3phEaaU2HyAiHlJcmwQ?p=preview
I'd like to have text selectable and clearable directly from the filter input.

**Comment by andrea-spotsoftware** [comment]
I could open a PR for this

**Comment by anjmao** [comment]
Hi @andrea-spotsoftware, this should be easy to do. There is showClear() method in https://github.com/ng-select/ng-select/blob/master/src/lib/src/ng-select.component.html#L41
You just need to update showClear() method to also check if filterValue was set, because currently it checks only if value was selected. Let me know if you need more help :)

**Comment by andrea-spotsoftware** [comment]
I think I have not explained well 😄 
You are talking about showing the cross button during filtering, right?

I was thinking about persisting selected item's display text in the html input field, making possible to select (for copy purpose) and delete it "manually", for example with keyboard backspace or canc, having the same effect of the cross button on the right.

Probably the filter input text should be visible only when the select gets focus, because it would hide the custom label template.
Obviously, this feature makes sense only in single selection mode. 

The plunker that i attached on the first message shows this behavior, if you select an item, it's clearable also with keyboard.

**Comment by anjmao** [comment]
Right, now I see what you mean. I don't like the idea of adding some background color for selected text like in kendo combobox, it looks ugly :) Let just make it this as simple as clearing model value on backspace(delete) button click, this will also work in multiselect case.
