### ISSUE TITLE
Issue auto close dropdown when searchable is false

### ISSUE THREAD

**Issue by KeitaElric** [ng-select/ng-select#412]
### Expected behavior
This issue occurs when I deactivate searchable and use focus output event to open dropdown together

### Actual behavior
View my plunker: https://plnkr.co/edit/WgSP8yQnar0gcCUEbVFY?p=preview

**Comment by varnastadeus** [comment]
@KeitaElric it happens because click opens dropdown and focus event closes it again, since with `[searchable]` focus works as toggle.
