### ISSUE TITLE
Feature request: Custom CLASS for dropdown list

### ISSUE THREAD

**Issue by fspezi** [ng-select/ng-select#413]
I am developing a "phone number" component. It is build with 2 parts:  
- a select where user select the international prefix (like +39, +44, and so on)
- a standard input where user type the national number without international prefix.

The first must be width=100px, the second 400px.  
The first is made with `ng-select`. I need to show flag and prefix. But, when the drop-down is shown, I would view the country name also.  
The problem is that the drop-down list is width like as fixed part: 100px.  

Then I suggest to permit a customization of the drop-down container, like allowing define a CLASS for it, or the ability to define an option to customize the drop-down size: min-width, or withAsContent:bool...

**Comment by varnastadeus** [comment]
@fspezi there are plenty issues regarding with, #293 #409
