### ISSUE TITLE
Error: Binding object({"id":2,"descricao":"Últimos 7 dias"}) with bindValue is not allowed.

### ISSUE THREAD

**Issue by emmanueldaher** [ng-select/ng-select#417]
Hello folks,

I think I got a very complex case. I've wrapped ng-select inside my own select to provide custom styles, custom empty option and custom search funcionality. And the inputs for options are always objects.

`
<ng-select [(ngModel)]="selected" [placeholder]="placeholder" [clearable]="allowClear" [searchable]="false" [disabled]="disabled" (blur)="onBlur()" (ngModelChange)="onSelect($event)" (open)="focusSearchBox()" (close)="onClose()">

    <ng-template ng-label-tmp let-item="item">
        {{getPropValue(selected, label) || emptyOption}}
    </ng-template>

    <ng-template *ngIf="searchable" ng-header-tmp>
        <div class="form-group no-margin has-feedback">
            <input #searchBox class="form-control" type="text" (input)="filter($event.target.value)" />
            <span class="form-control-feedback" aria-hidden="true">
                <span class="fa fa-search"></span>
            </span>
        </div>
    </ng-template>

    <ng-option *ngIf="showEmptyOption()" [value]="undefined">
        <span [ngOptionHighlight]="searchTerm" [innerHTML]="emptyOption"></span>
    </ng-option>

    <ng-template ngFor let-item [ngForOf]="optionsFiltered" [ngForTrackBy]="getTrackByFn()">
        <ng-option [value]="item">
            <ng-template [ngIf]="useOptionTemplate" [ngIfElse]="default">
                <ng-container *ngTemplateOutlet="itemTemplate; context: { item: item, searchTerm: searchTerm }"></ng-container>
            </ng-template>
            <ng-template #default>
                <span [ngOptionHighlight]="searchTerm" [innerHTML]="item[label]"></span>
            </ng-template>
        </ng-option>
    </ng-template>
</ng-select>
`

### Expected behaviour
Set the selected item properly from ngModel value.

### Actual behaviour
When I try to set de selected value **after the component initialization** I get the message:

> Error: Binding object({"id":2,"descricao":"Últimos 7 dias"}) with bindValue is not allowed.

And the ng-select doesn't change it's selected value even with no bindValue property value, remaning empty apparentily.

### More Info
ng-select version: 0.35.0

browser: Chrome

reproducible in demo page: NO

**Comment by varnastadeus** [comment]
@emmanueldaher  #148

**Comment by emmanueldaher** [comment]
@varnastadeus I think this isn't the same case, on #148 it's a simple binding. On my case I use <ng-option> and don't pass [items], nothing more, I also set [searchable]="false" and implement my custom search logic.

Besides, I only get the error when I change ngModel programmatically. If the user selects some option manually, there is no error.

but still I don't know for sure.

**Comment by varnastadeus** [comment]
It is the same issue. The error says that you are trying to set object as your ngModel when it expects simple value.

**Comment by emmanueldaher** [comment]
@varnastadeus I didn't noticed, but at some newer version was implemented the `[searchFn]` attribute, then it was possible to solve my core problem, custom search...

Thanks for the quickly replies

**Comment by mrSingh007** [comment]
why this ticket has been closed? I did see fix here. I am facing same problem. 
According to docu: bindValue-> Object property to use for selected model. By default binds to whole object.
My object looks like this:
```
[
 {
 key: "hello world",
 pk: "001"
}
{
 key: "hi there",
 pk: "002"
}
]
```
Thats how my code look like:
```
<ng-select
              class="btn-xxs"
              formControlName="costCenter"
              [items]="costCenters$ | async"
              bindLabel="key"
              bindValue="pk"
              (change)="costCenterChanged()"
            ></ng-select>
```
Here my form should be binded to pk thats why bindValue is pk. 
So why I am getting this 'bindValue is not allowed' ???
@varnastadeus
