### ISSUE TITLE
changing displayed value programmatically

### ISSUE THREAD

**Issue by gasiort** [ng-select/ng-select#418]
is it possible to change displayed value programmatically?

my `ng-select` looks like this: 

```
<ng-select [items]="imagesList"
                       [virtualScroll]="true"
                       bindLabel="imageName"
                       bindValue="imageId"
                       placeholder="Select image"
                       (add)="onSelectorSelect($event)">
            </ng-select>
```

By displayed value I mean `imageName` that appears in `ng-select` when object is choosed

**Comment by varnastadeus** [comment]
@gasiort selected value corresponds to `ngModel`, so setting `ngModel` changes selected value.
