### ISSUE TITLE
Bind Value - How to use?

### ISSUE THREAD

**Issue by carlhussey** [ng-select/ng-select#42]
This is probably working as intended but I figured I would ask.

I am using a reactive form, my control value is an array of objects. When I use bingLabel, everything is fine. When I bindValue to a property within the objects, it throws an error.

`ERROR Error: Binding object with bindValue is not allowed.`

```
cities: = [
      {id: '1', name: 'Vilnius'},
      {id: '2', name: 'Kaunas'},
      {id: '3', name: 'Pavilnys'} 
  ];
     
  ngOnInit(){
      this.heroForm = this.fb.group({
          city: [this.cities]
      });
  }

<ng-select 
   [items]="cities"
   placeholder="Select city"
   bindValue="id"
   bindLabel="name"
   formControlName="city">
</ng-select>

```
Should I be able to bind to the property of an object such as `bindValue="cities.id"` or `bindValue="city.id"`?

I may be over thinking this, seems to work without the `bindValue` there at all but was curious why I was getting the error.

https://plnkr.co/edit/eRnhdJBeIQhTTcmmK4Zv?p=preview

**Comment by varnastadeus** [comment]
Hi @carlhussey,
The idea of bindValue is to be able to bind single property as your selected model, e.g. if you have `{id: '1', name: 'Vilnius'}`, and you select 'Vilnius', then your `city`will be `'1'`, therefore your model can't be anything other than your provided bindValue. 

In your case you should set city as '1'
```javascript
ngOnInit(){
      this.heroForm = this.fb.group({
          city: '1'
      });
  }```

**Comment by carlhussey** [comment]
Thanks for the info, this clears it up!

**Comment by burakkilic** [comment]
How can we preselect multiple objects?

**Comment by ronbnsim** [comment]
I dont understand why they do this limitation?????
if you remove the "warning" in the code in  `NgSelectComponent.prototype._isValidWriteValue` to return true it works with objects just fine.

when this should be fixed alot of people here need to select objects...atleast let us work with the "compareWith" to recognize the object our self.

**Comment by mrduantran** [comment]
sample as code, i need show: bindLabel: 'id' + 'name', but not run

**Comment by kiren-aur** [comment]
> sample as code, i need show: bindLabel: 'id' + 'name', but not run

@mrduantran if I understand well your question, I think what you are looking for is a custom template. check docu. https://ng-select.github.io/ng-select#/templates
