### ISSUE TITLE
Bug: select.searchInputFocus should open the dropdown panel

### ISSUE THREAD

**Issue by shyamal890** [ng-select/ng-select#420]
Please fill below information if issuing a bug report. 
### Expected behaviour
When `ng-select` is programmatically focused with `focusSearchInput()`, `dropdown-panel` should open but it doesn't

https://stackblitz.com/edit/ng-select-focus-issue

**Comment by varnastadeus** [comment]
@shyamal890 why it should open dropdown panel? Tab focus doesn't opens it either.

**Comment by shyamal890** [comment]
![image](https://user-images.githubusercontent.com/6606965/38425340-44d15e28-39d1-11e8-92f7-58afe2493f4c.png)

Currently when the user clicks on the input, dropdown is triggered. So I thought its logical that `#select.focusSearchInput()` triggers the dropdown.

**Comment by varnastadeus** [comment]
Yes, but `focusSearchInput` works as default focus when you navigate with `tab` which doesn't opens dropdown.

**Comment by shyamal890** [comment]
Ok so how to focus and trigger dropdown similar to what happens when a user clicks on the input?

**Comment by varnastadeus** [comment]
You can just open it straightaway.
```javascript
setFocus = () => {
      this.select.open();
}
```

**Comment by varnastadeus** [comment]
how come attribute would be better than current option?

**Comment by shyamal890** [comment]
I am not sure. However, this should be in documentation.
