### ISSUE TITLE
Bug: ng-select doesn't hide the placeholder with bootstrap

### ISSUE THREAD

**Issue by Pat-Lovelace** [ng-select/ng-select#422]
### Expected behaviour
In the last version (0.35.1), the select should hide the placeholder when you select an option (with Bootstrap). 

### Actual behavior
The actual behavior: it shows the placeholder following by the selected item. As you can check on your example: [Demo](https://stackblitz.com/edit/ng-select?file=app%2Fapp.component.ts). [You have to install the last version: @ng-select/ng-select@0.35.1]

![image](https://user-images.githubusercontent.com/32704155/38413303-936a0b7a-398b-11e8-9ebf-d7cbe402b794.png)

I think this behaviour was caused by the bug fix: 

> 0.34.3 (2018-03-31)
> keep placeholder visible in material theme [(1e16f98)](https://github.com/ng-select/ng-select/commit/1e16f98), closes [#358 ](https://github.com/ng-select/ng-select/issues/358)

### More Info
ng-select version: 0.35.1

reproducible in demo page: YES

**Comment by varnastadeus** [comment]
@Pat-Lovelace [stackblitz](https://stackblitz.com/edit/ng-select?file=app%2Fapp.component.ts) I don't see it reproducible in stackblitz or in demo page.
