### ISSUE TITLE
[question] typeahead search : list isn't refreshed after item selection 

### ISSUE THREAD

**Issue by stoto34** [ng-select/ng-select#424]
Please fill below information if issuing a bug report. 
### Expected behaviour
I'm using custom search with an API. The API sends me 10 items per page. So the search works very well, I can search element on the second page but when I select and item, the list is not refreshed and the list is still filtered by the search.

How can I "restore" the full list one time I searched and selected an item ?

### Actual behaviour
Describe how it actually works or create example using [Plunker](https://plnkr.co/edit/hjZX6W?p=preview) issue template

### More Info
ng-select version: [INSERT HERE]

browser: [INSERT BROWSER INFO HERE]

reproducible in demo page: [YES/NO]

**Comment by varnastadeus** [comment]
@stoto34 after you selected item, just restore `[items]` with your desired state.

**Comment by stoto34** [comment]
Thank you for your quick answer. My problem by step :

* I have a list with lot of items.
* I search one item which is not on the list
* The item appears alone into the list
* I select it to add
* The search is empty but the list is still on the selected element, the list is not restored.

**Comment by stoto34** [comment]
I'm really sorry but I don't understand. My code is inspired from differents examples so maybe I have something wrong here. 

I've tried the "change event" as you suggested but still the same problem. If I don't select an item and erase what I've wrote, the old list comes back. If I select the item, the list is still filtered with the search even if there is nothing into the input (after the selected items I've just added).

In my component : 

        this.typeahead
            .pipe(
                debounceTime(200),
                switchMap(term => this.loadItems(term))
            )
            .subscribe(items => {
                this.listItems = items as Item[];
                this.cd.markForCheck();
            }, (err) => {
                console.log('error', err);
                this.listItems = [];
                this.cd.markForCheck();
            });
       
-------------

load items

    loadItems(term: string) {
        this.currentPage = 1;
        let criterias = [];

        if (term != "") {
            criterias['designation'] = term;
            this.searchItem = term;
        }
        return this.itemService.find(criterias, null, this.currentPage);
    }


---------------------

    fetchMoreItems() {

        let like = false;
        let pages = this.itemService.getPages();
        this.currentPage = this.currentPage + 1;

        if ( pages >= this.currentPage ) {
            if (this.searchItem) {
                let criterias = {};
                criterias["designation"] = this.searchItem;

                this.itemService.find(criterias, this.currentPage, like).subscribe(data => {
                    this.listItems = this.listItems.concat(data as Item[]);
                });
            } else {
                this.itemService.find(null, this.currentPage, like).subscribe(data => {
                    this.listItems = this.listItems .concat(data as Item[]);
                });
            }
        }
    }


------------------------

the view


                                        <ng-select [items]="listItems"
                                            bindLabel="designation"
                                            [virtualScroll]="true"
                                            (scrollToEnd)="fetchMoreItems($event)"
                                            [closeOnSelect]="false"
                                            [loading]="loading"
                                            dropdownPosition="top"
                                            placeholder="List of items"
                                            [multiple]="true"
                                            [typeahead]="typeahead"
                                            [(ngModel)]="currentItems"
                                            (change)="changeItem($event)"
                                            [ngModelOptions]="{standalone: true}">
                                        </ng-select>
                                    </div>

What i'm doing wrong ?

**Comment by stoto34** [comment]
After further consideration i think i got it wrong. 
Finally, I will use close event to load again the list.
