### ISSUE TITLE
rtl support

### ISSUE THREAD

**Issue by MetaiR** [ng-select/ng-select#426]
hello,
does this project contain or support any RTL version?

**Comment by varnastadeus** [comment]
@MetaiR no

**Comment by MetaiR** [comment]
if someone does it, do you accept the pull request?

**Comment by anjmao** [comment]
@MetaiR sure :)

**Comment by MehdiSaeedifar** [comment]
Still nor rtl version?

**Comment by ananbetak** [comment]
ok so ?
how to use this rtl on some selects ?

**Comment by IbrahimElkhatib** [comment]
any. updates on this?
