### ISSUE TITLE
Bug: Blur triggered on ng-footer-tmp click

### ISSUE THREAD

**Issue by shyamal890** [ng-select/ng-select#427]
Please fill below information if issuing a bug report. 
### Expected behaviour
Blur event shouldn't be triggered on click in `ng-footer-tmp`

**Comment by shyamal890** [comment]
This is not allowing click event in footer to be triggered. Example: https://stackblitz.com/edit/ng-select-footer-blur-issue

**Comment by varnastadeus** [comment]
@shyamal890 in your case you should handle it yourself since we can't handle any events on your custom template.
```
<div (mousedown)="$event.preventDefault()" (click)="footerEvent()">
   Test
</div>
```

**Comment by shyamal890** [comment]
Shouldn't this code be a part of `ng-dropdown-footer` div?

**Comment by varnastadeus** [comment]
If you put in on whole div then you will loose all valuable events, for example text selection.
