### ISSUE TITLE
[disabled] option doesn't work

### ISSUE THREAD

**Issue by arkonbob** [ng-select/ng-select#429]
I have tried adding the option [disabled]="true" to an ng-select as shown here:

[https://ng-select.github.io/ng-select#/multiselect](url)

However I receive the following runtime error in the browser console:

`Can't bind to 'disabled' since it isn't a known property of 'ng-select'.` 

I would like to use the option on a single select if possible, but I have tested on both a single and multi select and it doesn't work in either case. Other options work as expected. 

### More Info
ng-select version: 0.35.1

browser: Chrome, IE11

reproducible in demo page: NO

**Comment by anjmao** [comment]
Hi @arkonbob It is working fine for me on both single and multi select. It seems that you forgot to import `FormsModule` to you NgModule.

**Comment by arkonbob** [comment]
Thanks for the update. I have FormsModule imported. I've tried various combinations, importing to the root app module, the submodule and both together, I still get the error. Can you suggest anything else that might cause this?

**Comment by varnastadeus** [comment]
@arkonbob #132

**Comment by arkonbob** [comment]
@varnastadeus Yes, adding [(ngModel)] to the ng-select fixed it. Many thanks!

**Comment by kSzajo** [comment]
> @varnastadeus Yes, adding [(ngModel)] to the ng-select fixed it. Many thanks!

Hey, what do you mean by adding [(ngModel)]?
I have independent module, inside I imported FormsModule

**Comment by gajalchouhan** [comment]
@varnastadeus I am not getting your point. Can you please explain in brief or please give an example to understand this.

**Comment by jagomf** [comment]
Probably it means that ng-select cannot be disabled unless it is inside and bound to a form.
