### ISSUE TITLE
Angular 6-rc2 & ng-select 35.1 - binding issue

### ISSUE THREAD

**Issue by syska** [ng-select/ng-select#430]
Please fill below information if issuing a bug report. 
### Expected behaviour
Should bind to 'group' and make 'test' the selected value in the ng-select.

### Actual behaviour
Binding does not seem to work

### More Info
ng-select version: 35.1

browser: FF 59.0.2 (64-bit) on Windows

reproducible in demo page: NO

Here is my code:
template:

```
<div class="row">
  <div class="col-lg-12">
    <form role="form" ngForm #form="ngForm">
      <div class="form-group">
        <label>Nagios Host Group</label>
        <ng-select [items]="list" name="group" ([ngModel])="group"></ng-select>
      </div>
      <div>
        {{ group }}
      </div>
    </form>
  </div>
</div>
```

Component:
```
import { Component, OnInit } from '@angular/core';

import { NgForm } from '@angular/forms';

@Component({
  selector: 'mappings/mapping-details',
  templateUrl: './mapping-details.component.html',
  styleUrls: ['./mapping-details.component.css']
})
export class MappingDetailsComponent implements OnInit {
  public group = 'test2';
  public list = ['test', 'test2'];

  constructor() { }

  ngOnInit() {
  }
}
```

The ng-select shows the items, but does not update the binding value on "group".

Not sure if this is supposed to work with Angular 6 ... since it's only a few day ago since the first RC.

**Comment by anjmao** [comment]
Hi @syska, I just tried angular 6 RC3 and it is working fine https://stackblitz.com/edit/ng-select-angular6?file=app/app.component.ts
