### ISSUE TITLE
Updating the list dynamically

### ISSUE THREAD

**Issue by Varshamathukumalli** [ng-select/ng-select#431]
Hi,

On item selection change i want to modify the list binded to it.
I tried updating the list, but its not working.
Is there any way to solve this.

**Comment by anjmao** [comment]
Hi @Varshamathukumalli , please read https://github.com/ng-select/ng-select#change-detection
You need to change items reference so angular can detect changes.

**Comment by pierresh** [comment]
Hello,

It would be great to update the documentation by providing an example in which an array of objects is added to items instead of a single new object :)
