### ISSUE TITLE
Slow down and resource usage with large list in latest version (0.35.2)

### ISSUE THREAD

**Issue by bab2683** [ng-select/ng-select#432]
### Expected behaviour
Load list

### Actual behaviour
In the latest version, when handling a large list (+3k) it slows down dramatically and consumes twice the memory and it takes a few seconds to render the list, also the search implementation doesn't work.
I'm currently using v. 0.20.3 and it has no problems whatsoever, I just wanted to try the new features and noticed these bugs.

### More Info
ng-select version: 0.35.2

browser: all of them

**Comment by varnastadeus** [comment]
@bab2683 can you create reproducible stacklitz?

**Comment by bab2683** [comment]
@varnastadeus  I don't think I can today since I have a meeting , tomorrow morning you'll have it

**Comment by varnastadeus** [comment]
@bab2683 you can fork [Stackblitz](https://stackblitz.com/edit/ng-select?file=app%2Fapp.component.ts) and modify for your use case

**Comment by anjmao** [comment]
@bab2683 In newest version virtual scroll is not turn on by default, you need to use [virtualScroll]="true"

**Comment by bab2683** [comment]
@anjmao I tried it, doesn't solve the problem.
@varnastadeus here is the [Stackblitz](https://stackblitz.com/edit/ng-select-2bq8my) as requested. As you can see already, it is slow (takes 1 or 2 seconds to even load the list), with the version I'm currently working (0.20.3) this doesn't happen

**Comment by anjmao** [comment]
@bab2683 I just added [virtualScroll]="true" and it works fast and fine. In you stackblitz example I don't see `[virtualScroll]="true"`

```html
<ng-select [items]="bigList"
                   [virtualScroll]="true"
                   bindLabel="title"
                   placeholder="Select photo"
                   [(ngModel)]="selected_photo">
</ng-select>
```

**Comment by anjmao** [comment]
I will do profiling to check memory usage :)

**Comment by varnastadeus** [comment]
I have done some profiling and I don't see any memory increase, I would say it performs same or slightly better.

**Comment by trungjc** [comment]
[virtualScroll]="true" help me resolve the problem
