### ISSUE TITLE
[Question] My bindings dont bind correctly after update.

### ISSUE THREAD

**Issue by meiuqer** [ng-select/ng-select#435]
So i didn't change anything about my code but i did update to a more recent version of ng-select and know when i change something the ng-select stays empty up until i click something. 

I tried looking for something that changed, but couldn't immediately find something. Maybe i overlooked something? Sorry if this question has been asked before.

Angular version:
angular/cli: 1.0.3
node: 6.11.1
os: win32 x64
angular/common: 4.1.2
angular/compiler: 4.1.2
angular/core: 4.1.2
angular/forms: 4.1.2
angular/http: 4.1.2
angular/platform-browser: 4.1.2
angular/platform-browser-dynamic: 4.1.2
angular/router: 4.1.2
angular/cli: 1.0.3
angular/compiler-cli: 4.1.2

Ng-select:
"ng-select": "^1.0.0-rc.3",

Sample code:

HTML: 
```
<ng-select [options]="options" [ngModel]="value" (ngModelChange)="emit($event)"
    [placeholder]="placeholder">
</ng-select>
```
Typscript: 

```
import { Component, Input, Output, EventEmitter, OnChanges, OnInit, ChangeDetectionStrategy } from '@angular/core';

@Component({
    selector: 'cv-select',
    templateUrl: './select.component.html',
    styleUrls: ['./select.component.css'],
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class SelectComponent implements OnInit, OnChanges {
    @Input() public options: any;
    @Input() public value: any;
    @Input() public placeholder: string;
    @Output() public valueChange = new EventEmitter();

    public firstChange: boolean = true;

    constructor() {
    }
    ngOnChanges(changes) {
    }
    ngOnInit() {
    }
    convertArray(array) {
    }
    emit(event) {
        this.valueChange.emit(this.value);
        this.firstChange = false;
    }
}
```
`options` is always in the format of `{ label: string, value: string`.
`value` is always a string

**Comment by anjmao** [comment]
Hi @meiuqer 
Could you write which angular and ng-select version are you using and add code sample which is not working for you, thanks.

**Comment by meiuqer** [comment]
Right, sorry about that.

**Comment by anjmao** [comment]
You are using wrong ng-select. Version which you are using is from https://basvandenberg.github.io/ng-select#/home source code.
