### ISSUE TITLE
found version 4, expected 3, resolving symbol AppModule

### ISSUE THREAD

**Issue by fortheworld2017** [ng-select/ng-select#445]
ERROR in Metadata version mismatch for module D:/Git/project/Jonathan Harper/dmcangularapp/node_modules/@ng-select/ng-select/ng-select.d.ts, found version 4, expected 3, resolving symbol AppModule in D:/Git/project/Jonathan Harper/dmcangularapp/src/app/app.module.ts, resolving symbol AppModule in D:/Git/project/Jonathan Harper/dmcangularapp/src/app/app.module.ts

I have installed latest version and use Angular 4

**Comment by varnastadeus** [comment]
#329
