### ISSUE TITLE
How to bind one item to select tag

### ISSUE THREAD

**Issue by MansoorJafari** [ng-select/ng-select#450]
Hello
How to bind a item to select tag after load from server.

`<ng-select [items]="serverSideFilterItems"
                   bindLabel="fullName"
                   bindValue="customerId"
                   [typeahead]="customerTypeahead"
                   [(ngModel)]="account.customerId"
                   name="customerId"
                   #customerId="ngModel">
                   </ng-select>`

`
          this.accountService.GetCustomer(this.account.customerId).subscribe(cus=>{
              console.log(cus);
              this.serverSideFilterItems.push(cus);
              this.account.customerId = this.serverSideFilterItems[0].customerId;
          });`

after  load  a data from server and push to serverSideFilterItems
but dosen't show in select tag.
please help.

**Comment by varnastadeus** [comment]
@MansoorJafari https://github.com/ng-select/ng-select#change-detection
