### ISSUE TITLE
Feature Request: maxSelectedToShow when multiple is true

### ISSUE THREAD

**Issue by superkick** [ng-select/ng-select#452]
[x] feature request

Hi,

Sorry if this has been requested (or is possible?) but I'd love to be able to set a "maximum number of selected items to show" parameter when using multiple select.   

For example, the user selects 3 choices which is the "max".  A further selection is still chosen and highlighted in the open menu, and "+1" is shown as a badge in the "ng-value-container" area. 

![screen shot 2018-04-13 at 09 34 35](https://user-images.githubusercontent.com/15162932/38725384-19fec914-3eff-11e8-8c52-2289da1245be.png)

The use case is for fixing the physical size of box which is what my design needs.  Currently the box grows as the user selects more items. My users have up to 30 options.

This idea is implemented in "Angular 2 MultiSelect Dropdown" but ng-select is a vastly superior library IMHO:  https://cuppalabs.github.io/components/multiselectDropdown/

Cheers.

**Comment by varnastadeus** [comment]
@superkick its is already possibble. https://ng-select.github.io/ng-select#/multiselect

**Comment by superkick** [comment]
Many thanks @varnastadeus
