### ISSUE TITLE
My issue: DropDown does not close on background click when NgSelect in Popup

### ISSUE THREAD

**Issue by fspezi** [ng-select/ng-select#453]
I have an Issue in my code that I can't resolve.  
Can someone help me?  
I need to know where is the piece of code that manage the closing of Dropdown on click out of ng-select element.

### Expected behaviour

When dropdown is opened, I expect that it will close on click to any point of screen.

### Actual behaviour

The dropdown do not close. ng-select close dropdown on select to item or click to little arrow only.

### More Info

ng-select version: 0.36.2

browser: Chrome  65.0.3325.18

reproducible in demo page: NO

The NgSelect is drown inside Bootstrap Popup.  
The Popup size is equal to entire window.  
Popup position css style is "fixed".

**Comment by anjmao** [comment]
Hi @fspezi, ng-select creats invisible overlay, and it looks like modal window and overlay z-index values are not correct. As a quick fix you can solve it by making your modal z-index smaller than ng-select overlay, which modal are you using?

**Comment by fspezi** [comment]
Thanks for your support.  
I found the `ng-overlay-container` inside `ng-control`.

And now I understand that... the problem is not the Modal (z-index 2000) but a slideshow that it contains.  
I am using slideshow to develop a wizard.
The slideshow contains 4 pages, `ng-select` is inside the second page. The `ng-overlay-container` is drawn like in first page because the slideshow uses `transform` css attribute.

Then if `ng-overlay-container` was injected as brother of `ng-dropdown-panel`, my page would work well.

**Comment by anjmao** [comment]
This is related to https://github.com/ng-select/ng-select/issues/313
Overlay is created inside ng-select container which is not correct, because it will not be possible to set correct z-index in some cases like this because of z-context layout.
