### ISSUE TITLE
Error importing style for Ionic app

### ISSUE THREAD

**Issue by GCoe** [ng-select/ng-select#454]
I'm trying ng-select for an Ionic app but could apply style. Got this error : Refused to apply style from 'http://localhost:8100/build/~@ng-select/ng-select/themes/material.theme.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

Any idea ?

**Comment by anjmao** [comment]
Hi @GCoe,
It looks like something is wrong with Ionic http server or you are missing something. It stackblitz example it s works fine https://stackblitz.com/edit/ng-select-ionic?file=pages%2Fhome%2Fhome.html

You need to import styles inside your app main style.scss file
```scss
@import "~@ng-select/ng-select/themes/material.theme.css";
```
