### ISSUE TITLE
Spinner loader bug

### ISSUE THREAD

**Issue by LuanMaik** [ng-select/ng-select#456]
When I type only 1 caracter, the spin show, but the min length is 3;
```
this.typeahead
.pipe(
       distinctUntilChanged(),
       filter(t => t && t.length > 3),
       debounceTime(this.debounce),
       switchMap(term => this.search(term))
).subscribe((data : any) => {
       this.cd.markForCheck();
       this.registers = data.resultSet.data;
    }, (err) => {
      console.log(err);
      this.registers = [];
});
```

**Comment by anjmao** [comment]
Hi @LuanMaik could you try using [loading] input to manually control loading state and let me know it it  solves this problem?

**Comment by varnastadeus** [comment]
#399 duplicate

**Comment by LuanMaik** [comment]
The filter() method in ng-select.component.ts (line 399) verify if using typehead and use _typeaheadLoading attribute to control the loading status.

```
filter(term: string) {
        if (!this.searchable) {
            return;
        }
        this.filterValue = term;
        this.open();

        if (this._isTypeahead) {
            this._typeaheadLoading = true;
            this.typeahead.next(this.filterValue);
        } else {
            this.itemsList.filter(this.filterValue);
            this.itemsList.markSelectedOrDefault(this.markFirst);
        }
    }
```
The right way would be for the component to use only one attribute to control the loading status.

**Comment by anjmao** [comment]
@LuanMaik You are correct, I made a fix here https://github.com/ng-select/ng-select/pull/466 and removed this logic.
