### ISSUE TITLE
Not possible to create custom options when using hideSelected and item array is empty or already selected

### ISSUE THREAD

**Issue by goliknes** [ng-select/ng-select#457]
### Expected behaviour
It is not possible to  create custom options (addTag) if the item array is either empty or all items are selected.

### Actual behaviour
https://stackblitz.com/edit/ng-select-add-tag-hide-selected

### More Info
ng-select version: 0.36.2

browser: Google Chrome

reproducible in demo page: NO

**Comment by romanfedyshyn** [comment]
Have the same issue

**Comment by varnastadeus** [comment]
will look at it.
