### ISSUE TITLE
Installation/update issue, version 0.36.2

### ISSUE THREAD

**Issue by fspezi** [ng-select/ng-select#458]
I'm install `@ng-select/ng-select` version 0.36.2.

### Expected behaviour

When I look the HTML code I can't find elements with `ng-select-container` class.  

### Actual behaviour

The `ng-select` element hierarchy is:

    ng-select
        .ng-control
            .ng-value-container
                .ng-placeholder
                .ng-input

### More Info

ng-select version: 0.36.2

browser: Chrome, 65.0.3325.18

reproducible in demo page: NO

Seems like I am using a previous version. But the file "node_modules/@ng-select/ng-select/package.json" say me that the file version is right.

I was install component with this step:  

- insert this row in "dependencies" of "package.json" file: "@ng-select/ng-select": "^0.36.2"
- delete previous `nodes_module` folder and `package-lock.json" file
- run "npm install"

**Comment by anjmao** [comment]
Hi, please try installing newest version 1.0.1-rc0 which should have these html elements.

**Comment by fspezi** [comment]
Perfect! Thanks!
