### ISSUE TITLE
Error: ExpressionChangedAfterItHasBeenCheckedError after ngModelChange

### ISSUE THREAD

**Issue by sofiaseixas93** [ng-select/ng-select#460]
Hello, I'm having an issue in my code and am hoping that someone can help me.
What I'm trying to achieve is opening a Modal whenever the selected value in my dropdown is changed, but I keep getting the following error:

ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'true'. Current value: 'false'.

I can open the Modal just fine though, but I can't figure out why the error is showing up and how to prevent it from happening.
If I change the dropdown  to a regular select, I don't get the error, that's why I'm assuming this is related to ng-select.

Here is a sample code reproducing the error: 
https://stackblitz.com/edit/ng-select-example-l55yh8

Can anyone help me? Thanks in advance!

**Comment by anjmao** [comment]
@sofiaseixas93  I pushed new version with a fix, let me know it it helped.

**Comment by sofiaseixas93** [comment]
@anjmao Yes that fixed it, thank you so much!

**Comment by The-Don-Himself** [comment]
Hi @anjmao 
Great work, any chance we can have this merged on the 1.x branch for Angular 5.x users, please.
