### ISSUE TITLE
 use object to selected data in FormControl error binding

### ISSUE THREAD

**Issue by tsetrest** [ng-select/ng-select#462]
-- users2 for selected data   
users2: NgOption[] = [
        {id: '1'} 
    ]; 
-- usersLoad for loading data to select
    usersLoad: NgOption[] = [
        {id: '1', name: 'Anjmao'},
        {id: '2', name: 'Tadeus Varnas'}
    ]; 
but i have problem with this 
https://plnkr.co/edit/hHQ0kHdYfC9ltIk6QH2u?p=preview

**Comment by varnastadeus** [comment]
@tsetrest in your case there is now way to determine selected values so you need to provide `compareWith`

```javascript
compareFn(a, b) {
      return a.id === b.id;
}
```

**Comment by tsetrest** [comment]
not work 
!! Can't bind to 'compareWith' since it isn't a known property of 'ng-select'.

**Comment by varnastadeus** [comment]
omg! update to latest version!
