### ISSUE TITLE
DropDown position wrong when enabled "Virtual scroll" and "append to" options

### ISSUE THREAD

**Issue by fspezi** [ng-select/ng-select#463]
### Expected behaviour

The drop-down position is not perfect.  

1) When ng-select is shown in bottom of page, drop-down should be shown in top of ng-select. It is not always in right position.  

2) When I search a item typing inside textbox, the list will be reduce. But if drop-down is in top of ng-select, drop-down do not change the position.

3) When ng-select is in div in "position:fixed", the drop-down do not follow ng-select in scrolling.

### Actual behaviour

The drop-down is shown over the ng-select, or sometimes below it.

### More Info
ng-select version: 1.0.2

reproducible in demo page: https://stackblitz.com/edit/angular-pzw5i4

**Comment by fspezi** [comment]
Thanks for your support. 

The style solve some issue but not others.  
Point 2: typing "g" in last ng-select, the drop-down filter items but it is not positioned near relative ng-select. The position do not change. Look screenshot:

![image](https://user-images.githubusercontent.com/1487920/38854726-b81d5906-4221-11e8-8055-18fe47d0fd7e.png)

**Comment by carpeVideo** [comment]
Not sure if this will help - but I had issues with the dropdown panel position when embedded several levels down in scrollable items and if I changed the code in ng-dropdown-panel.component.ts slightly I got better results (~ line 363) - I have not seen any adverse reactions to my change

```
        //const offsetTop = selectRect.top - boundingRect.top;
		const offsetTop = selectRect.top + window.scrollY; 
```

**Comment by fspezi** [comment]
I was try it.  
But it has not fix issue.

When I filter items with dropdown on top of ng-select, the dropdown do not move near ng-select on resize of dropdown height.

When I try to scroll the ng-contaier container (where it has position:fixed) the dropdown to not follow ng-select (appendTo=body)
