### ISSUE TITLE
Focus Input on click

### ISSUE THREAD

**Issue by papaZuhl** [ng-select/ng-select#467]
### Expected behaviour
Using the mouse, if I click on any part of an unfocused ng-select component, I would expect the input element to focus so that I can just start typing to filter the items.

### Actual behaviour
If I click anywhere that is not the input element, for example slightly above or below the input element or the dropdown arrow, the ng-select component will focus and open the item list. 
However, it will not focus the input element and I can not start typing if I did not explicitly click the input element.

### More Info
ng-select version: 1.0.2

browser: Firefox 59.0.2; Chrome 65.0.3325.181
 
in demo page: YES

**Comment by anjmao** [comment]
Hi @papaZuhl , I just pushed 1.0.3 version which should fix this issue.

**Comment by papaZuhl** [comment]
Hey @anjmao thanks for the quick response, works great!

However, if I focus the ng-select component via mouseclick and subsequently click slightly above or below the input element, the input element will lose focus again. 

I would be fine with the way it is now, just thought i'd let you know.

**Comment by varnastadeus** [comment]
@papaZuhl 1.0.4 should work as expected.
