### ISSUE TITLE
After update to 1.0.2 problems with getting the full object

### ISSUE THREAD

**Issue by xigolle** [ng-select/ng-select#469]
Please fill below information if issuing a bug report. 
### Expected behaviour
Getting the full object in let-item="item" 

### Actual behaviour
I only get the value inside let-item="item"

I used this code with version 1.0.-.rc.0  and this worked great. But now I only get the value of the object where I am working with. 

My object looks like:
export interface Translation {
  value: string;
  label: string;
}

Not sure if maybe that is the problem? That first the object will be checked and then bindValue? 

<ng-select [ngClass]="'ng-select-searchable'" #citiesSelected [items]="citiesFiltered"
                   [clearable]="false"
                   [searchable]="false"
                   id="cities-select"
                   bindLabel="label"
                   (open)="customCitiesFilter('')"
                   (close)="citiesFiltered = cities"
                   formControlName="city"
                    placeholder="City" [(ngModel)]="selectedCity">
          <ng-template ng-label-tmp let-item="item">
            <span *ngIf="item.label; then label else placeholder"></span>
            <ng-template #placeholder><span class="placeholder">{{'personalinfo.updateaddress.placeholderZipcodeAndCity.Text' | translate}}</span></ng-template>
            <ng-template #label><span>{{item.label}}</span></ng-template>
          </ng-template>
### More Info
ng-select version: 1.0.3 and tested with 1.0.2

browser: Chrome

reproducible in demo page: Yes
https://stackblitz.com/edit/ng-select-example-cfnmdg

**Comment by varnastadeus** [comment]
@xigolle it can't be, since `let-item` was binding to value long time before version 1.0.0. There is also `let-label=label` which exposes inner label.

**Comment by mokey1** [comment]
i have same issue (after update to latest version of ng-select)

**Comment by varnastadeus** [comment]
@xigolle @mokey1 I will release new version soon with the fix.

**Comment by xigolle** [comment]
Alright great! Thanks for looking into it and awaiting the release :)

**Comment by varnastadeus** [comment]
Check 1.0.4 and let me know if it helped :)

**Comment by xigolle** [comment]
@varnastadeus Yes that worked for that problem but it created another one. 
I updated my example with an ng-template:
https://stackblitz.com/edit/ng-select-example-cfnmdg

When I click the input in the ng-template it closes the dropdown. Prior to 1.0.4 this wasn't the case. 
(Tested this by bumping the version and seeing this behaviour). 

Is there a solution for this problem? 
Maybe linked to this issue #467  ?

**Comment by xigolle** [comment]
@varnastadeus Just checked on the demo page under [Templates](https://ng-select.github.io/ng-select#/templates) and there is the same behaviour.

**Comment by varnastadeus** [comment]
@xigolle the example in demo is not valid since you have to handle all the cases yourself, I am working on feature where you could set `searchPosition = 'inline' | 'dropdown';`

**Comment by cupceavictor** [comment]
Got the same problem, the bug reproduces only if the object contains 'value' property.
created a issue and a plunker  [#477](https://github.com/ng-select/ng-select/issues/477)

**Comment by xigolle** [comment]
@varnastadeus Alright great, because if I now update to 1.0.5 it isn't possible anymore to select the input field in the ng-template. 
Do you have an estimate when this could be implemented ?

Thanks in advance for looking into it.

**Comment by varnastadeus** [comment]
@xigolle there is PR already, #478 which will allow to set `searchPosition` inline or dropdown, but I think we won't support custom input as a search control since as I mentioned before you need to handle all the cases like keyboard navigation, blur etc.

**Comment by xigolle** [comment]
@varnastadeus I can understand but it is so strange that is was working with version 1.0.2. So clicking on the custom input field worked and also when you lost focus it closes properly. The only problem there whas that the object wasn't being passed correctly. And off course I could always put `(blur)="ngSelect.close()"`  on the input itself.

**Comment by varnastadeus** [comment]
@xigolle we decided to not to rush with #478 and keep things as they were before. 
with #485 it will work as before.

**Comment by xigolle** [comment]
@varnastadeus Great! That is exactly what I needed everything is working like expected. Thanks for the great response and help! also thanks to @anjmao !
