### ISSUE TITLE
Wrong options position inside class text-center

### ISSUE THREAD

**Issue by d4rkc0de** [ng-select/ng-select#471]
Options position is wrong when using ng-select unser a div with class  'text-center'

```
<div class="col-md-3 text-center">
    <ng-select [items]="clinets"
               placeholder="azer"
               [(ngModel)]="analysisSearch.clientLabel">
    </ng-select>
</div>
```
https://b.top4top.net/p_838ifati1.png

### More Info
ng-select version: [1.0.3]

browser: [Google Chrome Version 65.0.3325.181]

**Comment by xonuzofa** [comment]
Add this css:

.ng-dropdown-panel {
  left: 0px;
}

**Comment by d4rkc0de** [comment]
@xonuzofa Thanks for your reply, but that only worked after changing the default.theme.css, I don't want to change it, and it didn't work inside my css file associated to that html.

**Comment by xonuzofa** [comment]
Change it in your program main.scss or whatever your main program css file is.  I wouldn't recommend changing it in the default style, if you upgrade the package you will lose it.

**Comment by d4rkc0de** [comment]
Thank you very much, fixed.
