### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by IslamEldeeb** [ng-select/ng-select#473]
Hello , when install the npm on my application and then put it on import (app.module.ts) , and run application display the following error : 
=========================================
". / ~ / @ng-select/ng-select/esm5/ng-select.js
Module not found: Error: Can't resolve 'rxjs/operators' in 'E:\app\node_modules\@ng-select\ng-select\esm5'
 @ ./~/@ng-select/ng-select/esm5/ng-select.js 5:0-54
 @ ./ClientApp/app/app.module.ts
 @ ./ClientApp/boot-client.ts
 @ multi event-source-polyfill webpack-hot-middleware/client?path=%2F__webpack_hmr ./ClientApp/boot-client.ts
==========================================
**## My angular ver. 4.2.5
"@ng-select/ng-select" ver. "^1.0.4",
can you help me ?**

**Comment by anjmao** [comment]
Hi @IslamEldeeb, you need to install newer rxjs version which has operators package then it should work fine.

**Comment by varnastadeus** [comment]
And update angular version to 5+.
