### ISSUE TITLE
selectOnTab should also complete the tab functionality (move focus to next item)

### ISSUE THREAD

**Issue by carpeVideo** [ng-select/ng-select#475]
### Expected behaviour
When select on tab is true , tab should select probably select and tab to the next item

### Actual behaviour
tab does select but focus remains on the original ng-select (or on the input div in the ng-select)

### More Info
ng-select version: 1.03

browser: chrome Version 65.0.3325.181 (Official Build) (64-bit)

**Comment by varnastadeus** [comment]
#370 here are the reasoning for this behaviour.
