### ISSUE TITLE
Feature Request: Allow ng-dropdown panel option to grow larger than parent

### ISSUE THREAD

**Issue by carpeVideo** [ng-select/ng-select#476]
### Expected behaviour
Allow the dropdown panel width for the options to grow larger than the parent for long items

### Actual behaviour
Dropdown panel width limited to the size of the parent

### More Info
ng-select version:1.0.3

I can allow this by changing the ng-dropdown-panel.component line  363:
```
        //from: dropdownPanel.style.width = selectRect.width + 'px';
		dropdownPanel.style.width = 'auto';
        dropdownPanel.style.minWidth = selectRect.width + 'px';
```

perhaps it makes sense to make this an option.

![image](https://user-images.githubusercontent.com/2836470/38940330-77ded922-42ef-11e8-9f2a-ce8ab9aa20b0.png)

**Comment by varnastadeus** [comment]
just use css

**Comment by carpeVideo** [comment]
You can't just use CSS because the minimum size is calculated in the code.  So while I can over-ride and set the width to auto CSS can not know the minimum size to set.  So what happens is if an ng-select has text that is smaller than the parent the panel becomes small than the parent which looks terrible.

**Comment by varnastadeus** [comment]
I am not following you. Why `.dropdown-panel:width 200px important` won't work?

**Comment by carpeVideo** [comment]
It only works if you you know the width of the dropdown parent and you do a .dropdown-panel:width for each dropdown.  As it happens in one of my applications we have 20-30 different (user) sized dropdowns, so letting ng-dropdown style it natively with min-width and using 1 single class with a width of "auto" makes more sense.  Also, using important should be avoided if possible.  I guess we can handle it either way, but by changing 1 word in the code it adds a nice option for ng-select users and does not impact backwards compatibility at all (I think :0)

Thanks,

**Comment by varnastadeus** [comment]
Ok I see what you mean and from custom styling it makes more sense to have `min-width` instead of `width`. I will check if it works correctly and do the change. Thanks for suggestion.

**Comment by varnastadeus** [comment]
I reverted this change since having very long label, there is no way to apply overflow hidden.
<img width="1243" alt="screen shot 2018-04-24 at 15 44 59" src="https://user-images.githubusercontent.com/17824796/39187631-7ef55dee-47d6-11e8-903b-07527fbd15e7.png">

**Comment by carpeVideo** [comment]
I agree - I was going to write that you added an extra line in the change, I think if you only change:
       dropdownPanel.style.width = selectRect.width + 'px';
to both:
         dropdownPanel.style.width = selectRect.width + 'px';
        dropdownPanel.style.minWidth = selectRect.width + 'px';

(instead of dropdownPanel.style.width = auto), then normal behavior applies and people who want the the larger dropdown panels can override the width behavior with CSS.  I think this keeps the behavior  the same for anyone who does not over-ride the width panel.  So essentially if you just add the minWidth I think everyone is happy.

Thanks,

**Comment by varnastadeus** [comment]
Agree, I added the change

**Comment by pgambino** [comment]
Ok.. So I'm struggling with this with Angular 6 and the latest version.  

![image](https://user-images.githubusercontent.com/8271417/46413265-8cb52d00-c6ee-11e8-8078-9b11c9304db9.png)

You can see how I get the ellipsis and it's cut off. Is there an attribute as part of the API to allow the dropdown panel to expand, a specific CSS directive to add?  Or do I have to pull source and mess with the code to get it to work?

**Comment by varnastadeus** [comment]
just override with `width: auto !important;` or your desired with

**Comment by pgambino** [comment]
I think the issue is I need it spelled out where to put that.  I tried in a CSS for .ng-select,I tried in the local style attribute.  What place am I missing?

**Comment by SergeyCherman** [comment]
This works fine when virtual scroll is false, but when setting `[virtualScroll]="true"` then width: auto doesn't work.

**Comment by R1cs1KING** [comment]
I followed the suggestions on this link: [https://stackoverflow.com/questions/50137172/angular-5-ng-select](url).
And made changes in my styles.scss like this:
`.ng-dropdown-panel {
        width: auto !important;
        max-width: 550px;
        min-width: 100%;
    }`

**Comment by metallidevils** [comment]
This doesn't work in 3.5

**Comment by CostinGabriel** [comment]
> This works fine when virtual scroll is false, but when setting `[virtualScroll]="true"` then width: auto doesn't work.

You saved me a lot of time

**Comment by carlosrc** [comment]
> This works fine when virtual scroll is false, but when setting `[virtualScroll]="true"` then width: auto doesn't work.

Anyone found a fix when [virtualScroll]="true"? 
@SergeyCherman @CostinGabriel ?

Thanks.

**Comment by slavede** [comment]
What in case ng-select is appended to body. This solution won't work unfortunately :( Any ideas for that case?

**Comment by slavede** [comment]
> I found a way to do it. In the "appendTo" input, add the parent class:
> 
> .some-parent-container { position: relative; } .ng-dropdown-panel { width: 100%; }
> 
> ![image](https://user-images.githubusercontent.com/16621122/210730715-2145139a-4339-45f6-b26f-911dfc5f3eb0.png)

it won't work in case it's appended to body
