### ISSUE TITLE
NgSelect working incorrect if object from an array of data contains 'value' property

### ISSUE THREAD

**Issue by cupceavictor** [ng-select/ng-select#477]
Please fill below information if issuing a bug report. 
### Expected behaviour
NgSelect functionality shouldn't depend on input data.

### Actual behaviour
If input data is an array of objects and every object contains 'value' property, component will not display anything.

### More Info
ng-select version: 1.0.3

browser: chrome

reproducible in demo page: YES
https://plnkr.co/edit/YQWGr0LWKYa4lyvaV9EK?p=preview

**Comment by varnastadeus** [comment]
this issue is already fixed.
