### ISSUE TITLE
[items]="someFunction()" Horrible Performance

### ISSUE THREAD

**Issue by xonuzofa** [ng-select/ng-select#480]
Using a function to gather the items in [items] has horrible performance.

**Comment by xonuzofa** [comment]
Fixed with PR #482

**Comment by anjmao** [comment]
Hi @xonuzofa 
Passing function call to input is not allowed in general, because you are executing it on every change detection cycle. Just pass array instead of function.

**Comment by xonuzofa** [comment]
I agree thanks.
