### ISSUE TITLE
Select object by id and display it by name

### ISSUE THREAD

**Issue by stoto34** [ng-select/ng-select#484]
Please fill below information if issuing a bug report. 
### Expected behaviour

I use bindLabel to display a property of my object but when the label is the same as another one (the object is not the same, there is just a different value in special property) in my list, the ng-select select the bad object (it's random).  Is it possible to select object by id and display by it name ? I tried to use bindValue, but it doesn't work.

By the way, the problem happens when I remove on element on my ng-select. My list has 27 elements when I'm on the ngOnInit and when I remove just one element, I've 18 elements left

Here the settings of my ng-select :

` <ng-select [items]="listItems"
                                        bindLabel="designation"
                                        [virtualScroll]="true"
                                        (scrollToEnd)="fetchMoreItems()"
                                        [closeOnSelect]="false"
                                        [loading]="loadingItems"
                                        dropdownPosition="top"
                                        placeholder="placeholder"
                                        [multiple]="true"
                                        [typeahead]="typeahead"
                                        [(ngModel)]="currentItems"
                                        [ngModelOptions]="{standalone: true}">
                                        <ng-template *ngIf="loadingProducts" ng-footer-tmp>
                                            <small class="form-text text-muted">loading...</small>
                                        </ng-template>
                                    </ng-select>
`

**Comment by varnastadeus** [comment]
@stoto34 `ng-select` tries to select by value is `bindValue` is defined or by reference if it isn't. If it doesn't finds any matching items it tries to select by 'bindLabel'. If this default behaviour doesn't fits your use case you could provide custom `compareWith` to define on which properties it should check while searching.

**Comment by stoto34** [comment]
It works :) thank very much for your help and this very useful package !
