### ISSUE TITLE
NgDropdownPanelComponent Memory leak !

### ISSUE THREAD

**Issue by caoduy1293** [ng-select/ng-select#493]
I have 2 modules (module A,B) and these modules is applied lazy loading, 
Module A I created Component: A1 I make a form using ng-select.
Module B I created Component: B1 make a list items clickable through click event , 
In Component A1 I click dropdown in ng-select component and choose something and dropdown panel is showed. I come to Component B1 click event of items inside this component  wont work anymore.
### Expected behaviour
click event of items inside Component B1  will work normally 

### Actual behaviour
click event of items inside Component B1 wont work anymore.

### More Info
ng-select version: v1.0.0

browser: Chrome v66.0.3359.117

**Comment by varnastadeus** [comment]
@caoduy1293 please create reproducible stackblitz

**Comment by caoduy1293** [comment]
I really sorry about this. I firgured out issues, it's my own code not your component. So I will close it . Thanks so much.
