### ISSUE TITLE
Focus on input from ng-template not working

### ISSUE THREAD

**Issue by xigolle** [ng-select/ng-select#494]
Please fill below information if issuing a bug report. 
### Expected behaviour
When clicking open the dropdown it should focus the inner dropdown of the ng-template

### Actual behaviour
It is not focussing the input element and only the parent element

### More Info

As you can see in the stackblitz i am using the default autofocus & a custom directive to force the focus to that but none if them are working. 
Is there anyway that this is possible?

ng-select version: 1.1.1

browser: Chrome

reproducible in demo page: YES
https://stackblitz.com/edit/ng-select-example-cfnmdg

Hope you can help me out! 😄

**Comment by varnastadeus** [comment]
@xigolle just wrap your ngAfterViewInit to timeout, eg.
```
ngAfterViewInit(): void {
  setTimeout(() => {
    this.el.nativeElement.focus()
  }, 10)
}
```

**Comment by xigolle** [comment]
@varnastadeus Thanks so much that worked like a charm! Do you maybe know why this needs to happen? 
Or is it just because ngAfterViewInit gets called before the actual template gets rendered? 

Thanks in advance for maybe explaining why this is the solution.

**Comment by varnastadeus** [comment]
It happens because ng-select has it own focus event. From this code, you can see that it blurs immediately after it was focused.

```javascript
@HostListener('blur') onBlur() {
  console.log('onblur')
}

@HostListener('focus') onFocus() {
  console.log('onfocus')
}

ngAfterViewInit(): void {
  this.el.nativeElement.focus();
}
```
