### ISSUE TITLE
select text on focus / on click

### ISSUE THREAD

**Issue by nkachroo** [ng-select/ng-select#495]
**Expected behaviour** 
If the ng-select drop list already has a value set and if we click (a.k.a focus) on the value, it would be better if the text value is either selected or the cursor is set to the end of the text value. This enables the user to use backspace and correct / replace the text ... having the text pre-selected upon click gives users a sense that they can start typing and that the selected text will go away.  

**Actual behaviour**
Currently in version 1.1.0, when we click on the ng-select component, the cursor is set to the start of the text. The text is not selected. 

If a user wishes to change the text, they can start typing the new text, which clears out the old text, which is good... but this behavior is not intuitive and is a bit confusing to users, given that majority of search implementations either select the text or point the cursor to the end. 

We could use '[clearable]' = true, but with that, the entire text is cleared out, not just the text that the user wants cleared out. 

To achieve selecting the text on click, I tried using "(focus)" event output and calling 'select() on the component, just like 'select()' works on a regular text-input. But, "(focus)" event output doesn't give me a handle on the component that I could call the 'select()' on. You can refer to the plunk for what I was trying to do. 

Would be great to have this as an enhancement. 

**More Info**
ng-select version: 1.1.0

browser: Chrome, Firefox

reproducible in demo page: Yes @ https://plnkr.co/edit/2woausdCYod448JzX3Sz?

Thanks,
NK

**Comment by anjmao** [comment]
Hi @nkachroo,
In most cases when filtering I want to type new value and if cursor will appear at the end I will need to select and delete current text which is not good. Another option is to select and focus whole text but it looks ugly. This is why this option was chosen.

In current implementation input has absolute position and it could be complicated to implement this, but if you could look at possible solutions I would be happy to accept PR.

**Comment by varnastadeus** [comment]
I am closing this since text in the control represents selected item and has nothing to do with the search term so having it selected or cursor at the end makes little sense.

**Comment by nikhilrajnair** [comment]
is there any option to position the cursor at end of the text after selecting one ?

**Comment by nkachroo** [comment]
No, not that I recall (in the version I looked at, couple months ago).

**Comment by nikhilrajnair** [comment]
can i disable the cursor after selecting one item from the option ?

**Comment by nikhilrajnair** [comment]
Nobody gonna help me ?

**Comment by uzumakinaruto123** [comment]
@varnastadeus 

I think this is required. I use custom label template, which basically ic concatenation of multiple object keys.

If user decides to change the value, user will have to hit back spaces multiple number of times or would have to clear the value using button. which is not desirable.

It would be great if the text is selected on focus by default, so user can directly start typing.

It is easily possible in case of normal input element as follows:

```html
<input #autoComp (focus)="autoComp.select()"   placeholder="Search Category">
```
