### ISSUE TITLE
Change detection issue when the last item is deselected in multiselect mode

### ISSUE THREAD

**Issue by maxkorz** [ng-select/ng-select#496]
1. Go to https://ng-select.github.io/ng-select#/multiselect.
2. In "Hide selected elements" demo select all items.
3. Deselect any item.
4. **The dropdown should appear but it doesn't.**
5. Deselect one more item. **The dropdown will appear with two elements.**

Note: if `closeOnSelect` is `false` the issue is more obvious.

### More Info
ng-select version: 1.1.4
browser: Google Chrome
reproducible in demo page: Yes.

**Comment by anjmao** [comment]
@maxkorz Hi,
Thanks for reporting, good catch.

**Comment by varnastadeus** [comment]
@anjmao In this case I don't think it should open at all when unselecting items, and it worked that way before.
