### ISSUE TITLE
Bind with empty object cause empty selection

### ISSUE THREAD

**Issue by LuanMaik** [ng-select/ng-select#500]
When using an empty object in ngModel, it's hidding the 'placeholder' and appears the X icon to remove 
a empty selection.
Example:
```
this.country = {};

<ng-select [items]="countries" [(ngModel)]="country"></ng-select>
```
https://ibb.co/fY0SWx

Perhaps by validating with `Object.keys(obj).length` inside component to verify if is a empty object, would solve the "problem".

**Comment by varnastadeus** [comment]
@LuanMaik is there is any reason why you are using empty object and not null or undefined? Empty object is valid value.

**Comment by LuanMaik** [comment]
My contex involve a nested object:

```
this.pessoa = {
        address: {
              country: { }
        }
}
```
I can't define `country` like `null` because if i try to bind the country's name in other place, I will get a error "name is not defined in NULL".

I understood what you said, but a empty object is not a valid option in my conception, because there's no attribute. In this case, a valid option would be has attribute with empty value:
**invalid:** `country: { }`
**valid:** `country: { name: "" }` 

**Conclusion:** I think that a empty option it's the same thing that no option selected. My problem it's only in initialization of component, not in array options;

Please, tell me if I'm crazy.

**Comment by varnastadeus** [comment]
@LuanMaik you are doing it wrong, have you tried `pessoa.address?.country` ?
