### ISSUE TITLE
Is it angular4 compatible?

### ISSUE THREAD

**Issue by augustbend** [ng-select/ng-select#501]
Hi everyone,

I've been looking for a select component to use in my angular4 project and this seems to have everything I need. But in the github page it says it is a "Native angular 5+ select component". Is it angular4 compatible? 

Thanks

**Comment by h3kt0r** [comment]
Im using it with angular 4.3.3 dependencies.
The last compatible version of the lib

`    "@ng-select/ng-select": "0.18.0"`

**Comment by augustbend** [comment]
Hi Sir. So correct me if I'm wrong. You tried the version released after 0.18.0 and it stopped working?

**Comment by h3kt0r** [comment]
Im not really sure about what is the latest version that works correctly in angular4 but 0.36.0 > prints error when angular builds the proyect.

**Comment by varnastadeus** [comment]
Cmon guys, there are multiple issues regarding this question and there is no need to create another one. Just use search.

**Comment by anjmao** [comment]
dup of https://github.com/ng-select/ng-select/issues/402#issuecomment-377630566
