### ISSUE TITLE
Typeahead broken when http request fails

### ISSUE THREAD

**Issue by ShinDarth** [ng-select/ng-select#502]
I'm using filtering with typeahead and "Custom server-side search":

https://ng-select.github.io/ng-select#/filter

my code is pretty identical to the example.

Basically everything works fine, except that whenever a request fails (e.g. the item with that name is not found, returning 404) the ng-select stops triggering any search.

### Expected behaviour
Type the name of an object which does not exist. An http request will be triggered and it will fail (returning 404). Type another name, it should keep triggering http requests.

### Actual behaviour
Type the name of an object which does not exist. An http request will be triggered and it will fail (returning 404). Type another name, it sends no more requests.

### More Info
ng-select version: 1.2.1

browser: Chrome

reproducible in demo page: [NO]

**Comment by varnastadeus** [comment]
@ShinDarth as you can see in the example, you need to handle errors yourself.

**Comment by ShinDarth** [comment]
@varnastadeus in my case my API is returning ERROR when no objects are found. So for me it is enough to just set the items array to `[]` when it happens. The problem is that as soon as an http request fails with error, the `ng-select` stops triggering any new requests.

So what should I do? This is my pipe:

```
this.itemsTypeahead.pipe(
      tap(() => this.itemsLoading = true),
      distinctUntilChanged(),
      debounceTime(200),
      switchMap(term => this.itemService.getItem(term, { showError: false })),
    ).subscribe((data: Item) => {
      this.items = [data];
      this.itemsLoading = false;
      this.cd.markForCheck();
    }, () => {
      this.items = [];
      this.itemsLoading = false;
    });
```

**Comment by anjmao** [comment]
Hi @ShinDarth , in this case you need to use catch operator to continue. Now when error happens your typeahead is completed and does not emit new values any more.

```ts
this.itemsTypeahead.pipe(
      tap(() => this.itemsLoading = true),
      distinctUntilChanged(),
      debounceTime(200),
      switchMap(term => this.itemService.getItem(term)),
      catch(() => of([]))
    ).subscribe((data: Item) => {
      this.items = [data];
      this.itemsLoading = false;
      this.cd.markForCheck();
    }, () => {
      this.items = [];
      this.itemsLoading = false;
    });
```

**Comment by ShinDarth** [comment]
@anjmao thanks to your input, I've solved using:

```
this.itemsTypeahead.pipe(
      tap(() => this.itemsLoading = true),
      distinctUntilChanged(),
      debounceTime(200),
      switchMap(term => this.itemService.getItem(term).catch(() => of([])),
    ).subscribe((data: Item) => {
      this.items = [data];
      this.itemsLoading = false;
      this.cd.markForCheck();
    }, () => {
      this.items = [];
      this.itemsLoading = false;
    });
```
