### ISSUE TITLE
Installation ng-select in Angular v5

### ISSUE THREAD

**Issue by AhmedHadjTaieb** [ng-select/ng-select#503]
### Actual behaviour
When I run 'ng serve' after integrated NgSelectModule in app.module the console output errors:

ERROR in ./src/app/home-page/door/door.module.ts
Module not found: Error: Can't resolve '@ng-select/ng-select' in '/home/access-control-fo-angular/src/app/home-page/door'
resolve '@ng-select/ng-select' in '/home/access-control-fo-angular/src/app/home-page/door'
  Parsed request is a module
  using description file: /home/access-control-fo-angular/package.json (relative path: ./src/app/home-page/door)
    Field 'browser' doesn't contain a valid alias configuration
.
.
.
 @ ./src/app/home-page/door/door.module.ts 21:0-54
 @ ./src/$$_lazy_route_resource lazy
 @ ./node_modules/@angular/core/esm5/core.js
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

ERROR in ./src/app/home-page/door/door.module.ts
Module not found: Error: Can't resolve '@ng-select/ng-select' in '/home/access-control-fo-angular/src/app/home-page/door'
resolve '@ng-select/ng-select' in '/home/access-control-fo-angular/src/app/home-page/door'
  Parsed request is a module
  using description file: /home/access-control-fo-angular/package.json (relative path: ./src/app/home-page/door)
    Field 'browser' doesn't contain a valid alias configuration
.
.
.
 @ ./src/app/home-page/door/door.module.ts 21:0-54
 @ ./src/$$_lazy_route_resource lazy
 @ ./node_modules/@angular/core/esm5/core.js
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

### More Info
ng-select version: v1.3.0
@angular/common: "^5.0.1",
@angular/compiler: "^5.0.1",
@angular/core: "^5.0.1",
@angular/forms: "^5.0.1",
rxjs: "^5.5.2",
zone.js: "^0.8.18"

browser: Chrome

reproducible in demo page: NO

**Comment by varnastadeus** [comment]
@AhmedHadjTaieb I have tried to include `ng-select` in cli project and it works without any errors. There is probably mistake in your setup rather than `ng-select` itself. How are you importing it?

**Comment by AhmedHadjTaieb** [comment]
@varnastadeus I have also used cli project so I had run the command line and after that I imported NgSelectModule inside the app.module.ts but didn't work so I tried to import in child module when I used the FormsModule but the same error output

**Comment by AhmedHadjTaieb** [comment]
@varnastadeus I think I found the problem:
At the first time when I included the NgSelectModule the project was deployed and run in container docker and the error output in console, but now I try to run the project in local without docker and I don't find any error in the output console it's running perfectly. The problem, it was related with deployed the project in container docker.. But the solution not found

**Comment by AhmedHadjTaieb** [comment]
I Solve the problem, It was my error because I exclude node_modules in the docker-file and I had forgotten to run npm install in container docker after added the plugin.
Sorry for the issue
