### ISSUE TITLE
[Solved] Pass a multiple Object in FormControl and addTags

### ISSUE THREAD

**Issue by Reuno92** [ng-select/ng-select#505]
Hi everyone, I need your assistance.

### Expected behaviour
I search to pass my array in custom ng-select component and display my Objects.

### Actual behaviour
I'm sure the problem comes from my screen and my chair. I don't understand what's wrong. 
An example from [StackBlitz](https://stackblitz.com/edit/ng-select-example-fvyw4p?file=app/app.component.ts).

I'm try to read [this](https://github.com/ng-select/ng-select/issues/462).

Someone can help me understand what's wrong.
Thanks in advance.

### More Info
ng-select version: 1.3.0
browser: Firefox 59
reproducible in demo page: YES

**Comment by varnastadeus** [comment]
@Reuno92 don't use bindValue if you are passing objects

**Comment by Reuno92** [comment]
Hello, thank you for your response. I've solved my error.
I've been pass my httpRequest directly in my form build.

I share for other people when they have the same problem.

Like that :
``` 
this.formBuilderVariable.controls.myFormControl.setValue(myDatas)
```
