### ISSUE TITLE
Unicode / Character References displaying in ng-option

### ISSUE THREAD

**Issue by stoconnor** [ng-select/ng-select#506]
### Expected behaviour
Unicode / Character References are not displayed in ng-option

### Actual behaviour
Unicode / Character Reference displaying in ng-option

### More Info
ng-select version: 1,3.0
browser: Chrome Version 65.0.3325.181 (Official Build) (32-bit)
reproducible in demo page: NO

`<ng-select placeholder="Please select a Category" (change)="toggleCategories($event)">
  <ng-option  *ngFor="let i of cat_group" [value]="i.id" >{{ i.name }}</ng-option>
</ng-select>`

Results from `console.log(this.cat_group);`
{id: 6, name: "House & Home", category_type: "XX"}
{id: 8, name: "Lifestyle & Tourism", category_type: "YY"}
{id: 4, name: "cat & cat", category_type: "ZZ"}

I was using checkboxes up to now, and moving to a dropdown list so trying out ng-select.

![image](https://user-images.githubusercontent.com/4786068/39401033-22e8e73a-4b34-11e8-8d91-cb99959943f3.png)

Any ideas?

**Comment by zealmurali** [comment]
We are also having the same issue... Can you please check this ?

**Comment by varnastadeus** [comment]
It is disabled for now to prevent XSS, you can add `ng-option-tmp` as temporary fix or use `[items]` instead.

**Comment by ek-marneau** [comment]
Hi, we are also having the same issue. We have been trying `ng-option-tmp` and  `[items]` but none of them seem to work. 

```
<ng-select
  [items]="items"
  [multiple]="true"
  bindLabel="name"
  [virtualScroll]="true"
  [(ngModel)]="selected"
>
  <ng-template ng-label-tmp let-item="item" let-clear="clear">
    <span class="ng-value-label">{{ item.name }}</span>
    <span class="ng-value-icon right" (click)="clear(item)" aria-hidden="true">×</span>
  </ng-template>

  <ng-template ng-option-tmp let-item="item">
    {{ item.name }}
  </ng-template>
</ng-select>
```

with `items` being : 
```
items = [
{name: "hello"},
{name: "it's me"}
]
```

Any solution ?

**Comment by tofurama3000** [comment]
We're in the same boat as ek-marneau. We're unable to display ampersands; it renders as `&amp;` instead.

**Comment by taiducnguyen** [comment]
Hi @varnastadeus , Have any fixing for this issue?

**Comment by ElangoAS** [comment]
Hi All,

It look like, work around not working and i am facing same issue.  Any fixes done or how it can be handled temporarily ( work around solution).

**Comment by andreypelykh** [comment]
@ElangoAS This solution worked for me:
```html
<ng-select placeholder="Please select a Category" (change)="toggleCategories($event)" bindValue="id">
    <ng-template ng-label-tmp let-item="item">
        {{item.name}}
    </ng-template>
</ng-select>
```

**Comment by MeetRishabh03** [comment]
Any work around for the above issue? 
I have ng-select and I am iterating through items
