### ISSUE TITLE
Dropdown options list not showing inside popup model

### ISSUE THREAD

**Issue by nashy18** [ng-select/ng-select#507]
Please fill below information if issuing a bug report. 
### Expected behavior
It show show the dropdown options list

### Actual behaviour
Dropdown options list not showing inside popup model. 

### More Info
ng-select version: 1.3.0

browser: Chrome

reproducible in demo page: Not Availbale
![image](https://user-images.githubusercontent.com/16122223/39406631-25151922-4bd7-11e8-966d-94264c09be89.png)

**Comment by varnastadeus** [comment]
@nashy18 have you tried append to body?

**Comment by nashy18** [comment]
Yes, already added that attribute

**Comment by varnastadeus** [comment]
https://ng-select.github.io/ng-select#/forms there is button `open in modal`

**Comment by varnastadeus** [comment]
I am closing this. If you still have any problems please create new issue with reproducible example.

**Comment by mirko1075** [comment]
> https://ng-select.github.io/ng-select#/forms there is button `open in modal`

Which doesn't work on that page either

**Comment by ekalavyaa** [comment]
we ran into the same issue. append to the body fixed the problem for me.
`appendTo="body"`

**Comment by ElvinaTva** [comment]
In the ts-component:

  constructor(
    private ngSelectConfig: NgSelectConfig,
  ) {
    this.ngSelectConfig.appendTo = '';
}
