### ISSUE TITLE
Pressing enter should open the dropdown when ng-select is focused

### ISSUE THREAD

**Issue by SandeepThomas** [ng-select/ng-select#508]
### Expected behaviour
Pressing the enter key when ng-select is focused should open the dropdown if its closed like native select.

### Actual behaviour
Pressing the enter key when ng-select is focused does nothing if its closed.

### More Info
ng-select version: 1.3.0

browser: Chrome

reproducible in demo page: YES

**Comment by varnastadeus** [comment]
@SandeepThomas it only opens on windows so this behaviour isn't consistent among other OS's

**Comment by SandeepThomas** [comment]
@varnastadeus yes, but is it possible open the dropdown on enter key if its closed?

**Comment by varnastadeus** [comment]
ofcourse it is, but you need to handle it yourself.

**Comment by SandeepThomas** [comment]
can you please guide on how to achieve that? i tried attaching a keyup event listener to open the dropdown  if its closed, but that opens the dropdown after selecting a value also.

**Comment by varnastadeus** [comment]
@SandeepThomas 
```html
<ng-select [items]="people$ | async"
    bindLabel="name"
    #select 
    bindValue="id"
    (keydown.enter)="$event.stopImmediatePropagation(); select.toggle()"
    [(ngModel)]="selectedPersonId">
</ng-select>
```

here is idea, ideally if select is open you need to to do nothing and if it is closed call `open` method.

**Comment by SandeepThomas** [comment]
Thanks, will try that tomorrow and post here the result.

**Comment by varnastadeus** [comment]
Also we will consider making it as a feature.

**Comment by varnastadeus** [comment]
@SandeepThomas I made change ir our codebase.

**Comment by SandeepThomas** [comment]
Oh, I see. Thanks buddy :+1:

**Comment by SandeepThomas** [comment]
@varnastadeus i tried it in my project, but its triggering search while pressing enter!

**Comment by varnastadeus** [comment]
can you add reproducible example? I don't see it happen in demo page.

**Comment by SandeepThomas** [comment]
@varnastadeus you can see my issue here: https://stackblitz.com/edit/ng-select-example-jl5swq

Am changing the focus to another input on dropdown value change, but its triggering the keydown.enter in the new input.

My use case involves a Phone Number input with ng-select to select country code and an input field to enter mobile number. So when a user selects a country code, i need to set focus automatically on the number field so that user can just enter the number and press enter to submit the form.

**Comment by varnastadeus** [comment]
use `(keydown.enter)`. While focusing to input, input still catches keyup event and triggers your logic. Or you could use timeout.

**Comment by dreamid27** [comment]
@varnastadeus Love your support, thank buddy. 

this is why i'm use ng-select !

**Comment by peca021** [comment]
I have updated angular from version 7 to 8 and now the stopImmediatePropagation() method on (keydown.enter) event is not working anymore. :/

Does anybody know how to prevent selecting the marked option on the enter key if the select's dropdown is closed?

In my project I use:
Angular: 8.2.14
Typescript: 3.7.3
ng-select: 3.7.0

Thanks in advance!

**Comment by peca021** [comment]
@varnastadeus, @dreamid27, @SandeepThomas guys can anybody help me?
