### ISSUE TITLE
Dropdown list not changing position when values are changed

### ISSUE THREAD

**Issue by Gillardo** [ng-select/ng-select#510]
Please fill below information if issuing a bug report. 

### Expected behaviour
Open dropdown, go to say item 20, and click on it, you will see the list refreshes, but stays at the same position, i would expect to go to the top of the list once the items are changed.

### Actual behaviour
I have a ng-select dropdown, and upon selecting 1 item, i refresh the list of items available and a user can select another one.  This all works perfectly fine, as i bind the list to a new array each time.  My problem is that if the user scrolls part way down the list, upon selecting an item, the new array is bound to the dropdown, but the list stays in the same position, it doesnt go to the top of the list.

### More Info
ng-select version: 1.3.0
browser: chrome 66.0.3359.139, firefox 59.0.3
reproducible in demo page: No

Example here: https://ng-select-5ct8bc.stackblitz.io

**Comment by varnastadeus** [comment]
@Gillardo why do you expect it should change position?

**Comment by Gillardo** [comment]
Because i have changed the values within the list.  You wouldnt start a book half way through, so why would you start a new list of items half way through?
