### ISSUE TITLE
Dropdown opening on removing an item

### ISSUE THREAD

**Issue by ShinDarth** [ng-select/ng-select#511]
Since I've upgraded to version 1.x whenever I remove an item from the multiselect, the dropdown will open.

This change of behaviour is breaking our automated tests, so I was wondering if there's a way to prevent this and switch back to the old behaviour where the dropdown does NOT open when you simply remove an item from the selection.

**Comment by varnastadeus** [comment]
@ShinDarth it should be fixed in latest version

**Comment by ShinDarth** [comment]
alright, I've updated to version 1.4.0 and it works fine. Thank you very much!
