### ISSUE TITLE
Closing dropdown does not always work as opening it

### ISSUE THREAD

**Issue by ShinDarth** [ng-select/ng-select#512]
### Expected behaviour
Every time you click on the toggle dropdown area it should open/close the dropdown

### Actual behaviour
There are some areas where the mouse cursor becomes a pointer and opening the dropdown always work. However closing it does not always work in that very same area.

To reproduce it just try to click many times on the dropdown toggle on the right, trying to slightly move the cursor.

You can actually reproduce it in the home page:

https://ng-select.github.io/ng-select#/data-sources

![image](https://user-images.githubusercontent.com/75517/39474893-513f06cc-4d56-11e8-8b38-6caf6a65dbca.png)

### More Info
ng-select version: 1.4.0

browser: Chrome

reproducible in demo page: YES

**Comment by SandeepThomas** [comment]
Looks like close action is attached to .ng-arrow instead of .ng-arrow-wrapper

**Comment by varnastadeus** [comment]
@ShinDarth I don't understand the issue, you need to click exactly on icon to toggle it.

**Comment by SandeepThomas** [comment]
@varnastadeus thats correct, but it would be nice if the clickable area is a little more larger to allow for easy clicking.

**Comment by varnastadeus** [comment]
then you will toggle on blank space which makes no sense, I am closing this as I don't see actual issue here.

**Comment by ShinDarth** [comment]
@varnastadeus the exact icon works fine, but there are areas where the expand works but not the collapse.. it looks a bit inconsistent

**Comment by tzoratto** [comment]
+1, sometimes collapsing the list takes you 3 or 4 tries because of the tiny clickable arrow. Of course one can click outside of the component to close the list easily but it's kind of disturbing when you opened it by clicking just next to the arrow in the first place

**Comment by earshinov** [comment]
+1 The current behavior is inconsisent and not user-friendly.

It also does not seem to match the common practice. Take virtually any combobox component and it will toggle its dropdown when the input itself is clicked. Just for instance, https://getbootstrap.com/docs/4.0/components/forms/.

 @varnastadeus, please reconsider.
