### ISSUE TITLE
Programatically trigger a search

### ISSUE THREAD

**Issue by augustbend** [ng-select/ng-select#515]
Hi.

Is there a way to trigger a search without the user interacting with the component? How can this be implemented?? I was thinking about using @ViewChild to get the instance of the ngx-select-ex and then pass a value to the search field.  But how do I tell the component that there is a new value in the input field? Is it possible or are there any other ways much more straightforward??

**Comment by varnastadeus** [comment]
it is not ngx-select-ex, wrong repo.
