### ISSUE TITLE
bindValue as global config

### ISSUE THREAD

**Issue by Poitrin** [ng-select/ng-select#516]
Let's say, every object in the `[items]` array has the same structure (e.g. `{label: "...", value: "..."}`) and I want to send the `value` property (i.e. not the whole object) to my backend, I need to configure the `bindValue="value"` for each select.

It would be nice to have the bindValue property globally configurable (and included in the NgSelectConfig interface).

**Comment by agil-NUBBA** [comment]
Comming from another library, that uses exactly that interface. Is not that hard to place `bindValue="value"` at every `ng-select`, but it would had been very helpful.
