### ISSUE TITLE
Min Chars before starting a search

### ISSUE THREAD

**Issue by eriveraa** [ng-select/ng-select#517]
Thanks for this incredible control for angular.
Is it possible to indicate the minimum characters to type before starting a search? (in case of Server side filtering)
Thanks for your response.

### More Info
ng-select version: [1.4.0]
browser: [Chrome]

**Comment by varnastadeus** [comment]
just use filter operator

```javascript
filter(t => t && t.length > 3)
```

**Comment by eriveraa** [comment]
Thanks so much it works!. If something need, this is my code:
``
  // Obtener la data para los combos y elementos de la UI del filtrado
  getIntegrantesData() {
    console.log('Entrando a getIntegrantesData');
    this.integrante1Typeahead.pipe(
      filter(t => t && t.length > 2), // Esto permite que el texto a buscar tenga 3 caracteres como mínimo
      tap(() => this.integrante1Loading = true),
      distinctUntilChanged(),
      debounceTime(450),
      switchMap(term => this.http.get('http://localhost:3000/rep-expedientes/integrantesearch?term=' + term)
        .map(retObject => {
          console.log('Response: (getIntegrantes1Data)', retObject);
          return retObject.json();
          })),
    ).subscribe(x => {
      this.integrante1Items = x.Data;
      this.integrante1Loading = false;
      this.cd.markForCheck();
    }, () => {
        this.integrante1Items = [];
    });
