### ISSUE TITLE
Feature request: multiple selection enable/disable

### ISSUE THREAD

**Issue by MarcoFiusco** [ng-select/ng-select#518]
Hi, 

I already use and appreciate your work and wish to still use it in multiple selection mode. 

Thank you,
Marco

**Comment by varnastadeus** [comment]
@MarcoFiusco what do you mean by multiple selection?

**Comment by MarcoFiusco** [comment]
What I really wanted to know is weather or not you already provided a way to inject the "form-control" class into the ng-select > ng-control as it's quite difficult to handle the class injection in a dynamic context.
