### ISSUE TITLE
option displa text got fliped by space

### ISSUE THREAD

**Issue by ruonan59** [ng-select/ng-select#519]
i have a list binding to a select, 
here is the list :    

 public static readonly advancedPaymentsDDItems = [
    { value: 2, name: '0' },
    { value: 3, name: '1 + 0' },
    { value: 5, name: '2 + 0' },
    { value: 6, name: '3 + 0' }
  ];
but while displayed on the front end 
it become to:
0
0 + 1
0 + 2
0 + 3
it works fine if i removed the space.
does anyone has the same issue? thanks

**Comment by varnastadeus** [comment]
<img width="896" alt="screen shot 2018-05-04 at 10 02 30" src="https://user-images.githubusercontent.com/17824796/39616082-5d5ebb04-4f82-11e8-931b-21478a10a8f8.png">
Not sure what are you talking about.
