### ISSUE TITLE
Is clearable compatible with custom template?

### ISSUE THREAD

**Issue by dpetersnews** [ng-select/ng-select#521]
When you have a selected option with a custom template, how does one still have the clear functionality as part of the item?

Example html
`
<ng-select [clearable]="true"
                   [items]="cities"
                   bindLabel="name"
                   [(ngModel)]="selectedCities"
                   multiple="true">
          <ng-template ng-label-tmp ng-option-tmp let-item="city">
            {{city.name}} - {{city.population}}
          </ng-template>
</ng-select>
`

The data model is simple enough:
`
let cities = [
  { "name": "Dublin", "population": 1000000 },
  { "name": "London", "population": 10000000 }
]
`

I'm wondering how would I be able to have the clear button as per the standard template part of this?

**Comment by varnastadeus** [comment]
Clearable is used to clear value itself, not separate items while having multiple selection.
