### ISSUE TITLE
Inject css form-control class into ng-select field

### ISSUE THREAD

**Issue by MarcoFiusco** [ng-select/ng-select#523]
Hi,
Did you already provided a way to inject the bootstrap "form-control" class into the ng-select > ng-control?
As it's quite difficult to handle the class injection in a dynamic context.

Thank you,
Marco Fiusco

**Comment by varnastadeus** [comment]
Why do you need it on ng-control? Now you could use ```ng-select class="form-control"```

**Comment by MarcoFiusco** [comment]
Because if you do this: <ng-select class="form-control"> it will just show a border around the selector as in the following image. And of course i don't need it, i'd like to apply the class the selector not the outer component. 
![form-control](https://user-images.githubusercontent.com/37865533/39663100-14a289b8-506d-11e8-9985-e852f2b1f6e3.PNG)

**Comment by varnastadeus** [comment]
Currently it is not possible and I doubt that it will be. I would suggest applying custom styles so the border would be on your desired element.

**Comment by MarcoFiusco** [comment]
Yeah, I'ts what I'll do.

**Comment by andrejm7** [comment]
@MarcoFiusco do you have the CSS to match the form-control of bootstrap 4.0?

**Comment by MarcoFiusco** [comment]
Hi,
at least I switched to an other plug in, sorry

**Comment by andrejm7** [comment]
@MarcoFiusco What plug?
