### ISSUE TITLE
Remove or disable an item of the list

### ISSUE THREAD

**Issue by stoto34** [ng-select/ng-select#525]
Please fill below information if issuing a bug report. 
### Expected behaviour

I don't know if it's an issue.

I'm using ng-select to display a list for single selection. When I select one item in my list and I click on a button to add the selected item to another list. From here, I want to remove or disable the selected item in my list (even if I search, scroll into this list, I don't want to be able to click on it again.).

I tried to remove the item by comparing the lists but the selected item is still displayed into the ng-select. How can I achieve this ?

Thank you :)

### Actual behaviour
Describe how it actually works or even better create example using [StackBlitz](https://stackblitz.com/edit/ng-select-example?file=app/app.component.ts) issue template

### More Info
ng-select version: 1.2.1

browser: [INSERT BROWSER INFO HERE]

reproducible in demo page: [YES/NO]

**Comment by varnastadeus** [comment]
Just set `disabled` property on the item, or remove it from the list and then rebind newly created array.

**Comment by varnastadeus** [comment]
here you go https://stackoverflow.com/questions/5767325/how-do-i-remove-a-particular-element-from-an-array-in-javascript

**Comment by stoto34** [comment]
Thank you very much for your help but it still doesn't work. I tried to splice selected element but my list still contains it.

`        if (this.applications.length > 0) { // the array with selected element when I click on a button after selected it into the list
            this.listApplication.forEach((item, index) => {
                if (this.applications.includes(item)) {
                    this.listApplication.splice(index, 1);
                }
            });
        }`

So I tried to disabled an element. I add a property "disabled:true" for each element which is selected but it doesn't work too.

`    removeSelectedApplication() {

        if (this.applications.length > 0) {
            this.listApplication.forEach((item, index) => {
                if (this.applications.includes(item)) {
                    this.listApplication[index]['disabled'] = true;
                }
            });

            console.log(this.listApplication); // The property disabled is set
        }
    }`

**Comment by varnastadeus** [comment]
as I mentioned before you need to mutate array refrenece. https://github.com/ng-select/ng-select#change-detection

**Comment by trupti28** [comment]
@varnastadeus It works for me!!
