### ISSUE TITLE
ng-select is throwing 404 in safari 8.x.x.x version

### ISSUE THREAD

**Issue by bana182** [ng-select/ng-select#531]
ng-select should work with safari 8.x.x version.  though It is working in 11.x.x.x

while running the application in safari 8.x.x version ng select is throwing 404 in  ng-select.map.js is not found.

I am using ng-select @ng-select/ng-select": "^1.3.0"

**Comment by varnastadeus** [comment]
@bana182 how are you including ng-select?

**Comment by anjmao** [comment]
@bana182 Closing as inactive, feel free to reopen if you still have any issues.
