### ISSUE TITLE
Feature Request: Allow bindLabel to be a function

### ISSUE THREAD

**Issue by vincentjames501** [ng-select/ng-select#532]
Right now `bindLabel` can only be a static string input. It would be awesome if it could accept a function that was given the selected object, and returns the string to display. I realize one could map over the items input to derive a display label, but then that value will be emitted on the output change event which isn't really desired and we then need to remove that display label.

**Comment by varnastadeus** [comment]
@vincentjames501 can you add more info why this would be better than having simple string?

**Comment by nukemyro** [comment]
My dropdown case is an account number, with it's sub number embedded from the object, but can't list 2 properties, only one - the master account, or the sub account.

**Comment by lcharbon** [comment]
Another use case would be translation. An item could have the keys `labelEN`, `labelES`, `labelFR`. It would be great to dynamically switch between them.

**Comment by shruti-ahuja** [comment]
Any progress on this?

**Comment by sayedsadat344** [comment]
Any update on this issue?
