### ISSUE TITLE
ng-select whether to set focus api ?

### ISSUE THREAD

**Issue by smile2014** [ng-select/ng-select#533]
ng-select whether to set focus api ?

**Comment by varnastadeus** [comment]
just use `#select.focus()`, it is documented.

**Comment by smile2014** [comment]
thank you

**Comment by pramodvkadam** [comment]
> just use `#select.focus()`, it is documented.

How can apply focus from directive?

I have created a directive to set focus on invalid controls but if we tried to focus as native element not get focused. 

I have code like follow:

import { Directive, ElementRef, HostListener } from '@angular/core';

@Directive({
  selector: '[oaksFocusFirstInvalidField]'
})
export class FocusFirstInvalidFieldDirective {

  constructor(private el: ElementRef) { }

  @HostListener('submit', ['$event'])
  onFormSubmit() {
   let invalidElements = null;
   invalidElements = this.el.nativeElement.querySelectorAll('.ng-invalid');
    if (invalidElements.length > 0) {
      invalidElements[0].focus();
    }
  }
}

It works with html elements but not with ng-select
