### ISSUE TITLE
Placeholder without specifying a value to bind

### ISSUE THREAD

**Issue by matteomason** [ng-select/ng-select#534]
Bug report

### Expected behaviour
```
<ng-select [items]="availablePlates"
               bindLabel="name"
               [(ngModel)]="itemToAdd"
                placeholder="Select plate"
               [ngModelOptions]="{standalone: true}">
</ng-select>
```

Here I'm especting to have "Select plate" as placeholder

### Actual behaviour
The placeholder never shows up. It only shows up if I define a bindValue but, in my context, I don't want to set a value to bind beacause I need the entire object.

### More Info
ng-select version: 1.4.1

browser: Firefox Quantum 59.0.3

**Comment by varnastadeus** [comment]
@matteomason create reproducible example.

**Comment by matteomason** [comment]
https://stackblitz.com/edit/ng-select-hwm6qc

**Comment by matteomason** [comment]
I really can't undestrand why in the example the two ways data binding works even if the object is not initialized...

**Comment by varnastadeus** [comment]
It is initialized even if you create empty object
