### ISSUE TITLE
compareWith does not work with bindValue

### ISSUE THREAD

**Issue by tomasz-nowakowski-stx** [ng-select/ng-select#535]
### Expected behavior
When I use both `compareWith` and `bindValue` I would expect that `compareWith` will still used for comparing.

### Actual behavior
Run this with console opened.
https://stackblitz.com/edit/angular-d1cvpv?file=src/app/hello.component.ts
Nothing shows up in console. But if you remove `bindValue` the "test" from `compareFn` should appear in console two times.

### Why would I need this
Because my initial ngModel is always a string but values in items might be strings or numbers. I want to convert ngModel and values to sting before comparing them in `compareWith`

### More Info
ng-select version: 1.4.1

browser: all

reproducible in demo page: NO

**Comment by varnastadeus** [comment]
@tomasz-nowakowski-stx I am not sure if it makes sense to use `compareWith` with `bindValue`. Here is why: 

1. When you use let say `bindValue="id"`,  you already tell that your value should match `id` property of items list so having `compareWith` seems redundant.

2. It will produce inconsistent results. 
```javascript
items = [{ id: 7, name: 'Vilnius' }]
```
Eg.: if you have your value as string `'7'`, initial NgModel will stay as string, but if you select it from the dropdown, NgModel would switch to number.

Having this in mind I recommend just casting your value to same type and thats it.

**Comment by tomasz-nowakowski-stx** [comment]
@varnastadeus  The problem is that I never know if values from API are strings or numbers (don't blame me 😃). And inconsistency you mentioned is fine for me in this case. 
But I see your arguments and that it might be confusing for some people in the future. But `compareWith` working only in some cases might me confusing also as it is was for me :)

**Comment by anjmao** [comment]
https://github.com/ng-select/ng-select/pull/586
