### ISSUE TITLE
Label for support

### ISSUE THREAD

**Issue by iranicus** [ng-select/ng-select#537]
Hello there, this might be a bug or an existing feature however I was unable to find any documentation covering this, so currently I am trying to set up a label for the dropdown I therefore have the following:

```
<label for="colourDropdown">Select from the colours</label>
<ng-select id="colourDropdown" [(items)]="colourArray" placeholder="Colours available"></ng-select>
```
However despite having a label with a for attribute matching the id of the ng-select there is no focus on the dropdown when the user clicks on the label. I might be going about this the wrong way but if I am then I would welcome some guidance.

Thanks now.

**Comment by varnastadeus** [comment]
I am not sure if we gonna support this, but for now simple click would work.
```
<label (click)="select.focus()">Select from the colours</label>
<ng-select #select [(items)]="colourArray" placeholder="Colours available"></ng-select>
```

**Comment by iranicus** [comment]
This sounds like a nice work around which will be implemented but it might not work for us since this came up in accessibility testing in that there was no label associated with the control despite us having the for and id matching. While this will solve the focus issue because the label might still be deemed as separate from the dropdown it seems we will be forced to not use ng-select unfortunately.

**Comment by iranicus** [comment]
Apologies, didn't mean to close the issue on this.

**Comment by varnastadeus** [comment]
version 2.0.1 support input `labelForId`

**Comment by jscharett** [comment]
Can this be back filled for Angular 5?  Will is work as a bound property; [labelForId]?

**Comment by iranicus** [comment]
Cools if it indeed is supported I'll give it a try tomorrow.
