### ISSUE TITLE
AutoSize dropdown width 

### ISSUE THREAD

**Issue by mani0608** [ng-select/ng-select#538]
Please add the ability to auto-adjust drop-down width  to the width of the option content/values.

**Comment by varnastadeus** [comment]
just set `width: auto !important` for dropdown panel

**Comment by varnastadeus** [comment]
#476

**Comment by varnastadeus** [comment]
same for ng-select itself.

**Comment by thesumitshrestha** [comment]
@mani0608  adding ng-select { .ng-dropdown-panel { width: auto !important; } } in CSS, it works but I would like to suggest adding a tooltip while hovering making a substring than adding css. 
```
<ng-template ng-option-tmp let-item="item">
        <div [ngbTooltip]="item.length > 15 ? item : ''" container="body">
          {{item.length > 15 ? (item| slice:0:15) + '..' : item}}
        </div>
</ng-template>
```
