### ISSUE TITLE
Issue using ng-select inside a ng-bootstrap dropdown

### ISSUE THREAD

**Issue by gschuager** [ng-select/ng-select#541]
While trying to use ng-select within a ng-bootstrap dropdown, I see that the dropdown is closed when selecting an ng-select option.
I tracked the issue down to the fact that the selected option node (click event target) is no longer in the dom when ng-bootstrap checks whether the click occurred inside or outside the parent dropdown element, thus closing the dropdown when the correct behavior would be for it to stay open after selection.

https://stackblitz.com/edit/angular-5kb9xd

(look at console output when selecting a ng-select option)

**Comment by varnastadeus** [comment]
I don't see how this is related to ng-select, but `<ng-select (click)="$event.stopPropagation()" [items]="colors"></ng-select>` does the trick.

**Comment by gschuager** [comment]
I created the issue here because I expected the option element to be able to be verified as a children of the ng-select... I was just wondering why it is removed from the dom instead of being hid.

Anyway, thanks for the workaround and thanks for this very useful component.

**Comment by varnastadeus** [comment]
It not renders dropdown because of performance considerations, it is not necessary to keep it in DOM while control is closed. Imagine having lots of ng-selects with each option in DOM, this will definitely have performance impact.

**Comment by Rebaiahmed** [comment]
Hi guys, I have some issue about preventing the drop-down menu from closing but I have ng -select inside component B, and the   <li class="nav-item dropdown config-panel"> is in component A , 
How can I make the "$event.stopPropagation();" be executed and fired from component B
