### ISSUE TITLE
Dinamically delete or update item property in ng-select list

### ISSUE THREAD

**Issue by oktay-rectasolutions** [ng-select/ng-select#543]
Hi, 
`   <ng-select [(items)]="objects"
                             bindLabel="name"
                             bindValue="id"
                             [(ngModel)]="selectedId"
                             (change)="onChange($event)">
                  </ng-select>`
I have objects list which contains specific objects and I am showing their names but I also I want to be able to update the names of the objects in my form when I do that ng-select doesn't pick up a new name, as Change Detector. I have gone through documentation and there is onPush Detector but how can I do remove or update of elements? 

Best regards,
Oktay

**Comment by varnastadeus** [comment]
@oktay-rectasolutions what part of https://github.com/ng-select/ng-select#change-detection is not clear?

**Comment by oktay-rectasolutions** [comment]
I want to remove item from a items array how to do that?

**Comment by varnastadeus** [comment]
https://stackoverflow.com/questions/5767325/how-do-i-remove-a-particular-element-from-an-array-in-javascript
