### ISSUE TITLE
Feature request: Or may be an options haven't turn on yet

### ISSUE THREAD

**Issue by dacsy** [ng-select/ng-select#547]
Please fill below information if issuing a bug report. 
### Expected behaviour
It will be nice when Multiple selection is on, we can show/hide the selected value on the input field as an options.
Cause in my case, I don't have enough place to show all selected value on the dropdown field.
![image](https://user-images.githubusercontent.com/10598358/39964825-4163f3ce-56b7-11e8-9bbb-68a54de74d76.png)

If we have an options to hide it then it will be a very nice options for user.

### More Info
ng-select version: latest

browser: chrome 66

reproducible in demo page:  Yes, if you set limit width of your search field

**Comment by varnastadeus** [comment]
it is already possible. https://ng-select.github.io/ng-select#/multiselect

**Comment by dacsy** [comment]
Which options do you means ?

**Comment by varnastadeus** [comment]
last example
