### ISSUE TITLE
core.js:1427 ERROR TypeError: Object(...) is not a function NgDropdownPanelComponent.ngOnInit

### ISSUE THREAD

**Issue by hamzahmidani** [ng-select/ng-select#548]
Hi,
I need help !! 

console log : 

core.js:1427 ERROR TypeError: Object(...) is not a function
    at NgDropdownPanelComponent.ngOnInit (ng-select.js:1450)
    at checkAndUpdateDirectiveInline (core.js:12400)
    at checkAndUpdateNodeInline (core.js:13927)
    at checkAndUpdateNode (core.js:13870)
    at prodCheckAndUpdateNode (core.js:14594)
    at Object.eval [as updateDirectives] (NgSelectComponent.ngfactory.js:407)
    at Object.updateDirectives (core.js:14316)
    at checkAndUpdateView (core.js:13836)
    at callViewAction (core.js:14187)
    at execEmbeddedViewsAction (core.js:14145)

this is my html

  <ng-select [items]="clients" bindLabel="name"  bindValue="id"  name="payee_id"  [(ngModel)]="single.payee_id" [loading]="clients == null">
                      
                       <ng-template ng-label-tmp  ng-option-tmp  let-item="item" let-label="label">
                            <img *ngIf="item.user_photo ==null" src="assets/img/user.png" width="20px" height="20px" /> 
                            <img *ngIf="item.user_photo !=null" [src]="item.user_photo" width="20px" height="20px" /> <span >{{item.name}}</span>
                        </ng-template>
                  </ng-select>

**Comment by danilocgraciano** [comment]
+1

```
<div class="form-group required" formGroupName="uf">
    <label class="control-label" for="uf">UF</label>
    <ng-select formControlName="id" [items]="ufList" bindLabel="descricao" bindValue="id">
    </ng-select>
  </div>

Object(...) is not a function
    at NgDropdownPanelComponent.ngOnInit (ng-select.js:1647)
    at checkAndUpdateDirectiveInline (core.js:10302)
    at checkAndUpdateNodeInline (core.js:11825)
    at checkAndUpdateNode (core.js:11768)
    at debugCheckAndUpdateNode (core.js:12647)
    at debugCheckDirectivesFn (core.js:12592)
    at Object.eval [as updateDirectives] (NgSelectComponent.html:62)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:12581)
    at checkAndUpdateView (core.js:11734)
    at callViewAction (core.js:12085)
```

**Comment by danilocgraciano** [comment]
Here: https://github.com/danilocgraciano/ng-select-demo

Clone, execute npm install and ng serve.

**Comment by hamzahmidani** [comment]
import {Component, Injector, Input, Output , EventEmitter} from '@angular/core';
 import {Agenda} from "./agenda.class";

@Component({
    selector: 'add_agenda',
    template: `

       <div  [ngClass]="{hh_box_menu:!popup ,hh_box:!popup }">
           
            <h1  *ngIf="!popup" ><i  class="fa fa-calendar-plus-o" aria-hidden="true"></i> {{'AGENDA'|translate}} ({{'ADD'|translate}})</h1>
 
          <form class="hh_form"  #hhform="ngForm" (ngSubmit)="onSubmit(hhform)">
               
               
                 <div class="row">
                 <div class="col-md-6">
                 
                    <div class="form-group">
                      <label class="hh_label">{{'TITLE'|translate}}</label>
                     <input    name="nom" type="text" class="hh_input" [(ngModel)]="single.title"   [_regex]="'default'" required [ngClass]="{'ng-untouched': !_obj.showerror }">
                 </div>
                 
                 </div>
                 <div class="col-md-6">
                 
                   
                  
                  <div class="col-md-6">
                    
                       <div class="form-group">
                       <label class="hh_label" >{{'PARTICIPANTS'|translate}} </label>
                   <ng-select [items]="personnels" bindLabel="name"  bindValue="id"  name="personnels"  [(ngModel)]="single.personnels"  [multiple]="true"   [hideSelected]="true" [loading]="personnels == null"  >
                        <ng-template ng-label-tmp  let-item="item" let-label="label" let-clear="clear">
                            <img *ngIf="item.thumbnail_image ==null" src="assets/img/user.png" width="20px" height="20px" /> 
                            <img *ngIf="item.thumbnail_image !=null" [src]="item.user_photo" width="20px" height="20px" /> {{item.name}} 
                                <span class="ng-value-icon right" (click)="clear(item)" aria-hidden="true">×</span>
                        </ng-template>
                         <ng-template  ng-option-tmp  let-item="item" let-label="label">
                            <img *ngIf="item.thumbnail_image ==null" src="assets/img/user.png" width="20px" height="20px" /> 
                            <img *ngIf="item.thumbnail_image !=null" [src]="item.user_photo" width="20px" height="20px" /> {{item.name}} 
                        </ng-template>
                       </ng-select>  
                   </div>
                  
                  </div>
                  </div>
                   
                 
                 
      
                <submit ></submit>
          </form>
 </div>
`
})
export class AgendaAddComponent {
 
    single:Agenda = new Agenda();
    
     personnels = [];
     


    constructor( ) {  }
 

     ngOnInit(){
         this.single.personnels =[];
       
         
         this.core.getApi('admin/personnels/names').then(collection => {
            this.personnels=collection;
        });
        
    }


 
    onSubmit(form) {
        
    }


}

**Comment by varnastadeus** [comment]
Well I hoped that you would create stackblitz, but anyway here it is and I don't see any errors.

https://stackblitz.com/edit/ng-select-object-keys?file=app/app.component.ts

**Comment by varnastadeus** [comment]
ok, error comes because you are using wrong version, there is error while restoring packages. Version 2.x is requires angular 6+. 
<img width="745" alt="screen shot 2018-05-14 at 08 46 18" src="https://user-images.githubusercontent.com/17824796/39980231-73979ec6-5753-11e8-8433-de972007a8ad.png">
