### ISSUE TITLE
Feature Request: Add hooks for events to disable dropdown panel closing.

### ISSUE THREAD

**Issue by nicholassinggih** [ng-select/ng-select#549]
Please fill below information if issuing a bug report. 
Need to keep the dropdown panel always opened. Calling open() in the (close) event handler is very costly. I have been looking into the codes and trying to find a solution to no avail. 
The [outsideClick] handler is set to "close()" in ng-select.component.html, which makes it even harder to customise. 
My request is for you to provide hooks such as : beforeClose($event), afterClose($event), beforeOpen($event) and afterOpen($event). So developers can easily customise the component's behaviour. 

### Actual behaviour
N/A

### More Info
ng-select version: 1.4.1

browser: any browser

reproducible in demo page: Not a bug.

**Comment by varnastadeus** [comment]
Have you tried `[closeOnSelect]`?  Also can you add considerable use case?

**Comment by varnastadeus** [comment]
It is not about how easy or hard it is to implement this behaviour. It is about usefulness for general user and if it is common among other select like controls. We are considering this because otherwise code base would become unmaintainable and enormous for this type of component.
For now I don't see any valid use cases for it. Why are you using dropdown component at first place if it should be opened all the time?

**Comment by deepender87** [comment]
@nicholassinggih This can be done via simply matching the CSS used by ng-select. What will be the use of a drop-down if you want it to be always open. In my view that's not a drop-down at all.

**Comment by deepender87** [comment]
@varnastadeus better to close this :D

**Comment by nicholassinggih** [comment]
@deepender87 

> This can be done via simply matching the CSS used by ng-select.
How can you override Angular's *ngIf by means of CSS? Please share with us how you think you're going to achieve this.

**Comment by anjmao** [comment]
Best option is to add new input called ` @Input() isOpen: boolean` which by default is undefined and if user set it to false or true when he is completely responsible for closing dropdown panel.

**Comment by nicholassinggih** [comment]
Thank you! I'm sure this would add value.
