### ISSUE TITLE
When "ng-select" clicked somewhere outside "dropdown" not closing.

### ISSUE THREAD

**Issue by MehmetSert** [ng-select/ng-select#550]
### Expected behaviour
When "ng-select" clicked somewhere outside "dropdown" not closing.
https://angular-yiiyq6.stackblitz.io

> HTML
`<ng-select placeholder="Seçiniz" [items]="people" bindLabel="name" bindValue="id" [virtualScroll]="true"></ng-select>`

> TS
`people = ['Ali', 'Veli', 'Ayşe', 'Fatma'];`

### Actual behaviour
How do I close "dropdown" when I click on an item other than "ng-select"?

### More Info
ng-select version: 2.0.0

browser: All

reproducible in demo page: [YES/NO]

**Comment by varnastadeus** [comment]
Please create reproducible example, otherwise we can't help you much. Stackblitz.com

**Comment by MehmetSert** [comment]
Of course

https://angular-yiiyq6.stackblitz.io

**Comment by varnastadeus** [comment]
`rxjs.fromEventPattern is not a function` there is error in console. v2.0.0 is for angular 6+

**Comment by SudeendraG** [comment]
NgSelectComponent.html:62 ERROR TypeError: Object(...) is not a function
    at NgDropdownPanelComponent.ngOnInit (ng-select.js:1450)
(NgDropdownPanelComponent.prototype.ngOnInit = function () {})

Error in the console  in angular 5+ also 
 please fix this.

**Comment by MehmetSert** [comment]
@varnastadeus I have updated the angular to version 6 and have fixed the problem. Thank you.

**Comment by varnastadeus** [comment]
https://github.com/ng-select/ng-select#v200
