### ISSUE TITLE
Question: Option display empty row

### ISSUE THREAD

**Issue by procnet0** [ng-select/ng-select#552]
> [items]="carrierServiceTypeOptions" [bindValue]="id" [bindLabel]="name"  [(ngModel)]="shipmentRequest.carrierServiceTypeId"

The html:
```
    <ng-select [items]="carrierServiceTypeOptions" [bindValue]="id" [bindLabel]="name" name="toto" [(ngModel)]="shipmentRequest.carrierServiceTypeId">
    </ng-select>
```
The Component includes:

```
carrierServiceTypeOptions: CarrierServiceTypeGenerated[] = [];

this.carrierTypeService.query().subscribe(
          (res) => {this.carrierServiceTypeOptions = res.body;},
          (error) => this.onError(error),
          () => console.log(this.carrierServiceTypeOptions)
          );

```

Should display 4 row  with name in it.

Actualy it display 4 Row but empty.
 Weirdly if i change  the ngModel from a regular \<select\>.
The value selected in ng-select display the Id.
I believe i have missed something but as i am  relatively new to angular i can't found what it is. 
Thanks for your time.

ng-select version: [1.4.2]. angular : [5.2]. browser: [google Chrome].

**Comment by anjmao** [comment]
Hi @procnet0, does your api returns objects with name property as you are binding label to name property?

**Comment by varnastadeus** [comment]
@procnet0 create reproducible [Stackblitz](https://stackblitz.com/edit/ng-select?file=app%2Fapp.component.ts)
