### ISSUE TITLE
Can't use ng-select with Angular version 4.4.6

### ISSUE THREAD

**Issue by evaleirasclapps** [ng-select/ng-select#555]
### Expected behaviour
It used to work (until today).

### Actual behaviour
When try to start the app today, this error appears on ser:

`Error: Metadata version mismatch for module C:/PATH/TO/PRORJECT/node_modules/@ng-select/ng-select/ng-select.d.ts, found version 4, expected 3, resolving symbol SharedModule in C:/PATH/TO/PRORJECT/src/app/shared/shared.module.ts, resolving symbol SharedModule in C:/PATH/TO/PRORJECT/src/app/shared/shared.module.ts`

### More Info
ng-select version: **2.0.0** or **1.4.2**

browser: ALL

reproducible in demo page: NO

**Comment by varnastadeus** [comment]
Minimal supported angular version is 5.
