### ISSUE TITLE
Custom search position

### ISSUE THREAD

**Issue by classicmike** [ng-select/ng-select#556]
Hi,
I have a bug to log with one of the examples as I am using it as a basis for one of my features of an app I am working on in my complany.

Custom Search Example under Templates. 

There is a custom search example under templates where a custom search field is inserted into the header template of the dropdown of ng-select.

In your live example you have your ng-dropdown appended based on default settings and when I focus on that custom filter, input you are still able use your arrow keys to highlight a choice you wish to select.

However, when focused on the custom search field, if ng-dropdown is 'appendTo="'body'", dropdown menu will not activate arrow keys to focus between different choices.

### Expected behaviour
If ng-dropdown is 'appendTo="'body'", dropdown and custom search field and custom search field is focused, user should be able to still use arrow keys to focus between choices.

### Actual behaviour
If ng-dropdown is 'appendTo="'body'", dropdown and custom search field and custom search field is focused, user should is not able to use the arrow keys to focus between choices.

i've attached a video link to demostrate the problem (https://drive.google.com/file/d/1mICGfQH6IxazbH-Iyl3Gfs2beGQ7tmHS/view?usp=sharing) and have forked your repo to write the code on the templates demo page to demonstrate the problem: https://github.com/classicmike/ng-select

### More Info
ng-select version: 2.0.0

browser: Google Chrome 66.0.3359.139

reproducible in demo page: Yes - Reproducible off a forked repo: https://github.com/classicmike/ng-select. Under the templates demo page.

**Comment by anjmao** [comment]
Hi @classicmike, it is known limitation and not fully supported yet, but I remember there is separate branch which implements custom search position, will need to check status of it.

**Comment by classicmike** [comment]
Hi @anjmao. Thanks for looking at this. I would assume on the same vain if we were to blur on that custom input filter field, using keyboard it wouldn't jump to the next input field and set focus to it right?

Thanks.
