### ISSUE TITLE
Allow configurable name option for input

### ISSUE THREAD

**Issue by jscharett** [ng-select/ng-select#558]
ng-select version: 1.0.2
browser: ANY
reproducible in demo page: YES

Can an option be added to allow setting the name attribute of the underlying input field?  Our testing team uses the name attribute for input in its automated selenium tests

**Comment by varnastadeus** [comment]
why not just use name attribute on ng-select itself?

**Comment by jscharett** [comment]
I didn't see anything in the api for it.  Does it support it?

**Comment by varnastadeus** [comment]
name is by default since it is native html attribute.

**Comment by jscharett** [comment]
But isn't technically only supported by form fields? https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes.  I've never seen a "name" attribute on a non-form field before, unless it was a data-prop like "data-name".  If name works on ng-select, I suppose we could use it. Will give it a shot.  Thanks

**Comment by jscharett** [comment]
Adding name did not work.  Seems like ng-select strips it.

**Comment by varnastadeus** [comment]
<img width="336" alt="screen shot 2018-05-16 at 19 35 43" src="https://user-images.githubusercontent.com/17824796/40130672-70a38498-5940-11e8-8064-bb8a517b3258.png">

**Comment by jscharett** [comment]
interesting

**Comment by jscharett** [comment]
Does not work if you use it as a bound property [name]

**Comment by varnastadeus** [comment]
Have you defined that property in component?

**Comment by jscharett** [comment]
yes.  Works in other areas, but not here.

**Comment by varnastadeus** [comment]
Because there is no input name, you need to use [attr.name]

**Comment by anilkokate2009** [comment]
Thank you. It works for me
