### ISSUE TITLE
Multiselect height on small resolution

### ISSUE THREAD

**Issue by anjmao** [ng-select/ng-select#56]
### Expected behaviour
Should not create new line if items can fit in select

### Actual behaviour
<img width="385" alt="multiselect-height" src="https://user-images.githubusercontent.com/3028012/31054412-bb2a6632-a6ba-11e7-88f1-5a8dee572f59.png">
On small resolution items can fit but new line is created because invisible filter width is 170px by default. It should not create new line if selected items can fill in the box. Probably we need to use flex to fill filter input all possible space.

### More Info
ng-select version: 0.2.0

browser: all browsers

reproducable in demo page: YES

**Comment by Hesesses** [comment]
![image](https://user-images.githubusercontent.com/2721970/31658252-385c851a-b339-11e7-8d3a-824e64893f6e.png)

I'm still having this issue. Using the 0.2.5v

**Comment by varnastadeus** [comment]
it will be fixed with next release, later today
