### ISSUE TITLE
Module not found: Error: Can't resolve 'rxjs/Subject' 

### ISSUE THREAD

**Issue by GoNode5** [ng-select/ng-select#561]
ERROR in ./node_modules/@ng-select/ng-select/esm5/ng-select.js
Module not found: Error: Can't resolve 'rxjs/Subject' in 'C:\dev-angular\car\node_modules\@ng-select\ng-select\esm5'
ERROR in ./node_modules/@ng-select/ng-select/esm5/ng-select.js
Module not found: Error: Can't resolve 'rxjs/observable/fromEventPattern' in 'C:\dev-angular\car\node_modules\@ng-select\ng-select\esm5'
ERROR in ./node_modules/@ng-select/ng-select/esm5/ng-select.js
Module not found: Error: Can't resolve 'rxjs/observable/merge' in 'C:\dev-angular\car\node_modules\@ng-select\ng-select\esm5'
i ｢wdm｣: Failed to compile.

OS: win32 x64
Angular: 6.0.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.1
@angular-devkit/build-angular     0.6.1
@angular-devkit/build-optimizer   0.6.1
@angular-devkit/core              0.6.1
@angular-devkit/schematics        0.6.1
@angular/cli                      6.0.1
@ngtools/webpack                  6.0.1
@schematics/angular               0.6.1
@schematics/update                0.6.1
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0

Tried for 2 hours al kind of combinations...
ng new project...
import { NgSelectModule } from '@ng-select/ng-select';
+imports: [
    BrowserModule,
    NgSelectModule

**Comment by varnastadeus** [comment]
@GoNode5 have you read this https://github.com/ng-select/ng-select#v200 ?

**Comment by GoNode5** [comment]
yes I did.  I though it means that I use Angular  6.0.2 + rxjs 6.1.0 that I dont need rxjs-compat ?

**Comment by varnastadeus** [comment]
And ng select v2

**Comment by axelboc** [comment]
Same issue here: `Module not found: Error: Can't resolve 'rxjs/Subject'`. I had to re-install `rxjs-compat` even though I migrated my app to Angular 6.
