### ISSUE TITLE
The (remove) output is not being triggered when item removed with keyboard (backspace)

### ISSUE THREAD

**Issue by jmvalencia** [ng-select/ng-select#564]
### Expected behaviour
(remove) output function being triggered on item removal using keyboard (backspace)

### Actual behaviour
When you have multiselect and try to remove on item with the backspace the (remove) output is not being triggered only is you do it from the list or clicking the 'x' besides the item it does, following you can check the code and in the console you will see the behavior: 
https://stackblitz.com/edit/ng-select-example-urgbvy

### More Info
ng-select version: [2.0]

browser: [Chrome]

reproducible in demo page: [YES] adding the (remove) output and the function handler

**Comment by jmvalencia** [comment]
@varnastadeus is this fix going to be part of v1.5? hope it will, thanks in advance

**Comment by jmvalencia** [comment]
btw thanks a lot for the quick response :)

**Comment by varnastadeus** [comment]
I thought I will get through with this one 😞 take in mind that we won't support v1.x forever 🤔
