### ISSUE TITLE
Click on clear button : list of items is empty

### ISSUE THREAD

**Issue by stoto34** [ng-select/ng-select#567]
Please fill below information if issuing a bug report. 
### Expected behaviour
When I click on the clear all button, the value is set to null and the list is reloaded.

### Actual behaviour
Describe how it actually works or even better create example using [StackBlitz]

If I click on the clear all button, the value is set to null and then the list is empty (the focus is on the ng-select). I have to click outside the ng-select to launch a function to refresh the list.

### More Info
ng-select version: [INSERT HERE]
1.2.1

browser: [INSERT BROWSER INFO HERE]

reproducible in demo page: [YES/NO]

```
    initCategory() {
        this.categoryService.find().subscribe(categoryData=> {
            categoryData = this.disableSelectedItems(categoryData);
            this.listCategory = [...categoryData];
            console.log(this.listCategory); // data are good but my list is empty
        });
    }
```

Thank you very much !

**Comment by varnastadeus** [comment]
please create reproducible [StackBlitz]

**Comment by stoto34** [comment]
It's my fault and I fixed it.

the search section (term) returns null and not "" when  I click on the clear button. You can close this issue
