### ISSUE TITLE
Cannot set ng-select disabled on a ReactiveFormsModule

### ISSUE THREAD

**Issue by smile2014** [ng-select/ng-select#568]
https://stackblitz.com/edit/ng-select-bug?file=app%2Fapp.component.ts

**Comment by varnastadeus** [comment]
https://github.com/ng-select/ng-select/blob/master/demo/app/examples/reactive-forms.component.ts

**Comment by smile2014** [comment]
@varnastadeus 
Can't bind the disabled attribute directly? Look at the demo I provided

**Comment by varnastadeus** [comment]
yes you can't, thats the whole idea of reactive forms.

**Comment by smile2014** [comment]
thank you
