### ISSUE TITLE
Can't see event data for focus/open/blur events

### ISSUE THREAD

**Issue by brumeregan** [ng-select/ng-select#571]
### Expected behaviour
On (focus) and other events I expect receiving actual event information.

### Actual behaviour
For now : 
(open) - null
(focus) - null

### More Info
reproducible in demo page: [YES]
https://ng-select.github.io/ng-select#/events

**Comment by varnastadeus** [comment]
@brumeregan open is internal, what do you expect to get? for focus it probably makes sense to return the event

**Comment by brumeregan** [comment]
@varnastadeus 
ok. thnx for answer. I expected to get actual select component for open event.
But actually I have problem with multiselect - when all options is selected and I want to remove one, first click just focus on the whole select, not remove option. I thought it is because of (focus) event returning null

**Comment by varnastadeus** [comment]
update to latest version, or you everything like in examples and you should have no problems.

**Comment by brumeregan** [comment]
@varnastadeus thank you. I'll try

**Comment by rohit0522** [comment]
Was event information added to focus and blur?
Still getting event as null on (blur)="blurred($event)"
[StackBlitz](https://stackblitz.com/edit/ng-select-upd5rv)
