### ISSUE TITLE
Edge Browser- Cannot use the keyboard arrow key for navigate in the items

### ISSUE THREAD

**Issue by Mage111** [ng-select/ng-select#573]
### Expected behaviour
cannot use the keyboard down arrow for select items

### Actual behaviour
when pressing the keyboard down arrow the browser cache is open above of the select box list

see attached image, can navigate un the browser cache list, but not in drop-down  options

![image](https://user-images.githubusercontent.com/23486790/40368023-718bc6a2-5de3-11e8-9147-7ca93848b679.png)

**Comment by anjmao** [comment]
Hi @Mage111, could you create stackblitz or paste your code, because I don't get this behaviour on my edge browser in demo page.

**Comment by varnastadeus** [comment]
Probably you have your styles messed up in your application.

**Comment by Mage111** [comment]
Occurs only in Edge. I don't see any style that can cause it.

**Comment by varnastadeus** [comment]
then create reproducible stackblitz since I don't see any issues in edge.

**Comment by Mage111** [comment]
It depends on browser settings. 
for reproducing it firstly turn on forms AutoComplete:

Select the More actions  button.
Select Settings > View advanced settings.
Turn on Save form entries.

note: the select box should be into html form

**Comment by varnastadeus** [comment]
should be solved with #269. Didn't reproduced it on edge
