### ISSUE TITLE
Getting error (TypeError: Object(...) is not a function) on initial click...  NgDropdownPanelComponent.ngOnInit

### ISSUE THREAD

**Issue by brandonyoung** [ng-select/ng-select#574]
Please fill below information if issuing a bug report. 
### Expected behaviour
When I initially click on the select, the items should display without a console error.

### Actual behaviour
When the select is displayed, I get console errors that point to: 
     NgDropdownPanelComponent.prototype.ngOnInit = function () {
        var _this = this;
        this._handleScroll();
        fromEventPattern(function (handler) { return document.addEventListener('mousedown', handler, true); })
            .pipe(takeUntil(this._destroy$))
            .subscribe(function ($event) { return _this._handleOutsideClick($event); });
    };

ERROR TypeError: Object(...) is not a function
    at NgDropdownPanelComponent.ngOnInit (ng-select.js:1444)
    at checkAndUpdateDirectiveInline (core.js:12411)
    at checkAndUpdateNodeInline (core.js:13935)
    at checkAndUpdateNode (core.js:13878)
    at debugCheckAndUpdateNode (core.js:14771)
    at debugCheckDirectivesFn (core.js:14712)
    at Object.eval [as updateDirectives] (NgSelectComponent.html:54)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:14697)
    at checkAndUpdateView (core.js:13844)
    at callViewAction (core.js:14195)

### More Info
ng-select version: 2.0.3

browser: Chrome (PC)

reproducible in demo page: [YES/NO]

**Comment by varnastadeus** [comment]
Let me guess, you are using angular 5?

**Comment by Ratikant01** [comment]
I am using Angular 5 - and getting same error, does not it support Angular 5?

**Comment by Ratikant01** [comment]
Maybe we have to use 1.5.2?

**Comment by anjmao** [comment]
You can try installing rxjs-compat and check if it works, if no when yes, you need to use angular 6 or 1.5.2 version.

**Comment by varnastadeus** [comment]
I was always wondering how can you program when you can't read 🤔 https://github.com/ng-select/ng-select#v200

**Comment by zzj0402** [comment]
I always wonder how you can live when you can't behave.
