### ISSUE TITLE
adding tabindex to ng-select

### ISSUE THREAD

**Issue by sreerajkarippala** [ng-select/ng-select#575]
How can i add tabindex to ng-select tag?

**Comment by anjmao** [comment]
Hi, is it some issue or this is a question? Please add normal description with your problem and usecase when filling new issues.

**Comment by anjmao** [comment]
Closing as inactive. Feel free to reopen if it is still relevant.

**Comment by aldus25** [comment]
tabindex is not working at all for iPads
