### ISSUE TITLE
Cannot use character reference

### ISSUE THREAD

**Issue by nadzeri** [ng-select/ng-select#576]
Please fill below information if issuing a bug report. 
### Expected behaviour
Using character reference should be work like native select

### Actual behaviour
Cannot use character reference. The screenshot:
![ng-select](https://user-images.githubusercontent.com/7666853/40404129-60e85688-5e80-11e8-945d-dc2175817fec.png)

### More Info
ng-select version: 1.5.2

browser: Chrome

reproducible in demo page: No

**Comment by anjmao** [comment]
Hi @nadzeri, it will not work because by default content is encoded for security reasons, if you want to have custom character you could use custom template.
```html
<ng-select>
    <ng-template ng-option-tmp let-item="item">
       {{item.value}}
    </ng-template>
</ng-select>
```
