### ISSUE TITLE
Form submit without value should not be possible on required 

### ISSUE THREAD

**Issue by gsteiner89** [ng-select/ng-select#579]
I found nothing to this particular case, please correct me if i am wrong!

### Expected behaviour
When **[required]** is set at **ng-select** a form should not be able to submit before a value is selected.

### Actual behaviour
When using **[required]="true"**, ng-invalid/ng-valid is bound to ng-select but not to the input tag. Result: Its possible to submit a form without selection, required isnt required.

Stackblitz example:
https://stackblitz.com/edit/ng-select-example-guawpp?file=app/app.component.ts

### More Info
ng-select version: 1.5.2
browser: Firefox (60.0.1), Firefox Developer Edition (61.0b7), Chrome (66.0.3359.181)
reproducible in demo page: YES

### Solution (?)
It may be a solution to bind required to the input tag, but styles need to be adjusted.

There are older issue-reports with similar problems. But they mostly got closed because there is a possibility to mark a invalid ng-select. Yes, i can get a red border around the component if its invalid but i also need a to build a second check outside of the usual form-validation for not submitting my form. It would be great if it would work without special treatment.

Thanks for creating such a great component, i love it!

**Comment by varnastadeus** [comment]
I think the problem here is that you are using native HTML5 validation with custom element which is angular component and obviously it doesn't supports it. In this case you should handle `ng-select` validation using angular itself.

**Comment by gsteiner89** [comment]
To bad the input is only used for filtering, but i get your point.
Im not really into angular validation yet, but i will test it tomorrow and maybe i can post a working example.

Thanks for your answer!

**Comment by varnastadeus** [comment]
https://loiane.com/2017/08/angular-reactive-forms-trigger-validation-on-submit/ here is some examples how it could be done with demo.
