### ISSUE TITLE
UX not found should clear and close

### ISSUE THREAD

**Issue by GoNode5** [ng-select/ng-select#58]
(really impressed by the last commits thank you!!!)
demo page:
when TAB
- dropdown should close
- when not found, should clear the not found entry input
![selectnotfound](https://user-images.githubusercontent.com/2210672/31054733-beaf2578-a6b9-11e7-9a89-92118e7aa039.gif)

**Comment by anjmao** [comment]
@GoNode5 Thanks for reporting :) @varnastadeus can you have a look at some point?
