### ISSUE TITLE
Multi-select drop-down list is not visible

### ISSUE THREAD

**Issue by deepender87** [ng-select/ng-select#580]
Hi 

I am using ag-grid to render the select box and multi-select box in row. It is getting rendered fine, but whenever i am trying open the ng-select drop-down, the list is not visible. However normal html select box is able to open the list box over the ag-grid.

 
`<ng-select [items]="list" container="body" [multiple]="true" [closeOnSelect]="false" bindLabel="name" placeholder="Select"
  [(ngModel)]="excludedItem" (add)="onAdd()">
</ng-select>`

**Comment by varnastadeus** [comment]
use appendTo="body"

**Comment by deepender87** [comment]
Thanks Man, it resolved the issue
