### ISSUE TITLE
How to show a single-line list of selected items in selected area of dropdown without having cross icon

### ISSUE THREAD

**Issue by deepender87** [ng-select/ng-select#581]
Whenever we select an item it is visible in the selected area of drop-down with additional cross icon to remove that item, instead, how I can show the selected items in one line with some space between them. 
Issue here is that selected items are moving down or in next line of the selected area of the drop-down and not visible in single list. So better if I can have the plane single line list with some space between them. Moreover, I don't want the selected items to be removed once selected and visible in the selected area of drop-down.

Thanks

**Comment by varnastadeus** [comment]
Have you looked at https://ng-select.github.io/ng-select? There are plenty examples how to achieve similar behaviour.

**Comment by deepender87** [comment]
Just now i saw that, but still i am not clear how i can achieve this. Can you please help with some example here to understand it

Thanks

**Comment by varnastadeus** [comment]
https://ng-select.github.io/ng-select#/multiselect last example. You can render anything you want in selected items.

**Comment by deepender87** [comment]
ok, I just tried but i am not able to override the css to remove the border of selected items.

`<ng-template ng-label-tmp let-item="item" let-clear="clear">
    <div class="ng-value">
      <span class="ng-value-label">
        {{item}}
      </span>
      <span class="ng-value-icon right" aria-hidden="true"></span>
    </div>
  </ng-template>`

css:

`.ng-value{
border:none;
}`

Am i missing something?

**Comment by varnastadeus** [comment]
don't use class="ng-value" at all

**Comment by deepender87** [comment]
ok, can you tell with some small example, how i can override this class. Also lets say i want to apply some class to the options of the dropdown only if that element is selected. I need this to add some css or override the same. 
please suggest something for this. Kinda stuck here.

**Comment by varnastadeus** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity

**Comment by deepender87** [comment]
you can close this issue, something wrong was with my CSS. That was coming from cache version. Not the latest one.

pasting the solution for future reference.

For selected items add the check mark in the options list: 

`.ng-dropdown-panel .ng-dropdown-panel-items .ng-option.ng-option-selected {
    &::before{
        content: '\2713';
    }
}`

Please mark it close

**Comment by jmaroa** [comment]
@varnastadeus Is there any good approach to remove/hide the ng-value list being shown when multi selecting options?
