### ISSUE TITLE
Convert comma separated value to tags

### ISSUE THREAD

**Issue by asadmalik3** [ng-select/ng-select#583]
Is there any option available to convert comma separated values to tags? If i type nike,adidas,puma,swift,honda the control should add 5 new tags.

**Comment by anjmao** [comment]
Hi @asadmalik3 , currently there is no such functionality, in fact tags are quit limited in ng-select, because main focus was on select itself, but we are planning to add better tags support.

**Comment by kalpeshhpatel** [comment]
Hi @anjmao is there any way programmatically to implement this feature for tags mode?
