### ISSUE TITLE
Recommendation: don't use subscribe for typeahead

### ISSUE THREAD

**Issue by otijhuis** [ng-select/ng-select#584]
In the documentation I came across the following:

```typescript
    private loadPeople3() {
        this.people3Typeahead.pipe(
            tap(() => this.people3Loading = true),
            distinctUntilChanged(),
            debounceTime(200),
            switchMap(term => this.dataService.getPeople(term)),
        ).subscribe(x => {
            this.people3 = x;
            this.people3Loading = false;
            this.cd.markForCheck();
        }, () => {
            this.people3 = [];
        });
    }
```

This has some issues:

1) You have to manually update the item list in the subscription
2) You have to think about unsubscribing
3) The use of  `ChangeDetectorRef`
4) distinctUntilChanged doesn't really help here, it should be after the debounce

You can also do it something like this:

```html
      <ng-select [items]="items$ | async"
                 [typeahead]="input$"></ng-select>
```

```typescript
   items$: Observable<string>;
   input$: Subject<string> = new Subject<string>();

   ngOnInit() {
        this.items$ = concat(
            of([]), // default items
            this.input$.pipe(
               debounceTime(200),
               distinctUntilChanged(),
               tap(() => {this.people3Loading = true;})
               switchMap(term => this.dataService.getPeople(term).pipe(
                   catchError(() => of([])), // empty list on error
                   tap(() => {this.people3Loading = false;})
               )) 
            )
        );
   }
```

Angular will now handle all the subscription details. And because `items` is now a stream there is no need for the `ChangeDetectorRef`. The list is automatically updated.

`distinctUntilChanged` will now also work if you type and backspace quickly for instance. When `distinctUntilChanged` is first, the input will basically always be different.

**Comment by anjmao** [comment]
@otijhuis Thanks good for recommendations and mistake on distinctUntilChanged. I will update docs example 👍

**Comment by anjmao** [comment]
Updated example https://github.com/ng-select/ng-select/blob/master/demo/app/examples/search.component.ts#L105

**Comment by marcorpsa** [comment]
https://github.com/ng-select/ng-select/issues/584#issuecomment-392524484 is broken
