### ISSUE TITLE
Reactive forms with ngModel input property deprecated

### ISSUE THREAD

**Issue by htrex** [ng-select/ng-select#587]
I'm creating an ng-select ngx-formly custom form field https://formly-js.github.io/ngx-formly/guide/custom-formly-field.
The template for the field is the following:
```
<ng-select
        [formControl]="formControl"
        [items]="items$ | async"
        [bindLabel]="labelProp"
        [bindValue]="valueProp"
        [hideSelected]="true"
        [typeahead]="input$"
        [ngModel]="initVal"
        [formlyAttributes]="field">
</ng-select>
```

ngx-formly is build on top of reactive forms so I need to use [formControl] while to set ng-select initial value I couldn't find anything but using [ngModel], this generates the following warning with Angular v6. 

>    It looks like you're using ngModel on the same form field as formControl. 
>    Support for using the ngModel input property and ngModelChange event with 
>    reactive form directives has been deprecated in Angular v6 and will be removed 
>    in Angular v7.

**Comment by aitboudad** [comment]
just remove `ngModel` and pass the initial value to `formControl` instead.

**Comment by anjmao** [comment]
@aitboudad Is correct, if you use reactive forms, ngModel should not be used.

**Comment by DuaneQ** [comment]
> just remove `ngModel` and pass the initial value to `formControl` instead.

How would I do that in this scenario?

`      <ion-select formControlName="gender" placeholder="*Gender">
        <ion-select-option data-cy="gender-dropdown" *ngFor="let genOption of genderOptions"> {{genOption}}</ion-select-option>
      </ion-select>`

I'm using a reusable form in multiple pages and passing in the select options like this:
`  <app-profile-form [bio]="bio" [genderOptions]="genderOptions"  (profile)="onSubmit($event)"></app-profile-form>`

**Comment by aitboudad** [comment]
@DuaneQ if you're using Formly custom type, this is how it should be done:

```patch
- <ion-select formControlName="gender" placeholder="*Gender"> ...</ion-select>
+ <ion-select [formControl]="formControl" placeholder="*Gender"> ...</ion-select>
```
