### ISSUE TITLE
Ng select is constantly stuck behind other elements despite z-index

### ISSUE THREAD

**Issue by LiamDotPro** [ng-select/ng-select#589]
### Expected behaviour
I'm not able to add z-index to any of the components pieces to bring the select box back over the other elements on the page, the vanilla html select doesn't have this issues. So I'm going to presume there is a bug somewhere in the css.

### Actual behaviour
Here is a minimal punker that showcases the problem:
https://plnkr.co/edit/Asl4Y29c50IIwktCb1z0?p=preview

### More Info
ng-select version: 1.5.2
browser: Chrome

reproducible in demo page: Appended above

**Comment by varnastadeus** [comment]
have you tried ```appendTo="body"```

**Comment by LiamDotPro** [comment]
Honestly the fact this isn't some kind of paid product is beyond good, thank you very much.

**Comment by varnastadeus** [comment]
here is article to better understand z-index and why it is not working in this case https://philipwalton.com/articles/what-no-one-told-you-about-z-index/

**Comment by kojint** [comment]
> have you tried `appendTo="body"` ?

Just to be pedantic, this needs to be applied to the HTML element itself. E.g. `<ng-select ... appendTo="body"></ng-select>`

**Comment by goce13** [comment]
> > have you tried `appendTo="body"` ?
> 
> Just to be pedantic, this needs to be applied to the HTML element itself. E.g. `<ng-select ... appendTo="body"></ng-select>`

This works for me like in charm :) thanks

**Comment by Parthan-Sachin** [comment]
thank you so much @varnastadeus . It worked for me.

**Comment by caiquevallim** [comment]
It's works but when you're using ng-select inside a modal dialog its brokes at the dom

**Comment by jassi5887** [comment]
how I solved it was to set a good enough z-index on the parent element.

**Comment by alydemah** [comment]
In my case it `appendTo="body"` didn't work because bootstrap class `input-group` had display flex
what i did keep appendTo="body" but in global css i added

`.ng-dropdown-panel {
  display: block !important;
}`

**Comment by borisBelloc** [comment]
> > have you tried `appendTo="body"` ?

Today is a sad day, it almost works for me, not the ngselect is visible but it breack it :(

![image](https://user-images.githubusercontent.com/37147299/136224264-425ae3cf-d6be-493e-895a-17d0be6aa1d8.png)

**Comment by Hashirattiyedath** [comment]
asdasdasd

**Comment by singhgurjyot** [comment]
appendTo="<<CSS SELECTOR>>" worked for me

**Comment by singhgurjyot** [comment]
appendTo="CSS_SELECTOR" worked for me

**Comment by garethrpratt** [comment]
I had the same problem - elaborating on the answers above, for those using ng-select within NgbModal, this seems to work nicely:

`<ng-select appendTo=".modal-content"`
