### ISSUE TITLE
[bug] Combining ngOptionHighlight with Typeahead

### ISSUE THREAD

**Issue by guillaumegarcia13** [ng-select/ng-select#591]
### Expected behaviour
Search terms should he highlighted

### Actual behaviour
ngOptionHighlight works for a split second 
![image](https://user-images.githubusercontent.com/2786038/40786914-8f4ebaae-64ec-11e8-827e-c855053b5200.png)
but new items replace previous (highlighted) ones and so highlight is no longer displayed.
See this stackblitz: https://stackblitz.com/edit/ng-select-highlight

### More Info
ng-select version: 2.0

browser: Chrome 66

reproducible in demo page: NO (haven't seen this combination of options?)

**Comment by anjmao** [comment]
Hi @guillaumegarcia13, thanks for reporting. it looks like https://github.com/ng-select/ng-select/blob/master/src/ng-select/ng-option-highlight.directive.ts#L30 is causing this issue since ngOnChanges may not be trigger on typeahead items change.

**Comment by omexus** [comment]
Hi - I am using version 1.5.2 (w/angular 4) - I read somewhere that changes/fixes would be back compatible but it does not seem the case for this issue, is my only option to upgrade to angular 5 or I may be missing something. 

Thanks!

**Comment by omexus** [comment]
... I meant I have angular 5 (do I need to migrate to 6?)

**Comment by guillaumegarcia13** [comment]
I might be mistaken but the commit [08f91ae](https://github.com/ng-select/ng-select/commit/08f91ae1a369d1778a4aa6b77fe66836e26ff1dd) is only present in 2.3.2 onwards.
The 1.5.2 version is older than the fix.

**Comment by omexus** [comment]
Thanks @guillaumegarcia13, the reason of my question is that, after they released v2.0.0 they been maintaining v1.x, currently on 1.5.2. But you may be right, fix for this issue may have not been put (may won't be) on version 1.x.
