### ISSUE TITLE
Default to select first option (in Async mode)

### ISSUE THREAD

**Issue by nicholassinggih** [ng-select/ng-select#592]
Hi all,

I know this has been asked but not answered in #202. I can't reopen that question, hence this new issue. Defaulting selection to the first option is easy for when the options are static or predefined. But when it's fetched via async data, this is not feasible at the moment. Because NgSelectComponent does not emit anything in the event when the itemsList has been successfully updated. 

So, my suggestion is either:
1. Have something like @Input() firstOptionSelectedByDefault:boolean;  (AND/OR)
2. Have NgSelectComponent emit an (optionsRefreshed) or (optionsRendered) event.

I guess this is more like a feature request or improvement.

PS: I have tried adding .finally in my Observable object, but that's not exactly when the itemsList has been completely updated. 
While in the .map of the Observable will not exactly give us the NgOption array, which I need to pass to NgSelectComponent's select method.

**Comment by anjmao** [comment]
Hi @nicholassinggih, have you tried setting your ngModel to first items element?
```ts
selectedItem = null;
items = [];
getItems().subscribe((items) => {
   this.items = items;
   this.selectedItem = items[0];
})
```

```html
<ng-select [ngModel]="selectedItem" [items]="items"></ng-select>
```

**Comment by nicholassinggih** [comment]
Hi @anjmao, I can't do it via template because I'm writing a dynamic component that should be able to handle different cases. 

Is there a way I can update the ngModel in the TypeScript code? 

```
ViewChild(NgSelectComponent) mySelect;

....


this.data$ = this.data$.map((items) => {
/*
// Update the NgModel here
         if (items && items.length > 0) {
               mySelect.selectedItems.push(items[0]); 
               mySelect._updateNgModel();  
         }
*/
return data;
})
```
