### ISSUE TITLE
@ng-select Weird Behavior

### ISSUE THREAD

**Issue by mixtou** [ng-select/ng-select#594]
Please fill below information if issuing a bug report. 
### Expected behaviour
It should render the data in drop down box

### Actual behaviour
I am using Angular 6 so i downloaded the @ng-select/ng-select version 2.1.2 for autocomplete input box. However the values are not rendered in ng-select dropdown box. They are there however because i can select them and they appear in form.value. However they are not shown in the dropdown like they are invisible, or in white color. I am using a service to get the values using httpClient and then i pass those values into [items]. My code is the following.

For the code see:
https://stackoverflow.com/questions/50638454/ng-select-weird-behavior

### More Info
ng-select version: 2.1.2

browser: chrome 66.0.3359.181

reproducible in demo page: NO
I can't use the same service to retrieve data

Bellow there is a screenshot of the problem:

<img width="1592" alt="ng-select" src="https://user-images.githubusercontent.com/9952442/40828787-43297f26-658a-11e8-9479-7b031fa1aebb.png">

See the Empty Drop Down Box
See The Forms Value Below of the selected item
See the data in JavaScript Console

**Comment by varnastadeus** [comment]
@mixtou `[bindLabel]="name"` you don't have property name in your data set

**Comment by mixtou** [comment]
It doesn't make any difference. I still get the exact same behavior.

**Comment by mixtou** [comment]
I added the [bindLabel]="name" as you suggested but i get exactly the same. Could it be something with the css???

**Comment by mixtou** [comment]
If you see carefully my code you will see that [bindLabel] exists in specialty ng-select field but i get exactly the same. No values rendering.

**Comment by mixtou** [comment]
Hasn't anyone else having the same problem?? Haven't found anything similar when googling it.

**Comment by varnastadeus** [comment]
@mixtou, bindLabel should point to property in your data model, in your case it could be `bindLabel="firstName"`

**Comment by mixtou** [comment]
Sorry but in the console are not logged the cities and specialties. My mistake. My city data model is the following so _"name"_  attribute is correct.

```
export class City {

  _id: number;
  _name: string;
  _patients: Patient[];
  _doctors: Doctor[];

  get id(): number {
    return this._id;
  }

  set id(value: number) {
    this._id = value;
  }

  get patients(): Patient[] {
    return this._patients;
  }

  set patients(value: Patient[]) {
    this._patients = value;
  }

  get doctors(): Doctor[] {
    return this._doctors;
  }

  set doctors(value: Doctor[]) {
    this._doctors = value;
  }

  get name(): string {
    return this._name;
  }

  set name(value: string) {
    this._name = value;
  }
}
```

**Comment by mixtou** [comment]
If i was using the wrong field form.value wouldn't update correct. Also submitting the form inserts the values correctly to database. So the problem i believe is somewhere else.

**Comment by mixtou** [comment]
I am using it and is not working…

**Comment by varnastadeus** [comment]
can you create reproducible example in stackblitz.com instead saying it is not working?

**Comment by mixtou** [comment]
I will try, however i can't use the exact same api to get data

**Comment by mixtou** [comment]
Could it be the greek fonts??

**Comment by mixtou** [comment]
I cannot reproduce it in stackblitz because the http api is not applicable. However by inspecting the page source i realized by inspecting the component generated source code contains the following:

<div class="ng-option ng-star-inserted" role="option" id="a966cd8e509a"><span class="ng-option-label ng-star-inserted"></span></div>

where i see [object Object] and not any values. I believe that is why nothing is displayed.
Any ideas how to solve it??
In my code i retrieve values by:

```
getRelatedData() {
    this.doctorsService.getRelatedData().subscribe(
      results => {
        this.specialties = results[0];
        this.cities = results[1];
        console.log('CITIES: ' + JSON.stringify(this.cities));
        console.log('SPECIALTIES: ' + JSON.stringify(this.specialties));
      }
    );
```

I have tried 
 
this.specialties = [...results[0]];
 this.cities =[... results[1]];
but with no success. I still get empty box.

where doctorsService.getRelatedDate() is:
```
getRelatedData() {
    return forkJoin([this.getSpecialties(), this.getCities()]);
  }

```
 and 

```
getSpecialties(): Observable<Specialty[]> {
    const specialtiesURL = 'specialties/all';

    return this.service.get<Specialty[]>(specialtiesURL)
      .pipe(catchError(ErrorHandler.handleError));
  }
```

 ```
 getCities(): Observable<City[]> {
    const citiesURL = 'cities/all';

    return this.service.get<City[]>(citiesURL)
      .pipe(catchError(ErrorHandler.handleError));
  }
```

Any ideas??

Thanks in advance

**Comment by varnastadeus** [comment]
You don't need the API to reproduce, just set your response as static variable and that's it.

**Comment by mixtou** [comment]
See it here
[https://stackblitz.com/edit/ngx-select-invisible-drop-down-menu-items](url)

**Comment by varnastadeus** [comment]
as I said before use `bindLabel="name"` instead of `[bindLabe]l="name"`. If you use brackets the value name is interpolated

**Comment by mixtou** [comment]
Oh god, that was so simple. I lost two days. Thank a lot anyway for your time and patience.

**Comment by varnastadeus** [comment]
lol, I told you the answer 3 days ago

**Comment by mixtou** [comment]
One more stupid question please. 
In some dropdown fields i would like to concat the values of two different fields. Can i use bindLabel="firstName lastName" or something similar??

Thanks in advance again

**Comment by varnastadeus** [comment]
use `ng-option-tmp` and construct it yourself. https://ng-select.github.io/ng-select#/templates

**Comment by mixtou** [comment]
Great Thanks a Lot

**Comment by AbhiruchiMaurya** [comment]
> as I said before use `bindLabel="name"` instead of `[bindLabel]="name"`. If you use brackets the value **name** is interpolated

I used the above but its not working in Firefox. I have the same issue.
