### ISSUE TITLE
unable to set value in ansyc in formcontrol

### ISSUE THREAD

**Issue by manuelapop** [ng-select/ng-select#597]
Please fill below information if issuing a bug report. 
### Expected behaviour
I should be able to set the value a formcontrolname in an ansyc multiselect

### Actual behaviour
unable to set the value
### More Info
ng-select version: latest
browser: chrome
reproducible in demo page: [YES/NO] no
how do you set the formcontrolname of an ansyc multiselect. this is not working for me

 people3$: Observable<Person[]>;
  people3Loading = false;
  people3input$ = new Subject<string>();
   selectedPersons: Person[] = <any>[{ name: 'Karyn Wright' }, { name: 'Other' }];
  heroForm: FormGroup;

  ngOnInit() {
    this.heroForm = this.fb.group({
      selectedPersonItem: this.selectedPersons
  });

    this.loadPeople3();
  }

 private loadPeople3() {
    this.people3$ = concat(
        of([]), // default items
        this.people3input$.pipe(
           debounceTime(200),
           distinctUntilChanged(),
           tap(() => this.people3Loading = true),
           switchMap(term => this.dataService.getPeople(term).pipe(
               catchError(() => of([])), // empty list on error
               tap(() => this.people3Loading = false)
           )) 
        )
    );
}
<form [formGroup]="heroForm" novalidate>
        <ng-select [items]="people3$ | async"
                   bindLabel="name"
                   [addTag]="true"
                   [multiple]="true"
                   [hideSelected]="true"
                   [loading]="people3Loading"
                   [typeahead]="people3input$"
                   formControlName="selectedPersonItem">
        </ng-select>

**Comment by manuelapop** [comment]
I figured out how to select the values, but I still have one problem.
I can only make the above work when I use the bindLabel and then I set the selected to the label. but I want the above behaviour with asyc and autocomplete for single only and be able to get the IDs. I cannot get the id or assign the id, I can only assign the label. Please help. I need tp be able to bind the value and get the id for single asycn autocomplete.

<form [formGroup]="heroForm" novalidate>
        <ng-select [items]="people3$ | async"
                   bindLabel="name"
                   [addTag]="true"
                   [multiple]="true"
                   [hideSelected]="true"
                   [loading]="people3Loading"
                   [typeahead]="people3input$"
                   formControlName="selectedPersonItem">
        </ng-select>

**Comment by varnastadeus** [comment]
just use `bindValue="id"` then 🤔

**Comment by anjmao** [comment]
@manuelapop Hi, it would be great if you can format your code properly like this:

```ts
ngOnInit() {
   this.heroForm = this.fb.group({
   selectedPersonItem: this.selectedPersons
});
```

not like this

```
ngOnInit() {
this.heroForm = this.fb.group({
```
selectedPersonItem: this.selectedPersons
});

It should be hard, thanks.

**Comment by varnastadeus** [comment]
If you are using bindValue then set your model with id of a person. 
Another option is to use `[compareWith]` and pass your custom compare function.
