### ISSUE TITLE
Keyboard input not working

### ISSUE THREAD

**Issue by venkata82** [ng-select/ng-select#598]
Please fill below information if issuing a bug report. 
### Expected behaviour
Select box should have keyboard input option.
Eg: States select Keyin "T" should show "Texas" & "Tennesse" states. 

### Actual behaviour
Not able to input or filter.  but, able to move up / down using keys.

### More Info
ng-select version: 1.2.1
![image](https://user-images.githubusercontent.com/2564808/40997724-3dd4d5a4-68cb-11e8-8d5f-4a0f5d838a2e.png)

browser: Chrome

reproducible in demo page: NO, demo one is set up with Angular 6.

**Comment by varnastadeus** [comment]
It was introduced in version 1.3

**Comment by venkata82** [comment]
I upgraded it to 1.5.2, still same issue.

**Comment by varnastadeus** [comment]
then create reproducible example since I am not sure what you are talking about.

**Comment by venkata82** [comment]
Works well after upgrading it to 1.3. Thanks for quick help.
