### ISSUE TITLE
HELP - [DOM] Found 2 elements with non-unique id #:

### ISSUE THREAD

**Issue by fernandozago** [ng-select/ng-select#599]
Please, this MAYBE a bug.
I found a way to reproduce. It seems that the problem isn't into the component, is a html bug ?

### Expected behaviour
Maybe input elements should have a generated unique id ?

### Actual behaviour
I'm getting an error on Chrome 66.0.3359.181
[DOM] Found 2 elements with non-unique id #:
[Image1](https://pasteboard.co/HoDSOSc.png)

the Html i beleive that is rendering alright
[Image2](https://pasteboard.co/HoDTfxo.png)

Describe how it actually works or even better create example using [StackBlitz] ( I DID IT !! )
https://stackblitz.com/edit/ng-select-example-wwjwtt?embed=1&file=app/app.component.ts

Heres a simple example
https://jsfiddle.net/2qf718de/

If the input type="password" is removed from html, and then recompiled, the error will go away.

Somebody can explain?

### More Info
ng-select version: 2.1.3

browser: Chrome 66.0.3359.181 

reproducible in demo page: [YES] (Look link above)
And open the chrome dev console

**Comment by fernandozago** [comment]
Ohh... i see. @anjmao Thank you!

I fixed my code now, adding the attribute "labelForId".

But, this is still a bug right ?
Because is not required the attribute "labelForId" to be set in the element tag.

**Comment by stevethemacguy** [comment]
It's only required if there is more than one ng-select visible in the DOM at the same time, but I agree that it feels like a bug. Maybe ng-select elements can create generic ids by default if none is provided? Either way, the readme should probably be updated to show that "labelForId" is required in these situations.

**Comment by sensoeurn** [comment]
`Cause the name of id must not same attribute name or duplicate name.
Example <select id="type"><option>1</option><option>2</option></select>
above will show warning in console.
=> I changed id="category_type"  and warning go away.
This worked for me.

**Comment by kumawatdhiren** [comment]
Duplicate of #
