### ISSUE TITLE
Selected value is not set after data loaded asynchronous

### ISSUE THREAD

**Issue by anjmao** [ng-select/ng-select#60]
### Expected behaviour
Set selected item after items loaded asynchronous

### Actual behaviour
Selected item is not set because `writeValue` method is called before items input is updated. Possible solution is to initialise itemsList only once and update its items on other changes.
https://ng-select.github.io/ng-select#/forms Selected photo should be first one after items loaded from backend.

### More Info
ng-select version: 0.2.1
reproducible in demo page: YES

**Comment by smasala** [comment]
Is there a workaround for the time being?

**Comment by varnastadeus** [comment]
@smasala it is fixed.

**Comment by smasala** [comment]
@varnastadeus if I see right though only in the next major version which isn't out yet
