### ISSUE TITLE
Show ng-option on multi lines

### ISSUE THREAD

**Issue by Skrytch** [ng-select/ng-select#600]
Hi and thx for this really good project!

### Expected behaviour
When text of ng-option is longer then the width, I need to have word-break and 2 or more lines...

### Actual behaviour
white-space : nowrap and text-overflow : ellipsis.

I custom many things with css but I'm not able to custom that! Maybe I make somethings wrong.
There is a special way to achieve that?
Thx.

### More Info
ng-select version: 1.5.2

Angular 5

browser: Chrome/firefox/ie

**Comment by Skrytch** [comment]
Sorry, 
I just make a mistake. 
It's work great.

++

**Comment by erpankajsingla** [comment]
Hi @Skrytch, how did you achieve this ?

**Comment by Skrytch** [comment]
Hi @erpankajsingla , i'm not sure because I don't work on this project anymore.

Try this in your css :

```
.ng-dropdown-panel .ng-dropdown-panel-items .ng-option {
    white-space: normal!important;
}
```

I hope it will help you!

Regards.

**Comment by erpankajsingla** [comment]
Thank you for your reply @Skrytch , !important is what I am using. 

Although, the styles I am using is more specific than the default one, it won't get picked up. Probably something to do with the load order of the styles. Wish there was some more documentation about using custom styles with this component
