### ISSUE TITLE
Multiselect checkbox

### ISSUE THREAD

**Issue by anjmao** [ng-select/ng-select#607]
It should be possible to create multiselect checkbox items which are grouped using custom templates.
Tasks:
- [ ] Add example in separate demo page.

Example:
<img width="730" alt="multicheckbox" src="https://user-images.githubusercontent.com/3028012/41160124-5dc2607a-6b37-11e8-96d1-53076f5f4c9e.png">

**Comment by tanjoreraj** [comment]
Hi,

Can we use this Multiselect Checkbox with Reactive forms????

Unable to fetch the selected data and unable to check the child when parent is checked.
