### ISSUE TITLE
Custom Styling

### ISSUE THREAD

**Issue by JonDeery** [ng-select/ng-select#608]
Hello,

I am trying to apply custom styling to ng-select and I cannot get it to work... not sure if it is a bug or me doing something wrong.

Ng-Select Code:
          <ng-select class="custom"
                     [items]="activeMarkets"
                     formControlName="market"
                     bindLabel="shortDescription"
                     id="marketSelect"
                     bindValue="marketId"
                     [(ngModel)]="selectedMarket"
                     [virtualScroll]="true">
          </ng-select>
SCSS:
ng-select.custom .ng-select-container {
  position: relative !important;
  top: 0;
  border-color: transparent !important;
  border-bottom-color: black !important;
  border-bottom-width: 0.0625rem !important;
  background-color: transparent !important;
  border-radius: 0px;
}

If I only do ng-select.custom {CSS CODE} then I can see it applied to ng-select but right when I try to go deeper into ng-select-container then it does not work.

Thank you so much!

### More Info
ng-select version: 1.5.2

browser: Chrome

reproducible in demo page: Not sure, having issues running demo locally

**Comment by varnastadeus** [comment]
I think this should answer all your questions https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity

**Comment by JonDeery** [comment]
Hello

Sorry for the late response I meant to remove the !important tags those were a last ditch effort to make it work. My issue is that 
.ng-select.custom .ng-select-container {} does not work. 
It will work if it is just .ng-select.custom{}.

I assume I have to be doing something wrong but I believe I am following the ng-select instructions for custom styling.

Thanks

**Comment by razorsyntax** [comment]
Can someone provide an example of scss working at the `.ng-select-container `level?  (Assuming this is possible.)

**Comment by tkstang** [comment]
.ng-select.custom {
  .ng-select-container {
    height: 42px;
    background-color: $nav-active-gray;
    border: 1px solid $form-input-border;
    .ng-value-container {
      color: $select-font-color;

      .ng-placeholder {
        color: $select-font-color;
      }
    }
  }
}

**Comment by tkstang** [comment]
After a bit of research is seems this is because of Angular's view encapsulation.  You can set view encapsulation to none inside of your component and you will be able to modify the styles in your local stylesheet.

import {ViewEncapsulation} from '@angular/core';

@Component({
  templateUrl: 'component.template.html',
  styleUrls: [`component.style.scss`],
  encapsulation: ViewEncapsulation.None
})

**Comment by razorsyntax** [comment]
Setting the encapsulation property as you did worked for me.

**Comment by JonDeery** [comment]
Worked for me as well. Thank you @tkstang so much! I have been stuck on this for far too long.

**Comment by ibbxinovacao** [comment]
thanks @tkstang !

**Comment by marina-ferreira** [comment]
If you are using ViewEncapsulation, your should use special `::ng-deep` selector which will prevent scoping for nested selectors.

```css
.ng-select.custom ::ng-deep .ng-select-container  {            
    min-height: 0px;
    border-radius: 0;
}
```
https://www.npmjs.com/package/@ng-select/ng-select

**Comment by AmineLAHRIM** [comment]
**you can't change style for deep child element if you didn't declare parent one inside other.**
.ng-select.custom {
        .ng-select-container {
            .ng-value-container {
                .ng-value {
                    background-color: #50a5f1;
                    border-color: #50a5f1;
                }
            }
            .ng-arrow-wrapper{
                display: none;
            }
        }

}

**Comment by ashishakm** [comment]
instead of disable can I change color of display data based on binddata flag?

**Comment by AshokNa05** [comment]
Can anyone tell me how can I change the placeholder color on hover that means the text written inside the container?

**Comment by sysmat** [comment]
- for me ng 17 nothing work for custom style
- boostrap 5.3
