### ISSUE TITLE
Modal esc key with select inside.

### ISSUE THREAD

**Issue by wkjesus** [ng-select/ng-select#612]
### Expected behaviour
I think when using inside modal, and appear the dropdown, could be able to press
esc key, and the dropdown go away and keep the modal.
### Actual behaviour
actually if the select is inside a modal and you press esc when dropdown appears. the modal
get close.
### More Info

Instead in the reactive forms example of the documentation.. it happens try out.

**Comment by varnastadeus** [comment]
Thanks for suggestion. I think it should work as you described.

**Comment by tomasszabo** [comment]
Also when dropdown is opened and by pressing Enter, the form is submitted. NgSelect should instead just select the value and close dropdown, but not submit the form (i.e. enter key press should not be propagated). When the dropdown is closed, pressing Enter on NgSelect should submit the form (this is the standard behaviour of classic HTML select element).

**Comment by splintor** [comment]
I would also like `ng-select` to behave this way.
It seems it has a simple fix. In `handleKeyDown()`, in the `KeyCode.Esc` case, simply call `$event.stopPropagation()` after `this.close()`.
