### ISSUE TITLE
Label parameter in the data overwrites the bindLabel property

### ISSUE THREAD

**Issue by ghtjiann4321** [ng-select/ng-select#614]
Please fill below information if issuing a bug report. 
### Expected behaviour
Describe how you think it should work

### Actual behaviour
If the options contains a label parameter the bindLabel option is overwritten by the label parameter

options = [{
name: 'Test',
label: 'Label'
}]

<ng-select bindLabel="'name'"></ng-select>

It should show Test as the bind value but instead it shows the Label value even though the bindLabel is set

### More Info
ng-select version: 6

browser: Chrome, Mozilla, Safari

reproducible in demo page: Yes

**Comment by varnastadeus** [comment]
can you create reproducible example using [stackblitz](http://stackblitz.com/) ?

**Comment by rdavono** [comment]
Why is this closed? This error is still present in the newest release 2.3.0
