### ISSUE TITLE
Emit Add event after the model is updated.

### ISSUE THREAD

**Issue by gicevgoran** [ng-select/ng-select#620]
Change when add event is emitted.

### Expected behaviour
I think that the add event should be emitted after the model has been updated, so the user can revert the action or do something with the model.

### Actual behaviour
The Add event is emitted before the model is updated so in the Add handler/callback the model still has the old value.

Here's the code:
```
select(item: NgOption) {
        this.itemsList.select(item);

        if (this.clearSearchOnAdd) {
            this._clearSearch();
        }

        this.addEvent.emit(item.value);
        if (this.closeOnSelect || this.itemsList.noItemsToSelect) {
            this.close();
        }

        this._updateNgModel();
}
```

**Comment by anjmao** [comment]
@gicevgoran Probably you are correct 👍

**Comment by BruneXX** [comment]
Hi Guys, I've noticed that the (add) output event is not fired when I'm selecting an element form the list of the ng-select.. anyone else has experienced the same behavior?

**Comment by Upendrasengar** [comment]
@BruneXX  could you find the solution I'm having the same issue?
