### ISSUE TITLE
Providing static label

### ISSUE THREAD

**Issue by Varshamathukumalli** [ng-select/ng-select#621]
Hi,

I was trying to bind a static text as a input instead of some placeholder/ from data.
Is there any way to achieve this?

Regards,
Varsha

**Comment by varnastadeus** [comment]
What do you mean `as a input`?

**Comment by Varshamathukumalli** [comment]
In dropdown until unless we select a value, there won't be any label in the textbox. Unlike this, we want to provide a label before hand only .
Is there any way to do so?

Regards,
Varsha

**Comment by varnastadeus** [comment]
Have you tried setting placeholder?

**Comment by Varshamathukumalli** [comment]
Yes, but instead of placeholder we wanted to display label

**Comment by varnastadeus** [comment]
what do you mean by label? do you want placeholder to look same as as selected value?

**Comment by Varshamathukumalli** [comment]
Exactly
