### ISSUE TITLE
Empty array and not displaying the ng-select drop-down

### ISSUE THREAD

**Issue by deepender87** [ng-select/ng-select#622]
I am binding an empty array to the items input. Initially my array will be empty and on drop-down open i will be filling them through Api call. I don't want to use async here. Can you please suggest something better (apart from giving an empty string to array)?

**Comment by varnastadeus** [comment]
Not totally sure what is your question. If it is how to populate your array, then read this https://github.com/ng-select/ng-select#change-detection
