### ISSUE TITLE
Reactive forms and required problem

### ISSUE THREAD

**Issue by virix** [ng-select/ng-select#623]
I'm creating a simple ng-select with required and an empty initial value.

### Expected behaviour
I expect that initially the field has no errors.

### Actual behaviour
The actual behaviour is shown in this example:
https://stackblitz.com/edit/ng-select-example-wbaleb

### More Info
ng-select version: 2.1.3

browser: Chrome, Mozilla, ecc.

reproducible in demo page: YES

**Comment by varnastadeus** [comment]
I would not say this is an error. If you have simple input with required it will also return `required` error. I think you need to check if it touched and has error.

**Comment by virix** [comment]
Ok, thank you. This solves my problem.
I'm using angular material and the behaviour with these components is different.
