### ISSUE TITLE
Disabling the input field without disabling the component

### ISSUE THREAD

**Issue by marianobarbuscio** [ng-select/ng-select#626]
This is probably not a bug , rather a question. Im using ng-select with a default value that should never be clearable. I dont want to allow the user to input any value, just pick from the list. On desktop this isnt a problem but on mobile, when I click on the select, the browser zooms in because the selector field is actually an input and it focuses on it even if it wont let me type in any values. Using [disabled] doesnt help because it disables the control as well and the dropdown doesnt appear. 

How can I achieve not disabling the control, but having the input be disabled (or not be an input at all) ?

### More Info
ng-select version: 2.1.3

browser: Chrome/66.0.3 , Safari IOs (mobile)

reproducible in demo page: [YES]

**Comment by marianobarbuscio** [comment]
Also, this might be related with autocomplete. How can i disable it? I'll post the question while i search other issues for an answer

**Comment by marianobarbuscio** [comment]
Editing the html to remove the autocomplete and set the input as disabled (but not the component) fixes the issue, can this be included into the API ?

BEFORE: 
<img width="331" alt="captura de pantalla 2018-06-16 a la s 16 24 19" src="https://user-images.githubusercontent.com/29992690/41501862-ae512b1a-7182-11e8-9796-6704799edd42.png">

AFTER:
<img width="301" alt="captura de pantalla 2018-06-16 a la s 16 30 51" src="https://user-images.githubusercontent.com/29992690/41501863-ae7806a4-7182-11e8-8ada-cc6be254b851.png">

**Comment by mbarbuscio** [comment]
@varnastadeus

**Comment by varnastadeus** [comment]
@marianobarbuscio there is option `[searchable]="false"`

**Comment by NitishaSrivastav** [comment]
You can use [searchable]="false" for disabling the search option for user
