### ISSUE TITLE
Tooltip functionality

### ISSUE THREAD

**Issue by dthakar007** [ng-select/ng-select#627]
Please fill below information if issuing a bug report. 
### Expected behaviour
Describe how you think it should work
A tooltip should be displayed for items that are too long to fit in the dropdown box. A tooltip should also be displayed for selected items because the selected item text gets hidden if the text is too large to fit in the text area.

### Actual behaviour
Describe how it actually works or even better create example using [StackBlitz](https://stackblitz.com/edit/ng-select-example?file=app/app.component.ts) issue template
Currently, tooltip functionality is not available.

### More Info
ng-select version: [1.4.1]
browser: [Chrome] 
reproducible in demo page: [YES]

**Comment by varnastadeus** [comment]
why not just use custom label and option template and your desired tooltip 🤔

**Comment by absolutehype** [comment]
Right now there is the ability to add a tooltip to the option, sadly not on the `ng-label-tmp` as it sits underneath the search input.
