### ISSUE TITLE
Two objects for bindLabel

### ISSUE THREAD

**Issue by PierBJX** [ng-select/ng-select#628]
### Expected behaviour
Hi Everyone,
I would like to know if it was possible to add two object for bindLabel such like that instead of using ng template:
```
 <ng-select [items]="users | async" [multiple]="true" [closeOnSelect]="false" [hideSelected]="true" bindLabel="firstname email" bindValue="_id" placeholder="Select people" [(ngModel)]="userselected" name="sharedUser" required #sharedUser="ngModel">
```

### Actual behaviour
For the moment I use ng template to add both but I would like to keep the same basic style.
```
                <ng-template ng-option-tmp let-item="item" let-index="index" let-search="searchTerm">
                  <h5>{{item.firstname}}  |  {{item.email}}</h5>
                </ng-template>
```

### More Info
ng-select version: v2.0.0

browser: Mozilla 60.0.2 (64-bit)

**Comment by anjmao** [comment]
Hi @PierBJX, for this case  on your data array you can create your custom property name something like `label` which combines firstname and email and use it as bindLabel. Combining two objects into bindLabel is not supported as this is very specific case and you can use custom templates for it. Hope this helped.

**Comment by tanmayparmar** [comment]
did you able to figure out this? Because i am having same user case, where i wanted to display Firstname and last name

**Comment by PierBJX** [comment]
In the component.ts, I get all the users from the server which are saved in a list of users (**data**). Then, I iterate through all the items of data and I add another element in the Object User bindName which combine firstname and lastname.
```
  ngOnInit() {
    this.currentUserId = this.auth.getUserDetails()._id;
    this.shared.changeShowInfo(false);
    this.api
      .getAllUsers()
      .takeUntil(this.destroy$)
      .subscribe(
        data => {
          for (let item in data) {
              data[item].bindName =
                data[item].firstname + " " + data[item].lastname;
              this.users.push(data[item]);
          }
        },
        err => {
          console.log(err);
        }
      );
}
```

In the HTML, **bindLabel="bindName**:
```
<ng-select [items]="users" [multiple]="true" [closeOnSelect]="false" [hideSelected]="true" bindLabel="bindName" bindValue="_id"
                    placeholder="Select people" [(ngModel)]="experiment.user_permission" name="sharedUser" required #sharedUser="ngModel">
             <ng-template ng-option-tmp let-item="item" let-index="index" let-search="searchTerm">
                      <h5>{{item.firstname}} {{item.lastname}}</h5>
             </ng-template>
</ng-select>
```

**Comment by HarounGazzah** [comment]
`this.resourceService.getResources().subscribe(res => {
  let ress: any[];
  ress = res;
  ress.map((i) => { i.fullName = i.firstname + ' ' + i.lastname; return i; });
  this.resources = ress;
});`
___________________________
`<ng-select [items]="resources" [multiple]="true"
                      name="resource"
                      bindLabel="fullName"
                      bindValue="reference"
                      notFoundText="Aucun élément trouvé"
                      typeToSearchText="tapez plus de 3 caractères pour trouver la resource"
                      [loading]="resourcesLoading"
                      [typeahead]="resourcesInput$"
                      [(ngModel)]="positioning.resourceReference">
                      </ng-select>`

**Comment by ChrisMarkatselis** [comment]
@HarounGazzah Thank you for your help!!! So helpful without using ng-template and more accurate!!!
