### ISSUE TITLE
Using checkbox for selection 

### ISSUE THREAD

**Issue by Varshamathukumalli** [ng-select/ng-select#629]
Hi,

Instead of highlighting the selected item, i want to display checkbox using custom template and on click of the item that checkbox needs to be selected.
How can we do that

Regards,
Varsha

**Comment by anjmao** [comment]
Hi, I'm currently working on a sample for it, it is not supported yet https://github.com/ng-select/ng-select/issues/607.

**Comment by Varshamathukumalli** [comment]
When can we expect this to be released

**Comment by varnastadeus** [comment]
I don't think you need that to be released, just select item while clicking checkbox.

**Comment by anjmao** [comment]
Hi @Varshamathukumalli, I added example https://ng-select.github.io/ng-select#/multiselect-checkbox, it may still miss some features, feedback is welcome.

**Comment by mohitj27** [comment]
but when i using angular material checkbox this behaviour gets altered what can i do suggest something and i also want when checkbox click then it only push otherwise no
please help me
