### ISSUE TITLE
Dealing with 0 inside ng select

### ISSUE THREAD

**Issue by LiamDotPro** [ng-select/ng-select#631]
Hello,

We are currently using `ng-select` within our production app which relies on a proprietary data layer which we are not able to modify, one of the caveats of this is the following scenario:

```
Table 1 - foo
------------------
id | categoryId
------------------
1 | 0
2 | 10
```
In the above table whenever `foo` is created a category is is initialized by default with 0 rather than null, 0 has no category assigned to it within our category table.

This leads to the problem where when we receive a view model from the api we are given a foo object that has 0's which means when we do `([ngModel])="someObj.category"` the select box starts with a selected empty field, though the select box functions as intended but we can no longer see the placeholder text initially. I personally do not wish to add further resets that returns our objects field back to null or on creation checks for 0 in over 120 tables worth of view models, it would take forever.

Potential solution:
I suppose this is a feature request but I was thinking maybe we could expand the functionality of `ng-select` to allow us to set an option (this would default as off ofc) that considers 0 to be unselected or rather doesn't attempt to match a label to a value?

I'd be more than willing to expand the information here if you have any questions.

### More Info
ng-select version: 2.0.0

browser: Chrome

reproducible in demo page: N/A

**Comment by varnastadeus** [comment]
0 is valid value and if you want to handle it differently, I would suggest using `ng-label-tmp` and then showing placeholder or label.

**Comment by LiamDotPro** [comment]
I'm not really sure how using a template will work here as it'll still show it as being selected still, 

```<ng-select [items]="cities" [(ngModel)]="selectedCity" bindLabel="name" bindValue="name">
    <ng-template ng-label-tmp let-item="item">
       <ng-template *ngIf="!!item.id">
        <img height="15" width="15" [src]="item.avatar"/>
        {{item.name}}
      </ng-template>
    </ng-template>
</ng-select>```

How would you suggest I update the selects to function as intended?

**Comment by varnastadeus** [comment]
I was thinking something like this
```html
<div *ngIf="item.id == 0">select one</div>
<div *ngIf="item.id">{{item.name}}</div>
```

**Comment by LiamDotPro** [comment]
This kind of works, though it's not ideal as the displayed text no longer looks like a placeholder and the X is still present on the select:

![image](https://user-images.githubusercontent.com/13067327/41660402-d7a482c8-7493-11e8-8fb9-f4d58a6c6b3d.png)
