### ISSUE TITLE
angular 6 ERROR TypeError: items.map is not a function

### ISSUE THREAD

**Issue by bdairy** [ng-select/ng-select#632]
Hey there,
I am using **Angular 6**
Trying to get the data from the server as this example https://github.com/ng-select/ng-select/blob/master/demo/app/examples/search.component.ts

this is my ng-select :

`  <ng-select [items]="employees | async" [multiple]="isMultiple" placeholder="Select Employee" [appendTo]="'body'" [(ngModel)]="selectedEmployee"
    [hideSelected]="true" [loading]="loading" [typeahead]="employeesInput"></ng-select>`

 I am getting the employees as an observable the same way in the example... but I am getting the error  _ERROR TypeError: items.map is not a function_ it is in ng-select.js file,, while the items is recieved as a string of my typeahed,, but the map is not defined..

and since I am Angular 6 I've change the concat as the new RXJS so now it is an operator.

**Comment by varnastadeus** [comment]
https://github.com/ng-select/ng-select/blob/master/README.md#versions
@bdairy make sure you are using correct version

**Comment by bdairy** [comment]
The error was with the subscriber fro my side,, kept using the concat pipe assuming it gives the same output as concat in prev versions of rxjs

**Comment by lucianomilen** [comment]
Excuse me, @bdairy how did you fix it? I'm having the same problem, didn't quite understand what's wrong with my `concat pipe`

**Comment by Ismaestro** [comment]
@bdairy can you provide your final solution? we have the same problem ...

**Comment by anton-rukhlin** [comment]
same issue here. can you give a bit more info on how to resolve this? some of us are noobs and that sentences does not draw a complete picture. thank you

**Comment by osmolyar** [comment]
Same issue here

**Comment by maceteligolden** [comment]
this error occurs when the map function is being used on a data that not an array. i hope this helps
