### ISSUE TITLE
addTags as strings (not objects => regression?)

### ISSUE THREAD

**Issue by juristr** [ng-select/ng-select#633]
Please fill below information if issuing a bug report. 

### Expected behaviour

This is related to #315. When I configure ng-select as follows

```
<ng-select [items]="cities"
                   [addTag]="true"
                   [multiple]="true"
                   placeholder="Select city"
                   [(ngModel)]="selectedCity">
        </ng-select>
```

with `cities` being empty, if I add new tags, I'd like to get them as string array.

```
[
   'selected 1', 'selected 2',...
]
```

### Actual behaviour

Instead, if  `cities` being empty, I don't get a string array as a result of adding new tags, but rather objects of the following structure

```
{
    label: '....'
}
```

Here's a [StackBlitz](https://stackblitz.com/edit/ng-select-bug-addtags-label?file=app/app.component.ts) that reproduces it.

The root cause of this is that at these lines

https://github.com/ng-select/ng-select/blob/03270677eb4e4f93a83c6db3afc2e6334194fe6c/src/ng-select/ng-select.component.ts#L487-L489

the 1st item is being taken from the source to determine the resulting format, defaulting to `{ label: '...' }`.

I have a local branch with a failing test for this and I'd also be willing to contribute a PR. Just wanted to first open an issue to start discussion on how to implement it.

### More Info

ng-select version: latest `v2.2.0`

reproducible in demo page: (probably, there is no specific demo that shows the outcome)

**Comment by juristr** [comment]
If I'm not totally wrong, I think this line

```
this._primitive = !firstItem ? this._primitive : !isObject(firstItem); 
```

should be 

```
this._primitive = !firstItem ? (this._primitive = true ) : !isObject(firstItem); 
```

🤔

**Comment by varnastadeus** [comment]
In this case there is no way to check whether it is primitive and your suggestion only implies it should be primitive if there are no items set, which in my opinion doesn't change anything. I would suggest adding `addTag` as fn and returning term straight away. 

```javascript
addTag = (term) => term;
```

**Comment by juristr** [comment]
Hmm...I can explore that as well. However the line I changed in my PR seems to be wrong anyway 🙂, as the if condition didn't have any effect.
