### ISSUE TITLE
Programmatically set search text and trigger search

### ISSUE THREAD

**Issue by alexishacks** [ng-select/ng-select#635]
Please fill below information if issuing a bug report. 
### Expected behaviour
The user clicks the component to modify the existing selected value. The field is automatically populated with the existing value as the search term and shows the options.

### Actual behaviour
After clicking the component, the existing value still shows as the value but the user needs to retype the whole search term all over again.

### More Info
ng-select version: 2.1.3

browser: Google Chrome 67.0.3396.87 (Official Build) (64-bit)

reproducible in demo page: N/A

**Comment by varnastadeus** [comment]
This should work

```html
<ng-select 
  #select
  [items]="items"
  (open)="select.filterValue = selected; select.filter(select.filterValue)" 
  [(ngModel)]="selected">
</ng-select>

```
