### ISSUE TITLE
Configuring position of input textbox

### ISSUE THREAD

**Issue by Varshamathukumalli** [ng-select/ng-select#636]
Hi,

Currently the input search box is coming beside the selected values. Is there any way to change the textbox position below the selected values/ just above the options.

Regards,
Varsha

**Comment by varnastadeus** [comment]
Do you mean inside dropdown?

**Comment by Varshamathukumalli** [comment]
yeah

**Comment by varnastadeus** [comment]
there is example in the https://ng-select.github.io/ng-select#/templates, but it doesn't work perfectly and there is feature request to support it #556
