### ISSUE TITLE
Clearable doesn't reset the searched data

### ISSUE THREAD

**Issue by carlhussey** [ng-select/ng-select#64]
Please fill below information if issuing a bug report. 
### Expected behaviour
When clicking on the clear icon, I would expect that upon entering the field, the previous results would not be shown.

### Actual behaviour
After clearing the field, upon selecting the input for a search, it shows the last results it found instead of starting over.

### More Info
ng-select version: 0.2.1

browser: chrome

reproducible in demo page: yes

Visit: https://ng-select.github.io/ng-select#/filter-server

- Enter a search term.
- Clear the term.
- Open the field, previous results are shown.

**Comment by anjmao** [comment]
Thanks for reporting, this is quit easy to fix, probably will be fixed today :)

**Comment by anjmao** [comment]
@carlhussey I pushed new version to npm, here is demo with this case https://ng-select.github.io/ng-select#/filter-server.

**Comment by carlhussey** [comment]
Looks good, solves the problem :) - nice work!
