### ISSUE TITLE
Publicize or Expose More APIs

### ISSUE THREAD

**Issue by firstor** [ng-select/ng-select#640]
I like the component and now I want more public APIs on this component.

**_For example:_**
In my code, I need to clear the element by script, but I couldn't find any API for it on the documentation. I looked through the code and then found a right method `handleClearClick`. Everything works fine as my expectation, however, I am not sure it's a good way ~ since `handleClearClick` has not been publicized on the documentation, I am wondering if I did do right thing.

SO could you publicize or expose more APIs that can make us operate the component possibly by script?

Thanks.

**Comment by varnastadeus** [comment]
The reason there is only some of the methods publicised is because generally you should not use anything else unless you have very specific use case.

In your case, you should clear you model without touching any apis.

**Comment by firstor** [comment]
@varnastadeus Thanks for the update. As I said, I need to reset the element by script at some circumstance. What I want is to expose one public method `clear()`. Could you help me?

**Comment by varnastadeus** [comment]
Just reset your model, you don't to call any API.

**Comment by firstor** [comment]
@varnastadeus Ok, so I tried to reset model on my script. Here is sample:
```html
<ng-select [items]="items" #myselect
            bindLabel="title"
            bindValue="imdbId"
            [loading]="loading"
            [placeholder]="placeholder"
            (change)="this.itemChange($event)"
            [(ngModel)]="query"
            [typeahead]="typeAhead"
            [clearSearchOnAdd]="true">
  <ng-template ng-option-tmp let-item="item" let-index="index"  let-search="searchTerm">
    ...
  </ng-template>
</ng-select>
```
I tried to clear select in the following:
```ts
// works just as my wish ~ but not recommended by you?
this.myselect.handleClearClick();
```
```ts
// clears the search list but search text/term still exists on the box even with `x` button
this.query = '';
this.items = [];
```
Could you please give me more hint?

**Comment by varnastadeus** [comment]
Create reproducible example so I could all code you are using

**Comment by firstor** [comment]
@varnastadeus Here is more:
```ts
items: MyItem[] = [];
query;
loading = false;
typeAhead = new Subject<string>();
@ViewChild('myselect') private myselect: ElementRef;

constructor(private itemsService: MyItemsService,
              private cd: ChangeDetectorRef,
              ...) {
}

ngOnInit() {
  this.queryItems();
}

private queryItems() {
  this.typeAhead.pipe(
        tap(() => this.loading = true),
        distinctUntilChanged(),
        debounceTime(300),
        switchMap(term => this.itemService.query(term)),
      ).subscribe(
        (res) => {
          if(res is valid) {
            this.items = res;
            this.loading = false;
            this.cd.markForCheck();
          } else {
            this.items = [];
          }
          this.loading = false;
        },
        () => {
          this.items = [];
          this.queryItems();
          this.loading = false;
        }
      );
}

// will be invoked outside of this component at a certain criteria
// should clear ng-select
clear() {
    this.query = '';
    this.items = [];
    // (this.myselect as any).handleClearClick(); // it works just as my wish
  }
```

**Comment by varnastadeus** [comment]
set query to null or undefined, since `''` is valid value.

**Comment by firstor** [comment]
@varnastadeus Thanks for your hint. I just tried with `null` assignment and it doesn't still work.
For more info, at the very first time, it works, but not work 2nd, 3rd, ...

`(this.myselect as any).handleClearClick();` works as my wish.
So I think you can expose `close()` with the following body?
```ts
close() {
  this.handleClearClick();
}
```

**Comment by varnastadeus** [comment]
Then create reproducible example because it should. That method won't get exposed because it is used while clicking clear icon and no more than that.

**Comment by firstor** [comment]
@varnastadeus The above example is not enough?

**Comment by varnastadeus** [comment]
No it is not. There are few [examples](https://ng-select.github.io/ng-select#/multiselect) in demo page how to properly clear your model which works perfectly fine. If you can't reproduce it, there is not much I could do.
