### ISSUE TITLE
items.map is not a function

### ISSUE THREAD

**Issue by ChristianGalvez23** [ng-select/ng-select#641]
I have in my html:
`<ng-select #unidadesMedicas bindLabel="nombre" bindValue="id" [items]="unidadesMedicas" [placeholder]="'Seleccionar'" [clearable]="false"></ng-select>`

At the beginning I have an empty array:
`public unidadesMedicas = new Array<any>()`

So, when I load my component (where ng-select is) throws an error related to: **items.map is not a function**

PD. The view renders good but I don't see my items in the ng-select.

But I don't a understand why. I think, ng-select internally doesn't take the array.

### More Info
ng-select version: 1.5.2

browser: Chrome

reproducible in demo page: No

**Comment by varnastadeus** [comment]
Probably you are using wrong angular version

**Comment by eloufirhatim** [comment]
I have the same issue, using ng-select 1.5.2 and Angular 5, do you found a solution?

**Comment by ChristianGalvez23** [comment]
I fixed using setTimeout function.
This is because when I was trying to load the data from server and assign it to select, the select doesn't exist in tha view yet. I had to wait Angular renders the view and when that happened I assigned the data to select.

**Comment by FelipeFelizardo** [comment]
Got same problem here

**Comment by chriszichrisz** [comment]
If you load the data from a server add `async`, `setTimeout` works, but it seems a bit hacky.

`[items]="data | async"`
