### ISSUE TITLE
Integrating in Bootstrap input group height and border error

### ISSUE THREAD

**Issue by Disane87** [ng-select/ng-select#642]
### Expected behaviour
Border color and height should be applied like a normal input group of bootstrap:
https://getbootstrap.com/docs/4.0/components/input-group/#buttons-with-dropdowns

### Actual behaviour
The border color is not the color of the inputgroup and the height is not suitable:
![grafik](https://user-images.githubusercontent.com/956158/41918584-f34d6828-795c-11e8-98fa-ad0ff83d4c6e.png)

Both should be used from the inputgroup.

### More Info
ng-select version: 2.1.0

browser: FF/Chrome

reproducible in demo page: 
https://stackblitz.com/edit/ng-select-luyb3j

**Comment by varnastadeus** [comment]
Default theme is not based on bootstrap 4 that's why it has its differences. To make it work adjust css for your needs.
