### ISSUE TITLE
Making ng-select work with strict Content Security Policy (CSP) enabled.

### ISSUE THREAD

**Issue by bjuhr** [ng-select/ng-select#643]
Please fill below information if issuing a bug report. 
### Expected behaviour

Expected ng-select to work with a strict Content Security Policy (CSP) enabled.

### Actual behaviour
Describe how it actually works or even better create example using [StackBlitz](https://stackblitz.com/edit/ng-select-example?file=app/app.component.ts) issue template

If a strict Content Security Policy (CSP) is enabled, it will block inline styles for NgDropdownPanelComponent and NgSelectComponent.

Workarounds:
* Allow "unsafe-inline" for styles in the CSP.
* Copy styles from NgDropdownPanelComponent and NgSelectComponent into a separate CSS file.

Error message received:
Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-FZSQTEwWo0g0IjrvFF1ceP7uyjjId/UWptsH3tRRklg='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.

Suggestion for solution: Since you're already using ViewEncapsulation.None for your components you would only have to extract the styles in to a separate CSS file to fully support CSP.

### More Info
ng-select version: 2.3.1

browser: Chrome Version 67.0.3396.87

reproducible in demo page: [NO]

**Comment by TokenR1ng** [comment]
Wanted to ask if something can be done about this?

The unsafe-inline problem comes mainly from Angular itself, when a component defines its styles by styleUrls and a separate SCSS file. Angular then creates a <style> entry in the DOM, which violates strict CSP. In the project, NgSelectComponent refers to ng-select.component.scss.

If the styles could be defined in the global styles file, or as suggested by @bjuhr in a separate file instead, the lib would be strict CSP compliant.

Thanks.
