### ISSUE TITLE
Can't reposition input cursor with a mouse

### ISSUE THREAD

**Issue by shedar** [ng-select/ng-select#644]
### Expected behaviour

When a user types something in autocomplete field and then clicks on a certain text position to fix a typo - input cursor should be moved to a clicked position

### Actual behaviour

A cursor can be moved with arrow keys, but can't be moved with mouse clicks.
Reproducible in [official demos](https://ng-select.github.io/ng-select#/filter). 

### More Info
ng-select version: 2.3.1

browser: Chrome 67.0.3396.87

reproducible in demo page: YES

**Comment by hankolsen** [comment]
Aaah, that bugs me too!
