### ISSUE TITLE
not display text (ngxtranslate)

### ISSUE THREAD

**Issue by SrgGs** [ng-select/ng-select#649]
When I insert text in option as {{'key' | translate}} 
and refresh page, translations disappear 

AND 

when change language text in option not change 

https://github.com/ngx-translate/core << module translation

```
    <ng-select #resetReferenceType="ngModel" class="custom" placeholder="{{'sort.all' | translate}}" [clearable]="false" [markFirst]="true"
      [searchable]="false" [(ngModel)]="interactionTypeId" (add)="changeInteractionType($event)" bindLabel="label" bindValue="id">
      <ng-option [value]="'ALL'"> {{'sort.all' | translate}}</ng-option>
      <ng-option [value]="'OPEN'"> {{'sort.open' | translate}}</ng-option>
      <ng-option [value]="'CLOSED'"> {{'sort.close' | translate}}</ng-option>
    </ng-select>
```

**Comment by varnastadeus** [comment]
please create reproducible example

**Comment by SrgGs** [comment]
http://sergio07.vot.pl/ > live


https://github.com/SrgGs/example > repo clean only translate and ng select

**Comment by jalu14** [comment]
Similar bug, text show on the default language, does not update when changed

**Comment by jalu14** [comment]
Found a solution, just us a template, the text will update and show always, templates are available for search, options and empty parts of ng-select (as far as I have search)

**Comment by melodyfang** [comment]
+1

**Comment by dmoshfegh** [comment]
+1

**Comment by dothem1337** [comment]
Is there a fix for this issue? Even with template its not working.

**Comment by hizliemre** [comment]
+1

**Comment by anjmao** [comment]
The problem with dynamic translations is that it requires to track ng-option label text in order to make it work which would be quite expensive. My suggestion would be to fully reload page on language change so new translations could be picked up.

**Comment by andzejsw** [comment]
Only way of getting this around i think is pipe creation. I don't like page reload as solution, cause don't want to make multiple unnecessary requests.

**Comment by sheva-od** [comment]
Has someone found the solution how to use ng-option with translation?

**Comment by LameesSkyloov** [comment]
is there a solution for it? cause when I use the ngx-translate within ng-option it does not work the label disappeared.
