### ISSUE TITLE
After selecting and clearing, tab inserts item

### ISSUE THREAD

**Issue by GoNode5** [ng-select/ng-select#65]
After selecting and clearing, tab inserts item 

![dropdownopen3](https://user-images.githubusercontent.com/2210672/31116565-decdcc60-a826-11e7-99ff-adfbcdf2679c.gif)

**Comment by varnastadeus** [comment]
@GoNode5 it works as expected, since tab selects last highlighted item. If you want to close dropdown without selection you should press ESC or click away.

**Comment by GoNode5** [comment]
Cannot agree. Tab is never a way to select anything. Suddenly there is is something chosen because of highlight? Never seen this kind of logic...

**Comment by varnastadeus** [comment]
ok, I will do some investigation and will get back to you

**Comment by GoNode5** [comment]
Thnx I'am a little biased. The Chosen/Jquery Multiple Select works perfect. I never get any support questions. I did a test with replacing it ng-selects and I was getting questions within an hour (surely about the colors).  I strongly suggest to take a look how Chosen works, its also based on years of UX (2011)..

**Comment by varnastadeus** [comment]
From Chosen I can see that it does selects value on tab when single, and doesn't when multiple. Will that work?

**Comment by anjmao** [comment]
@GoNode5 There are a lot of components and they all do it in different way. I think best way is to only close dropdown on tab click and not select any value at all, because It can be selected on enter click. Also angular material 2 is doing it the same way, not selecting any value.
