### ISSUE TITLE
Searching in select box with virtual scroll does not find entries that have not yet been loaded

### ISSUE THREAD

**Issue by denniske** [ng-select/ng-select#650]
### Expected behaviour
Searching in select box with virtual scroll should find entries that are not yet loaded.

### Actual behaviour
https://ng-select.github.io/ng-select#/virtual-scroll

Enter "voluptatem". The entry "54 voluptatem ..." is not shown.

**Comment by varnastadeus** [comment]
That example shows simple case of infinite scroll. In your case you should call backend API with search term similar as in this example https://stackblitz.com/edit/ng-select-infinite
