### ISSUE TITLE
[1.x] Remove input if searchable if false

### ISSUE THREAD

**Issue by earshinov** [ng-select/ng-select#651]
### Expected behaviour

When the inner input is not interactable, it should not manifest itself in the UI.

Currently in some cases it is not so, for example if we put an ng-select into a table cell. Please see the example: https://stackblitz.com/edit/ng-select-example-zhw3c1

![ng-select](https://user-images.githubusercontent.com/52021/42113584-63938588-7bf4-11e8-94f1-439449a58787.png)

After the input is either removed from the DOM or set to `display: none;`:

![ng select after](https://user-images.githubusercontent.com/52021/42113731-0e926ca6-7bf5-11e8-916a-89f1e2311229.png)

Note that without the input ng-select will collapse to almost zero width when it does not contain anything, but this behaviour can easily be prevented by setting `min-width`.

The issue might also be present in 2.x version, I just did not bother to check (yet).

### More info

Related:
  - https://github.com/ng-select/ng-select/issues/390, fixed in PR https://github.com/ng-select/ng-select/pull/442 by actually omitting the input from DOM (imo, this was the right decision)
  - https://github.com/ng-select/ng-select/commit/ff295822006b241d23c30ec6c1aa570baebd9460 when the input began to appear in DOM once again (for no apparent reason)

### Version info

ng-select version: 1.5.2

browsers:
- Google Chrome 67.0.3396.99
- Firefox 61.0
- Microsoft Edge 38.14393.2068.0

reproducible in demo page: YES

**Comment by varnastadeus** [comment]
I think the problem is not in input itself, but that it gets default width which expands whole container. Input is necessary to make control focusable, so I will set `width:0` when `searchable=false`

**Comment by earshinov** [comment]
@varnastadeus , Could you backport the fix to 1.x branch?
