### ISSUE TITLE
Support of Regex and Max Length in custom Tags 

### ISSUE THREAD

**Issue by DESHU44** [ng-select/ng-select#652]
### Expected behaviour
Two new Input variable should be available as below:-
1) @Input() regex: string; ---> Only set of characters should be allowed in custom tags as regex provided by developer.
2) @Input() maxLength: number; ---> Only custom tag character length shouldn't bigger than maxLength.
e.g.
---------------------------------
Component variable : -
private regexForCustomTag = "/^[a-zA-Z0-9-_]+$/";      //Only Alphanumeric value with underscore will be allowed in custom tag. 
---------------------------------
---------------------------------
HTML :- 
<ng-select id="userTag" [items]="userCountryTags"
                                  bindLabel="name"
                                  notFoundText="No Tag Found"
                                  addTagText="Add Tag"
                                  placeholder="User Tag"
                                  regex="regexForCustomTag"
                                  maxLength="15"
                                  [addTag]="true"
                                  (focus)="fetchUserTags()"
                                  [(ngModel)]="articleModel.userTag" name="userTag">
                          </ng-select>
---------------------------------

### Actual behaviour
Currently this functionality is not available. Please add this functionality. It's seems very small task.

### More Info
ng-select version: Latest Version

browser: Not applicable.

reproducible in demo page: Yes

**Comment by DESHU44** [comment]
@varnastadeus will you please look into this..?

**Comment by varnastadeus** [comment]
You can achieve that using custom tag function.

```html
<ng-select 
...
[addTag]="addTagFn">
</ng-select>
```

```javascript
addTagFn = (term) => {
    if (matchesLength && matchesRegex) {
        return term;
    }
    return null;
}

```
