### ISSUE TITLE
Placeholder not displayed when using ng-select with formGroupName (when the form is loaded)

### ISSUE THREAD

**Issue by yeddaalous** [ng-select/ng-select#653]
### Expected behaviour
The placeholder should be dispalyed when the form is loaded

### Actual behaviour
The input field is blanc (empty)

```
<form [formGroup]="form.group">
          <div class="form-group" formGroupName="adress">
            <label class="font-weight-bold"> Street</label>
            <ng-select placeholder="Select street" [items]="streets" formControlName="street"
              required bindLabel="label" bindValue="code">
            </ng-select>
          </div>
</form>
```
### More Info
ng-select version: 2.1.3

browser: Chrome Version 67.0.3396.87

reproducible in demo page: No (It would be appreciated if added in the Demo page)

Thank you in advance.

**Comment by varnastadeus** [comment]
can you create reproducible example?

**Comment by yeddaalous** [comment]
I have update the comment by adding the snippet code.

The problem appears when Angular calls writeValue(obj: any) for the first time.

**Comment by varnastadeus** [comment]
I bet your model `street` is empty string?

**Comment by varnastadeus** [comment]
You don't see label because your model is set with valid value, empty object is also valid. You should use null or undefined in your case.

**Comment by yeddaalous** [comment]
But I don't have control over this part, when the form is loaded, Angular call writeValue(obj: any).

As a result we don't see the placeholder.

I have cloned the project and fixing the problem by making a workaround :
`if ((isValObject || isPrimitive)) {
                    this.itemsList.select(this.itemsList.mapItem(val, null));
                } else if (**false && this.bindValue**) {
                    item = {
                        [this.bindLabel]: null,
                        [this.bindValue]: val
                    };
                    this.itemsList.select(this.itemsList.mapItem(item, null));
                }`

**Comment by varnastadeus** [comment]
http://stackblitz.com/ create example here.

**Comment by yeddaalous** [comment]
Thank you for the help.

This is the example issue [https://stackblitz.com/edit/angular-z6rzym](url)

**Comment by yeddaalous** [comment]
Thank you very much, It works now.

**Comment by danielprogramic** [comment]
Thanks!!!!!

**Comment by anithasubramani** [comment]
help me to resolve the same problem...

**Comment by anithasubramani** [comment]
countryCode: [null, [Validators.required, Validators.minLength(3), Validators.maxLength(100)]]

**Comment by kavinda1995** [comment]
> countryCode: [null, [Validators.required, Validators.minLength(3), Validators.maxLength(100)]]

I'm experiencing same like scenario. Using reactive forms and the default value is null. But the placeholder is hidden

**Comment by marimar492** [comment]
If I define the form control with null, then I have an issue with the validators, cuz I can't read the property get from undefined
