### ISSUE TITLE
Min selection of items in ng-select

### ISSUE THREAD

**Issue by deepender87** [ng-select/ng-select#654]
Hi 
I have a use case where user should select  at least 3 or 2 items out of the items list. The number can be dynamic and vary.
We have maxSelectedItems, couldn't find similar to it for minimum item selection. 
Kindly share the detail or the possible workaround.

Thanks

**Comment by varnastadeus** [comment]
For `maxSelectedItems` there is no easy way to disable additional selection of items thats why it made sense to add it as API property.

In your case simple validation message should be enough which should be shown when `model.length < 3`.

**Comment by deepender87** [comment]
Thanks :)
