### ISSUE TITLE
Add possibility to display count of selected options

### ISSUE THREAD

**Issue by exsoflowe** [ng-select/ng-select#656]
### Expected behaviour
I think it's good idea to add parameter in API which allow to limit the number of items to display in the input field. If we don't use this parameter, ng-select shows all selected.
For example, ~maxItemsLimit = 8. If I select 7 or 8 options, I will see all of them. But if I select 9 options, I will see '9 selected'
![image](https://user-images.githubusercontent.com/37380366/42270230-fc2c0148-7f88-11e8-9405-b1cc8bf11aa1.png)

### Actual behaviour
I can select any number of options. And all of them will be shown in input tag.

### More Info
ng-select version: 2.3.2

**Comment by varnastadeus** [comment]
this is achievable using `multi-label-tmp` https://ng-select.github.io/ng-select#/multiselect

**Comment by exsoflowe** [comment]
Thanks. My fail) Need to close
