### ISSUE TITLE
Auto position is calculated before drop down items are updated

### ISSUE THREAD

**Issue by splintor** [ng-select/ng-select#657]
### Expected behaviour
If drop down items are updated, on the first time the drop-down is opened, the calculation if it should be 'top' or 'bottom' is based on the old items and not the new items.

### Actual behaviour
The calculation of whether the drop down is 'top' or 'bottom' should be after the new items are updated (maybe in `_updateItems`).
See https://stackblitz.com/edit/ng-select-example-jwxmin
When you open the drop-down and then check the "Show many cities" checkbox, on the first open, the dropdown will still open below the ng-select, and only on the next time it will consider the new list of cities and open it above the ng-select.

### More Info
ng-select version: 2.3.2

browser: Chrome

reproducible in demo page: Yes

**Comment by splintor** [comment]
Similiar problems exist with scroll to the selected item. It is done before the new list is updated, so if the selected item didn't exist in the old list, the new list will be displayed, but will not scroll to the selected item.

**Comment by koczkadavid** [comment]
Same happens for me, anyone has a workaround or fix?

**Comment by afiqwazien** [comment]
anyone has workaround or fix for this issue? it's been a while

**Comment by varnastadeus** [comment]
I think this is fixed in the latest version
