### ISSUE TITLE
Usage of ng-select in a project that uses VirtualScoll itself

### ISSUE THREAD

**Issue by marplx** [ng-select/ng-select#659]
### Conflict with Virtual Scroll
I tried to use the ng-select with virtualScroll enabled like this:

    <ng-select [virtualScroll]="true" ...></ng-select>

in a project that also imports the `VirtualScrollModule`.
This leads to an Angular Error:

    More than one component matched on this element.
    Make sure that only one component's selector can match a given element.
    Conflicting components: NgSelectComponent, VirtualScrollComponent

### Workaround
I found a *workaround* myself:

HTML

    <ng-select #myNgSelect ...></ng-select>

Component.ts

    @ViewChild('myNgSelect') myNgSelectComponent: NgSelectComponent;

    ngAfterViewInit() {
        //this has to be set programmatically because the [virtualScroll] attribute is provided by more than one component
        this.myNgSelectComponent.virtualScroll = true;
    }

**Comment by Nikcharn** [comment]
same problem,
I had to make a wrapper component to solve this problem. Maybe it's time to rename this property?
