### ISSUE TITLE
Multiple input, after search and select delete input

### ISSUE THREAD

**Issue by GoNode5** [ng-select/ng-select#66]
Please fill below information if issuing a bug report. 
### Expected behaviour
Multiple input, after search and select delete input.

### Actual behaviour
After search and select, the input is not cleared. If you want to search for an whole other beginning/letter, the user uses backspace but that clears the selection. By default the input should be cleared in my opinion.

reproducable in demo page: [YES/NO]

![clearsearch](https://user-images.githubusercontent.com/2210672/31116906-13f715e4-a828-11e7-9e2f-9bf797bdf641.gif)

**Comment by yzuoran** [comment]
Actually this is not a bug,perhaps can be made into a setting attribute. some scenes need this feature. Just like now...I need to select multiple items when input a filter key...seeking reply...

**Comment by varnastadeus** [comment]
There is issue for it

**Comment by yzuoran** [comment]
thank you for your reply @varnastadeus ,but I did not find the issue...could you share the issue url...

**Comment by varnastadeus** [comment]
@yzuoran #276
