### ISSUE TITLE
Special characters decoding issue

### ISSUE THREAD

**Issue by khalid-folio3** [ng-select/ng-select#660]
Please fill below information if issuing a bug report. 
### Expected behaviour
Some & Title

### Actual behaviour
`Some &amp; Title`

As the title said, Data fetched via API and when `title` property has some special character like `&` it just encodes it and doesn't show the decoded/original data.

```
<ng-select formControlName="some_control">
       <ng-option value="">Select </ng-option>
       <ng-option *ngFor="let obj of data" [value]="obj.id">{{ obj.title }}</ng-option>
</ng-select> 

```

[Stackblitz](https://stackblitz.com/edit/ng-select-example-mgxygj) issue template

### More Info
ng-select version: [1.0.5]

reproducible in demo page: [YES]

**Comment by khalid-folio3** [comment]
@varnastadeus duplicate of which issue can you provide the link also?

**Comment by varnastadeus** [comment]
#506

**Comment by taiducnguyen** [comment]
Hi @varnastadeus, Have any fixing for this issue?

**Comment by ElangoAS** [comment]
I am facing the same issue.  Kindly let me know any fixes done on this or any work around can be done

**Comment by MeetRishabh03** [comment]
i had same issue in my application,
since ng-option has bug(it decodes special characters for security),
i used ng-template instead,
previously i used ng-option to iterate data ...which i switched with ng-template
