### ISSUE TITLE
Tag is not removed when select-container has defined height and scroll is shown.

### ISSUE THREAD

**Issue by michalturak** [ng-select/ng-select#661]
### Expected behaviour
Tag should be removed when click (X) and select-container has limited height.

### Actual behaviour
When tag select has declared maximum container height, clicking on e.g. first item (X) (if select is not focused) is only scroling tags vieport without removing.

https://ng-select-example-mxi8u1.stackblitz.io

steps to reproduce:
1. Open example.
2. Click (X) at first item.
3. Viewport is scrolled and item is still selected.
4. Clicking on last item (X) without focusing select works fine.

### More Info
ng-select version: 2.1.0 (but affects newest too)

browser: all

reproducible in demo page: YES (after modify some css)

**Comment by varnastadeus** [comment]
what the issue here? everything seems fine for me and item gets removed

**Comment by michalturak** [comment]
I`m sorry, 
in edit mode browser was smaller, i updated css body width so please check it now :)

**Comment by michalturak** [comment]
Any comment on this? Do you consider it as bug?
