### ISSUE TITLE
Feature Request: Show "X items selected" rather than all selected items as boxes for multiple selections

### ISSUE THREAD

**Issue by headyrules** [ng-select/ng-select#663]
If you have potentially big selections or you want to limit the input to a certain height for style purposes, you could disable display of all selected options as seperate boxes as this results in huge input elements.

Instead you could define a custom text or write "X Items selected" per default. You could also define a function that returns the displayed string, like the "md-selected-text" of the old Angular Material.

**Comment by varnastadeus** [comment]
https://ng-select.github.io/ng-select#/multiselect
