### ISSUE TITLE
Input sanitization issue

### ISSUE THREAD

**Issue by nagos** [ng-select/ng-select#665]
```
<ng-select>
<ng-option>A > B</ng-option>
</ng-select>
```

### Expected behaviour
Option should be "A > B"

### Actual behaviour
Option is "A \&gt; B"

### More Info
ng-select version: master aaffc908c519ff469646c46c0c5e2fd32038757d

reproducible in demo page: YES

Issue was introdused in commit 1fbfd24bb482b6edf2c3012b59b2dc5f9b6e193e
Last working release 0.36.0

**Comment by varnastadeus** [comment]
#506
