### ISSUE TITLE
Store whole object in selected model instead of the value only - Fails when use ng-label-tmp

### ISSUE THREAD

**Issue by Ratikant01** [ng-select/ng-select#667]
I am using ng-select option **label** like:
```
<ng-template ng-label-tmp let-item="item" let-clear="clear">
      <span class="ng-value-icon left" aria-hidden="true" [ngClass]="{'active': item.type === 'active', 'in-active: item.type === 'inActive'}"></span>
      <span>{{item.name}}</span>
      <span class="ng-value-icon right" (click)="clear(item)" aria-hidden="true">×</span>
</ng-template>
```

I am using **item.type** to check the status which adds style to label accordingly.

Now I am trying to set the options by setting [(ngModel)] attribute, but this attribute only takes an array of selected **values** not whole item object where I have item.type defined!! So it is failing to do the styling as item.type cannot be passed to it!!

Any idea how this can be done?

**Comment by varnastadeus** [comment]
can you create reproducible example using stackblitz.com ?

**Comment by Ratikant01** [comment]
The ng-select does not work properly / set the selected values when we set ngModel; Below is link:
[stackblitz](https://stackblitz.com/edit/angular-jyp26v)

**Comment by varnastadeus** [comment]
Your items array is empty and your model is set with `thumbnailUrl` which is simple string. How do you expect it should behave? 
In this case you should preload your items array so it could resolve whole object by value or don't use `bindValue` and set model with object which contains all required information.

**Comment by Ratikant01** [comment]
I was considering the first option initially and thanks for your input; now I am confidently go ahead with this approach!!
