### ISSUE TITLE
Idea - Multiselect sortable

### ISSUE THREAD

**Issue by johaven** [ng-select/ng-select#670]
It should be a cool feature if we be able sort items with drag and drop.

**Comment by varnastadeus** [comment]
I think this idea falls out of scope of this component, but thanks for suggestion!

**Comment by galvakojis** [comment]
i agree with @johaven, it would be really nice to sort items in multiselection

**Comment by crissty** [comment]
+1

**Comment by bsarkadi** [comment]
+1

**Comment by Xteda87** [comment]
+1

**Comment by devsaran** [comment]
+1

**Comment by PolarbearDK** [comment]
+1
