### ISSUE TITLE
both templates not working 

### ISSUE THREAD

**Issue by vialeda** [ng-select/ng-select#672]
Please fill below information if issuing a bug report. 
### Expected behaviour
Describe how you think it should work
I added the default.theme.css into the angular.json this way :

"styles": [
              "src/styles.css",
              "node_modules/bootstrap/dist/css/bootstrap.min.css",
              "node_modules/@ng-select/ng-select/themes/default.theme.css"
            ]

And I added a ng-select this way :

<ng-select
        [items]="cities"
        [multiple]="true"
        [closeOnSelect]="false"
        bindLabel="name"
        placeholder="Select people"
        [(ngModel)]="selectedCarId"
        [ngModelOptions]="{standalone: true}">
    </ng-select>

### Actual behaviour
Describe how it actually works
The default.theme.css is not apply to the ng-select item. 
It is almost invisible.
I can select items and all features except theme works well. 
I can also see that the theme has been load in browser source file.

### More Info
ng-select version: [2.3.2]

reproducible in demo page: [YES/NO]

**Comment by varnastadeus** [comment]
https://stackblitz.com/edit/ng-select-tad?file=angular.json here is simple example with working styles.

**Comment by genu** [comment]
I don't think I follow, what is different between the working example and the original question?

**Comment by TolgaND** [comment]
I have the exact same problem with this crap library.

**Comment by varnastadeus** [comment]
Then don't use it

**Comment by MarieAnneClay** [comment]
You need to add encapsulation: ViewEncapsulation.None in @Component like this (from '@angular/core') :
@Component({
    selector: 'app-exemple',
    templateUrl: './exemple.component.html',
    styleUrls: ['./exemple.component.scss'],
    encapsulation: ViewEncapsulation.None
})

**Comment by pavelmalai** [comment]
Adding "./node_modules/@ng-select/ng-select/themes/default.theme.css" to styles in angular.json solved it for me.

**Comment by RanjeetEppa18** [comment]
@pavelmalai In this case, I am not able to use bootstrap css, How can I override bootstrap css ?

**Comment by Raphjacksun7** [comment]
Thanks @pavelmalai it's works perfectly!

**Comment by razmjo-netlinks** [comment]
how to import default theme in a specific component. I dont want to put it global inside of style.scss or importing into angular.json file.

I want to import it wherever I need it. I have tried to import inside component , and also I have tried to import inside of component .scss file. Unfortunately, it does not work until I import it inside of main style file or angular.json file.

**Comment by eassapn21** [comment]
@MarieAnneClay  Thankyou it working fine for me ...................
