### ISSUE TITLE
Prepopulating an element if there are multiple options with same id

### ISSUE THREAD

**Issue by HarshMathur** [ng-select/ng-select#674]
**This is a question.**

I have initialized ng-select with my 'items' array like:

[{id: 'project', name: 'Project', dataType:'string'},
 {id:'issue', name: 'Issue', dataType:'string'},
 {id:'project', name:'Project', dataType:'project'}]

Here multiple options can have same id. I need to select default the option based on the id and dataType both. Like: I need when the page is loaded then initial model will have value {id:'project', name:'Project', dataType:'project'}

But the ng-select only works with id and automatically selects the first option with given id.
I am using [(ngModel)] for setting up the model.

<ng-select [items]="destinationFields"
          placeholder="Select..."
          bindLabel="name"
          (focus)="prevDestinationProject = selectedDestinationProject"
          (change)="projectChange('destination', prevDestinationProject);"
          [(ngModel)]="selectedDestinationProject">

Is there any way to achieve this?

Thanks!!

**Comment by varnastadeus** [comment]
use `compareWith`
