### ISSUE TITLE
Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by alhamdi23** [ng-select/ng-select#677]
I have issue when have two dropdown list related to each other.
please check exmaple 

https://stackblitz.com/edit/ng-select-example-ptfzwl

**Comment by varnastadeus** [comment]
Why are you using same property for NgModel and items input? It should be separate properties

**Comment by alhamdi23** [comment]
sorry
you are right. now its fixed.
the question is why after selecting primary and secondary and try to change the primary, the value of secondary not change to other list.

the scenario is 
1- select primary
2- select secondry
3- try to change the primary
their is error message shown in the console 
ERROR
Error: Cannot read property 'indexOf' of undefined
