### ISSUE TITLE
All styles of `label-tmp` should be definable in `label-tmp`

### ISSUE THREAD

**Issue by piernik** [ng-select/ng-select#679]
When defining own `label-tmp` You wrap it all into `<div class="ng-value ng-star-inserted"></div>`
That element has it's own styles so I cannot change whole background-color (with `[style.background-color]` - not with css).
I think all css styles corresponding to that `ng-value` should be in `label-tmp`.

**Comment by varnastadeus** [comment]
First of all you shouldn't use `[style.background-color]` on `ng-template`, you should wrap your template with div and then do the styling.

**Comment by piernik** [comment]
I'm not trying to apply style on `ng-template`
This is my template. As You see I'm changing color of `ng-value-label` but border and icon color is in parent DIV to which I don't have access.
```
<ng-template ng-label-tmp let-item="item" let-clear="clear">
                  <span class="ng-value-icon left" (click)="clear(item)" aria-hidden="true">×</span>
                  <span class="ng-value-label text-white" [style.background-color]="item.kolor">{{item.text}}</span>
              </ng-template>
```

**Comment by varnastadeus** [comment]
so just remove default border and background from parent

**Comment by piernik** [comment]
I did it that way. It's suggestion that fi You define own `label-tmp` You should defaine whole label not only it's content.
