### ISSUE TITLE
Set tabindex on ng-select input

### ISSUE THREAD

**Issue by honzajde** [ng-select/ng-select#680]
Please fill below information if issuing a bug report. 
### Expected behaviour
[tabindex]="-1" should remove select box from tab flow. Maybe solution can be generalized to adding syntax for propagating attributes to underlying input? Not sure of other usecases though.

### Actual behaviour
There is no support for setting tabindex on the underlying input element. Setting tabindex on ng-select element does not propagte down to input.

### More Info
ng-select version: 2.3.3

browser: all

reproducible in demo page: [NO]

**Comment by MaxWilson** [comment]
I updated to 2.4 and I am still seeing no change in behavior. I tried this:

```
        <ng-select [items]="storeInfo" [(ngModel)]="selectedStore" bindLabel="displayName" (change)="onStoreSelect(selectedStore)" [tabIndex]="-1">
        </ng-select>
```

but I still can tab into my control, and I see no tabindex=-1 in the HTML. I also tried setting [tabindex]="-1" just in case it's case-sensitive, but it made no difference.

**Comment by MaxWilson** [comment]
Thank you!

**Comment by muditjuneja** [comment]
Thank you! Thank you so much. I noticed this issue sometime ago when I was trying to use tab index. But with your latest commit it is working like charm. Thanks again. You saved a lot of hours that I would have burned while looking deeper.

**Comment by 13hola** [comment]
i tried like that and its working <html>
<body>

[tabIndex]="-1"
--


<br class="Apple-interchange-newline">
</body>
</html>
not like that 
<html>
<body>


[tabindex]="-1"
--


<br class="Apple-interchange-newline">
</body>
</html>
for more : [https://www.npmjs.com/package/@ng-select/ng-select](url)
