### ISSUE TITLE
Custom selected options (multi select)

### ISSUE THREAD

**Issue by stoto34** [ng-select/ng-select#681]
Please fill below information if issuing a bug report. 
### Expected behaviour

I have a list of objects and a list of current selected object.

list of objects :  [{"id":"1", "name":"test"},{"id":"2", "name": "test2"},{"id":"3", "name": "test3"}]
Current selected object : [{"t_id":"2", "t_name": "test2"},{"t_id":"3", "t_name": "test3"}]

I would like to know if it's possible to get ids 2 and 3 selected in my custom list. As you can see, they haven't same properties but same values. How can I achieve this with custom html ? I'm using "compareWith" function to compare object but it only works with display selected data (when the select is not open). PS :  I don't want to rewrite my object.

Thank you very much !

`<ng-select [items]="listItem"
            bindLabel="name"
            appendTo="body"
            [multiple]="true"
            [compareWith]="compareItem"
            [closeOnSelect]="false"
            (scrollToEnd)="fetchMoreItems()"
            placeholder="{{title}}"
            [typeahead]="typeAheadItem"
            [(ngModel)]="currentItems"
            (remove)="removeItem($event)"
            (add)="addItem($event)"
            [ngModelOptions]="{standalone: true}">
            <ng-template *ngIf="loadingTag" ng-footer-tmp>
                <small class="form-text text-muted">Loading</small>
            </ng-template>
            <ng-template ng-label-tmp let-item="item" let-clear="clear">
                <div><span class="ng-value-icon right" (click)="clear(item)" aria-hidden="true">×</span>{{item.t_name}}</div>
            </ng-template>
            <ng-template ng-option-tmp let-item="item" let-index="index" let-search="searchTerm">
                <div>{{item.name}} ({{item.category.name}})</div>
            </ng-template>
        </ng-select>`

### Actual behaviour
Describe how it actually works or even better create example using [StackBlitz](https://stackblitz.com/edit/ng-select-example?file=app/app.component.ts) issue template

### More Info
ng-select version: [INSERT HERE]
1.2.1

browser: [INSERT BROWSER INFO HERE]

reproducible in demo page: [YES/NO]

**Comment by varnastadeus** [comment]
I don't see how `compareWith` could not work.

**Comment by stoto34** [comment]
The compareWith function works really well, I can check if ids are equals. But the ng-select displays values from my model and not from the list. I would like the ng-select pick data from the list not the from my model.

`    compareItem(a, b) {

        console.log("compare");
        console.log(a);
        console.log(b);

        return a.id === b.t_id;
    }`

**Comment by varnastadeus** [comment]
create example using stackblitz

**Comment by stoto34** [comment]
You were right, compareWith is enough. My mistake was to set bad values inside my view. Thank you very much, your component is really awesome :)

You can close this issue.
