### ISSUE TITLE
Example on how to use loadingText with Virtual Scroll

### ISSUE THREAD

**Issue by rohitkrishna12** [ng-select/ng-select#682]
Please fill below information if issuing a bug report. 
### Expected behaviour
An example in demo on how to use loadingText and where it applies would be of great help.

### Actual behaviour
Currently No example in the demo explaining on how to use the loadingText attribute and where it applies?

### More Info
ng-select version: 2.3.3

browser: Any

**Comment by varnastadeus** [comment]
https://ng-select.github.io/ng-select#/filter check last example

**Comment by rohitkrishna12** [comment]
@varnastadeus Thank you for pointing to me to the example
