### ISSUE TITLE
Searching within options with Virtual Scroll

### ISSUE THREAD

**Issue by rohitkrishna12** [ng-select/ng-select#683]
Please fill below information if issuing a bug report. 
### Expected behaviour
Im looking at the Virtual Scroll example listed below to replicate for suiting my needs. Currently when using this if we search for item it only looks within the options loaded in the select. Is there any way i can get this to search in the whole data object and not just in the buffer? or am i looking at incorrect example? i also looked at the stackblitz demo which has another virtual scroll implementation.
[https://ng-select.github.io/ng-select#/virtual-scroll](url)

### Actual behaviour
Currently only searches in the options loaded

### More Info
ng-select version: 2.3.3

browser: Any

reproducible in demo page: [YES/NO] Yes

**Comment by varnastadeus** [comment]
https://stackblitz.com/edit/ng-select-infinite

**Comment by varnastadeus** [comment]
just pass searchTerm to your function? 🤔 I updated example

**Comment by SerenaIce** [comment]
Will this example work well in ng-select version: 1.6.3 ? I am using angular 5.

**Comment by avinashvalluru** [comment]
How this can be possible loaded 5600 of 5000
![select](https://user-images.githubusercontent.com/19501149/76761710-efe93100-67b5-11ea-8ddf-913472039f97.png)

**Comment by ferge22** [comment]
What if in this example https://stackblitz.com/edit/ng-select-infinite we use other fake json like https://jsonplaceholder.typicode.com/users and the point to user.name ? In that case lists starts with 
Capital letter so search doesn't work if i use lower case. Example "c" will not find "C"  => "Clementine" can't be found if i type "clementine". Also filterValue doesn't exist on ng-select, do we need to use "(scrollToEnd)="fetchMore(select.searchTerm)" ?

**Comment by marvinruder** [comment]
In case another person finds this and wonders why `(scrollToEnd)="fetchMore(select.filterValue)"` in `app.component.html:9` sends `undefined` to the function: `filterValue` has been changed to `searchTerm` in the meantime. Perhaps @varnastadeus could update the example linked above.
