### ISSUE TITLE
Provide way to keep search text when calling `close()`

### ISSUE THREAD

**Issue by axelboc** [ng-select/ng-select#687]
### Expected behaviour
There should be a way to keep the search text when closing the drop-down programmatically with `close()`.

### Actual behaviour
The search text is cleared on close:

```js
close() {
  if (!this.isOpen || this._manualOpen) {
    return;
  }
  this.isOpen = false;
  this._clearSearch(); // <<<< this line
  this._onTouched();
  this.closeEvent.emit();
  this._cd.markForCheck();
}
```

### More Info
- ng-select version: 2.3.1
- affected line: https://github.com/ng-select/ng-select/blob/86b1b1e8117e8d9875d49ec103a976f294934b8e/src/ng-select/ng-select.component.ts#L356
- reproducible in demo page: YES - https://ng-select.github.io/ng-select#/forms

---

This could be linked to issue #678. The problem seems to be that `[clearSearchOnAdd]` is too specific and the only way to control the search text. I can think of a few potential solutions:

- Provide an extra input like `[clearSearchOnClose]`.
- Rename the input to `[clearSearch]`, use it for both adding and closing (so they can both be turned off), and expose a `clearSearch()` method.
- Make the search text controllable from the outside, just like the open/closed state, perhaps through two-way binding of `[(typeahead)]`. That'd be ideal but, I assume, very complex.

**Comment by varnastadeus** [comment]
and why would you need to keep search term while dropdown is closed?

**Comment by axelboc** [comment]
I'm using it as a picker with autocomplete. As soon as an option is selected and the dropdown is closed, I store the selection myself then clear the dropdown's model. The dropdown never holds a value (well, not for long).

Once the dropdown is closed, I'd like the search to be persisted so I can pick another option. I'm able to keep the options, but the search term gets cleared.

Does it make sense?

**Comment by bagintz** [comment]
+1, I would like this functionality too for a search box that is fired from a separate button, so if the search term they are looking for doesn't exist in the [items], we can use their entered value for our secondary search.

**Comment by varnastadeus** [comment]
```html
<ng-select
    #select
    [items]="items"
    (close)="select.filterValue = searchTerm"
    (input)="searchTerm = select.filterValue"
    [(ngModel)]="selected">
</ng-select>
```

I still don't see this behaviour as normal, but you can preserve search term this way. Also I would like to see some working example so it would be easier to understand this use case.

**Comment by bagintz** [comment]
This sort of works, but has 2 issues (I am currently trying to work around)
1) The styling of the text input would be nice to be the same as the drop down options
2) When/If you click a drop down value after typing something in it does not overwrite the typed in value

**Comment by ibbxinovacao** [comment]
Was looking for this solution too! Thanks @varnastadeus

**Comment by simbrams** [comment]
@bagintz Did you find a way to fix the overwrite issue (2.) ?

**Comment by salih0313** [comment]
> @bagintz Did you find a way to fix the overwrite issue (2.) ?

Work around i did
`<ng-select
    #select
    [items]="items"
    (close)="onClose(select, searchTerm)"
    (input)="searchTerm = select.filterValue"
    [(ngModel)]="selected">
</ng-select>`

`onClose(select,searchTerm ) {
    if (this.selected) {
      select.filterValue = this.selected;
    } else {
      select.filterValue = searchTerm;
    }
  }`

**Comment by joel1618** [comment]
Another work around that may be easier that seems to work well for me.  
`<ng-select [items]="users" bindLabel=" mergedName" bindValue="mergedName"
             [(ngModel)]="user.mergedName" (search)="search($event)"></ng-select>

search(event) { this.user.mergedName = event.term; //Do api call for users}`

**Comment by udnand** [comment]
Use [clearSearchOnAdd] = "false" in ng-select
