### ISSUE TITLE
Getting Focus and blur event as null

### ISSUE THREAD

**Issue by rohit0522** [ng-select/ng-select#690]
### Expected behaviour
Getting Event as null on focus and blur events
### Actual behaviour
Should get the actual event data on focus or on blur

### More Info
ng-select version: 2.3.2

browser: Google Chrome

reproducible in demo page: YES
[StackBlitz](https://stackblitz.com/edit/ng-select-ugwhsy)

**Comment by daniel-macleod** [comment]
+1
