### ISSUE TITLE
custom searchFn should support convenient use of options

### ISSUE THREAD

**Issue by honzajde** [ng-select/ng-select#692]
### Expected behaviour
Using `[searchFn]="searchFn"` should not be limited to usage with `[items]="..."` . 
It is convenient yo use `<option value="some value">label here</option>` inside ng-select

### Actual behaviour
When using `<option value="some value">label here</option>`,  `searchFn(term, item)` will get `item=option.value="some value"` which does not allow me to search in label.

### More Info
ng-select version: 2.3.3

browser: Chrome

reproducible in demo page: NO

**Comment by KamilKonopka** [comment]
that would be nice to have... Have you got a chance to work that through? Any fancy workaround? Appreciate, any of these...
