### ISSUE TITLE
Difficulty updating to version 2.3.5

### ISSUE THREAD

**Issue by elvispdosreis** [ng-select/ng-select#696]
I'm trying to upgrade to the latest version but without success

"C:\Program Files\JetBrains\PhpStorm 2018.1.5\bin\runnerw.exe" "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" install --scripts-prepend-node-path=auto
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @ng-select/ng-select@^2.3.5
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'pd-pro-angular'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Elvis\AppData\Roaming\npm-cache\_logs\2018-07-19T12_06_23_563Z-debug.log

{
  "name": "pd-pro-angular",
  "version": "1.0.1",
  "repository": {
    "type": "git",
    "url": "https://github.com/creativetimofficial/paper-dashboard-pro-angular.git"
  },
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^6.0.9",
    "@angular/compiler": "^6.0.9",
    "@angular/core": "^6.0.9",
    "@angular/forms": "^6.0.9",
    "@angular/http": "^6.0.9",
    "@angular/platform-browser": "^6.0.9",
    "@angular/platform-browser-dynamic": "^6.0.9",
    "@angular/router": "^6.0.9",
    "@auth0/angular-jwt": "^2.0.0",
    "@ckeditor/ckeditor5-build-classic": "^10.1.0",
    "@ng-select/ng-select": "^2.3.3",
    "@ngui/map": "0.30.0",
    "@types/googlemaps": "3.30.7",
    "bootstrap": "3.3.5",
    "bootstrap-notify": "3.1.3",
    "bootstrap-select": "1.12.4",
    "bootstrap-switch": "3.3.4",
    "bootstrap-tagsinput": "0.7.1",
    "chartist": "^0.11.0",
    "chartist-plugin-zoom": "0.4.1",
    "chartjs-plugin-zoom": "0.6.3",
    "core-js": "2.5.3",
    "datatables": "1.10.13",
    "datatables.net-bs": "1.10.16",
    "datatables.net-responsive": "2.2.1",
    "easy-pie-chart": "2.1.7",
    "eonasdan-bootstrap-datetimepicker": "4.17.47",
    "fullcalendar": "3.9.0",
    "jasny-bootstrap": "3.1.3",
    "jquery": "1.12.4",
    "ng-chartist": "^2.0.0-beta.1",
    "nouislider": "9.2.0",
    "rxjs": "^6.2.2",
    "twitter-bootstrap-wizard": "^1.2.0",
    "web-animations-js": "2.3.1",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.6.8",
    "@angular/cli": "^6.0.8",
    "@angular/compiler-cli": "^6.0.9",
    "@types/bootstrap": "3.3.32",
    "@types/chartist": "0.9.38",
    "@types/datatables.net": "^1.10.12",
    "@types/jasmine": "2.8.6",
    "@types/jquery": "1.10.31",
    "@types/node": "6.0.102",
    "codelyzer": "4.2.1",
    "jasmine-core": "3.1.0",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "2.0.0",
    "karma-chrome-launcher": "2.2.0",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "1.4.2",
    "karma-jasmine": "1.1.1",
    "karma-jasmine-html-reporter": "0.2.2",
    "protractor": "5.3.0",
    "ts-node": "5.0.1",
    "tslint": "5.9.1",
    "typescript": "2.7.2"
  }
}

### More Info
ng-select version: 2.2.3

**Comment by varnastadeus** [comment]
https://docs.npmjs.com/cli/update 🤔
