### ISSUE TITLE
Prevent HTML in labels from being escaped

### ISSUE THREAD

**Issue by shaq147** [ng-select/ng-select#698]
HTML in labels are being escaped and not being rendered

example:
```
items = [
  {"value": "user1", "label": "<i class="fa fa-user"></i> <span>User 1</span>"},
  {"value": "user2", "label": "<i class="fa fa-user"></i> <span>User 2</span>"}
]
```
`<ng-select  [items]="items" [bindLabel]="'label'" [bindValue]="'value'"...></ng-select>`

This produces a dropdown that has the actual HTML text escaped instead of rendering the HTML.

Anybody know how to prevent it from escaping?

**Comment by varnastadeus** [comment]
#506 duplicate
