### ISSUE TITLE
Typeahead and scrollToEnd cannot be used at the same time, two search together do not take effect

### ISSUE THREAD

**Issue by smile2014** [ng-select/ng-select#700]
Typeahead and scrollToEnd cannot be used at the same time, two search together do not take effect

**Comment by smile2014** [comment]
Scroll to the last page after the first input condition, and the filter condition will be invalid again.

**Comment by varnastadeus** [comment]
https://stackblitz.com/edit/ng-select-infinite

**Comment by smile2014** [comment]
Thank you

**Comment by ilapavuluri** [comment]
this is borken in ng-select 4.0 select.filterValue is returing undefine

**Comment by ilapavuluri** [comment]
Hi @varnastadeus  the above is broken in ng-select 4.0 and select.filterValue is always returning undefine.

Appreciate your help

Thanks
Ashok

**Comment by ilapavuluri** [comment]
the above resolved after changing select.filterValue to select.searchTerm
