### ISSUE TITLE
Feature: Custom label text for multiple selections

### ISSUE THREAD

**Issue by delbertlegg** [ng-select/ng-select#701]
Currently supported is a tag for each selection is shown. Propose the option to show a single text in the input that accepts a string value (translated if necessary).

Example: instead of showing a tag for each selection, the text input could show a string including the number of items shown (Items(1), Items(None), Items(All)).

**Comment by varnastadeus** [comment]
<img width="708" alt="screen shot 2018-07-23 at 18 18 26" src="https://user-images.githubusercontent.com/17824796/43085922-d45748aa-8ea4-11e8-8c23-1491506513d8.png">

**Comment by delbertlegg** [comment]
Works perfectly, thank you!
