### ISSUE TITLE
Displaying number of selected items in multiple select

### ISSUE THREAD

**Issue by HarshMathur** [ng-select/ng-select#703]
I have a multiple ng-select and when i choose the options the selected options appear in label each with a clear button. I need only the number of selected items in label, not the actual selected options. Is there a way to do so?

**Comment by varnastadeus** [comment]
just check the demo

**Comment by certainlyakey** [comment]
@varnastadeus do you mean the last example [here](https://ng-select.github.io/ng-select#/multiselect)?

**Comment by varnastadeus** [comment]
yes
