### ISSUE TITLE
[Mac] Safari with japanese input issue

### ISSUE THREAD

**Issue by pvdk276** [ng-select/ng-select#704]
### Actual behaviour
Can't type japanese kanji

### More Info
ng-select version: 1.5.2

browser: Safari

reproducible in demo page: [NO]

**Comment by varnastadeus** [comment]
Please create reproducible example.

**Comment by xama5** [comment]
Issue can be reproduced using the steps below.

Tested on MacOS 10.18.6, using Chrome 69.0.3497.100  and Safari 12.0:

1. Go to System Settings > Keyboard > Input Sources and add "Japanese" in the list to the left.
2. Set your input mode to "Hiragana" in the "icon" bar of macOS.
3. Attempt to write "mizu" (water) in a ng-select field, settings do not matter. (Note: The layout switches to QWERY, if you use a QWERTZ keyboard)

Also recorded it. First one is Chrome, which behaves correctly. The other window is Safari which produces non-sense. Normal <input> fields in Safari behave correctly though.

![untitled](https://user-images.githubusercontent.com/5559501/46088177-29864080-c1ac-11e8-9349-4f1a9c4fdbda.gif)

**Comment by JiaHongL** [comment]
Maybe this can solve the problem.

in ng-select.component.html
(input)="filter(filterInput.value)"  to   (keyup)="filter($event.target.value)"

**Comment by ng-kode** [comment]
> Maybe this can solve the problem.
> 
> ng-select.component.html
> `(input)="filter(filterInput.value)" to (keyup)="filter(filterInput.value)"`
> 
> ng-select.component.ts
> 
> ```
>     filter(term: string, $event?) {
>         this.filterValue = term;
>         this.open();
> 
>         if (this._isTypeahead) {
>             this.typeahead.next(this.filterValue);
>         } else {
>             this.itemsList.filter(this.filterValue);
>             if (this.isOpen) {
>               if ($event.which !== KeyCode.ArrowDown && $event.which !== KeyCode.ArrowUp) {
>                 this.itemsList.markSelectedOrDefault(this.markFirst);
>               }
>             }
>         }
>         this.searchEvent.emit(term);
>     }
> ```

I tried this solution and found that we've to provide the "$event" param in HTML template to make it work, i.e.

`(keyup)="filter($event, filterInput.value)`
in HTML
and 
`filter($event: any, term: string) { ... }`
 in the corresponding component.ts

To improve a bit further, if we want to keep the feature of "closing the dropdown panel when user presses enter to select an option", we can do

>```
>filter(term: string, $event?) {
>        this.filterValue = term;
>        if ($event.which === KeyCode.Enter) {
>          this.close();
>        } else {
>          this.open();
>        }
>       // the rest remains the same as JiaHongL suggested
>}

Hope that helps

**Comment by ZeekoZhu** [comment]
A simple reproduce and a hack to fix this problem: https://stackblitz.com/edit/assign-input-value-oninput

**Comment by ZeekoZhu** [comment]
> A simple reproduce and a hack to fix this problem: https://stackblitz.com/edit/assign-input-value-oninput

I think I'm on a wrong way, we should use `compositonstart` and `compositionend` event to solve this problem.

**Comment by ZeekoZhu** [comment]
I also create a package for #1274 : https://www.myget.org/feed/zeekoget/package/npm/@ng-select/ng-select
