### ISSUE TITLE
Drop Down list of options is cut off when using in an fixed height ngx-datatable row

### ISSUE THREAD

**Issue by dstj** [ng-select/ng-select#705]
### Expected behaviour
The drop down list of options should not be constricted by the `ngx-datatable` row height and should fully overlay over other rows of the table, as a regular `<select>` does.

### Actual behaviour
The overflow of the list of options is cut off, making the selection impossible.

You can see a reproduction here: https://plnkr.co/QvEWjhJhbsghy1OD

Here's an image. There are 3 options:
![image](https://user-images.githubusercontent.com/467692/43151542-2a8f5fce-8f3a-11e8-954e-45daf9cb6a08.png)

### More Info
ng-select version: 2.3.3
browser: Chrome 67.0.3396.99, Edge 42.17134.1.0
reproducible in demo page: NO
I also tried a [StackOverflow post](https://stackoverflow.com/questions/51411060/ng-select-inside-ngx-datatable-dropdown-is-not-visible), but no response

**Comment by varnastadeus** [comment]
you should use `appendTo="body"`

**Comment by dstj** [comment]
Great, thanks! 
I never would've figured it out with the documentation alone. I'll also answer the StackOverflow post in case other stumbles unto this.
