### ISSUE TITLE
Activate typeahead only when enter is pressed

### ISSUE THREAD

**Issue by jherman** [ng-select/ng-select#707]
Is this supported?  I can't seem to find the option.  If not, any idea on how to go about this?  This is a huge problem when results can take many seconds (even up to a minute) to return in some environments, and it's searching on every letter press.  I thought about limiting search to 3 characters or more, but there may be results that need to be shown when there are less than 3 characters.  Any advice on this would be greatly appreciated!

**Comment by varnastadeus** [comment]
in such case I don't think you need typeahead. This how it could work:
```html
<ng-select [items]="items"
                   #select
                   (keydown.enter)="loadItems(select.filterValue)"
                   [loading]="loading"
                   [(ngModel)]="selectedItems">
 </ng-select>
```

```javascript
loadItems(searchTerm: string) {
    this.loading = true;
    // ... load items
    this.loading = false;
}
```
