### ISSUE TITLE
Question about virtualscroll example

### ISSUE THREAD

**Issue by dalu** [ng-select/ng-select#708]
In https://github.com/ng-select/ng-select/blob/master/demo/app/examples/virtual-scroll.component.ts

in
```ts
    ngOnInit() {
        this.http.get<any[]>('https://jsonplaceholder.typicode.com/photos').subscribe(photos => {
            this.photos = photos;
            this.photosBuffer = this.photos.slice(0, this.bufferSize);
        });
}
```
then,

```ts

    fetchMore() {
        const len = this.photosBuffer.length;
        const more = this.photos.slice(len, this.bufferSize + len);
        this.loading = true;
        // using timeout here to simulate backend API delay
        setTimeout(() => {
            this.loading = false;
            this.photosBuffer = this.photosBuffer.concat(more);
        }, 200)
}
```

this makes no sense.

What is supposed to happen there? You've already fetched all of the photo object from the api.
Why would I let the client artificially wait?

**Comment by varnastadeus** [comment]
This is just an example how `fetchMore` could work, since we don't have real API we just preload all data and then `fetchMore` take slice of it 🤔
