### ISSUE TITLE
Append to body

### ISSUE THREAD

**Issue by anjmao** [ng-select/ng-select#71]
We need to allow to append dropdown to body to handle cases there dropdown is shown in absolute containers with overflow:hidden.

**Comment by varnastadeus** [comment]
Even append to body wont solve issue with overflow

**Comment by Kim-Andersen** [comment]
This would be a much loved feature.

Any estimate on when version 1.0.0 is due?

**Comment by varnastadeus** [comment]
Hi, I might start working on it after fixing few bugs.

**Comment by anjmao** [comment]
Hi @Kim-Andersen I'm working on it now :)
