### ISSUE TITLE
How to remove cross icon after selection.

### ISSUE THREAD

**Issue by musman92** [ng-select/ng-select#710]
Please fill below information if issuing a bug report. 
### Expected behaviour
i do not want cross icon in dropdown

### Actual behaviour
Describe how it actually works or even better create example using [StackBlitz]
currently cross icon is shown

### More Info
ng-select version: [1.4.1]

browser: [all]

reproducible in demo page: [YES]
![download](https://user-images.githubusercontent.com/8155538/43356286-2aaa9046-9287-11e8-96a4-d9e2aa887d06.png)

**Comment by varnastadeus** [comment]
use `clearable="false"`

**Comment by liamlaverty** [comment]
> use `clearable="false"`

This is now `[clearable]="false"`

**Comment by Goutham-Harshith** [comment]
> > use `clearable="false"`
> 
> This is now `[clearable]="false"`

Both of them are not working now
