### ISSUE TITLE
Option to move addTag text option as first option in dropdown

### ISSUE THREAD

**Issue by vikeshmittal** [ng-select/ng-select#714]
### Expected behaviour
There should be configuration option to show custom tag text as first option in dropdown

### Actual behaviour
Custom text tag option is the last option in dropdown and user has to scroll down till end to reach there. This is specially painful if user is using keyboard to navigate.

### More Info
reproducible in demo page: YES
https://ng-select.github.io/ng-select#/tags

**Comment by varnastadeus** [comment]
#377 duplicate
