### ISSUE TITLE
Cannot dynamically change disabled property of a item 

### ISSUE THREAD

**Issue by gokayerim** [ng-select/ng-select#717]
Hello everyone,
I have a problem with disabled feature, i wrote a test scenario in below.
- user adds a new item
- page adds a new ng-select
- user selects first item and we add selected item disabled attribute as true,
- user adds another item now we have two ng-select,
- user selects seconds items (first item is disabled. So far so 

what if the user wants to change first item?
### Expected behaviour

I expect that user can select every item except second item because we disabled it. If we examine the current itemList, you can see that.

### Actual behaviour
Every item is selectable, disabled value only works on init time, we cannot change it dynamicly.

So can see it in stackblitz code
https://stackblitz.com/edit/angular-fjdeum

### More Info
ng-select version: 2.3.2

browser: Chrome v67.0.3396.99

reproducible in demo page: YES

**Comment by varnastadeus** [comment]
That is correct, here is how you change items dynamically. https://github.com/ng-select/ng-select#change-detection
