### ISSUE TITLE
Overriding certain CSS attributes not working

### ISSUE THREAD

**Issue by asherbig** [ng-select/ng-select#718]
### Expected behaviour
Overriding the :hover attribute of the .ng-select-container class should apply custom styles
In my case, I'm trying to keep the box shadow on the input box when the dropdown is opened, even when it's being hovered over. 

I also want to get rid of the box shadow in the ng-select-focused:not(.ng-select-opened)>.ng-select-container class. The shadow can be seen after selecting a value from the dropdown, and not clicking anything else on the page.

### Actual behaviour
Hovering over the box removes the box shadow when it should not.
Opening the dropdown box should always have the box shadow present.

There should be no box shadow after a value is selected from the dropdown.
https://stackblitz.com/edit/ng-select-example-bnsu8r?file=styles.scss

### More Info
ng-select version: 1.5.2

browser: Chrome Version 67.0.3396.87 (Official Build) (32-bit)

reproducible in demo page: YES

**Comment by varnastadeus** [comment]
I hope you know that to override styles you should increase selector specificity https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity
