### ISSUE TITLE
appendTo wrongly calculate position.

### ISSUE THREAD

**Issue by cleever** [ng-select/ng-select#719]
### Expected behavior

I'm trying to use ng-select inside a dialog using material2. However, the dropdown panel creates a weird scroll like explained in issue https://github.com/ng-select/ng-select/issues/240.

In order to fix this issue, I'm using the [appendTo]="'body'" functionality but it doesn't calculate the right position.

### Actual behaviour

Is possible to see this issue in the example below:
[StackBlitz](https://stackblitz.com/edit/angular-material2-issue-xqixk2?file=app/app.component.html) 

### More Info
ng-select version: 2.3.6

browser: Google Chrome

**Comment by varnastadeus** [comment]
You should set `position:relative` on body element which would solve your calculations. I updated docs

**Comment by gelevanog** [comment]
Unfortunately, that doesn't fix the issue

**Comment by egozavr** [comment]
> Unfortunately, that doesn't fix the issue

Have tried on [stackblitz](https://stackblitz.com/run?file=src/search-default-example.component.html):

- default panel position:
![image](https://user-images.githubusercontent.com/2705355/70141345-e83eca00-16a7-11ea-804d-3d7bd5b54907.png)

- panel position with `[appendTo]="'body'"`:
![image](https://user-images.githubusercontent.com/2705355/70141287-cb09fb80-16a7-11ea-8976-ac8117fda93b.png)
