### ISSUE TITLE
Selected item persists when options change

### ISSUE THREAD

**Issue by softwareishappiness** [ng-select/ng-select#720]
HI,

### Expected behaviour
Option should be cleared if not in items

### Actual behaviour
When *ngFor provides options and those options change the currently selected option persists even though the the option is no longer in items.

### More Info

1. Visit http://ms.dev.softwareishappiness.com/static/survey/vendor/index.html and click on "Product Questions" tab.
2. Click on at least four buttons and the dependent ng-select will show below
3. Choose an option for each ng-select
4. Change the first ng-select to have the same option as the last ng-select
5. Notice how the last ng-select doesn't have the selected option in the drop down-- that is correct
6. But the selected option should be cleared because it is no longer in items

**Comment by varnastadeus** [comment]
In your specific case it should, but in general I don't think change of `[items]` should have any effect on your selected model. E.g. you could have selected items even if there are no items yet.

In your case you should handle it same as you are handling items removal

**Comment by softwareishappiness** [comment]
I am in the process of upgraded to latest version of ng-bootstrap. I will reply back if/when issue is resolved.

**Comment by softwareishappiness** [comment]
I upgraded to the latest version and issue persists. See screen shot.


[http://ms.dev.softwareishappiness.com/static/screenshots/ng-select_issue-720.png](http://ms.dev.softwareishappiness.com/static/screenshots/ng-select_issue-720.png)

**Comment by softwareishappiness** [comment]
```
<div *ngIf="!stacked" class="container" style="padding: 0px; margin: 0px;">
  <div class="row">

    <div *ngIf="options.length >= 1; else elseHorizontalRanking1" class="col-4">
      <ng-select id="Ranking{{ name }}1" name="Ranking{{ name }}1" (change)="propogateClick($event, name, 1)"
                 placeholder="" [(ngModel)]="ranking1" [ngModelOptions]="{standalone: true}">
        <ng-option *ngFor="let input of options" [value]="input.value">{{ input.text }}</ng-option>
      </ng-select>
    </div>
    <ng-template #elseHorizontalRanking1>
        <div class="col-4">
          <ng-select id="Ranking{{ name }}1" name="Ranking{{ name }}1"
                     placeholder="" [(ngModel)]="placeholder1" [ngModelOptions]="{standalone: true}">
            <ng-option [value]=""> </ng-option>
          </ng-select>
        </div>
    </ng-template>

    <div *ngIf="options.length >= 2 && ranking1; else elseHorizontalRanking2" class="col-4">
      <ng-select id="Ranking{{ name }}2" name="Ranking{{ name }}2" (change)="propogateClick($event, name, 2)"
                 placeholder="" [(ngModel)]="ranking2" [ngModelOptions]="{standalone: true}">
        <ng-option *ngFor="let input of options | option: {'ranking1': ranking1, 'ranking2': ''}" [value]="input.value">{{ input.text }}</ng-option>
      </ng-select>
    </div>
    <ng-template #elseHorizontalRanking2>
        <div class="col-4">
          <ng-select id="Ranking{{ name }}2" name="Ranking{{ name }}2"
                     placeholder="" [(ngModel)]="placeholder2" [ngModelOptions]="{standalone: true}">
            <ng-option [value]=""> </ng-option>
          </ng-select>
        </div>
    </ng-template>

    <div *ngIf="options.length >= 3 && ranking2; else elseHorizontalRanking3" class="col-4">
      <ng-select id="Ranking{{ name }}3" name="Ranking{{ name }}3" (change)="propogateClick($event, name, 3)"
                 placeholder="" [(ngModel)]="ranking3" [ngModelOptions]="{standalone: true}">
        <ng-option *ngFor="let input of options | option: {'ranking1': ranking1, 'ranking2': ranking2}" [value]="input.value">{{ input.text }}</ng-option>
      </ng-select>
    </div>
    <ng-template #elseHorizontalRanking3>
        <div class="col-4">
          <ng-select id="Ranking{{ name }}3" name="Ranking{{ name }}3"
                     placeholder="" [(ngModel)]="placeholder3" [ngModelOptions]="{standalone: true}">
            <ng-option [value]=""> </ng-option>
          </ng-select>
        </div>
    </ng-template>

  </div>
</div>
```

**Comment by softwareishappiness** [comment]
It should be re-opened because I am *not* changing [items]. Please look at the source code. I am using *ngFor and <ng-option> instead. As a result of using <ng-option> templates the issue persists after upgrade to latest version of ng-select.

The issue is that after I select an option in the select and then Angular updates the <ng-option> tags and there by excluding the previously selected option-- the option remains selected even though it is no longer there.

Please look closely at the screen shot provided earlier at: http://ms.dev.softwareishappiness.com/static/screenshots/ng-select_issue-720.png

**Comment by varnastadeus** [comment]
yes, you are not using `[items]` but still updating your `options` array somehow which has same effect: it doesn't affect your selected model which is by design.

**Comment by softwareishappiness** [comment]
Thank you for the clarification. I guess I was confused since that isn't how HTML `<select>` works. Thanks again.

**Comment by varnastadeus** [comment]
Maybe you can create some simple reproducible example? I would check the behaviour to see maybe it worth to support this

**Comment by softwareishappiness** [comment]
Certainly. I will reply back with online snippet. Thanks for your feedback.
