### ISSUE TITLE
NgOption from Array Length 0 does not clear options

### ISSUE THREAD

**Issue by xonuzofa** [ng-select/ng-select#722]
Simple replication of this problem: 

    getOptions() {
        return this.data.filter(a => a.name === this.form.value.name);
    }

    <ng-select [ngClass]="[form.controls.selectedOption.valid ? 'is-valid' : 'is-invalid']" formControlName="selectedOption" placeholder="Select Option">
        <ng-option *ngFor="let option of getOptions()" [value]="option._id">{{option.description}}</ng-option>
    </ng-select>

When getOptions returns array length of 0, the select dropdown still shows the options that it had before getOptions returned an array length of 0.  They need to be cleared out.  There is somewhere in the code checking for length and if there is no length, it is not being accounted for.

ng-select version: 1.0.0

**Comment by xonuzofa** [comment]
![screen shot 2018-08-01 at 10 15 41 am](https://user-images.githubusercontent.com/2785016/43530747-f1f77742-9573-11e8-845a-e987330f79e0.png)
![screen shot 2018-08-01 at 10 15 52 am](https://user-images.githubusercontent.com/2785016/43530759-f792cc2e-9573-11e8-9f45-f65c2ad88ec7.png)
![screen shot 2018-08-01 at 10 16 03 am](https://user-images.githubusercontent.com/2785016/43530763-f9b2e548-9573-11e8-8309-973ba77ff93c.png)

**Comment by varnastadeus** [comment]
you should update to latest version, issue should be fixed there.

**Comment by xonuzofa** [comment]
I apologize this was the wrong package, thought I was using this one.

**Comment by xonuzofa** [comment]
Using "@ng-select/ng-select": "^2.3.6", this actually still has this bug.  I will look at the code later to see if I can't figure out a solution.  Thanks.

**Comment by varnastadeus** [comment]
can you create reproducible example?
