### ISSUE TITLE
feat req: max-visible attribute to limit rendered items

### ISSUE THREAD

**Issue by crhistianramirez** [ng-select/ng-select#726]
### **Proposal:**
There should be a `max-visible` attribute I can set. If i set it to 20 for example only 20 items will render. The first 20 from the list, or after a search is entered the first 20 from those results.

### **Use Case:**
I have some drop-downs with several hundred items. Realistically, no one's going to care to scroll down the list of items so I'd like to use search as a primary means of allowing them to find an item. My app visibly chokes trying to render the full list and if I use virtual scroll, I can't search on the entire list.

Another option is having search play nicely with virtual scroll

**Comment by varnastadeus** [comment]
I am not sure what problem with virtual scroll you have. Having virtual scroll enabled only chunk of items are rendered and you should be able to search among all of you data.
