### ISSUE TITLE
Tooltip for <ng-option>

### ISSUE THREAD

**Issue by aniketavhad13** [ng-select/ng-select#727]
Please fill below information if issuing a bug report. 
### Expected behaviour
Describe how you think it should work

### Actual behaviour
Describe how it actually works or even better create example using [StackBlitz](https://stackblitz.com/edit/ng-select-example?file=app/app.component.ts) issue template

### More Info
ng-select version: [INSERT HERE]

browser: [INSERT BROWSER INFO HERE]

reproducible in demo page: [YES/NO]

**Comment by smithk58** [comment]
It'd be convenient if there was a built in tooltip on options for the cases where your dropdown is restricted to a width that's smaller than your values. Here's a reasonable work around though @aniketavhad13 - https://stackblitz.com/edit/angular-q5pnzc

**Comment by aniketavhad13** [comment]
I have already developed this solution

**Comment by varnastadeus** [comment]
When #506 will be resolved, you would be able to add any type of html tooltip you want.

**Comment by Gaabooo** [comment]
This shouldn't be closed then. I'm having the same issue and #506 is open :/ I say leave this open so you wont forget :)

Adding something like [tooltip]='true' would be really nice.
