### ISSUE TITLE
Won't add item when used in web component

### ISSUE THREAD

**Issue by kubiq** [ng-select/ng-select#729]
### Expected behaviour
Dropdown should add item on click and then close 

### Actual behaviour
Dropdown closes before item is added to items array. Problem is in event re-targeting see:[(Events in Shadow DOM.)](https://gist.github.com/praveenpuglia/0832da687ed5a5d7a0907046c9ef1813#events-in-shadow-dom)

### More Info
ng-select version: v2.3.6

browser: chrome 68

reproducible in demo page: NO

**Comment by varnastadeus** [comment]
Hi, can you create reproducible example showing this behaviour?

**Comment by kubiq** [comment]
Hello, I realized it is problem with encapsulation native, that creates shadow DOM, rather then web components. Example is [here](https://stackblitz.com/edit/ng-select-example-shj3wk?file=app/app.component.ts)

**Comment by kubiq** [comment]
I have pushed improved condition, now it checks if active element is actually in shadow DOM.

**Comment by varnastadeus** [comment]
can you add unit tests?

**Comment by kubiq** [comment]
I added test, but i have no idea if it is correct, it passes if i add my code, and fails when i remove it. [#730](https://github.com/ng-select/ng-select/pull/730/commits/de8dcfabfde902b90665addb8dd3509501be57c6)

**Comment by kubiq** [comment]
Also fixed code style

**Comment by gbelmm** [comment]
fix code  please :)

**Comment by nikkonduru88** [comment]
Hi. I am noticing similar behavior, is there any plan to merge the code and close this issue.
