### ISSUE TITLE
Batch selection

### ISSUE THREAD

**Issue by srahulk1** [ng-select/ng-select#734]
Please fill below information if issuing a bug report. 
### Expected behaviour
I am using ng-select to select multiple options and also the multiple groups.  When I select group, I want all the child element within that group should be selected and their value should be displayed in input box. 
![actualresult](https://user-images.githubusercontent.com/38346966/43891524-24ae79aa-9be7-11e8-9135-ea40a9ec3b97.png)
![expectedresult](https://user-images.githubusercontent.com/38346966/43891525-24edad00-9be7-11e8-9927-4ad6ea8efc7a.png)

### Actual behaviour
Currently when I select group, Group values get's displayed in and only group value is selected. 

### More Info
ng-select version: [1.4.1]
browser: Chrome, Firefox

Attached images for reference

**Comment by tibuurcio** [comment]
I was looking for the same behaviour and was able to implement it by removing `[selectableGroup]` option and using a custom template with a button for the group to select all options:

```html
<ng-select
    [(ngModel)]="selectedItems"
    [items]="items"
    [closeOnSelect]="false"
    [groupBy]="groupByName"
    bindLabel="name"
    [multiple]="true">
    <ng-template ng-optgroup-tmp let-item="item">
        {{ item.name }}
        <button class="ml-1 btn btn-sm btn-outline-info"
            (click)="selectItemsFromName(item.name)">Select All</button>
    </ng-template>
</ng-select>
```

Then you just need to implement your `selectItemsFromName` function and filter your list of selected items based on what you want to select. You could also mix that with `[compareWith]` option if you need custom selection.

Also, make sure to reassign your `selectedItems` array instead of just using `Array.push()` otherwise ng-select won't be able to detect your changes. (Lost some time with that myself)

Hope it helps.

**Comment by srahulk1** [comment]
Thanks for your feedback... It will be a great help if you can share some live demo.

**Comment by tibuurcio** [comment]
There you go: https://ng-select-eeqhhs.stackblitz.io

One could be more clever in how to determine if a group is already selected by using objects to keep track of which groups have been selected, but I believe the minimal example above can get you started.

Cheers! :+1:

**Comment by varnastadeus** [comment]
There is already some sort of batch selection implemented, https://ng-select.github.io/ng-select#/multiselect-checkbox. Only difference that if you have `selectableGroup`, it selects group and marks all children as selected. I think there should be switch which would allow to configure where to select all children or group itself.

**Comment by srahulk1** [comment]
Thanks, guys for your suggestions, It solved my problem.  Now I got stuck with some other issue which is I want to remove drop-down arrow and reset all sign from ng-select. Which I guess can be achieved by css. Please suggest here if someone has done this.

**Comment by srahulk1** [comment]
Hi @tibuurcio ,

I have used your approach to implement the solution, It's working fine. The only issue I am facing now is when I try to search the group by typing group name in the search box, I am not able to do so. Search functionality is only working with the item name, not by the group name. 

Please suggest if you have implemented such scenario or any pointer would really be helpful.

Thanks

**Comment by srahulk1** [comment]
Hi @tibuurcio ,

I have tried the solution and its working fine as expected, the Only problem I am facing is that it's not working when I enable the group as selectable and on pressing the enter it tries to select the group but I want to achieve the same functionality as we have discussed earlier and found solution suggested by you. I can see there is one option selectableGroupAsModel but this does not work with angular 5 version. Please suggest

**Comment by Retail13** [comment]
> Thanks for your feedback... It will be a great help if you can share some live demo.





https://lnkr.fun/756ee42
