### ISSUE TITLE
Selecting a value bind the same value to all ng-select dropdowns

### ISSUE THREAD

**Issue by deepender87** [ng-select/ng-select#736]
Hi
I am using ng-select in ngFor, thus showing up the more than one ng-select dropdown in UI. But issue is whenever i am trying to select a value for a dropDown, it auto selects the same value for all other dropdowns.

Template:
```
<div>
  <ul class="attrib-list" *ngFor="let car of allCarsModelsInState">
    <li>{{car.description}}</li>
    <div class="pos">
      <ng-select [items]="values" [multiple]="true" [closeOnSelect]="true" placeholder="{{'select' | translate}}" [searchable]="false"
        [(ngModel)]="selectedCars" (focus)="getListOfCars(car)" [clearable]="false">
        <ng-template ng-multi-label-tmp>
          <span>{{selectedCars}}</span>
        </ng-template>
      </ng-select>
    </div>
  </ul>
</div>
```

ts file: 
values = ['c1','c2','c3'.....] Values for cars will be prepared dynamically whenever i click on a dropdown.
```
export class Cars{
selectedCars[] = [];

getListOfCars(car){
this.values = carvalues
}
}
```

Please help
Thanks

**Comment by varnastadeus** [comment]
because you are using same `[(ngModel)]` for all of your dropdowns 🤔

**Comment by deepender87** [comment]
Then how i can use differently?

**Comment by varnastadeus** [comment]
use stackoverflow for this type of questions

**Comment by Exlord** [comment]
@deepender87 did u find a solution for this, I have the same problem.
I tried using array/object with indexes for ngModel, but the models won't update when selection changes !

**Comment by Gaabooo** [comment]
Same issue here :/
