### ISSUE TITLE
[Feature] Support of complex labels

### ISSUE THREAD

**Issue by pupizoid** [ng-select/ng-select#738]
Hi!

As I can see, for now `bindLabel` supports only string to be an item's property. But there are several cases when it's usefull to compile label from multiple properties, for example "[id] name".

Is it possible to use the same way as displaying selected item's label with ng-template? Or it can be a function that receives an item and returns a string...

**Comment by varnastadeus** [comment]
I was thinking to make `bindLabel` and `bindValue` to support function expressions which would be more flexible and this way there is no need to support nested strings like `parent.name`. Since this will introduce breaking change, this change will be scheduled with next major release.

**Comment by valllabh** [comment]
Instead of creating function expressions for labels, what if we create template like options?
It will also support using Angular Components.
For value function expressions makes sense.
