### ISSUE TITLE
Disable Issue

### ISSUE THREAD

**Issue by mi1olson** [ng-select/ng-select#74]
Hi, anjmao
I face a problem about multi select disable, when the ngSelect inside FormGroup tag and modal, it wont disable the multi select. so how can fix it?

### More Info
ng-select version: [0.2.5]

browser: [Google Chrome]

reproducable in demo page: [YES]

**Comment by anjmao** [comment]
@mi1olson Thanks for reporting, I'm looking into it :)

**Comment by anjmao** [comment]
@mi1olson It appears that then using reactive forms you should disable it using form control API and [disabled] attribute wont work, this is how angular reactive forms work. I added this sample to demo page also.
```js
    togglePhotoDisabled() {
        const photo = this.heroForm.get('photo');
        if (photo.disabled) {
            photo.enable();
        } else {
            photo.disable();
        }
    }
```

**Comment by mi1olson** [comment]
Thank You very much Mr Anjmao. :)
its works for me

**Comment by musman92** [comment]
@anjmao  thank you
