### ISSUE TITLE
Disable browser autocomplete in ng-select

### ISSUE THREAD

**Issue by redkarsanket** [ng-select/ng-select#740]
Set autocomplete="off/nope" not working for ng-select. How can I disable browser autocomplete?
autocomplete="off/nope" feature is available in input type="text". How can I do the same in ng-select?

ng-select version: 0.23.2

browser: Chrome  68.0.3440.106 (Latest)

reproducible in demo page: [NO]

Thanks in advance. Awaiting your response.

**Comment by redkarsanket** [comment]
I found the solution by myself. I will share that solution by tomorrow.

**Comment by nickjpanella** [comment]
@redkarsanket please share your solution!

**Comment by akakshita** [comment]
Does anyone have a solution for this?

**Comment by specchiasoft** [comment]
in angular via css:
::ng-deep .ng-select .ng-select-container .ng-value-container .ng-input > input[aria-autocomplete] {
  visibility: hidden;
}
