### ISSUE TITLE
clearable button is disabled if multiple=true

### ISSUE THREAD

**Issue by Ayesha-Mulla** [ng-select/ng-select#743]
### Expected behaviour
clearable button should be enabled so that user can clear all tags in ng-select text box

### Actual behaviour
clearable button is currently disabled when multiple option is true. Checked in latest version

### More Info
ng-select version: [2.4.1]

browser: [chrom]

reproducible in demo page: [YES/NO]

` <ng-select #summarySearch bindLabel="name" [loading]="typeaheadSearchStatus === 'loading'" (change)="filter()" clearable="true" formControlName="accounts" (focus)="onTypeAheadFocus()" (blur)="onTypeAheadBlur()" [items]="searchList" [markFirst]="false" [multiple]="true" [(ngModel)]="searchModel" typeToSearchText="{{ localeStrings.typeToSearchText }}" placeholder="{{ localeStrings.searchFor }}" (search)="searchBy('searchText',$event)" dropdownPosition="bottom" [typeahead]="typeaheadSearch">
 <ng-template ng-label-tmp let-item="item" let-clear="clear">
              <span class="search-tag">
                <span>{{item.name}}</span>
                <span (click)="clear(item)">&times;</span>
              </span>
            </ng-template>
</ng-select>`

**Comment by varnastadeus** [comment]
You use `clearable=false`, why do you expect it should be clearable?

**Comment by Ayesha-Mulla** [comment]
@varnastadeus I updated the comment above.. Even If I put "clearable" as true, Its showing the 'x' button as disabled.

**Comment by varnastadeus** [comment]
create reproducible demo, there should be something wrong in your example.

**Comment by ubien** [comment]
I'm having this issue in safari on IOS.  Here's an example of it happening on the demo site:
![no-x](https://user-images.githubusercontent.com/361696/46639391-8a9e0480-cb1a-11e8-9d1e-e540f0749755.gif)

**Comment by ubien** [comment]
I'll open as a separate issue since my example is IOS only and not sure it's the same @Ayesha-Mulla encountered.
