### ISSUE TITLE
Remove underline for dropdown in material version

### ISSUE THREAD

**Issue by rasmusviben** [ng-select/ng-select#744]
Hi,

I need help to remove the border at the bottom in the material design version of the dropdown box.

I've attached a picture, where you can see the line is messing with the overall design of my page:

<img width="412" alt="screen shot 2018-08-13 at 11 19 16" src="https://user-images.githubusercontent.com/23384799/44023612-29fda5dc-9eeb-11e8-9915-57cb322d7046.png">

I've tried overwriting almost everything, but no luck. Hope that someone can tell me how to remove it. :) 

### More Info
ng-select version: 1.5.2

browser: Safari

reproducible in demo page: NO

**Comment by varnastadeus** [comment]
```css
.ng-select .ng-select-container:after {
    border-bottom: none;
}
```
