### ISSUE TITLE
Displaying summary rather than all the selected items

### ISSUE THREAD

**Issue by srahulk1** [ng-select/ng-select#745]
Please fill below information if issuing a bug report. 
### Expected behaviour
 If more than one option is selected on closing the dropdown it should show the number of options has been selected rather than all the selected items.  Again if dropdown is in open state all the selected option should be displayed.
![image](https://user-images.githubusercontent.com/38346966/44029070-a6c9d440-9f19-11e8-9c9c-327dcef63bc5.png)

![image](https://user-images.githubusercontent.com/38346966/44029107-c0f1eb96-9f19-11e8-8f4d-8d455b0508bc.png)

### Actual behaviour
Describe how it actually works or even better create example using [StackBlitz]

As of now, all the selected items are getting displayed in both the cases.
![image](https://user-images.githubusercontent.com/38346966/44029163-f21ef79a-9f19-11e8-914a-17f4871a70d0.png)

### More Info
ng-select version: [1.4.1]

browser: [Chrome,Firefox]

reproducible in demo page: [None]

**Comment by varnastadeus** [comment]
check last example https://ng-select.github.io/ng-select#/multiselect

**Comment by srahulk1** [comment]
Thanks @varnastadeus , But this does not solve my problem. As my problem is the summary should be only displayed when drop down is closed. If we open the dropdown it should show all the selected option not custom template.

**Comment by varnastadeus** [comment]
then just add `*ngIf` to show custom template only when closed
