### ISSUE TITLE
Request - Select All feature

### ISSUE THREAD

**Issue by shongqing** [ng-select/ng-select#748]
Is there already a feature to have select all? If not, any workaround?

ng-select version: 2.4.2

**Comment by varnastadeus** [comment]
`Select All` means setting model with all your items. There is example [here](https://ng-select.github.io/ng-select#/templates)

**Comment by queejie** [comment]
There's a bug in the [example](https://ng-select.github.io/ng-select#/templates).  If you select all, then deselect all several times the list builds up and items in the list cannot be removed.
