### ISSUE TITLE
ng-select should honor the disabled state of its parent fieldset

### ISSUE THREAD

**Issue by ahumeniy** [ng-select/ng-select#751]
Please fill below information if issuing a bug report. 
### Expected behaviour
ng-select should honor the disabled state of a fieldset according to https://www.w3.org/wiki/HTML/Elements/fieldset

### Actual behaviour
When you put a ng-select component within a fieldset, the select is not disabled.

### More Info
ng-select version: 2.1.3

browser: Google Chrome

reproducible in demo page: YES

**Comment by mirkospagnol** [comment]
+1

**Comment by varnastadeus** [comment]
I think this will be resolved with https://github.com/angular/angular/issues/13856

**Comment by Danyx1980** [comment]
I'm still seeing this issue. 

Stackblitz: https://stackblitz.com/edit/angular-kde14p?file=package.json

**Comment by com-xuonghuynh** [comment]
Still getting this issue

**Comment by skrzepij** [comment]
Same issue here. 
On Angular 11 disabling fieldset works correctly on normal input fields, but ng-select is ignoring it 😞 

any chances to fix it shortly? 🙏🏻

**Comment by rockccf** [comment]
Same, I'm still seeing this issue, using Angular 11.

**Comment by MaximSagan** [comment]
@varnastadeus Not sure if this issue was ever actually resolved, but if it was, it has regressed now. Please reopen this issue.

**Comment by mgohin** [comment]
Still a problem today :(

**Comment by raydirty** [comment]
Still an issue with angular v13.3.0 and ng-select v8.1.1
