### ISSUE TITLE
Lose scope of the component when call addTag function

### ISSUE THREAD

**Issue by pinguindark** [ng-select/ng-select#753]
### Expected behaviour
the callback function of addTag should have acces to the component and for example use injection provider

```
addTag(tag) {
   console.log(this)
}
```
output 
`SomeComponent{atribute1: value1, atribute2: value2....}`

### Actual behaviour

when try to access to component de result is the ngSelectComponent itseft

```
addTag(tag) {
   console.log(this)
}
```
output
`NgSelectComponent {classes: "custom", tabIndex: null...}`

**Comment by varnastadeus** [comment]
If you wan't scope of your component then you should use arrow fn:
```javascript
addTag = (tag) => {
   console.log(this)
}
```
This way `this` would get scope of your current component.
