### ISSUE TITLE
Set Selected Group

### ISSUE THREAD

**Issue by marcosv-lealferreira** [ng-select/ng-select#758]
**Select options and groups**
When using `groupBy="country"` and `[selectableGroup]="true"`, as [grouping](https://ng-select.github.io/ng-select#/grouping) and select an entire group, the value of ng-select gets something like shown below:

```
Selected: [
      { "name": "Amalie", "email": "amalie@email.com", "age": 12, "country": "Argentina", "child": { "state": "Active" } },
      { "name": "Samantha", "email": "samantha@email.com", "age": 30, "country": "United States", "child": { "state": "Active" }},
      { "country": "Colombia" }
]
```

**The problem**
When the component is initialized, and we try to pass the values obtained from the options and the groups, ng-select does not load the group correctly, see:

<img width="688" alt="captura de tela 2018-08-17 as 17 07 43" src="https://user-images.githubusercontent.com/25247656/44286718-70455a00-a240-11e8-9b68-b4baa15c0bb1.png">

It looks like the group value is set exactly the same as when we selected it, but ng-select does not display it correctly.

**Comment by varnastadeus** [comment]
#658 duplicate
