### ISSUE TITLE
support autofoucs attribute

### ISSUE THREAD

**Issue by achimha** [ng-select/ng-select#762]
The component should support the HTML5 `autofocus` attribute and assign it to its `input`. This removes the need to write code calling the focus method after a timeout.

**Comment by jennifer-elyse** [comment]
Since autofocus isn't supported yet, is there a way to set focus?

**Comment by achimha** [comment]
```
@ViewChild('ngSelect') ngSelect: NgSelectComponent;

ngAfterViewInit() {
        if (this.autofocus) {
            setTimeout(() => {
                this.ngSelect.focus();
            });
        }
    }
```

**Comment by RebeccaWeber** [comment]
I would like to set autofocus conditionally. Unfortunately, `[attr.autofocus]="shouldFocus"` does not seem to work. Is there a way to set it conditionally?

**Comment by mnyamor** [comment]
Apparently adding **autofocus** to **ng-select** kinda works ( I know autofoucs is private  )  but it's all depending on how you use it. Tried to add it here

https://stackblitz.com/run?file=src/output-events-example.component.html
