### ISSUE TITLE
value="null" when using angular universal

### ISSUE THREAD

**Issue by kamilchlebek** [ng-select/ng-select#764]
**Describe the bug**
Assume you've created page with ng-select component that has some set of items but currently does not have any value. When you render page using angular universal, `<div class="ng-input"><input role="combobox" type="text" autocomplete="a0eb5d2d24b2" value="null" aria-expanded="false"></div>` is being added to HTML which causes `NULL` text to be visible inside the input. After client app loads `NULL` disappears. It appears no matter if I'm using template or reactive forms.

**To Reproduce**
1. Configure angular universal
2. Add simple ng-select component to page
3. Build & run ssr 
4. See error (before client app loads)

**Expected behavior**
ng-select should not render `value="null"` as it disappears later

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser: Chrome
 - Version: 67.0.3396.99

I've created simple repo with universal and ng-select configured.
https://github.com/kamilchlebek/universal-ng-select

To see this error run:
1. npm install
2. npm build
3. npm start:server
4. open localhost:4000

**Comment by anjmao** [comment]
Hi @kamilchlebek,

Thanks for repo, PR is welcome for angular universal, that would be great to support it 👍
