### ISSUE TITLE
Add option [readonly] to disable dropdown & change

### ISSUE THREAD

**Issue by pmestrum** [ng-select/ng-select#768]
**Is your feature request related to a problem? Please describe.**
Not possible to disable changes

**Describe the solution you'd like**
As it's possible with native input tags, I want to be able to set readonly that shows the dropdown as is (white background) but that disables you to make changes or open the dropdown.

**Describe alternatives you've considered**
none

**Comment by varnastadeus** [comment]
Have you tried [disabled]=true?

**Comment by pmestrum** [comment]
Hi,

It didn’t work.  I now set my items to just the one that was selected, set clearable=false and and now I see the selected value and it can’t be changed, but dropdown still appears when clicked on.  Good enough for now.

Regards,
Paul

**Comment by varnastadeus** [comment]
If you are using reactive forms, you need to use `FormControl({value: '', disabled: true})` or calling `control.disable()` or `control.enable()` like in demo.

**Comment by laserus** [comment]
@varnastadeus I also vote for "readonly" on the input. If you run control.disable() then the value of this field won't be in subscribe value changes. 

Let's say we have this scenario, we need value in the form but do not want to allow users to modify the field (after for example we saved something immutable to server, for example some item_id). If we have the items selected by ng-select and item_it is part of formgroup (and it really could be deep inside another formgroup and again inside). At highest level you want to subscribe and follow the changes of the whole hierarchy of forms and if some input is disabled you won't be able to get this item_id from inside, but if it is readonly, then you get the item_id, user sees uneditable input and everyone is happy.

**Comment by chr1soscl** [comment]
@laserus I agree, that is the same issue I am facing now, I want the user to be able to use the value but I don't want the user to be able to change the field.
