### ISSUE TITLE
Show a message when maxSelectedItems is reached

### ISSUE THREAD

**Issue by BenvdStouwe** [ng-select/ng-select#776]
**Is your feature request related to a problem? Please describe.**
When maxSelectedItems is set and the user has reached that value, ng-select just stops working with no visual cue to say why. 

**Describe the solution you'd like**
Show a message that the maximum selected items are reached and if you want other items you should first deselect some others. 

**Describe alternatives you've considered**
A colleague of mine "fixed" it like this (it's a little obfuscated):
```
<ng-select [multiple]="true" [(ngModel)]="selectedOptions" [ngModelOptions]="{standalone: true}" [closeOnSelect]="false">
    <ng-container *ngIf="canSelectMore; else warning">
        <ng-option *ngFor="let option of options" [value]="option" >{{ option }}</ng-option>
    </ng-container>
    <ng-template #warning>
        <ng-option [disabled]="true">There can only be {{ numberOfOptions }} options selected.</ng-option>
    </ng-template>
</ng-select>
```

**Additional context**
You could mention the maxSelectedItems value in the message.
A custom message (like notFoundText) would be very useful.

**Comment by varnastadeus** [comment]
I think it is very app specific and should be handled on your side, I updated demo to show one way of doing it.
