### ISSUE TITLE
Ng-select freezing when binding items via getter

### ISSUE THREAD

**Issue by DimaStoyanov** [ng-select/ng-select#777]
**Describe the bug**
When click on ng-select, add or remove items, all ui freeze

**To Reproduce**
1. Html: write smth like 
`<ng-select [items]=items bindLabel="label" bindValue="value"></ng-select>`
2. TS: 
```
get items() {
    return values.map(value => {
         return {label: this.getValueMap(role), value: value}
   }
}
```
3. Click on ng-select, add or remove items
4. UI freezing

**Expected behavior**
Fast ng-select response.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrom
-  Version 68.0.3440.106

**Additional context**
It looks like ng-select overflow stack by infinitely calling get method

**Comment by anjmao** [comment]
@DimaStoyanov Consider this example

```ts
const obj = {
   prop: [1, 2 ,3],
   get prop2() {
      return this.prop.map(x => x);
   }
}

obj.prop === obj.prop2 // false
obj.prop2 === obj.prop2 // also false
```
It is clear that both prop and prop2 will return the same value, but when you use map you are creating new reference. This is why angular can't handle it. It's not related to ng-select, this is how angular's change detection works.

You can use mobx library and add `@computed` decorator on your items, when it will work fine.

**Comment by varnastadeus** [comment]
https://github.com/angular/angular/issues/11097 I think this is related, since if you are using simple component with getter as input there is no loop issue
