### ISSUE TITLE
Control stucks when binded

### ISSUE THREAD

**Issue by burakkilic** [ng-select/ng-select#78]
Please fill below information if issuing a bug report. 
### Expected behaviour
The user should be available to scroll down to the end of the list.
### Actual behaviour
1 - Cannot scroll until the end of the list
2 - When an option is selected, it is mixed with the placeholder
### More Info
ng-select version: 0.2.5

browser: Chrome

reproducable in demo page: [YES/NO]

    this.sharedService.getLanguages().then(languages => this.languages = languages);

and country array is like:
    
    countries = [ 
        {
            name: 'Afghanistan',
            code: 'AF'
        }, {
            name: 'Åland Islands',
            code: 'AX'
        }, {
            name: 'Albania',
            code: 'AL'
        }, ....

and the template is:

    <ng-select [items]="countries" bindLabel="name" bindValue="code" placeholder="Select country" [(ngModel)]="selectedCountryId">
                                        </ng-select>

If I remove [(ngModel)]="selectedCountryId" from the template, it works.

Where am I wrong?

**Comment by burakkilic** [comment]
I added name attribute to ng-select (it is not written in the manual) and it worked.

**Comment by varnastadeus** [comment]
yes, you need to have name attribute when using reactive forms in angular.
