### ISSUE TITLE
add a "no newline" option

### ISSUE THREAD

**Issue by dalu** [ng-select/ng-select#780]
**Is your feature request related to a problem? Please describe.**
I'm trying to align an input element, and 2 ng-select elements on 1 line. They're displayed below each other.

**Describe the solution you'd like**
```html
<ng-select [newline]="false">
```
default should be true

**Describe alternatives you've considered**
None yet

**Additional context**

![screenshot from 2018-08-31 22-43-11](https://user-images.githubusercontent.com/2694548/44935055-86d6cf80-ad6f-11e8-9a9e-90e9727a6916.png)

**Comment by dalu** [comment]
wtf

**Comment by dalu** [comment]
@varnastadeus reason for closing?

**Comment by dalu** [comment]
Seems like Tadeus is quite the pompous asshole

**Comment by varnastadeus** [comment]
This feature makes no sense, you should read about CSS before creating this type of requests.
