### ISSUE TITLE
ng-select not initializing properly when selectableGroupAsModel = false and async content

### ISSUE THREAD

**Issue by ivangarcia2** [ng-select/ng-select#781]
When you initialize ng-select with async data and disable selectableGroupAsModel input, the selected elements don't show.

I've created a stackblitz with a demo:

https://stackblitz.com/edit/ng-select-a1lv34

In the example you will see the different behaviour of two ng-selects, one using selectableGroupAsModel = false, and the other = true.

**Comment by varnastadeus** [comment]
you misstyped `account$ | async`....

**Comment by ivangarcia2** [comment]
There is a bug in both ng-select. The first one should display Adam, Samantha and Amalie and the second United State, Amalie.
