### ISSUE TITLE
Search Event

### ISSUE THREAD

**Issue by newprogrammer1991** [ng-select/ng-select#782]
Hello friends!!! Please give me help !!! You have  searchEvent , but it doesn't trigger( somethimes need change template when user click  and type words to search  ) 
![image](https://user-images.githubusercontent.com/25803072/44953768-ac172b00-aea0-11e8-8f4a-71a71e84f432.png)

**Comment by vtnhan** [comment]
Hi 
Please help us fix on Version 1.x

**Comment by newprogrammer1991** [comment]
+++? update please for 1.x also
