### ISSUE TITLE
Add option [readonly] to disable dropdown & change

### ISSUE THREAD

**Issue by laserus** [ng-select/ng-select#786]
This is reincarnation of closed issue, which is impossible to open and which does not get attention from contributors: https://github.com/ng-select/ng-select/issues/768

Disable is simply doesn't work / shouldn't be used for readonly purpose at all.

With following comment:
Let's say we have this scenario, we need value in the form but do not want to allow users to modify the field (after for example we saved something immutable to server, for example some item_id). If we have the items selected by ng-select and item_it is part of formgroup (and it really could be deep inside another formgroup and again inside). At highest level you want to subscribe and follow the changes of the whole hierarchy of forms and if some input is disabled you won't be able to get this item_id from inside, but if it is readonly, then you get the item_id, user sees uneditable input and everyone is happy.

**Comment by varnastadeus** [comment]
As mentioned in #768 while using reactive forms you should use `enable()/disable()` methods or set disabled state through `FormControl`. If this doesn't work then create example showing your scenario.

**Comment by varnastadeus** [comment]
on the main page

**Comment by varnastadeus** [comment]
I think this is related to core form functionality and firstly should be changed there. https://github.com/angular/angular/issues/11447. Also to get all values you could use 
```javascript
this.testForm.valueChanges.subscribe((data: any) => {
    this.form_data = this.testForm.getRawValue();
});
```

**Comment by laserus** [comment]
@varnastadeus it is not so much related. Binding [readonly] is already exists and works fine for all forms, except ng-select. 

The suggested hack simply does not work and generally should not be used. Readonly and disabled completely different things. I have a very complex, nested and dynamic formgroup hierarchy and I disable these which values I do not need for root components (programmable form generation).  I do not want to filter out disabled values (and right now Angular works in line with standard for disabled), as it produce some ugly hacks of unknown complexity to manage.

Html5 has an elegant `readonly` attribute. Is there any reason why you do not want to add it and ask users to do hack on top another hack to achieve near similar functionality?

**Comment by laserus** [comment]
Thanks. For now it will be good enough even for reactive forms, compared to all alternatives.

**Comment by Gaabooo** [comment]
Any news on this topic?

**Comment by frostbytedata** [comment]
Another example where `readonly` woulkd be extremely useful is for validation. For business reasons, my company has a form that allows users to fill in their name for instance in one place in the form. That data is then automatically filled in a input later in the form as well, but we only want the user to be able to edit that name on the first input. We also would like to validate the FormGroup and the inputted name at the readonly input (the name was copied into this from the first input). If we simply disable this second input, we cannot run validations on it. If we were able to mark readonly in a model driven fashion, we could show the copied name, validate against it, and all would work well.

**Comment by anjmao** [comment]
@frostbytedata In HTML5 select doesn't have readonly attribute. Here is workaround in [stackoverflow](https://stackoverflow.com/questions/368813/html-form-readonly-select-tag-input?page=1&tab=votes#tab-top)
Basically you can handle it with hidden input.

**Comment by jpike88** [comment]
I don't use reactive forms, and I want to be able to disable my select with an input pre-selected. I'm surprised this wasn't included in the base functionality.

> Binding readonly in the template seems counter to the point of reactive forms

You shouldn't be designing a component with the assumption that all users use reactive forms with it. It's a select component, it should be used wherever I want it to be without requiring another component to make proper use of it. I don't even know why this is up for debate.

**Comment by jpike88** [comment]
Does anyone know a workaround that doesn't involve implementing reactive forms?

**Comment by jpike88** [comment]
I should also add that the 'no items found' option which is currently what I'm limited to doesn't seem intuitive, in fact it just looks like things are broken. I don't want my users to interact with a component unless it's ready to be interacted with.

**Comment by jpike88** [comment]
@varnastadeus is this going to happen? Otherwise I'll fork

**Comment by lluis-stage** [comment]
Need readonly property in select for lots of reasons already said here. If you cannot use readonly in all form elements you don't use it at all. Making hacks here and there is not a solution.

**Comment by keegandsouza** [comment]
This CSS workaround worked for me

    .ng-select.disabled .ng-arrow-wrapper .ng-arrow {
       display: none;
    }

    .ng-select.disabled ng-dropdown-panel {
      display: none;
    }

    .ng-select.disabled .ng-clear-wrapper {
     display: none;
    }

Then add the `disabled` class to the `ng-select` element.

     <ng-select class="disabled" [searchable]="false" [clearable]="false">

Credits go to  [this stackoverflow answer](https://stackoverflow.com/a/52316373/2996302)

**Comment by exonity** [comment]
I need this readonly attribute, too.

**Comment by Fulminant** [comment]
I guess that we need [readonly] attribute.
In case if we will use reactive forms and should validate select, for now, we can't do this because Angular doesn't validate disabled FormControls.
Sure, we can use CSS hotfix, but this not secure.

**Comment by yluijten** [comment]
Any updates concerning this issue?
