### ISSUE TITLE
All ng-select instances are bound to one another.

### ISSUE THREAD

**Issue by divdavem** [ng-select/ng-select#787]
**Describe the bug**
All ng-select instances are bound to one another.

**To Reproduce**
1. Go to https://ng-select.github.io/ng-select/
2. Select something in the first ng-select
3. Click on the second ng-select
4. It automatically takes the value selected in the first ng-select.

**Expected behavior**
Each ng-select should be independent of one another.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 61 (but it it probably the case in all browsers)
 - Version: 2.7.0

**Additional context**
This issue probably comes from the latest commit https://github.com/ng-select/ng-select/commit/a1ce17f8dec8823b59312715a11b415997b9c7f5. There seems to be a single instance of the `SelectionModel` class for the whole application, as it is `providedIn: 'root'`.

**Comment by varnastadeus** [comment]
the problem is known, I removed 2.7.0 from npm for now

**Comment by adilos** [comment]
+1
I have the same problem. Can you please fix this issue ASAP ?
