### ISSUE TITLE
Provide the ability to customize multiple selections

### ISSUE THREAD

**Issue by sdwallace** [ng-select/ng-select#790]
In 1.x we used ui-select to achieve a component that looks like this:  

![desired](https://user-images.githubusercontent.com/2144130/45095794-f1c83380-b0ec-11e8-8449-9909cc8a9d5f.png)

I am trying to do the same with ng-select.  Here is what I have so far (still working on more styling):  

![wip](https://user-images.githubusercontent.com/2144130/45095820-06a4c700-b0ed-11e8-9092-1ac33567caa6.png)

The problem is I am having to modify the ng-select.component.html to do this.  I added a new section to display the selected items and them commented out the multi label template section (so that it did not display selected items in the filter box.  

Can something like this be added or am I missing feature?

**Comment by varnastadeus** [comment]
You can render selected items outside of `ng-select` and use multi label template to show nothing inside.

**Comment by sdwallace** [comment]
OK interesting.  Sorry for what might be a basic question but how would I invoke clearItem() outside?

**Comment by varnastadeus** [comment]
Just remove that value from your model.

**Comment by sdwallace** [comment]
I tried that and got funky results because we also want hideSelected="true".  

Here is my code.  I modified your example SelectMultiComponent

    clearItem(item: any) {
      let index = this.selectedPeople1.findIndex(x => x.id === item.id); //find index in your array
        this.selectedPeople1.splice(index, 1);//remove element from array
    }

What ends up happening is it does remove it from the selected people list but it also does not show in the selectable list because it thinks it is selected.  :-(

**Comment by varnastadeus** [comment]
try 

```javascript
clearItem(item: any) {
  this.selectedPeople1 = this.selectedPeople1.filter(x => x !== item);
}
```

**Comment by sdwallace** [comment]
OK - that worked.  I am not sure I understand why.  

I guess the last step to avoid having this boilerplate formatting and clear code all over, we will need to create a component that wraps ng-select and then have our programmers use "new-select"?

Thanks for the help and quick responsiveness!

**Comment by varnastadeus** [comment]
It works because you need to mutate array reference so ng-select could detect change and apply selected items on its side.
