### ISSUE TITLE
Is it possible to use image in drop down ?

### ISSUE THREAD

**Issue by prajaktatkare1234** [ng-select/ng-select#793]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by varnastadeus** [comment]
Yes it is possible, check demo page

**Comment by esdegan50000** [comment]
@varnastadeus Hello Buddy, image will be loaded **every time** ng-select selected/expanded, so **every time** we open ng-select it will be blinky for a while to load images, whether is possible to load images once at first only? Thanks.

**Comment by varnastadeus** [comment]
I think this is a general question how would you preload or cache your images, ng-select only displays them

**Comment by brunano21** [comment]
@esdegan50000 are you sure images aren't cached by the browser? Do you see new network requests every time ng-select gets expanded?

**Comment by esdegan50000** [comment]
Oh my bad, I forgot if cache have been disabled when chrome devtools opened, it works as expected when I enabled cache setting on devtools, Thanks for quick response brooo.
