### ISSUE TITLE
Keep search term when [closeOnSelect]="false"

### ISSUE THREAD

**Issue by varnastadeus** [ng-select/ng-select#794]
While `[closeOnSelect]="false"` ng-select clears search term after selection. To prevent it additional `clearSearchOnAdd` should be set. Keeping search term after selection by default should improve overall UX.

**Comment by earshinov** [comment]
Please mention incompatibilities in the changelog (https://github.com/ng-select/ng-select/blob/master/CHANGELOG.md). We are getting a little bit tired of unexpected surprises after ng-select updates, at times discovered by end users.
