### ISSUE TITLE
Double Clicking Option Loses Focus

### ISSUE THREAD

**Issue by jennifer-elyse** [ng-select/ng-select#796]
**Describe the bug**
Single click works as expected when selecting a value, however if a user double clicks on a select option the cursor does not behave as expected.

**To Reproduce**
You can reproduce this error in the demos.
1. Click on select to open the list.
2. Double click an option.
3. The cursor disappears until you click Tab.

**Expected behavior**
The cursor should remain on the selected value.

**Desktop**
 - OS: OSX
 - Browser: Chrome
 - Version: 68

**Context**
We are using this component in an enterprise application and we have users that still double-click in a desktop environment. Old habits die hard, I guess.  Those users are having some difficulty using the component because their cursor disappears when they double-click.

**Comment by varnastadeus** [comment]
Actually there is no way to trigger double click event on option since it gets closed imideatelly
