### ISSUE TITLE
[Question]How to custom value display?

### ISSUE THREAD

**Issue by loongdefect** [ng-select/ng-select#798]
Hi all,
I have use ng-select with Multiselect checkbox. 
I have a problem is value to much. (see image).
How to I can custom it. 
![untitled](https://user-images.githubusercontent.com/8251888/45214263-2e01bc80-b2c4-11e8-8f9f-c1bbeb016cc6.png)

**Comment by varnastadeus** [comment]
https://ng-select.github.io/ng-select#/multiselect last example
