### ISSUE TITLE
Setting default type-ahead model?

### ISSUE THREAD

**Issue by carlhussey** [ng-select/ng-select#80]
If using the type ahead setup, how can I populate the field with a default object (label and value)?

I am creating the "edit" portion of a page and I need to set this field to some data fetched from the database. It is still clearable and searchable but I need to set its default value.

**Comment by anjmao** [comment]
Currently we determine selected item by items input array. As are workaround for now you can push one item with array to `items` input and then it will bind to you ngModel.
```js
items = [{value: 1, label: 'Item 1 name'}];
```
I added this as improvement because we can determine label and value if ngModel is object without the need to populate items array.

**Comment by carlhussey** [comment]
What if I am using a custom template? Would I be able to set that manually ?

```
<ng-select [items]="employees" bindLabel="NTID" placeholder="Search Leaders" typeToSearchText="Enter 2 characters to begin your search.."
notFoundText="No employee records found" [typeahead]="typeahead" [(ngModel)]="employeeModel" [clearable]="false" (change)="fetchOutcomeData($event.QID)">
<ng-template ng-label-tmp let-item="item">
   {{ item.FirstName + ' ' + item.LastName + ' ('+item.NTID+')'}}
</ng-template>
<ng-template ng-option-tmp let-item="item">
   <div class="row">
      <div class="col-md-1"><img src="{{ bridgePhotoURL }}{{item.QID}}.jpg" width="35px" height="45px"></div>
      <div class="col-md-11">
         {{ item.FirstName + ' ' + item.LastName }}
         <div class="row">
            <div class="col-md-12">
               <span class="smallText">NTID: {{ item.NTID }} | Location: {{ item.CenterName }}</span>
            </div>
         </div>
      </div>
   </div>
</ng-template>
</ng-select>
```

**Comment by carlhussey** [comment]
I figured this out per your example, thank you.

**Comment by anjmao** [comment]
@carlhussey It is now possible to set model with selected value even if you don't have items loaded. See server side filter https://ng-select.github.io/ng-select#/filter. You just need to set your model as object so ng-select can know what is label and value.
