### ISSUE TITLE
Backport the fix for #651 to 1.x branch

### ISSUE THREAD

**Issue by earshinov** [ng-select/ng-select#800]
The issue described in https://github.com/ng-select/ng-select/issues/651 still exists in the 1.x version, against which the issue was originally reported, because the fix (056f34fc) was never backported there.

I am opening a separate issue for this as the original issue has already been closed.

**Comment by varnastadeus** [comment]
We stopped backporting while ago, but you can cherry pick the commit and create pull request to 1.x branch which I gladly will merge.

**Comment by earshinov** [comment]
OK, thanks!
