### ISSUE TITLE
Can't bind to isOpen since is isn't a known property of ng-select 

### ISSUE THREAD

**Issue by dohly** [ng-select/ng-select#801]
**Describe the bug**
I can' use [isOpen] property in my code. 
Everything works well, if I don't use this property. 
For some reason I don't see this property in source code https://github.com/ng-select/ng-select/blob/1.x/src/ng-select/ng-select.component.ts as well
**To Reproduce**
I've just installed ng-select to my angular 5 app
`"@ng-select/ng-select": "^1.6.0",`

**Expected behavior**
 [isOpen] property should be available

**Screenshots**
![image](https://user-images.githubusercontent.com/1271285/45250579-89c55780-b34f-11e8-9407-62866a920b22.png)

**Desktop (please complete the following information):**
 - OS: windows 8.1
 - Browser Chrome
 - Version 1.6.0

**Comment by varnastadeus** [comment]
it was introduces in version 2.x
