### ISSUE TITLE
[Question]How to custom layout element Multiselect checkbox.

### ISSUE THREAD

**Issue by loongdefect** [ng-select/ng-select#802]
Hi all,
I want custom layout of like image bellow:
Thank all.
![untitled](https://user-images.githubusercontent.com/8251888/45279852-80c5b900-b4fc-11e8-9022-a65815e73d36.png)

**Comment by afelipeor** [comment]
I haven't tried to customize it this much, so take with a grain of salt, but I'm pretty sure that accessing the pre-defined classes in CSS allows you to change the layout this much. Some parts might be tricky, but it should be possible.

**Comment by varnastadeus** [comment]
<img width="681" alt="screen shot 2018-09-18 at 17 48 01" src="https://user-images.githubusercontent.com/17824796/45695861-fe2ba200-bb6a-11e8-8b37-f766dedf8a79.png">
I think it is possible, you just need to use flex and flex-wrap css features
