### ISSUE TITLE
Option to always keep ng-dropdown-panel open (inline)

### ISSUE THREAD

**Issue by DronkWynie** [ng-select/ng-select#803]
**Would be very cool to have**
Have an option to always keep the **ng-dropdown-panel** open, This would solve major UX issues on quite a few websites.

**Additional context**
Similar to the native **\<select multiple\>**:
![image](https://user-images.githubusercontent.com/4537265/45340949-e8314680-b598-11e8-8d7a-a3567ef167ec.png)

**Comment by varnastadeus** [comment]
I think it is already solved, just use `[isOpen]="true"`
