### ISSUE TITLE
In table while using for loop .. its not populating data.

### ISSUE THREAD

**Issue by rajhim** [ng-select/ng-select#805]
==============================

<tr *ngFor="let item of data.details; let i = index;">
                                 <td>
                                        <label class="select" >
                                            <ng-select [items]="list"
                                                       bindLabel="text"
                                                       bindValue="id"
                                                       #purposeFocus
                                                       id="list_{{i+1}}"
                                                       name="list_{{i+1}}"
                                                       placeholder="उद्देश्य छान्नुहोस "
                                                       style="width:150px"
                                                       (change)="onSelectList(i,$event)"
                                                       [(ngModel)]="theItem.purposeId">
                                            </ng-select>
                                          </td
</tr>
=> data submitted from the ng-select after submitted data .. 
=>  data from the service its not displaying value .!
angular 5
ng-select version 1.x

**Comment by varnastadeus** [comment]
Should I guess what do you mean or you can rephrase your issue?
