### ISSUE TITLE
addTag adding a object instead a string

### ISSUE THREAD

**Issue by williangd** [ng-select/ng-select#809]
**Describe the bug**
I don't using `bindValue` and `bindLabel` properties, but when the tag is added, it gets the format: `{ "label": "dsadas" }`

```<ng-select [items]="simpleItems" [(ngModel)]="selectedSimpleItem" [multiple]="true" [addTag]="true"></ng-select>```

This problem does not occur in versions 1.x or 2.0.0.

**Expected behavior**
When you do not use binds, the value added is just a string.

**Comment by varnastadeus** [comment]
Which version you are using? Also create reproducible example

**Comment by williangd** [comment]
I have the "problem" with any version > 2.0.0.

Exemple: https://stackblitz.com/edit/ng-select-hzcdzr

**Comment by MarkDoggen** [comment]
I have this as well. As a temporary fix I used the addTag method as follows:

```[addTag]="addTag"```

and in component.ts:

```
addTag(tag: string) {
    /* https://github.com/ng-select/ng-select/issues/809 */
    return tag;
}
```

**Comment by mohit-nirwan** [comment]
> I have this as well. As a temporary fix I used the addTag method as follows:
> 
> `[addTag]="addTag.bind(this)"`
> 
> and in component.ts:
> 
> ```
> addTag(tag: string) {
>     /* https://github.com/ng-select/ng-select/issues/809 */
>     return tag;
> }
> ```


This would be required for it to work

**Comment by HongLinh97** [comment]
> > I have this as well. As a temporary fix I used the addTag method as follows:
> > `[addTag]="addTag.bind(this)"`
> > and in component.ts:
> > ```
> > addTag(tag: string) {
> >     /* https://github.com/ng-select/ng-select/issues/809 */
> >     return tag;
> > }
> > ```
> 
> This would be required for it to work


-Can I ask how to customize the label and value of newly tag? Because when using addTag(tag: string) function above, the label and value is the same. I need to customize the value (increasing number for example) but still keep the label from insert

-I also try:
```
addTag(tag: string) {
     let newOpt : NgOption = {
       label: tag+ "-new",
        value: tag,
    }
   return newOpt;
 }
```
The error is: <ng-option> get the label from newOpt, but the value is still an object {label: 'awsd-new', value: 'awsd'}
