### ISSUE TITLE
Placeholder not displayed when using ng-select with formControlName

### ISSUE THREAD

**Issue by bernalvinicius** [ng-select/ng-select#815]
When I put formControlName in my div, placeholder not displayed, but, when I put it out, placeholder displayed.
HTML:
`     <div class="form-group" [ngClass]="applyCssError('dropdown')">
       <select formControlName="dropdown" class="custom-select form-control" id="dropdown">
        <option class="dropdown-placeholder" value="&quot;PLACEHOLDER_1427118222253&quot;" style="color: rgb(51, 51, 51); display: none;">Select a Challenge</option>
        <option value="1">Copenhagen - 2018</option>
        <option value="2">Paris - 2018</option>
      </select>
			<div class="col-sm-12">
				<app-field-control-error
				[showError]="verifyValidTouched('dropdown')"
				msgError="Dropdown Required">
				</app-field-control-error>
			</div>
    </div>`

TYPESCRIPT:
`import { Http } from '@angular/http';
import { FormGroup, FormBuilder, Validators, FormControl } from '@angular/forms';
import { Component, OnInit } from '@angular/core';
import 'rxjs/add/operator/map';
import { IMyDpOptions } from 'mydatepicker';
import { SelectItem } from 'primeng/api';

@Component({
  selector: 'app-form-challenge',
  templateUrl: './form-challenge.component.html',
  styleUrls: ['./form-challenge.component.css']
})
export class FormChallengeComponent implements OnInit {

  private selectUndefinedOptionValue: any;

  public myDatePickerOptions: IMyDpOptions = {
    dateFormat: 'mm.dd.yyyy'
  };

  selectedChallenge: '';

  form: FormGroup;

  constructor(
    private formBuilder: FormBuilder,
    private http: Http,
  ) { }

  ngOnInit() {
    this.form = this.formBuilder.group({
      dropdown: [null, Validators.required],
      name: [null, [Validators.required, Validators.minLength(3), Validators.maxLength(30)]],
      phone: [null, Validators.required],
      email: [null, [Validators.required, Validators.email]],
      company: [null, Validators.required],
      dateincorporation: [null, Validators.required],
      companyAddress: [null, Validators.required],
      vat: null,
      mensage: [null, Validators.required],
      website: [null, Validators.required],
      video: null
    });
  }

  onSubmit() {
    console.log(this.form.value);

    if (this.form.valid) {

      this.http.post('https://httpbin.org/post', JSON.stringify(this.form.value))
      .map(res => res)
      .subscribe(dados => {
        console.log(dados);
        this.form.reset();
      });

    } else {
      console.log('formulario invalido');
      Object.keys(this.form.controls).forEach(field => {
        console.log(field);
        const control = this.form.get(field);
        control.markAsDirty();
      });
    }

  }

  verifyValidTouched(field) {
    return !this.form.get(field).valid && (this.form.get(field).touched || this.form.get(field).dirty);
  }

  applyCssError(field) {
    return {
      'has-error': this.verifyValidTouched(field),
      'has-feedback': this.verifyValidTouched(field)
    };
  }

  setDate(): void {
    const date = new Date();
    this.form.patchValue({dateincorporation: {
      date: {
        year: date.getFullYear(),
        month: date.getMonth() + 1,
        day: date.getDate()
      }
    }});
  }

  clearDate(): void {
    this.form.patchValue({myDate: null});
  }

  selectedChange(event: any) {
    this.selectedChallenge = event.target.value;
    console.log(this.selectedChallenge);
  }

}
`

I need use the formControlName because that's where are all my validations

**Comment by varnastadeus** [comment]
please create reproducible example because copying this mess to description does little good

**Comment by bernalvinicius** [comment]
Hii, 

Here I reproduced the project: https://stackblitz.com/edit/angular-qccrcv?file=src/app/form-challenge/form-challenge.component.html

The formatting is strange because the bootstrap is not working.

But the validation is correct, when I have formControlName = "dropdown", works and applies CSS in case of error. But the placeholder does not work.

When I throw formControlName = "dropdown", the placeholder works, but the validation does not.

**Comment by varnastadeus** [comment]
but you are not using ng-select at all 🤔 😮

**Comment by bernalvinicius** [comment]
Sorry, I do not understand, I'm new to this.

How should I do it?

**Comment by varnastadeus** [comment]
just check demo page and exmaples ;)

**Comment by bernalvinicius** [comment]
I'll see, thank you for help :))
