### ISSUE TITLE
Disable items from selection without setting a disable property

### ISSUE THREAD

**Issue by ghost** [ng-select/ng-select#820]
**Is your feature request related to a problem? Please describe.**
Need to disable certain items from selection but still show them in the dropdown. From reading other issues, seems this can be accomplished by setting a 'disable' property on the item itself. 

This is not ideal for two main reasons. First, I don't want to add a 'disable' property to the item's model, it is not a part of the item model, it is for controlling a view component. Second, you now need to clone the items if you show the underlying item in multiple selections (e.g. rows in a table); introducing state leads to a lot of potential complexity.

**Describe the solution you'd like**
Better solution is to pass an optional function to the select component that dynamically returns true if the item should be disabled.

**Comment by anjmao** [comment]
Hi @electric-ladyland, added new input something like `itemDisableFn` could potentially work.

```ts
itemDisableFn(item): boolean {
   return item.isActive === false;
}
```

But this will not work if you want to set some items disabled dynamically. Best way would be to expose some method on ng-select instance like `setItemState(item: NgOption)`;

```ts
class NgSelectComponent {
   setItemState(item: NgOption) {
       // merge state with internal option
       internalItem = {...internalItem, ...item}
       
       // detect changes
       this.detectChanges();
   }
}
```

In your component

```ts
class MyComponent {
     @ViewChild(NgSelectComponent) ngSelect: NgSelectComponent;

     onSomeAction() {
         const item = this.ngSelect.itemsList.find(x => ...);
         item.disabled = true;
         this.ngSelect.setItemState(item);
     }
}
```

Probably exposing setItemState would allow to fully control items without a need to create new copy of items.

**Comment by jziggas** [comment]
I'm having the same problem as I use ng-templates inside of ng-select and there doesn't seem to be proper APIs to disable a single dropdown option that is rendered with ng-templates. So I did something dirty:

```
<ng-select ...>
    <ng-template ng-option-tmp let-item="item" let-item$="item$">
        <span [ngClass]="{'': disableUnclassUser(item$, item)}"> ... custom content </span>
    <ng-tempate>
<ng-select>
```

**Comment by Chay08** [comment]
Adding "disabled: true" into the item array seems to work now with ng-templates

`items = [
    {id: 1, title: 'item1',  disabled: false},
    {id: 1, title: 'item1',  disabled: true}
  ]`

`<ng-select [items]="items"
                              required
                              bindLabel="value"
                              bindValue="id"
                              placeholder=""
                              [clearable] = false
                              appendTo=body
                              formControlName="itemTypes">
                      <ng-template ng-label-tmp let-item="item" style="white-space: normal;">
                        {{item.title}}
                      </ng-template>
                      <ng-template ng-option-tmp let-item="item" let-index="index">
                          <p class="wrapping-option"><strong>{{item.title}}: </strong><span style="font-weight: 400;">{{item.value}}</span></p>
                          <p *ngIf="item.disabled">disbled message</p>
                      </ng-template>
                    </ng-select>`
