### ISSUE TITLE
Is there a way to "paste" several values in multi-selection and the detection of those values will be autocomplete?

### ISSUE THREAD

**Issue by natalicontguard** [ng-select/ng-select#823]
I need to paste several values in one time, and the dropdown should be completed accordingly. 
It would be nice to handle values that were found in the items, and items which weren't found. 

what is the easiest and efficient way to perform this action with the current version?

Thanks,

**Comment by varnastadeus** [comment]
What do you mean by `dropdown should be completed accordingly` >

**Comment by natalicontguard** [comment]
I mean that if the values I pasted in the search box were found, then they should be marked as the selected choices

**Comment by varnastadeus** [comment]
https://stackblitz.com/edit/ng-select-copy here is example, but you need to handle it yourself
