### ISSUE TITLE
Output event (add) only works when [multiple]="true"

### ISSUE THREAD

**Issue by izgqwnqlb** [ng-select/ng-select#824]
**Describe the bug**
When an item is selected, there is no (add) output event. It only works if `[multiple]="true"` is used.
It worked in version 2.1.0 with `[multiple]="false"`. 
In version 2.9.1, which was published today, it still does not work.

**Expected behavior**
There is nowhere mentioned in the documentation that the (Add) event is dependent on other things, so I expect it to work in the same way in a later version.

It was also reported not so long ago: see #772 (but it is Closed)

**Comment by varnastadeus** [comment]
`(add)` event was introduced specifically for multi-select to address last selected item. Since you have only one selection in single-select, this event doesn't make sense and you should `(change)` event which output last selection. Also I updated readme.

**Comment by izgqwnqlb** [comment]
Thank you for clarifying this.
