### ISSUE TITLE
NgOptionHighlightDirective highlights letters in special characters

### ISSUE THREAD

**Issue by Farioch** [ng-select/ng-select#826]
**Description**
When using custom **ng-option-tmp** with **ngOptionHighlight** to highlight searched value, letters in special characters are searched and highlighted.

**Example**
When we have an _option_ with _name_, containing '&', and search for 'a', '&' is displayed as '\&amp;';

![image](https://user-images.githubusercontent.com/4190606/45873217-8e036300-bd9a-11e8-84e3-f356b6c33a9b.png)

```html
<ng-template ng-option-tmp let-item="item" let-index="index" let-search="searchTerm">
        <span class="option" [ngOptionHighlight]="search">
            {{ item.name}}
        </span>
</ng-template>
```

**Expected behavior**
**ngOptionHighlight** should not search in innerHtml of element, but probably in innerText.
```javascript
this.label = this.element.innerHTML;
```

**Version**
"@ng-select/ng-select": "2.5.1"

**Comment by varnastadeus** [comment]
this is related to #506
