### ISSUE TITLE
Error: mat-form-field must contain a MatFormFieldControl

### ISSUE THREAD

**Issue by Dsupreme** [ng-select/ng-select#828]
**Describe the bug**
Receive the error when ng-select is wrapped inside a mat-form-field element

**To Reproduce**
1. Create a Reactive Form
2. Wrap ng-select component inside mat-form-field element
3. Check console to see error

**Expected behavior**
ng-select should not break

**Code** 
```
<mat-grid-tile [colspan]=1 [rowspan]=1>
    <mat-form-field>
    <ng-select matInput placeholder="Select country" #countrySelect [items]="country$" [selectOnTab]="true"
        bindValue="id" labelForId="name" [formControl]="countryFormControl">
    </ng-select>
    </mat-form-field>
</mat-grid-tile>
```

**Additional context**
The problem seems to be ng-select not having an matInput directive which is shared across mat-form-field chlidren.

Have added the Material Modules: Form, Input, Select
https://github.com/angular/material2/issues/7898

**Comment by varnastadeus** [comment]
I don't see how this is related to ng-select  🤔ng-select is not part of angular material. I think you need to wrap ng-select as custom material control like described here https://material.angular.io/guide/creating-a-custom-form-field-control

**Comment by kelvinlouis** [comment]
has anyone succesfully wrapped ng-select for angular material, so it actually aligns and behaves like all the other fields? we decided against ng-select because of this and used ngx-mat-select-search instead, which is buggy and has a lot of boilerplate code.

**Comment by jean-merelis** [comment]
@kelvinlouis 
I have created a directive to support the MatFormFieldControl. 
SCSS file needs a little more polishing but it works as expected.
https://gist.github.com/jean-merelis/44a3ed842c24e99d38cd2f1e9249c473#file-ng-select-directive-ts

**Comment by davdinesh** [comment]
<mat-form-field class="example-full-width">
        <mat-label>Priority</mat-label>
        <mat-slider thumbLabel [displayWith]="formatLabel" [formControl]="priorityControl" tickInterval="1" min="1" max="30"></mat-slider>
  </mat-form-field>

I had imported MatInputModule and MatFormFieldModule in app.component.ts, even then mat-form-field must contain a MatFormFieldControl. error throws. Could you please help me?

**Comment by nzbin** [comment]
@Dsupreme @kelvinlouis @davdinesh 
I have made a material form field wrapper of ng-select [`mtx-select`](https://ng-matero.github.io/extensions/select)

**Comment by Nabeeh-AlSawaf** [comment]
i worked out an scss for outline view styles only with error information under it 

scsss : 
`ng-select.ng-invalid.ng-touched .ng-select-container.ng-appearance-outline:after{
    border-color: #f44336 !important;
    border-width: 2px;
}
ng-select.ng-invalid.ng-touched .ng-select-container.ng-appearance-outline .ng-value-container .ng-placeholder{
    color: #f44336;
}
ng-select.ng-invalid.ng-touched .ng-select-container.ng-appearance-outline .ng-arrow-wrapper .ng-arrow{
    color: #f44336;
}
ng-select.ng-invalid.ng-touched .ng-select-container.ng-appearance-outline{
box-shadow: none !important;
}
.ng-select .ng-select-container .ng-value-container{
    padding: 0.6875rem 0;
}`
in html example (ps: i am using translate plugin you can ignore it)
html:
`                  <ng-select  id="langSelect" [items]="shared.languages" [multiple]="true" bindLabel="name"
                  formControlName="language" appearance = "outline"
                  bindValue="code"
                  [placeholder]="('userForm.languages' | translate) + ' *'" [closeOnSelect]="false"
                  (change) = "onCountrySelected($event)"
                  >
                </ng-select>
                <div class="mat-form-field-appearance-outline ">
                  <div class="mat-form-field-subscript-wrapper">
                    <mat-error *ngIf="docForm.get('language').hasError('required') && docForm.get('language').touched">
                      {{'userForm.languageValidation' | translate}}
                    </mat-error>
                  </div>
                </div>
`
of course it is not full styling but just small working styles instead, if you need a full style i advice you installing the package in nzbin comment
