### ISSUE TITLE
Request to add support for multiple = true on typeahead

### ISSUE THREAD

**Issue by carlhussey** [ng-select/ng-select#83]
Please fill below information if issuing a bug report. 
### Expected behaviour
When using the type-ahead example with `multiple=true`, I would expect to be able to search for one or more values from a service and select them. Upon clicking on this field again to add more, I would expect that my new search wouldn't wipe out what was already there and replace it with the new results.

### Actual behaviour
When using type-ahead with `multiple=true`, I can search for and click on one or more results. When I click on the input again to add more results, it is overwriting what I had previously selected. It also seems to retain the searched value in the input even after selecting a value from the results.

Example: https://giphy.com/gifs/3o7aDaWZdDy0nIV37G/fullscreen

My use case for this is that I have an input that allows me to select "tags" for support requests and those tags are provided to me from a service. When I go back to this page to edit the existing tags, I need to populate it with the current ones but still allow me to search for more via the service/typeahead.

### More Info
ng-select version: 0.2.5

browser: chrome

reproducable in demo page: on plunkr for type-ahead

**Comment by anjmao** [comment]
@carlhussey This is definitely needed feature. Thanks for suggestion :)

**Comment by varnastadeus** [comment]
in demo page, https://ng-select.github.io/ng-select#/filter-server, it works as you described

**Comment by carlhussey** [comment]
Ah thanks @varnastadeus - I didn't think to compare the plunk and the one from the demo page. Looks like this already has been accounted for.
