### ISSUE TITLE
Weird behavior when there is duplicate item values from different groups

### ISSUE THREAD

**Issue by Ratikant01** [ng-select/ng-select#830]
Consider below scenario where I have 2 different group of items (animal & bird) as below: and I do decorate the tags depending on type using styles.

```
results = [{
type: 'animal',
name: 'Mr A'
},
{
type: 'bird',
name: 'Mr B'
},
{
type: 'bird',
name: 'Mr A'
}]

bindValue="name"

[(ngModel)]="searchItemsModel"
```

Now when I select 'Mr A' from animal & then 'Mr A' from bird it behaves weird; it does not add the second item properly. Also it does not work when come back this page using bookmark where we have these values set in URL param. Any idea, how we can handle this scenario from API level?

**Comment by varnastadeus** [comment]
create reproducible example

**Comment by varnastadeus** [comment]
also to resolve value properly you should use `compareWith`
