### ISSUE TITLE
Is Multiselect checkbox with reactive forms possible? 

### ISSUE THREAD

**Issue by tanjoreraj** [ng-select/ng-select#831]
I am trying to use the Multiselect Checkbox-- Group selects children with reactive forms is it possible??

I am facing difficulty in select the parent and their child as well as to get the selected checkbox's data in the formControlName..

Please help me...

**Comment by varnastadeus** [comment]
If it works with ngModel I don't see why this should not work with reactive forms.

**Comment by snayak46** [comment]
Is it possible to do validation for  Multiselect Checkbox in reactive forms?
As to apply validation , below mentioned css needs to be applied: 
ng-select.ng-invalid.ng-touched .ng-select-container {
    border-color: #dc3545;
    box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 0 3px #fde6e8;
}

but ng-select with Multiselect checkbox is not showing ng-invalid class .

Any Help will be appreciated.
