### ISSUE TITLE
Allow custom icon on "clear all" action instead of hardcoded "x"

### ISSUE THREAD

**Issue by anbaran** [ng-select/ng-select#835]
**Is your feature request related to a problem? Please describe.**
I would like to change the icon on ng-select action "clear all" to match the style of my application. However, for some reason "clear all" icon is hardcoded in html file 

**Describe the solution you'd like**
I would like to have the possibility to define "clear all" icon on my own in css. When it comes to the arrow next "clear all" it is nicely done with ng-arrow class. Can't it be done the same way with ng-clear?

**Describe alternatives you've considered**
Up until recent versions I could overcome it with the following:
```
.ng-select.custom .ng-clear-zone .ng-clear  {
    display:none;
}

.ng-select.custom .ng-clear-zone:after  {
    color: #337ab7;
    font-size: 12px;
    font-family: 'Glyphicons Halflings';
    content: "\e014";
}
```
However, in the recent version you listen for action on clear all with:
```
 if (target.className === 'ng-clear') {
            this.handleClearClick();
            return;
        }
```
and my solution cause target.className to be ng-clear-zone(or newly ng-clear-wrapper) so my solution/hack stopped working.

It would be cool to have "clear all" action the same approach as with ng-arrow class

I use ng-select 1.x for Angular 5

**Comment by anjmao** [comment]
Hi @anbaran,

If you could make a PR with this change and check if it still works that would be great 👍 

```ts
if (target.className === 'ng-clear-wrapper') {
    this.handleClearClick();
    return;
}
```
