### ISSUE TITLE
output (search) not working 

### ISSUE THREAD

**Issue by FelipeFelizardo** [ng-select/ng-select#836]
The (search) isn't being called.

`<ng-select placeholder="Select some items"
                   [items]="items"
                   [(ngModel)]="selectedItems"
                   bindLabel="name"
                   bindValue="id"
                   [multiple]="true"
                   (open)="onOpen()"
                   (close)="onClose()"
                   (focus)="onFocus($event)"
                   (search)="onSearch($event)"
                   (blur)="onBlur($event)"
                   (clear)="onClear()"
                   (add)="onAdd($event)"
                   (scrollToEnd)="onScrollToEnd($event)"
                   (remove)="onRemove($event)"
                   (change)="onChange($event)">
        </ng-select>
onChange($event) {
        this.events.push({ name: '(change)', value: $event });
    }

    onFocus($event: Event) {
        this.events.push({ name: '(focus)', value: $event });
    }

    onBlur($event: Event) {
        this.events.push({ name: '(blur)', value: $event });
    }

    onOpen() {
        this.events.push({ name: '(open)', value: null });
    }

    onClose() {
        this.events.push({ name: '(close)', value: null });
    }

    onAdd($event) {
        this.events.push({ name: '(add)', value: $event });
    }

    onRemove($event) {
        this.events.push({ name: '(remove)', value: $event });
    }

    onClear() {
        this.events.push({ name: '(clear)', value: null });
    }

    onScrollToEnd($event) {
        this.events.push({ name: '(scrollToEnd)', value: $event });
    }

    onSearch($event) {
        this.events.push({ name: '(search)', value: $event })
    }`

**Comment by varnastadeus** [comment]
it was added in 2.8.0v
