### ISSUE TITLE
Form patchValue does not work when used with formControl of type FormGroup

### ISSUE THREAD

**Issue by yeddaalous** [ng-select/ng-select#837]
Form patchValue does not work when used with formControl of type FormGroup

**To Reproduce**

export class InfosForm {
    group: FormGroup;

    constructor(private fb?: FormBuilder, private formModel?: Object) {
            this.group = this.fb.group({
                school: new FormGroup({
               code: new FormControl(null, Validators.required)
                })
            });
        this.group.patchValue({school: {code: 'SH001'}});
    }
}

<form [formGroup]="form.group" >
  <div class="form-group" formGroupName="juridiction">
    <label > School*</label>
    <ng-select placeholder="Enter school" [items]="schools"
      formControlName="code" required bindLabel="label" bindValue="code">
    </ng-select>
  </div>

**Expected behavior**
The form select school should be populated with the patched value

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 69.0.3497.100 (Build officiel)

Thank you in advance

**Comment by varnastadeus** [comment]
please create reproducible example, there is little help from your code snippet

**Comment by yeddaalous** [comment]
this is the link of an example : https://stackblitz.com/edit/angular-m8zwem

**Comment by varnastadeus** [comment]
https://stackblitz.com/edit/angular-tmcnp7, your example works as expect 😮

**Comment by yeddaalous** [comment]
Yes, the problem was in our implementation.

Thanky you for your support.

**Comment by minnumerinalex** [comment]
> https://stackblitz.com/edit/angular-tmcnp7 your example works as expected 😮

Can you please help me the same with multiple="true" on ng-select

**Comment by VishvaAshok** [comment]
Try the below code with multiple="true"

this.group.patchValue({
      school: {
        code: **['SC001']**
      }
    });
