### ISSUE TITLE
"export 'defineInjectable' was not found in '@angular/core'

### ISSUE THREAD

**Issue by muhammad-ragab** [ng-select/ng-select#839]
i'm on angular 5  
got that error in
 ./node_modules/@ng-select/ng-select/fesm5/ng-select.js
"export 'defineInjectable' was not found in '@angular/core'

**Comment by elarbee** [comment]
For anyone getting this error that is in the position I'm in where upgrading to ng 6 would be an issue. The simple answer is to install v1.x of ng-select. I didn't see the compatibility table that exists first in the first part of the readme. 🤦‍♂️
