### ISSUE TITLE
Unable to leverage unselect() feature when using ng-label-tmp

### ISSUE THREAD

**Issue by davidaah** [ng-select/ng-select#84]
(I'm not sure if this is so much of a bug report or a feature request)

### Expected behaviour
When using ng-template "ng-label-tmp" it should still be possible to leverage built-in [unselect()](https://github.com/ng-select/ng-select/blob/6a911270a39fb7d3a10d6820b78c73dca75c8da5/src/lib/src/ng-select.component.html#L6) action
(Alternatively, as a feature: allow user to optionally disable items in the input form that are disabled in the drop down <-- my guess is that this is probably much easier)

### Actual behaviour
I am trying to be able to disable removal of an item from a select box when the disabled field is set to true (similar to the way it is in the dropdown menu).

As this is not supported out of the box, I was instead trying to leverage ng-label-tmp to remove the "x" button, however once I introduce the template the default unselect() action is no longer called. So I can't remove items from the list without returning to the dropdown menu

The use case is when I am pre-populating the initial state of the input field and I do not want the user to be able to remove some of the initial values

See below example

### More Info
ng-select version: 0.3.0

browser: Chrome 61

reproducible in (fork of) demo page: YES
https://embed.plnkr.co/qgZgyfAUaGrZNVb2NfQQ/
(notice clicking the "x" on one of the pre-populated values that is not disabled doesn't do anything)

**Comment by varnastadeus** [comment]
Hi @davidaah, it's currently possible and there is example on demo page under multiselect.
Basically you need to declare **clear** action and add it to click event you want.
```html
<ng-template ng-label-tmp let-item="item" let-clear="clear">
              <div class="ng-value-wrapper default">
                <span class="ng-value-icon left" (click)="clear(item)" *ngIf="item.disabled !== true">×</span>
                <span class="ng-value-label">{{ item.name }}</span>
              </div>
            </ng-template>
```

**Comment by varnastadeus** [comment]
code from demo: https://github.com/ng-select/ng-select/blob/master/src/demo/app/examples/multi.component.ts

**Comment by davidaah** [comment]
@varnastadeus ahh excellent thank you, not sure how i missed this... I was able to implement this but now the clear() action *and* the dropdown selector are getting triggered by the onClick event

reproduced in plnk -- https://embed.plnkr.co/qgZgyfAUaGrZNVb2NfQQ/

**Comment by varnastadeus** [comment]
yes, and default implementation covers that. In custom templates you must handle it by yourself, since we are not in control what user template would be. Try this one 
```html
(click)="clear(item); $event.stopPropagation()
```

**Comment by davidaah** [comment]
great thanks! that get's me up to https://github.com/ng-select/ng-select/issues/79 ... will keep an eye out for an update on that one.
one other question for you @varnastadeus which is quite possibly another oversight on my part and if so i apologize. i've been having trouble overloading some of CSS properties exposed by the module.

because the classes are injected within `ng-select` but outside of the `ng-template` , the only thing i have been able to make work for various properties has been something using the (eventually deprecated) `::ng-deep`.

```css
:host ::ng-deep ng-select.ng-multiple .ng-control .ng-value-container {
  vertical-align: middle;
  padding: 0px;

  .ng-placeholder {
    padding: 0px;
  }

  .ng-input {
    padding: 0px;
  }
}
```

**Comment by varnastadeus** [comment]
you got it working because additional selectors adds higher priority in css. You can get it to work with `!important`also, but the original issue is that **ng-select** styles are loaded after your page styles which overrides your customisations if selectors are equal.

**Comment by varnastadeus** [comment]
also added #87, to hide close button for disabled selected items

**Comment by davidaah** [comment]
thank you very much!
