### ISSUE TITLE
Where does the addTag add new Items when a promise is resolved 

### ISSUE THREAD

**Issue by mahit777** [ng-select/ng-select#840]
Where are the new Items of addTag Stored and what happens when a promise is resolved for an addTag
I tried to log the items array but the array does not contain the newly added Items but still they are displayed in the dropdowns how is that possible  ?

[StackBlitz](https://stackblitz.com/edit/ng-select-dpqkgk)

**Comment by varnastadeus** [comment]
it is added to inner items of dropdown itself. Your array stays the same

**Comment by mahit777** [comment]
what happens when my array is dynamic and is changed by service calls ?. currently when that happens my dropdown shows empty

**Comment by mahit777** [comment]
so I should add the newly created items into my array dynamically?

**Comment by varnastadeus** [comment]
yes

**Comment by mahit777** [comment]
although when I'm trying to call a funtion which returns a promise the select box shows an empty box with 'x' at the end what does this mean ?
![select snip](https://user-images.githubusercontent.com/18370058/46256583-44b5c080-c4ca-11e8-8dd7-918556c30a48.PNG)

**Comment by mahit777** [comment]
the code for my method is 

Html :
```

<ng-select #searchable
[items]="lookUpMap[parentId]"
[required]="requiredCreation" 
bindLabel="value"
bindValue="id"
[loading]="loading"
[addTag]="addTagPromise"
addTagText="Add new"
#element="ngModel"
name="parent"
[(ngModel)]="entity[parentId]">
</ng-select>

```

Component.Ts 

   ```
 addTag = (term) => {

            return new Promise((resolveProm) => {
               setTimeout(() => {
                resolveProm({id: 213, value: term});
               }, 1000);
            })
    }`
```
