### ISSUE TITLE
Problem when set value for ng-select using ansyc in formcontrol

### ISSUE THREAD

**Issue by vietdq1291** [ng-select/ng-select#841]
Hi 
i have problem set value for ng-select when using ansyc
here is my code 

html code : 
 <ng-select formControlName="traLoiMaVanBan"
                                       [items]="lstVanBanDen$ | async"
                                       bindLabel="text"
                                       bindValue="value"
                                       [hideSelected]="true"
                                       [loading]="documentloading"
                                       [typeahead]="documentinput$"
                                       [(ngModel)]="model.traLoiMaVanBan">
                            </ng-select>

TS Code : 

private loadIncommingDocument() {
    this.lstVanBanDen$ = concat(
      of([]), // default items
      this.documentinput$.pipe(
        startWith(''),
        debounceTime(200),
        distinctUntilChanged(),
        tap(() => this.documentloading = true),
        switchMap(term => this._service.suggestIncommingDocument({ keyword: term }).pipe(
          catchError(() => of([])), // empty list on error
          tap(() => this.documentloading = false)
        ))
      )
    );
  }

  documentloading: boolean = false;
  lstVanBanDen$: Observable<any[]>;
  documentinput$ = new Subject<string>();

onload data i have check 

 if (this.model.traLoiMaVanBan != null) {
         this.lstVanBanDen$ = concat(
          of([data.traLoiVanBanInfo]));
      }

with this code is binding my object data.traLoiVanBanInfo but can't search on this controll and it not set select value with value = this.model.traLoiMaVanBan 

how can i binding my selected value and keep search with that controll

**Comment by vietdq1291** [comment]
help me !

**Comment by varnastadeus** [comment]
create reproducible example

**Comment by vietdq1291** [comment]
data.traLoiVanBanInfo {value:1, text:"something"} is a object have value i have select on create (this.model) save in database , code above it's edit (this.model) with data i have this.model.traLoiMaVanBan

**Comment by vietdq1291** [comment]
<ng-select formControlName="traLoiMaVanBan"
[items]="lstVanBanDen$ | async"
bindLabel="text"
bindValue="value"
[hideSelected]="true"
[loading]="documentloading"
[typeahead]="documentinput$"
[(ngModel)]="model.traLoiMaVanBan">

// Async Data from Server 
private loadIncommingDocument() {
this.lstVanBanDen$ = concat(
of([]), // default items
this.documentinput$.pipe(
startWith(''),
debounceTime(200),
distinctUntilChanged(),
tap(() => this.documentloading = true),
switchMap(term => this._service.suggestIncommingDocument({ keyword: term }).pipe(
catchError(() => of([])), // empty list on error
tap(() => this.documentloading = false)
))
)
);
}

// Variable
documentloading: boolean = false;
lstVanBanDen$: Observable<any[]>;
documentinput$ = new Subject();


//Value first 

traLoiVanBanInfo = [{ value : 1, text : "Special"}];

model.traLoiMaVanBan = 1;

How to bindding selected value with **model.traLoiMaVanBan**  and list data **traLoiVanBanInfo** 

and keep using search when remove this value **model.traLoiMaVanBan**

**Comment by varnastadeus** [comment]
pasting your code snippets doesn't help

**Comment by vietdq1291** [comment]
I have found the way
