### ISSUE TITLE
Emit event when an item is selected

### ISSUE THREAD

**Issue by dsteegen** [ng-select/ng-select#844]
Hi,

In an older version (2.1.x) of ng-select, the `add` event was also triggered when selecting an item if the component is not configured to handle multiple selects. This feature was removed in a recent version (commit of 09/07 at line 402 in `ng-select.component.ts`). Is there a reason why this was removed for single selects?
Is it possible to re-add this behaviour or to add a different kind of event (e.g `itemSelected`)? If not, how can I determine when an item is selected by the user?

**Comment by varnastadeus** [comment]
there is explanation in #824

**Comment by dsteegen** [comment]
Thank you. That's exactly what I was looking for :)
