### ISSUE TITLE
Multiselect: Removing one object with same bindLabel as other objects will remove others too.

### ISSUE THREAD

**Issue by twsgermany** [ng-select/ng-select#845]
Hello, I just wanna ask if you can combine two attributes for bindLabel.
So for example I have **name** and **id**.

If I selected 3 Objects with the same **name** value in multiselection and remove it with the X symbol, it will remove all Objects with the same name attribute from the ngModel.
Example:
 ______
(  x  Foo )
 ______

{"id":1,"name":"Foo"}
{"id":2,"name":"Foo"}
{"id":3,"name":"Foo"}

**Describe the solution you'd like**
So my idea was to combine **name** and **id** in bindLabel.
But I have no idea how I can do that.

 ______
|  x  Foo(ID:1) |     |  x  Foo(ID:2) |     |  x  Foo(ID:3) |
 ______

{"id":1,"name":"Foo"}
{"id":2,"name":"Foo"}
{"id":3,"name":"Foo"}

I appreciate every answer.

Have a nice day :)

**Comment by twsgermany** [comment]
So #738 would solve it but mayber somebody know an other workaround :)

**Comment by varnastadeus** [comment]
items are unselected by reference not by label names, you are probably doing something wrong. Create reproducible example if you want help
