### ISSUE TITLE
Binding to items does not work

### ISSUE THREAD

**Issue by korenb** [ng-select/ng-select#849]
I've been trying to bind some data (all countries) to `[items]` property. But `<ng-select>` does not act with that. I do have no idea why this behavior is happening. hlp pls!

i created the case on StakBlitz.com:
https://stackblitz.com/edit/angular-select-with-geonames

**Expected behavior**
`<ng-select>` sees updates on `[items]` property and renders select options accordingly.

**Comment by varnastadeus** [comment]
you should return in your map function 😮 
```javascript
loadCountries() {
    this.countries$ =
      of(Countries.Get())
        .pipe(
          map(data => {
            let items = data.geonames.map(record => {
              return {
                id: record.geonameId,
                name: record.countryName
              };
            });
            console.log(items);
            return items;
          })
        )
  }
```

**Comment by korenb** [comment]
that's mad. it's found out it's a little thing i missed :slightly_frowning_face:
