### ISSUE TITLE
[Feature] New output event "beforeChange" with option to cancel

### ISSUE THREAD

**Issue by ahweis** [ng-select/ng-select#850]
The `(change)` event allows one to react on changes, but first after the model also has changed. In case one wants to validate the old model state agains the new model state it would be very nice to have a `(beforeChange)` event fired with the possibility to "cancel" the change.

**Scenario:**
If a change in the selected value have side effects to other parts of the application one might want to prompt the user with a confirmation dialog, and only continue the change if the user accepts the side effects related to the change. If the user do not accept, it should be possible to "cancel" the change and dont have any model state changes propagated from the select control.

**Comment by anjmao** [comment]
@ahweis Hi, thanks for suggestion.

In you scenario it could be useful. One thing is that beforeChange can't be output because it's one way from ng-select to user. Instead it could be Input which returns Promise.

```ts
class NgSelect {
   @Input() beforeChangeFn: (event$) => Promise;
}
```
User component
```ts
@Component({
     template: `
          <ng-select [beforeChangeFn]="beforeChangeFn"></ng-select>
    `
})
class MyComponent {
    beforeChangeFn = (event$)  => {
          if (confirm('Are you sure about this change')) {
                return Promise.resolve();
          }
          return Promise.reject();
    }
}
```

**Comment by AnthonyLenglet** [comment]
Needed this feature not too long ago, as I was in the exact same case mentioned (Asking for additional info before confirming the change, with the ability to cancel the change)

here's what I ended up doing:
```typescript
private refreshStatus(item: Object & { status: string }) {
  const old_status = item.status
  item.status = undefined
  this.changeDetectorRef.detectChanges()
  item.status = old_status
}
```
Works, but definitely feels odd to do, an event for this would be super nice

**Comment by gitmibrahim** [comment]
Any updates about this suggestion?

**Comment by harvanchik** [comment]
Could really use this right about now.

**Comment by seb9465** [comment]
I agree ! Would be cool to have.

**Comment by btimfl** [comment]
Any updates?
