### ISSUE TITLE
ng-select (no style, even when importing as shown in examples)

### ISSUE THREAD

**Issue by TolgaND** [ng-select/ng-select#853]
### Expected behaviour
I was expecting to see the default style when using this ng-select library in Angular 6.0.1.

### Actual behaviour
It seems that is has no style, even when I am importing a theme like the following in my scss file:
`@import "~@ng-select/ng-select/themes/material.theme.css";`

<img width="1207" alt="screen shot 2018-10-09 at 12 21 51" src="https://user-images.githubusercontent.com/7658320/46645308-516ba000-cbbf-11e8-9cee-37b2dac24373.png">

<img width="1211" alt="screen shot 2018-10-09 at 12 21 59" src="https://user-images.githubusercontent.com/7658320/46645314-54ff2700-cbbf-11e8-85fe-4773b07fe9f8.png">

### More Info
ng-select version: 2.10.1

browser: Google Chrome

reproducible in demo page: NO

**Comment by varnastadeus** [comment]
create reproducible example

**Comment by Avillanueva1997** [comment]
Did you solve the problem? I have the same issue.

-Angular 6.0.3
-"@ng-select/ng-select": "^2.10.1"

**Comment by TolgaND** [comment]
> Did you solve the problem? I have the same issue.
> 
> -Angular 6.0.3
> -"@ng-select/ng-select": "^2.10.1"

Nope... I already hate this library!

**Comment by TolgaND** [comment]
> create reproducible example
Here you go:
https://github.com/TolgaND/select-example

**Comment by varnastadeus** [comment]
@TolgaND why are you using if you hate it? If you have read README carefully you would see that styles should be imported to your `styles.css` or `angular.json`. Also if you knew something about angular view encapsulation it would be obvious for you why importing it to `app.component.css` doesn't work needs to be changed to make it work.

Next time before writing your hateful comments take time to read the docs and learn how things works instead of showing your incompetence.

**Comment by TolgaND** [comment]
> @TolgaND why are you using if you hate it? If you have read README carefully you would see that styles should be imported to your `styles.css` or `angular.json`. Also if you knew something about angular view encapsulation it would be obvious for you why importing it to `app.component.css` doesn't work and what needs to be changed to make it work.
> 
> Next time before writing your hateful comments take time to read the docs and learn how things work instead of showing your incompetence.

What are you blabbering about? I followed the tutorial as shown on Github and other sites! I was only saying that I hated it already because it doesn't work as how it should be! You are one ignorant asshole!

**Comment by kaproslaci** [comment]
> ### Expected behaviour
> I was expecting to see the default style when using this ng-select library in Angular 6.0.1.
> 
> ### Actual behaviour
> It seems that is has no style, even when I am importing a theme like the following in my scss file:
> `@import "~@ng-select/ng-select/themes/material.theme.css";`
> 
> <img alt="screen shot 2018-10-09 at 12 21 51" width="1207" src="https://user-images.githubusercontent.com/7658320/46645308-516ba000-cbbf-11e8-9cee-37b2dac24373.png">
> 
> <img alt="screen shot 2018-10-09 at 12 21 59" width="1211" src="https://user-images.githubusercontent.com/7658320/46645314-54ff2700-cbbf-11e8-85fe-4773b07fe9f8.png">
> 
> ### More Info
> ng-select version: 2.10.1
> 
> browser: Google Chrome
> 
> reproducible in demo page: NO

You don't have any "scss file" (i assume you were thinking about your app.component.css . That's just a pure css file. I can assure you that the library works if you follow the tutorial and you can distinguish .css and .scss extensions.
