### ISSUE TITLE
clearSearchOnAdd is "false" by default

### ISSUE THREAD

**Issue by zolastro** [ng-select/ng-select#854]
**Describe the bug**
Although documentation states that clearSearchOnAdd is "false" by default, but just updated to the current version and I had to explicitly set it to "true". (I was using a multiple ng-select)
**To Reproduce**
Update to the current version and use `<ng-select [items]="myitems" [multiple]="true"></ng-select>` in any project Angular +6.

**Expected behavior**
It should delete the text after pressing Enter or clicking an option

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Chrome

**Comment by varnastadeus** [comment]
It is by design. I updated readme
