### ISSUE TITLE
ng-clear not clickable on iOS safari

### ISSUE THREAD

**Issue by ubien** [ng-select/ng-select#856]
**Describe the bug**
Clearable 'x' of input box does not work on safari in iOS

**To Reproduce**
1. Go to [demo site](https://ng-select.github.io/ng-select/) on IOS 
2. Open a dropdown and select an item
3. Try to click 'x' to clear selection

**Expected behavior**
Selected item should be cleared

**Screenshots**
![no-x](https://user-images.githubusercontent.com/361696/46681836-f460f180-cba0-11e8-8b37-4bf99903e829.gif)

**Smartphone (please complete the following information):**
 - Device: iOS Simulator
 - OS: 12
 - Browser: safari
 - Version: ? 

**Additional context**
It seems like there is an element overlapping the 'x' causing event to not be captured.

**Comment by AndersTornkvist** [comment]
Seems to be a problem also in iOS 12 Chrome 70.0.3538.60.

**Comment by varnastadeus** [comment]
should be fixes in #923

**Comment by kurpav** [comment]
It's not fixed 😭

**Comment by longwa** [comment]
This is still an issue in iOS 12.4, should this ticket be re-opened?

**Comment by smessimer** [comment]
I'm still seeing the issue.

**Comment by matsta25** [comment]
Still the same... :/
