### ISSUE TITLE
Default value

### ISSUE THREAD

**Issue by guuse** [ng-select/ng-select#858]
Im looking at the docs but can't find a way to add default value. For now im using a placeholder as default value but that's not how I want it. What i'm trying to do is if there is one value in my array, to default to that option instead of having to open the dropdown to select the single value.
![schermafbeelding 2018-10-10 om 09 21 18](https://user-images.githubusercontent.com/17782988/46719310-e4fbaa00-cc6d-11e8-9814-4086f25c5871.png)

**Comment by varnastadeus** [comment]
@guuse "default value" should be set as your `ngModel`

**Comment by guuse** [comment]
then something is wrong, when I console.log my package it's correct. But it isn't displayed.

**Comment by varnastadeus** [comment]
set `bindLabel` with property you want to display 🤔

**Comment by guuse** [comment]
Used that before, working now but wasn't working before. Think I might made a typo before, sorry feel stupid. Could you check out my first comment, about the default open. Still kinda stuck on that, sorry i'm new to this package.

**Comment by varnastadeus** [comment]
If you feel stupid, read `README` and check demo page. It will answer all your questions

**Comment by guuse** [comment]
I did read both but I can't find the open options in both, am I blind or isn't it there. For the default open problem.
