### ISSUE TITLE
Add tag text still shows even if there is a match on items Angular 5 (ng-select@1.6.2)

### ISSUE THREAD

**Issue by johnfrades** [ng-select/ng-select#859]
**Describe the bug**
The add item tag still shows even if there is a direct match with the existing option.
I am on Angular 5 and im using 1.6.2 version of ng-select. I saw that this issue already been raised and resolved. Before im only on 1.6.0 then i found out that its been fixed on #732. So i tried to upgrade to the latest 1.x version, but still the add tag text still exist.

Heres my code

`  <ng-select [items]="['data', 'baba', 'fafa']"
             labelForId="subCategory"
             [addTag]="addTag"
             [hideSelected]="true"
             multiple="true"
             [(ngModel)]="someThing">
  </ng-select>
`

**To Reproduce**
1. Just install the 1.6.2 version and try to add tag with existing option, the add tag text still there

**Expected behavior**
Add tag text shouldnt appear if there is already a direct match on existing option

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 8.1
 - Browser: Google Chrome
 - Version 69

**Additional context**
I double checked and the fix was inside the 1.6.2 version
https://github.com/ng-select/ng-select/compare/v1.6.2...master

Is anyone experiencing the same problem?

**Comment by johnfrades** [comment]
Here's the stackblitz example. Im running angular 5 and ng-select 1.6.2
and it the problem persists there

[Stackblitz Example](https://stackblitz.com/edit/angular-5-example-n6fplu)

Thank you

**Comment by varnastadeus** [comment]
It was fixed in 2.x branch and we generally don't back port it to 1.x but if you could cherry pick the commit and create the PR I will gladly merge it.
