### ISSUE TITLE
NG_SELECT_DEFAULT_CONFIG is wrongly provided (should be global)

### ISSUE THREAD

**Issue by atakchidi** [ng-select/ng-select#862]
Default implementation of NG_SELECT_DEFAULT_CONFIG injection token is provided each time with the NgSelectModule.
This means token is overwritten each time you import the NGSelectModule in a lazy loaded module. Workaround to this would be a wrapped module that imports NGSelectModule and adds NG_SELECT_DEFAULT_CONFIG to providers, and everywhere where NgSelect is needed we could use that wrapper.
But this is a wrong way to do things in all cases. No point in DI at all. Docs are misleading and whole point of the config is gone.

Plus according to the [docs](https://github.com/ng-select/ng-select#step-4-optional-configuration), you can provide separate params for the config, but currently this not gonna work as expected, all missing params will be undefined

**Expected behavior**
NG_SELECT_DEFAULT_CONFIG shouldn't be provided, right way to provide defaults for the token is via  [factory parameter](https://angular.io/api/core/InjectionToken#description)

**Comment by ivanpadavan** [comment]
@atakchidi Did your PR anyhow solved the problemwith overriding due to lazy load?

**Comment by atakchidi** [comment]
@ivanpadavan Yes sure it does.
It was one of the main reasons why I created that pr.
Now config is provided as any other [angular singletone service](https://angular.io/guide/singleton-services#providing-a-singleton-service). So it will share the same instance unless you would make it not to do so.

**Comment by ivanpadavan** [comment]
@atakchidi You opened my eyes about singleton services in librarian code! Thank you!
