### ISSUE TITLE
MultiSelect enhancement

### ISSUE THREAD

**Issue by jiangyh1024** [ng-select/ng-select#865]
**Is your feature request related to a problem? Please describe.**
if I select many items, some items will be placed into another line.

**Describe the solution you'd like**
I think there should be a property, and user can specify its value, for example [maxTags]="3", if I select more than 3 items, then the select box should show '1 more item is selected'

more details:
there is a datasource = ['a', 'b', 'c', 'd', 'e', ...]; and I set [maxTags]="3" to <ng-select [maxTags]="3">
if I select 'a', 'b', 'c', then the select box should show 'a' , 'b', 'c'.
if more than 3 items are selected, then the select box should show
'a' , 'b', 'c', '1 more item is selected'
'a' , 'b', 'c', '2 more items are selected' 

here is an example
https://www.telerik.com/kendo-angular-ui/components/dropdowns/multiselect/summary-tag-mode/
you can run the code on 'Grouping Tags Based on the Number of Selections' section

**Describe alternatives you've considered**

**Additional context**

**Comment by jiangyh1024** [comment]
What I want to solve is do not put items to a new line if many items are selected. Hope you can improve this. Thank you.

**Comment by varnastadeus** [comment]
this is already supported just check last example in https://ng-select.github.io/ng-select#/multiselect

**Comment by jiangyh1024** [comment]
Oh, Found that. Thank you.

**Comment by sangecz** [comment]
Hi, are we able to limit ng-select to show exact number of lines (multiple=true)? thx
