### ISSUE TITLE
Multiple Select not listening to model changes

### ISSUE THREAD

**Issue by lachskardinal** [ng-select/ng-select#866]
**Describe the bug**
When I remove a element from the binded property Array, the Component does not react.

**To Reproduce**
1. Go to https://ng-select-b7379q.stackblitz.io/
2. Fill Dropdown with multiple Values
3. Open Console
4. Click the Delete First Entry Button

**Expected behavior**
The Component should show only Elements that are in the Array.

**Stackblitz**
https://stackblitz.com/edit/ng-select-b7379q?file=app/app.component.ts

Thanks in advance 😉

**Comment by varnastadeus** [comment]
you should [mutate](https://github.com/ng-select/ng-select#change-detection) your array: 
```javascript
selectedItems = this.selectedItems.filter(x => x !== item);
```

**Comment by lachskardinal** [comment]
Thank you for your feedback 👍 

Works now.
