### ISSUE TITLE
addTag, how to validate after add the new tag?

### ISSUE THREAD

**Issue by kathiraashi** [ng-select/ng-select#867]
```
<ng-select [items]="_Customers"
           [addTag]="addTagPromise"
           [bindLabel]="'name'"
           [(ngModel)]="selectedCustomer">
</ng-select>
```

**addTag** is working but **addTagPromise function** inside already defined values not accessible

```
  _Customers: any[] = [];
  companies = ['company one', 'company Two', 'company three'];
  selectedCustomer;

  ngOnInit() {
     this.companies.forEach((c, i) => {
         this._Customers.push({ id: i, name: c });
     });
  }

  addTagPromise(name) {
    console.log(this._Customers);
     return new Promise((resolve) => {
        setTimeout(() => {
            resolve({ id: 5, name: name, valid: true });
         }, 1000);
     })
  }
```

printed log is undefined

how to access the already defined values inside of addTagPromise function?

**Comment by varnastadeus** [comment]
Use arrow function

**Comment by varnastadeus** [comment]
addTagPromise = (name) => {
 };

**Comment by kathiraashi** [comment]
its not working

**Comment by kathiraashi** [comment]
> Use arrow function
> 
> ```js
> addTagPromise = (name) => {
> };
> ```

its not working

**Comment by identiq** [comment]
@varnastadeus It is working, many thanks !

**Comment by varnastadeus** [comment]
I don't think this is related to `ng-select`, this is how js works and if you don't have `this` in your function it works perfectly fine. 
More about it here:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#No_separate_this
