### ISSUE TITLE
::ng-deep deprecated - update docs?

### ISSUE THREAD

**Issue by rmcsharry** [ng-select/ng-select#870]
Not really a bug, just letting you know that the docs state this:

> If you are using ViewEncapsulation, your should use special ::ng-deep selector which will prevent scoping for nested selectors.

but :`:ng-deep` has [already been removed ](https://www.chromestatus.com/features/6750456638341120)from Chrom (v63, now on 69) and Opera.

Also it is marked [deprecated](https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep) in Angular.

**Comment by anjmao** [comment]
Hi @rmcsharry, thanks for info 👍. I added warning and pointed to this issue https://github.com/angular/angular/issues/17867.
