### ISSUE TITLE
option elements must have right align in rtl mode

### ISSUE THREAD

**Issue by MetaiR** [ng-select/ng-select#871]
in the RTL mode, everything starts from right to left (obviously) including option elements inside the drop-down menu

but in the demo the options align for RTL mode is left, so the problem is:
![image](https://user-images.githubusercontent.com/7807264/46916959-6b95eb80-cfce-11e8-88ac-d6980175a291.png)

I create a simple pull request that will fix this problem #868 
@varnastadeus

**Comment by anjmao** [comment]
@MetaiR Thanks for contributing, I merged you fix. It's working now 👍
