### ISSUE TITLE
What to remove in V3 release?

### ISSUE THREAD

**Issue by anjmao** [ng-select/ng-select#872]
Before making V3 breaking change release I would like to get you opinion about functionality which we could remove in V3 release.

Initial list:
- [ ] [Highlight](https://github.com/ng-select/ng-select/blob/master/src/ng-select/ng-option-highlight.directive.ts) can be easily implemented by user itself and this is something that really doesn't add much value. This could be deprecated and removed in V3.
- [ ]  Remove `<ng-option>` tag. Currently there are two ways of setting data. Using [items] input and ng-option tag with *ngFor. It adds a lot of extra complexity.

**Comment by maxkorz** [comment]
Hi. Please do not remove `<ng-option>` tag. Angular encourages and promotes declarative syntax in the templates. With `<ng-option>` I can easily create simple selects, for example:
```html
<ng-select [(ngModel)]="order">
  <ng-option [value]="1">A to Z</ng-option>
  <ng-option [value]="-1">Z to A</ng-option>
</ng-select>
```
I don't want to create an array of objects in component's controller for such simple use-case.
