### ISSUE TITLE
when I have parent and no grouped items selected and I remove a non grouped element the parent value disappears

### ISSUE THREAD

**Issue by yduartep** [ng-select/ng-select#876]
**Describe the bug**
If I select a parent group and multiple items (children or not grouped) and I remove a not grouped item, the text of the parent group disappears from the selection.

**To Reproduce**
1. Go to https://stackblitz.com/edit/ng-select-ejmvk8
2. Select the item Developers, Marketing and Bussiness
3. Remove the Marketing item (non grouped item).
4. Now you will see that the Developers element is deselected and no more displayed in the selection.

**Expected behavior**
When I remove a parent group from the selection the behaviour is correct but when I remove a child or non grouped element, the Developers parent group should stay selected and displayed in the selection list.

**Screenshots**
![ng select - remove item](https://user-images.githubusercontent.com/24477117/47014933-f2bc9e00-d14b-11e8-8e1d-2a09eb99545a.png)

**Desktop (please complete the following information):**
 - OS: macOS High Sierra version 10.13.6
 - Browser [chrome]
 - Version [69.0.3497.100 (Official Build) (64-bit)]

**Comment by anjmao** [comment]
Hi @yduartep,
It looks like you have a bug in you custom onRemoveItem code. There is let-clear method exposed on ng-template exactly for that. Yous should use built in clear method instead of custom one.

```html
<span class="ng-value-icon left" (click)="clear(item)" aria-hidden="true">×</span>
```
Le me know if it helped :)

**Comment by yduartep** [comment]
You were right. I didn't know about that method. It's working. Thanks
