### ISSUE TITLE
Implementing an auto populating ng-select

### ISSUE THREAD

**Issue by gustavofrancoporto** [ng-select/ng-select#880]
I'm trying to create a select that is able to populate itself using the ng-select component and a custom directive that loads the data and set it to the ng-select.
The directive code is very simple. Something like this:

```typescript
@Directive({
	selector: '[dataLoader]'
})
export class DataLoaderDirective implements AfterViewInit {

	constructor(
		private host: NgSelectComponent,
		private someService: SomeService) {
	}

	ngAfterViewInit(): void {
		this.someService.findItems().subscribe(items => this.host.items = items);
	}
}
```

However, this is not populating the select as desired. The ng-select is still empty after the items property is updated with the new data. I see that there is a method to set the items but it is private.
Am I doing something wrong? If not, would it be possible to add this feature to the ng-select?

**Comment by gustavofrancoporto** [comment]
I was able to do this by calling ngOnChanges manually.

Thanks you!

**Comment by levchukanton** [comment]
another solution
https://stackblitz.com/edit/ng-select-infinite-lqfzq2
from here
https://medium.com/@isaacplmann/ngonchanges-only-runs-when-the-input-change-comes-from-a-template-binding-like-component-8797b759ba0b
