### ISSUE TITLE
Multi column dropdown

### ISSUE THREAD

**Issue by Tabris841** [ng-select/ng-select#881]
Hello, 
I like to ask is there a way to split the dropdown options into multiple columns, for example 2 columns.
Like so
![screenshot 2018-10-18 at 18 01 34](https://user-images.githubusercontent.com/12796958/47164056-e9743280-d2ff-11e8-9e4c-162729f1351f.png)

I tried doing it with template , but didn't find solution.

**Comment by varnastadeus** [comment]
as shown in #802 it is possible using css flex features, but columns dynamic based on whole width and width of single option.

**Comment by Tabris841** [comment]
It work that way thanks a lot !

**Comment by munishahaha** [comment]
@Tabris841  could you please create a demo on stackbliz ?
