### ISSUE TITLE
ERROR TypeError: items.map is not a function

### ISSUE THREAD

**Issue by VitaTamry** [ng-select/ng-select#882]
I am using ng select with a server-side search. while  I am typing in the search this error shows up "ERROR TypeError: items.map is not a function"

this is the HTML 
` <ng-select [items]="users | async"
            [virtualScroll]="true"
            bindLabel="name"
            bindValue="id"
            placeholder="إختر موظف"
            [loading]="usersLoading"
            [multiple]="true"
            [typeahead]="usersinput$"
            [(ngModel)]="selectedUserIds">
  </ng-select>`

and this is the ts

```
import { Subject, of , concat} from "rxjs";
import { debounceTime, distinctUntilChanged, tap, switchMap, catchError } from "rxjs/operators";
import { UserService } from "../../../service
export class EditCompany implements OnInit {
  
  selectedUserIds: number[];
  users:any;
  usersinput$ = new Subject<string>();
  usersLoading = false;

 ngOnInit() {
    this.loadusers();
}
private loadusers() {
    this.users = concat(
        of([]), // default items
        this.usersinput$.pipe(
           debounceTime(200),
           distinctUntilChanged(),
           tap(() => this.usersLoading = true),
           switchMap(term => this.UsersS.findUser(term).pipe(
               catchError(() => of([])), // empty list on error
               tap(() => this.usersLoading = false)
           )) 
        )
    );
}
```

I am using Angular 6 and ng-select ^2.10.5

any help would be much appreciated

**Comment by varnastadeus** [comment]
please create reproducible example

**Comment by VitaTamry** [comment]
Okay.
[](https://stackblitz.com/edit/ng-select-rmgfrw)

**Comment by varnastadeus** [comment]
it works for me without errors

**Comment by VitaTamry** [comment]
Thank for your time.

I changed the HTTP request with your example [here](https://github.com/ng-select/ng-select/blob/master/demo/app/shared/data.service.ts)
and it worked.
so I made this change and still not working 
`
 getPeople(term: string = null): Observable<any> {
    let items = this.http.get(this.globals.backendUrl+'/finduser/'+term);
    if (term) {
       items
        .subscribe(x => items = x['data']);
    }
    return of(items).pipe(delay(500));
}
`

here is the data from the server 

`
0: {id: 1, name: "admin", email: "admin@test.com", phone: "01234567890", deleted_at: null, …}
1: {id: 3, name: "test", email: "test@test.com", phone: "01234567870", deleted_at: null, …}
2: {id: 4, name: "fsdf", email: "fdfd@ik.de", phone: "98347289347928", deleted_at: null, …}
3: {id: 5, name: "fsd", email: "fs@we.de", phone: "111111111111", deleted_at: null, …}
4: {id: 6, name: "fsd", email: "fsdf@e.e", phone: "222222222222", deleted_at: null, …}
5: {id: 19, name: "cdcs", email: "DED@OK.DE", phone: "92929292929992", deleted_at: null, …}
6: {id: 21, name: "mina", email: "mina@test.com", phone: "0987765445674", deleted_at: null, …}
7: {id: 22, name: "sw", email: "sw@sw.de", phone: "02993838727473", deleted_at: null, …}
8: {id: 23, name: "wsa", email: "lm@lm.cpm", phone: "0999009990909", deleted_at: null, …}
`

**Comment by varnastadeus** [comment]
unless you create reproducible example, I can't help you with anything
