### ISSUE TITLE
Update to Angular 7

### ISSUE THREAD

**Issue by carlosasj** [ng-select/ng-select#883]
**Is your feature request related to a problem? Please describe.**
The only problem is update to Angular 7, because the peer dependencies are set to `>=6.0.0 <7.0.0`

**Describe the solution you'd like**
I believe that update the peer dependencies to `>=6.0.0 <8.0.0` would be enough, but some tests cannot do harm :)

**Comment by anjmao** [comment]
@carlosasj Would you like to help with this one ? :)

**Comment by carlosasj** [comment]
Of course I can help :)

I'll have time to look on this tonight
