### ISSUE TITLE
Use @HostBinding('attr.tabindex') instead of @Attribute('tabindex') in constructor

### ISSUE THREAD

**Issue by Marka83** [ng-select/ng-select#884]
**Is your feature request related to a problem? Please describe.**
I would like to write a component which use ng-select and I want to bind its tabindex attribute to ng-select's. This will not work because you use @Attribute('tabindex') in constructor so binding will not be propagated to filterInput element.

**Describe the solution you'd like**
Use this instead:
@HostBinding('attr.tabindex')
@Input() public tabindex: string;

**Describe alternatives you've considered**
I could possibly manually set  tabindex on filterInput native element, but it wouldn't be elegant solution.

**Additional context**

**Comment by varnastadeus** [comment]
why it won't be propagated?

**Comment by Marka83** [comment]
Because @attribute will only work with static values.
Look at this post:
https://netbasal.com/getting-to-know-the-attribute-decorator-in-angular-4f7c9fb61243
In last comment, author says it's for static strings only.

I've tried it on ng-select and only static tabindex will set tabindex on filterInput

Maybe I missed something and there is another way to set bound tabindex.

**Comment by varnastadeus** [comment]
should be fixed in the latest version
