### ISSUE TITLE
Default values in multi-select async

### ISSUE THREAD

**Issue by VitaTamry** [ng-select/ng-select#886]
This is not a bug but a question
I am trying to set default values in multi-select with async data source and it's not working 

my HTML 
` <ng-select style="padding-top: 10px" [items]="users | async"
            [virtualScroll]="true"
            bindLabel="name"
            bindValue="id"
            placeholder="إختر موظف"
            [loading]="usersLoading"
            (add)="addUser($event)"
            [multiple]="true"
            [typeahead]="usersinput$"
            [(ngModel)]="selectedUser">
  </ng-select>`

and TS
```
 comp: any;
  submitted: boolean;
  EditCompanyForm: FormGroup;
  errors: any;
  logo: any;
  uploadLogo: any;
  progress:any;
  selectedUser:User[];
  users:any;
  usersinput$ = new Subject<string>();
  usersLoading = false;

 ngOnInit() {
    this.loadusers();
 this.getComapny();
}
getComapny() {
    const id = +this.route.snapshot.paramMap.get("id");
    this.companyService.getCompany(id).subscribe(res => {
      this.assignCompany(res);
    });
  }
 assignCompany(data) {
    this.comp = data;
    let u=this.comp.employees.map(a=>a.user);
//here where I am trying to assign the default values
    this.selectedUser= u     ;
   });
     }
```
**Expected behavior**
I can find the selected users + search the backend to select users

Angular 6 
ng-select 2.10.5

**Comment by varnastadeus** [comment]
can you create reproducible example so I could point what to change?

**Comment by VitaTamry** [comment]
@varnastadeus 

here's my code 
[https://stackblitz.com/edit/ng-select-rmgfrw](https://stackblitz.com/edit/ng-select-rmgfrw)

**Comment by varnastadeus** [comment]
your code doesn't even compiles

**Comment by VitaTamry** [comment]
@varnastadeus 

I think @angular/router wasn't installed. I fixed this.
but the rest of the code is working on my project (except for the issue)

**Comment by varnastadeus** [comment]
<img width="532" alt="screenshot 2018-10-20 at 17 52 43" src="https://user-images.githubusercontent.com/17824796/47257013-f8d6b580-d490-11e8-9052-de525cd0b56e.png">

**Comment by VitaTamry** [comment]
@varnastadeus 
it works now

**Comment by varnastadeus** [comment]
<img width="636" alt="screenshot 2018-10-20 at 19 29 04" src="https://user-images.githubusercontent.com/17824796/47258060-6d642100-d49e-11e8-83b4-70b18cd3edee.png">
There is warning in console, if you want to set your model as object you should not use `bindValue`.
Or if you want to use bindValue and object then define `compareWith` so ng-select could resolve your value by your predicate.

**Comment by VitaTamry** [comment]
@varnastadeus 
This was a great help
Thank you.

**Comment by heisaman** [comment]
> @varnastadeus
> This was a great help
> Thank you.

@VitaTamry Hi, I faced the same problem with yours. How did you solve it, with the code snippet provided above?

**Comment by VitaTamry** [comment]
@heisaman

Just add      
 `[compareWith]="selectedUsersFn"`
and pass the selected items with this
`[(ngModel)]="selectedUser"`
where this function returns true on the selected id
`selectedUsersFn = (item, selected) => {
    if (selected.id && item.id) {
        return item.id === selected.id;
    }`

**Comment by heisaman** [comment]
> <img alt="screenshot 2018-10-20 at 19 29 04" width="636" src="https://user-images.githubusercontent.com/17824796/47258060-6d642100-d49e-11e8-83b4-70b18cd3edee.png">
> 
> There is warning in console, if you want to set your model as object you should not use **bindValue**.
> **_Or if you want to use bindValue and object as model then define `compareWith` so ng-select could resolve your value by your predicate._**

@VitaTamry Thank you for your quick reply!! I figured out that by removing bindValue attribute, ng-select works fine with pre-selected values.
However, what if I want to preserve bindValue and string value list as model, can I achieve the same effect? I don't quite understand the 2nd solution provided by @varnastadeus

**Comment by VitaTamry** [comment]
@heisaman 
Not sure

**Comment by gauravmasand09** [comment]
Is this issue solved? because i cannot bind the data for async multiselect
