### ISSUE TITLE
Do not select groups by default when searching

### ISSUE THREAD

**Issue by AndersTornkvist** [ng-select/ng-select#887]
In the [demo page](https://ng-select.github.io/ng-select#/grouping) tab _Grouping_, there is an example (_Example 4_) with selectable multiple groups. When searching for "Adam" and pressing [ENTER], "United States" is selected.

I would like an option that prevents groups from getting selected by default. The first filtered item should instead get selected in this case.

```
<ng-select [items]="accounts4"
    bindLabel="name"
    groupBy="country"
    [multiple]="true"
    [closeOnSelect]="false"
    [selectableGroup]="true"
    [compareWith]="selectedAccounts4Fn"
    [(ngModel)]="selectedAccounts4">
    <ng-template ng-optgroup-tmp let-item="item">
        {{item.country || 'Unnamed group'}}
    </ng-template>
</ng-select>
```

**Comment by varnastadeus** [comment]
not sure if this solution is correct, maybe if group is selectable it shouldn't appear in search results unless term matches group name itself.

**Comment by kylesean** [comment]
@AndersTornkvist I agree with you。It's reasonable。

**Comment by armved** [comment]
Hi guys!

So is there an issue for searching selectable groups? I would like to help/contribute to that issue.

**Comment by tylerh** [comment]
Were @AndersTornkvist changes ever released? I really need this feature and I cannot find it. Any help would be appreciated.

**Comment by AndersTornkvist** [comment]
@tylerh Yes, the changes in this issue were included with https://github.com/ng-select/ng-select/commit/6a2a6e7a46b870f24848d6f68c95a7711c130a3e and then released. However, they were removed 
on 5 Jul 2019 with https://github.com/ng-select/ng-select/commit/4fef383efd8c386cfd94ba3208edeb967971cdc8#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

There is a published scoped npm version for Angular 11 with the [excludeGroupsFromDefaultSelection] option added by cherry picking. It also includes the [addTagAlways] option. (Angular 11 support was added by merging the commits in #1844 solving #1803)

```
npm i --save @anderstornkvist/ng-select
```

Do not forget to import from ```'@anderstornkvist/ng-select'``` instead of  ```'@ng-select/ng-select'```
