### ISSUE TITLE
Change event does not fire for manual sets

### ISSUE THREAD

**Issue by Goonersid** [ng-select/ng-select#89]
When i programmatically set a value in the select box, the change event does not fire...

```
 <ng-select
                [items]="accounts"
                bindLabel="currency"
                bindValue="id"
                [multiple]="true"
                (close) = "onModalClose(a,$event)"
                (change) ="onChange()"
                [(ngModel)]="selectedAccounts">
        </ng-select>

<button (click) = "setModel('INR')" class="btn btn-secondary btn-sm"> Set INR</button>

 onChange() {
    console.log('I have changed now');
  }

 setModel(currency: string) {
    
    this.selectedAccounts.push(0);

    let unqiueItems = new Set(this.selectedAccounts);

    this.selectedAccounts = [...Array.from(unqiueItems)];
  
  }
```
### Expected behaviour
Change event should not depend on selection, it should fire no matter how the tag has been added.

### Actual behaviour
Change event fires only if a selection has happened through the select box ui.

**Comment by anjmao** [comment]
@Goonersid Currently change event is fired if model was changed inside ng-select using its controls. Can you describe your use case why would you like to get change event fired if you are setting model programmatically because in this case you already know that change will happen. Thanks :)

**Comment by Goonersid** [comment]
@anjmao  If i had a change event implementation i'd always listen to the change event , programmatically or from the View.. Makes things easy to implement.. Currently i have to call a method from two places, one post manually setting the value and one in the change callback..

**Comment by anjmao** [comment]
This can be fixed by one line of code in ng-select but I checked more popular libraries like angular material 2 select and it also work the same way. If model is changed programatically then change event is not fired and this make sense because you can control it better. I hope this helped you :)

**Comment by dreamid27** [comment]
So, what solution if we want to run change event manually ?
