### ISSUE TITLE
Default value depending on queryParams

### ISSUE THREAD

**Issue by caronalex** [ng-select/ng-select#893]
When I initialize my model from a queryParams, ng-select does not affect his default value.

Example :

`<ng-select [items]="branches" [clearable]="false" [(ngModel)]="selectedBranchId" (change)="selectBranch()"  bindLabel="Name" bindValue="Id" [multiple]="false" placeholder="Select branch plant"></ng-select>`

```
ngOnInit() {
    this.routeParams = this.route.snapshot.params;
    this.selectedBranchId = this.routeParams.selectedBranchId

    this.getBranches();
    this.subscribeToData();
  }
```

`selectedBranchId` is well initialized

The options appear in the dropdown, but none is choosen.

Everything else is working correctly.

**Comment by caronalex** [comment]
For the moment I've switched to the basic <select></select> and it's working.

**Comment by varnastadeus** [comment]
create reproducible example

**Comment by caronalex** [comment]
Yes, there is Id and Name.

Actually, I think this is not my typescript code the problem because when I've changed for the basic `<select></select>`, all was working on the first time.

I think this is a rendering problem. Maybe the `<ng-select></ng-select>` must be rendered after `ngOnInit` have started?

**Comment by varnastadeus** [comment]
there is no difference, there is problem in your setup somewhere

**Comment by caronalex** [comment]
Come on.. I've just said you I've changed nothing on my component.. Anyway.. I'm closing this issue as I will use the default `<select>` in the future

**Comment by varnastadeus** [comment]
without actual example I can't help you out, also if it fits your requirements `<select>` is more than enough

**Comment by marondev** [comment]
There's still an issue on this. `ng-select` dropdown can't detect the change on the value of `queryParams`

Check this sample:
[https://stackblitz.com/edit/angular-akzhs8](url)

**Comment by varnastadeus** [comment]
I think issue was because queryParams returns string by default, so before setting id you should parse it or use `compareWith`
