### ISSUE TITLE
For Empty Array it should display "Not Found"  

### ISSUE THREAD

**Issue by bitturids** [ng-select/ng-select#895]
Please fill below information if issuing a bug report. 
### Expected behaviour
When Array is empty it does not show "Not Found" on selection.
It shows only if I have array values and my entered values do not match with any of array content.

For Example : 

`<ng-select [items]="itemList" [multiple]="true" [hideSelected]="true" placeholder="Select Multiple Deals" [(ngModel)]="selectedDealIds"></ng-select>`

### Actual behaviour
First image is which have values 
![image](https://user-images.githubusercontent.com/8012891/47487259-a9b7c880-d874-11e8-9174-5c1e4a037994.png)

Now, from this array I have typed 0 which does not have value. So , it display not found.

![image](https://user-images.githubusercontent.com/8012891/47487324-ce13a500-d874-11e8-8f45-711460c5de3a.png)

Now, the below image with no array data. and tried to to find one value.
![image](https://user-images.githubusercontent.com/8012891/47487415-fc918000-d874-11e8-894d-cb5319908f26.png)

- If my array is empty , and try to enter any value or by default it should display "No Data"

### More Info
ng-select version: @ng-select/ng-select@2.11.1

browser: Chrome

reproducible in demo page: Yes

**Comment by bitturids** [comment]
@varnastadeus Can you please help me with this?

**Comment by varnastadeus** [comment]
I will check in spare time

**Comment by bitturids** [comment]
Hey, is there any updates ?

**Comment by varnastadeus** [comment]
I think this should work for you
```html
<ng-template ng-notfound-tmp let-searchTerm="searchTerm">
    <div class="ng-option ng-option-disabled">
        {{ itemsStatic.length === 0 ? 'no data' : 'no items found' }}
    </div>
</ng-template>
```

**Comment by bitturids** [comment]
Thanks. I will try to update this.

**Comment by manishambashta** [comment]
Hi @bitturids , I am facing the same issue but the resolve provided is not working for me. Can you share how you resolve your issue?

@varnastadeus : If you can provide any alternative to this, it would be nice.
