### ISSUE TITLE
How can I add an option in my DB by calling a service?

### ISSUE THREAD

**Issue by kypergio** [ng-select/ng-select#896]
I'm not sure if it's  bug or my bad. 
I only need help to solve this. I need create options dinamically in my DB trough an angular service call.

I've tried to do this:
`return new Promise((resolve) => {
      this.variantService.add(name).subscribe(res => {
        resolve(res.d);
      });
    });`

But my service  is never called. It seems this = tagComponent

Sorry if it's a dumy question. Maybe it's not this awesome plugin's issue. But I need to solve this. Thanks in advance regards.

**Comment by varnastadeus** [comment]
from your description I can't help anything, create reproducible example and then we will see

**Comment by varnastadeus** [comment]
@kypergio check this [HttpClient](https://angular.io/guide/http). It should answer all your questions
