### ISSUE TITLE
Ng-select shows blank when a new row is added to ngx-datatable

### ISSUE THREAD

**Issue by ahmettahasakar** [ng-select/ng-select#901]
**Describe the bug**
I have used appendTo="body" as described in other #705 . It works. There is no cutoff. However, when I add a new row to the array of ngx-datatable, the ng-select shows blank. However, the options are still remaining. And also, there is not suppose to be a blank option in the ng-select either.

**To Reproduce**
1. Add a ngx-datatable with a row that has ng-select
2. Select an option from ng-select
3. Add a row to ngx-datatable source array
4. Table is updated, and row is added, however, the option that is selected in Step 2 is gone.

**Expected behavior**
Selected option must have remained

**Comment by varnastadeus** [comment]
create reproducible example

**Comment by ahmettahasakar** [comment]
While recreating the problem, I understood that putting the table in a form tag, triggers error.

[selectTest.zip](https://github.com/ng-select/ng-select/files/2519570/selectTest.zip)

**Comment by varnastadeus** [comment]
can you use [stackblitz](http://stackblitz.com)?

**Comment by ahmettahasakar** [comment]
sure.

https://angular-3uzuqv.stackblitz.io

**Comment by varnastadeus** [comment]
@ahmettahasakar it happens because each of your `ng-select` has same name in form which is `gender`, it should be unique. Try:
```js
<ng-template let-row="row" let-rowIndex="rowIndex" ngx-datatable-cell-template>
              <ng-select [items]="genders"
              name="{{'gender' + rowIndex}}"
              [clearable]="false"
              [(ngModel)]="row.gender"
              appendTo="body"
              [hideSelected]="true"
              required>
              </ng-select>
          </ng-template>
```
