### ISSUE TITLE
bindLabel doesn't working

### ISSUE THREAD

**Issue by Sgourebi** [ng-select/ng-select#903]
I followed the example of ng-select from this page https://github.com/ng-select/ng-select/blob/master/demo/app/examples/dropdown-positions.component.ts

In my Component I have some companies loaded from a service. The service returns the companies like this outpout below.

```
 [
        {
            "id": "5bce7516eba7103a95466709",
            "name": "Lorem1",
            "location": "test",
        },
        {
            "_id": "5bce754feba7103a9546670a",
            "name": "Lorem2",
            "location": "testok",
        },
        {
            "_id": "5bcf78ad050d9221d1fa2918",
            "name": "Lorem3",
            "location": "Plateau",
        }
    ]
```
When I set the **bindLabel** attribute to **name** like this 
```
<ng-select [dropdownPosition]="'top'"
                   [bindValue]="id"
                   [bindLabel]="name"
                   [items]="companies">
        </ng-select>
```
it doesn't work. But when I change the  **name** property of my service response to **label** and set the **bindLabel** attribute to **name** like this
```
<ng-select [dropdownPosition]="'top'"
                   [bindValue]="id"
                   [bindLabel]="label"
                   [items]="companies">
        </ng-select>
```
or without the bindLabel

```
<ng-select [dropdownPosition]="'top'"
                   [items]="companies">
        </ng-select>
```
  it works.

I would like to keep my service response and use the name property instead of label.
I don't know if the [binValue] has the same mistake. 

### More Info
ng-select version: 2.11.2

browser: Chrome

**Comment by Sgourebi** [comment]
I used **bindLabel** instead of **[bindLabel]** and it worked.

**Comment by varnastadeus** [comment]
you should know that `[bindLabel]` is interpolated and `bindLabel` is not
