### ISSUE TITLE
dynamic title for  each item

### ISSUE THREAD

**Issue by aliShreef** [ng-select/ng-select#904]
hi every one ...
i want to ask if there is possible way to add title for each item select in the ng-select.  
my case is that i have to display list of item that user will select from but the items is too long to be display in the component . so i want to add title for each item when user hover the item it will display title (description of the option ) like title attr in the option tag. 
i search for that but i did not find any thing related to this. 
thank you

**Comment by varnastadeus** [comment]
use
```html
<ng-template ng-option-tmp let-item="item">
      <div title="{{item}}">{{item}}</div>
</ng-template>
```

**Comment by abhi747** [comment]
> use
> 
> ```
> <ng-template ng-option-tmp let-item="item">
>       <div title="{{item}}">{{item}}</div>
> </ng-template>
> ```

Hi
Actually I also have sam requirement as mentioned by @aliShreef , i.e. to add title attribute from the items array.

@varnastadeus , Can you please provide this code alongside a sample ng-select dropdown code?
It will be helpful to understand where to place the code you provided earlier with respect to ng-select and analogy between the item in title and in items array.

**Comment by varnastadeus** [comment]
```html
<ng-select>
    <ng-template ng-option-tmp let-item="item">
        <div title="{{item}}">{{item}}</div>
    </ng-template>
</ng-select>
```
