### ISSUE TITLE
does not allow to type space in autocomplete input box

### ISSUE THREAD

**Issue by jayeshsheta** [ng-select/ng-select#905]
<ng-select [items]="buyerList"   bindLabel="v" bindValue="k"  >
               </ng-select>

**Comment by varnastadeus** [comment]
create reproducible example

**Comment by jayeshsheta** [comment]
@varnastadeus ?

**Comment by varnastadeus** [comment]
use [stackblitz](https://stackblitz.com) for that purpose, there is no point to paste your code snippets here

**Comment by jayeshsheta** [comment]
but it not works so i have raise issue

**Comment by varnastadeus** [comment]
from now on I will start closing all issues that don't match this [template](https://github.com/ng-select/ng-select/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)
