### ISSUE TITLE
Getting an error "items.map is not a function"

### ISSUE THREAD

**Issue by marcscheuner-bfh** [ng-select/ng-select#914]
**Describe the bug**
I'm using Angular **6.0.7** and ng-select **2.11.2**. 

This is my "ng-select":

    <ng-select 
          [items]='employees | async'
          bindLabel="id"
          [addTag]='true'
          [multiple]='true'
          [hideSelected]='true'
          [loading]='employeeLoading'
          [typeahead]='employeeInput'
          [(ngModel)]='selectedEmployees'>
    </ng-select>

I have a data service that provides the data for the autocomplete, and it provides an `Observable` (of my data class) - that part works fine.

But when trying to bind this information to a `<ng-select>` - based on what I've read in the docs here: https://ng-select.github.io/ng-select#/filter - I keep getting this error and I don't understand what it really means and how to fix it:

> NgSelectComponent.html:7 ERROR TypeError: **items.map is not a function**  
>  
> at ItemsList.push../node_modules/@ng-select/ng-select/fesm5/ng-select.js.ItemsList.setItems (ng-select.js:1177)  
> at NgSelectComponent.push../node_modules/@ng-select/ng-select/fesm5/ng-select.js.NgSelectComponent._setItems (ng-select.js:3128)  
> at NgSelectComponent.push../node_modules/@ng-select/ng-select/fesm5/ng-select.js.NgSelectComponent.ngOnChanges (ng-select.js:2638)  
> at checkAndUpdateDirectiveInline (core.js:9038)  
> at checkAndUpdateNodeInline (core.js:10306)  
> at checkAndUpdateNode (core.js:10268)  
> at debugCheckAndUpdateNode (core.js:10901)  
> at debugCheckDirectivesFn (core.js:10861)  
> at Object.eval [as updateDirectives] (NgSelectComponent.html:26)  
> at Object.debugUpdateDirectives [as updateDirectives] (core.js:10853)  

What is `items.map` ? `items` on the `<ng-select>` refers to an observable of my data class - I don't have any such function.... do I need to write a `map` function on my data object, to provide the text to be displayed - or what else does this refer to?

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome v70, Firefox v60

**Comment by varnastadeus** [comment]
can you create reproducible example?

**Comment by marcscheuner-bfh** [comment]
Check out:

https://stackblitz.com/edit/angular-1ldpc1

**Comment by mairacosta** [comment]
But he did use async......
