### ISSUE TITLE
Setting Virtual scroll as true, cant see more than two items in list

### ISSUE THREAD

**Issue by deepender87** [ng-select/ng-select#922]
Hi
I am setting [virtualScroll]="true" in ng-select, when i open the list. I am only able to see two or max three items in the list. When i scroll only then i can see the remaining items of list. How i can set the min number of items to be visible in the list when virtualScroll is on.

Thanks

**Comment by varnastadeus** [comment]
Can you create reproducible example?

**Comment by deepender87** [comment]
> Can you create reproducible example?

I will do that, just FYI on focus of it i am making a service call to get the list items. So at this point issue is happening. Second time i am not making any service call ( as i already have list) there it works fine.
