### ISSUE TITLE
Initializing ng-select with previously selected elements

### ISSUE THREAD

**Issue by marcscheuner-bfh** [ng-select/ng-select#925]
I have a ng-select up and running allowing me to select one or several of my employees - works fine. On saving the form, I persist the employee id (a 3 character string plus a number, e.g. "snm2") into my database table.

What I can't seem to figure out (and haven't found anything on the interwebs, either) is how to **initialize** the ng-select next time around, when I show the form, with the employees I had selected the first time around.

Mostly, my trouble is: the input field is a "Subject<string>" - but I bind to an "EmployeeModel" - not just a string. How can I turn those employee id's from my database back into "pre-selected" employees in the ng-select?

**Comment by varnastadeus** [comment]
just use `compareWith`, this compares your selected values with items in the dropdown, if predicate returns true, item gets selected
