### ISSUE TITLE
[single select] cursor disappear

### ISSUE THREAD

**Issue by GoNode5** [ng-select/ng-select#93]
Cursor should be show, tab should close list (I do x to clear then tab  to leave select

BTW Thank you for all your updates. This becoming as the most usable select !!! Great Job.

Another option would by that an single select is not editable when there are limited choices  ...

![singleselect](https://user-images.githubusercontent.com/2210672/31850524-98783620-b653-11e7-9ef1-7aca38356852.gif)

**Comment by anjmao** [comment]
@GoNode5 Thanks for reporting :)
