### ISSUE TITLE
Not working with Angular 7.0.2

### ISSUE THREAD

**Issue by dotNetAthlete** [ng-select/ng-select#935]
**Describe the bug**
An array of items will not show, just says "No items found"

**Comment by varnastadeus** [comment]
can you provide example or should I guess what the problem is?

**Comment by dotNetAthlete** [comment]
In my html:
`<ng-select [items]="arrayForLogTypes"></ng-select>'

In my component in ngOnInit():
`// get a list of call types...
    this.logTypes$ = this.callService.getLogtypes();

    this.logTypes$.subscribe(groupedItems => {
      groupedItems.find(items => {
        var tblLogTypes = items.tblLogTypeLu;
        tblLogTypes.forEach(item => {
          this.arrayForLogTypes.push({ id: item.id, logTypeName: item.logTypeName, parentName: items.classification });
        });
      });
    });`

The items are definitely there because {{ arrayForLogTypes | json }}
in the html shows it all.

**Comment by dotNetAthlete** [comment]
> https://github.com/ng-select/ng-select#change-detection this should solve your issue

WOW, that fixed it, thanks so much, you've potentially saved me days, if not weeks of fruitless hacking!
(I hadn't read as far down the page as Change Tracking and the three dot syntax is bizarre - never seen that before !!)
Change Tracking should really be taught early on in Angular, along with npm dependency management.
