### ISSUE TITLE
On letter click on keyboard it's not scrolling to active option

### ISSUE THREAD

**Issue by JuliaPechenka** [ng-select/ng-select#937]
**Describe the bug**
On selecting option with any letter on keyboard it's not scrolling to this option so user can't see that smth was highlighted.

**To Reproduce** 
1. Go to https://stackblitz.com/edit/ng-select?file=app%2Fapp.component.ts
2. To the last ng-select on examples list add [searchable]="false"
3. Click on this ng-select on browser preview
4. Click 'w' on keyboard
5. Option 'Wladimir' was highlighted as active but it wasn't scrolled to this option.

**Expected behavior**
It should scroll to active option on the list

**Screenshots**
![image](https://user-images.githubusercontent.com/13165476/48255062-e99db480-e40b-11e8-96da-04e7ae1f698a.png)

**Desktop (please complete the following information):**
 - iOS
 - Chrome

**Comment by varnastadeus** [comment]
fixed in latest version
