### ISSUE TITLE
Clear all X button not clickable since v2.12.0  

### ISSUE THREAD

**Issue by ShinDarth** [ng-select/ng-select#938]
After upgrading from v2.11.2 to  v2.12.0, the "clear all" X button in multiple select is no longer clickable (the selection menu will open instead).

I'm trying to reproduce the issue in an isolate environment, no success so far. I'm still opening this one so other users can confirm it if I'm not the only one having the issue.

Edit: after some debugging, this element should receive the click:
![image](https://user-images.githubusercontent.com/75517/48270932-7875f580-e43b-11e8-90a9-331f8b201338.png)

its parent is receiving the click instead:

![image](https://user-images.githubusercontent.com/75517/48270960-86c41180-e43b-11e8-9543-e858bad77aa5.png)

For some reasons, switching back to version 2.11.2 solves the issue for me.

**Comment by varnastadeus** [comment]
this is already fixed in #931

**Comment by varnastadeus** [comment]
will be released in 2.13.0
