### ISSUE TITLE
Readme - Getting Started Step 3 is not clear for Angular 6+

### ISSUE THREAD

**Issue by rmcsharry** [ng-select/ng-select#942]
The readme is not clear on point 3 of Getting Started. I would edit it but I don't know what the actual solution is.

It says this:

> If you're using the Angular CLI, you can add this to your styles.scss or include it in .angular-cli.json (Angular v5 and below) or angular.json (Angular v6 onwards).

then it shows two import statements (which can obviously be put into styles.css).

However what do you put in angular.json for v6+ ?  No example given and there appears to be no node_modules folder for ng-select after installing... so I am not really sure what the guide is suggesting we put into angular.json?

**Comment by varnastadeus** [comment]
you should put path to your styles as you did in previous versions https://github.com/angular/angular-cli/wiki/stories-global-styles
