### ISSUE TITLE
Standard bootstrap validation style does not follow convention

### ISSUE THREAD

**Issue by rmcsharry** [ng-select/ng-select#943]
**Describe the bug**
Very similar to this issue: #227  
When you import the default styles from ng-select for Bootstrap 4.0, the standard validation css does work the same way.

**Reproducbile example**
https://stackblitz.com/edit/ng-select-kzq5ad

**To Reproduce** 
Add standard left border style to required controls:
```
.ng-valid:not(form), .ng-valid.required {
  border-left: 5px solid #2d922d;
}

```
**Expected behavior**
The validation green/red border should be 'inside' the control. Currently it is off to the left. It seems that the input is at a higher index level than the left ng-valid border. If you increase the width of the input you will see that it will totally cover the green border.

**Screenshots**
![image](https://user-images.githubusercontent.com/1156100/48313476-6b810f80-e5bd-11e8-9bee-cf93c5e229b9.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
Mac OS Sierra.
Chrome 70

**Comment by varnastadeus** [comment]
Default theme is not dedicated for bootstrap 4, its default theme which we initially implemented and there is feature request adding actual bootstrap 4 theme #647, so maybe this should be addressed there. Although I am not sure if even then this should work as you described or you need to align styles with control yourself.

For now this should work:
```css
.ng-valid .ng-select-container {
  border-left: 5px solid #2d922d;
}
```
