### ISSUE TITLE
Expose key event to control ng-select behavior

### ISSUE THREAD

**Issue by firstor** [ng-select/ng-select#944]
I need to capture key event on `ng-select` component to customize its natural behavior. For example, when `Ctrl+Enter` is pressed, I need to do some process rather than selecting an item. 
So what I actually need is to get possibility to capture key event and control original behavior by setting a certain flag in the following:
```html
<ng-select ...
    (keyinput)="this.handleKeyInput($event)"
    ...
>
...
```
```ts
handleKeyInput(e: /*NgSelectKeyInputEvent*/) {
    // e.keyEvent: KeyboardEvent
    // e.preventDefault: boolean (true to prevent default behavior of ng-select)
    if (e.keyEvent.ctrlKey && e.keyEvent.which === 13 /* Ctrl + Enter */) {
        console.log('ctrl+enter detected');
        e.preventDefault = true;
        this.doSomeCustomProcess();
    }
}
```
Could you expose such event?

**Comment by varnastadeus** [comment]
#1378 should cover this
