### ISSUE TITLE
Problem with themes

### ISSUE THREAD

**Issue by EtheranNebel** [ng-select/ng-select#945]
Hello,

(Sorry for my language, I dont speak well english).

I have a problem with the library. The themes are not applied to the component.
The select are invisible on the page, but the placeholder appears, and the option too, when i click on the placeholder.
I tried to add the theme in angular.json file, in the scss file of the component, in the scss file of the app... Nothing works.

I think i reproduce the problem here : https://stackblitz.com/edit/angular-nl5uav (but without data, I start in Angular...)

And there is a screenshot by my project : 
![bug-ng-select](https://user-images.githubusercontent.com/32545408/48442226-e436c600-e78d-11e8-9895-95b2438e568e.PNG)

 - OS: Windows 10
 - Browser : Chrome and Opera

Thank you in advance for your answers

**Comment by EtheranNebel** [comment]
apparently, the import works only in the styles.scss, not in angular.json... it was the last location where i dont tried... and its work ! 
Sorry for the disturbance

**Comment by varnastadeus** [comment]
it works both including in `styles.scss` or in `angular.json`.
```json
"styles": [
    "src/styles.scss",
    "node_modules/@ng-select/ng-select/themes/default.theme.css"
],
```

**Comment by wedeleon** [comment]
try to add in your component

@Component({
  selector: 'app-search',
  templateUrl: './search.component.html',
  styles: ['node_modules/@ng-select/ng-select/themes/default.theme.css']
})
