### ISSUE TITLE
Option to disable opening on right click

### ISSUE THREAD

**Issue by MaddMugsy** [ng-select/ng-select#948]
I'm trying to use ng-select in combination with a context menu.  The problem I'm having is that ng-select opens up regardless of which mouse button is used to click it.  I'd like to disable opening on right mouse click (or anything but left mouse) so I can display the context menu when the RMB is clicked.

I may be blind, but I don't see any way of doing this currently, except maybe overriding the prototype for the handleMousedown function, which is not ideal.

It would be great if there could be a simple way to either: 
a) disable the right mouse button via a toggle in an Input API, or
b) catch an event that's raised somewhere to tell it to ignore the mouse click if it's not the LMB.

Please let me know if there is already a way to do this.

Thanks!

**Comment by aks1994** [comment]
@MaddMugsy did you ever find a solution to this?

**Comment by aks1994** [comment]
Can this issue be reopened, it has gone stale? And can #1379 be merged?

**Comment by anjmao** [comment]
Hi, somebody test PR https://github.com/ng-select/ng-select/pull/1379 with a fix to this issue. I remember I changed from click to mousedown event on purpose since it coused over issues.

**Comment by aitorbelike** [comment]
We need this please!

**Comment by pavankjadda** [comment]
This is implemented and closed as part of #2412
