### ISSUE TITLE
Hide 'clear all' button but leave ability to remove items one by one via backspace

### ISSUE THREAD

**Issue by Serg-Mois** [ng-select/ng-select#949]
**Is your feature request related to a problem? Please describe.**
Hello, in multiple mode I need ability to remove single items by backspace but 'clear all' button should not be visible.

**Describe the solution you'd like**
When multiple mode is enabled - if 'clearable' property is set to false, and clearOnBackspace is set to true - 'clear all cross' in the right side is hidden, but user can remove single item using backspace button.

So here:
https://github.com/ng-select/ng-select/commit/af79a45caa26f78b42349af862af513b1237d0c9
should be:

if (this.filterValue || **(!multiple** && !this.clearable) || !this.clearOnBackspace || !this.hasValue) {

template example:
```
<ng-select>
(add)=...
(remove)=...
[multiple]="true"
[clearable]="false"
[clearOnBackspace]="true"
</ng-select>
```

**Comment by varnastadeus** [comment]
you can hide clear button simply by css

**Comment by RanjeetEppa18** [comment]
Can some provide CSS for this?

**Comment by bobsyourgrannie** [comment]
css to clear is:

```
.ng-clear-wrapper {
  display: none;
}
```
