### ISSUE TITLE
Class ng-has-class applying incorrectly 

### ISSUE THREAD

**Issue by abhi747** [ng-select/ng-select#950]
Class ng-has-class is applying incorrectly to parent div of ng-select placeholder, i.e it is getting applied even when the ngModel of the ng-select input is empty. Because of this the transition animation on select placeholder when in focus 
![untitled](https://user-images.githubusercontent.com/39051251/48542539-6ede0900-e8e5-11e8-92ad-e2fbb4cf674c.png)
is not working properly.

Angular: 5.0.0
ng-select: 2.0.0

**Comment by varnastadeus** [comment]
create reproducible exmaple

**Comment by abhi747** [comment]
Got the issue. Actually the ngModel value was empty string instead of null/ undefined. So ' ng-has-class' was getting applied.
