### ISSUE TITLE
Dropdown position shifted if body height is set to 100%

### ISSUE THREAD

**Issue by imkremen** [ng-select/ng-select#955]
**Describe the bug**
If `html` and `body` height is set to 100% dropdown position is shifted

**Reproducbile example**
https://ng-select-xqgl9y.stackblitz.io/

**Expected behavior**
The position and width of the dropdown should be correct.

**Desktop (please complete the following information):**
 - OS: Window 10
 - Browser Chrome
 - Version 70

**Additional context**
Adding `position: relative` to `body` doesn't help.

**Comment by imkremen** [comment]
This is due to the scrollbar on the `body`, caused when calculating the dropdown position.

**Comment by SaberOuarezzamen** [comment]
Hi, I'm having the same issue.
I've added `position: relative` to `body` but still not working.
Is there any update about this issue ?

**Comment by imkremen** [comment]
@SaberOuarezzamen my pull request still not approved
