### ISSUE TITLE
Select allows duplicates when using custom server side search

### ISSUE THREAD

**Issue by talynone** [ng-select/ng-select#956]
**Bug Description**
Select allows duplicates when using custom server side search.

**Reproducible example**
[ Custom server-side search](https://ng-select.github.io/ng-select#/filter)

**To Reproduce** 
1. Go to https://ng-select.github.io/ng-select#/filter
2. Scroll down to 'Custom server-side search'
3. Type in 'Karyn Wright' and select.
4. Repeat step 3 and it keeps adding the same person to the list 

**Expected behavior**
Do nothing/disallow the duplicate item select/add. (Kendo's multi select clears the original item, but I prefer doing nothing).

**Desktop:**
 - OS: Windows 10 x64 Build 1803
 - Browser Chrome
 - Version  70.0.3538.77 (Official Build) (64-bit)

**Comment by varnastadeus** [comment]
this was fixed with #982
