### ISSUE TITLE
Add term sticky on the bottom option

### ISSUE THREAD

**Issue by sircon** [ng-select/ng-select#961]
**Is your feature request related to a problem? Please describe.**
In our use case of ng-select we use autocomplete to populate the dropdown but sometimes the search term has many variations and the user wants to add exactly what they wrote down. In this scenario the `Add item` is too far down the list and a bit annoying.

**Describe the solution you'd like**
It would be nice to have an options for the `ng-tag-tmp` template to always show on the bottom like the `ng-footer-tmp` does.

**Describe alternatives you've considered**
We tried to use the `ng-footer-tmp` as the template to add a new tag, and it works in theory (with some styling and hacking) but this template is missing the `let-searchTerm`.

**Comment by varnastadeus** [comment]
I think this can be closed with #965
