### ISSUE TITLE
Same values selectable multiple times with typeahead

### ISSUE THREAD

**Issue by harryy2510** [ng-select/ng-select#962]
**Description**
1. When selecting multiple values in typeahead, and clearing the search, same value is displayed again and can be selected multiple times. 
2. Even if hideSelected is set to true, it will not hide the already selected option.

**Reproducbile example**
[Example](https://ng-select.github.io/ng-select#/filter) In the last example, it can be reproduced

**To Reproduce** 
Steps to reproduce the behavior
1. Go to last example 'Custom server-side search'
2. Clear all selected options
3. Search for 'Karyn'
4. Select 'Karyn'
5. Search for 'Karyn' again. Wait for results to come up. And clear search and again wait for results to come up.
6. You can see 'Karyn' again. Now we have two selections with same objects.
7. Clear both selections and wait for results to come up. Now we have two 'Karyn' in the dropdown.

**Screenshots**
<img width="722" alt="screenshot 2018-11-22 at 4 53 40 pm" src="https://user-images.githubusercontent.com/7416971/48900218-d5c86880-ee77-11e8-8e73-f11e0f44d8da.png">

**Comment by sircon** [comment]
@harryy2510 this is a duplicate from #956
