### ISSUE TITLE
Error when using ngModel in Angular 7.0.3 inside formGroup 

### ISSUE THREAD

**Issue by cnschwarz** [ng-select/ng-select#963]
**To Reproduce** 
Steps to reproduce the behavior (if example is not provided):
1. Use ng select multiple inside a form group
This is the code I am using based on the multiple demo published:
<img width="282" alt="screen shot 2018-11-22 at 14 10 30" src="https://user-images.githubusercontent.com/19342760/48904945-6eeb8500-ee60-11e8-81a6-af585dc58096.png">

2. Publish your status: the first error message appears :
<img width="849" alt="screen shot 2018-11-22 at 14 08 07" src="https://user-images.githubusercontent.com/19342760/48904902-3c418c80-ee60-11e8-9dce-3ed7c757a8d3.png">

3. Change the code and use formControlName attribute instead of ngModel, of course such a formcontrol has to be created in order to be valid. 

4. The code looks now like this: 
<img width="280" alt="screen shot 2018-11-22 at 14 18 40" src="https://user-images.githubusercontent.com/19342760/48905334-942cc300-ee61-11e8-8006-37b13d99956b.png">

5. After publishing the following error message is shown 
<img width="819" alt="screen shot 2018-11-22 at 14 17 47" src="https://user-images.githubusercontent.com/19342760/48905356-a1e24880-ee61-11e8-889f-aa0a488b957d.png">

**Expected behavior**
I can integrate ng-select into my existing fromGroup and use it as a normal formControl element.

If you have a workaround or another solution how I can get this to work I would really appreciate it.

**Comment by varnastadeus** [comment]
https://github.com/ng-select/ng-select/blob/master/demo/app/examples/reactive-forms.component.ts please look at reactive forms example to setup it correctly
