### ISSUE TITLE
Material theme bottom border invisible at lower zoom levels 

### ISSUE THREAD

**Issue by BaluVyamajala** [ng-select/ng-select#969]
NgSelect with Material theme , bottom border is invisible at zoom level lower than 80% 

Its evident even in the demo site, so, I am guessing its probably known behavior, however I would like know what is best approach to get around this? should I increase border width from 1 px to 2 px or something?

Tto replicate, Goto Link https://ng-select.github.io/ng-select#/data-sources 
Set zoom to lower than 80% in chrome browser.

**Comment by varnastadeus** [comment]
`border-width: thin;` should probably fix the issue
