### ISSUE TITLE
hideSelected only working for when multiple is true, but not for multiple is false.

### ISSUE THREAD

**Issue by nikkonduru88** [ng-select/ng-select#970]
**Describe the bug**
When multiple is false and hideSelected is true, selected item is not hidden. It still shows up in the dropdown. But when multiple is true and hideSelected is true, it works as expected. Selected items are hidden from the dropdown. Is this expected or error?

**Expected behavior**
Hide selected should work regardless of multiple flag. 

**Desktop (please complete the following information):**
 - OS: macOS High Sierra
 - Browser: Chrome
 - Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by petersandor** [comment]
This is still happening in version `2.15.2`. Documentation doesn't suggest that `hideSelected` works only when `multiple` is set to `true`.

**Comment by shyamal890** [comment]
This used to work in `2.1.0`. I can confirm this no longer works in `2.15.2` or `2.15.3`

One can change the versions and check here: https://stackblitz.com/edit/ng-select-hide-selected
