### ISSUE TITLE
Make multi select item disable not deletable

### ISSUE THREAD

**Issue by mike9ar** [ng-select/ng-select#971]
I have a problem when I mark an item as disabled. Even disabled, user can delete it with clear X button or backspace, there are a way to avoid this?

![gif_demo](https://user-images.githubusercontent.com/22224714/49195666-cf9a2680-f366-11e8-8683-1198ebba4f9f.gif)

(This doesn't work for backspace or clear button)
#340

**Comment by JayceeZ** [comment]
Yes, same issue was spotted by our team,
for me that is a bug because a Disabled entry should not be removable nor add-able by the Users. (informative entries that are read-only)
