### ISSUE TITLE
bindLabel filter

### ISSUE THREAD

**Issue by viandanteoscuro** [ng-select/ng-select#972]
Hi to all,

Is it possible to filter the bindLabel option?

Some like this: bindLabel="name | myfilter"

At the moment it is not possible... is there any workaround?

If i use the custom template, all works fine but when i select the option, the label is ''

Thanks

Massimo

**Comment by varnastadeus** [comment]
why would you need filter on bindLabel? `bindLabel` is string displayed in select

**Comment by viandanteoscuro** [comment]
Yes, but i have very long strings such "ABC/FGR/HODF/KGFUF/DJFID.Nfo" and i need to display only DJFID.

At the moment i use a custom filter to do that. If i can't apply a filter i must do this transformation before, but i prefer to apply the filter if possible...

Thanks

Massimo

**Comment by varnastadeus** [comment]
No, you can't use it on `bindLabel` since it is not actual value. It may be resolved with #532, but for now just use templates
