### ISSUE TITLE
Expose the sugestions through an event

### ISSUE THREAD

**Issue by kavi87** [ng-select/ng-select#973]
When searching for an element, I'd like to retrieve the list of sugestions that match the search filter.

Why ? I'd like to offer an alternative to the user if the result is empty.

**Comment by ratiuandreea** [comment]
Is there a way to make loading specific to an input? I have to loop through an array and show 8 inputs let's say. This searchLoading is general for any input and the loading icon appears on each of the 8 inputs from the for loop.

**Comment by benj0c** [comment]
Features like this one, you should put in changelog file as breaking changes or am I wrong?
