### ISSUE TITLE
add Output async

### ISSUE THREAD

**Issue by blhasan** [ng-select/ng-select#974]
Hi,
I have problems with adding asynchronous tags.

![image](https://user-images.githubusercontent.com/8158194/49294733-18abc100-f4b4-11e8-818c-05c30cc3c135.png)

![image](https://user-images.githubusercontent.com/8158194/49294750-22cdbf80-f4b4-11e8-8dfa-55f62831b518.png)

angular: 6.0.0
rxjs: 6.0.0
import 'rxjs/add/observable/of';
import { Observable } from 'rxjs';
...
public addTagNowRef: (title)=>void;
constructor(...){
 this.addTagNowRef = this.addTagNow.bind(this); 
}
.....
addTagNow(title:string){
  console.log('ADD');
  this.tagLoading = true;
  const tagData:Tag = new Tag(null,this.associateId, 'Associates', title);

  this.tagService.save(tagData).subscribe(
    data => {
      if (data["result"]["code"] == 200) {
        this.tagLoading = false;
        return Observable.of({'title':data["result"]["data"]['title'], 'tag': true});
      } else {       
        this.tagLoading = false;
        throw new ServerRequestError(data["result"]["code"],data["result"]["message"]);
     }
    },
    error => {
      this.tagLoading = false;
      throw error;
    }
  );

 template:

          <ng-select [items]="tagTitelsObj"
          (clear) = "onClear($event)"
          (remove) = "onRemove($event)"
          (focus) = "onTagsFocus()"
          (blur) = "onTagsBlur()"
         
          bindLabel="title"
          bindValue="title"
          [multiple]="true"
          [addTag]="addTagNowRef"
          placeholder="Tags"
          [loading]="tagLoading"
          [(ngModel)]="tagTitels"
          (change)="onChange($event)"
          [isOpen] = "false">
        </ng-select>

**Comment by blhasan** [comment]
"b" will not be added

**Comment by varnastadeus** [comment]
create reproducible example, pasting your code here doesn't help
