### ISSUE TITLE
Not able to select an option in dropdown with ShadowDom in IOS devices

### ISSUE THREAD

**Issue by BaluVyamajala** [ng-select/ng-select#976]
When Encapsulation ShadowDom is used , though styles are cascaded properly, not able to select option, i.e even when an option is selected, drop down is closed as if it is clicked outside.  so, something is not cascaded or some styles are boken, making the dropdown pannel close without selection. Not able to figure it out , spend a lot of time. 

We can re-produce by 
1. Create a new Angular project (7)
2. install ng-select
3. add encapsulation: ViewEncapsulation.ShadowDom in @Component decorator in app.component
4. import ng-select theme in app.component.scss
5. Use any ng-select in html
6. build and deploy it. 
7. works fine in web , android, but not in any browser of IOS devices, tried in Iphone 6S Chrome, safari.

Overall some style in ng-select is breaking the encapsulation to go all over.

**Comment by varnastadeus** [comment]
#968 this is probably related

**Comment by BaluVyamajala** [comment]
@varnastadeus  I will be very happy if it solves the problem. looks like its merged, can I expect it to be released soon?

**Comment by BaluVyamajala** [comment]
Just an update, 
 Since the actual package.json for ng-select is in src/ folder, I couldn't refer to github branch directly in my project package.json. So, I copied entire project source code into my application and removed from node module and I can confirm that fix #968  indeed solve the problem with ShadowDom. 

Thanks for the bug fix and thanks for building such an awesome module!!
