### ISSUE TITLE
incoherent state between selected item in model and dropdown selection

### ISSUE THREAD

**Issue by wniar** [ng-select/ng-select#977]
**Describe the bug**
When i get items from web api on route param change, selection disappear from dropdown list

**Reproducbile example**
I try reproduce issue but this seams occure only when you get request from web api (i use .net core for backend)

https://stackblitz.com/edit/angular-jvtn1x

**To Reproduce** 
Steps to reproduce the behavior (if example is not provided):

1. Select 'Poland' from the list of country
2. Select some city/cities from list
3. Close dropdown list
4. Open dropdown list and select another/deselect/remove city

Now you should have incoherent state between selected item in model and dropdown selection

**Expected behavior**

**Screenshots**
![issue](https://user-images.githubusercontent.com/42281980/49342952-d0ca9c80-f661-11e8-8cea-17bec7013c55.jpg)

**Desktop (please complete the following information):**
 - Browser chrome
 - Version 70.0.3538.110

Perhaps this issue is releted with #959

**Comment by varnastadeus** [comment]
I don't see any problem in your provided example

**Comment by wniar** [comment]
@varnastadeus  like i say, issue not occure in m provided example. I add example that you can see what i do with yours select box and you can chack i use it properly. But to reproduce issue you need add to my code real web api calls. My screenshot show what heppen when you use data from web api request. If you need more information i'm ready to help.

**Comment by wniar** [comment]
@varnastadeus example is ready. After adding angular-in-memory-wep-api you can easly reproduce issue. For reproduce fallow below steps:

1. Select 'Poland' in country select box
2. Select 'Stetin', 'Warsaw' and 'Cracow' in cities select box
3. Close dropdown list (route param will update)
4. Remove 'Warsaw' clicking on 'x'
5. Open dropdown list

You should have unselected all cities. 

Also you can unselect 'Warsaw' from dropdown list (after few milliseconds other selected cities should dissapear). This is alternative for step 4 and 5.

Hope this help.
