### ISSUE TITLE
Changing option label doesn't update selected option label (regression from somwhere after 2.1.0)

### ISSUE THREAD

**Issue by devel112** [ng-select/ng-select#980]
**Describe the bug**
The selected value name doesn't update if the selected option names are changed. (This worked in 2.1.0).

**Reproducbile example**
Select Vilnius, then press Toggle name
[Example](https://stackblitz.com/edit/ng-select-jcxysw) 2.1.0 - works
[Example](https://stackblitz.com/edit/ng-select-dbqsye) 2.13.0

**To Reproduce** 
Steps to reproduce the behavior
1. Select Vilnius, then press Toggle name in the examples

**Expected behavior**
Also update the name of the selected value like in 2.1.0

**Comment by varnastadeus** [comment]
I will take a look, thanks
