### ISSUE TITLE
when typing 'ng','nng' was displayed using safari(iphone6sp).

### ISSUE THREAD

**Issue by mail4regist** [ng-select/ng-select#981]
<img width="356" alt="qq20181204-210101 2x" src="https://user-images.githubusercontent.com/12605438/49443682-04dfc200-f808-11e8-9f49-2951643c8963.png">

when typing 'ng','nng' was displayed using safari(iphone6sp).

**Comment by varnastadeus** [comment]
There simple input inside without any magic so I don't have any answer for, maybe some safari bug 🤔
