### ISSUE TITLE
Multiple autocompelte select in the same page.

### ISSUE THREAD

**Issue by VigneshVaidyanathan** [ng-select/ng-select#983]
I am trying to create an autocomplete using the select and more than one autocomplete selects are present in the same page. The autocompletes are working fine and the results are properly shown.

The problem however is that the number of calls for the resource is equal to the number of the autocompletes present in the page, though I am actually using only one. This is unnecessary requests and would like to know how to get rid of them.

Please let me know based on the code that I have pasted below. Thanks

`<div class="form-group small auto-margin">
                            <ng-select #inventory="ngModel" class="small" [ngModel]="item.materialName" [clearable]="false"
                              [name]="'material-' + item.uniqueId" required [items]="materialAutocomplete | async"
                              (focus)="onSelectSubCMaterialFocus()" (blur)="onSelectBlur(item)" [typeahead]="materialInput"
                              (change)="onSubcontractorMaterialSelect($event, item, room)"></ng-select>
                            <div *ngIf="inventory.invalid && (inventory.dirty || inventory.touched) && (item.inventory === '' || item.inventory === undefined || item.inventory === null)">
                              <div class="help-block form-text with-errors form-control-feedback feedback-icon">
                                <i class="fa fa-times"></i>
                              </div>
                              <div *ngIf="!item.isAlreadySelected" class="help-block form-text with-errors form-control-feedback">Select
                                the Material</div>
                              <div *ngIf="item.isAlreadySelected" class="help-block form-text with-errors form-control-feedback">The
                                same material is already selected in the list. Please add/reduce quantities from there.</div>
                            </div>
                          </div>`

`this.materialAutocomplete = concat(
      of([]),
      this.materialInput.pipe(
        debounceTime(200),
        distinctUntilChanged(),
        tap(() => this.isMaterialAutocompleteLoading = true),
        switchMap(term => this.projectService.getMaterialForSearch({
          inventoryType: this.selectedType,
          searchTerm: term
        }).pipe(
          catchError(() => of([])),
          tap(() => this.isMaterialAutocompleteLoading = false)
        ))
      )
    );`

**Comment by varnastadeus** [comment]
create reproducible example

**Comment by gabrielbusarello** [comment]
If you still having that problem, you can use `share()` in your subject.
With `share()` you can share obviously the results with another subject, this solved my problem.
You can learn more here:
[share](https://www.learnrxjs.io/operators/multicasting/share.html)
