### ISSUE TITLE
Removing all selected options in ng-select-multiple does not close dropdown

### ISSUE THREAD

**Issue by iantrudell** [ng-select/ng-select#984]
**Describe the bug**
With an ng-select-multiple, if you have one or more options selected, AND have the dropdown open, if you click the "close all" X, it will remove all the selected options, but will not close the open dropdown, resulting in a "floating" dropdown.

**Reproducible example**

**To Reproduce** 
1. Create multi-select
2. Select 1 or more options
3. Open the dropdown as if you were selecting another option
4. Click the "remove all" x to remove all currently selected options
5. The dropdown will be floating and still open.

**Expected behavior**
The dropdown should close if it is open when the "close all" x is clicked.

**Screenshots**
![open-multi](https://user-images.githubusercontent.com/33202657/49611383-653d4380-f96f-11e8-8b8e-b0b4e3079bb4.PNG)
![open-multi2](https://user-images.githubusercontent.com/33202657/49611384-68383400-f96f-11e8-88c2-4007229fb573.PNG)
![open-multi3](https://user-images.githubusercontent.com/33202657/49611471-a0d80d80-f96f-11e8-940f-0baea2b75d8f.PNG)

**Desktop (please complete the following information):**
 - OS: Any
 - Browser: Any

**Comment by iantrudell** [comment]
If not closed, then "reattached" to the bottom of the main input area so there's not a "phantom gap" in between the main area and the dropdown after options are removed.

**Comment by imkremen** [comment]
I think it possible to recalculate position of dropdown in this case
