### ISSUE TITLE
function passed to groupBy loses context

### ISSUE THREAD

**Issue by maxkorz** [ng-select/ng-select#987]
**Describe the bug**
`this` in function passed to groupBy points to `ItemsList` class, which makes it impossible to implement custom logic in some cases.

**Reproducbile example**
https://stackblitz.com/edit/ng-select-ldnh2t?file=app/app.component.ts

**Comment by varnastadeus** [comment]
user arrow function https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

**Comment by maxkorz** [comment]
@varnastadeus what?

**Comment by varnastadeus** [comment]
did you event read the article?

**Comment by maxkorz** [comment]
@varnastadeus what arrow functions have to do with class methods and passing methods to Angular Component?

**Comment by varnastadeus** [comment]
read last article I provided and you will understand, it is explained there

**Comment by varnastadeus** [comment]
I already told you how to fix your issue and added article which explains reasoning behind that fix. What else do you want?

**Comment by maxkorz** [comment]
@varnastadeus I want you to try to fix the issue in the demo that I provided in the first message. Then you will see that you're wrong and that the problem is with the plugin.
