### ISSUE TITLE
Lock Selected Choices

### ISSUE THREAD

**Issue by DzmVasileusky** [ng-select/ng-select#989]
**Is your feature request related to a problem? Please describe.**
I was using angular-ui/ui-select in times of Angular.js.
It has an opportunity to lock as selected options conditionally.
It's very usefull when one field is connected to another. 
For example:
first select: Beast, Fish, Bird
second select: Wolf, Bear, Hair, Salmon, Trout, Bass, Crow, Pegeon, Seagull.
If user has selected Salmon I want to lock selection of Fish for the first selectbox. 
There are a plenty of buisness-specific real use cases like that.

**Describe the solution you'd like**
Add `[lockOptions]` input which would accept a function `(option) => boolean` which determine if we should select and lock an option. 
Those options should became not removable.

**Describe alternatives you've considered**
Don't know how to do it right now with the library

**Comment by DzmVasileusky** [comment]
Figured out that it can be done with custom templates
```
ng-template(let-clear="clear", let-item="item", ng-label-tmp)
    span.ng-value-icon.left(*ngIf="!isItemLocked(item)", (click)="clear(item)") ×
    span.ng-value-label {{item}}
```

**Comment by jziggas** [comment]
The above code wouldn't prevent a backspace from removing the item. I am also wondering how to lock a choice? I noticed that setting `item.disabled = true` hides the clear button on an item, but then backspace will still remove the item and then the item shows up as disabled and unselectable in the dropdown.
