### ISSUE TITLE
ng-value-label should have a (click)="$event.stopPropagation()"

### ISSUE THREAD

**Issue by davidaah** [ng-select/ng-select#99]
Please fill below information if issuing a bug report. 
### Expected behaviour
Clicking a label name should not open the dropdown menu for multi select

Suggest adding `(click)="$event.stopPropagation()"` to `ng-value-label` as in https://github.com/ng-select/ng-select/commit/3609a108f82b055127e17a8177f70702510487dc#diff-68265c9310f2ae9e060ab288eb5e8491R8

### Actual behaviour
Clicking a label name opens the dropdown menu for multi-select

### More Info
ng-select version: 0.4.1

browser: Chrome 61

reproducable in demo page: YES

**Comment by anjmao** [comment]
I was thinking about this before but there are cases like this one:
<img width="430" alt="multifull" src="https://user-images.githubusercontent.com/3028012/31875131-78538e3e-b7d5-11e7-85ba-64e519bcebd2.png">

In this case multiselect is full and there is almost no space where to click to open it, this is why this behaviour is a way to go :)

**Comment by davidaah** [comment]
Thanks, understood! For now I have overridden the behavior using templates
