### ISSUE TITLE
Change Detection OnPush in parent component issue

### ISSUE THREAD

**Issue by jarradf123** [ng-select/ng-select#995]
**Describe the bug**
UI/Model issues when using ChangeDetectionStrategy.OnPush in parent component.

Initially selecting the ng-select component doesn't open the items, then selecting off the component and back successfully opens the items. Selected model item is not updated etc.

Similar to [https://github.com/ng-select/ng-select/pull/140/commits/2a18a61a5d1b3a3cd257e070b76390ee471e8e08] and the same can be achieved by calling detectChanges in the appropriate events (blur/focus) etc. but even still the UI doesn't work as expected.

**Reproducbile example**
[https://stackblitz.com/edit/angular-gasp12]

**To Reproduce** 
Steps to reproduce the behavior (if example is not provided):
1. Click on the ng-select component (will not open)
2. Click off the component
3. Click on the ng-select component (will open)
4. Click on 'Test 2' item (no change)
5. Click on the "open/close" arrow (selected item will update)

**Expected behavior**
Expect the UI to operate as if changes were automatically detected, and selections to be updated etc.

**Desktop (please complete the following information):**
 - OS: Win 7
 - Browser Chrome 
 - Version 70.0.3538.110 (Official Build) (64-bit)

Cheers

**Comment by varnastadeus** [comment]
why are you talking about `ChangeDetectionStrategy.OnPush` if your `ChangeDetectorRef` is detached?

**Comment by jarradf123** [comment]
Yea sorry, just a copy paste error on my behalf. My issue is definitely occurring when the ChangeDetectorRef is detached. Is there a way to force a detectChanges on the ng-select component?

**Comment by varnastadeus** [comment]
If you are using detached mode you need to trigger change detection yourself
